-- France deep-dive content backfill: page-level fields, stats,
-- cards, steps, portal, penalty table, and lifecycle pills.
-- English only for now; ES/DE/FR follow.

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-20' FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Decentralised CTC (Y-model)', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. PA accreditation lists, penalty enforcement posture, and technical specifications continue to evolve as the September 2026 go-live approaches — confirm current requirements directly with DGFiP, AIFE, or your chosen Plateforme Agréée before building an integration.', 'France''s reform runs two parallel tracks — structured B2B e-invoicing and a separate "e-reporting" obligation for everything e-invoicing doesn''t cover (B2C, cross-border). Both are phased by company size.', 'France is unusually flexible on syntax — three different formats are all legally acceptable, as long as they carry the same underlying EN 16931 data.', 'France''s "Y-model" is deliberately decentralised: unlike Italy''s single government clearance system, France licenses many private platforms to do the actual invoice exchange, with one shared public directory tying it all together.', 'There''s no single "sign up here" government portal for invoicing itself — registration happens through your chosen PA, which then notifies the national directory on your behalf.', 'The Finance Law for 2026 raised the statutory fines considerably — but DGFiP has publicly signalled a lenient early-enforcement approach.' FROM countries WHERE name_en = 'France';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Y-model', 'Compliance model');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '3 formats', 'Factur-X / UBL 2.1 / CII');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '100+', 'Accredited PAs (Jan 2026)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '10 yrs', 'Archive requirement');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '€50', 'Fine per non-compliant invoice');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Accepted formats', '[["Hybrid", "Factur-X (PDF/A-3 + embedded CII XML)"], ["Structured XML (Peppol-ready)", "UBL 2.1"], ["Structured XML (complex B2B)", "UN/CEFACT CII"], ["Plain PDF / email attachment", "No longer valid from Wave 1"]]', 'Factur-X is the most distinctly "French" choice — the embedded PDF keeps a human-readable copy for staff who still open invoices by eye, while the XML layer does the machine processing.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Governing standard', '[["European semantic model", "EN 16931"], ["National technical spec", "AFNOR XP Z12-012"], ["Covers", "Formats, codelists, business rules, lifecycle statuses (XP Z12-013)"], ["Ruleset size", "~112 Factur-X 1.0.06 rules"]]', 'AFNOR XP Z12-012 is the master reference — it defines the semantic model and syntax for every accepted format plus the e-reporting XML and lifecycle status messages, so any PA or in-house build should validate against it directly.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Mandatory identifiers', '[["SIREN", "9-digit legal entity ID"], ["SIRET", "14-digit establishment ID (SIREN + 5)"], ["Reception channel", "Recipient''s chosen PA, per directory entry"]]', 'Every invoice must resolve to a correct SIRET-level routing address in the national directory — get this wrong and the PA can''t deliver the invoice, regardless of whether the XML itself is valid.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Archiving', '[["Retention period", "10 years"], ["Format to retain", "Original electronic format, guaranteed integrity"]]', 'Archiving the PDF rendering of a Factur-X invoice isn''t sufficient on its own — the original structured file (with embedded XML) is what must be preserved for the full 10 years.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Network architecture', '[["Model", "Decentralised CTC (\"Y-model\")"], ["Invoice exchange", "Via a certified Plateforme Agr\u00e9\u00e9e (PA)"], ["Central directory", "PPF (Portail Public de Facturation) \u2014 annuaire"], ["Software-only option", "Solution Compatible (SC) \u2014 must still route via a PA"]]', 'The PPF itself doesn''t exchange invoices anymore — it''s the national directory and routing/reporting concentrator. All actual sending and receiving of structured invoices happens through your chosen PA (or an SC layered on top of one).', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'E-reporting cadence', '[["Scope", "B2C sales & cross-border transactions"], ["Legal basis", "CGI Article 290"], ["Standard VAT regime cadence", "Within 7 days, by 10-day period"]]', 'E-reporting is not real-time — don''t over-engineer for instant transmission. It runs on a 10-day-period cycle with a 7-day submission window, distinct from the invoice-level lifecycle statuses above.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Platform continuity protections', '[["Minimum service continuity", "1 year after switching PA"], ["PA connectivity requirement", "Must support Factur-X, UBL, and CII"]]', 'If you switch providers, your former PA is legally required to keep serving you for at least a year — a safeguard against being locked into a platform that stops fitting your needs.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🕊️ Early enforcement leniency', NULL, NULL, 'DGFiP Director General Amélie Verdier confirmed at the May 2026 E-Invoicing Day that sanctions won''t be applied automatically from day one — businesses demonstrating genuine implementation effort get a "right to make mistakes" during the initial rollout, with softened enforcement expected to continue at least until January 2027.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⏳ Platform-connection grace period', NULL, NULL, 'If DGFiP finds you''re not connected to an accredited platform for receiving e-invoices, you get a formal notice and three months to register with a PA before the €50/invoice fine regime kicks in.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📎 Legal basis', NULL, NULL, 'Article 123 of Law No. 2026-103 (19 February 2026) amends CGI Articles 289 bis, 289 E, 290, 1737 and 1788 D — this is the citation to check if you need the primary source rather than a summary.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, (SELECT COUNT(*) FROM deep_dive_steps ds2 JOIN countries c2 ON c2.id=ds2.country_id WHERE c2.name_en='France') FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Choose a Plateforme Agréée (PA)', 'Select from the DGFiP''s published list of accredited platforms (100+ as of January 2026), based on format support, integration with your accounting software, and whether it also handles e-reporting. A "Solution Compatible" (SC) can sit on top of a PA if you prefer your existing software, but it cannot connect to the directory directly.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, (SELECT COUNT(*) FROM deep_dive_steps ds2 JOIN countries c2 ON c2.id=ds2.country_id WHERE c2.name_en='France') FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Provide your company''s SIREN/SIRET details', 'Your PA collects your legal entity identifiers, reception channel preference, and intended e-invoicing go-live date as part of onboarding.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, (SELECT COUNT(*) FROM deep_dive_steps ds2 JOIN countries c2 ON c2.id=ds2.country_id WHERE c2.name_en='France') FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm your directory (annuaire) entry', 'Review and confirm your company information, chosen reception channel (your PA), e-invoicing address, and service start date. Your PA transmits this to AIFE (Agence pour l''Informatique Financière de l''État) and DGFiP, who populate the national directory used to route invoices to you.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, (SELECT COUNT(*) FROM deep_dive_steps ds2 JOIN countries c2 ON c2.id=ds2.country_id WHERE c2.name_en='France') FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Test format generation and lifecycle status handling', 'Validate that your ERP or the PA''s tooling can generate compliant Factur-X, UBL, or CII output, and that your systems correctly consume and emit lifecycle statuses (Deposited, Sent, Received, Approved/Rejected, Payment Due/Done).');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, (SELECT COUNT(*) FROM deep_dive_steps ds2 JOIN countries c2 ON c2.id=ds2.country_id WHERE c2.name_en='France') FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Set up e-reporting for B2C and cross-border sales', 'Configure separate transmission for transactions outside the domestic B2B scope — these follow the 10-day-period/7-day-window e-reporting cadence rather than invoice-by-invoice lifecycle tracking.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, (SELECT COUNT(*) FROM deep_dive_steps ds2 JOIN countries c2 ON c2.id=ds2.country_id WHERE c2.name_en='France') FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Keep your directory entry current', 'If you switch PA or change your reception channel, update the directory promptly — your former PA must maintain a minimum one year of continuity, but the directory itself needs to reflect the change so invoices route correctly.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://chorus-pro.gouv.fr', 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Chorus Pro / PPF');

INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Invoice not issued/received electronically', '€50 per invoice', '€15,000');
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Missing e-reporting transmission', '€500 per transmission', '€15,000');
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Not connected to an accredited platform (after 3-month notice)', '€500 → €1,000 → €1,000/quarter', '—');

INSERT INTO deep_dive_lifecycle_intro (country_id) SELECT id FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_intro_translations (country_id, lang, title, intro_text) SELECT id, 'en', 'Lifecycle status exchange', 'Every invoice must carry status updates through its life — this is what lets DGFiP pre-fill VAT returns in near real time.' FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_statuses (country_id, sort_order, is_special) SELECT id, 0, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_status_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses), 'en', 'Deposited');
INSERT INTO deep_dive_lifecycle_statuses (country_id, sort_order, is_special) SELECT id, 1, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_status_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses), 'en', 'Sent');
INSERT INTO deep_dive_lifecycle_statuses (country_id, sort_order, is_special) SELECT id, 2, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_status_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses), 'en', 'Received');
INSERT INTO deep_dive_lifecycle_statuses (country_id, sort_order, is_special) SELECT id, 3, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_status_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses), 'en', 'Approved');
INSERT INTO deep_dive_lifecycle_statuses (country_id, sort_order, is_special) SELECT id, 4, 1 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_status_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses), 'en', 'Rejected');
INSERT INTO deep_dive_lifecycle_statuses (country_id, sort_order, is_special) SELECT id, 5, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_status_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses), 'en', 'Payment Due');
INSERT INTO deep_dive_lifecycle_statuses (country_id, sort_order, is_special) SELECT id, 6, 0 FROM countries WHERE name_en = 'France';
INSERT INTO deep_dive_lifecycle_status_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses), 'en', 'Payment Done');
