-- Germany milestone backfill. English only for now.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'de-xrechnung-b2g', id, '2020-11-27', 1, 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108886/eInvoicing+in+Germany' FROM countries WHERE name_en = 'Germany';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('de-xrechnung-b2g', 'en', 'XRechnung mandatory for federal public authorities (B2G)', 'Every invoice sent to a German federal ministry, state authority, or municipal body in scope must comply with XRechnung or an equivalent EN 16931-conformant format — years ahead of any B2B obligation.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'de-wachstumschancengesetz', id, '2024-03-22', 1, 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108886/eInvoicing+in+Germany' FROM countries WHERE name_en = 'Germany';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('de-wachstumschancengesetz', 'en', 'Wachstumschancengesetz (Growth Opportunities Act) passes the Bundesrat', 'The law establishing Germany''s B2B e-invoicing mandate clears its final legislative hurdle, setting the phased 2025–2028 timeline.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'de-receive', id, '2025-01-01', 0, 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108886/eInvoicing+in+Germany' FROM countries WHERE name_en = 'Germany';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('de-receive', 'en', 'Mandatory receipt of structured e-invoices', 'All German businesses, regardless of size, must be able to receive EN 16931-compliant structured e-invoices (XRechnung or ZUGFeRD) for domestic B2B transactions.', '["Confirm your accounts-payable process can accept XRechnung XML or ZUGFeRD hybrid PDFs", "A structured-invoice-capable email inbox meets the current minimum bar"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'de-issue-large', id, '2027-01-01', 0, 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108886/eInvoicing+in+Germany' FROM countries WHERE name_en = 'Germany';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('de-issue-large', 'en', 'Issuing mandate — businesses over €800k turnover', 'Businesses with prior-year turnover above €800,000 must issue structured e-invoices for domestic B2B transactions; PDF-only invoices no longer qualify for this group.', '["Confirm your ERP can generate XRechnung or ZUGFeRD 2.1+ output", "Existing EDI arrangements must become EN 16931-compliant or transition by end of 2027"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'de-issue-all', id, '2028-01-01', 0, 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108886/eInvoicing+in+Germany' FROM countries WHERE name_en = 'Germany';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('de-issue-all', 'en', 'Issuing mandate — all domestic B2B businesses', 'The issuing obligation extends to every domestic B2B business regardless of turnover, completing Germany''s phased rollout under the Growth Opportunities Act.', '["Complete rollout to any remaining domestic B2B invoicing flows", "No further transitional arrangements will apply after this date"]');
