-- Poland milestone backfill. English only for now.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-b2g-peppol', id, '2019-01-01', 1, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-b2g-peppol', 'en', 'B2G e-invoicing mandatory via Peppol', 'Public-sector invoicing runs on Peppol, entirely separate from the KSeF platform that would later handle B2B — the two systems don''t share infrastructure.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-ksef2-api-published', id, '2025-06-30', 1, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-ksef2-api-published', 'en', 'Final KSeF 2.0 API documentation and FA(3) schema published', 'The Ministry of Finance released the OpenAPI 3.0.4 specification, integration guides with C#/Java examples, .NET and Java SDKs, and the final FA(3) logical structure — replacing FA(2) and shaped by public consultation with businesses, accountants, and IT vendors.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-test-environment', id, '2025-09-30', 1, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-test-environment', 'en', 'KSeF 2.0 test environment opens', 'Integrators and businesses gain access to a sandbox for architectural planning and prototype development ahead of the mandatory rollout.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-certificates-available', id, '2025-11-01', 1, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-certificates-available', 'en', 'KSeF certificates become available', 'Taxpayers can begin applying for KSeF certificates via the Certificates and Authorizations Module (MCU) — the credential that will fully replace token-based authentication from January 2027.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-large', id, '2026-02-01', 0, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-large', 'en', 'KSeF mandatory — large taxpayers (>PLN 200m)', 'Large taxpayers with turnover above PLN 200 million became the first group required to issue B2B invoices through the Krajowy System e-Faktur (KSeF) clearance platform.', '["Integrate with KSeF via API using the FA(3) XML schema", "Set up KSeF authorisations for staff and any third-party issuers"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-all', id, '2026-04-01', 0, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-all', 'en', 'KSeF mandatory — all other VAT-registered businesses', 'The KSeF mandate extended to all remaining VAT-registered businesses in Poland (excluding micro-entrepreneurs); an invoice only carries legal force once KSeF has cleared it.', '["Confirm your invoicing system generates valid FA(3) structured invoices", "Correction notes (noty koryguj\u0105ce) are no longer valid \u2014 use KSeF''s structured correction process instead", "Add the KSeF invoice number to bank transfer references once that requirement takes effect (1 Aug 2026)"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-grace-period-ends', id, '2026-12-31', 0, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-grace-period-ends', 'en', '2026 grace period and small-invoice exception both end', 'The full-year 2026 grace period (no financial penalties for KSeF errors, regardless of a business''s mandatory start date) expires, along with the exception letting the smallest sellers (≤PLN 10,000 gross monthly invoicing) issue outside KSeF.', '["Confirm any remaining KSeF integration gaps are resolved before financial penalties begin", "If you''ve been relying on the small-invoice exception, confirm your KSeF readiness before it expires"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pl-micro', id, '2027-01-01', 0, 'https://ksef.mf.gov.pl/' FROM countries WHERE name_en = 'Poland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pl-micro', 'en', 'KSeF mandatory — micro-entrepreneurs; penalties begin', 'Micro-entrepreneurs join the KSeF mandate, and the grace period on financial penalties (up to 100% of invoice VAT for non-compliance) ends for everyone.', '["Micro-businesses: confirm KSeF integration is live well before this date", "All businesses: resolve any lingering compliance gaps before penalties apply"]');
