-- Malaysia milestone backfill. English only for now.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'my-phase1', id, '2024-08-01', 1, 'https://www.hasil.gov.my/en/e-invoice' FROM countries WHERE name_en = 'Malaysia';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('my-phase1', 'en', 'Phase 1 — businesses above RM100 million turnover', 'The largest taxpayers become the first mandatory cohort, establishing MyInvois as the national clearance platform.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'my-phase2', id, '2025-01-01', 1, 'https://www.hasil.gov.my/en/e-invoice' FROM countries WHERE name_en = 'Malaysia';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('my-phase2', 'en', 'Phase 2 — RM25 million to RM100 million', 'Mid-large businesses join the mandate.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'my-phase3', id, '2025-07-01', 1, 'https://www.hasil.gov.my/en/e-invoice' FROM countries WHERE name_en = 'Malaysia';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('my-phase3', 'en', 'Phase 3 — RM5 million to RM25 million', 'The mandate extends further down the turnover scale toward mid-sized companies.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'my-phase4', id, '2026-01-01', 0, 'https://www.hasil.gov.my/en/e-invoice' FROM countries WHERE name_en = 'Malaysia';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('my-phase4', 'en', 'MyInvois Phase 4 — turnover RM1m–5m', 'Businesses with annual turnover between RM1 million and RM5 million entered the mandate, with a relaxation period (no penalties for submission errors) extended to 31 December 2027.', '["Register for MyInvois portal or API access with LHDN", "Determine your phase using your FY2022 audited accounts or first available tax return", "Individual e-invoices are mandatory above RM10,000 \u2014 consolidated invoicing is no longer allowed for those amounts"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'my-related', id, '2026-07-01', 0, 'https://www.hasil.gov.my/en/e-invoice' FROM countries WHERE name_en = 'Malaysia';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('my-related', 'en', 'Related/subsidiary companies of RM1m+ groups', 'Businesses below RM1 million turnover that are subsidiaries or related companies of an RM1 million+ group must still comply, regardless of their own individual revenue.', '["Check group structure \u2014 related-company status can trigger the mandate even for small entities", "Register and test MyInvois integration well before the deadline"]');
