-- Malaysia deep-dive content backfill. English only for now.

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Centralised clearance (MyInvois)', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. MyInvois validation rules, phase thresholds, and penalty provisions continue to evolve — confirm current requirements directly with LHDN before building an integration.', 'Malaysia''s rollout works top-down by turnover tier, with a relaxation period running well past each tier''s formal start date.', 'Malaysia genuinely supports two serialisations of the same underlying UBL 2.1 structure — pick whichever fits your stack, not a fixed single format.', 'MyInvois is a genuine clearance platform: LHDN validates in real time and assigns identifiers before an invoice carries legal weight.', 'Getting API credentials is a genuine multi-step identity-verification process, not a self-serve signup.', 'Non-compliance ties back into Malaysia''s general Income Tax Act framework rather than a standalone e-invoicing fine schedule.' FROM countries WHERE name_en = 'Malaysia';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'UBL 2.1', 'XML or JSON');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '55', 'Mandatory data fields');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '72 hrs', 'Rejection/cancellation window');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '8', 'Supported document types');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '7 yrs', 'Archive requirement');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format', '[["Data structure", "UBL 2.1 (Universal Business Language)"], ["Accepted serialisations", "XML or JSON"], ["Digital certificate", "Mandatory, issued by a recognised Malaysian Certificate Authority"]]', 'Both XML and JSON carry the same UBL 2.1 data model — choose based on what integrates more cleanly with your existing ERP, not a compliance preference.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Mandatory data fields', '[["Field count", "55 specific data fields"], ["Covers", "Seller/buyer details, transaction items, quantities, prices, taxes, totals, payment information"], ["Reference fields", "TIN, MSIC code, tax classification"]]', 'Validation failures at LHDN fail closed — the document is rejected outright rather than accepted with a warning, so getting these 55 fields right the first time genuinely matters.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Document types (8 total)', '[["Standard types", "Invoice, credit note, debit note, refund note"], ["Self-billed variants", "Four equivalents, for self-billing scenarios"]]', 'Self-billed invoices are treated as a genuinely distinct document type set, not just a flag on the standard invoice type — plan your integration accordingly if you use self-billing.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Peppol as a separate track', '[["Managed by", "MDEC (Malaysia Digital Economy Corporation)"], ["Used for", "Cross-border and B2G invoice exchange"], ["Format difference", "MyInvois typically uses UBL 2.1 JSON; Peppol uses UBL 2.1 XML with PINT"]]', 'A business can and often does use both tracks simultaneously — MyInvois for domestic compliance, Peppol for government procurement or international clients — but they''re genuinely different protocols requiring separate handling.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'API mechanics', '[["Authentication", "OAuth 2.0, scope \"InvoicingAPI\""], ["Identity", "Taxpayer TIN + NRIC/BRN"], ["Endpoint", "POST to /api/v1.0/documents/submit"], ["Credentials", "Environment-specific \u2014 sandbox and production are separate"]]', 'Don''t reuse sandbox credentials in production or vice versa — LHDN issues distinct client ID/secret pairs for each environment via the MyInvois developer portal.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'The 72-hour window', '[["Buyer rejection request", "Within 72 hours of validation"], ["Issuer cancellation", "Within 72 hours of approval"], ["After the window", "Must issue a credit/debit note instead"]]', 'Trying to cancel outside this window returns an "OperationPeriodOver" error — plan your correction workflow around credit/debit notes as the fallback path, not cancellation.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚖️ Section 120 liability', NULL, NULL, 'Non-compliance with the e-invoicing mandate is commonly cited as exposing businesses to penalties under Section 120 of the Income Tax Act — confirm the current figures with LHDN or a Malaysian tax advisor, since general tax-offence provisions like this are periodically revised.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🧾 Consolidated e-invoices for retail/B2C', NULL, NULL, 'Retail and other high-volume B2C scenarios have a consolidated e-invoice mechanism to ease the burden of individual invoicing — worth investigating if your business handles high transaction volumes with individual consumers.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📅 Common implementation mistakes', NULL, NULL, 'Missing or incorrectly formatted TINs, using unsupported formats, failing to handle rejections promptly, and neglecting to archive validation responses alongside the original invoice are the most frequently cited first-time implementation errors.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 3 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔮 Looking to 2027–2030', NULL, NULL, 'LHDN''s stated roadmap continues to evolve beyond the current phases — track official guidance for any further scope expansion or new document type requirements as the mandate matures.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Determine your applicable phase', 'Check your FY2022 audited accounts (or first available tax return) against the current turnover tier to confirm when your obligation actually begins.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Register on the MyInvois developer portal', 'Complete identity verification using your TIN and BRN (or NRIC for individuals), and apply for API access — LHDN issues a client ID and client secret for the OAuth 2.0 flow.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Obtain a digital certificate', 'Source this from a recognised Malaysian Certificate Authority — every submitted document must be digitally signed.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Map your data to UBL 2.1', 'Ensure your ERP or invoicing software can generate all 55 mandatory fields correctly, in either XML or JSON — validation failures fail closed with no partial acceptance.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Test thoroughly in the sandbox environment', 'Use your separate sandbox credentials to validate the full submission → validation → status-polling flow before switching to production.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Brief sales and finance teams', 'Sales needs to capture accurate TINs at the deal stage; finance needs a daily rejection-queue monitoring routine, since fixes need to happen fast within the 72-hour window.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 6 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Check group structure for related-company exposure', 'Confirm whether being part of an RM1m+ group brings you into scope even if your own standalone revenue sits below that threshold.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.hasil.gov.my/en/e-invoice', 0 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'LHDN — MyInvois / e-Invoice');

INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'Submission methods', NULL, 'API submission is recommended for moderate-to-high invoice volumes — it enables direct ERP integration and automated batch processing that manual portal entry can''t match.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Manual entry via MyInvois Portal');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Direct API integration');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Accredited/Peppol-linked solutions');
INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Malaysia';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'Validation lifecycle', NULL, 'On successful validation, MyInvois returns a UUID immediately and a Long ID once server-side validation completes — build your status polling around both identifiers.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'New');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Processing');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Submitted');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 3, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Approved / Rejected');
