-- UK milestone backfill. English only for now.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-nhs-peppol', id, '2019-01-01', 1, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-nhs-peppol', 'en', 'NHS Supply Chain requires Peppol BIS 3.0 from suppliers', 'The first genuine UK e-invoicing mandate — narrow in scope, but proof that Peppol infrastructure was already embedded in UK public procurement years before any general policy existed.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-procurement-act', id, '2023-01-01', 1, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-procurement-act', 'en', 'Public Procurement Act 2023 sets a reception baseline', 'All public bodies covered by the Act must be able to accept e-invoices compliant with BS EN 16931 — a reception requirement, not a full Peppol mandate, but it normalised structured e-invoicing across UK public procurement.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-consultation', id, '2025-02-13', 1, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-consultation', 'en', 'HMRC/DBT run a 12-week public consultation', '"Electronic invoicing: promoting e-invoicing across UK businesses and the public sector" gathered views from businesses of all sizes on e-invoicing models and whether a future mandate should be introduced. Ran 13 February – 7 May 2025.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-budget-2025', id, '2025-11-26', 1, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2025', 'en', 'Autumn Budget 2025 confirms a mandate from April 2029', 'The government publishes its consultation response alongside the Budget: e-invoicing will become mandatory for VAT invoices in B2B and B2G transactions from 1 April 2029, with a decentralised, standards-based approach rather than a centralised clearance regime.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-stakeholder-phase', id, '2026-01-01', 1, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-stakeholder-phase', 'en', 'Stakeholder collaboration phase begins', 'A structured period of detailed technical collaboration with industry starts, working through interoperability requirements ahead of the full roadmap.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-peppol-confirmed', id, '2026-06-23', 1, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-peppol-confirmed', 'en', 'Peppol formally confirmed as the interoperability framework', 'The government confirms a 4-corner Peppol model without e-reporting obligations — closely resembling Belgium''s first-phase regime. This removes the biggest remaining architectural question mark, even though implementation detail is still pending.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-budget-2026-due', id, '2026-11-01', 0, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2026-due', 'en', 'Full implementation roadmap and technical standards due', 'This is where the "how" gets answered: file formats, accreditation requirements, whether an existing standard or a UK-specific CIUS is adopted, and whether the rollout will be phased by business size.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uk-mandate', id, '2029-04-01', 0, 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/electronic-invoicing-promoting-e-invoicing-across-uk-businesses-and-the-public-sector' FROM countries WHERE name_en = 'United Kingdom';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-mandate', 'en', 'Mandatory e-invoicing for all VAT invoices (B2B and B2G)', 'Confirmed at Budget 2025, all VAT-registered businesses must issue and receive structured e-invoices for B2B and B2G transactions, using a decentralised four-corner Peppol model. Real-time reporting to HMRC is not part of this initial mandate.', '["Confirm your accounting software has a route to Peppol-based e-invoicing", "Watch for the full implementation roadmap and technical standards expected at Budget 2026", "Northern Ireland businesses: note a possible earlier, additional EU-aligned obligation for goods trade from July 2030"]');
