-- ES/DE/FR translations for all 8 UK milestones.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-nhs-peppol', 'es', 'NHS Supply Chain exige Peppol BIS 3.0 a los proveedores', 'El primer auténtico mandato de facturación electrónica del Reino Unido — de alcance reducido, pero prueba de que la infraestructura Peppol ya estaba integrada en la contratación pública británica años antes de que existiera ninguna política general.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-nhs-peppol', 'de', 'NHS Supply Chain verlangt Peppol BIS 3.0 von Lieferanten', 'Die erste echte E-Invoicing-Vorgabe des Vereinigten Königreichs — eng im Anwendungsbereich, aber ein Beweis dafür, dass Peppol-Infrastruktur bereits Jahre vor jeder allgemeinen Politik in der britischen öffentlichen Beschaffung verankert war.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-nhs-peppol', 'fr', 'NHS Supply Chain exige Peppol BIS 3.0 des fournisseurs', 'La première véritable obligation de facturation électronique du Royaume-Uni — de portée restreinte, mais preuve que l''infrastructure Peppol était déjà intégrée dans les marchés publics britanniques des années avant l''existence de toute politique générale.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-procurement-act', 'es', 'La Ley de Contratación Pública de 2023 establece una base de recepción', 'Todos los organismos públicos cubiertos por la Ley deben poder aceptar facturas electrónicas conformes con BS EN 16931 — un requisito de recepción, no un mandato Peppol completo, pero normalizó la facturación electrónica estructurada en la contratación pública británica.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-procurement-act', 'de', 'Der Public Procurement Act 2023 legt eine Empfangsgrundlage fest', 'Alle vom Gesetz erfassten öffentlichen Stellen müssen in der Lage sein, mit BS EN 16931 konforme E-Rechnungen anzunehmen — eine Empfangspflicht, keine vollständige Peppol-Vorgabe, doch sie normalisierte strukturierte E-Rechnungsstellung in der gesamten britischen öffentlichen Beschaffung.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-procurement-act', 'fr', 'Le Public Procurement Act 2023 établit une base de réception', 'Tous les organismes publics couverts par la loi doivent pouvoir accepter des factures électroniques conformes à la norme BS EN 16931 — une exigence de réception, non une obligation Peppol complète, mais elle a normalisé la facturation électronique structurée dans les marchés publics britanniques.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-consultation', 'es', 'La HMRC/DBT realiza una consulta pública de 12 semanas', '"Facturación electrónica: promoción de la facturación electrónica entre las empresas del Reino Unido y el sector público" recogió opiniones de empresas de todos los tamaños sobre los modelos de facturación electrónica y si debía introducirse un futuro mandato. Se desarrolló del 13 de febrero al 7 de mayo de 2025.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-consultation', 'de', 'HMRC/DBT führen eine 12-wöchige öffentliche Konsultation durch', '"Electronic invoicing: promoting e-invoicing across UK businesses and the public sector" sammelte Meinungen von Unternehmen jeder Größe zu E-Invoicing-Modellen und dazu, ob eine künftige Vorgabe eingeführt werden sollte. Lief vom 13. Februar bis 7. Mai 2025.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-consultation', 'fr', 'La HMRC/DBT mènent une consultation publique de 12 semaines', '« Electronic invoicing: promoting e-invoicing across UK businesses and the public sector » a recueilli les avis d''entreprises de toutes tailles sur les modèles de facturation électronique et sur l''opportunité d''introduire une future obligation. S''est déroulée du 13 février au 7 mai 2025.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2025', 'es', 'El Presupuesto de Otoño de 2025 confirma un mandato desde abril de 2029', 'El gobierno publica su respuesta a la consulta junto con el Presupuesto: la facturación electrónica se volverá obligatoria para las facturas de IVA en transacciones B2B y B2G a partir del 1 de abril de 2029, con un enfoque descentralizado y basado en estándares en lugar de un régimen de compensación centralizado.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2025', 'de', 'Der Herbsthaushalt 2025 bestätigt eine Vorgabe ab April 2029', 'Die Regierung veröffentlicht ihre Konsultationsantwort zusammen mit dem Haushalt: E-Invoicing wird ab dem 1. April 2029 für Umsatzsteuerrechnungen bei B2B- und B2G-Transaktionen verpflichtend, mit einem dezentralisierten, standardbasierten Ansatz statt eines zentralisierten Clearing-Regimes.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2025', 'fr', 'Le Budget d''automne 2025 confirme une obligation à partir d''avril 2029', 'Le gouvernement publie sa réponse à la consultation aux côtés du Budget : la facturation électronique deviendra obligatoire pour les factures de TVA dans les transactions B2B et B2G à partir du 1er avril 2029, selon une approche décentralisée et fondée sur des normes plutôt qu''un régime de contrôle centralisé.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-stakeholder-phase', 'es', 'Comienza la fase de colaboración con las partes interesadas', 'Comienza un periodo estructurado de colaboración técnica detallada con la industria, trabajando en los requisitos de interoperabilidad antes de la hoja de ruta completa.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-stakeholder-phase', 'de', 'Die Phase der Stakeholder-Zusammenarbeit beginnt', 'Eine strukturierte Phase detaillierter technischer Zusammenarbeit mit der Industrie beginnt, in der Interoperabilitätsanforderungen vor der vollständigen Roadmap erarbeitet werden.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-stakeholder-phase', 'fr', 'La phase de collaboration avec les parties prenantes débute', 'Une période structurée de collaboration technique détaillée avec l''industrie commence, travaillant sur les exigences d''interopérabilité avant la feuille de route complète.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-peppol-confirmed', 'es', 'Peppol se confirma formalmente como el marco de interoperabilidad', 'El gobierno confirma un modelo Peppol de cuatro esquinas sin obligaciones de e-reporting — que se asemeja estrechamente al régimen de primera fase de Bélgica. Esto elimina la mayor incógnita arquitectónica restante, aunque el detalle de implementación sigue pendiente.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-peppol-confirmed', 'de', 'Peppol wird formell als Interoperabilitätsrahmen bestätigt', 'Die Regierung bestätigt ein Vier-Ecken-Peppol-Modell ohne E-Reporting-Pflichten — was dem belgischen Regime der ersten Phase stark ähnelt. Dies beseitigt das größte verbleibende architektonische Fragezeichen, auch wenn Umsetzungsdetails noch ausstehen.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-peppol-confirmed', 'fr', 'Peppol est formellement confirmé comme cadre d''interopérabilité', 'Le gouvernement confirme un modèle Peppol à quatre coins sans obligations d''e-reporting — ressemblant étroitement au régime de première phase de la Belgique. Cela élimine le plus grand point d''interrogation architectural restant, même si le détail de mise en œuvre reste en attente.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2026-due', 'es', 'Se espera la hoja de ruta de implementación completa y los estándares técnicos', 'Aquí es donde se responde al "cómo": formatos de archivo, requisitos de acreditación, si se adopta un estándar existente o un CIUS específico del Reino Unido, y si la implementación se hará por fases según el tamaño de la empresa.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2026-due', 'de', 'Vollständige Umsetzungs-Roadmap und technische Standards erwartet', 'Hier wird das "Wie" beantwortet: Dateiformate, Akkreditierungsanforderungen, ob ein bestehender Standard oder eine UK-spezifische CIUS übernommen wird, und ob die Einführung nach Unternehmensgröße gestaffelt erfolgt.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2026-due', 'fr', 'La feuille de route de mise en œuvre complète et les normes techniques attendues', 'C''est ici que le « comment » trouve sa réponse : formats de fichiers, exigences d''accréditation, adoption d''une norme existante ou d''un CIUS propre au Royaume-Uni, et déploiement par phases selon la taille de l''entreprise ou non.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-mandate', 'es', 'Facturación electrónica obligatoria para todas las facturas de IVA (B2B y B2G)', 'Confirmado en el Presupuesto de 2025, todas las empresas registradas a efectos de IVA deben emitir y recibir facturas electrónicas estructuradas para transacciones B2B y B2G, usando un modelo Peppol de cuatro esquinas descentralizado. El reporte en tiempo real a la HMRC no forma parte de este mandato inicial.', '["Confirme que su software de contabilidad tiene una vía hacia la facturación electrónica basada en Peppol", "Esté atento a la hoja de ruta de implementación completa y los estándares técnicos esperados en el Presupuesto de 2026", "Empresas de Irlanda del Norte: tengan en cuenta una posible obligación adicional y anterior, alineada con la UE, para el comercio de bienes desde julio de 2030"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-mandate', 'de', 'Verpflichtende E-Rechnungsstellung für alle Umsatzsteuerrechnungen (B2B und B2G)', 'Im Haushalt 2025 bestätigt: Alle umsatzsteuerpflichtigen Unternehmen müssen strukturierte E-Rechnungen für B2B- und B2G-Transaktionen ausstellen und empfangen, unter Verwendung eines dezentralisierten Vier-Ecken-Peppol-Modells. Echtzeitmeldungen an die HMRC sind nicht Teil dieser ersten Vorgabe.', '["Bestätigen Sie, dass Ihre Buchhaltungssoftware einen Weg zu Peppol-basierter E-Rechnungsstellung hat", "Achten Sie auf die vollständige Umsetzungs-Roadmap und die technischen Standards, die zum Haushalt 2026 erwartet werden", "Unternehmen in Nordirland: Beachten Sie eine mögliche frühere, zusätzliche EU-angeglichene Pflicht für den Warenhandel ab Juli 2030"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-mandate', 'fr', 'Facturation électronique obligatoire pour toutes les factures de TVA (B2B et B2G)', 'Confirmé lors du Budget 2025, toutes les entreprises assujetties à la TVA doivent émettre et recevoir des factures électroniques structurées pour les transactions B2B et B2G, selon un modèle Peppol décentralisé à quatre coins. La déclaration en temps réel à la HMRC ne fait pas partie de cette obligation initiale.', '["Confirmez que votre logiciel comptable dispose d''une voie vers la facturation électronique basée sur Peppol", "Surveillez la feuille de route de mise en œuvre complète et les normes techniques attendues lors du Budget 2026", "Entreprises d''Irlande du Nord : notez une possible obligation antérieure et supplémentaire, alignée sur l''UE, pour le commerce de biens à partir de juillet 2030"]');
