-- ES/DE/FR translations for all 8 UK milestones.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-nhs-peppol', 'es', 'NHS Supply Chain exige Peppol BIS 3.0 a los proveedores', 'El primer auténtico mandato de facturación electrónica del Reino Unido — de alcance reducido, pero prueba de que la infraestructura Peppol ya estaba integrada en la contratación pública del Reino Unido años antes de que existiera cualquier política general.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-nhs-peppol', 'de', 'NHS Supply Chain verlangt Peppol BIS 3.0 von Lieferanten', 'Die erste echte E-Invoicing-Vorgabe des Vereinigten Königreichs — eng im Anwendungsbereich, aber ein Beleg dafür, dass die Peppol-Infrastruktur bereits Jahre vor jeder allgemeinen Politik in der öffentlichen Beschaffung des Vereinigten Königreichs verankert war.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-nhs-peppol', 'fr', 'NHS Supply Chain exige Peppol BIS 3.0 de la part des fournisseurs', 'La première véritable obligation de facturation électronique du Royaume-Uni — étroite dans son champ d''application, mais preuve que l''infrastructure Peppol était déjà ancrée dans les marchés publics britanniques des années avant l''existence d''une politique générale.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-procurement-act', 'es', 'La Ley de Contratación Pública de 2023 establece una base de recepción', 'Todos los organismos públicos cubiertos por la Ley deben poder aceptar facturas electrónicas conformes con BS EN 16931 — un requisito de recepción, no un mandato Peppol completo, pero normalizó la facturación electrónica estructurada en toda la contratación pública del Reino Unido.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-procurement-act', 'de', 'Der Public Procurement Act 2023 legt eine Empfangsgrundlage fest', 'Alle vom Gesetz erfassten öffentlichen Stellen müssen BS-EN-16931-konforme E-Rechnungen annehmen können — eine Empfangsanforderung, keine vollständige Peppol-Vorgabe, doch sie hat die strukturierte E-Rechnungsstellung in der gesamten britischen öffentlichen Beschaffung etabliert.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-procurement-act', 'fr', 'Le Public Procurement Act 2023 établit une base de réception', 'Tous les organismes publics couverts par la loi doivent pouvoir accepter des factures électroniques conformes à la BS EN 16931 — une exigence de réception, pas une obligation Peppol complète, mais elle a normalisé la facturation électronique structurée dans l''ensemble des marchés publics britanniques.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-consultation', 'es', 'La HMRC/DBT llevan a cabo una consulta pública de 12 semanas', '"Facturación electrónica: promoviendo la facturación electrónica en las empresas y el sector público del Reino Unido" recogió opiniones de empresas de todos los tamaños sobre los modelos de facturación electrónica y si debería introducirse un futuro mandato. Se desarrolló del 13 de febrero al 7 de mayo de 2025.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-consultation', 'de', 'HMRC/DBT führen eine 12-wöchige öffentliche Konsultation durch', '"Electronic invoicing: promoting e-invoicing across UK businesses and the public sector" sammelte Meinungen von Unternehmen aller Größen zu E-Invoicing-Modellen und ob eine künftige Vorgabe eingeführt werden sollte. Lief vom 13. Februar bis 7. Mai 2025.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-consultation', 'fr', 'La HMRC/DBT mènent une consultation publique de 12 semaines', '« Electronic invoicing: promoting e-invoicing across UK businesses and the public sector » a recueilli les avis d''entreprises de toutes tailles sur les modèles de facturation électronique et sur l''opportunité d''introduire une future obligation. S''est déroulée du 13 février au 7 mai 2025.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2025', 'es', 'El Presupuesto de Otoño de 2025 confirma un mandato desde abril de 2029', 'El gobierno publica su respuesta a la consulta junto con el Presupuesto: la facturación electrónica será obligatoria para las facturas de IVA en transacciones B2B y B2G a partir del 1 de abril de 2029, con un enfoque descentralizado y basado en estándares en lugar de un régimen de compensación centralizado.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2025', 'de', 'Der Herbsthaushalt 2025 bestätigt eine Vorgabe ab April 2029', 'Die Regierung veröffentlicht ihre Konsultationsantwort zusammen mit dem Haushalt: E-Rechnungsstellung wird für USt-Rechnungen bei B2B- und B2G-Transaktionen ab dem 1. April 2029 verpflichtend, mit einem dezentralisierten, standardbasierten Ansatz statt einem zentralisierten Clearing-Regime.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2025', 'fr', 'Le Budget d''automne 2025 confirme une obligation à partir d''avril 2029', 'Le gouvernement publie sa réponse à la consultation aux côtés du Budget : la facturation électronique deviendra obligatoire pour les factures de TVA dans les transactions B2B et B2G à partir du 1er avril 2029, avec une approche décentralisée et fondée sur des normes plutôt qu''un régime de contrôle centralisé.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-stakeholder-phase', 'es', 'Comienza la fase de colaboración con las partes interesadas', 'Comienza un periodo estructurado de colaboración técnica detallada con la industria, trabajando en los requisitos de interoperabilidad antes de la hoja de ruta completa.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-stakeholder-phase', 'de', 'Die Phase der Stakeholder-Zusammenarbeit beginnt', 'Eine strukturierte Phase detaillierter technischer Zusammenarbeit mit der Industrie beginnt, in der Interoperabilitätsanforderungen vor der vollständigen Roadmap erarbeitet werden.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-stakeholder-phase', 'fr', 'La phase de collaboration avec les parties prenantes commence', 'Une période structurée de collaboration technique détaillée avec l''industrie débute, travaillant sur les exigences d''interopérabilité avant la feuille de route complète.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-peppol-confirmed', 'es', 'Peppol se confirma formalmente como el marco de interoperabilidad', 'El gobierno confirma un modelo Peppol de cuatro esquinas sin obligaciones de e-reporting — que se asemeja mucho al régimen de primera fase de Bélgica. Esto elimina el mayor interrogante arquitectónico restante, aunque el detalle de implementación sigue pendiente.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-peppol-confirmed', 'de', 'Peppol wird formell als Interoperabilitätsrahmen bestätigt', 'Die Regierung bestätigt ein 4-Ecken-Peppol-Modell ohne E-Reporting-Pflichten — das dem belgischen Regime der ersten Phase stark ähnelt. Dies beseitigt die größte verbleibende architektonische Unklarheit, auch wenn das Umsetzungsdetail noch aussteht.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-peppol-confirmed', 'fr', 'Peppol est formellement confirmé comme cadre d''interopérabilité', 'Le gouvernement confirme un modèle Peppol à quatre coins sans obligations d''e-reporting — ressemblant fortement au régime de première phase de la Belgique. Cela élimine la plus grande incertitude architecturale restante, même si le détail de mise en œuvre reste en attente.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2026-due', 'es', 'Se esperan la hoja de ruta de implementación completa y las normas técnicas', 'Aquí es donde se responde al "cómo": formatos de archivo, requisitos de acreditación, si se adopta un estándar existente o un CIUS específico del Reino Unido, y si la implementación se hará por fases según el tamaño de la empresa.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2026-due', 'de', 'Vollständige Umsetzungs-Roadmap und technische Standards erwartet', 'Hier wird das "Wie" beantwortet: Dateiformate, Akkreditierungsanforderungen, ob ein bestehender Standard oder eine britische CIUS übernommen wird, und ob die Einführung nach Unternehmensgröße gestaffelt erfolgt.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-budget-2026-due', 'fr', 'La feuille de route de mise en œuvre complète et les normes techniques sont attendues', 'C''est ici que le « comment » trouve sa réponse : formats de fichiers, exigences d''accréditation, adoption d''une norme existante ou d''un CIUS spécifique au Royaume-Uni, et déploiement échelonné ou non selon la taille de l''entreprise.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-mandate', 'es', 'Facturación electrónica obligatoria para todas las facturas de IVA (B2B y B2G)', 'Confirmado en el Presupuesto de 2025, todas las empresas registradas a efectos de IVA deben emitir y recibir facturas electrónicas estructuradas para transacciones B2B y B2G, utilizando un modelo Peppol descentralizado de cuatro esquinas. El reporte en tiempo real a la HMRC no forma parte de este mandato inicial.', '["Confirme que su software contable tiene una vía hacia la facturación electrónica basada en Peppol", "Esté atento a la hoja de ruta de implementación completa y las normas técnicas previstas para el Presupuesto de 2026", "Empresas de Irlanda del Norte: tengan en cuenta una posible obligación adicional y anterior, alineada con la UE, para el comercio de mercancías a partir de julio de 2030"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-mandate', 'de', 'Verpflichtende E-Rechnungsstellung für alle USt-Rechnungen (B2B und B2G)', 'Im Haushalt 2025 bestätigt: Alle umsatzsteuerpflichtigen Unternehmen müssen strukturierte E-Rechnungen für B2B- und B2G-Transaktionen ausstellen und empfangen, unter Verwendung eines dezentralisierten Vier-Ecken-Peppol-Modells. Die Echtzeitmeldung an die HMRC ist nicht Teil dieser ersten Vorgabe.', '["Bestätigen Sie, dass Ihre Buchhaltungssoftware einen Weg zur Peppol-basierten E-Rechnungsstellung hat", "Achten Sie auf die vollständige Umsetzungs-Roadmap und technische Standards, die zum Haushalt 2026 erwartet werden", "Unternehmen in Nordirland: beachten Sie eine mögliche frühere, zusätzliche EU-angeglichene Pflicht für den Warenhandel ab Juli 2030"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uk-mandate', 'fr', 'Facturation électronique obligatoire pour toutes les factures de TVA (B2B et B2G)', 'Confirmé lors du Budget 2025, toutes les entreprises assujetties à la TVA doivent émettre et recevoir des factures électroniques structurées pour les transactions B2B et B2G, selon un modèle Peppol décentralisé à quatre coins. La déclaration en temps réel à la HMRC ne fait pas partie de cette obligation initiale.', '["Confirmez que votre logiciel comptable dispose d''une voie vers la facturation électronique basée sur Peppol", "Surveillez la feuille de route de mise en œuvre complète et les normes techniques attendues au Budget 2026", "Entreprises d''Irlande du Nord : notez une possible obligation supplémentaire et antérieure, alignée sur l''UE, pour le commerce de marchandises à partir de juillet 2030"]');
