-- ES/DE/FR translations for all 7 Romania milestones.
-- ro-established and ro-sme reuse the tracker's own existing translations
-- (i18n/{lang}-data.json) verbatim, per the tracker-phrasing-wins rule.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-voluntary', 'es', 'RO e-Factura abre para uso voluntario', 'La plataforma se abrió para el registro voluntario antes de cualquier mandato legal, dando a las empresas y organismos públicos pioneros tiempo para probar la integración.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-voluntary', 'de', 'RO e-Factura öffnet für die freiwillige Nutzung', 'Die Plattform wurde für die freiwillige Registrierung geöffnet, noch vor jeder gesetzlichen Verpflichtung, um früh einsteigenden Unternehmen und öffentlichen Stellen Zeit zu geben, die Integration zu testen.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-voluntary', 'fr', 'RO e-Factura s''ouvre à l''usage volontaire', 'La plateforme s''est ouverte à l''inscription volontaire avant toute obligation légale, laissant aux entreprises et organismes publics précurseurs le temps de tester l''intégration.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-b2g', 'es', 'La facturación electrónica B2G se vuelve obligatoria', 'Las autoridades contratantes públicas dentro del alcance de la Ley 199/2020 (que transpone la Directiva UE 2014/55/UE) deben aceptar y procesar facturas estructuradas conformes con EN 16931 para la contratación pública por encima de los umbrales de la UE.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-b2g', 'de', 'E-Rechnungspflicht für B2G wird verpflichtend', 'Öffentliche Auftraggeber im Anwendungsbereich des Gesetzes 199/2020 (zur Umsetzung der EU-Richtlinie 2014/55/EU) müssen EN-16931-konforme strukturierte Rechnungen für die öffentliche Beschaffung oberhalb der EU-Schwellenwerte akzeptieren und verarbeiten.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-b2g', 'fr', 'La facturation électronique B2G devient obligatoire', 'Les pouvoirs adjudicateurs publics relevant de la loi 199/2020 (transposant la directive UE 2014/55/UE) doivent accepter et traiter les factures structurées conformes à l''EN 16931 pour les marchés publics au-delà des seuils de l''UE.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-law296', 'es', 'La Ley 296/2023 establece la facturación electrónica B2B obligatoria', 'Comienzan las obligaciones de e-reporting B2B para las personas sujetas al impuesto establecidas en Rumanía (y las entidades no establecidas registradas a efectos de IVA), bajo el marco de la Ordenanza del Gobierno 120/2021 y la especificación técnica RO_CIUS (Orden del MF 1366/2021).', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-law296', 'de', 'Gesetz 296/2023 führt die verpflichtende B2B-E-Rechnung ein', 'Für in Rumänien ansässige Steuerpflichtige (sowie nicht ansässige, umsatzsteuerlich registrierte Unternehmen) beginnen B2B-E-Reporting-Pflichten im Rahmen der Regierungsverordnung 120/2021 und der technischen Spezifikation RO_CIUS (Anordnung des Finanzministeriums 1366/2021).', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-law296', 'fr', 'La loi 296/2023 instaure la facturation électronique B2B obligatoire', 'Les obligations de télédéclaration B2B débutent pour les assujettis établis en Roumanie (ainsi que pour les entités non établies immatriculées à la TVA), dans le cadre de l''ordonnance gouvernementale 120/2021 et de la spécification technique RO_CIUS (arrêté du ministère des Finances 1366/2021).', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-established', 'es', 'Modelo de compensación RO e-Factura obligatorio para B2B/B2G (en vigor desde julio de 2024)', 'Rumanía opera un modelo de compensación centralizado (CTC): las facturas B2B y B2G deben ser validadas y selladas digitalmente por la ANAF a través de RO e-Factura antes de tener efectos legales. El reporte B2C siguió desde enero de 2025.', '["Confirme el registro en RO e-Factura y la generación de facturas XML conformes con RO_CIUS", "El plazo de transmisión es de 5 días hábiles desde la emisión (reducido desde 5 días naturales en enero de 2026)"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-established', 'de', 'RO-e-Factura-Clearing-Modell verpflichtend für B2B/B2G (seit Juli 2024 in Kraft)', 'Rumänien betreibt ein zentralisiertes Clearing-Modell (CTC): B2B- und B2G-Rechnungen müssen von der ANAF über RO e-Factura validiert und digital versiegelt werden, bevor sie Rechtswirkung entfalten. Die B2C-Meldung folgte ab Januar 2025.', '["Bestätigen Sie die Registrierung bei RO e-Factura und die Erstellung RO_CIUS-konformer XML-Rechnungen", "Die Übermittlungsfrist beträgt 5 Werktage ab Ausstellung (verkürzt von 5 Kalendertagen im Januar 2026)"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-established', 'fr', 'Modèle de contrôle RO e-Factura obligatoire pour le B2B/B2G (en vigueur depuis juillet 2024)', 'La Roumanie applique un modèle de contrôle centralisé (CTC) : les factures B2B et B2G doivent être validées et scellées numériquement par l''ANAF via RO e-Factura avant d''avoir un effet légal. La déclaration B2C a suivi à partir de janvier 2025.', '["Vérifiez l''enregistrement à RO e-Factura et la génération de factures XML conformes à RO_CIUS", "Le délai de transmission est de 5 jours ouvrés à compter de l''émission (raccourci depuis 5 jours calendaires en janvier 2026)"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-sme', 'es', 'La aplicación plena se extiende a los pequeños contribuyentes (<500.000 € de facturación)', 'Tras un retraso confirmado, los pequeños contribuyentes con facturación inferior a 500.000 € quedan plenamente sujetos a la aplicación y sanciones de e-Factura, en igualdad de condiciones con las empresas más grandes.', '["Estandarice las direcciones de clientes y los códigos de país/ISO antes de la fecha límite", "Confirme que su herramienta de facturación aplica la regla de transmisión de 5 días hábiles"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-sme', 'de', 'Volle Durchsetzung erweitert sich auf Kleinunternehmen (Umsatz <500.000 €)', 'Nach einer bestätigten Verzögerung unterliegen Kleinunternehmen mit einem Umsatz unter 500.000 € nun in vollem Umfang der e-Factura-Durchsetzung und den Sanktionen, gleichrangig mit größeren Unternehmen.', '["Standardisieren Sie Kundenadressen und Länder-/ISO-Codes rechtzeitig vor der Frist", "Bestätigen Sie, dass Ihr Rechnungstool die 5-Werktage-Übermittlungsregel anwendet"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-sme', 'fr', 'L''application complète s''étend aux petits contribuables (chiffre d''affaires <500 000 €)', 'Après un report confirmé, les petits contribuables dont le chiffre d''affaires est inférieur à 500 000 € sont désormais pleinement soumis à l''application et aux sanctions d''e-Factura, sur un pied d''égalité avec les grandes entreprises.', '["Standardisez les adresses des clients et les codes pays/ISO avant l''échéance", "Vérifiez que votre outil de facturation applique la règle de transmission de 5 jours ouvrés"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-b2c', 'es', 'El reporte B2C se incorpora al mandato', 'Las facturas B2C ordinarias también deben reportarse a través de RO e-Factura en formato XML RO_CIUS. Los recibos fiscales de punto de venta y las transacciones individuales puntuales permanecen exentos.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-b2c', 'de', 'B2C-Meldung tritt der Verpflichtung bei', 'Reguläre B2C-Rechnungen müssen ebenfalls über RO e-Factura im RO_CIUS-XML-Format gemeldet werden. Kassenbons am Verkaufsort und einmalige Transaktionen von Privatpersonen bleiben ausgenommen.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-b2c', 'fr', 'La déclaration B2C rejoint l''obligation', 'Les factures B2C ordinaires doivent également être déclarées via RO e-Factura au format XML RO_CIUS. Les reçus fiscaux de point de vente et les transactions individuelles ponctuelles restent exemptés.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-nonvat-register', 'es', 'El registro se amplía a entidades no registradas a efectos de IVA', 'El Registro obligatorio RO e-Invoice ahora también cubre a asociaciones, fundaciones y entidades sin ánimo de lucro no registradas a efectos de IVA, agricultores individuales bajo el régimen agrícola especial, y autónomos identificados por número de identificación personal (CNP).', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-nonvat-register', 'de', 'Register wird auf nicht umsatzsteuerlich registrierte Einrichtungen ausgeweitet', 'Das verpflichtende RO-e-Invoice-Register umfasst nun auch Vereine, Stiftungen und gemeinnützige Organisationen ohne Umsatzsteuerregistrierung, Einzellandwirte unter der besonderen landwirtschaftlichen Regelung sowie Einzelunternehmer, die über die persönliche Identifikationsnummer (CNP) identifiziert werden.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ro-nonvat-register', 'fr', 'Le registre s''étend aux entités non immatriculées à la TVA', 'Le registre obligatoire RO e-Invoice couvre désormais aussi les associations, fondations et organismes à but non lucratif non immatriculés à la TVA, les agriculteurs individuels relevant du régime agricole spécial, ainsi que les entrepreneurs individuels identifiés par leur numéro d''identification personnel (CNP).', '[]');
