-- ES/DE/FR translations for all 6 Belgium milestones.
-- be-mandate, be-penalty, be-ereport reuse the tracker's own existing
-- translations (i18n/{lang}-data.json) verbatim, per tracker-phrasing-wins.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-mercurius', 'es', 'La plataforma Mercurius se lanza para la facturación electrónica B2G vía Peppol', 'El centro central de Bélgica para la facturación electrónica entre empresas y administración pública entra en funcionamiento, construido sobre la red Peppol desde el principio — la misma infraestructura que el mandato B2B de 2026 ampliaría más tarde.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-mercurius', 'de', 'Die Mercurius-Plattform startet für B2G-E-Invoicing über Peppol', 'Belgiens zentrale Anlaufstelle für die elektronische Rechnungsstellung zwischen Unternehmen und Behörden geht live, von Anfang an auf dem Peppol-Netzwerk aufgebaut — dieselbe Infrastruktur, die das B2B-Mandat 2026 später erweitern würde.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-mercurius', 'fr', 'La plateforme Mercurius est lancée pour la facturation électronique B2G via Peppol', 'Le pôle central belge pour la facturation électronique entre entreprises et administration entre en service, construit dès le départ sur le réseau Peppol — la même infrastructure que l''obligation B2B de 2026 étendra plus tard.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-b2g-phasein', 'es', 'El mandato B2G se implementa por fases según el valor del contrato y luego se generaliza', 'Octubre de 2022: contratos/concesiones ≥215.000 €. Abril de 2023: ≥30.000 €. Octubre de 2023: por debajo de 30.000 €. Marzo de 2024: todos los contratos y concesiones públicas, sin importar el valor, transponiendo íntegramente la Directiva UE 2014/55/UE.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-b2g-phasein', 'de', 'Die B2G-Pflicht wird stufenweise nach Vertragswert eingeführt und dann allgemein verpflichtend', 'Oktober 2022: Verträge/Konzessionen ≥215.000 €. April 2023: ≥30.000 €. Oktober 2023: unter 30.000 €. März 2024: alle öffentlichen Verträge und Konzessionen, unabhängig vom Wert, womit die EU-Richtlinie 2014/55/EU vollständig umgesetzt wird.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-b2g-phasein', 'fr', 'L''obligation B2G s''applique par étapes selon la valeur du contrat, puis devient universelle', 'Octobre 2022 : contrats/concessions ≥215 000 €. Avril 2023 : ≥30 000 €. Octobre 2023 : en dessous de 30 000 €. Mars 2024 : tous les contrats et concessions publics, quelle que soit leur valeur, transposant intégralement la directive UE 2014/55/UE.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-law-2024', 'es', 'La Ley del 6 de febrero de 2024 fija la fecha de inicio del B2B', 'El Parlamento incorpora la obligación de facturación electrónica estructurada a la legislación belga y fija el 1 de enero de 2026 como fecha de inicio obligatoria para las transacciones B2B nacionales. Un Real Decreto emitido en 2025 establece después Peppol BIS Billing 3.0 como el estándar técnico exigido.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-law-2024', 'de', 'Das Gesetz vom 6. Februar 2024 legt den B2B-Starttermin fest', 'Das Parlament verankert die Pflicht zur strukturierten E-Rechnung im belgischen Recht und legt den 1. Januar 2026 als verpflichtenden Starttermin für inländische B2B-Transaktionen fest. Ein 2025 erlassener Königlicher Erlass legt anschließend Peppol BIS Billing 3.0 als vorgeschriebenen technischen Standard fest.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-law-2024', 'fr', 'La loi du 6 février 2024 fixe la date de début du B2B', 'Le Parlement inscrit l''obligation de facturation électronique structurée dans la loi belge et fixe le 1er janvier 2026 comme date de début obligatoire pour les transactions B2B nationales. Un arrêté royal publié en 2025 fixe ensuite Peppol BIS Billing 3.0 comme norme technique requise.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-mandate', 'es', 'Facturación electrónica B2B obligatoria vía Peppol', 'La facturación electrónica estructurada pasó a ser obligatoria para las transacciones B2B nacionales entre empresas belgas registradas a efectos del IVA, utilizando el estándar Peppol BIS Billing 3.0 / EN 16931.', '["Conéctese a través de un Punto de Acceso Peppol certificado (o confirme que su proveedor lo es)", "Emita y reciba facturas UBL Peppol BIS Billing 3.0 para todas las ventas B2B nacionales", "Las facturas en PDF y en papel ya no son válidas — solo se admite el formato estructurado"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-mandate', 'de', 'Verpflichtendes B2B-E-Invoicing über Peppol', 'Strukturiertes E-Invoicing wurde für inländische B2B-Transaktionen zwischen belgischen umsatzsteuerpflichtigen Unternehmen verpflichtend, unter Verwendung des Standards Peppol BIS Billing 3.0 / EN 16931.', '["Verbinden Sie sich über einen zertifizierten Peppol Access Point (oder bestätigen Sie, dass Ihr Anbieter dies ist)", "Stellen Sie Peppol BIS Billing 3.0 UBL-Rechnungen für alle inländischen B2B-Verkäufe aus und empfangen Sie sie", "PDF- und Papierrechnungen sind nicht mehr zulässig — nur strukturiertes Format"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-mandate', 'fr', 'Facturation électronique B2B obligatoire via Peppol', 'La facturation électronique structurée est devenue obligatoire pour les transactions B2B nationales entre entreprises belges assujetties à la TVA, selon la norme Peppol BIS Billing 3.0 / EN 16931.', '["Connectez-vous via un Access Point Peppol certifié (ou vérifiez que votre prestataire en est un)", "Émettez et recevez des factures UBL Peppol BIS Billing 3.0 pour toutes les ventes B2B nationales", "Les factures PDF et papier ne sont plus valables — seul le format structuré est accepté"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-penalty', 'es', 'Finaliza el período de tolerancia — se aplican sanciones', 'Finalizó el período de tolerancia administrativa de tres meses; ahora se aplica un régimen de sanciones progresivas (1.500 € / 3.000 € / 5.000 €) a la facturación no conforme.', '["Resuelva de inmediato cualquier vacío pendiente en la incorporación a Peppol — se aplican multas por infracción", "Audite las facturas recientes para verificar el cumplimiento del formato estructurado"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-penalty', 'de', 'Toleranzfrist endet — Sanktionen werden durchgesetzt', 'Die dreimonatige administrative Toleranzfrist endete; nun gilt ein progressives Sanktionssystem (1.500 € / 3.000 € / 5.000 €) bei nicht konformer Rechnungsstellung.', '["Beheben Sie ausstehende Lücken beim Peppol-Onboarding umgehend — Bußgelder gelten pro Verstoß", "Prüfen Sie kürzlich ausgestellte Rechnungen auf Einhaltung des strukturierten Formats"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-penalty', 'fr', 'Fin de la période de tolérance — sanctions appliquées', 'La période de tolérance administrative de trois mois a pris fin ; un régime de sanctions progressives (1 500 € / 3 000 € / 5 000 €) s''applique désormais à la facturation non conforme.', '["Résolvez immédiatement toute lacune d''intégration Peppol en suspens — des amendes s''appliquent par infraction", "Vérifiez les factures récentes pour vous assurer de la conformité au format structuré"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-ereport', 'es', 'Reporte casi en tiempo real (modelo Peppol de 5 esquinas)', 'Bélgica prevé introducir el reporte digital de IVA casi en tiempo real mediante un modelo Peppol de cinco esquinas, que enviará automáticamente los datos de las facturas a la autoridad fiscal.', '["Empiece a definir el alcance de la capacidad de reporte Peppol de cinco esquinas con su proveedor de Punto de Acceso", "Confirme que esto sigue en marcha a medida que se acerque la fecha — las normas de aplicación finales aún están pendientes"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-ereport', 'de', 'Nahezu-Echtzeit-Meldung (5-Corner-Peppol-Modell)', 'Belgien plant die Einführung einer digitalen Umsatzsteuermeldung nahezu in Echtzeit über ein Fünf-Ecken-Peppol-Modell, das Rechnungsdaten automatisch an die Steuerbehörde meldet.', '["Beginnen Sie mit Ihrem Access-Point-Anbieter, die Fähigkeit zur Fünf-Ecken-Peppol-Meldung zu planen", "Bestätigen Sie näher am Termin, dass dies weiterhin im Zeitplan liegt — die endgültigen Durchführungsbestimmungen stehen noch aus"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('be-ereport', 'fr', 'Déclaration quasi en temps réel (modèle Peppol à 5 coins)', 'La Belgique prévoit d''introduire une déclaration numérique de TVA quasi en temps réel via un modèle Peppol à cinq coins, transmettant automatiquement les données de facturation à l''administration fiscale.', '["Commencez à définir la capacité de déclaration Peppol à cinq coins avec votre fournisseur d''Access Point", "Vérifiez que ce calendrier reste d''actualité à l''approche de l''échéance — les règles d''application définitives sont encore en attente"]');
