-- Finland milestone backfill (Stage 4). English only for now.
-- 7 timeline entries: 3 also exist in the tracker's own DATA array
-- (fi-b2g, fi-en-standard, fi-vida), using tracker phrasing; the other 4
-- are deep-dive-only background facts. fi-early2000s uses 2000-01-01 as a
-- representative date for the page's own vague "Early 2000s" label -- exact
-- year doesn't affect the in-effect/upcoming badge outcome either way.
-- fi-b2g keeps the tracker's anchor:true (Finland's one genuinely binding
-- requirement); the other tracker-matched ids (fi-en-standard, fi-vida) keep
-- anchor=0 to match the tracker's own values.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'fi-early2000s', id, '2000-01-01', 1, 'https://www.valtiokonttori.fi/en/e-invoicing-fast-and-safe/' FROM countries WHERE name_en = 'Finland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('fi-early2000s', 'en', 'Finland pioneers national e-invoicing formats', 'Finvoice and TEAPPSXML predate most of Europe''s e-invoicing infrastructure — Finland built genuine national capability well before any EU-level push existed.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'fi-act2019', id, '2019-01-01', 1, 'https://www.valtiokonttori.fi/en/e-invoicing-fast-and-safe/' FROM countries WHERE name_en = 'Finland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('fi-act2019', 'en', 'eInvoicing Act 241/2019 passed', 'Establishes the statutory right for businesses with turnover above €10,000 to demand e-invoices from their suppliers — a genuine legal right, but not a mandate to issue them.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'fi-b2g', id, '2020-04-01', 1, 'https://www.valtiokonttori.fi/en/e-invoicing-fast-and-safe/' FROM countries WHERE name_en = 'Finland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('fi-b2g', 'en', 'B2G e-invoicing mandatory (in force since Apr 2020)', 'All suppliers invoicing Finnish government agencies must send e-invoices unless otherwise agreed — one of the most mature B2G regimes in Europe, with around 99% of invoices to public buyers already electronic. Finland has no general B2B or B2C e-invoicing mandate: domestic B2B e-invoicing remains entirely voluntary, though businesses with turnover above €10,000 have a statutory right to demand e-invoices from their suppliers under the eInvoicing Act 241/2019.', '["If you supply any Finnish public-sector body, confirm you can send e-invoices — this has been the norm for years, not a new requirement", "For domestic B2B, don''t assume a legal mandate exists — check your specific customer''s contractual requirements instead"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'fi-en-standard', id, '2021-04-01', 0, 'https://www.valtiokonttori.fi/en/e-invoicing-fast-and-safe/' FROM countries WHERE name_en = 'Finland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('fi-en-standard', 'en', 'State requires EN 16931-compliant e-invoices (in force since Apr 2021)', 'From this date, Finnish government agencies only accept e-invoices compliant with the European Standard (EN 16931) — non-standard formats are no longer sufficient for B2G invoicing, even though e-invoicing itself had already been mandatory for a year. Finvoice 3.0 and TEAPPSXML 3.0 can both produce EN-compliant invoices, but compliance isn''t automatic — businesses must verify their software''s output actually meets the standard rather than assuming it by default.', '["Confirm your invoicing software''s Finvoice 3.0 or TEAPPSXML 3.0 output is genuinely EN 16931-compliant, not just superficially similar", "Check the Verkkolaskuosoite directory to confirm which e-invoicing operator/portal reaches a given public-sector counterparty — there''s no single central platform"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'fi-peppol-ordering', id, '2025-01-01', 1, 'https://www.valtiokonttori.fi/en/e-invoicing-fast-and-safe/' FROM countries WHERE name_en = 'Finland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('fi-peppol-ordering', 'en', 'Peppol Advanced Ordering mandated for Central Government', 'Central Government now requires Peppol Advanced Ordering specifically, extending standardisation beyond invoicing into the ordering process itself.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'fi-vida-prep', id, '2028-01-01', 0, 'https://www.valtiokonttori.fi/en/e-invoicing-fast-and-safe/' FROM countries WHERE name_en = 'Finland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('fi-vida-prep', 'en', 'Government plans to begin ViDA preparations', 'Finland''s government has signalled it plans to begin preparing for intra-EU B2B e-invoicing obligations around this year — a soft, non-binding marker rather than a confirmed mandate date.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'fi-vida', id, '2030-07-01', 0, 'https://www.valtiokonttori.fi/en/e-invoicing-fast-and-safe/' FROM countries WHERE name_en = 'Finland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('fi-vida', 'en', 'Intra-EU B2B e-invoicing mandatory under EU ViDA', 'Finland currently has no domestic B2B e-invoicing mandate and none is confirmed before this EU-wide deadline, under which intra-EU B2B transactions will require structured e-invoicing and digital reporting across every member state. Finland''s government has indicated it plans to begin preparations around 2028, and a domestic mandate may follow this EU deadline rather than precede it — a genuinely different posture from most other countries in this tracker, which are moving well ahead of the 2030 EU floor.', '["Don''t assume Finland will follow the same domestic-mandate timeline as its Nordic neighbours — as of today, no domestic B2B mandate date has been set", "Revisit this page periodically rather than treating \"no mandate yet\" as a permanent state — 2028 preparations could surface a firmer domestic timeline"]');
