-- Denmark deep-dive content backfill (Stage 4). English only for now.
-- Penalty table has a generic 2-column (Factor/Range) shape rather than a
-- failure-type list -- mapped directly onto failure_description/fine_amount,
-- annual_cap NULL for both rows (no cap concept here either).

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Technical-capability mandate (not a transmission mandate)', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. NemHandel BIS 4 development, SAF-T 2.0 specifications, and enforcement practice continue to evolve — confirm current requirements directly with Erhvervsstyrelsen before building an integration.', 'Denmark''s Bookkeeping Act is unusual: it mandates the technical capability to e-invoice, not that every invoice actually be sent electronically — and it''s already mid-transition to a new national format.', 'Denmark is mid-migration — the format you build against today is not the format you''ll be using by the end of the decade.', 'The single most important thing to understand about Denmark: this law mandates capability, not universal transmission — a meaningful difference from every clearance-model country in this tracker.', 'Compliance here is about your bookkeeping system''s status, not a single "sign up" step — plan around the six statutory obligations.', 'Danish fines scale dramatically with severity — and the ultimate sanction goes well beyond money.' FROM countries WHERE name_en = 'Denmark';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2 formats', 'OIOUBL 2.1 / Peppol BIS 3.0');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '5 yrs', 'Standard archive requirement');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'DKK 1.5m', 'Maximum fine');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2029', 'OIOUBL fully phased out');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Jul 2026', 'NemHandel-by-default begins');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Current formats', '[["National format", "OIOUBL 2.1"], ["International format", "Peppol BIS 3.0 (EN 16931-compliant)"], ["OIOUBL 3.0", "Cancelled, January 2026 — no replacement"]]', 'Both operative formats must be supported by any system seeking "registered" status — this is a non-negotiable procurement checklist item, not an either/or choice.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'The migration path', '[["Destination format", "Nemhandel BIS 4 (localised Peppol BIS 4)"], ["Depends on", "Development of Peppol BIS 4 itself, incorporating PINT"], ["Regulatory driver", "EU ViDA cross-border deadline, 1 Jul 2030"]]', 'Once migration completes, Erhvervsstyrelsen proposes to simplify the Bookkeeping Act''s format requirement down to a single supported standard — Nemhandel BIS support alone.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Danish-specific requirements', '[["Chart of accounts", "Standardkontoplan (Danish standard structure)"], ["Audit reporting", "Danish SAF-T, generated on demand from Jan 2027"], ["Audit trail split", "Kontrolspor (control trail) vs. transaktionsspor (transaction trail)"]]', 'A globally configured ledger doesn''t map natively to the Danish standardkontoplan — this is a genuine localisation task, not just a format-conversion exercise.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Archiving', '[["Standard retention", "5 years (most cases)"], ["Access requirement", "Must support authority data requests on demand"]]', 'Test this explicitly: simulate a data request from Erhvervsstyrelsen or Skattestyrelsen before you''re ever asked for real — it''s one of the six principal obligations under the Act.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'What the law actually requires', '[["Mandate type", "Technical capability to send/receive"], ["Not required", "Universal e-invoice transmission for every transaction"]]', 'A business can be fully compliant while still exchanging some invoices in other ways — what it can''t do is lack the capability entirely, or use a non-compliant system to record its books.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'NemHandel', '[["Access", "Danish companies with a CVR number only"], ["Foreign companies", "Use a Peppol Access Point instead"], ["Directory", "NemHandelsregisteret (public register)"]]', 'NemHandel is Denmark''s national platform, but it''s interconnected with the broader Peppol network — you don''t need a CVR number to participate, just a different entry point.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Two paths to system compliance', '[["Path A", "Certified system on Erhvervsstyrelsen''s registered list"], ["Path B", "Non-registered custom system, declared to the Authority"]]', '"Custom" doesn''t mean "less scrutinised" — Path B still has to meet every statutory technical requirement, it means you carry the burden of proving compliance yourself rather than relying on a pre-certified vendor.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 3 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'NemHandel-by-default (from Jul 2026)', '[["Mechanism", "Automatic enrolment for registered-system entities"], ["Opt-out", "Window provided, not compulsory participation"]]', 'This campaign nudges actual e-invoice issuance up without changing the underlying legal mandate — decide deliberately whether to opt out rather than let default enrolment catch you unprepared.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚠️ Beyond fines: forced dissolution', NULL, NULL, 'In the most serious cases, consequences extend beyond financial penalties to forced dissolution of the entity — this is a genuinely existential risk category, not just a cost of doing business.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📋 B2G non-compliance', NULL, NULL, 'Separately from the general Bookkeeping Act penalties, failure to follow public-sector invoicing rules can trigger fines from the Danish Business Authority specifically tied to that relationship.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔄 OIOUBL 3.0''s cancellation matters here', NULL, NULL, 'Because the planned successor format was scrapped, any compliance roadmap built around it needs re-planning around the Nemhandel BIS 4 timeline instead — a real, not hypothetical, planning risk.');

INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Statutory fine range', 'DKK 10,000 – 1,500,000 (~EUR 1,350 – 200,000)', NULL);
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Severity depends on', 'Nature and duration of the violation, and whether it''s a repeated pattern', NULL);

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Decide: registered system or declared custom system', 'Check Erhvervsstyrelsen''s official register first — using an already-certified system is materially less work than declaring and proving compliance for a custom build.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm dual-format support: OIOUBL 2.1 and Peppol BIS 3.0', 'Both are required for registered status today — treat this as non-negotiable when evaluating or switching systems.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Register for NemHandel if you hold a CVR number', 'Foreign companies without a CVR should set up a Peppol Access Point connection instead to receive and send OIOUBL/Peppol invoices.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Map your ledger to the Danish standardkontoplan', 'Don''t assume a globally configured chart of accounts satisfies this — it''s a genuine localisation requirement for registered-system status.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Decide your NemHandel-by-default posture ahead of July 2026', 'If your system is registered, you''ll be auto-enrolled — actively decide whether to stay in or opt out rather than let it happen passively.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Prepare Danish SAF-T generation ahead of January 2027', 'Confirm your system can produce SAF-T 2.0 on demand, and that your kontrolspor and transaktionsspor audit trails are properly distinguished.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 6 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Track the OIOUBL → NemHandel BIS 4 migration', 'Don''t build long-term integrations against OIOUBL 3.0 — it''s cancelled. Watch for the 2027–2028 release candidate of NemHandel BIS 4 instead.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://erhvervsstyrelsen.dk', 0 FROM countries WHERE name_en = 'Denmark';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Erhvervsstyrelsen (Danish Business Authority)');
