-- ES/DE/FR translations for all 11 Denmark milestones.
-- dk-established, dk-small reuse the tracker's own existing translations
-- (i18n/{lang}-data.json) verbatim, per tracker-phrasing-wins.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-b2g-2005', 'es', 'La facturación al sector público ya es digital', 'Dinamarca lleva dos décadas con facturación electrónica B2G — la Ley de Contabilidad de 2022 extiende esa misma disciplina al sector privado en lugar de inventar algo nuevo.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-b2g-2005', 'de', 'Rechnungsstellung im öffentlichen Sektor bereits digital', 'Dänemark betreibt seit zwei Jahrzehnten digitale B2G-Rechnungsstellung — das Buchführungsgesetz von 2022 weitet dieselbe zugrunde liegende Disziplin auf den Privatsektor aus, statt etwas Neues zu erfinden.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-b2g-2005', 'fr', 'La facturation au secteur public est déjà numérique', 'Le Danemark pratique la facturation électronique B2G depuis deux décennies — la loi sur la comptabilité de 2022 étend cette même discipline au secteur privé plutôt que d''inventer quelque chose de nouveau.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-act-2022', 'es', 'Se aprueba la Bogføringsloven (Ley de Contabilidad), Ley n.º 700', 'Establece el marco moderno de contabilidad digital, sustituyendo al régimen que había regido la contabilidad danesa desde 2006.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-act-2022', 'de', 'Bogføringsloven (Buchführungsgesetz), Gesetz Nr. 700, verabschiedet', 'Begründet den modernen digitalen Buchführungsrahmen und ersetzt das Regime, das die dänische Buchführung seit 2006 geregelt hatte.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-act-2022', 'fr', 'La Bogføringsloven (loi sur la comptabilité), loi n° 700, est adoptée', 'Établit le cadre moderne de comptabilité numérique, remplaçant le régime qui régissait la comptabilité danoise depuis 2006.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-regulation-2024', 'es', 'Se publica el reglamento de aplicación (Bekendtgørelse n.º 205)', 'Establece los criterios técnicos detallados tanto para los sistemas de contabilidad digital registrados como para los no registrados.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-regulation-2024', 'de', 'Durchführungsverordnung veröffentlicht (Bekendtgørelse Nr. 205)', 'Legt die detaillierten technischen Kriterien sowohl für registrierte als auch für nicht registrierte digitale Buchführungssysteme fest.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-regulation-2024', 'fr', 'Le règlement d''application est publié (Bekendtgørelse n° 205)', 'Définit les critères techniques détaillés pour les systèmes de comptabilité numérique enregistrés et non enregistrés.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-established', 'es', 'Ley de Contabilidad Digital en vigor — empresas medianas/grandes (en vigor desde julio de 2024)', 'Las empresas medianas y grandes que presentan informes anuales deben usar un sistema de contabilidad digital certificado capaz de enviar y recibir facturas electrónicas estructuradas (OIOUBL o Peppol BIS 3.0) y generar archivos SAF-T a petición.', '["Confirme que su sistema de contabilidad figura en la lista certificada de la Autoridad Empresarial Danesa, o garantice el cumplimiento usted mismo si usa un sistema personalizado", "Mantenga registros digitales durante 5 años con copia de seguridad automatizada externa"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-established', 'de', 'Digitales Buchführungsgesetz durchgesetzt — mittlere/große Unternehmen (seit Juli 2024 in Kraft)', 'Mittlere und große Unternehmen, die Jahresberichte einreichen, müssen ein zertifiziertes digitales Buchführungssystem verwenden, das strukturierte E-Rechnungen (OIOUBL oder Peppol BIS 3.0) senden und empfangen sowie auf Anfrage SAF-T-Dateien erzeugen kann.', '["Bestätigen Sie, dass Ihr Buchführungssystem auf der zertifizierten Liste der dänischen Unternehmensbehörde steht, oder stellen Sie bei Nutzung eines individuellen Systems die Konformität selbst sicher", "Führen Sie 5-jährige digitale Aufzeichnungen mit automatisierter externer Sicherung"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-established', 'fr', 'Loi sur la comptabilité numérique appliquée — moyennes/grandes entreprises (en vigueur depuis juillet 2024)', 'Les moyennes et grandes entreprises déposant des rapports annuels doivent utiliser un système de comptabilité numérique certifié capable d''envoyer et de recevoir des factures électroniques structurées (OIOUBL ou Peppol BIS 3.0) et de générer des fichiers SAF-T sur demande.', '["Vérifiez que votre système comptable figure sur la liste certifiée de l''Autorité danoise des entreprises, ou assurez vous-même la conformité si vous utilisez un système personnalisé", "Conservez des registres numériques pendant 5 ans avec sauvegarde automatisée hors site"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-phasein', 'es', 'El despliegue por fases se completa en todos los tipos de empresa', 'Comenzando por las empresas de propiedad privada con una facturación superior a 300.000 DKK, extendiéndose a empresas financieras de cualquier tamaño y a empresas de propiedad personal por encima del mismo umbral, para el 1 de enero de 2026.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-phasein', 'de', 'Der stufenweise Rollout ist für alle Unternehmenstypen abgeschlossen', 'Beginnend mit privat gehaltenen Unternehmen mit einem Umsatz über 300.000 DKK, ausgeweitet auf Finanzunternehmen jeder Größe und persönlich gehaltene Unternehmen oberhalb derselben Schwelle bis zum 1. Januar 2026.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-phasein', 'fr', 'Le déploiement par phases s''achève pour tous les types d''entreprises', 'En commençant par les entreprises détenues à titre privé dont le chiffre d''affaires dépasse 300 000 DKK, puis en s''étendant aux entreprises financières de toute taille et aux entreprises détenues à titre personnel au-delà du même seuil, d''ici le 1er janvier 2026.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-oioubl3-cancelled', 'es', 'Se cancela OIOUBL 3.0', 'La próxima versión principal prevista del formato nacional danés se cancela por completo — OIOUBL 2.1 sigue siendo el estándar vigente sin sustituto directo, a la espera de la migración basada en Peppol que se describe más adelante.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-oioubl3-cancelled', 'de', 'OIOUBL 3.0 gestrichen', 'Die geplante nächste Hauptversion des dänischen nationalen Formats wird vollständig gestrichen — OIOUBL 2.1 bleibt der geltende Standard ohne direkten Ersatz, bis zur nachstehend beschriebenen Peppol-basierten Migration.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-oioubl3-cancelled', 'fr', 'OIOUBL 3.0 est annulé', 'La prochaine version majeure prévue du format national danois est entièrement abandonnée — OIOUBL 2.1 reste la norme en vigueur sans remplacement direct, en attendant la migration basée sur Peppol décrite ci-dessous.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-nemhandel-default', 'es', 'Comienza la campaña de NemHandel por defecto', 'Erhvervsstyrelsen inscribe automáticamente a todas las entidades con sistemas de contabilidad registrados en NemHandel, impulsando la emisión de facturas electrónicas por defecto con una ventana de exclusión voluntaria — un empujón hacia el uso real, no solo hacia la capacidad.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-nemhandel-default', 'de', 'Die Kampagne "NemHandel standardmäßig" beginnt', 'Erhvervsstyrelsen meldet alle Einrichtungen mit registrierten Buchführungssystemen automatisch bei NemHandel an und regt damit standardmäßig die Ausstellung von E-Rechnungen an, mit einem Opt-out-Fenster — ein Anstoß zur tatsächlichen Nutzung, nicht nur zur Fähigkeit.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-nemhandel-default', 'fr', 'La campagne « NemHandel par défaut » débute', 'Erhvervsstyrelsen inscrit automatiquement toutes les entités disposant de systèmes comptables enregistrés à NemHandel, encourageant l''émission de factures électroniques par défaut avec une fenêtre de désinscription — une incitation vers un usage réel, pas seulement la capacité.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-small', 'es', 'Las pequeñas empresas (facturación >300.000 DKK) con sistemas personalizados deben cumplir', 'Las pequeñas empresas y empresas unipersonales que superan los 300.000 DKK de facturación en dos años consecutivos, que usan sistemas de contabilidad no registrados ("personalizados"), quedan plenamente sujetas a los requisitos digitales de la Ley de Contabilidad.', '["Compruebe si su facturación ha superado el umbral de 300.000 DKK en los últimos dos ejercicios fiscales", "Las empresas con sistemas registrados/certificados ya debían cumplir desde enero de 2026"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-small', 'de', 'Kleinunternehmen (Umsatz >300.000 DKK) mit individuellen Systemen müssen die Vorgaben erfüllen', 'Kleinunternehmen und Einzelunternehmen, die in zwei aufeinanderfolgenden Jahren einen Umsatz von 300.000 DKK überschreiten und nicht registrierte ("individuelle") Buchhaltungssysteme verwenden, unterliegen nun vollständig den digitalen Anforderungen des Buchführungsgesetzes.', '["Prüfen Sie, ob Ihr Umsatz die Schwelle von 300.000 DKK in den letzten zwei Geschäftsjahren überschritten hat", "Unternehmen mit registrierten/zertifizierten Systemen mussten die Vorgaben bereits seit Januar 2026 erfüllen"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-small', 'fr', 'Les petites entreprises (chiffre d''affaires >300 000 DKK) utilisant des systèmes personnalisés doivent se conformer', 'Les petites entreprises et entreprises individuelles dépassant 300 000 DKK de chiffre d''affaires sur deux années consécutives, utilisant des systèmes comptables non enregistrés (« personnalisés »), sont désormais pleinement soumises aux exigences numériques de la loi sur la comptabilité.', '["Vérifiez si votre chiffre d''affaires a dépassé le seuil de 300 000 DKK au cours des deux derniers exercices", "Les entreprises utilisant des systèmes enregistrés/certifiés devaient déjà se conformer depuis janvier 2026"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-saft2027', 'es', 'Se exige la generación del SAF-T danés 2.0', 'Las entidades con sistemas de contabilidad registrados deben poder generar un Archivo Estándar de Auditoría para efectos fiscales danés a petición — SAF-T 2.0 armonizará a nivel nacional los planes de cuentas y los códigos de IVA.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-saft2027', 'de', 'Erzeugung des dänischen SAF-T 2.0 erforderlich', 'Einrichtungen mit registrierten Buchführungssystemen müssen auf Anfrage ein dänisches Standard Audit File for Tax erzeugen können — SAF-T 2.0 wird Kontenpläne und USt-Codes landesweit vereinheitlichen.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-saft2027', 'fr', 'La génération du SAF-T danois 2.0 est exigée', 'Les entités disposant de systèmes comptables enregistrés doivent pouvoir générer un fichier d''audit standard danois à des fins fiscales sur demande — SAF-T 2.0 harmonisera les plans comptables et les codes de TVA à l''échelle nationale.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-bis4-rc', 'es', 'Candidato de lanzamiento de NemHandel BIS 4', 'Se publica una versión propuesta del formato Peppol BIS 4 localizado de Dinamarca (que incorpora la arquitectura PINT) para recibir comentarios de las partes interesadas.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-bis4-rc', 'de', 'NemHandel BIS 4 Release Candidate', 'Eine vorgeschlagene Version des lokalisierten dänischen Peppol-BIS-4-Formats (unter Einbeziehung der PINT-Architektur) wird zur Stellungnahme durch Interessengruppen veröffentlicht.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-bis4-rc', 'fr', 'Candidat de version NemHandel BIS 4', 'Une version proposée du format Peppol BIS 4 localisé du Danemark (intégrant l''architecture PINT) est publiée pour recueillir les commentaires des parties prenantes.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-oioubl-phaseout', 'es', 'OIOUBL 2.1 se elimina por completo', 'Dinamarca completa su migración a NemHandel BIS 4 / Peppol PINT — programada deliberadamente para coincidir con el plazo transfronterizo del ViDA de la UE del 1 de julio de 2030.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-oioubl-phaseout', 'de', 'OIOUBL 2.1 vollständig abgeschafft', 'Dänemark schließt seine Migration zu NemHandel BIS 4 / Peppol PINT ab — bewusst zeitlich abgestimmt auf die EU-ViDA-Frist für grenzüberschreitende Transaktionen am 1. Juli 2030.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('dk-oioubl-phaseout', 'fr', 'OIOUBL 2.1 est totalement supprimé', 'Le Danemark achève sa migration vers NemHandel BIS 4 / Peppol PINT — délibérément calée sur l''échéance transfrontalière ViDA de l''UE du 1er juillet 2030.', '[]');
