-- Ireland milestone backfill (Stage 4). English only for now.
-- 9 milestones total: 7 deep-dive-only entries, PLUS ie-phase1 and
-- ie-phase2 reused directly from the tracker's own DATA array --
-- these two match deep-dive timeline cards exactly by date and topic
-- (Nov 2028 Phase 1, Nov 2029 Phase 2), so tracker phrasing wins per
-- the established rule, unlike Denmark's non-overlapping tracker pair.
-- Neither tracker entry sets anchor:true, so both keep anchor=0 here
-- to match, per the Belgium precedent.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-peppol-authority-2018', id, '2018-01-18', 1, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-peppol-authority-2018', 'en', 'Office of Government Procurement becomes Irish Peppol Authority', 'OGP takes on responsibility for the technical and procurement infrastructure connecting Irish public bodies to Peppol — years before any general B2B policy existed.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-b2g-mandatory-2020', id, '2020-04-01', 1, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-b2g-mandatory-2020', 'en', 'All public sector entities required to receive e-invoices', 'A working B2G precedent that Phase 1 businesses can point to directly — Irish public bodies have processed structured Peppol invoices for years already.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-consultation-2023', id, '2024-01-12', 1, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-consultation-2023', 'en', 'Revenue Commissioners run a public consultation', 'Gathering stakeholder views on real-time digital VAT reporting and electronic invoicing, following Finance Minister Michael McGrath''s Budget 2024 announcement.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-budget2026-confirm', id, '2025-10-08', 1, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-budget2026-confirm', 'en', 'Budget 2026 confirms the phased rollout; VAT Modernisation document published', 'Finance Minister Paschal Donohoe confirms Revenue will implement a phased domestic e-invoicing rollout; Revenue''s implementation document sets out the three-phase structure.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-phase1-criteria-2026', id, '2026-02-10', 1, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-phase1-criteria-2026', 'en', 'Revenue confirms Phase 1 taxpayer criteria', '"Large corporate" is defined administratively — whether your tax affairs are managed by Revenue''s Large Corporates Division — not by a public turnover or headcount threshold.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-phase1-criteria-reconfirmed', id, '2026-10-02', 1, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-phase1-criteria-reconfirmed', 'en', 'Phase 1 scope reconfirmed', 'Revenue restates the Phase 1 criteria roughly eight months after the initial confirmation, signalling the scope is now stable ahead of go-live.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-phase1', id, '2028-11-01', 0, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-phase1', 'en', 'Phase 1 — large corporates must issue e-invoices; all businesses must receive', 'VAT-registered large corporates managed by Revenue''s Large Corporates Division must issue structured e-invoices and report a subset of transaction data for domestic B2B sales. All businesses must be technically able to receive structured e-invoices from this date.', '["Large corporates: assess ERP readiness for EN 16931 structured invoicing over Peppol now", "All businesses: confirm your systems can receive structured e-invoices — PDFs will no longer be accepted from in-scope suppliers"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-phase2', id, '2029-11-01', 0, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-phase2', 'en', 'Phase 2 — mandate extends to all VAT-registered businesses in intra-EU trade', 'The domestic e-invoicing and reporting obligation extends to all remaining VAT-registered businesses engaged in cross-border EU B2B trade, ahead of full EU ViDA compliance in July 2030.', '["Businesses trading cross-border within the EU should begin Peppol integration planning", "Watch for detailed Revenue guidance, expected well in advance of each phase"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ie-phase3-vida', id, '2030-07-01', 1, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf' FROM countries WHERE name_en = 'Ireland';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ie-phase3-vida', 'en', 'Phase 3 — full EU ViDA cross-border requirements', 'Irish businesses already operating under the domestic system transition to meet full EU ViDA obligations alongside every other member state.', '[]');
