-- Ireland deep-dive content backfill (Stage 4). English only for now.
-- The static page's status-banner (explaining the Confirmed/Pending
-- technical-spec distinction) is folded into scope_intro rather than
-- built as new schema, per the UK/Spain precedent. Inline badge tags
-- on 3 file_format cards use the existing badge_label/badge_type
-- columns (migration 085). No penalty table -- Revenue hasn't
-- published a fine structure yet, genuinely correct per Finland/UK
-- precedent, not a gap. No lifecycle/pill-list cards.

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Peppol + real-time reporting (hybrid)', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. Ireland''s exact technical specifications, reported-data fields, and penalty framework are still being finalised — confirm current requirements directly with Revenue before building an integration.', 'Ireland''s VAT Modernisation programme has moved from consultation to confirmed scope faster than most — Phase 1''s taxpayer criteria were locked down over two years before go-live.', 'Ireland''s direction is clear even if the last technical details aren''t locked — this is one clear step ahead of the UK''s still-open format question.', 'Ireland sits between the UK''s pure decentralised model and France or Poland''s full clearance model — invoices don''t need government pre-approval, but transaction data still flows to Revenue in real time. Ireland''s phased timeline and reporting model are firmly confirmed by Revenue — including who''s in Phase 1. The detailed technical specification (exact schema profile, API detail) is still being finalised alongside the Irish Peppol Authority; sections below are marked Confirmed or Pending technical spec accordingly.', 'There''s no self-assessment step here — Revenue tells you if you''re in Phase 1, not the other way around.', 'No penalty framework has been published yet — expect this alongside the detailed technical specifications ahead of Phase 1.' FROM countries WHERE name_en = 'Ireland';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Nov 2028', 'Phase 1 go-live');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Real-time', 'Per-transaction reporting to Revenue');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'EN 16931', 'Standard (via Peppol BIS 3.0)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '€1.7bn', 'Ireland''s estimated VAT gap');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2018', 'OGP named Irish Peppol Authority');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Direction', '[["Standard", "EN 16931"], ["Typical implementation", "Peppol BIS Billing 3.0 XML"], ["Network", "Peppol"]]', 'Ireland is explicitly planning a Peppol-based model — this is stated policy direction, not speculation, even though the fine technical specification is still being worked through.', NULL, 'Confirmed', 'confirmed');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'What''s explicitly ruled out', '[["PDFs", "Not valid e-invoices for compliance purposes"], ["Scanned paper invoices", "Not valid e-invoices for compliance purposes"]]', 'Revenue''s February 2026 communication was unambiguous on this point — don''t assume a "structured enough" PDF workflow will satisfy Phase 1.', NULL, NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Reporting layer', '[["What''s reported", "A specified subset of transaction data"], ["Cadence", "Real time, per transaction"], ["Comparable to", "PAYE Modernisation, but for VAT"]]', 'This isn''t a periodic VAT return — it''s a live data feed alongside each invoice''s issuance, conceptually similar to how PAYE Modernisation transformed payroll reporting.', NULL, 'Confirmed concept', 'confirmed');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'What''s still pending', '[["Exact reported data fields", "Not yet published"], ["API/schema detail", "Being finalised with the Irish Peppol Authority"]]', 'Revenue has committed to publishing detailed guidance and technical specifications ahead of each phase — don''t lock in field-level assumptions until that lands.', NULL, 'Pending technical spec', 'pending');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Governance split', '[["Office of Government Procurement (OGP)", "Irish Peppol Authority since 2018 — technical/procurement infrastructure"], ["Revenue Commissioners", "Owns VAT Modernisation policy, the mandate, and the reporting layer"]]', 'These are two different bodies with two different jobs — OGP scales the network, Revenue defines what must be reported over it.', NULL, NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Network capacity work', '[["Framework", "Multi-Supplier Framework Agreement (public bodies)"], ["Focus", "Preparing Peppol for significant volume expansion"]]', 'Revenue is consulting closely with OGP specifically because Phase 1 represents a large jump in network usage from today''s largely voluntary/public-sector base.', NULL, NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'No clearance step', '[["Invoice validity", "Not government-approved before legal effect"], ["Comparison", "Unlike France, Poland, or Italy''s CTC models"]]', 'This is the key structural distinction from continental clearance models — Ireland pairs network-based exchange with a reporting obligation, rather than requiring government sign-off on every invoice.', NULL, NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 3 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'The VAT gap context', '[["EU Commission estimate", "~€1.7bn, 10.1% of expected VAT revenue"], ["Policy driver", "Move from periodic returns to near-real-time reporting"]]', 'Ireland''s VAT gap is broadly in line with the EU average — but still high enough that Revenue has made closing it the explicit justification for Phase 1''s reporting layer.', NULL, NULL, NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '💶 Penalty framework not yet published', NULL, NULL, 'Revenue hasn''t set out enforcement or fine structures for VAT Modernisation — treat this the same way as the UK''s pending framework: it''s coming, but not yet.', NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🏛️ Public sector as a working precedent', NULL, NULL, 'Public bodies have processed EN 16931 Peppol invoices since April 2020 — a genuine operational track record Phase 1 businesses can look to when planning their own integration.', NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🇬🇧 A useful contrast with the UK', NULL, NULL, 'Both countries chose Peppol, but Ireland pairs it with real-time reporting to Revenue while the UK has explicitly excluded reporting from its 2029 mandate — worth keeping straight if you operate in both markets.', NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 3 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📞 Direct engagement channel', NULL, NULL, 'Revenue has opened a dedicated inbox — vatmodernisation@revenue.ie — specifically for rollout queries, a sign the programme is in active, responsive development rather than a fixed, published-and-done policy.', NULL, NULL);

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Don''t self-assess "large corporate" status', 'It''s an administrative definition tied to whether Revenue''s Large Corporates Division manages your tax affairs — not a turnover or headcount threshold you calculate yourself. Revenue will write to affected businesses individually.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'If you''re in Phase 1 scope, start ERP readiness assessment now', 'Both issuance and real-time reporting need to be built — this is more than a format change, it''s a new live data pipeline into Revenue.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Every business needs receiving capability by November 2028', 'Even if you''re not issuing yet, confirm your accounting software or an Access Point can accept inbound Peppol documents — this obligation is universal, not limited to large corporates.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Watch for Revenue''s phase-by-phase technical specifications', 'Monitor the dedicated channel at vatmodernisation@revenue.ie and Revenue''s published guidance — don''t build against assumed field-level detail before it''s confirmed.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'If you trade cross-border in the EU, plan Phase 1 and Phase 2 together', 'November 2028 and November 2029 are only a year apart — it''s more efficient to design your integration with both phases in mind from the start.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf', 0 FROM countries WHERE name_en = 'Ireland';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Revenue — VAT Modernisation / eInvoicing');
