-- Norway milestone backfill (Stage 4). English only for now.
-- 7 milestones total: 5 deep-dive-only entries, PLUS no-issue and
-- no-receive reused directly from the tracker's own DATA array --
-- these two match deep-dive timeline cards exactly by date and topic
-- (Jan 2027 issuance, Jan 2030 reception), so tracker phrasing wins,
-- same pattern as Ireland's ie-phase1/ie-phase2.
-- Neither tracker entry sets anchor:true, so both keep anchor=0 here.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'no-b2g-2019', id, '2019-04-02', 1, 'https://www.skatteetaten.no' FROM countries WHERE name_en = 'Norway';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('no-b2g-2019', 'en', 'B2G e-invoicing mandatory via EHF/Peppol', 'Public sector entities and their suppliers must use EHF/Peppol BIS Billing 3.0 over the Peppol network — the infrastructure the 2027 B2B mandate builds directly on top of.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'no-consultation-2024', id, '2024-12-01', 1, 'https://www.skatteetaten.no' FROM countries WHERE name_en = 'Norway';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('no-consultation-2024', 'en', 'Preliminary consultation note published', 'The Ministry of Finance publishes an initial consultation examining mandatory digital accounting and invoicing between businesses, based on a report from the Directorate of Taxes.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'no-instruction-2026', id, '2026-03-16', 1, 'https://www.skatteetaten.no' FROM countries WHERE name_en = 'Norway';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('no-instruction-2026', 'en', 'Ministry instructs Skattedirektoratet to prepare regulations', 'A follow-up letter asks the Directorate of Taxes to prepare detailed regulatory amendments covering invoice format, electronic bookkeeping systems, and possible small-business exemptions.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'no-law-enacted-2026', id, '2026-06-19', 1, 'https://www.skatteetaten.no' FROM countries WHERE name_en = 'Norway';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('no-law-enacted-2026', 'en', 'Law formally enacted (Law-2026-06-19-39)', 'Parliament approves the Act on Amendments to the Bookkeeping Act and Certain Other Laws in the Financial Market Area, confirming the transition from proposal (Prop. 44 L) to binding statutory regime.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'no-technical-detail-2026', id, '2026-12-15', 1, 'https://www.skatteetaten.no' FROM countries WHERE name_en = 'Norway';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('no-technical-detail-2026', 'en', 'Skattedirektoratet to confirm remaining technical detail', 'Final rules on invoice format specifics, digital bookkeeping system criteria, and any exemptions or postponements for small businesses are due by this date.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'no-issue', id, '2027-01-01', 0, 'https://www.skatteetaten.no' FROM countries WHERE name_en = 'Norway';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('no-issue', 'en', 'Mandatory B2B e-invoice issuance (EHF 3.0 / Peppol BIS)', 'Following the enactment of amendments to the Bookkeeping Act, all businesses with Norwegian bookkeeping obligations must issue structured e-invoices (EHF format) to other businesses registered in the ELMA directory.', '["Register in ELMA (the Norwegian Peppol recipient directory) if not already listed", "Confirm your invoicing software supports EHF 3.0 / Peppol BIS output", "PDF and paper B2B invoices will no longer be valid for in-scope transactions"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'no-receive', id, '2030-01-01', 0, 'https://www.skatteetaten.no' FROM countries WHERE name_en = 'Norway';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('no-receive', 'en', 'Mandatory e-invoice reception and fully digital bookkeeping', 'The mandate extends to receiving structured e-invoices and maintaining fully digital bookkeeping records, completing Norway''s two-phase reform.', '["Plan migration to an approved digital bookkeeping system well ahead of this date", "Confirm AP systems can receive and process EHF/Peppol invoices automatically"]');
