-- ES/DE/FR translations for all 7 Slovakia milestones.
-- sk-voluntary and sk-mandate reuse the tracker's own phrasing per
-- tracker-phrasing-wins.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-b2g-2023', 'es', 'Facturación electrónica B2G/G2G obligatoria a través de IS EFA', 'Eslovaquia introduce la facturación electrónica estructurada obligatoria para las transacciones entre empresas y gobierno y entre organismos gubernamentales a través de la plataforma IS EFA (Informačný Systém Elektronickej Fakturácie), alineada con la norma EN 16931 — la base sobre la que se extiende el mandato B2B de 2027.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-b2g-2023', 'de', 'B2G-/G2G-E-Rechnung über IS EFA verpflichtend', 'Die Slowakei führt die verpflichtende strukturierte E-Rechnungsstellung für Transaktionen zwischen Unternehmen und Behörden sowie zwischen Behörden über die Plattform IS EFA (Informačný Systém Elektronickej Fakturácie) ein, ausgerichtet an der EN 16931 — die Grundlage, auf der die B2B-Pflicht ab 2027 aufbaut.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-b2g-2023', 'fr', 'Facturation électronique B2G/G2G obligatoire via IS EFA', 'La Slovaquie instaure la facturation électronique structurée obligatoire pour les transactions entre entreprises et administration ainsi qu''entre administrations, via la plateforme IS EFA (Informačný Systém Elektronickej Fakturácie), alignée sur la norme EN 16931 — le socle sur lequel s''appuie l''obligation B2B de 2027.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-b2b-postponed-2024', 'es', 'El anterior plan voluntario B2B se pospone discretamente', 'Un marco voluntario B2B originalmente previsto para enero de 2022 se pospuso indefinidamente, reflejando la genuina complejidad de hacerlo bien — algo a tener presente al leer las fechas confirmadas de hoy.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-b2b-postponed-2024', 'de', 'Früherer freiwilliger B2B-Plan wird still verschoben', 'Ein ursprünglich für Januar 2022 geplanter freiwilliger B2B-Rahmen wurde auf unbestimmte Zeit verschoben — ein Hinweis auf die tatsächliche Komplexität, dies richtig umzusetzen, und ein guter Kontext für die heute bestätigten Termine.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-b2b-postponed-2024', 'fr', 'Un précédent plan B2B volontaire discrètement reporté', 'Un cadre B2B volontaire initialement prévu pour janvier 2022 a été reporté indéfiniment, reflétant la réelle complexité de bien faire les choses — un point à garder à l''esprit en lisant les dates aujourd''hui confirmées.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-peppol-codelist-2025', 'es', 'Las listas de códigos Peppol v9.5 definen el esquema de identificadores eslovaco', 'Se formaliza el esquema 0245 (SG:DIC) para el Número de Identificación Fiscal eslovaco (DIČ) de 10 dígitos, el identificador con el que los usuarios finales eslovacos se registrarán en la red Peppol.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-peppol-codelist-2025', 'de', 'Peppol Code Lists v9.5 legt das slowakische Kennungsschema fest', 'Das Schema 0245 (SG:DIC) wird für die 10-stellige slowakische Steueridentifikationsnummer (DIČ) formalisiert — die Kennung, unter der sich slowakische Endnutzer im Peppol-Netzwerk registrieren.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-peppol-codelist-2025', 'fr', 'Les listes de codes Peppol v9.5 définissent le schéma d''identifiants slovaque', 'Le schéma 0245 (SG:DIC) est formalisé pour le numéro d''identification fiscale slovaque à 10 chiffres (DIČ), l''identifiant sous lequel les utilisateurs finaux slovaques s''enregistreront sur le réseau Peppol.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-voluntary', 'es', 'Comienza el período voluntario de transición a la facturación/reporte electrónico', 'Las empresas pueden registrarse voluntariamente para probar la facturación electrónica estructurada y el reporte antes del mandato de enero de 2027, utilizando un modelo descentralizado de "5 esquinas" basado en Peppol.', '["Regístrese para la participación voluntaria con la Administración Financiera para probar integraciones desde el principio", "Confirme que su software de contabilidad puede generar XML UBL Peppol BIS 3.0"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-voluntary', 'de', 'Freiwillige Übergangsphase für E-Rechnung / E-Reporting beginnt', 'Unternehmen können sich freiwillig registrieren, um vor der Pflicht ab Januar 2027 strukturierte E-Rechnungsstellung und Meldung zu testen, unter Verwendung eines dezentralen Peppol-basierten "5-Ecken"-Modells.', '["Registrieren Sie sich zur freiwilligen Teilnahme bei der Finanzverwaltung, um Integrationen frühzeitig zu testen", "Bestätigen Sie, dass Ihre Buchhaltungssoftware Peppol-BIS-3.0-UBL-XML erzeugen kann"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-voluntary', 'fr', 'La période de transition volontaire vers la facturation/déclaration électronique débute', 'Les entreprises peuvent s''inscrire volontairement pour tester la facturation électronique structurée et la déclaration avant l''obligation de janvier 2027, selon un modèle décentralisé Peppol « à 5 coins ».', '["Inscrivez-vous à la participation volontaire auprès de l''Administration financière pour tester les intégrations dès maintenant", "Vérifiez que votre logiciel comptable peut générer du XML UBL Peppol BIS 3.0"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-mandate', 'es', 'Facturación electrónica B2B/B2G nacional obligatoria y reporte casi en tiempo real', 'La facturación electrónica estructurada y el reporte en tiempo real pasan a ser obligatorios para las transacciones nacionales B2B y B2G entre contribuyentes eslovacos de IVA, utilizando puntos de acceso "Digital Postman" certificados en una red basada en Peppol.', '["Seleccione un proveedor de Digital Postman aprobado (punto de acceso certificado)", "A partir de 2027, no podrán reclamarse deducciones de IVA soportado sobre facturas entrantes no conformes", "Nota: la facturación electrónica transfronteriza llega más tarde, bajo el calendario del ViDA de la UE a partir de julio de 2030"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-mandate', 'de', 'Verpflichtende inländische B2B-/B2G-E-Rechnung und nahezu Echtzeitmeldung', 'Strukturierte E-Rechnungsstellung und Echtzeitmeldung werden für inländische B2B- und B2G-Transaktionen zwischen slowakischen Umsatzsteuerpflichtigen verpflichtend, unter Nutzung zertifizierter "Digital-Postman"-Zugangspunkte in einem Peppol-basierten Netzwerk.', '["Wählen Sie einen zugelassenen Digital-Postman-Anbieter (zertifizierter Access Point)", "Ab 2027 können Vorsteuerabzüge auf nicht konforme eingehende Rechnungen nicht mehr geltend gemacht werden", "Hinweis: die grenzüberschreitende E-Rechnung folgt später, im Rahmen des EU-ViDA-Zeitplans ab Juli 2030"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-mandate', 'fr', 'Facturation électronique B2B/B2G nationale obligatoire et déclaration quasi temps réel', 'La facturation électronique structurée et la déclaration en temps réel deviennent obligatoires pour les transactions B2B et B2G nationales entre assujettis à la TVA slovaques, via des points d''accès « Digital Postman » certifiés sur un réseau basé sur Peppol.', '["Choisissez un fournisseur Digital Postman agréé (point d''accès certifié)", "À partir de 2027, les déductions de TVA en amont ne pourront plus être réclamées sur des factures entrantes non conformes", "Remarque : la facturation électronique transfrontalière suivra plus tard, dans le cadre du calendrier ViDA de l''UE à partir de juillet 2030"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-postman-mandatory-2027', 'es', 'La transmisión mediante Digital Postman certificado pasa a ser obligatoria', 'El uso exclusivo de proveedores de servicios Digital Postman certificados para la transmisión y recepción se convierte en un requisito firme — aquí termina el período de gracia educativo integrado en la primera mitad de 2027.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-postman-mandatory-2027', 'de', 'Die Übermittlung über einen zertifizierten Digital Postman wird verpflichtend', 'Die ausschließliche Nutzung zertifizierter Digital-Postman-Dienstanbieter für Übermittlung und Empfang wird zu einer festen Anforderung — die in die erste Hälfte 2027 eingebaute pädagogische Übergangsfrist endet hier.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-postman-mandatory-2027', 'fr', 'La transmission via un Digital Postman certifié devient obligatoire', 'Le recours exclusif à des prestataires Digital Postman certifiés pour la transmission et la réception devient une exigence ferme — la période de grâce pédagogique intégrée à la première moitié de 2027 se termine ici.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-crossborder-2030', 'es', 'Extensión transfronteriza; se elimina el reporte heredado', 'El mandato se extiende a las transacciones B2B intracomunitarias y a las entidades extranjeras con registro de IVA eslovaco. El "Kontrolný výkaz" nacional (declaración de control de IVA) y el "súhrnný výkaz" de la UE (lista recapitulativa CE) se retiran por completo, y el plazo de emisión de facturas se reduce de 15 a 10 días.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-crossborder-2030', 'de', 'Grenzüberschreitende Erweiterung; bisherige Meldung wird abgeschafft', 'Die Pflicht wird auf innergemeinschaftliche B2B-Transaktionen und ausländische Unternehmen mit slowakischer Umsatzsteuerregistrierung ausgeweitet. Der inländische "Kontrolný výkaz" (Umsatzsteuer-Kontrollmeldung) und die EU-"súhrnný výkaz" (Zusammenfassende Meldung) werden vollständig eingestellt, und die Rechnungsausstellungsfrist verkürzt sich von 15 auf 10 Tage.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sk-crossborder-2030', 'fr', 'Extension transfrontalière ; la déclaration existante est supprimée', 'L''obligation s''étend aux transactions B2B intracommunautaires et aux entités étrangères disposant d''une immatriculation TVA slovaque. Le "Kontrolný výkaz" national (relevé de contrôle TVA) et le "súhrnný výkaz" de l''UE (état récapitulatif CE) sont entièrement supprimés, et le délai d''émission des factures passe de 15 à 10 jours.', '[]');
