-- Slovakia deep-dive page translations: page fields, stats, cards,
-- penalty rows, steps, portal.

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'es', 'Peppol de 5 esquinas ("Digital Postman")', 'Esta página de análisis refleja la orientación técnica disponible públicamente a julio de 2026 y se proporciona a título informativo general, no como asesoramiento legal o fiscal. El CIUS nacional de Eslovaquia, las especificaciones de API y la normativa del Ministerio de Finanzas aún se están finalizando — confirme los requisitos actuales directamente con la Dirección Financiera antes de construir una integración.', 'Eslovaquia ya ha pasado por esto antes — se planificó un marco B2B voluntario para 2022 que se archivó discretamente. Esta vez el mandato está legislado con una fecha firme.', 'Eslovaquia no ha publicado un CIUS nacional — se apoya en el estándar base EN 16931 en lugar de añadir una capa claramente eslovaca.', 'La etiqueta de "5 esquinas" importa aquí: los Digital Postmen no solo mueven facturas entre socios comerciales, también reportan los datos a la autoridad fiscal en el mismo paso.', 'La fase voluntaria de 2026 existe precisamente para que las empresas puedan resolver los problemas de integración antes de que el mandato tenga consecuencias reales.', 'Eslovaquia está adoptando explícitamente un enfoque educativo durante la primera mitad de 2027 — pero las multas detrás de ese período de gracia son reales.' FROM countries WHERE name_en = 'Slovakia';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'de', 'Peppol 5-Ecken-Modell ("Digital Postman")', 'Diese Länderanalyse spiegelt öffentlich verfügbare technische Hinweise mit Stand Juli 2026 wider und dient der allgemeinen Information, nicht als Rechts- oder Steuerberatung. Die slowakische nationale CIUS, die API-Spezifikationen und die Vorschriften des Finanzministeriums werden noch finalisiert — bestätigen Sie aktuelle Anforderungen direkt bei der Finanzdirektion, bevor Sie eine Integration aufbauen.', 'Die Slowakei kennt das bereits — ein freiwilliger B2B-Rahmen war für 2022 geplant und wurde still zurückgestellt. Diesmal ist die Pflicht mit einem festen Termin gesetzlich verankert.', 'Die Slowakei hat keine nationale CIUS veröffentlicht — sie stützt sich auf den europäischen Basisstandard EN 16931, statt eine eigene slowakische Ebene hinzuzufügen.', 'Die Bezeichnung "5-Ecken" ist hier entscheidend: Digital Postmen bewegen Rechnungen nicht nur zwischen Handelspartnern, sie melden die Daten im selben Schritt an die Finanzverwaltung.', 'Die freiwillige Phase 2026 existiert genau deshalb, damit Unternehmen Integrationsprobleme lösen können, bevor die Pflicht Konsequenzen hat.', 'Die Slowakei verfolgt in der ersten Hälfte von 2027 ausdrücklich einen pädagogischen Ansatz — aber die Bußgelder hinter dieser Übergangsfrist sind real.' FROM countries WHERE name_en = 'Slovakia';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'fr', 'Peppol à 5 coins (« Digital Postman »)', 'Cette analyse par pays reflète les directives techniques publiquement disponibles à juillet 2026 et est fournie à titre d''information générale, non comme un conseil juridique ou fiscal. La CIUS nationale de la Slovaquie, les spécifications API et la réglementation du ministère des Finances sont encore en cours de finalisation — confirmez les exigences actuelles directement auprès de la Direction financière avant de construire une intégration.', 'La Slovaquie est déjà passée par là — un cadre B2B volontaire était prévu pour 2022 et a été discrètement mis de côté. Cette fois, l''obligation est inscrite dans la loi avec une date ferme.', 'La Slovaquie n''a pas publié de CIUS nationale — elle s''appuie sur la norme européenne de base EN 16931 plutôt que d''y ajouter une couche nettement slovaque.', 'L''étiquette « à 5 coins » compte ici : les Digital Postmen ne se contentent pas de faire circuler les factures entre partenaires commerciaux, ils déclarent aussi les données à l''administration fiscale dans la même étape.', 'La phase volontaire de 2026 existe précisément pour permettre aux entreprises de résoudre les problèmes d''intégration avant que l''obligation n''ait de réelles conséquences.', 'La Slovaquie adopte explicitement une approche pédagogique jusqu''à la mi-2027 — mais les amendes derrière cette période de grâce sont bien réelles.' FROM countries WHERE name_en = 'Slovakia';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', 'EN 16931', 'Sintaxis UBL 2.1 / CII' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', 'EN 16931', 'UBL-2.1-/CII-Syntax' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', 'EN 16931', 'Syntaxe UBL 2.1 / CII' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '5 esquinas', 'Peppol + reporte en tiempo real' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '5-Ecken', 'Peppol + Echtzeitmeldung' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '5 coins', 'Peppol + déclaration en temps réel' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '10 años', 'Requisito de archivo' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '10 Jahre', 'Aufbewahrungspflicht' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '10 ans', 'Obligation d''archivage' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '100.000 €', 'Multa máxima (infracción reiterada)' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '100.000 €', 'Höchststrafe (wiederholter Verstoß)' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '100 000 €', 'Amende maximale (infraction répétée)' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '2030', 'Extensión transfronteriza' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '2030', 'Grenzüberschreitende Erweiterung' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '2030', 'Extension transfrontalière' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Sintaxis y estándar', '[["Estándar", "EN 16931"], ["Sintaxis aceptadas", "UBL 2.1 o UN/CEFACT CII"], ["CIUS nacional", "Aún no implementado — en evaluación"]]', 'A diferencia del RO_CIUS de Rumanía o el HR-FISK de Croacia, Eslovaquia está construyendo actualmente sobre el estándar base europeo simple — esté atento a la definición de un CIUS nacional a medida que avance el despliegue.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Syntax & Standard', '[["Standard", "EN 16931"], ["Akzeptierte Syntaxen", "UBL 2.1 oder UN/CEFACT CII"], ["Nationale CIUS", "Noch nicht umgesetzt — wird geprüft"]]', 'Anders als Rumäniens RO_CIUS oder Kroatiens HR-FISK baut die Slowakei derzeit auf dem einfachen europäischen Basisstandard auf — achten Sie darauf, ob im Zuge des Rollouts eine nationale CIUS definiert wird.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Syntaxe et norme', '[["Norme", "EN 16931"], ["Syntaxes acceptées", "UBL 2.1 ou UN/CEFACT CII"], ["CIUS nationale", "Pas encore mise en œuvre — en cours d''évaluation"]]', 'Contrairement au RO_CIUS de la Roumanie ou au HR-FISK de la Croatie, la Slovaquie s''appuie actuellement sur la norme européenne de base simple — surveillez la définition d''une CIUS nationale à mesure que le déploiement mûrit.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Identificadores', '[["Esquema Peppol", "0245 — SG:DIC"], ["Identificador", "NIF eslovaco de 10 dígitos (DIČ)"], ["Emitido por", "Administración Financiera de la República Eslovaca"]]', 'Utilice el esquema 0245 al registrar usuarios finales eslovacos en la red Peppol — este es el identificador que se resuelve al DIČ concreto del destinatario a efectos de enrutamiento.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Kennungen', '[["Peppol-Schema", "0245 — SG:DIC"], ["Kennung", "10-stellige slowakische Steuernummer (DIČ)"], ["Ausgestellt von", "Finanzverwaltung der Slowakischen Republik"]]', 'Verwenden Sie das Schema 0245 bei der Registrierung slowakischer Endnutzer im Peppol-Netzwerk — dies ist die Kennung, die für Routingzwecke auf die DIČ eines bestimmten Empfängers verweist.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Identifiants', '[["Schéma Peppol", "0245 — SG:DIC"], ["Identifiant", "Numéro fiscal slovaque à 10 chiffres (DIČ)"], ["Délivré par", "Administration financière de la République slovaque"]]', 'Utilisez le schéma 0245 lors de l''enregistrement des utilisateurs finaux slovaques sur le réseau Peppol — c''est l''identifiant qui se résout au DIČ d''un destinataire donné à des fins de routage.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Lo que queda expresamente excluido', '[["PDF / imágenes escaneadas", "No se consideran facturas electrónicas"], ["Transacciones B2C", "Fuera de alcance"], ["Otras exenciones", "Información clasificada; ciertos organismos públicos"]]', 'El documento de preguntas frecuentes (9/DPH/2025) es explícito: una factura electrónica se define como un archivo XML estructurado legible por máquina, sin más — nada que simplemente parezca una factura cualifica.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Was ausdrücklich ausgeschlossen ist', '[["PDFs / gescannte Bilder", "Gelten nicht als E-Rechnungen"], ["B2C-Transaktionen", "Nicht im Anwendungsbereich"], ["Weitere Ausnahmen", "Verschlusssachen; bestimmte Behörden"]]', 'Das FAQ-Dokument (9/DPH/2025) ist eindeutig: Eine E-Rechnung ist als maschinenlesbare strukturierte XML-Datei definiert, Punkt — alles, was nur wie eine Rechnung aussieht, zählt nicht.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Ce qui est explicitement exclu', '[["PDF / images scannées", "Ne sont pas considérées comme des factures électroniques"], ["Transactions B2C", "Hors champ"], ["Autres exemptions", "Informations classifiées ; certains organismes publics"]]', 'Le document FAQ (9/DPH/2025) est explicite : une facture électronique est définie comme un fichier XML structuré lisible par machine, un point c''est tout — tout ce qui ressemble simplement à une facture ne suffit pas.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Archivo y plazos', '[["Conservación", "10 años, en formato XML original"], ["Plazo de emisión (hasta 2030)", "15 días desde el devengo"], ["Plazo de emisión (desde 2030)", "Se reduce a 10 días"]]', 'Enviar la factura a través de un Digital Postman dentro del plazo es lo que cumple la obligación de emisión — el plazo se cuenta desde la transmisión, no solo desde la generación.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Archivierung und Fristen', '[["Aufbewahrung", "10 Jahre, im ursprünglichen XML-Format"], ["Ausstellungsfrist (bis 2030)", "15 Tage ab dem Steuertatbestand"], ["Ausstellungsfrist (ab 2030)", "Verkürzt sich auf 10 Tage"]]', 'Der Versand der Rechnung über einen Digital Postman innerhalb der Frist erfüllt die Ausstellungspflicht — die Frist läuft ab der Übermittlung, nicht nur ab der Erstellung.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Archivage et délais', '[["Conservation", "10 ans, au format XML d''origine"], ["Délai d''émission (jusqu''en 2030)", "15 jours à compter du fait générateur"], ["Délai d''émission (à partir de 2030)", "Réduit à 10 jours"]]', 'L''envoi de la facture via un Digital Postman dans le délai imparti est ce qui satisfait l''obligation d''émission — le délai court à partir de la transmission, pas seulement de la génération.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'file_format' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'El modelo de 5 esquinas', '[["Esquinas 1–4", "Intercambio Peppol estándar (proveedor → PA → PA → comprador)"], ["Esquina 5", "Reporte en tiempo real a la Administración Financiera"], ["Término del proveedor de servicios", "\"Digitálni poštári\" (Carteros Digitales)"]]', 'Este es un avance arquitectónico genuino más allá de los modelos simples de 4 esquinas de Bélgica o el Reino Unido — el tramo de reporte está integrado en la misma transmisión, no es una presentación separada.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Das 5-Ecken-Modell', '[["Ecken 1–4", "Standard-Peppol-Austausch (Lieferant → AP → AP → Käufer)"], ["Ecke 5", "Echtzeitmeldung an die Finanzverwaltung"], ["Begriff für den Dienstanbieter", "\"Digitálni poštári\" (Digitale Postboten)"]]', 'Dies ist ein echter architektonischer Schritt über die einfachen 4-Ecken-Modelle Belgiens oder des Vereinigten Königreichs hinaus — der Meldeschritt ist in dieselbe Übermittlung integriert, keine separate Einreichung.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Le modèle à 5 coins', '[["Coins 1 à 4", "Échange Peppol standard (fournisseur → AP → AP → acheteur)"], ["Coin 5", "Déclaration en temps réel à l''Administration financière"], ["Terme pour le prestataire de service", "« Digitálni poštári » (Facteurs numériques)"]]', 'C''est une véritable avancée architecturale au-delà des simples modèles à 4 coins de la Belgique ou du Royaume-Uni — le volet déclaratif est intégré à la même transmission, pas une déclaration séparée.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'IS EFA frente a la red B2B', '[["IS EFA", "Plataforma central B2G/G2G, en funcionamiento desde 2023"], ["B2B", "Red de Digital Postman basada en Peppol, que extiende los mismos principios"]]', 'No confunda las dos — las facturas B2G a IS EFA usan UBL 2.1 o CII D16B directamente; las facturas B2B se mueven a través de Digital Postmen acreditados sobre Peppol, con IS eFaktúra recibiendo los datos reportados.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'IS EFA im Vergleich zum B2B-Netzwerk', '[["IS EFA", "Zentrale B2G-/G2G-Plattform, seit 2023 in Betrieb"], ["B2B", "Peppol-basiertes Digital-Postman-Netzwerk, das dieselben Prinzipien erweitert"]]', 'Verwechseln Sie die beiden nicht — B2G-Rechnungen an IS EFA verwenden direkt UBL 2.1 oder CII D16B; B2B-Rechnungen laufen über akkreditierte Digital Postmen über Peppol, wobei IS eFaktúra die gemeldeten Daten empfängt.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'IS EFA face au réseau B2B', '[["IS EFA", "Plateforme centrale B2G/G2G, en service depuis 2023"], ["B2B", "Réseau Digital Postman basé sur Peppol, prolongeant les mêmes principes"]]', 'Ne confondez pas les deux — les factures B2G vers IS EFA utilisent directement UBL 2.1 ou CII D16B ; les factures B2B transitent via des Digital Postmen accrédités sur Peppol, IS eFaktúra recevant les données déclarées.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Validación y gestión de errores', '[["Validación previa al envío", "El Digital Postman señala errores de formato/datos antes de la transmisión"], ["Corrección posterior a la transmisión", "Nota de crédito formal + nueva factura corregida"], ["Modificación directa", "No es posible una vez transmitida"]]', 'El rechazo por parte del destinatario debe gestionarse bilateralmente entre proveedor y comprador — no existe una función de rechazo dentro de la propia red Peppol para este fin.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Validierung und Fehlerbehandlung', '[["Validierung vor dem Versand", "Digital Postman markiert Format-/Datenfehler vor der Übermittlung"], ["Korrektur nach der Übermittlung", "Formale Gutschrift + neue korrigierte Rechnung"], ["Direkte Änderung", "Nach der Übermittlung nicht möglich"]]', 'Eine Ablehnung durch den Empfänger muss bilateral zwischen Lieferant und Käufer geklärt werden — im Peppol-Netzwerk selbst gibt es dafür keine Ablehnungsfunktion.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Validation et gestion des erreurs', '[["Validation avant envoi", "Le Digital Postman signale les erreurs de format/données avant la transmission"], ["Correction après transmission", "Note de crédit formelle + nouvelle facture corrigée"], ["Modification directe", "Impossible une fois transmise"]]', 'Le rejet par le destinataire doit être géré bilatéralement entre le fournisseur et l''acheteur — il n''existe pas de fonction de rejet au sein du réseau Peppol lui-même à cette fin.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Empresas extranjeras (contexto B2G)', '[["Canal", "Envío por correo electrónico"], ["Confirmación", "Confirmada o rechazada por correo electrónico por el gobierno"]]', 'Esta vía más ligera por correo electrónico se aplica específicamente a los escenarios B2G para entidades extranjeras — el B2B sigue requiriendo una relación con un Digital Postman una vez que se aplique el mandato de 2027.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Ausländische Unternehmen (B2G-Kontext)', '[["Kanal", "E-Mail-basierte Einreichung"], ["Bestätigung", "Von der Behörde per E-Mail bestätigt oder abgelehnt"]]', 'Dieser leichtere E-Mail-Weg gilt speziell für B2G-Szenarien ausländischer Unternehmen — für B2B ist weiterhin eine Digital-Postman-Beziehung erforderlich, sobald die Pflicht ab 2027 gilt.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Entreprises étrangères (contexte B2G)', '[["Canal", "Soumission par e-mail"], ["Confirmation", "Confirmée ou rejetée par e-mail par l''administration"]]', 'Cette voie allégée par e-mail s''applique spécifiquement aux scénarios B2G pour les entités étrangères — le B2B nécessite toujours une relation avec un Digital Postman une fois l''obligation de 2027 applicable.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'scope_transmission' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'es', 'Infracción inicial', 'Hasta 10.000 €', NULL FROM deep_dive_penalty_rows dpr JOIN countries c ON c.id = dpr.country_id WHERE c.name_en = 'Slovakia' AND dpr.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'de', 'Erstverstoß', 'Bis zu 10.000 €', NULL FROM deep_dive_penalty_rows dpr JOIN countries c ON c.id = dpr.country_id WHERE c.name_en = 'Slovakia' AND dpr.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'fr', 'Infraction initiale', 'Jusqu''à 10 000 €', NULL FROM deep_dive_penalty_rows dpr JOIN countries c ON c.id = dpr.country_id WHERE c.name_en = 'Slovakia' AND dpr.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'es', 'Infracciones reiteradas', 'Hasta 100.000 €', NULL FROM deep_dive_penalty_rows dpr JOIN countries c ON c.id = dpr.country_id WHERE c.name_en = 'Slovakia' AND dpr.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'de', 'Wiederholte Verstöße', 'Bis zu 100.000 €', NULL FROM deep_dive_penalty_rows dpr JOIN countries c ON c.id = dpr.country_id WHERE c.name_en = 'Slovakia' AND dpr.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'fr', 'Infractions répétées', 'Jusqu''à 100 000 €', NULL FROM deep_dive_penalty_rows dpr JOIN countries c ON c.id = dpr.country_id WHERE c.name_en = 'Slovakia' AND dpr.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', '🎓 Enfoque educativo hasta mediados de 2027', NULL, NULL, '2026 y la primera mitad de 2027 sirven como períodos de gracia con énfasis en la educación en lugar del castigo — aunque las sanciones técnicamente aún pueden aplicarse tras la entrada en vigor en casos flagrantes.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', '🎓 Pädagogischer Ansatz bis Mitte 2027', NULL, NULL, '2026 und die erste Hälfte von 2027 dienen als Übergangsfristen mit Schwerpunkt auf Aufklärung statt Bestrafung — Bußgelder können jedoch technisch auch nach dem Start in besonders schweren Fällen verhängt werden.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', '🎓 Approche pédagogique jusqu''à mi-2027', NULL, NULL, '2026 et la première moitié de 2027 servent de périodes de grâce mettant l''accent sur la pédagogie plutôt que sur la sanction — bien que des amendes puissent techniquement encore s''appliquer après l''entrée en vigueur dans les cas les plus flagrants.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', '📖 Dónde consultar la letra pequeña', NULL, NULL, 'Las preguntas frecuentes oficiales de la Dirección Financiera ("Najčastejšie otázky a odpovede k eFaktúre", documento 9/DPH/2025) y los estándares técnicos detallados (esquemas, listas de códigos, especificaciones de API Peppol) se están emitiendo mediante un reglamento de carácter general del Ministerio de Finanzas — consulte info-efaktura.sk y financnasprava.sk para actualizaciones.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', '📖 Wo Sie das Kleingedruckte nachlesen können', NULL, NULL, 'Das offizielle FAQ der Finanzdirektion ("Najčastejšie otázky a odpovede k eFaktúre", Dokument 9/DPH/2025) sowie detaillierte technische Standards (Schemas, Codelisten, Peppol-API-Spezifikationen) werden über eine allgemein verbindliche Verordnung des Finanzministeriums veröffentlicht — prüfen Sie info-efaktura.sk und financnasprava.sk auf Updates.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', '📖 Où consulter les détails', NULL, NULL, 'La FAQ officielle de la Direction financière (« Najčastejšie otázky a odpovede k eFaktúre », document 9/DPH/2025) ainsi que les normes techniques détaillées (schémas, listes de codes, spécifications API Peppol) sont publiées via un règlement d''application générale du ministère des Finances — consultez info-efaktura.sk et financnasprava.sk pour les mises à jour.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', '🔁 Un mandato que ya se ha retrasado antes', NULL, NULL, 'Dado que el anterior marco voluntario de 2022 se archivó, conviene tratar la fecha de 2027 con una confianza razonable, pero estando atento a posibles nuevos cambios de calendario a medida que se acerca el plazo.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', '🔁 Eine Pflicht, die schon einmal verschoben wurde', NULL, NULL, 'Da der frühere freiwillige Rahmen von 2022 zurückgestellt wurde, lohnt es sich, den Termin 2027 mit angemessenem Vertrauen zu behandeln, aber wachsam gegenüber weiteren Terminänderungen zu bleiben, je näher die Frist rückt.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', '🔁 Une obligation déjà reportée par le passé', NULL, NULL, 'Étant donné que le précédent cadre volontaire de 2022 a été mis de côté, il convient de considérer la date de 2027 avec une confiance raisonnable, tout en restant attentif à d''éventuels nouveaux changements de calendrier à l''approche de l''échéance.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Slovakia' AND dc.section = 'penalties_related' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Evalúe sus sistemas de facturación actuales', 'Compruebe la compatibilidad con la salida EN 16931 / UBL XML e identifique las actualizaciones necesarias antes de la entrada en vigor obligatoria.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Bewerten Sie Ihre aktuellen Rechnungssysteme', 'Prüfen Sie die Kompatibilität mit der EN-16931-/UBL-XML-Ausgabe und identifizieren Sie notwendige Upgrades vor dem verpflichtenden Start.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Évaluez vos systèmes de facturation actuels', 'Vérifiez la compatibilité avec la sortie EN 16931 / UBL XML et identifiez les mises à niveau nécessaires avant l''entrée en vigueur obligatoire.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Seleccione y contrate un Digital Postman acreditado', 'Hágalo con suficiente antelación al 1 de enero de 2027 — y tenga en cuenta que a partir del 1 de julio de 2027 solo podrán usarse Digital Postmen certificados.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Wählen und beauftragen Sie einen akkreditierten Digital Postman', 'Tun Sie dies rechtzeitig vor dem 1. Januar 2027 — und beachten Sie, dass ab dem 1. Juli 2027 ausschließlich zertifizierte Digital Postmen verwendet werden dürfen.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Choisissez et contractez un Digital Postman accrédité', 'Faites-le bien avant le 1er janvier 2027 — et sachez qu''à partir du 1er juillet 2027, seuls des Digital Postmen certifiés pourront être utilisés.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Use la fase voluntaria de 2026 para probar de extremo a extremo', 'Regístrese voluntariamente para pilotar los flujos de envío, validación y corrección de facturas antes de que el mandato tenga consecuencias reales.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Nutzen Sie die freiwillige Phase 2026 für einen End-to-End-Test', 'Registrieren Sie sich freiwillig, um die Workflows für Rechnungsübermittlung, Validierung und Korrektur zu testen, bevor die Pflicht echte Konsequenzen hat.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Utilisez la phase volontaire de 2026 pour tester de bout en bout', 'Inscrivez-vous volontairement pour piloter les flux de soumission, de validation et de correction des factures avant que l''obligation n''ait de réelles conséquences.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Confirme que su ID de participante Peppol usa el esquema 0245', 'Asegúrese de que su DIČ de 10 dígitos está correctamente registrado bajo el esquema de identificador eslovaco — esto es lo que le hace enrutable en la red.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Bestätigen Sie, dass Ihre Peppol-Teilnehmer-ID das Schema 0245 verwendet', 'Stellen Sie sicher, dass Ihre 10-stellige DIČ korrekt unter dem slowakischen Kennungsschema registriert ist — dies macht Sie im Netzwerk routbar.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Confirmez que votre identifiant participant Peppol utilise le schéma 0245', 'Assurez-vous que votre DIČ à 10 chiffres est correctement enregistré sous le schéma d''identifiant slovaque — c''est ce qui vous rend routable sur le réseau.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Forme a su personal en el flujo de corrección', 'Dado que la modificación directa de una factura transmitida no es posible, asegúrese de que su equipo entiende el proceso de nota de crédito más reemisión antes de necesitarlo bajo presión.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Schulen Sie Ihr Personal im Korrekturworkflow', 'Da eine direkte Änderung einer übermittelten Rechnung nicht möglich ist, stellen Sie sicher, dass Ihr Team den Prozess aus Gutschrift plus Neuausstellung versteht, bevor er unter Druck benötigt wird.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Formez votre personnel au processus de correction', 'La modification directe d''une facture transmise n''étant pas possible, assurez-vous que votre équipe comprend le processus de note de crédit suivie d''une réémission avant d''en avoir besoin sous pression.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Integre en su proceso el plazo de emisión de 15 días (pronto 10)', 'Automatice el envío cerca del devengo en lugar de agrupar por lotes — el plazo corre desde el hecho imponible, no desde el momento en que alguien se dispone a generar el archivo.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 5;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Bauen Sie die 15-Tage- (bald 10-Tage-) Ausstellungsfrist in Ihren Prozess ein', 'Automatisieren Sie die Übermittlung nahe am Steuertatbestand, statt zu bündeln — die Frist läuft ab dem steuerauslösenden Ereignis, nicht erst ab dem Zeitpunkt, an dem jemand die Datei erzeugt.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 5;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Intégrez le délai d''émission de 15 jours (bientôt 10) à votre processus', 'Automatisez la soumission au plus près du fait générateur plutôt que par lots — le délai court à partir de l''événement imposable, pas à partir du moment où quelqu''un génère le fichier.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Slovakia' AND ds.sort_order = 5;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'es', 'Administración Financiera de la República Eslovaca' FROM deep_dive_portals dp JOIN countries c ON c.id = dp.country_id WHERE c.name_en = 'Slovakia' AND dp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'de', 'Finanzverwaltung der Slowakischen Republik' FROM deep_dive_portals dp JOIN countries c ON c.id = dp.country_id WHERE c.name_en = 'Slovakia' AND dp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'fr', 'Administration financière de la République slovaque' FROM deep_dive_portals dp JOIN countries c ON c.id = dp.country_id WHERE c.name_en = 'Slovakia' AND dp.sort_order = 0;
