-- Sweden milestone backfill (Stage 4). English only for now.
-- 10 milestones total: se-b2g (tracker, anchor:true) exactly replaces
-- deep-dive timeline card #3 (1 Apr 2019, full EN 16931 mandate) --
-- same date/event, tracker phrasing wins. se-b2b-expected (tracker,
-- 2030-07-01) does NOT map onto any deep-dive timeline card -- the only
-- static-page mention of the 2030 ViDA deadline is inside a narrative
-- related-card, not a timeline entry -- so it's kept as its own
-- non-overlapping row, same as Denmark's dk-established/dk-small.
-- 8 remaining deep-dive-only entries + se-b2g + se-b2b-expected = 10.

INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-b2g-2008', id, '2008-01-01', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-b2g-2008', 'en', 'First partial B2G mandate — central government agencies', 'All invoices sent to central public administrations must be electronic, alongside the creation of DIGG''s predecessor functions to steer public-sector digitalisation.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-act-2018', id, '2018-01-01', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-act-2018', 'en', 'Act on Electronic Invoicing in Public Procurement (Act 2018:1277)', 'Transposes EU Directive 2014/55/EU into Swedish law, setting the legal foundation for the full public-sector mandate that follows.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-b2g', id, '2019-04-01', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-b2g', 'en', 'B2G e-invoicing mandatory for all public entities (in force since 2019)', 'All contracting authorities and public entities in Sweden must be able to receive e-invoices compliant with EN 16931, with Peppol BIS Billing 3.0 the recommended (and increasingly required) format as legacy formats like Svefaktura are phased out.', '["Suppliers to Swedish public entities: use Peppol BIS Billing 3.0 where possible — legacy SFTI/EDIFACT formats are being retired", "No domestic B2B mandate exists yet — see the entry below on expected EU alignment"]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-b2g-extended-2019', id, '2019-12-01', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-b2g-extended-2019', 'en', 'Extended to all regional and municipal administrations', 'Full public-sector coverage achieved — every entity wishing to trade with public authorities must be connected to the Peppol network.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-b2b-assessment-2023', id, '2023-02-01', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-b2b-assessment-2023', 'en', 'DIGG, Skatteverket and Bolagsverket jointly request a B2B/G2B assessment', 'The three agencies formally ask the government to evaluate introducing a domestic B2B and G2B e-invoicing mandate — the first concrete institutional push beyond the existing voluntary approach.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-tullverket-2025', id, '2025-03-01', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-tullverket-2025', 'en', 'Tullverket (Swedish Customs) adopts Peppol BIS Billing 3', 'Sweden''s customs authority begins using Peppol BIS for invoicing customs duties, taxes, and fees — a sign of the format''s continued spread even without a general legal mandate.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-sfti-phaseout-2025', id, '2025-07-01', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-sfti-phaseout-2025', 'en', 'SFTI phases out legacy formats as "recommended" standards', 'Svefaktura and SFTI ESAP 6 Fulltextfaktura are no longer recommended for new public procurement projects — Peppol BIS becomes the preferred format, though legacy formats remain technically accepted for now.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-vida-inquiry-2026', id, '2026-02-05', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-vida-inquiry-2026', 'en', 'National ViDA implementation inquiry launched', 'The Ministry of Finance formally launches an inquiry into how ViDA should be implemented in Swedish law. A commissioner is appointed to examine necessary legislative changes, assess whether domestic B2B e-invoicing should be mandated, and consider how Skatteverket might use e-invoicing data for VAT administration and fraud prevention.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-inquiry-findings-2027', id, '2027-11-30', 1, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-inquiry-findings-2027', 'en', 'Inquiry findings due', 'This is the concrete date to watch — it will determine whether Sweden follows its Nordic neighbours into a legislated domestic B2B mandate, or continues with the current voluntary, high-adoption approach.', '[]');
INSERT INTO milestones (id, country_id, date, anchor, source_url) SELECT 'se-b2b-expected', id, '2030-07-01', 0, 'https://www.digg.se' FROM countries WHERE name_en = 'Sweden';
INSERT INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('se-b2b-expected', 'en', 'Cross-border B2B e-invoicing expected under EU ViDA', 'Sweden has not yet legislated a domestic B2B e-invoicing mandate; Skatteverket, DIGG and Bolagsverket have asked the government to evaluate one, but the only firm deadline currently on the table is the EU-wide ViDA cross-border requirement.', '["Monitor for a domestic mandate announcement — a formal government proposal is still pending", "Cross-border traders should still plan for EN 16931/Peppol readiness ahead of the EU-wide 2030 deadline"]');
