-- ES/DE/FR translations for all 7 China milestones.
-- cn-nationwide and cn-paper-phaseout reuse the tracker's own
-- phrasing per tracker-phrasing-wins.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-general-vat-2015', 'es', 'La e-fapiao general de IVA se implanta a nivel nacional', 'Utilizada principalmente para transacciones B2C no deducibles — el primer formato de factura digital a nivel nacional, construido sobre el Sistema de Impuestos de Oro ya existente.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-general-vat-2015', 'de', 'Allgemeine Umsatzsteuer-E-Fapiao landesweit eingeführt', 'Hauptsächlich für B2C-Transaktionen ohne Vorsteuerabzug verwendet — das erste landesweite digitale Rechnungsformat, aufbauend auf dem bestehenden Golden-Tax-System.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-general-vat-2015', 'fr', 'La e-fapiao générale de TVA est déployée à l''échelle nationale', 'Principalement utilisée pour les transactions B2C non déductibles — le premier format de facture numérique à l''échelle nationale, construit sur le Golden Tax System déjà existant.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-special-vat-pilot-2020', 'es', 'Comienzan los proyectos piloto de e-fapiao especial de IVA', 'Estas facturas B2B deducibles de IVA comienzan a probarse en regiones seleccionadas — a menudo se exige su uso a los nuevos contribuyentes, mientras que las empresas existentes pueden sumarse de forma voluntaria.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-special-vat-pilot-2020', 'de', 'Pilotprojekte für spezielle Umsatzsteuer-E-Fapiao beginnen', 'Diese B2B-Rechnungen mit Vorsteuerabzug werden in ausgewählten Regionen pilotiert — neue Steuerpflichtige müssen sie oft verwenden, während bestehende Unternehmen freiwillig teilnehmen können.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-special-vat-pilot-2020', 'fr', 'Les projets pilotes de e-fapiao spéciale de TVA débutent', 'Ces factures B2B déductibles de TVA commencent à être testées dans certaines régions — les nouveaux contribuables sont souvent tenus de les utiliser, tandis que les entreprises existantes peuvent y adhérer volontairement.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-pilots-allprovinces-2023', 'es', 'Los pilotos se extienden a todas las provincias', 'La sucursal local de la STA en la Región Autónoma del Tíbet lanza su piloto, completando la cobertura provincial a nivel nacional antes del despliegue nacional completo.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-pilots-allprovinces-2023', 'de', 'Pilotprojekte werden auf alle Provinzen ausgeweitet', 'Die lokale STA-Niederlassung der Autonomen Region Tibet startet ihr Pilotprojekt und vervollständigt damit die landesweite Provinzabdeckung vor dem vollständigen landesweiten Rollout.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-pilots-allprovinces-2023', 'fr', 'Les projets pilotes s''étendent à toutes les provinces', 'L''antenne locale de la STA dans la région autonome du Tibet lance son projet pilote, complétant la couverture provinciale nationale avant le déploiement national complet.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-railway-2024', 'es', 'Entran en vigor las normas de e-fapiao para el transporte ferroviario de pasajeros', 'Anunciadas conjuntamente con el Ministerio de Finanzas y China State Railway Group, cubriendo normas para números/códigos de factura y procedimientos de verificación de pasajeros.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-railway-2024', 'de', 'Regeln für E-Fapiao im Schienenpersonenverkehr treten in Kraft', 'Gemeinsam mit dem Finanzministerium und der China State Railway Group angekündigt, umfassen sie Regeln für Rechnungsnummern/-codes und Fahrgastverifizierungsverfahren.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-railway-2024', 'fr', 'Les règles relatives à la e-fapiao pour le transport ferroviaire de voyageurs entrent en vigueur', 'Annoncées conjointement avec le ministère des Finances et le China State Railway Group, elles couvrent les règles relatives aux numéros/codes de facture et aux procédures de vérification des passagers.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-aviation-2024', 'es', 'Se promueve la e-fapiao para el transporte aéreo civil de pasajeros', 'El despliegue específico por sector continúa, ampliando el formato totalmente digitalizado a otra categoría importante de transacciones.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-aviation-2024', 'de', 'E-Fapiao für den zivilen Luftverkehr von Passagieren wird gefördert', 'Der sektorspezifische Rollout wird fortgesetzt und erweitert das vollständig digitalisierte Format auf eine weitere wichtige Transaktionskategorie.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-aviation-2024', 'fr', 'La e-fapiao pour le transport aérien civil de passagers est promue', 'Le déploiement sectoriel se poursuit, étendant le format entièrement numérisé à une autre catégorie majeure de transactions.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-nationwide', 'es', 'La factura electrónica totalmente digitalizada (e-fapiao) se implanta a nivel nacional (en vigor desde diciembre de 2024)', 'La Administración Estatal de Impuestos (STA) completó el despliegue nacional de facturas electrónicas totalmente digitalizadas (e-fapiao), otorgándoles la misma validez legal que las facturas en papel y sustituyendo a las fases piloto anteriores del Sistema de Impuestos de Oro.', '["Configure una cuenta fiscal digital con la STA para emitir y recibir e-fapiao", "Confirme que los sistemas ERP/facturación pueden generar e-fapiao con los campos obligatorios en chino simplificado y renderizado OFD/XML", "Conserve el código de factura de la STA, la firma digital, el código QR dinámico y la marca de tiempo de compensación de cada factura"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-nationwide', 'de', 'Vollständig digitalisierte E-Rechnung (E-Fapiao) landesweit eingeführt (seit Dezember 2024 in Kraft)', 'Die staatliche Steuerverwaltung (STA) hat den landesweiten Rollout vollständig digitalisierter elektronischer Rechnungen (E-Fapiao) abgeschlossen und ihnen dieselbe Rechtsgültigkeit wie Papierrechnungen verliehen, wodurch die früheren Pilotphasen des Golden-Tax-Systems abgelöst werden.', '["Richten Sie ein digitales Steuerkonto bei der STA ein, um E-Fapiao auszustellen und zu empfangen", "Bestätigen Sie, dass ERP-/Rechnungssysteme E-Fapiao mit den vorgeschriebenen vereinfacht-chinesischen Feldern und OFD-/XML-Darstellung erzeugen können", "Bewahren Sie den STA-Rechnungscode, die digitale Signatur, den dynamischen QR-Code und den Clearing-Zeitstempel für jede Rechnung auf"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-nationwide', 'fr', 'La facture électronique entièrement numérisée (e-fapiao) est déployée à l''échelle nationale (en vigueur depuis décembre 2024)', 'L''administration fiscale d''État (STA) a achevé le déploiement national des factures électroniques entièrement numérisées (e-fapiao), leur conférant la même validité juridique que les factures papier et remplaçant les phases pilotes antérieures du Golden Tax System.', '["Mettez en place un compte fiscal numérique auprès de la STA pour émettre et recevoir des e-fapiao", "Vérifiez que les systèmes ERP/de facturation peuvent produire des e-fapiao avec les champs obligatoires en chinois simplifié et le rendu OFD/XML", "Conservez le code de facture de la STA, la signature numérique, le code QR dynamique et l''horodatage de contrôle pour chaque facture"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-paper-phaseout', 'es', 'Se acelera la eliminación regional de las facturas en papel', 'Las autoridades fiscales locales de varias regiones (por ejemplo, Dalian, con efecto a partir del 1 de julio de 2026) han comenzado a eliminar tipos específicos de facturas en papel supervisadas fiscalmente en favor de la e-fapiao, y se espera que más regiones sigan este camino a lo largo de 2026.', '["Consulte los anuncios de su sucursal local de la STA sobre las fechas de eliminación de facturas en papel específicas para su región y sector", "Las facturas emitidas antes de la fecha límite de una región siguen siendo válidas, pero la emisión de nuevas facturas en papel puede bloquearse a partir de esa fecha"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-paper-phaseout', 'de', 'Regionale Einstellung von Papierrechnungen beschleunigt sich', 'Lokale Steuerbehörden in mehreren Regionen (z. B. Dalian, ab 1. Juli 2026) haben begonnen, bestimmte steuerlich überwachte Papierrechnungsarten zugunsten der E-Fapiao einzustellen, wobei im Laufe des Jahres 2026 weitere Regionen folgen dürften.', '["Prüfen Sie die Ankündigungen Ihrer lokalen STA-Niederlassung zu den für Ihre Region und Ihren Sektor spezifischen Terminen für die Einstellung von Papierrechnungen", "Vor dem Stichtag einer Region ausgestellte Rechnungen bleiben gültig, aber die Ausstellung neuer Papierrechnungen kann ab diesem Datum blockiert werden"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('cn-paper-phaseout', 'fr', 'L''abandon régional des factures papier s''accélère', 'Les administrations fiscales locales de plusieurs régions (par exemple Dalian, à compter du 1er juillet 2026) ont commencé à abandonner certains types de factures papier sous contrôle fiscal au profit de la e-fapiao, et d''autres régions devraient suivre tout au long de 2026.', '["Consultez les annonces de votre antenne locale de la STA pour connaître les dates d''abandon des factures papier propres à votre région et à votre secteur", "Les factures émises avant la date limite d''une région restent valables, mais l''émission de nouvelles factures papier peut être bloquée à partir de cette date"]');
