-- India deep-dive content: page, stats, file_format cards,
-- scope_transmission cards + lifecycle card ("The clearance flow"),
-- steps, penalty rows, penalties_related cards, portal.

INSERT OR IGNORE INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Centralised clearance (IRP)', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. Turnover thresholds, IRP technical requirements, and penalty provisions continue to evolve — confirm current requirements directly on the GST e-Invoice portal or with a GST practitioner before building an integration.', 'India rolled out e-invoicing by progressively lowering the turnover threshold — a gradual widening of scope rather than a single flag-day mandate.', 'India''s e-invoice is a JSON document, not an XML one — a distinction worth flagging since much of the rest of the world defaults to XML.', 'Four institutions share responsibility for how this system runs — worth knowing who does what when something goes wrong.', 'Registration is straightforward if you''re already a GST-registered business — the real work is in building or connecting your IRP submission pipeline.', 'The bigger practical risk isn''t the fine itself — it''s that an invoice without a valid IRN is not a legally valid GST invoice at all.' FROM countries WHERE name_en = 'India';

INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'JSON', 'Schema format (INV-01)' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '₹5 crore', 'AATO threshold' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '30 days', 'IRP reporting window (≥₹10cr)' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '4', 'Governing institutions' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '2020', 'Mandatory since October' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Schema', '[["Format", "Form GST INV-01 (schema v1.1)"], ["Syntax", "JSON"], ["Master codes", "HSN, country, currency, state codes"]]', 'Registered persons continue creating GST invoices in their own accounting/billing/ERP systems as before — the change is that these invoices must now be reported to an IRP before they carry legal force.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'What "e-invoicing" actually means here', '[["Common misconception", "Government generates the invoice"], ["Reality", "Business generates it; IRP validates and registers it"]]', 'GSTN is explicit on this point in its own FAQ: e-invoicing does not mean invoice generation by a government portal — it means reporting to the IRP and obtaining an IRN.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'The IRN itself', '[["What it is", "A hash computed by the IRP"], ["Validity rule", "A GST invoice is valid only with a valid IRN"]]', 'The hash the IRP computes over your invoice data becomes the Invoice Reference Number — this is what makes the IRN tamper-evident by construction, not just by policy.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'QR code contents', '[["Included data", "Seller & buyer GSTINs, invoice number/date, line item count, major-commodity HSN, hash"], ["Printing requirement", "Mandatory on the invoice (Rule 46, CGST Rules)"], ["IRN printing", "Optional — it''s already embedded in the QR code"]]', 'Printing the QR code on separate paper isn''t allowed — it must appear on the invoice itself as one of the mandatory particulars.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'file_format' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Governing institutions', '[["GST Council", "Sets policy direction, recommends threshold changes"], ["CBIC", "Translates recommendations into binding notifications"], ["GSTN", "Builds and maintains the IT infrastructure"], ["IRPs", "Multiple authorised portals process and register invoices"]]', 'The Central Board of Indirect Taxes and Customs (CBIC) is the body that actually issues the binding legal notifications — GSTN builds the technology underneath them.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Submission channels', '[["Direct", "Upload directly to an IRP"], ["Via intermediary", "Through a GST Suvidha Provider (GSP)"], ["No software?", "Free GSTN-empanelled tools, or the offline bulk generation tool"]]', 'Small and medium taxpayers without their own ERP or billing software genuinely aren''t left out — free tooling exists specifically for this case.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'The 30-day rule''s teeth', '[["Applies to", "AATO ≥ ₹10 crore"], ["Effect", "Invoices older than 30 days are rejected outright by the IRP"]]', 'This isn''t a late-fee situation — past this window, the invoice simply cannot be registered at all, and past invoices cannot be retroactively registered if compliance was missed earlier.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 0, 'pills' FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) SELECT dlc.id, 'en', 'The clearance flow', 'Every invoice passes through the same sequence:', 'Upon successful registration, the data auto-populates the supplier''s GSTR-1 return — a genuine downstream compliance simplification, not just a formality.' FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India';
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 0, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', '1. Generate JSON' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India' AND dls.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 1, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', '2. Upload to IRP' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India' AND dls.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 2, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', '3. IRP validates & signs' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India' AND dls.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 3, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', '4. IRN + QR returned' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India' AND dls.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 4, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', '5. Issue to buyer' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'India' AND dls.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Confirm your aggregate turnover across all GSTINs', 'Check your combined turnover under a single PAN — it only needs to exceed ₹5 crore once in any financial year since 2017–18 to bring you permanently into scope.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Enable e-invoicing on the GST portal if not auto-enabled', 'If your turnover has crossed the threshold but you haven''t been automatically enabled, use Registration → e-Invoice Enablement to switch it on voluntarily.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Choose your submission channel', 'Direct IRP upload, a GST Suvidha Provider, or — if you lack ERP/billing software — a free GSTN-empanelled tool or the offline bulk generation utility.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Enable multi-factor authentication', 'Mandatory on the GST portal for AATO above ₹100 crore since mid-2023, and for AATO ≥ ₹10 crore since April 2025 — confirm your access setup meets the requirement for your bracket.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Build the 30-day reporting window into your workflow', 'If your AATO is ≥ ₹10 crore, automate submission well within 30 days of issuance — there''s no path to registering an invoice after that window closes.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'If you''ve missed compliance, act immediately rather than retroactively', 'Past invoices cannot be registered after the fact. Begin compliant generation for all new invoices now, and consult a GST practitioner about voluntary disclosure for the non-compliant period.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'India' AND ds.sort_order = 5;

INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'en', 'Failure to generate a required e-invoice', 'Penalty under CGST Act non-compliance provisions, tied to tax involved', NULL FROM deep_dive_penalty_rows dpr JOIN countries co ON co.id = dpr.country_id WHERE co.name_en = 'India' AND dpr.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT dpr.id, 'en', 'Incorrect or invalid e-invoice', 'Separate penalty for incorrect invoicing under GST law', NULL FROM deep_dive_penalty_rows dpr JOIN countries co ON co.id = dpr.country_id WHERE co.name_en = 'India' AND dpr.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '⚠️ Invalidity is the sharper risk', NULL, NULL, 'An invoice issued without an IRN is not legally a GST invoice — beyond any monetary fine, this can block the buyer''s input tax credit claim entirely, a far more disruptive commercial consequence than the penalty figure itself.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🔒 No retroactive fix', NULL, NULL, 'If compliance was missed in a past period, those invoices remain permanently invalid — this makes catching a compliance gap early far more valuable than in regimes that allow retroactive correction.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '📉 Watch for further threshold reductions', NULL, NULL, 'Given the trajectory from ₹500 crore down to ₹5 crore over five years, further reductions (some discussion has floated ₹2 crore) remain plausible — don''t assume the current threshold is permanent.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'India' AND dc.section = 'penalties_related' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://einvoice1.gst.gov.in', 0 FROM countries WHERE name_en = 'India';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'e-Invoice / IRP (NIC)' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'India' AND dp.sort_order = 0;
