-- New Zealand milestones (Stage 4 deep-dive/tracker migration)
-- 8 total: 5 deep-dive-only + 3 tracker-matched (nz-central, nz-2000, nz-largesupplier),
-- all exact date/event matches with the tracker's own DATA entries -- tracker phrasing wins.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-anz-arrangement-2018', id, '2018-01-01', 0, NULL FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-anz-arrangement-2018', 'en', 'Australia–New Zealand Government Electronic Invoicing Arrangement', 'Both governments commit to a shared approach — the basis for the PINT A-NZ specification both countries now use.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-framework-2019', id, '2019-01-01', 0, NULL FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-framework-2019', 'en', 'E-invoicing framework launches, alongside Australia', 'New Zealand''s Peppol-based e-invoicing infrastructure goes live, with MBIE established as the national Peppol Authority.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-central', id, '2022-03-31', 1, 'https://www.einvoicing.govt.nz' FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-central', 'en', 'Central government agencies mandatory to receive e-invoices (in force since Mar 2022)', 'All central public agencies have been required to receive Peppol e-invoices since March 2022, administered by MBIE as New Zealand''s Peppol Authority.', '["Suppliers to central agencies: set up Peppol invoicing capability via an accredited Access Point"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-pint-anz-2025', id, '2025-05-15', 0, NULL FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-pint-anz-2025', 'en', 'PINT A-NZ becomes the only accepted specification', 'The legacy A-NZ Peppol BIS Billing 3.0 extension is fully removed from the network used by MBIE-accredited Access Points.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-5th-edition-announced-2025', id, '2025-10-09', 0, NULL FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-5th-edition-announced-2025', 'en', 'Fifth Edition Government Procurement Rules announced', 'MBIE publishes updated rules expanding e-invoicing obligations for both agencies and large suppliers, alongside new prompt-payment standards.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-5th-edition-effect-2025', id, '2025-12-01', 0, NULL FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-5th-edition-effect-2025', 'en', 'Fifth Edition rules take effect', 'The new B2G e-invoicing expectations are formally baked into public sector procurement practice.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-2000', id, '2026-01-01', 0, 'https://www.einvoicing.govt.nz' FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-2000', 'en', 'Agencies handling 2,000+ invoices/year must send & receive e-invoices', 'Government agencies processing more than 2,000 domestic trade invoices annually must be fully capable of both sending and receiving structured e-invoices, and pay 95% of them within 5 business days.', '["Confirm PINT A-NZ format compliance — mandatory for government e-invoicing since May 2025", "Check whether your government customer falls within this volume threshold"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'nz-largesupplier', id, '2027-01-01', 0, 'https://www.einvoicing.govt.nz' FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('nz-largesupplier', 'en', 'Large suppliers (>NZD 33m revenue) must submit e-invoices to government', 'Suppliers with revenue exceeding NZD 33 million in each of the previous two accounting years must submit e-invoices via Peppol for domestic trade invoices to government buyers.', '["Assess whether your revenue crosses the NZD 33 million threshold", "Integrate with a Peppol Access Point well ahead of the deadline"]');
