-- New Zealand deep-dive content: page, stats, file_format cards,
-- scope_transmission cards, steps, penalties_related cards, portal.
-- No penalty rows/table -- NZ's enforcement is administrative (no statutory fines).

INSERT OR IGNORE INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Decentralised 4-corner Peppol', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. Government Procurement Rules, large-supplier thresholds, and any future extension to broader B2B remain subject to change — confirm current requirements directly with MBIE before building an integration.', 'New Zealand''s approach is procurement-rule-driven rather than tax-law-driven — the obligations live in Government Procurement Rules, not VAT/GST legislation.', 'Identical specification to Australia — a genuine trans-Tasman standard, not a lookalike national variant.', 'A pure four-corner Peppol model — no central government platform, no clearance step, identical in structure to Australia''s.', 'If you''re a large supplier to government, the 2027 deadline is closer than it looks once you factor in testing time with individual agencies.', 'New Zealand''s B2B economy remains voluntary — but the government supply chain increasingly won''t be.' FROM countries WHERE name_en = 'New Zealand';

INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'PINT A-NZ', 'Only supported spec since May 2025' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'NZD 33m', 'Large-supplier revenue threshold' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '2,000', 'Invoice/year agency capability trigger' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '7 yrs', 'Record retention' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'No fines', 'Administrative consequences only' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Specification', '[["Format", "PINT A-NZ (New Zealand''s tailored version of EN 16931)"], ["Syntax", "UBL-based XML"], ["Superseded", "Peppol BIS Billing 3.0 (deprecated May 2025)"]]', 'Because Australia and New Zealand share this exact specification, a business trading across both markets can reuse the same mappings and validations rather than building twice.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Identifiers', '[["Routing identifier", "New Zealand Business Number (NZBN)"], ["Role", "Peppol Participant Identifier"]]', 'Every New Zealand business already has an NZBN — this makes onboarding materially simpler than jurisdictions requiring a separate registration number just for e-invoicing.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Scope of the 2027 mandate', '[["Applies to", "Domestic trade invoices in NZD only"], ["Excludes", "International suppliers, cross-border invoicing"]]', 'If your New Zealand government contract involves any cross-border element, check carefully whether the specific invoice line actually falls inside or outside this mandate''s scope.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'No real-time reporting', '[["Tax reporting", "GST continues via periodic returns"], ["Retention", "7 years"]]', 'Unlike Ireland or France, there''s no data-reporting layer bolted onto this mandate — it''s purely about the exchange format, not tax administration modernisation.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'file_format' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Governance', '[["National Peppol Authority", "Ministry of Business, Innovation and Employment (MBIE)"], ["Role", "Oversees the framework, accredits Access Points"]]', 'MBIE doesn''t operate a clearance or exchange platform itself — invoices move directly between accredited Access Points on the Peppol network.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Determining "large supplier" status', '[["Threshold", "NZD 33 million total revenue"], ["Includes", "Subsidiary revenue combined with parent"], ["Measurement period", "Each of the two preceding accounting periods"]]', 'Check this on a consolidated group basis, not just your standalone entity''s revenue — a smaller subsidiary of a large group can still be caught by the threshold.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Agency-side obligations', '[["2,000+ invoice threshold", "Must send AND receive structured e-invoices"], ["Payment standard", "95% of e-invoices paid within 5 business days"]]', 'Fast payment is the tangible incentive for suppliers here — agencies covered by these rules are contractually motivated to prefer e-invoiced suppliers.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 3 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Enforcement style', '[["Statutory financial penalties", "None"], ["Mechanism", "Administrative, under the Government Procurement Rules"], ["Transparency", "Agencies report quarterly to MBIE; results published publicly"]]', 'There''s no fine for non-compliance — but public quarterly reporting on prompt-payment performance creates its own reputational pressure on agencies to comply.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'scope_transmission' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Evaluate your size status', 'Confirm whether your combined group revenue (including subsidiaries) exceeds NZD 33 million in each of the last two accounting periods — this determines whether the January 2027 mandate applies to you.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Choose a Peppol-compliant solution', 'Confirm your invoicing software can send and receive Peppol e-invoices natively, or explore integration options with a certified Access Point if it can''t.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Validate against PINT A-NZ specifically', 'Ensure your invoicing templates meet the current standard''s mandatory fields and data formats — the legacy Peppol BIS 3.0 profile is no longer accepted anywhere on the network.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Test with government agencies during 2026', 'Participate in testing well ahead of the January 2027 deadline to catch onboarding issues before they become deadline pressure.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Confirm your NZBN is correctly registered', 'This is your Peppol routing identifier — make sure it''s accurately linked to your Access Point registration.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'New Zealand' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🇦🇺 Trans-Tasman consistency', NULL, NULL, 'Organisations operating in both New Zealand and Australia can align on PINT A-NZ to reuse mappings and validations — a genuinely practical benefit of the two countries'' shared specification choice.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🏛️ Procurement rules, not tax law', NULL, NULL, 'Because this entire framework sits inside Government Procurement Rules rather than GST legislation, enforcement is administrative and contractual — there''s no equivalent to a tax authority penalty regime here.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '📈 Voluntary B2B remains encouraged', NULL, NULL, 'Outside the government supply chain, e-invoicing adoption is voluntary but actively encouraged — many businesses adopt it anyway for the reduced errors and faster processing it brings.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 3 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '💰 A narrower domestic-only scope', NULL, NULL, 'The large-supplier mandate applies only to NZD-denominated domestic trade invoices — a deliberately narrow scope compared to more ambitious mandates elsewhere in this tracker.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'New Zealand' AND dc.section = 'penalties_related' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.einvoicing.govt.nz', 0 FROM countries WHERE name_en = 'New Zealand';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'einvoicing.govt.nz — MBIE' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'New Zealand' AND dp.sort_order = 0;
