-- Singapore deep-dive content: page, stats, file_format cards,
-- scope_transmission cards + lifecycle card ("The exchange flow"),
-- steps, penalties_related cards, portal. No penalty rows/table.

INSERT OR IGNORE INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Peppol, transitioning 4-corner → 5-corner', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. PINT-SG technical detail, phased rollout dates, and IRAS reporting requirements continue to evolve — confirm current requirements directly with IRAS or IMDA before building an integration.', 'Singapore is running one of the longest, most granular phase-in schedules in this tracker — six years, sliced by both incorporation status and revenue band.', 'SG Peppol BIS Billing 3.0 is a genuine national extension of the European standard — not a from-scratch local format.', 'InvoiceNow is deliberately transitioning from a pure exchange network into a tax-reporting one — the "5-corner" upgrade adds IRAS as a genuine participant, not just an observer.', 'Registration hinges on getting a Peppol ID before you ever touch IRAS — treat it as the true first step, not a formality.', 'Singapore''s approach is notably gradual and consultative — a genuinely different posture from the faster-moving mandates elsewhere in this tracker.' FROM countries WHERE name_en = 'Singapore';

INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'SG Peppol BIS 3.0', 'Format standard' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'UEN', 'Peppol ID base identifier' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '2018', 'First Peppol Authority outside Europe' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '5-corner', 'Model being adopted for GST reporting' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '2031', 'Full rollout complete' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Format', '[["Current standard", "SG Peppol BIS Billing 3.0"], ["Base", "European Peppol BIS 3.0, extended for Singapore-specific requirements"], ["Digital signature", "Not required from the taxpayer"]]', 'Unlike clearance-model countries, InvoiceNow doesn''t require the taxpayer to digitally sign invoices — security, integrity, and authenticity are safeguarded by the Peppol network and accredited Access Point providers instead.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Mandatory Data Elements', '[["Party identifiers", "Supplier/customer UEN and GST registration numbers (GSTN)"], ["Tax codes", "Mapped to IRAS-approved GST category codes (Annex E, e-Tax Guide)"], ["Aggregated entries", "Special \"POS\" or \"PCP\" indicators for point-of-sale/petty-cash purchases"]]', 'Mapping your internal tax codes correctly to IRAS''s standardised GST category list is one of the highest-friction technical steps — get this wrong and your submissions will be flagged.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Identifiers', '[["Peppol ID base", "Unique Entity Number (UEN)"], ["Also underlies", "PayNow Corporate (Singapore''s e-payment scheme)"], ["Multi-entity businesses", "Each GST-registered entity needs its own Peppol ID"]]', 'For groups with multiple operating entities, design for a separate Peppol ID and Access Point configuration per entity from the start — retrofitting this after go-live is genuinely disruptive.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Evolving format: PINT SG', '[["Fields not in older templates", "Supply type codes, line-level GST amounts, UEN-linked Peppol IDs"]]', 'If your invoice templates were built before InvoiceNow''s GST requirement, expect meaningful gaps against the newer PINT-SG-aligned field requirements — audit rather than assume compatibility.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'file_format' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Governance', '[["IMDA", "Singapore''s Peppol Authority; defines Peppol Authority Specific Requirements (PASR)"], ["IRAS", "Receives the reported invoice data for GST administration"]]', 'IMDA accredits the Access Point/SMP service providers; IRAS is the tax authority consuming the data those providers transmit — two distinct roles worth keeping separate in your mental model.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Submission timing', '[["Deadline", "Earlier of the GST return filing date or the statutory deadline for that return"]]', 'This ties your InvoiceNow transmission cadence directly to your existing GST filing calendar rather than requiring a separate real-time deadline to track.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Roles: IRSP vs. AP', '[["IRSP", "InvoiceNow-Ready Solution Provider — provides the accounting software"], ["AP", "Access Point — enables network connectivity"]]', 'These are often the same commercial provider in practice, but they''re conceptually distinct roles — worth clarifying with your vendor which function they''re actually performing for you.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 0, 'pills' FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) SELECT dlc.id, 'en', 'The exchange flow', NULL, 'The invoice reaches the customer, and a copy is transmitted to IRAS simultaneously or shortly after — through the same InvoiceNow network, not a separate filing channel.' FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 0, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', 'Supplier''s ERP' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore' AND dls.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 1, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', 'Supplier''s Access Point' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore' AND dls.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 2, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', 'Buyer''s Access Point (via UEN)' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore' AND dls.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 3, 0 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', 'Buyer''s ERP' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore' AND dls.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) SELECT dlc.id, 4, 1 FROM deep_dive_lifecycle_cards dlc JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'en', 'Copy to IRAS' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries co ON co.id = dlc.country_id WHERE co.name_en = 'Singapore' AND dls.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Obtain your Peppol ID', 'Work with your chosen IRSP or AP provider to register in the SG Peppol Directory using your UEN — this is a prerequisite for any InvoiceNow transmission, separate from your ACRA registration or GST registration number itself.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Engage an IMDA-accredited Access Point (if using custom/in-house software)', 'If you''re not using an off-the-shelf InvoiceNow-Ready Solution, you''ll need an accredited AP provider specifically to establish secure network connectivity.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Map your internal tax codes to IRAS''s GST category codes', 'Use Annex E of the IRAS e-Tax Guide as your reference — every transaction needs accurate categorisation before submission.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Confirm your InvoiceNow-Ready Solution is IRAS-integrated', 'Make sure it connects via API technology through IMDA-accredited Access Points, enabling real-time or regular automated transmission of invoice data to IRAS.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Plan for multi-entity Peppol ID architecture early', 'If you operate multiple GST-registered entities, design your Peppol ID and Access Point configuration per entity from the outset rather than discovering the requirement during testing.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Check where you land on the phased rollout', 'If you''re not yet mandatorily in scope, use the voluntary phase to build institutional familiarity ahead of your specific 2028–2031 milestone.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Singapore' AND ds.sort_order = 5;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🐢 A deliberately long runway', NULL, NULL, 'Six years between the first mandatory cohort (Nov 2025) and full rollout (Apr 2031) is among the longest phase-in periods in this tracker — Singapore appears to be prioritising smooth adoption over speed.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🔄 4-corner to 5-corner is a genuine architecture shift', NULL, NULL, 'The addition of IRAS as a "5th corner" wasn''t in InvoiceNow''s original 2019 design — it represents Singapore evolving a voluntary exchange network into a tax-reporting one over time, rather than building a clearance system from scratch.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '💰 Transitional support available', NULL, NULL, 'Government grants have historically supported InvoiceNow adoption costs — worth checking current IMDA/IRAS schemes if cost is a barrier to early adoption.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 3 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🌏 Regional Peppol leadership', NULL, NULL, 'As the first Peppol Authority outside Europe, Singapore''s InvoiceNow experience has directly informed how newer Asia-Pacific Peppol markets like Malaysia and Japan have approached their own rollouts.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Singapore' AND dc.section = 'penalties_related' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.iras.gov.sg/taxes/goods-services-tax-(gst)/gst-invoicenow-requirement', 0 FROM countries WHERE name_en = 'Singapore';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'IRAS — GST InvoiceNow Requirement' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'Singapore' AND dp.sort_order = 0;
