-- Brazil milestones (Stage 4 deep-dive/tracker migration)
-- 10 total: 7 deep-dive-only + 3 tracker-matched (br-fields, br-validate,
-- br-mandatory), all exact date/event matches with the tracker's own DATA entries
-- -- tracker phrasing wins.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-nfe-established', id, '2005-01-01', 0, NULL FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-nfe-established', 'en', 'NF-e system established, reaching near-universal adoption', 'Brazil pioneered clearance-model e-invoicing in Latin America — goods cannot legally ship without a SEFAZ-authorised NF-e.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-nfse-mei-2023', id, '2023-09-01', 0, NULL FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-nfse-mei-2023', 'en', 'NFS-e mandatory for MEIs (micro-entrepreneurs)', 'Originally due 3 April 2023, this brought Brazil''s smallest formal businesses into structured service-invoice reporting via the emerging national NFS-e framework.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-nt-2025-002-2024', id, '2024-12-06', 0, NULL FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-nt-2025-002-2024', 'en', 'Technical Note 2025.002 published', 'Defines the CST tax codes for the three new consumption taxes — CBS, IBS, and the Selective Tax (IS) — and begins the long process of updating NF-e/NFC-e XML layouts for the reform.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-lei-complementar-2025', id, '2025-01-16', 0, NULL FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-lei-complementar-2025', 'en', 'Lei Complementar 214/2025 enacted', 'Formally institutes IBS, CBS, and the Selective Tax, replacing PIS, COFINS, IPI, ICMS, and ISS under a Dual VAT model — the legal foundation for everything that follows.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-test-env-2025', id, '2025-07-01', 0, NULL FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-test-env-2025', 'en', 'Test environment opens for new tax codes', 'Businesses can trial the new CST codes and CBS/IBS/IS fields against SEFAZ''s homologation servers ahead of go-live.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-nt-v133-postpone-2025', id, '2025-12-01', 0, NULL FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-nt-v133-postpone-2025', 'en', 'NT 2025.002 v1.33 postpones the hard validation block', 'The rule that would reject invoices missing IBS/CBS fields is marked "future implementation" rather than enforced immediately — a technical relaxation, but explicitly not a legal exemption.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-fields', id, '2026-01-01', 1, 'https://www.nfe.fazenda.gov.br/portal/principal.aspx' FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-fields', 'en', 'CBS/IBS fields required on NF-e/NFC-e/NFS-e (test rates)', 'As Brazil''s dual-VAT tax reform begins, electronic tax documents must include the new CBS and IBS fields at test rates (0.9% / 0.1%) — no financial impact yet, but the legal obligation to include the data already applies.', '["Update invoicing layouts to Technical Note 2025.002-RTC (latest version)", "Test in SEFAZ''s homologation environment before go-live", "Simples Nacional / MEI taxpayers have an extended timeline to 2027"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-validate', id, '2026-04-01', 0, 'https://www.nfe.fazenda.gov.br/portal/principal.aspx' FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-validate', 'en', 'CBS/IBS field validation begins — rejection risk', 'Authorization systems start rigorously validating CBS/IBS fields; invoices with missing or inconsistent data risk automatic rejection.', '["Audit invoice output for complete, consistent CBS/IBS/IS data groups", "Resolve any rejections quickly — blocked invoices halt the movement of goods"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-mandatory', id, '2026-08-03', 0, 'https://www.nfe.fazenda.gov.br/portal/principal.aspx' FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-mandatory', 'en', 'Full legal reporting obligation for General Tax Regime', 'Under Technical Note 2025.002-RTC v1.40, General Tax Regime taxpayers must report IBS and CBS groups in NF-e and NFC-e with full legal effect.', '["Confirm your ERP/e-invoicing provider has completed the required schema updates", "Reconcile reported CBS/IBS data against your accounting records ahead of full enforcement"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'br-full-migration-2033', id, '2027-01-01', 0, NULL FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('br-full-migration-2033', 'en', 'CBS/IS collection begins; full migration completes by 2033', 'Actual tax collection under CBS and the Selective Tax starts in 2027, with the legacy taxes (PIS, COFINS, IPI, ICMS, ISS) phased out entirely by 2033 — this is a genuinely multi-year transition, not a single cutover date.', '[]');
