-- Brazil deep-dive page translations: page fields, stats, cards,
-- lifecycle card + statuses, steps, portal.

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'es', 'Compensación multicapa (estatal + municipal + federal)', 'Esta página de análisis refleja la orientación técnica disponible públicamente a julio de 2026 y se proporciona a título informativo general, no como asesoramiento legal o fiscal. La Nota Técnica 2025.002-RTC sigue revisándose durante la transición de la reforma fiscal, y los requisitos estatales/municipales varían — confirme los requisitos actuales directamente con la SEFAZ, la Receita Federal o un asesor fiscal brasileño antes de construir una integración.', 'El sistema NF-e de Brasil funciona desde mediados de la década de 2000 con una adopción casi universal — la historia actual es la reforma del impuesto al consumo que se está incorporando a la infraestructura existente.', 'La profundidad del XML de Brasil es genuinamente inusual — se trata de una estructura mucho más granular que la mayoría de los estándares europeos de facturación electrónica.', 'Brasil no opera un único sistema de facturación electrónica — opera varios, divididos por tipo de transacción y nivel de gobierno, cada uno con sus propias particularidades.', 'Dado que la reforma fiscal se superpone a un sistema existente y maduro, "estar preparado" aquí significa principalmente actualizar lo que ya opera, no construir desde cero.', 'En Brasil, el rechazo suele ser el riesgo práctico más agudo — una factura bloqueada detiene el movimiento de mercancías, lo que con frecuencia importa más que la multa en sí.' FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'de', 'Mehrschichtiges Clearing (bundesstaatlich + kommunal + föderal)', 'Diese Länderanalyse spiegelt öffentlich verfügbare technische Hinweise mit Stand Juli 2026 wider und dient der allgemeinen Information, nicht als Rechts- oder Steuerberatung. Die Technische Mitteilung 2025.002-RTC wird während des Steuerreform-Übergangs weiterhin überarbeitet, und die bundesstaatlichen/kommunalen Anforderungen variieren — bestätigen Sie aktuelle Anforderungen direkt bei der SEFAZ, der Receita Federal oder einem brasilianischen Steuerberater, bevor Sie eine Integration aufbauen.', 'Brasiliens NF-e-System läuft seit Mitte der 2000er-Jahre mit nahezu universeller Verbreitung — die aktuelle Geschichte ist die Verbrauchsteuerreform, die in die bestehende Infrastruktur eingebettet wird.', 'Brasiliens XML-Tiefe ist wirklich ungewöhnlich — dies ist eine weitaus granularere Struktur als die meisten europäischen E-Rechnungsstandards.', 'Brasilien betreibt nicht ein einziges E-Rechnungssystem — es betreibt mehrere, aufgeteilt nach Transaktionstyp und Regierungsebene, jedes mit seinen eigenen Eigenheiten.', 'Da die Steuerreform auf einem bereits ausgereiften bestehenden System aufbaut, bedeutet "Vorbereitung" hier vor allem die Aktualisierung dessen, was Sie bereits betreiben, nicht den Aufbau von Grund auf.', 'In Brasilien ist Ablehnung oft das schärfere praktische Risiko — eine blockierte Rechnung stoppt den Warenverkehr, was häufig schwerer wiegt als die Geldstrafe selbst.' FROM countries WHERE name_en = 'Brazil';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'fr', 'Contrôle multicouche (étatique + municipal + fédéral)', 'Cette analyse par pays reflète les directives techniques publiquement disponibles à juillet 2026 et est fournie à titre d''information générale, non comme un conseil juridique ou fiscal. La note technique 2025.002-RTC continue d''être révisée tout au long de la transition de la réforme fiscale, et les exigences étatiques/municipales varient — confirmez les exigences actuelles directement auprès de la SEFAZ, de la Receita Federal ou d''un conseiller fiscal brésilien avant de construire une intégration.', 'Le système NF-e du Brésil fonctionne depuis le milieu des années 2000 avec une adoption quasi universelle — l''actualité aujourd''hui est la réforme de la taxe à la consommation qui se superpose à l''infrastructure existante.', 'La profondeur du XML brésilien est véritablement inhabituelle — il s''agit d''une structure bien plus granulaire que la plupart des normes européennes de facturation électronique.', 'Le Brésil n''exploite pas un système unique de facturation électronique — il en exploite plusieurs, répartis par type de transaction et niveau de gouvernement, chacun avec ses propres particularités.', 'Comme la réforme fiscale se superpose à un système existant mature, « se préparer » ici signifie surtout mettre à niveau ce que vous exploitez déjà, pas construire à partir de zéro.', 'Au Brésil, le rejet est souvent le risque pratique le plus aigu — une facture bloquée arrête le mouvement des marchandises, ce qui compte souvent plus que l''amende elle-même.' FROM countries WHERE name_en = 'Brazil';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '500+', 'Etiquetas XML estructuradas' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '500+', 'Strukturierte XML-Tags' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '500+', 'Balises XML structurées' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '44 dígitos', 'Chave de acesso (clave de acceso)' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '44-stellig', 'Chave de acesso (Zugangsschlüssel)' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '44 chiffres', 'Chave de acesso (clé d''accès)' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '5.000+', 'Variaciones municipales de NFS-e' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '5.000+', 'Kommunale NFS-e-Varianten' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '5 000+', 'Variantes municipales de NFS-e' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '5 años', 'Requisito de archivo' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '5 Jahre', 'Aufbewahrungspflicht' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '5 ans', 'Obligation d''archivage' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'es', '2033', 'Migración completa de CBS/IBS finalizada' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'de', '2033', 'Vollständige CBS/IBS-Migration abgeschlossen' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'fr', '2033', 'Migration CBS/IBS complète achevée' FROM deep_dive_stats ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Estructura del documento', '[["Documento legal", "El XML firmado — no el DANFE impreso"], ["Profundidad de la estructura", "500+ etiquetas estructuradas, 400+ reglas de validación"], ["Códigos de modelo", "Modelo 55 (NF-e), Modelo 65 (NFC-e)"]]', 'El DANFE contiene menos del 10% de los datos del XML — trate cualquier proceso de AP que solo lea el DANFE como una re-introducción manual de información que ya existe en forma estructurada, y que probablemente omite detalles fiscales que afectan a la recuperación del crédito fiscal.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Dokumentstruktur', '[["Rechtsdokument", "Das signierte XML — nicht das gedruckte DANFE"], ["Strukturtiefe", "500+ strukturierte Tags, 400+ Validierungsregeln"], ["Modellcodes", "Modell 55 (NF-e), Modell 65 (NFC-e)"]]', 'Das DANFE enthält weniger als 10 % der XML-Daten — betrachten Sie jeden AP-Prozess, der nur das DANFE liest, als manuelle Neueingabe von Informationen, die bereits in strukturierter Form vorliegen, und der wahrscheinlich Steuerdetails übersieht, die die Vorsteuerrückgewinnung betreffen.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Structure du document', '[["Document légal", "Le XML signé — pas le DANFE imprimé"], ["Profondeur de structure", "500+ balises structurées, 400+ règles de validation"], ["Codes de modèle", "Modèle 55 (NF-e), Modèle 65 (NFC-e)"]]', 'Le DANFE contient moins de 10 % des données du XML — considérez tout processus AP qui ne lit que le DANFE comme une resaisie manuelle d''informations qui existent déjà sous forme structurée, et qui manque probablement des détails fiscaux affectant la récupération du crédit de TVA en amont.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'La clave de acceso de 44 dígitos', '[["Nombre", "Chave de acesso"], ["Alcance", "Única en todo Brasil, en todo momento"], ["Especificación que la rige", "SEFAZ Nota Técnica 2011/004"]]', 'Esta única clave es todo lo que necesita para verificar la autenticidad de una NF-e, comprobar si ha sido cancelada o recuperar el XML completo directamente de la SEFAZ — trátela como la referencia universal para cualquier factura brasileña.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Der 44-stellige Zugangsschlüssel', '[["Name", "Chave de acesso"], ["Umfang", "Eindeutig in ganz Brasilien, über die gesamte Zeit"], ["Maßgebliche Spezifikation", "SEFAZ Nota Técnica 2011/004"]]', 'Dieser einzelne Schlüssel ist alles, was Sie benötigen, um die Echtheit einer NF-e zu überprüfen, festzustellen, ob sie storniert wurde, oder das vollständige XML direkt von der SEFAZ abzurufen — betrachten Sie ihn als universelle Referenz für jede brasilianische Rechnung.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'La clé d''accès à 44 chiffres', '[["Nom", "Chave de acesso"], ["Portée", "Unique dans tout le Brésil, à travers le temps"], ["Spécification régissante", "SEFAZ Nota Técnica 2011/004"]]', 'Cette clé unique est tout ce dont vous avez besoin pour vérifier l''authenticité d''une NF-e, vérifier si elle a été annulée, ou récupérer le XML complet directement auprès de la SEFAZ — considérez-la comme la référence universelle pour toute facture brésilienne.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Firma digital', '[["Tipos de certificado", "A1 (basado en software) o A3 (token de hardware)"], ["Acreditación", "Autoridad certificadora acreditada por ICP-Brasil"]]', 'Ambos tipos de certificado son válidos — A1 se adapta a la emisión automatizada de gran volumen, A3 se adapta a escenarios de menor volumen o mayor seguridad, pero confirme cuál admite su integración ERP específica.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Digitale Signatur', '[["Zertifikatstypen", "A1 (softwarebasiert) oder A3 (Hardware-Token)"], ["Akkreditierung", "Von ICP-Brasil akkreditierte Zertifizierungsstelle"]]', 'Beide Zertifikatstypen sind gültig — A1 eignet sich für automatisierte Hochvolumen-Ausstellung, A3 für Szenarien mit geringerem Volumen oder höherer Sicherheit, aber bestätigen Sie, welches Ihre spezifische ERP-Integration unterstützt.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Signature numérique', '[["Types de certificat", "A1 (basé sur logiciel) ou A3 (jeton matériel)"], ["Accréditation", "Autorité de certification accréditée ICP-Brasil"]]', 'Les deux types de certificat sont valides — A1 convient à l''émission automatisée à haut volume, A3 convient aux scénarios à volume plus faible ou à sécurité renforcée, mais confirmez lequel votre intégration ERP spécifique prend en charge.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Nuevos campos de la reforma fiscal (NT 2025.002-RTC)', '[["Nuevos grupos", "Grupos de datos IBS, CBS e IS (Impuesto Selectivo)"], ["Nuevos códigos fiscales", "Códigos CST específicos para los tres nuevos impuestos"], ["Nuevos tipos de documento", "Notas de Débito y Crédito formales dentro del modelo 55"]]', 'Las Notas de Débito y Crédito son un instrumento genuinamente nuevo, no uno reutilizado — pero explícitamente no pueden usarse para ajustar el ICMS o IPI heredados a menos que esa legislación se modifique por separado.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Neue Steuerreformfelder (NT 2025.002-RTC)', '[["Neue Gruppen", "IBS-, CBS- und IS-Datengruppen (Selektivsteuer)"], ["Neue Steuercodes", "CST-Codes speziell für die drei neuen Steuern"], ["Neue Dokumenttypen", "Formale Lastschriften und Gutschriften innerhalb von Modell 55"]]', 'Last- und Gutschriften sind ein wirklich neues Instrument, kein umfunktioniertes altes — sie können jedoch ausdrücklich nicht zur Anpassung der Alt-ICMS oder -IPI verwendet werden, sofern diese Gesetzgebung nicht separat geändert wird.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Nouveaux champs de la réforme fiscale (NT 2025.002-RTC)', '[["Nouveaux groupes", "Groupes de données IBS, CBS et IS (taxe sélective)"], ["Nouveaux codes fiscaux", "Codes CST spécifiques aux trois nouvelles taxes"], ["Nouveaux types de documents", "Notes de débit et de crédit formelles au sein du modèle 55"]]', 'Les notes de débit et de crédit sont un instrument véritablement nouveau, pas un ancien réutilisé — mais elles ne peuvent explicitement pas être utilisées pour ajuster les anciens ICMS ou IPI sauf modification législative distincte.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'file_format' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'La familia de documentos', '[["NF-e", "Mercancías — SEFAZ a nivel estatal"], ["NFC-e", "Recibos minoristas/de consumidor — SEFAZ a nivel estatal"], ["CT-e", "Documentos de transporte — SEFAZ a nivel estatal"], ["NFS-e", "Servicios — nivel municipal (5.000+ variaciones)"]]', 'Qué sistema se aplica depende enteramente de lo que esté facturando — mercancías, transporte y venta minorista corresponden al estado; los servicios corresponden al municipio, y los requisitos municipales varían significativamente.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Die Dokumentenfamilie', '[["NF-e", "Waren — SEFAZ auf Bundesstaatenebene"], ["NFC-e", "Einzelhandels-/Verbraucherquittungen — SEFAZ auf Bundesstaatenebene"], ["CT-e", "Transportdokumente — SEFAZ auf Bundesstaatenebene"], ["NFS-e", "Dienstleistungen — kommunale Ebene (5.000+ Varianten)"]]', 'Welches System gilt, hängt vollständig davon ab, was Sie fakturieren — Waren, Transport und Einzelhandel liegen beim Bundesstaat; Dienstleistungen liegen bei der Gemeinde, und die kommunalen Anforderungen variieren erheblich.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'La famille de documents', '[["NF-e", "Marchandises — SEFAZ au niveau étatique"], ["NFC-e", "Reçus de détail/consommateur — SEFAZ au niveau étatique"], ["CT-e", "Documents de transport — SEFAZ au niveau étatique"], ["NFS-e", "Services — niveau municipal (5 000+ variantes)"]]', 'Le système applicable dépend entièrement de ce que vous facturez — marchandises, transport et vente au détail relèvent de l''État ; les services relèvent de la municipalité, et les exigences municipales varient considérablement.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'La fragmentación del NFS-e, y la solución en curso', '[["Estado actual", "Cada Prefeitura (municipio) establece sus propios requisitos"], ["Estándar nacional", "SNNFS-e (Sistema Nacional da Nota Fiscal de Serviços Eletrônica)"], ["Componentes", "Portal de envío centralizado + repositorio NDE (Entorno Nacional de Datos)"]]', 'La adopción del SNNFS-e es gradual y aún no obligatoria en todas partes — compruebe el estado actual de su municipio específico en lugar de asumir que la estandarización nacional ya se ha producido.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Die NFS-e-Fragmentierung und die laufende Lösung', '[["Aktueller Stand", "Jede Prefeitura (Gemeinde) legt ihre eigenen Anforderungen fest"], ["Nationaler Standard", "SNNFS-e (Sistema Nacional da Nota Fiscal de Serviços Eletrônica)"], ["Komponenten", "Zentralisiertes Einreichungsportal + NDE-Repository (National Data Environment)"]]', 'Die SNNFS-e-Einführung erfolgt schrittweise und ist noch nicht überall verpflichtend — prüfen Sie den aktuellen Status Ihrer spezifischen Gemeinde, statt anzunehmen, dass die nationale Standardisierung bereits erfolgt ist.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'La fragmentation du NFS-e, et la solution en cours', '[["État actuel", "Chaque Prefeitura (municipalité) fixe ses propres exigences"], ["Norme nationale", "SNNFS-e (Sistema Nacional da Nota Fiscal de Serviços Eletrônica)"], ["Composants", "Portail de soumission centralisé + dépôt NDE (National Data Environment)"]]', 'L''adoption du SNNFS-e est progressive et pas encore obligatoire partout — vérifiez le statut actuel de votre municipalité spécifique plutôt que de présumer que la normalisation nationale a déjà eu lieu.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', 'Lo que viene: Pago Dividido', '[["Base legal", "Acto Administrativo Conjunto RFB/CGIBS N.º 2/2026"], ["Qué hace", "Publica documentación técnica para una Plataforma Pública de Pago Dividido"]]', 'Esta es una pieza emergente de la arquitectura de la reforma — la remesa automática de impuestos en el momento del pago — que vale la pena seguir aunque todavía no sea una obligación vigente.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', 'Was kommt: Split Payment', '[["Rechtsgrundlage", "Gemeinsamer Verwaltungsakt RFB/CGIBS Nr. 2/2026"], ["Was es bewirkt", "Veröffentlicht technische Dokumentation für eine öffentliche Split-Payment-Plattform"]]', 'Dies ist ein aufkommender Baustein der Reformarchitektur — automatische Steuerabführung zum Zeitpunkt der Zahlung — der es wert ist, verfolgt zu werden, auch wenn er noch keine geltende Pflicht ist.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', 'Ce qui arrive : le paiement scindé', '[["Base juridique", "Acte administratif conjoint RFB/CGIBS n° 2/2026"], ["Ce que cela fait", "Publie la documentation technique d''une plateforme publique de paiement scindé"]]', 'Il s''agit d''un élément émergent de l''architecture de la réforme — la remise automatique de la taxe au moment du paiement — qui mérite d''être suivi même s''il ne s''agit pas encore d''une obligation en vigueur.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) SELECT dlc.id, 'es', 'El flujo de compensación de la NF-e', NULL, 'La NF-e también se transmite al repositorio nacional de la Receita Federal do Brasil (Ambiente Nacional) — un respaldo a nivel federal que existe junto con la autorización a nivel estatal.' FROM deep_dive_lifecycle_cards dlc JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil';
INSERT OR IGNORE INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) SELECT dlc.id, 'de', 'Der NF-e-Clearing-Ablauf', NULL, 'Die NF-e wird ebenfalls an das nationale Repository der Receita Federal do Brasil (Ambiente Nacional) übermittelt — eine föderale Absicherung, die neben der bundesstaatlichen Autorisierung besteht.' FROM deep_dive_lifecycle_cards dlc JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil';
INSERT OR IGNORE INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) SELECT dlc.id, 'fr', 'Le flux de contrôle de la NF-e', NULL, 'La NF-e est également transmise au référentiel national de la Receita Federal do Brasil (Ambiente Nacional) — une sauvegarde au niveau fédéral qui existe parallèlement à l''autorisation au niveau étatique.' FROM deep_dive_lifecycle_cards dlc JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil';

INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'es', '1. Generar XML' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'de', '1. XML erzeugen' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'fr', '1. Générer le XML' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'es', '2. Firmar digitalmente' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'de', '2. Digital signieren' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'fr', '2. Signer numériquement' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'es', '3. Enviar mediante SOAP a la SEFAZ estatal' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'de', '3. Über SOAP an die bundesstaatliche SEFAZ übermitteln' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'fr', '3. Soumettre via SOAP à la SEFAZ étatique' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'es', '4. La SEFAZ autoriza' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'de', '4. SEFAZ autorisiert' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'fr', '4. La SEFAZ autorise' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'es', '5. Enviar con el DANFE' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'de', '5. Mit DANFE versenden' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT dls.id, 'fr', '5. Expédier avec le DANFE' FROM deep_dive_lifecycle_statuses_v2 dls JOIN deep_dive_lifecycle_cards dlc ON dlc.id = dls.card_id JOIN countries c ON c.id = dlc.country_id WHERE c.name_en = 'Brazil' AND dls.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Obtenga un certificado digital ICP-Brasil', 'Elija A1 o A3 según su volumen e infraestructura, de una autoridad certificadora acreditada — esto es necesario antes de poder firmar una sola NF-e.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Beschaffen Sie ein digitales ICP-Brasil-Zertifikat', 'Wählen Sie je nach Volumen und Infrastruktur A1 oder A3 von einer akkreditierten Zertifizierungsstelle — dies ist erforderlich, bevor Sie auch nur eine einzige NF-e signieren können.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Obtenez un certificat numérique ICP-Brasil', 'Choisissez A1 ou A3 selon votre volume et votre infrastructure, auprès d''une autorité de certification accréditée — ceci est requis avant de pouvoir signer la moindre NF-e.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Configure su establecimiento fiscal', 'Configure el certificado, el entorno, la versión de NF-e, la autoridad, la validación del esquema y el modo de contingencia por establecimiento fiscal en su ERP — se trata de una configuración genuinamente por establecimiento, no de un ajuste global único.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Konfigurieren Sie Ihre steuerliche Niederlassung', 'Richten Sie Zertifikat, Umgebung, NF-e-Version, Behörde, Schemavalidierung und Notfallmodus pro steuerlicher Niederlassung in Ihrem ERP ein — dies ist eine wirklich niederlassungsbezogene Konfiguration, keine einmalige globale Einstellung.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Configurez votre établissement fiscal', 'Configurez le certificat, l''environnement, la version NF-e, l''autorité, la validation du schéma et le mode de contingence par établissement fiscal dans votre ERP — il s''agit d''une configuration véritablement par établissement, pas d''un réglage global unique.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Actualice a la Nota Técnica 2025.002-RTC (versión actual)', 'Asigne los nuevos campos IBS, CBS e IS y los códigos fiscales CST actualizados en sus diseños de facturación — verifique cuidadosamente el número de versión, ya que esta nota se ha revisado varias veces durante 2025–2026.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Aktualisieren Sie auf die Technische Mitteilung 2025.002-RTC (aktuelle Version)', 'Ordnen Sie die neuen IBS-, CBS- und IS-Felder sowie die aktualisierten CST-Steuercodes in Ihre Rechnungslayouts ein — prüfen Sie die Versionsnummer sorgfältig, da diese Mitteilung 2025–2026 mehrfach überarbeitet wurde.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Mettez à jour vers la note technique 2025.002-RTC (version actuelle)', 'Associez les nouveaux champs IBS, CBS et IS ainsi que les codes fiscaux CST mis à jour dans vos formats de facturation — vérifiez attentivement le numéro de version, car cette note a été révisée plusieurs fois en 2025-2026.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Pruebe en el entorno de homologación de la SEFAZ', 'Use los mismos certificados que en producción, apuntando a servidores de prueba, para validar sus nuevos campos de la reforma fiscal antes de que afecten a facturas reales.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Testen Sie in der Homologationsumgebung der SEFAZ', 'Verwenden Sie dieselben Zertifikate wie in der Produktion, gerichtet auf Testserver, um Ihre neuen Steuerreformfelder zu validieren, bevor sie echte Rechnungen betreffen.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Testez dans l''environnement d''homologation de la SEFAZ', 'Utilisez les mêmes certificats qu''en production, pointés vers des serveurs de test, pour valider vos nouveaux champs de réforme fiscale avant qu''ils n''affectent de vraies factures.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Construya los nuevos flujos de trabajo de Notas de Débito/Crédito', 'Implemente los instrumentos formalizados de Notas de Débito y Crédito del modelo 55 para los ajustes de CBS/IBS — recordando que no pueden usarse para correcciones heredadas de ICMS/IPI sin un cambio legislativo separado.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Bauen Sie die neuen Last-/Gutschriften-Workflows auf', 'Implementieren Sie die formalisierten Modell-55-Last- und Gutschrifteninstrumente für CBS/IBS-Anpassungen — denken Sie daran, dass sie ohne separate Gesetzesänderung nicht für Alt-ICMS-/IPI-Korrekturen verwendet werden können.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Construisez les nouveaux flux de travail de notes de débit/crédit', 'Mettez en œuvre les instruments formalisés de notes de débit et de crédit du modèle 55 pour les ajustements CBS/IBS — en gardant à l''esprit qu''ils ne peuvent pas être utilisés pour des corrections ICMS/IPI héritées sans modification législative distincte.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Compruebe los requisitos específicos del municipio de su NFS-e', 'Si emite facturas de servicios, confirme por separado la especificación NFS-e actual de su municipio y el estado de adopción del SNNFS-e — no asuma todavía uniformidad nacional.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 5;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Prüfen Sie die spezifischen Anforderungen Ihrer NFS-e-Gemeinde', 'Wenn Sie Dienstleistungsrechnungen ausstellen, bestätigen Sie separat die aktuelle NFS-e-Spezifikation und den SNNFS-e-Einführungsstatus Ihrer Gemeinde — gehen Sie noch nicht von nationaler Einheitlichkeit aus.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 5;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Vérifiez les exigences spécifiques de votre municipalité NFS-e', 'Si vous émettez des factures de services, confirmez séparément la spécification NFS-e actuelle de votre municipalité et le statut d''adoption du SNNFS-e — ne présumez pas encore d''une uniformité nationale.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 5;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'es', 'Confirme el calendario de transición de su régimen', 'Las empresas de Simples Nacional y MEI generalmente tienen una transición extendida (hasta 2027) en comparación con los contribuyentes del Régimen Normal/General — verifique cuál se aplica a usted antes de asumir los mismos plazos.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 6;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'de', 'Bestätigen Sie den Übergangszeitplan Ihres Steuersystems', 'Simples-Nacional- und MEI-Unternehmen haben im Allgemeinen einen verlängerten Übergang (bis 2027) im Vergleich zu Steuerpflichtigen des normalen/allgemeinen Steuersystems — prüfen Sie, welcher für Sie gilt, bevor Sie dieselben Fristen annehmen.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 6;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'fr', 'Confirmez le calendrier de transition de votre régime', 'Les entreprises Simples Nacional et MEI bénéficient généralement d''une transition prolongée (jusqu''en 2027) par rapport aux contribuables du régime normal/général — vérifiez lequel s''applique à vous avant de présumer des mêmes échéances.' FROM deep_dive_steps ds JOIN countries c ON c.id = ds.country_id WHERE c.name_en = 'Brazil' AND ds.sort_order = 6;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', '🚧 El rechazo como sanción operativa', NULL, NULL, 'A partir del 3 de agosto de 2026, los datos IBS/CBS faltantes o inconsistentes corren el riesgo de rechazo directo del documento en producción — una NF-e rechazada no puede usarse para enviar mercancías, lo que convierte esto en un riesgo de interrupción de la cadena de suministro tanto como de cumplimiento.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', '🚧 Ablehnung als operative Sanktion', NULL, NULL, 'Ab dem 3. August 2026 riskieren fehlende oder inkonsistente IBS/CBS-Daten eine direkte Ablehnung des Dokuments in der Produktion — eine abgelehnte NF-e kann nicht zum Versand von Waren verwendet werden, was dies ebenso zu einem Lieferkettenrisiko wie zu einem Compliance-Risiko macht.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', '🚧 Le rejet comme sanction opérationnelle', NULL, NULL, 'À partir du 3 août 2026, des données IBS/CBS manquantes ou incohérentes risquent un rejet pur et simple du document en production — une NF-e rejetée ne peut pas être utilisée pour expédier des marchandises, ce qui en fait autant un risque de perturbation de la chaîne d''approvisionnement qu''un risque de conformité.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', '🌱 El aterrizaje suave fue informal, no una exención legal', NULL, NULL, 'Incluso durante el período de gracia de enero a abril de 2026, en el que los campos IBS/CBS faltantes no provocaban rechazo, la obligación legal subyacente de incluir esos datos ya estaba vigente — las empresas que la omitieron por completo aún enfrentan exposición a sanciones de forma retroactiva.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', '🌱 Die sanfte Landung war informell, keine gesetzliche Befreiung', NULL, NULL, 'Selbst während der Übergangsfrist von Januar bis April 2026, in der fehlende IBS/CBS-Felder keine Ablehnung auslösten, galt die zugrunde liegende gesetzliche Pflicht zur Angabe dieser Daten bereits — Unternehmen, die sie vollständig ausließen, sind rückwirkend weiterhin einem Strafrisiko ausgesetzt.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', '🌱 L''atterrissage en douceur était informel, pas une exemption légale', NULL, NULL, 'Même pendant la période de grâce de janvier à avril 2026, où des champs IBS/CBS manquants n''entraînaient pas de rejet, l''obligation légale sous-jacente d''inclure ces données était déjà en vigueur — les entreprises qui l''ont complètement ignorée restent exposées à des sanctions rétroactives.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', '🏛️ La variación a nivel estatal añade complejidad', NULL, NULL, 'Los estados individuales pueden superponer sus propios mandatos técnicos al marco federal — Goiás, por ejemplo, exige por separado que los contribuyentes de ICMS integren los sistemas de pago (tarjetas, PIX) directamente con la emisión de NF-e/NFC-e en tiempo real.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', '🏛️ Bundesstaatliche Abweichungen erhöhen die Komplexität', NULL, NULL, 'Einzelne Bundesstaaten können ihre eigenen technischen Vorgaben auf das föderale Rahmenwerk aufsetzen — Goiás beispielsweise verlangt separat von ICMS-Steuerpflichtigen, Zahlungssysteme (Karten, PIX) in Echtzeit direkt mit der NF-e/NFC-e-Ausstellung zu integrieren.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', '🏛️ Les variations au niveau étatique ajoutent de la complexité', NULL, NULL, 'Certains États peuvent superposer leurs propres mandats techniques au cadre fédéral — Goiás, par exemple, exige séparément des contribuables ICMS qu''ils intègrent les systèmes de paiement (cartes, PIX) directement avec l''émission de NF-e/NFC-e en temps réel.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'es', '🌍 Proveedores extranjeros recién incluidos en el alcance', NULL, NULL, 'La reforma extiende las obligaciones de CBS/IBS a los proveedores extranjeros de servicios digitales por primera vez — anteriormente, los proveedores extranjeros generalmente no podían registrarse sin presencia local, y los servicios digitales transfronterizos a menudo caían bajo el ISS municipal.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'de', '🌍 Ausländische Anbieter neu im Anwendungsbereich', NULL, NULL, 'Die Reform erweitert die CBS/IBS-Pflichten erstmals auf ausländische Anbieter digitaler Dienstleistungen — zuvor konnten sich ausländische Anbieter im Allgemeinen nicht ohne lokale Präsenz registrieren, und grenzüberschreitende digitale Dienstleistungen fielen oft stattdessen unter die kommunale ISS.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'fr', '🌍 Les fournisseurs étrangers nouvellement concernés', NULL, NULL, 'La réforme étend pour la première fois les obligations CBS/IBS aux fournisseurs étrangers de services numériques — auparavant, les fournisseurs étrangers ne pouvaient généralement pas s''enregistrer sans présence locale, et les services numériques transfrontaliers relevaient souvent de l''ISS municipal à la place.', NULL, NULL FROM deep_dive_cards dc JOIN countries c ON c.id = dc.country_id WHERE c.name_en = 'Brazil' AND dc.section = 'penalties_related' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'es', 'Portal Nacional da NF-e (SEFAZ)' FROM deep_dive_portals dp JOIN countries c ON c.id = dp.country_id WHERE c.name_en = 'Brazil' AND dp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'de', 'Portal Nacional da NF-e (SEFAZ)' FROM deep_dive_portals dp JOIN countries c ON c.id = dp.country_id WHERE c.name_en = 'Brazil' AND dp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'fr', 'Portal Nacional da NF-e (SEFAZ)' FROM deep_dive_portals dp JOIN countries c ON c.id = dp.country_id WHERE c.name_en = 'Brazil' AND dp.sort_order = 0;
