-- Peru milestones (Stage 4 deep-dive/tracker migration)
-- 5 total: 4 deep-dive-only + 1 tracker-matched (pe-established),
-- an exact date/event match with the tracker's own DATA entry -- tracker phrasing wins.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pe-rollout-2017', id, '2017-01-01', 0, NULL FROM countries WHERE name_en = 'Peru';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-rollout-2017', 'en', 'Mandatory rollout begins with large taxpayers', 'SUNAT starts requiring the largest businesses to issue Comprobantes de Pago Electrónicos, establishing the clearance infrastructure the rest of the economy would later join.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pe-ubl21-2019', id, '2019-03-01', 0, NULL FROM countries WHERE name_en = 'Peru';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ubl21-2019', 'en', 'UBL 2.1 becomes the only supported format', 'Earlier UBL 2.0 documents are no longer accepted — every CPE from this date must be structured according to UBL 2.1.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pe-ose-2019', id, '2019-07-01', 0, NULL FROM countries WHERE name_en = 'Peru';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ose-2019', 'en', 'OSE validation compulsory for big contributors', 'Large taxpayers with automated billing must use an authorised Electronic Services Operator (OSE) for validation, rather than relying on SUNAT''s own free tools.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pe-established', id, '2022-06-01', 1, 'https://www.sunat.gob.pe' FROM countries WHERE name_en = 'Peru';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-established', 'en', 'E-invoicing (CPE) mandatory for all taxpayers (in force since Jun 2022)', 'Peru operates one of Latin America''s most mature e-invoicing systems. Electronic Payment Receipts (CPE) must be issued in UBL 2.1 XML, digitally signed, and validated by SUNAT or an authorised Electronic Services Operator (OSE) before they are legally valid.', '["Use an approved Electronic Service Provider (PSE) to generate and sign CPEs", "Send e-invoices to SUNAT within 3 calendar days of issuance", "Archive XML invoices and CDR receipt confirmations for at least 5 years"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'pe-airline-2026', id, '2026-08-01', 0, NULL FROM countries WHERE name_en = 'Peru';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-airline-2026', 'en', 'New airline ticket reporting system takes effect', 'Superintendency Resolution No. 000033-2026/SUNAT introduces a digital reporting system for commercial airlines providing scheduled passenger transport, replacing the older PDT No. 3540-based model with one aligned to the standard e-invoicing infrastructure.', '[]');
