-- Peru milestone translations (ES/DE/FR)

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-rollout-2017', 'es', 'Comienza el despliegue obligatorio con los grandes contribuyentes', 'La SUNAT comienza a exigir a las empresas más grandes que emitan Comprobantes de Pago Electrónicos, estableciendo la infraestructura de compensación a la que el resto de la economía se uniría más tarde.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-rollout-2017', 'de', 'Verpflichtender Rollout beginnt mit Großsteuerpflichtigen', 'Die SUNAT beginnt, von den größten Unternehmen die Ausstellung von Comprobantes de Pago Electrónicos zu verlangen und legt damit die Clearing-Infrastruktur fest, der sich der Rest der Wirtschaft später anschließen würde.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-rollout-2017', 'fr', 'Le déploiement obligatoire commence avec les grands contribuables', 'La SUNAT commence à exiger des plus grandes entreprises qu''elles émettent des Comprobantes de Pago Electrónicos, établissant l''infrastructure de contrôle que le reste de l''économie rejoindrait plus tard.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ubl21-2019', 'es', 'UBL 2.1 se convierte en el único formato admitido', 'Los documentos UBL 2.0 anteriores ya no se aceptan — cada CPE a partir de esta fecha debe estructurarse conforme a UBL 2.1.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ubl21-2019', 'de', 'UBL 2.1 wird zum einzig unterstützten Format', 'Frühere UBL-2.0-Dokumente werden nicht mehr akzeptiert — jede CPE muss ab diesem Datum gemäß UBL 2.1 strukturiert sein.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ubl21-2019', 'fr', 'UBL 2.1 devient le seul format pris en charge', 'Les documents UBL 2.0 antérieurs ne sont plus acceptés — chaque CPE à partir de cette date doit être structuré selon UBL 2.1.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ose-2019', 'es', 'La validación OSE se vuelve obligatoria para los grandes contribuyentes', 'Los grandes contribuyentes con facturación automatizada deben utilizar un Operador de Servicios Electrónicos (OSE) autorizado para la validación, en lugar de depender de las herramientas gratuitas de la propia SUNAT.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ose-2019', 'de', 'OSE-Validierung für Großsteuerpflichtige verpflichtend', 'Großsteuerpflichtige mit automatisierter Rechnungsstellung müssen für die Validierung einen autorisierten Electronic Services Operator (OSE) nutzen, anstatt sich auf die eigenen kostenlosen Tools der SUNAT zu verlassen.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-ose-2019', 'fr', 'La validation OSE devient obligatoire pour les grands contribuables', 'Les grands contribuables disposant d''une facturation automatisée doivent utiliser un opérateur de services électroniques (OSE) autorisé pour la validation, plutôt que de s''appuyer sur les outils gratuits propres de la SUNAT.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-established', 'es', 'Facturación electrónica (CPE) obligatoria para todos los contribuyentes (en vigor desde junio de 2022)', 'Perú opera uno de los sistemas de facturación electrónica más maduros de América Latina. Los Comprobantes de Pago Electrónicos (CPE) deben emitirse en XML UBL 2.1, firmarse digitalmente y ser validados por la SUNAT o un Operador de Servicios Electrónicos (OSE) autorizado antes de tener validez legal.', '["Use un Proveedor de Servicios Electrónicos (PSE) aprobado para generar y firmar CPEs", "Envíe las facturas electrónicas a la SUNAT dentro de los 3 días calendario posteriores a la emisión", "Archive las facturas XML y las confirmaciones de recepción CDR durante al menos 5 años"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-established', 'de', 'E-Rechnungsstellung (CPE) für alle Steuerpflichtigen verpflichtend (in Kraft seit Juni 2022)', 'Peru betreibt eines der ausgereiftesten E-Rechnungssysteme Lateinamerikas. Elektronische Zahlungsbelege (CPE) müssen im UBL-2.1-XML-Format ausgestellt, digital signiert und von der SUNAT oder einem autorisierten Electronic Services Operator (OSE) validiert werden, bevor sie rechtsgültig sind.', '["Verwenden Sie einen zugelassenen Electronic Service Provider (PSE), um CPEs zu erstellen und zu signieren", "Senden Sie E-Rechnungen innerhalb von 3 Kalendertagen nach Ausstellung an die SUNAT", "Bewahren Sie XML-Rechnungen und CDR-Empfangsbestätigungen mindestens 5 Jahre lang auf"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-established', 'fr', 'Facturation électronique (CPE) obligatoire pour tous les contribuables (en vigueur depuis juin 2022)', 'Le Pérou exploite l''un des systèmes de facturation électronique les plus matures d''Amérique latine. Les reçus de paiement électroniques (CPE) doivent être émis en XML UBL 2.1, signés numériquement et validés par la SUNAT ou un opérateur de services électroniques (OSE) autorisé avant d''être légalement valides.', '["Utilisez un fournisseur de services électroniques (PSE) approuvé pour générer et signer les CPE", "Envoyez les factures électroniques à la SUNAT dans les 3 jours calendaires suivant l''émission", "Archivez les factures XML et les confirmations de réception CDR pendant au moins 5 ans"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-airline-2026', 'es', 'Entra en vigor el nuevo sistema de reporte de boletos aéreos', 'La Resolución de Superintendencia N.° 000033-2026/SUNAT introduce un sistema de reporte digital para las aerolíneas comerciales que prestan transporte regular de pasajeros, sustituyendo el antiguo modelo basado en el PDT N.° 3540 por uno alineado con la infraestructura estándar de facturación electrónica.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-airline-2026', 'de', 'Neues Meldesystem für Flugtickets tritt in Kraft', 'Die Aufsichtsverfügung Nr. 000033-2026/SUNAT führt ein digitales Meldesystem für kommerzielle Fluggesellschaften ein, die planmäßigen Passagiertransport anbieten, und ersetzt das ältere PDT-Nr.-3540-basierte Modell durch eines, das an die Standard-E-Rechnungsinfrastruktur angepasst ist.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('pe-airline-2026', 'fr', 'Entrée en vigueur du nouveau système de déclaration des billets d''avion', 'La résolution de surintendance n° 000033-2026/SUNAT introduit un système de déclaration numérique pour les compagnies aériennes commerciales assurant un transport régulier de passagers, remplaçant l''ancien modèle basé sur le PDT n° 3540 par un système aligné sur l''infrastructure standard de facturation électronique.', '[]');
