-- United States milestone translations (ES/DE/FR)

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-omb-2015', 'es', 'El Memorándum M-15-19 de la OMB ordena la facturación electrónica a las agencias federales', 'Se ordena a las agencias federales pasar a la facturación electrónica para las contrataciones apropiadas antes del final del año fiscal 2018, utilizando un proveedor de servicios compartidos federal o una solución aprobada como la Plataforma de Procesamiento de Facturas del Tesoro.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-omb-2015', 'de', 'OMB-Rundschreiben M-15-19 verpflichtet Bundesbehörden zur E-Rechnungsstellung', 'Bundesbehörden werden angewiesen, für geeignete Beschaffungen bis zum Ende des Haushaltsjahres 2018 auf elektronische Rechnungsstellung umzusteigen, unter Nutzung eines föderalen Shared-Service-Anbieters oder einer genehmigten Lösung wie der Invoice Processing Platform des Finanzministeriums.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-omb-2015', 'fr', 'Le mémorandum OMB M-15-19 impose la facturation électronique aux agences fédérales', 'Les agences fédérales reçoivent l''ordre de passer à la facturation électronique pour les marchés appropriés d''ici la fin de l''exercice fiscal 2018, en utilisant un fournisseur de services partagés fédéral ou une solution approuvée comme la plateforme de traitement des factures du Trésor.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-federal-b2g', 'es', 'Las agencias federales deben gestionar las facturas electrónicamente (B2G, en vigor desde 2018)', 'La Oficina de Administración y Presupuesto ordenó a las agencias federales pasar a la facturación electrónica para las contrataciones apropiadas. La mayoría utiliza ahora la Plataforma de Procesamiento de Facturas (IPP) del Tesoro — pero no existe un formato único obligatorio, ni ningún mandato B2B nacional de ningún tipo.', '["Si vende a agencias federales, confirme que está configurado en la IPP o en el canal de facturación electrónica designado por su agencia", "Conserve los registros de facturas electrónicas de manera que permanezcan accesibles, precisos y legibles según la orientación del IRS (Publicación 583)"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-federal-b2g', 'de', 'Bundesbehörden müssen Rechnungen elektronisch verwalten (B2G, in Kraft seit 2018)', 'Das Office of Management and Budget wies Bundesbehörden an, für geeignete Beschaffungen auf elektronische Rechnungsstellung umzusteigen. Die meisten nutzen inzwischen die Invoice Processing Platform (IPP) des Finanzministeriums — aber es gibt kein einheitlich vorgeschriebenes Format und kein inländisches B2B-Mandat jeglicher Art.', '["Wenn Sie an Bundesbehörden verkaufen, bestätigen Sie, dass Sie über die IPP oder den von Ihrer Behörde vorgesehenen E-Rechnungskanal eingerichtet sind", "Bewahren Sie elektronische Rechnungsunterlagen so auf, dass sie gemäß IRS-Richtlinie (Publication 583) zugänglich, korrekt und lesbar bleiben"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-federal-b2g', 'fr', 'Les agences fédérales doivent gérer les factures électroniquement (B2G, en vigueur depuis 2018)', 'L''Office of Management and Budget a ordonné aux agences fédérales de passer à la facturation électronique pour les marchés appropriés. La plupart utilisent désormais la plateforme de traitement des factures (IPP) du Trésor — mais il n''existe aucun format unique obligatoire, ni aucun mandat B2B national d''aucune sorte.', '["Si vous vendez à des agences fédérales, confirmez que vous êtes configuré sur l''IPP ou le canal de facturation électronique désigné par votre agence", "Conservez les enregistrements de factures électroniques de manière à ce qu''ils restent accessibles, exacts et lisibles conformément aux directives de l''IRS (Publication 583)"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-bpc-pilot-2022', 'es', 'Comienza el Piloto del Mercado de Intercambio de Facturas Electrónicas de la Business Payments Coalition', 'La primera ola conecta a unas 20 empresas; para mayo de 2022, más de 75 empresas internacionales se han unido a través de tres oleadas de implementación, probando la entrega segura de facturas electrónicas entre proveedores de servicios.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-bpc-pilot-2022', 'de', 'Der E-Invoice Exchange Market Pilot der Business Payments Coalition beginnt', 'Die erste Welle verbindet rund 20 Unternehmen; bis Mai 2022 sind über 75 internationale Unternehmen in drei Rollout-Wellen beigetreten und testen die sichere Zustellung von E-Rechnungen zwischen Dienstanbietern.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-bpc-pilot-2022', 'fr', 'Début du pilote de marché d''échange de factures électroniques de la Business Payments Coalition', 'La première vague connecte environ 20 entreprises ; d''ici mai 2022, plus de 75 entreprises internationales ont rejoint le programme à travers trois vagues de déploiement, testant la livraison sécurisée de factures électroniques entre fournisseurs de services.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-pilot-finalised-2023', 'es', 'El piloto se extiende; se finalizan las reglas y especificaciones', 'La BPC y la Reserva Federal formalizan las reglas y especificaciones técnicas del marco de intercambio, pasando de una prueba de concepto a una estructura de gobernanza duradera.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-pilot-finalised-2023', 'de', 'Pilot wird ausgeweitet; Regeln und Spezifikationen finalisiert', 'Die BPC und die Federal Reserve formalisieren die Regeln und technischen Spezifikationen des Austauschrahmens und gehen vom Proof-of-Concept zu einer dauerhaften Governance-Struktur über.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-pilot-finalised-2023', 'fr', 'Le pilote s''étend ; les règles et spécifications sont finalisées', 'La BPC et la Réserve fédérale formalisent les règles et spécifications techniques du cadre d''échange, passant d''une preuve de concept à une structure de gouvernance durable.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-dbnalliance', 'es', 'Red de intercambio de facturas electrónicas B2B DBNAlliance en funcionamiento (voluntaria, impulsada por el mercado)', 'La Digital Business Networks Alliance (DBNAlliance) — una organización sin fines de lucro surgida de un piloto de la Reserva Federal / Business Payments Coalition — opera ahora una red de cuatro esquinas al estilo Peppol para el intercambio voluntario y estructurado de facturas electrónicas B2B en EE. UU. y Canadá. Ninguna ley federal o estatal exige su adopción.', '["Considere conectarse a través de un proveedor de servicios certificado por DBNAlliance antes de cualquier mandato futuro", "Si comercia con socios en países que ya exigen la facturación electrónica (UE, México, Brasil, etc.), asegúrese de que sus sistemas todavía puedan producir los formatos que requieren"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-dbnalliance', 'de', 'DBNAlliance-B2B-E-Rechnungsaustauschnetzwerk live (freiwillig, marktgeführt)', 'Die Digital Business Networks Alliance (DBNAlliance) — eine gemeinnützige Organisation, die aus einem Pilotprojekt der Federal Reserve/Business Payments Coalition hervorgegangen ist — betreibt nun ein Peppol-ähnliches Vier-Ecken-Netzwerk für den freiwilligen strukturierten B2B-E-Rechnungsaustausch in den USA und Kanada. Kein Bundes- oder Landesgesetz schreibt die Einführung vor.', '["Erwägen Sie eine Anbindung über einen DBNAlliance-zertifizierten Dienstanbieter vor einem etwaigen künftigen Mandat", "Wenn Sie mit Partnern in Ländern handeln, die die E-Rechnungsstellung bereits vorschreiben (EU, Mexiko, Brasilien usw.), stellen Sie sicher, dass Ihre Systeme weiterhin deren erforderliche Formate erzeugen können"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-dbnalliance', 'fr', 'Le réseau d''échange de factures électroniques B2B DBNAlliance est en service (volontaire, piloté par le marché)', 'La Digital Business Networks Alliance (DBNAlliance) — une organisation à but non lucratif issue d''un pilote de la Réserve fédérale / Business Payments Coalition — exploite désormais un réseau à quatre coins de style Peppol pour l''échange volontaire et structuré de factures électroniques B2B aux États-Unis et au Canada. Aucune loi fédérale ou d''État n''exige son adoption.', '["Envisagez de vous connecter via un fournisseur de services certifié DBNAlliance avant tout futur mandat", "Si vous commercez avec des partenaires dans des pays qui imposent déjà la facturation électronique (UE, Mexique, Brésil, etc.), assurez-vous que vos systèmes peuvent toujours produire leurs formats requis"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-first-invoice-2024', 'es', 'Se transfiere con éxito la primera factura a través de la red DBNAlliance', 'Un hito operativo genuino — prueba de que la red funciona en producción, no solo en pruebas piloto.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-first-invoice-2024', 'de', 'Erste Rechnung erfolgreich über das DBNAlliance-Netzwerk übertragen', 'Ein echter operativer Meilenstein — Beweis, dass das Netzwerk in der Produktion funktioniert, nicht nur im Pilottest.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('us-first-invoice-2024', 'fr', 'Première facture transférée avec succès via le réseau DBNAlliance', 'Une véritable étape opérationnelle — preuve que le réseau fonctionne en production, pas seulement en phase pilote.', '[]');
