-- Canada milestones (Stage 4 deep-dive/tracker migration)
-- 4 total: 2 deep-dive-only + 2 tracker-matched (ca-watch, ca-federal-b2g),
-- both topical/exact date matches with the tracker's own DATA entries -- tracker phrasing wins.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ca-cra-research-2018', id, '2018-01-01', 0, NULL FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ca-cra-research-2018', 'en', 'CRA launches research into electronic invoicing', 'The Canada Revenue Agency begins early-stage research initiatives into e-invoicing — years before any concrete proposal would follow.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ca-watch', id, '2021-06-01', 1, 'https://www.canada.ca/en/revenue-agency.html' FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ca-watch', 'en', 'CRA studies a potential B2B e-invoicing mandate (no mandate enacted)', 'The Canada Revenue Agency conducted stakeholder research into a possible domestic B2B e-invoicing mandate. No legislation or firm timeline has followed — GST/HST rules remain format-neutral, and paper, PDF, and EDI invoices are all currently acceptable provided they carry the required tax information.', '["No action required today beyond good record-keeping practice", "Monitor for future CRA / Finance Canada announcements, particularly as DBNAlliance network adoption grows in Canada"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ca-federal-b2g', id, '2022-04-01', 1, 'https://www.canada.ca/en/public-services-procurement/services/acquisitions/support-for-businesses/electronic-procurement-transition.html' FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ca-federal-b2g', 'en', 'All federal government suppliers must invoice electronically (B2G, in force since 2022)', 'Since April 2022, Public Services and Procurement Canada (PSPC) has required suppliers to submit invoices electronically through its SAP Ariba-based electronic procurement solution. There is no federal B2B e-invoicing mandate.', '["If you supply the Government of Canada, register in SAP Ariba via CanadaBuys", "Retain electronic invoices for at least 6 years per CRA record-keeping requirements"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'ca-regulatory-plan-2025', id, '2025-01-01', 0, NULL FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ca-regulatory-plan-2025', 'en', 'CRA''s regulatory plans list digital reporting initiatives — but not e-invoicing by name', 'CRA''s forward regulatory plan includes various digital reporting rules for this period, but none explicitly names an e-invoicing mandate — a signal that the topic remains on the agenda without a committed timeline.', '[]');
