-- Canada deep-dive content: page, stats, file_format cards (including a 5th card
-- mapping the static page's dedicated "Provincial tax variation" .prov-table section,
-- since the renderer has no distinct section type for it), scope_transmission cards
-- (no flow-grid/lifecycle card this time), steps, penalties_related cards, 2 portals.
-- No penalty rows/table.

INSERT OR IGNORE INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'No B2B mandate — B2G via SAP Ariba', 'This deep-dive page reflects publicly available guidance as of July 2026 and is provided for general awareness, not legal or tax advice. Canada''s B2B e-invoicing landscape remains voluntary with no mandate on the horizon — confirm current developments directly with the CRA or PSPC before making infrastructure decisions.', 'Canada''s federal government moved decisively on its own procurement; everything beyond that has stayed at the study-and-signal stage for several years running.', 'Outside federal procurement, Canada doesn''t prescribe a format at all — the requirement is about invoice content, not structure.', 'There is no B2B e-invoicing mandate in Canada, and none currently proposed on a fixed timeline. The one real, existing obligation is federal B2G — suppliers to the Government of Canada must invoice electronically via SAP Ariba. Two entirely separate worlds exist side by side: a mandated federal channel, and an unregulated everything-else.', 'What "getting ready" means here depends entirely on which side of the federal/everything-else line your business sits on.', 'No penalty framework exists for B2B non-adoption — because there''s nothing mandatory to fail to adopt.' FROM countries WHERE name_en = 'Canada';

INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'No B2B', 'Federal mandate — none' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'SAP Ariba', 'B2G channel via CanadaBuys' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '9 fields', 'CRA-required invoice content' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '6 yrs', 'Record retention' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '2021', 'CRA''s B2B feasibility study' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'What CRA actually requires', '[["Format", "Any readable format — paper, PDF, or EDI"], ["Numbering", "No prescribed format, but must be unique and traceable to your records"]]', 'CRA doesn''t care whether your invoice is structured XML or a scanned PDF — what matters is that it carries the required tax information and can be traced back to your books during an audit.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'The 9 required fields', '[["Identity", "Business name, GST/HST/Business Number, invoice number, date"], ["Transaction", "Description, amount"], ["Tax", "Tax breakdown, total"], ["Commercial", "Payment terms"]]', 'These fields exist for two reasons: CRA compliance, and enabling your customer''s Input Tax Credit claim. Missing the GST/HST number specifically can block your client''s ITC entirely.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'For federal government suppliers', '[["Preferred standards", "Peppol BIS format or UBL-XML"], ["Delivery", "Via SAP Ariba, or any certified Peppol network provider"]]', 'This is the one place in Canada where structured-format preferences actually exist in writing — everywhere else, content is what matters, not structure.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'No Canadian Peppol identifier', '[["CRA Business Number", "Cannot be used as a Peppol ID"], ["Workaround", "Register under GLN (scheme 0088) or DUNS (scheme 0060)"]]', 'Because Canada has no national Peppol Authority or identifier scheme, Canadian businesses wanting Peppol connectivity use an international identifier agreed bilaterally with trading partners — there''s no local accreditation step to complete.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'file_format' AND dc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 4 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Provincial tax variation', '[["Ontario", "13% HST (combined federal + provincial)"], ["Atlantic provinces (NS, NB, PE, NL)", "15% HST"], ["Quebec", "5% GST + 9.975% QST, shown as separate lines (QST calculated on subtotal only)"], ["Alberta, NWT, Nunavut, Yukon", "5% GST only — no provincial sales tax"], ["Other provinces", "5% GST plus separately administered PST, per province"]]', 'A static invoice footer that assumes a single tax rate is a real risk for any business selling across provincial lines — the correct tax treatment depends on the customer''s province of supply, not your own.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'file_format' AND dc.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Federal B2G (mandatory)', '[["Platform", "SAP Ariba, accessed via the CanadaBuys procurement portal"], ["Authority", "Public Services and Procurement Canada (PSPC)"]]', 'This is a genuine, existing, unambiguous requirement — if you sell to the Government of Canada, there''s no ambiguity about what''s expected of you.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Domestic B2B (voluntary)', '[["Common practice", "PDF email, EDI in established trade sectors"], ["Real-time reporting", "None — GST/HST runs entirely on periodic returns"]]', 'There''s no unified national network for domestic B2B — businesses use whatever their trading partner accepts, from paper through to enterprise EDI.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Peppol''s actual use case in Canada', '[["Realistic scenario", "Cross-border — EU/Australian operations invoicing Canadian subsidiaries"], ["Local accreditation needed", "None"]]', 'Be clear-eyed about this: Peppol adoption in Canada today is driven by multinational groups extending infrastructure they already run elsewhere, not by any domestic push.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 3 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Provincial & municipal fragmentation', '[["Coordinated framework", "None"], ["Example pilot", "Vancouver School Board''s digital invoicing portal"]]', 'A handful of isolated provincial or municipal digital-invoicing pilots exist, but there''s no coordinated cross-provincial framework comparable to what''s happening federally.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'scope_transmission' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'If you supply the federal government, register in SAP Ariba via CanadaBuys', 'This is the one genuinely mandatory step in the entire Canadian landscape — confirm your registration and integration are current.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'For everyone else, confirm your invoices carry all 9 CRA-required fields', 'Business name, GST/HST/Business Number, date, invoice number, description, amount, correct provincial tax breakdown, total, and payment terms.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Get your provincial tax logic right', 'Confirm your invoicing system applies the correct tax treatment based on the customer''s province of supply — Ontario HST, Quebec''s separate GST/QST lines, or Alberta''s GST-only rule all require different logic.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Choose a Peppol identifier only if you actually need cross-border connectivity', 'If a European or Australian counterparty requests Peppol connectivity, register under a GLN or DUNS identifier through any standard Access Point — there''s no domestic requirement driving this decision.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Set up 6-year record retention', 'Keep invoices and supporting documents for at least six years from the end of the relevant tax year — CRA can request them well after the fact during an audit or review.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Watch CRA''s regulatory plan cycle, not a fixed deadline', 'There''s no countdown to plan around — instead, periodically check CRA''s published regulatory plans for any future signal that a domestic e-invoicing mandate is moving from study to proposal.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'Canada' AND ds.sort_order = 5;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '💰 No penalties, no format law', NULL, NULL, 'Provincial sales taxes and GST/HST rules don''t specify invoice format at all — there are no Canadian penalties tied to using paper versus digital invoicing under sales tax law.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🤔 CRA''s own stakeholders flagged the chicken-and-egg problem', NULL, NULL, 'The 2021 study surfaced a genuinely honest business concern: adopting e-invoicing feels pointless if the businesses you work with haven''t — a real illustration of why voluntary network-effect-dependent systems can stall without a regulatory push.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '📈 Adoption is happening anyway, gradually', NULL, NULL, 'Small-business payment data suggests average late-payment periods in Canada have been improving quarter over quarter, partly attributed to gradual e-invoicing adoption — change is happening organically, just without a mandate forcing it.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 3 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🌍 The pressure, when it comes, will be external', NULL, NULL, 'As Europe''s mandates phase in through 2026–2030 and Singapore''s requirement reaches full GST-registered coverage by 2031, Canadian exporters trading with those markets will feel the pull toward e-invoicing infrastructure long before any domestic law requires it.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'Canada' AND dc.section = 'penalties_related' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.canada.ca/en/public-services-procurement/services/acquisitions/support-for-businesses/electronic-procurement-transition.html', 0 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'Canada.ca — Electronic procurement (PSPC)' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'Canada' AND dp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.canada.ca/en/revenue-agency.html', 1 FROM countries WHERE name_en = 'Canada';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'Canada Revenue Agency' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'Canada' AND dp.sort_order = 1;
