-- European Union deep-dive content: page, stats, file_format cards, scope_transmission
-- cards, steps, penalties_related cards, 2 portals. No lifecycle card (this is a
-- policy-framework overview, not a single national clearance flow) and no penalty rows
-- (ViDA sets the framework; fines remain a national competence).
-- Authored fresh (no legacy static page existed for the EU) from the official EC ViDA
-- page and CEN's EN 16931-1:2026 announcement, both verified via live research.

INSERT OR IGNORE INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-01' FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Phased EU-wide framework — ViDA (2025–2035)', 'This deep-dive page reflects the official European Commission ViDA guidance and CEN''s EN 16931-1:2026 standard as of August 2026, and is provided for general awareness, not legal or tax advice. ViDA sets an EU-wide framework — it does not replace or override any single member state''s own domestic e-invoicing mandate. Check the tracker''s individual country pages for what''s actually mandatory where you invoice today, and confirm current developments directly with the European Commission''s Taxation and Customs Union before making infrastructure decisions.', 'ViDA isn''t a single deadline — it''s three pillars phasing in on three different schedules between 2025 and 2035, layered on top of whatever domestic mandate your own member state already runs.', 'ViDA standardises the data model, not a single national transmission network — EN 16931 defines what a compliant e-invoice must contain, not how every member state must deliver it.', 'This page covers the EU-wide ViDA framework itself, not any single country''s domestic mandate. ViDA is built on three pillars running on different timelines: real-time Digital Reporting Requirements for cross-border B2B trade (from 2030), updated VAT rules for the platform economy (from 2028), and a Single VAT Registration model extending the existing One Stop Shop (phased from 2027). Check the tracker''s individual country pages — Italy, Belgium, Poland, and others — for what''s actually mandatory in the market where you invoice today.', 'What to actually do depends on which pillar affects you, and when — a short-term rental platform preparing for 2028 has a different checklist from a cross-border B2B trader preparing for 2030.', 'ViDA itself doesn''t set a fine schedule — enforcement remains a national competence, so penalties for non-compliance will look like whatever your own member state already applies (or introduces) for its own domestic mandate.' FROM countries WHERE name_en = 'European Union';

INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '3', 'ViDA pillars: DRR, platform economy, single VAT registration' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '€11B/yr', 'Projected VAT fraud reduction from real-time digital reporting' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '€4.1B/yr', 'Projected compliance-cost savings for EU traders' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '1 Jul 2030', 'Cross-border DRR + mandatory EN 16931 e-invoicing go live' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '1 Jan 2035', 'Deadline for pre-2024 domestic systems to align with the EU model' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'EN 16931 — the semantic backbone', '[["Original standard", "Adopted under Directive 2014/55/EU, focused on B2G e-invoicing"], ["2026 revision", "EN 16931-1:2026, approved by CEN 13 Feb 2026, published 18 Mar 2026"]]', 'EN 16931 defines a common semantic data model for the core elements of an e-invoice — a shared vocabulary, not a single file format — ensuring interoperability across all EU member states.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'The 2026 revision, in detail', '[["New fields", "IBAN, triangulation indicators, corrective invoice sequencing, margin-scheme support"], ["Purpose", "Future-proof the B2G-era standard for complex B2B and cross-border ViDA scenarios"]]', 'This revision is what makes EN 16931 fit for purpose ahead of 2030 — the original standard was written for B2G use cases and needed real expansion to carry EU-wide B2B Digital Reporting Requirements traffic.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Format vs. mandate — two different things', '[["What ViDA defines", "The EN 16931 data model that a compliant e-invoice must satisfy"], ["What ViDA doesn''t define", "A single EU-wide transmission network or clearance model"]]', 'Don''t confuse the two: ViDA sets the destination data standard, but leaves it to each member state (or business relationship) to choose the transmission channel — Peppol, a domestic platform, or a direct exchange.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Structured means machine-readable, not any specific syntax', '[["Compliant syntaxes", "UBL and CII are the two base syntaxes EN 16931 formally supports"], ["Common implementation", "Peppol BIS Billing 3.0, the most widely adopted EN 16931-conformant profile across the EU"]]', '"EN 16931-compliant" is a semantic-content requirement, not a single named file format — most EU businesses meet it today via Peppol BIS Billing 3.0, but any UBL or CII implementation of the same data model qualifies.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'file_format' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Three pillars, three timelines', '[["Digital Reporting Requirements (DRR)", "Cross-border B2B e-invoicing + near-real-time reporting from 1 Jul 2030"], ["Platform economy", "Deemed-supplier VAT rules for short-term rental & road transport from 1 Jul 2028"], ["Single VAT Registration (SVR)", "Expanded OSS/IOSS scope, phased from 1 Jan 2027"]]', 'These three pillars were adopted together as a single package on 11 March 2025, but they take effect on genuinely different dates — treat them as three separate compliance projects, not one.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Domestic mandates today vs. the 2030 cross-border layer', '[["Domestic", "Several member states (Italy, Belgium, Poland, France, and others) already run — or are introducing — their own binding domestic B2B mandates, under derogations available since ViDA''s April 2025 entry into force"], ["Cross-border", "ViDA''s own EU-wide Digital Reporting Requirements apply specifically to cross-border intra-EU B2B transactions from July 2030, as a separate layer"]]', 'A business can already be legally required to e-invoice domestically today in one member state, while the EU-wide cross-border layer for the same business''s intra-EU trade doesn''t arrive until 2030 — both are real, and they run on different clocks.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'The 2035 convergence', '[["Who''s affected", "Member states with a domestic real-time transaction reporting system already in place before 1 January 2024 (e.g. Italy''s SDI)"], ["What changes", "Those pre-existing domestic systems must align with the harmonised EU ViDA standard and model by 1 January 2035"]]', 'This is the finish line for the whole ViDA package — by 2035, even the oldest and most established national clearance systems in the EU must converge on the same EN 16931-based standard as everyone else.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Map every member state where you have VAT obligations', 'List each EU country where you''re VAT-registered or trading, and track that country''s own domestic e-invoicing/derogation timeline separately from the EU-wide ViDA dates below — many are already ahead of 2030.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Confirm your ERP/AP systems can produce EN 16931-1:2026-conformant e-invoices', 'This means covering the 2026 revision''s expanded field set — IBAN, triangulation indicators, corrective invoice sequencing, and margin-scheme support — not just the original B2G-era standard.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'If you trade cross-border B2B within the EU, prepare for the 2030 DRR layer', 'Build toward issuing EN 16931-compliant e-invoices within 10 days of the chargeable event and reporting near-real-time, ahead of the 1 July 2030 go-live for intra-EU B2B transactions.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'If you run a qualifying platform or supply into states where you''re not registered, review the 2028 changes', 'Short-term accommodation rental and road passenger transport platforms take on deemed-supplier VAT obligations from 1 July 2028; non-established, non-VAT-registered suppliers may also become subject to a new mandatory reverse charge.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'If you already operate under a domestic clearance system, track its alignment plan', 'Businesses in countries with pre-2024 domestic real-time reporting (such as Italy''s SDI) should watch their own tax authority''s plan to converge with the harmonised EU ViDA standard ahead of the 1 January 2035 deadline.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Don''t wait for 2030 as your only planning date', 'Several member states already have — or are actively introducing — their own binding domestic mandates well ahead of the EU-wide cross-border layer. Check this tracker''s individual country pages, not just this EU-level summary.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'European Union' AND ds.sort_order = 5;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '💶 Fraud reduction is the headline economic case', NULL, NULL, 'The European Commission estimates real-time digital reporting could reduce VAT fraud by up to €11 billion a year, while cutting administrative and compliance costs for EU traders by more than €4.1 billion a year over the following decade — the core justification for the whole package.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '⚖️ ViDA sets the framework, not the fines', NULL, NULL, 'ViDA itself creates no EU-wide penalty schedule for non-compliance — enforcement and fines remain a national competence, so expect penalty structures shaped like whatever your own member state already runs for its domestic mandate (see that country''s own tracker page).', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🧩 A 27-member-state patchwork, by design', NULL, NULL, 'ViDA''s phased pillars deliberately coexist with member states'' own domestic mandates rather than replacing them outright — the framework converges everyone onto the same standard eventually (by 2035), but the path there runs through 27 different national timelines.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'penalties_related' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 3 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🔜 The direction of travel is set even where the date isn''t', NULL, NULL, 'Even in member states without a finalised domestic mandate yet, ViDA locks in the EN 16931 destination format across the whole bloc — the open question for most businesses isn''t whether structured e-invoicing is coming, but which year their own country lands on.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'European Union' AND dc.section = 'penalties_related' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://taxation-customs.ec.europa.eu/taxation/vat/vat-digital-age-vida_en', 0 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'EU Taxation & Customs Union — ViDA' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'European Union' AND dp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://vat-one-stop-shop.ec.europa.eu/index_en', 1 FROM countries WHERE name_en = 'European Union';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'VAT e-Commerce — One Stop Shop' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'European Union' AND dp.sort_order = 1;
