-- Italy milestone translations (ES/DE/FR)
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-b2g-2014', 'es', 'Fase 0 — FatturaPA obligatoria para B2G a través de SDI', 'Italia es pionera en facturación electrónica para proveedores del gobierno, estableciendo la infraestructura técnica, el formato XML y el modelo de compensación que más tarde se extendería a toda la economía doméstica.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-sdi', 'es', 'Facturación electrónica B2B/B2C obligatoria vía SDI (en vigor desde 2019)', 'Italia fue el primer Estado miembro de la UE en exigir la facturación electrónica con modelo de compensación para prácticamente todas las transacciones domésticas — B2B, B2C y B2G — a través del Sistema di Interscambio (SDI), utilizando el formato XML FatturaPA.', '["Confirme que su generación de FatturaPA y su canal de transmisión al SDI (PEC, FTP o servicio web) siguen activos", "Vigile los cambios de alineación con EN 16931/ViDA antes de la renovación de la excepción del SDI de Italia (hasta 2027) y el plazo de armonización de la UE de 2035"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-v191-published', 'es', 'Se publica FatturaPA v1.9.1', 'La Agenzia delle Entrate emite una especificación técnica actualizada: listas de códigos revisadas, controles de validación más estrictos y definiciones de campos actualizadas.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-v191-mandatory', 'es', 'El cumplimiento de v1.9.1 se vuelve obligatorio', 'A partir de esta fecha, el SDI rechaza cualquier factura que no cumpla con la nueva especificación — un hito de cumplimiento firme, no un objetivo flexible, dado el modelo de validación de tolerancia cero del SDI.', '["Valide específicamente contra FatturaPA v1.9.1 — cualquier cosa que aún apunte a una versión anterior será rechazada de plano"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-b2g-2014', 'de', 'Phase 0 — FatturaPA für B2G über SDI verpflichtend', 'Italien ist Vorreiter bei der E-Rechnungsstellung für Lieferanten der öffentlichen Hand und schafft die technische Infrastruktur, das XML-Format und das Clearing-Modell, das später auf die gesamte inländische Wirtschaft ausgeweitet wird.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-sdi', 'de', 'Verpflichtendes B2B-/B2C-E-Invoicing über SDI (in Kraft seit 2019)', 'Italien war der erste EU-Mitgliedstaat, der ein Clearing-Modell für die E-Rechnungsstellung für praktisch alle inländischen Transaktionen — B2B, B2C und B2G — über das Sistema di Interscambio (SDI) mit dem FatturaPA-XML-Format vorschrieb.', '["Stellen Sie sicher, dass Ihre FatturaPA-Erstellung und Ihr SDI-Übertragungskanal (PEC, FTP oder Webdienst) weiterhin aktiv sind", "Beobachten Sie EN-16931-/ViDA-Angleichungsänderungen im Vorfeld der Erneuerung von Italiens SDI-Ausnahme (bis 2027) und der EU-weiten Harmonisierungsfrist 2035"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-v191-published', 'de', 'FatturaPA v1.9.1 veröffentlicht', 'Die Agenzia delle Entrate gibt eine aktualisierte technische Spezifikation heraus: überarbeitete Codelisten, strengere Validierungskontrollen und aktualisierte Felddefinitionen.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-v191-mandatory', 'de', 'Die Einhaltung von v1.9.1 wird verpflichtend', 'Ab diesem Datum weist der SDI jede Rechnung zurück, die nicht der neuen Spezifikation entspricht — angesichts des Null-Toleranz-Validierungsmodells des SDI ein fester Compliance-Meilenstein, kein weiches Ziel.', '["Validieren Sie speziell gegen FatturaPA v1.9.1 — alles, was noch auf eine ältere Version abzielt, wird rundweg zurückgewiesen"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-b2g-2014', 'fr', 'Phase 0 — FatturaPA obligatoire pour le B2G via SDI', 'L''Italie est pionnière en matière de facturation électronique pour les fournisseurs de l''État, mettant en place l''infrastructure technique, le format XML et le modèle de contrôle qui s''étendront plus tard à l''ensemble de l''économie domestique.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-sdi', 'fr', 'Facturation électronique B2B/B2C obligatoire via SDI (en vigueur depuis 2019)', 'L''Italie a été le premier État membre de l''UE à rendre obligatoire la facturation électronique selon un modèle de contrôle pour la quasi-totalité des transactions domestiques — B2B, B2C et B2G — via le Sistema di Interscambio (SDI), en utilisant le format XML FatturaPA.', '["Vérifiez que votre génération de FatturaPA et votre canal de transmission au SDI (PEC, FTP ou service web) restent actifs", "Surveillez les évolutions d''alignement EN 16931/ViDA avant le renouvellement de la dérogation SDI de l''Italie (jusqu''en 2027) et l''échéance d''harmonisation de l''UE de 2035"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-v191-published', 'fr', 'Publication de FatturaPA v1.9.1', 'L''Agenzia delle Entrate publie une spécification technique mise à jour : listes de codes révisées, contrôles de validation renforcés et définitions de champs actualisées.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('it-v191-mandatory', 'fr', 'La conformité à la version v1.9.1 devient obligatoire', 'À partir de cette date, le SDI rejette toute facture non conforme à la nouvelle spécification — une échéance de conformité ferme, et non un objectif indicatif, compte tenu du modèle de validation à tolérance zéro du SDI.', '["Validez spécifiquement par rapport à FatturaPA v1.9.1 — tout ce qui vise encore une version antérieure sera purement et simplement rejeté"]');
