-- Saudi Arabia milestone translations (ES/DE/FR)
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-phase1', 'es', 'Comienza la Fase 1 (Fase de Generación)', 'Todos los contribuyentes registrados a efectos del IVA deben generar facturas electrónicas mediante un sistema electrónico conforme y almacenarlas digitalmente — en esta etapa aún no se requiere integración en vivo con ZATCA.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-phase2-wave1', 'es', 'Comienza la Fase 2 (Fase de Integración) — Ola 1', 'Los mayores contribuyentes (ingresos anuales superiores a SAR 3.000 millones) deben integrar directamente sus sistemas de facturación con la plataforma Fatoora de ZATCA. Cada ola posterior incorpora empresas más pequeñas, cada una notificada con al menos 6 meses de antelación.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-wave23', 'es', 'ZATCA Fatoora — Ola 23 (facturación > SAR 750.000)', 'Las empresas con facturación sujeta a IVA superior a SAR 750.000 en 2022, 2023 o 2024 debían completar la integración de la Fase 2 con la plataforma Fatoora para la compensación en tiempo real.', '["Confirme el plazo de notificación e integración directa de ZATCA para su entidad", "Integre su sistema de facturación con la API de Fatoora para la compensación en tiempo real B2B/B2G", "Asegúrese de que las facturas incluyan UUID, código QR y sello criptográfico"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-wave24', 'es', 'ZATCA Fatoora — Ola 24 (facturación > SAR 375.000)', 'El umbral bajó a SAR 375.000 — igualando efectivamente el umbral de registro obligatorio de IVA, incorporando a casi todas las empresas registradas a efectos del IVA a la compensación de la Fase 2.', '["Asuma que está dentro del alcance si está registrado a efectos del IVA; ZATCA notifica a los contribuyentes afectados con aproximadamente seis meses de antelación", "Emita facturas estándar (compensación, IVA soportado deducible) para B2B/B2G y facturas simplificadas para B2C, reportadas dentro de las 24 horas"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-phase1', 'de', 'Phase 1 (Generierungsphase) beginnt', 'Alle umsatzsteuerlich registrierten Steuerpflichtigen müssen E-Rechnungen mit einem konformen elektronischen System erstellen und digital speichern — in dieser Phase ist noch keine Live-Integration mit ZATCA erforderlich.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-phase2-wave1', 'de', 'Phase 2 (Integrationsphase) beginnt — Welle 1', 'Die größten Steuerpflichtigen (Jahresumsatz über SAR 3 Milliarden) müssen ihre Abrechnungssysteme direkt mit der Fatoora-Plattform von ZATCA integrieren. Jede weitere Welle bringt kleinere Unternehmen in den Anwendungsbereich, jeweils mit mindestens 6 Monaten Vorlauf benachrichtigt.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-wave23', 'de', 'ZATCA Fatoora — Welle 23 (Umsatz > SAR 750.000)', 'Unternehmen mit umsatzsteuerpflichtigem Umsatz über SAR 750.000 in den Jahren 2022, 2023 oder 2024 mussten die Phase-2-Integration mit der Fatoora-Plattform für die Echtzeit-Freigabe abschließen.', '["Bestätigen Sie die direkte Benachrichtigungs- und Integrationsfrist von ZATCA für Ihr Unternehmen", "Integrieren Sie Ihr Rechnungssystem mit der Fatoora-API für die Echtzeit-B2B-/B2G-Freigabe", "Stellen Sie sicher, dass Rechnungen eine UUID, einen QR-Code und einen kryptografischen Stempel tragen"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-wave24', 'de', 'ZATCA Fatoora — Welle 24 (Umsatz > SAR 375.000)', 'Die Schwelle sank auf SAR 375.000 — was effektiv der verpflichtenden Umsatzsteuer-Registrierungsschwelle entspricht und nahezu jedes umsatzsteuerlich registrierte Unternehmen in die Phase-2-Freigabe einbezieht.', '["Gehen Sie davon aus, im Anwendungsbereich zu sein, wenn Sie umsatzsteuerlich registriert sind; ZATCA benachrichtigt betroffene Steuerpflichtige rund sechs Monate im Voraus", "Stellen Sie Standardrechnungen (Freigabe, anrechenbare Vorsteuer) für B2B/B2G und vereinfachte Rechnungen für B2C aus, gemeldet innerhalb von 24 Stunden"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-phase1', 'fr', 'La phase 1 (phase de génération) débute', 'Tous les assujettis immatriculés à la TVA doivent générer des factures électroniques au moyen d''un système électronique conforme et les stocker numériquement — aucune intégration en direct avec ZATCA n''est encore requise à ce stade.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-phase2-wave1', 'fr', 'La phase 2 (phase d''intégration) débute — Vague 1', 'Les plus grands contribuables (chiffre d''affaires annuel supérieur à 3 milliards de SAR) doivent intégrer directement leurs systèmes de facturation à la plateforme Fatoora de ZATCA. Chaque vague suivante fait entrer des entreprises plus petites dans le champ d''application, chacune notifiée au moins 6 mois à l''avance.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-wave23', 'fr', 'ZATCA Fatoora — Vague 23 (chiffre d''affaires > 750 000 SAR)', 'Les entreprises dont le chiffre d''affaires assujetti à la TVA dépassait 750 000 SAR en 2022, 2023 ou 2024 devaient achever l''intégration de phase 2 avec la plateforme Fatoora pour le contrôle en temps réel.', '["Confirmez l''échéance de notification et d''intégration directe de ZATCA pour votre entité", "Intégrez votre système de facturation à l''API Fatoora pour le contrôle B2B/B2G en temps réel", "Assurez-vous que les factures comportent un UUID, un code QR et un cachet cryptographique"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('sa-wave24', 'fr', 'ZATCA Fatoora — Vague 24 (chiffre d''affaires > 375 000 SAR)', 'Le seuil est descendu à 375 000 SAR — correspondant effectivement au seuil d''immatriculation obligatoire à la TVA, faisant entrer presque toutes les entreprises immatriculées à la TVA dans le contrôle de phase 2.', '["Considérez que vous êtes concerné si vous êtes immatriculé à la TVA ; ZATCA notifie les contribuables concernés environ six mois à l''avance", "Émettez des factures standard (contrôle, TVA déductible) pour le B2B/B2G et des factures simplifiées pour le B2C, déclarées dans les 24 heures"]');
