-- United Arab Emirates milestones (Stage 4 deep-dive/tracker migration)
-- 8 total, matching the static page's 8 timeline rcards.
-- 4 deep-dive-only (dict consultation, ministerial decisions, first ASPs, penalty
-- framework) + 4 tracker-matched (uae-pilot, uae-asp, uae-phase1, uae-phase2), all
-- exact date/topic matches -- tracker phrasing wins for all 4. None of the tracker's
-- own uae-* DATA entries set anchor:true, so all keep anchor=0.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-dict-consult', id, '2025-02-01', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-dict-consult', 'en', 'PINT AE Data Dictionary released for public consultation', 'The UAE''s localised Peppol PINT specification is opened for stakeholder feedback, with updated versions following as input is integrated.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-ministerial-decisions', id, '2025-06-01', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-ministerial-decisions', 'en', 'Ministerial Decisions No. 243 and 244 of 2025 issued', 'The Ministry of Finance formally adopts PINT AE as the UAE Data Dictionary and sets out the Electronic Invoicing System and its implementation, under the authority of Federal Decree-Law No. 8 of 2017 on VAT.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-first-asps', id, '2025-08-01', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-first-asps', 'en', 'First Accredited Service Providers (ASPs) published', 'The MoF publishes its first list of accredited service providers, expanding progressively as more providers complete accreditation.', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-penalty-framework', id, '2025-12-01', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-penalty-framework', 'en', 'Cabinet Decision No. 106 of 2025 sets the penalty framework', 'Six specific e-invoicing violation categories are defined with fixed penalties, alongside Cabinet Decision No. 129 of 2025, which separately revises penalties across the broader UAE tax framework — creating potential "dual penalty exposure."', '[]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-pilot', id, '2026-07-01', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-pilot', 'en', 'Voluntary e-invoicing pilot phase begins', 'Voluntary participation opened ahead of the mandate, letting businesses test Accredited Service Provider (ASP) connectivity and the PINT AE invoice format risk-free before penalties apply.', '["Consider joining the voluntary pilot to resolve ASP integration issues before the mandatory phase", "Monitor Federal Tax Authority (FTA) technical guidance updates"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-asp', id, '2026-10-30', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-asp', 'en', 'ASP appointment deadline — businesses ≥ AED 50 million revenue', 'Businesses with revenue of AED 50 million or more must have appointed an Accredited Service Provider (ASP) ahead of the January 2027 go-live (deadline extended from 31 July 2026).', '["Select and contract an FTA-accredited Accredited Service Provider", "Begin PINT AE (UBL 2.1) integration testing with your ASP"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-phase1', id, '2027-01-01', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-phase1', 'en', 'Phase 1 mandatory go-live — revenue ≥ AED 50 million', 'Structured e-invoicing becomes mandatory for large businesses, transmitted through an ASP over the Peppol network in PINT AE format, with a real-time copy reported to the FTA.', '["Complete ASP integration and end-to-end testing before go-live", "Ensure invoices carry all FTA-mandated data fields — PDFs and paper no longer qualify"]');
INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url) SELECT 'uae-phase2', id, '2027-07-01', 0, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('uae-phase2', 'en', 'Mandate extends to all other VAT-registered businesses', 'The e-invoicing mandate broadens to cover all remaining VAT-registered businesses for B2B/B2G transactions, with G2B/B2G-specific obligations following from October 2027.', '["Confirm VAT registration status and appoint an ASP well ahead of this date", "Intra-group transactions within a single UAE VAT group have an extended transition to 1 January 2029"]');
