-- United Arab Emirates deep-dive content: page, stats, 4 file_format cards,
-- 3 scope_transmission cards + 1 lifecycle card ('The five corners', a genuine
-- sequential DCTCE flow -- unlike Saudi Arabia's QR-code tag list, this one is a real
-- process, and sits in scope_transmission per the usual pattern), 6 steps, a genuine
-- 6-row tabular penalty schedule + 3 narrative penalties_related cards (both at once,
-- per Belgium/Italy/Saudi precedent), 1 portal.

INSERT OR IGNORE INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-07-21' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro) SELECT id, 'en', 'Decentralised 5-corner (DCTCE)', 'This deep-dive page reflects publicly available technical guidance as of July 2026 and is provided for general awareness, not legal or tax advice. PINT AE technical specifications, the ASP accreditation register, and penalty enforcement continue to evolve — confirm current requirements directly with the UAE Ministry of Finance or Federal Tax Authority before building an integration.', 'The UAE built its e-invoicing framework unusually methodically — data dictionary consultation, then legislation, then ASP accreditation, then a voluntary pilot, all before the mandate itself begins.', 'PINT AE is a genuinely large specification — over 135 data elements, layered deliberately to balance global Peppol interoperability with UAE-specific VAT rules.', 'The UAE''s "5-corner" DCTCE model bundles Peppol-style exchange with automatic tax reporting — there''s no separate VAT filing step for e-invoiced transactions.', 'Don''t assume your ASP alone handles everything — internal IT and finance alignment is explicitly called out as a common gap.', 'Cabinet Decision No. 106 of 2025 defines six specific violation categories — some capped monthly, others accumulating daily without limit.' FROM countries WHERE name_en = 'United Arab Emirates';

INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'PINT AE', 'UBL-based data dictionary' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '5-corner', 'DCTCE model' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '135+', 'Data elements defined' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', 'AED 100–5k', 'Per-violation / monthly cap' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT ds.id, 'en', '2 yrs', 'ASP accreditation term' FROM deep_dive_stats ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'What PINT AE is', '[["Full meaning", "Peppol International (UAE)"], ["Base standard", "UBL, aligned with global Peppol PINT"], ["Legal adoption", "Ministerial Decision No. 243 of 2025"]]', 'PINT AE is a localised extension, not a wholly separate schema — businesses already familiar with Peppol PINT elsewhere have a genuine head start.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Three content layers', '[["Shared Core Content", "Universal Peppol PINT elements (IDs, dates, parties, totals)"], ["Aligned Content", "Internationally standardised fields mapped to UAE classifications (VAT categories, tax logic, payment)"], ["UAE Extension", "UAE-specific fields beyond the global baseline"]]', 'This layered design is exactly what preserves baseline interoperability across the global Peppol network while still enforcing UAE-specific VAT rules.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'file_format' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Field count & scope', '[["Total elements", "135+ (mandatory, conditional, optional)"], ["Standard tax invoice", "~50–51 mandatory fields"], ["Supported scenarios", "Standard, zero-rated, reverse charge, free zone supplies"]]', 'Missing or incorrectly formatted mandatory fields cause outright rejection with no manual override — there''s no partial acceptance or manual correction step at the ASP layer.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'file_format' AND dc.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'Key identifiers & content', '[["UUID", "Unique per invoice document"], ["Line-level", "VAT rate and amount per line item"], ["Currency", "Total invoice amount in AED"], ["Security", "Digital signature (applied by the ASP) + QR code"]]', 'PDFs, scanned documents, and paper invoices are explicitly not valid under the mandate — only structured XML/JSON generated to PINT AE counts.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'file_format' AND dc.sort_order = 3;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'What your ASP actually does', '[["Validation", "Checks XML against the PINT AE schema"], ["Conversion", "Converts invoicing data to compliant PINT AE XML"], ["Security", "Applies digital signature and QR code"], ["Transmission", "Sends over the Peppol network to the buyer''s ASP"]]', 'Your ERP only needs to generate the underlying invoice data — the ASP handles conversion, signing, and delivery, but that division of labour means choosing the right ASP genuinely matters.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'ASP accreditation process', '[["1. Application", "Submitted via the MoF portal"], ["2–3. Testing", "Pre-approval interoperability checks, then production end-to-end testing"], ["4. Certification", "ISO certificate, insurance, and compliance verification"], ["5. Credential", "Peppol PKI certificate issuance"], ["6. Accreditation", "Granted for 2 years, renewable"]]', 'Always verify a provider''s accreditation against the MoF''s official public register directly — don''t rely on a provider''s own marketing claim of accreditation.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', 'No direct FTA portal upload', '[["Model", "Decentralised — invoices flow via Peppol/ASP, never directly to a government portal"]]', 'This is the defining contrast with Saudi Arabia next door: there''s no government clearance portal to upload to — everything routes through your accredited service provider.', NULL, NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'scope_transmission' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 3, 'pills' FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) SELECT lc.id, 'en', 'The five corners', 'Every invoice passes through all five in sequence:', 'Corner 5 (the FTA) receives a Tax Data Document (TDD) report from both ASPs automatically — tax data flows to the authority with every invoice exchanged, with no separate VAT reporting step required.' FROM deep_dive_lifecycle_cards lc JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order) SELECT lc.id, 0 FROM deep_dive_lifecycle_cards lc JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT ls.id, 'en', 'Supplier' FROM deep_dive_lifecycle_statuses_v2 ls JOIN deep_dive_lifecycle_cards lc ON lc.id = ls.card_id JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3 AND ls.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order) SELECT lc.id, 1 FROM deep_dive_lifecycle_cards lc JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT ls.id, 'en', 'Supplier''s ASP' FROM deep_dive_lifecycle_statuses_v2 ls JOIN deep_dive_lifecycle_cards lc ON lc.id = ls.card_id JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3 AND ls.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order) SELECT lc.id, 2 FROM deep_dive_lifecycle_cards lc JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT ls.id, 'en', 'Buyer''s ASP' FROM deep_dive_lifecycle_statuses_v2 ls JOIN deep_dive_lifecycle_cards lc ON lc.id = ls.card_id JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3 AND ls.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order) SELECT lc.id, 3 FROM deep_dive_lifecycle_cards lc JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT ls.id, 'en', 'Buyer' FROM deep_dive_lifecycle_statuses_v2 ls JOIN deep_dive_lifecycle_cards lc ON lc.id = ls.card_id JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3 AND ls.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order) SELECT lc.id, 4 FROM deep_dive_lifecycle_cards lc JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) SELECT ls.id, 'en', 'FTA' FROM deep_dive_lifecycle_statuses_v2 ls JOIN deep_dive_lifecycle_cards lc ON lc.id = ls.card_id JOIN countries co ON co.id = lc.country_id WHERE co.name_en = 'United Arab Emirates' AND lc.section = 'scope_transmission' AND lc.sort_order = 3 AND ls.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Identify and verify an accredited ASP', 'Check the MoF''s official public register directly to confirm Peppol connectivity and current accreditation status before signing anything.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Prioritise ERP integration and data mapping', 'Map your invoicing data to PINT AE / UBL structures — this is foundational work that needs to happen regardless of which ASP you choose.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Design a stable API integration with your ASP', 'Build a resilient connection to the UAE e-invoicing rails rather than a fragile point solution — this is infrastructure you''ll depend on continuously, not a one-time filing.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Test early, in stages', 'Develop structured test cases covering invoices, credit notes, cancellations, and unusual VAT scenarios (reverse charge, free zone supplies) — don''t wait for a finished product to start testing.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Establish internal governance', 'Define master data ownership, exception workflow procedures, archiving policy, and compliance monitoring — these are organisational decisions your ASP can''t make for you.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT ds.id, 'en', 'Meet the ASP appointment deadline with margin', 'Large businesses: appoint well ahead of 30 October 2026. Late or emergency ASP onboarding carries a real cost premium beyond the standard implementation rate.' FROM deep_dive_steps ds JOIN countries co ON co.id = ds.country_id WHERE co.name_en = 'United Arab Emirates' AND ds.sort_order = 5;

INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT pr.id, 'en', 'Failure to implement system / appoint ASP on time', 'AED 5,000 per month (accumulating)', NULL FROM deep_dive_penalty_rows pr JOIN countries co ON co.id = pr.country_id WHERE co.name_en = 'United Arab Emirates' AND pr.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT pr.id, 'en', 'Failure to issue/transmit an e-invoice on time', 'AED 100 per invoice, capped at AED 5,000/month', NULL FROM deep_dive_penalty_rows pr JOIN countries co ON co.id = pr.country_id WHERE co.name_en = 'United Arab Emirates' AND pr.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT pr.id, 'en', 'Failure to issue/transmit an e-credit note on time', 'AED 100 per note, capped at AED 5,000/month', NULL FROM deep_dive_penalty_rows pr JOIN countries co ON co.id = pr.country_id WHERE co.name_en = 'United Arab Emirates' AND pr.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT pr.id, 'en', 'Issuer fails to notify FTA of system failure', 'AED 1,000 per day (uncapped, accumulating)', NULL FROM deep_dive_penalty_rows pr JOIN countries co ON co.id = pr.country_id WHERE co.name_en = 'United Arab Emirates' AND pr.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT pr.id, 'en', 'Recipient fails to notify FTA of system failure', 'AED 1,000 per day (uncapped, accumulating)', NULL FROM deep_dive_penalty_rows pr JOIN countries co ON co.id = pr.country_id WHERE co.name_en = 'United Arab Emirates' AND pr.sort_order = 4;
INSERT OR IGNORE INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) SELECT pr.id, 'en', 'Failure to notify ASP of data changes', 'AED 1,000 per day (uncapped, accumulating)', NULL FROM deep_dive_penalty_rows pr JOIN countries co ON co.id = pr.country_id WHERE co.name_en = 'United Arab Emirates' AND pr.sort_order = 5;

INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '🕊️ Voluntary participants exempt', NULL, NULL, 'Businesses using the system voluntarily during the pilot phase are not subject to these penalties until they become mandatorily subject to e-invoicing — a genuine risk-free window to test.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '⚠️ Dual penalty exposure', NULL, NULL, 'E-invoicing failures can also trigger broader tax violation penalties under Cabinet Decision No. 129 of 2025 — for example, invoice data gaps leading to inaccurate VAT return figures carry their own separate percentage-based penalties on top of the CD 106 fines.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body, badge_label, badge_type) SELECT dc.id, 'en', '📦 Retention periods', NULL, NULL, 'Five years for VAT purposes generally; five years from the end of the calendar year for non-VAT-registered businesses; seven years specifically for real estate records. Failure to retain data in a retrievable, FTA-accessible format carries its own separate penalty under the Tax Procedures Law.', NULL, NULL FROM deep_dive_cards dc JOIN countries co ON co.id = dc.country_id WHERE co.name_en = 'United Arab Emirates' AND dc.section = 'penalties_related' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://mof.gov.ae/en/about-ministry/mof-initiatives/einvoicing/', 0 FROM countries WHERE name_en = 'United Arab Emirates';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT dp.id, 'en', 'UAE Ministry of Finance — eInvoicing' FROM deep_dive_portals dp JOIN countries co ON co.id = dp.country_id WHERE co.name_en = 'United Arab Emirates' AND dp.sort_order = 0;
