-- Populates the new top-of-page mandate-summary tile (mandate_summary +
-- mandate_summary_icon) for all 31 countries, English only. Also restores
-- scope_intro to its original, section-03-only meaning for the 6 countries whose
-- static page had a genuine standalone .status-banner that got folded into
-- scope_intro during Stage 4 migration (Spain, UK, Ireland, US, Canada, Sweden) --
-- that original banner text is now split back out into mandate_summary instead.

-- Six countries with an original static-page status-banner
UPDATE deep_dive_page_translations SET mandate_summary = 'Spain runs two separate, complementary reforms that are easy to conflate: VeriFactu secures the invoicing software itself, with confirmed dates in January and July 2027, while Crea y Crece mandates structured B2B invoice exchange. Crea y Crece''s framework law has passed, but the implementing ministerial order — and therefore the exact start dates — remains pending as of mid-2026.', mandate_summary_icon = '🧩' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Spain');
UPDATE deep_dive_page_translations SET scope_intro = 'Spain runs three parallel systems that don''t all talk to each other the same way — knowing which one applies to you matters as much as the technical detail.' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Spain');
UPDATE deep_dive_page_translations SET mandate_summary = 'The UK mandate''s direction is confirmed — Peppol, 4-corner, no real-time reporting, targeting April 2029 — but the detailed technical standards, exact scope, and any phasing are not yet published. HMRC has committed to a full implementation roadmap at Budget 2026 (November). Sections below are marked Confirmed or Pending Budget 2026 accordingly.', mandate_summary_icon = '🚧' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United Kingdom');
UPDATE deep_dive_page_translations SET scope_intro = 'The UK has deliberately chosen the opposite end of the spectrum from Poland or France — no clearance authority, and explicitly no live transaction feed to HMRC at launch.' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United Kingdom');
UPDATE deep_dive_page_translations SET mandate_summary = 'Ireland''s phased timeline and reporting model are firmly confirmed by Revenue, including who''s in Phase 1. The detailed technical specification — exact schema profile, API detail — is still being finalised alongside the Irish Peppol Authority. Sections below are marked Confirmed or Pending technical spec accordingly.', mandate_summary_icon = '📋' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Ireland');
UPDATE deep_dive_page_translations SET scope_intro = 'Ireland sits between the UK''s pure decentralised model and France or Poland''s full clearance model — invoices don''t need government pre-approval, but transaction data still flows to Revenue in real time.' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Ireland');
UPDATE deep_dive_page_translations SET mandate_summary = 'There is no federal B2B e-invoicing mandate in the United States, and none is currently proposed on any fixed timeline. This page describes the voluntary DBNAlliance network and the existing federal B2G requirement — both real today, neither compulsory for private B2B trade.', mandate_summary_icon = '🇺🇸' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United States');
UPDATE deep_dive_page_translations SET scope_intro = 'Two genuinely separate channels exist — DBNAlliance for voluntary B2B, and a distinct federal procurement channel for anyone selling to the government.' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United States');
UPDATE deep_dive_page_translations SET mandate_summary = 'There is no B2B e-invoicing mandate in Canada, and none currently proposed on a fixed timeline. The one real, existing obligation is federal B2G — suppliers to the Government of Canada must invoice electronically via SAP Ariba. This page covers that requirement plus the honest state of everything else.', mandate_summary_icon = '🍁' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Canada');
UPDATE deep_dive_page_translations SET scope_intro = 'Two entirely separate worlds exist side by side: a mandated federal channel, and an unregulated everything-else.' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Canada');
UPDATE deep_dive_page_translations SET mandate_summary = 'Sweden has no legislated domestic B2B mandate. What''s genuinely new: a national inquiry into ViDA implementation launched 5 February 2026, explicitly tasked with assessing whether to mandate domestic B2B/G2B e-invoicing, with findings due no later than 30 November 2027.', mandate_summary_icon = '🔎' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Sweden');
UPDATE deep_dive_page_translations SET scope_intro = 'There is genuinely no central Swedish platform — this is one of the purest decentralised models in this tracker.' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Sweden');

-- Remaining 25 countries: fresh mandate_summary + icon, scope_intro unchanged
UPDATE deep_dive_page_translations SET mandate_summary = 'There is still no general B2B e-invoicing mandate in Australia — adoption of the Peppol network remains voluntary for private businesses. The one binding requirement is on the federal government itself: Commonwealth agencies have been required to receive Peppol e-invoices since July 2022, with compliance targets escalating through 2026.', mandate_summary_icon = '🐨' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Australia');
UPDATE deep_dive_page_translations SET mandate_summary = 'Belgium''s B2B e-invoicing mandate is fully in effect: since 1 January 2026, VAT-registered businesses must exchange invoices in structured Peppol format. It follows years of B2G e-invoicing via the Mercurius platform, with a near-real-time e-reporting layer due to follow in 2028.', mandate_summary_icon = '📨' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Belgium');
UPDATE deep_dive_page_translations SET mandate_summary = 'Brazil doesn''t have a single e-invoicing mandate — it has several, layered by transaction type and level of government, most of them in force for years. The live development right now is a major consumption-tax reform (CBS/IBS) being phased into that mature infrastructure, not a new invoicing requirement.', mandate_summary_icon = '🧱' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Brazil');
UPDATE deep_dive_page_translations SET mandate_summary = 'Chile''s clearance model has been mandatory for all businesses since 2018, making it one of the longest-running e-invoicing regimes in Latin America. Current activity is incremental — extending the same clearance approach to consumer receipts (boleta electrónica) rather than introducing anything new.', mandate_summary_icon = '🧾' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Chile');
UPDATE deep_dive_page_translations SET mandate_summary = 'China''s fully digitalized e-fapiao system has been mandatory nationwide since December 2024, the endpoint of a decade-long, carefully piloted rollout. Every invoice is cleared through the Golden Tax System before it''s legally valid — human-readable copies exist, but the XML is the actual legal document.', mandate_summary_icon = '🏮' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'China');
UPDATE deep_dive_page_translations SET mandate_summary = 'Croatia''s Fiskalizacija 2.0 reform made structured e-invoicing and e-reporting mandatory for VAT-registered businesses from 1 January 2026, building on a B2G system already running since 2019. Non-VAT-registered entities and public bodies join the mandate in 2027.', mandate_summary_icon = '📡' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Croatia');
UPDATE deep_dive_page_translations SET mandate_summary = 'Denmark''s Bookkeeping Act is a capability mandate, not a transmission mandate — businesses must be able to issue and receive e-invoices, but aren''t required to use that capability for every transaction. It''s already in force for medium and large companies, phasing down to smaller businesses through 2026, against a backdrop of an evolving national format moving from OIOUBL to NemHandel BIS.', mandate_summary_icon = '🔧' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Denmark');
UPDATE deep_dive_page_translations SET mandate_summary = 'ViDA doesn''t itself create a domestic e-invoicing mandate in any member state — it''s an EU-wide framework rolling out in phases through 2035, layered on top of whatever mandate each country already runs. The parts genuinely already in force are limited: member states may introduce their own domestic mandates freely, and a Single VAT Registration transposition deadline lands at the end of 2026.', mandate_summary_icon = '🇪🇺' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'European Union');
UPDATE deep_dive_page_translations SET mandate_summary = 'Finland has no domestic B2B e-invoicing mandate at all — one of the few countries in this tracker in that position — but adoption is already near-universal in practice, driven by decades of voluntary use. The one binding requirement is B2G: public-sector invoicing has been mandatory since 2020.', mandate_summary_icon = '🧊' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Finland');
UPDATE deep_dive_page_translations SET mandate_summary = 'France''s B2G e-invoicing mandate has been in force for years, but the much larger B2B reform is still phasing in: large and medium businesses must be able to receive structured invoices from September 2026, with the full issuing mandate reaching every business a year later. A separate e-reporting obligation runs in parallel for transactions outside e-invoicing''s scope.', mandate_summary_icon = '⏳' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'France');
UPDATE deep_dive_page_translations SET mandate_summary = 'Germany''s mandate arrives in careful stages: receiving structured invoices became mandatory for all businesses at the start of 2025, but the issuing requirement doesn''t reach smaller businesses until 2028. There''s no clearance authority and no domestic reporting obligation attached — Germany stays fully decentralised throughout.', mandate_summary_icon = '🛠️' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Germany');
UPDATE deep_dive_page_translations SET mandate_summary = 'India''s GST e-invoicing mandate has been rolled out by progressively lowering the turnover threshold rather than a single flag-day — it''s now in force for businesses above ₹5 crore turnover. Every qualifying invoice must be cleared through a government Invoice Registration Portal before it''s legally valid.', mandate_summary_icon = '🪜' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'India');
UPDATE deep_dive_page_translations SET mandate_summary = 'Italy runs the most mature clearance mandate in this entire tracker — B2G since 2014, and all domestic B2B/B2C transactions since 2019, via the Sistema di Interscambio. Current activity is routine schema maintenance (FatturaPA v1.9.1), not a new requirement.', mandate_summary_icon = '🏛️' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Italy');
UPDATE deep_dive_page_translations SET mandate_summary = 'Malaysia''s MyInvois clearance mandate is rolling out top-down by company turnover, already covering businesses down to the RM1–5 million tier as of 2026. Each tier gets a relaxation period after its formal start date before enforcement tightens.', mandate_summary_icon = '🎚️' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Malaysia');
UPDATE deep_dive_page_translations SET mandate_summary = 'Mexico''s CFDI clearance mandate is over a decade old and fully in force for all businesses — the activity today is version upgrades (CFDI 4.0) and annual catalog maintenance, not a new rollout. A 2026 tax reform tightens authenticity requirements on top of the existing system.', mandate_summary_icon = '🌵' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Mexico');
UPDATE deep_dive_page_translations SET mandate_summary = 'New Zealand runs the same Peppol framework as Australia, but its mandate lives in Government Procurement Rules rather than tax law. Central government agencies have had to receive e-invoices since March 2022, with obligations expanding to large suppliers selling into government from 2027.', mandate_summary_icon = '🥝' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'New Zealand');
UPDATE deep_dive_page_translations SET mandate_summary = 'Norway''s B2B e-invoicing mandate only became actual law in June 2026, after years as a proposal — and it''s deliberately asymmetric: businesses must be able to issue e-invoices from 2027, three full years before the reception requirement arrives in 2030.', mandate_summary_icon = '⚖️' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Norway');
UPDATE deep_dive_page_translations SET mandate_summary = 'Peru''s e-invoicing mandate (CPE) has applied to all taxpayers since 2022, the endpoint of a rollout that started with the largest taxpayers back in 2017. Every invoice must be validated either directly by SUNAT or by an authorised OSE before it carries legal weight.', mandate_summary_icon = '🏔️' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Peru');
UPDATE deep_dive_page_translations SET mandate_summary = 'Poland''s KSeF clearance mandate is now in force in stages: large taxpayers since February 2026, and virtually every other VAT-registered business since April 2026, following an earlier version of the system that was paused and rebuilt after a technical audit. Micro-entrepreneurs and penalty enforcement follow in 2027.', mandate_summary_icon = '🔁' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Poland');
UPDATE deep_dive_page_translations SET mandate_summary = 'Portugal doesn''t have a general B2B or B2C e-invoicing mandate — genuinely unusual among mature EU e-invoicing regimes — but a dense layer of certified-software and document-security requirements applies to every invoice regardless. A real structured-format mandate does exist for B2G, and is currently expanding to small and micro-enterprises.', mandate_summary_icon = '🔐' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Portugal');
UPDATE deep_dive_page_translations SET mandate_summary = 'Romania''s RO e-Factura clearance mandate has been fully in force for B2B and B2G transactions since mid-2024, after starting as a voluntary channel in 2021 and becoming B2G-mandatory in 2022. B2C reporting joined in 2025, and full enforcement reaches small taxpayers in mid-2026.', mandate_summary_icon = '🖋️' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Romania');
UPDATE deep_dive_page_translations SET mandate_summary = 'Saudi Arabia''s ZATCA mandate is fully in effect and rolling toward universal coverage: every VAT-registered business has had to generate e-invoices since December 2021, and direct government integration is now extending down through smaller turnover waves, reaching businesses above SAR 375,000 by mid-2026.', mandate_summary_icon = '🕌' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Saudi Arabia');
UPDATE deep_dive_page_translations SET mandate_summary = 'Singapore''s InvoiceNow started as a purely voluntary Peppol exchange network in 2019, and is now transitioning into a genuine tax-reporting requirement — GST InvoiceNow is already mandatory for new voluntary GST registrants, with the phase-in for existing GST-registered businesses stretching out to 2031, one of the longest runways in this tracker.', mandate_summary_icon = '🦁' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Singapore');
UPDATE deep_dive_page_translations SET mandate_summary = 'Slovakia''s B2B e-invoicing mandate is legislated law with a firm 2027 start date, after an earlier voluntary plan was quietly shelved in 2024. B2G/G2G e-invoicing has already been mandatory since 2023, and once B2B arrives, transmission must run through a certified "Digital Postman" that reports data to the tax authority in the same step.', mandate_summary_icon = '📮' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Slovakia');
UPDATE deep_dive_page_translations SET mandate_summary = 'The UAE built its e-invoicing framework unusually methodically — legislation, then service-provider accreditation, then a genuinely risk-free voluntary pilot — all before the mandate itself begins. The first mandatory go-live is 1 January 2027 for large businesses (AED 50 million+ revenue), extending to all other VAT-registered businesses six months later.', mandate_summary_icon = '🏗️' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United Arab Emirates');
