-- ES/DE/FR translations for all 5 Luxembourg milestones.
-- lx-b2g, lx-b2b-receipt, lx-b2b-issue-large, lx-b2b-issue-all reuse the
-- tracker's own translations (i18n/{lang}-data.json) verbatim, per
-- tracker-phrasing-wins. lx-law-2019 is deep-dive-only background.

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-law-2019', 'es', 'La Ley del 16 de mayo de 2019 establece el marco de facturación electrónica B2G', 'Luxemburgo transpone la Directiva UE 2014/55/UE a su legislación nacional, exigiendo a los proveedores del sector público poder enviar facturas electrónicas estructuradas. La Ley del 13 de diciembre de 2021 la modifica posteriormente para fijar las fechas de implementación escalonada según el tamaño de la empresa.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-law-2019', 'de', 'Das Gesetz vom 16. Mai 2019 schafft den Rahmen für die B2G-E-Rechnung', 'Luxemburg setzt die EU-Richtlinie 2014/55/EU in nationales Recht um und verpflichtet Lieferanten des öffentlichen Sektors, strukturierte E-Rechnungen versenden zu können. Das Gesetz vom 13. Dezember 2021 ändert es später, um die stufenweisen Einführungstermine nach Unternehmensgröße festzulegen.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-law-2019', 'fr', 'La loi du 16 mai 2019 établit le cadre de la facturation électronique B2G', 'Le Luxembourg transpose la directive européenne 2014/55/UE dans son droit national, obligeant les fournisseurs du secteur public à pouvoir envoyer des factures électroniques structurées. La loi du 13 décembre 2021 la modifie ensuite pour fixer les dates de déploiement progressif selon la taille de l''entreprise.', '[]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2g', 'es', 'El mandato de facturación electrónica B2G está plenamente vigente', 'La implementación escalonada de la facturación electrónica B2G de Luxemburgo se completó: todos los operadores económicos, incluidas las pequeñas empresas y las de reciente creación, deben ahora emitir facturas electrónicas Peppol BIS Billing 3.0 / EN 16931 a los organismos públicos de Luxemburgo.', '["Confirme que su Punto de Acceso Peppol (o la opción de carga manual de guichet.lu) está configurado para cada contrato público que suministre", "Se exigen facturas estructuradas EN 16931 para toda la contratación pública — no se aplica ningún umbral"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2g', 'de', 'B2G-E-Invoicing-Pflicht vollständig in Kraft', 'Luxemburgs stufenweise Einführung der B2G-E-Rechnung ist abgeschlossen: Alle Wirtschaftsteilnehmer, einschließlich kleiner und neu gegründeter Unternehmen, müssen nun Peppol-BIS-Billing-3.0- / EN-16931-E-Rechnungen an luxemburgische öffentliche Stellen ausstellen.', '["Bestätigen Sie, dass Ihr Peppol Access Point (oder die manuelle Upload-Option von guichet.lu) für jeden von Ihnen belieferten öffentlichen Auftrag eingerichtet ist", "Strukturierte EN-16931-Rechnungen sind für die gesamte öffentliche Beschaffung erforderlich — es gilt kein Schwellenwert"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2g', 'fr', 'L''obligation de facturation électronique B2G est pleinement en vigueur', 'Le déploiement progressif de la facturation électronique B2G au Luxembourg est achevé : tous les opérateurs économiques, y compris les petites entreprises et celles nouvellement créées, doivent désormais émettre des factures électroniques Peppol BIS Billing 3.0 / EN 16931 aux organismes publics luxembourgeois.', '["Vérifiez que votre Access Point Peppol (ou l''option de téléversement manuel de guichet.lu) est configuré pour chaque marché public que vous fournissez", "Des factures structurées EN 16931 sont exigées pour l''ensemble des marchés publics — aucun seuil ne s''applique"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-receipt', 'es', 'Propuesta: la recepción de facturas electrónicas B2B pasa a ser obligatoria', 'Según el proyecto de ley aprobado por el Consejo de Gobierno de Luxemburgo el 17 de julio de 2026, todas las empresas estarían obligadas a poder recibir facturas electrónicas estructuradas para las transacciones B2B nacionales a través de una red Peppol de cuatro esquinas, antes de que entre en vigor la obligación de emisión.', '["Siga la tramitación del proyecto en el Parlamento — todavía es un proyecto de ley, no está en vigor", "Confirme que su sistema de facturación/ERP ya puede recibir facturas Peppol BIS Billing 3.0"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-receipt', 'de', 'Vorschlag: Empfang von B2B-E-Rechnungen wird verpflichtend', 'Nach dem vom luxemburgischen Regierungsrat am 17. Juli 2026 gebilligten Gesetzentwurf müssten alle Unternehmen in der Lage sein, strukturierte E-Rechnungen für inländische B2B-Transaktionen über ein Peppol-Vier-Ecken-Netzwerk zu empfangen — noch vor der Pflicht zur Ausstellung.', '["Verfolgen Sie den Gesetzentwurf im Parlament — es handelt sich noch um einen Entwurf, der noch nicht in Kraft ist", "Bestätigen Sie, dass Ihr Rechnungs-/ERP-System bereits Peppol-BIS-Billing-3.0-Rechnungen empfangen kann"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-receipt', 'fr', 'Proposition : la réception de factures électroniques B2B devient obligatoire', 'Selon le projet de loi approuvé par le Conseil de gouvernement luxembourgeois le 17 juillet 2026, toutes les entreprises seraient tenues de pouvoir recevoir des factures électroniques structurées pour les transactions B2B nationales via un réseau Peppol à quatre coins, avant l''obligation d''émission.', '["Suivez l''évolution du projet de loi au Parlement — il ne s''agit encore que d''un projet, non encore en vigueur", "Vérifiez que votre système de facturation/ERP peut déjà recevoir des factures Peppol BIS Billing 3.0"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-issue-large', 'es', 'Propuesta: emisión de facturas electrónicas B2B para grandes y medianas empresas', 'Las empresas grandes y medianas estarían obligadas a emitir, y no solo recibir, facturas electrónicas B2B nacionales estructuradas a través de Peppol — seis meses después de que la obligación de recepción entre en vigor para todos.', '["Proveedores de mayor tamaño: inicien la incorporación al Punto de Acceso Peppol con bastante antelación a esta fecha", "Confirme su clasificación actual por tamaño de empresa, ya que determina qué plazo se aplica"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-issue-large', 'de', 'Vorschlag: Ausstellung von B2B-E-Rechnungen für große und mittlere Unternehmen', 'Große und mittlere Unternehmen müssten strukturierte inländische B2B-E-Rechnungen über Peppol nicht nur empfangen, sondern auch ausstellen — sechs Monate nachdem die Empfangspflicht für alle in Kraft getreten ist.', '["Größere Lieferanten: Beginnen Sie das Onboarding beim Peppol Access Point rechtzeitig vor diesem Termin", "Bestätigen Sie Ihre aktuelle Einstufung nach Unternehmensgröße, da diese die geltende Frist bestimmt"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-issue-large', 'fr', 'Proposition : émission de factures électroniques B2B pour les grandes et moyennes entreprises', 'Les grandes et moyennes entreprises seraient tenues d''émettre, et pas seulement de recevoir, des factures électroniques B2B nationales structurées via Peppol — six mois après l''entrée en vigueur de l''obligation de réception pour tous.', '["Fournisseurs de grande taille : commencez l''intégration à un Access Point Peppol bien avant cette date", "Vérifiez votre classification actuelle par taille d''entreprise, car elle détermine l''échéance applicable"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-issue-all', 'es', 'Propuesta: la emisión de facturas electrónicas B2B se generaliza', 'Las empresas restantes, incluidas las pymes, estarían obligadas a emitir facturas electrónicas B2B nacionales estructuradas, completando así el despliegue escalonado anunciado junto con las reformas del IVA en la era digital (ViDA) de la UE.', '["Pymes: este es el plazo que les aplica, 18 meses después de que comience la obligación de recepción", "No se prevé ningún reporte de IVA en tiempo real a nivel nacional junto con esta medida — Luxemburgo mantiene el modelo de interoperabilidad Peppol, no un sistema de compensación"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-issue-all', 'de', 'Vorschlag: Ausstellung von B2B-E-Rechnungen wird allgemein verpflichtend', 'Die übrigen Unternehmen, einschließlich KMU, müssten strukturierte inländische B2B-E-Rechnungen ausstellen und damit die stufenweise Einführung abschließen, die im Zusammenhang mit den EU-Reformen zur Mehrwertsteuer im digitalen Zeitalter (ViDA) angekündigt wurde.', '["KMU: Dies ist die für Sie geltende Frist, 18 Monate nach Beginn der Empfangspflicht", "Eine inländische Echtzeit-Umsatzsteuermeldung ist damit nicht geplant — Luxemburg bleibt beim Peppol-Interoperabilitätsmodell und führt kein Clearing-System ein"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('lx-b2b-issue-all', 'fr', 'Proposition : l''émission de factures électroniques B2B devient universelle', 'Les entreprises restantes, y compris les PME, seraient tenues d''émettre des factures électroniques B2B nationales structurées, achevant ainsi le déploiement progressif annoncé dans le cadre des réformes européennes de la TVA à l''ère numérique (ViDA).', '["PME : c''est l''échéance qui vous concerne, 18 mois après le début de l''obligation de réception", "Aucune déclaration de TVA nationale en temps réel n''est prévue en parallèle — le Luxembourg conserve le modèle d''interopérabilité Peppol plutôt qu''un système de contrôle centralisé"]');
