-- ES/DE/FR translations for the Luxembourg newsletter story.
-- INSERT OR IGNORE, safe against existing English rows.

INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-07-17-luxembourg-b2b-draft-law', 'es', 'Luxemburgo aprueba un proyecto de ley que extiende la facturación electrónica obligatoria al B2B nacional', 'El Consejo de Gobierno de Luxemburgo aprobó el 17 de julio de 2026 un proyecto de ley que extendería el mandato existente de facturación electrónica B2G a las transacciones B2B nacionales, implementado por fases a través de una red Peppol de cuatro esquinas entre 2028 y 2029 — aunque todavía requiere la aprobación parlamentaria.', '<h3>🇱🇺 Luxemburgo aprueba un proyecto de ley que extiende la facturación electrónica obligatoria al B2B nacional</h3>
<p>El 17 de julio de 2026, el Consejo de Gobierno de Luxemburgo, presidido por el primer ministro Luc Frieden, aprobó un proyecto de ley que extendería la facturación electrónica estructurada obligatoria más allá de la contratación pública (B2G) a las transacciones B2B nacionales entre empresas establecidas en Luxemburgo. El proyecto transpone el artículo 1 de la Directiva (UE) 2025/516 del Consejo — parte del paquete de reformas del IVA en la era digital (ViDA) de la UE.</p>
<p>El despliegue propuesto se escalona por tipo de obligación y tamaño de empresa: todas las empresas necesitarían poder <strong>recibir</strong> facturas electrónicas estructuradas a partir del 1 de enero de 2028; las empresas grandes y medianas necesitarían empezar a <strong>emitirlas</strong> a partir del 1 de julio de 2028; y el resto de las empresas, incluidas las pymes, necesitarían emitirlas a partir del 1 de enero de 2029. Las facturas circularían por la misma red Peppol de cuatro esquinas que Luxemburgo ya utiliza para el B2G, estructuradas conforme a EN 16931.</p>
<p>Esto se construye directamente sobre el mandato B2G existente de Luxemburgo, plenamente vigente desde marzo de 2023 tras una implementación por fases según el tamaño de la empresa que comenzó en 2022. No existe una capa nacional de reporte electrónico en tiempo real junto a esta propuesta — la única obligación de reporte electrónico en el horizonte es la declaración transfronteriza (DRR) a nivel de la UE bajo ViDA a partir del 1 de julio de 2030, cubierta por un proyecto de ley complementario.</p>
<p><strong>Qué significa esto para su equipo:</strong> se trata todavía de un proyecto de ley, no de una ley — necesita la aprobación parlamentaria antes de que cualquier fecha de 2028 quede fijada. Pero si comercia B2B a nivel nacional en Luxemburgo, la dirección ya está clara, y funcionará sobre la misma infraestructura Peppol que el mandato B2G existente. Si ya cumple con el B2G, prepararse para las normas B2B propuestas debería ser un esfuerzo menor que empezar de cero.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-07-17-luxembourg-b2b-draft-law', 'de', 'Luxemburg billigt Gesetzentwurf zur Ausweitung der verpflichtenden E-Rechnung auf inländisches B2B', 'Luxemburgs Regierungsrat billigte am 17. Juli 2026 einen Gesetzentwurf, der die bestehende B2G-E-Invoicing-Pflicht des Landes auf inländische B2B-Transaktionen ausweiten würde, stufenweise über ein Peppol-Vier-Ecken-Netzwerk von 2028 bis 2029 — dies bedarf jedoch noch der parlamentarischen Zustimmung.', '<h3>🇱🇺 Luxemburg billigt Gesetzentwurf zur Ausweitung der verpflichtenden E-Rechnung auf inländisches B2B</h3>
<p>Am 17. Juli 2026 billigte Luxemburgs Regierungsrat unter Vorsitz von Premierminister Luc Frieden einen Gesetzentwurf, der die verpflichtende strukturierte E-Rechnung über die öffentliche Beschaffung (B2G) hinaus auf inländische Geschäfte zwischen in Luxemburg ansässigen Unternehmen (B2B) ausweiten würde. Der Entwurf setzt Artikel 1 der Richtlinie (EU) 2025/516 des Rates um — Teil des EU-Reformpakets zur Mehrwertsteuer im digitalen Zeitalter (ViDA).</p>
<p>Die vorgeschlagene Einführung ist nach Pflichtart und Unternehmensgröße gestaffelt: Alle Unternehmen müssten ab dem 1. Januar 2028 in der Lage sein, strukturierte E-Rechnungen zu <strong>empfangen</strong>; große und mittlere Unternehmen müssten ab dem 1. Juli 2028 mit der <strong>Ausstellung</strong> beginnen; und die übrigen Unternehmen, einschließlich KMU, müssten ab dem 1. Januar 2029 ausstellen. Die Rechnungen würden über dasselbe Peppol-Vier-Ecken-Netzwerk laufen, das Luxemburg bereits für B2G nutzt, strukturiert nach EN 16931.</p>
<p>Dies baut direkt auf Luxemburgs bestehender B2G-Pflicht auf, die seit März 2023 nach einer 2022 begonnenen stufenweisen Einführung nach Unternehmensgröße vollständig in Kraft ist. Eine inländische Echtzeit-Meldeebene ist neben diesem Vorschlag nicht vorgesehen — die einzige am Horizont stehende E-Reporting-Pflicht ist die separate, EU-weite grenzüberschreitende Meldepflicht (DRR) unter ViDA ab dem 1. Juli 2030, die durch einen begleitenden Gesetzentwurf abgedeckt wird.</p>
<p><strong>Was das für Ihr Team bedeutet:</strong> Dies ist noch ein Entwurf, kein Gesetz — er benötigt die parlamentarische Zustimmung, bevor ein Termin in 2028 feststeht. Wenn Sie jedoch inländisch B2B in Luxemburg handeln, ist die Richtung nun klar, und sie wird auf derselben Peppol-Infrastruktur laufen wie die bestehende B2G-Pflicht. Wenn Sie bereits B2G-konform sind, dürfte die Vorbereitung auf die vorgeschlagenen B2B-Regeln ein kleinerer Schritt sein als ein Neuanfang.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-07-17-luxembourg-b2b-draft-law', 'fr', 'Le Luxembourg approuve un projet de loi étendant la facturation électronique obligatoire au B2B national', 'Le Conseil de gouvernement luxembourgeois a approuvé le 17 juillet 2026 un projet de loi qui étendrait l''obligation existante de facturation électronique B2G aux transactions B2B nationales, déployée par phases via un réseau Peppol à quatre coins de 2028 à 2029 — bien qu''elle nécessite encore l''approbation parlementaire.', '<h3>🇱🇺 Le Luxembourg approuve un projet de loi étendant la facturation électronique obligatoire au B2B national</h3>
<p>Le 17 juillet 2026, le Conseil de gouvernement luxembourgeois, présidé par le Premier ministre Luc Frieden, a approuvé un projet de loi qui étendrait la facturation électronique structurée obligatoire au-delà des marchés publics (B2G) aux transactions B2B nationales entre entreprises établies au Luxembourg. Le texte transpose l''article 1 de la directive (UE) 2025/516 du Conseil — qui s''inscrit dans le paquet de réformes européennes de la TVA à l''ère numérique (ViDA).</p>
<p>Le déploiement proposé est échelonné par type d''obligation et par taille d''entreprise : toutes les entreprises devraient pouvoir <strong>recevoir</strong> des factures électroniques structurées à partir du 1er janvier 2028 ; les grandes et moyennes entreprises devraient commencer à les <strong>émettre</strong> à partir du 1er juillet 2028 ; et les entreprises restantes, y compris les PME, devraient les émettre à partir du 1er janvier 2029. Les factures circuleraient sur le même réseau Peppol à quatre coins que le Luxembourg utilise déjà pour le B2G, structurées selon la norme EN 16931.</p>
<p>Cette mesure s''appuie directement sur l''obligation B2G existante du Luxembourg, pleinement en vigueur depuis mars 2023 à la suite d''un déploiement progressif par taille d''entreprise entamé en 2022. Aucune couche nationale de télédéclaration en temps réel n''est prévue en parallèle de cette proposition — la seule obligation de déclaration électronique à l''horizon est la déclaration transfrontalière (DRR) à l''échelle de l''UE au titre de ViDA à partir du 1er juillet 2030, couverte par un projet de loi complémentaire.</p>
<p><strong>Ce que cela signifie pour votre équipe :</strong> il ne s''agit encore que d''un projet, pas d''une loi — il doit obtenir l''approbation parlementaire avant qu''une échéance de 2028 ne soit fixée. Mais si vous commercez en B2B au niveau national au Luxembourg, la direction est désormais claire, et le dispositif reposera sur la même infrastructure Peppol que l''obligation B2G existante. Si vous êtes déjà conforme au B2G, vous préparer aux règles B2B proposées devrait représenter un effort moindre que de repartir de zéro.</p>');
