-- Egypt deep-dive content (English). Follows the Luxembourg 193 shape:
-- page + stats + cards + steps + portals, penalties covered narratively
-- in penalties_related cards (Egypt's published penalty landscape mixes
-- fixed fines, daily penalties, and consequence-based enforcement, which
-- reads better as cards than as a fine-schedule table).

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-02' FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en', 'Centralized clearance — ETA platform (e-invoices + e-receipts)', 'This deep-dive page reflects publicly available technical guidance as of August 2026 and is provided for general awareness, not legal or tax advice. The ETA adjusts wave scopes, thresholds, and penalty practice by decision and circular — confirm current requirements directly with the Egyptian Tax Authority or your integration provider before building against them.', 'Egypt''s rollout ran as two parallel tracks under one authority: ETA-cleared B2B/B2G e-invoicing phased in from November 2020 and universal by April 2023, and a separate B2C e-receipt system rolled out in staged waves — with 2026 marking the shift from onboarding to enforcement.', 'Egypt uses its own ETA-defined structured formats rather than an EU-style standard: JSON or XML documents, digitally signed, carrying standardized product codes, and cleared by the central platform which assigns each document its official UUID.', 'Everything routes through the ETA''s central platform: invoices are cleared in real or near-real time via API integration, the web portal, or the mobile app, while consumer receipts flow from POS systems integrated with the parallel e-receipt system.', 'Getting compliant means registering with the ETA, obtaining a digital certificate, mapping your product codes, and integrating each sales channel — with the invoice and receipt tracks needing separate attention.', 'Egypt backs the mandate with real teeth: explicit fines for late submission and missed registration since 2026, denial of VAT input credits on non-cleared documents, and consequence-based enforcement reaching import/export rights and government contracts.', 'Egypt''s ETA-cleared e-invoicing has been mandatory for all VAT-registered businesses since April 2023, with paper invoices losing VAT-deduction validity from July 2023 and a parallel B2C e-receipt rollout. Since January 2026 the regime is in its enforcement stage: late-submission penalties, QR codes on printed receipts, and a registration threshold cut to EGP 250,000.', '🏛️' FROM countries WHERE name_en = 'Egypt';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Clearance', 'Centralized ETA model');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'JSON/XML', 'Structured formats');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2023', 'B2B fully in force');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'EGP 250k', '2026 registration threshold');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'QR', 'Required on printed e-receipts');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & standard', '[["Document formats", "JSON or XML per the ETA''s published schema"], ["Signature", "Digital signature required (HSM or USB token certificate)"], ["Product coding", "GS1 international codes or EGS (Egyptian) internal coding"], ["Clearance artefact", "ETA assigns each cleared document an official UUID"]]', 'Egypt predates and sits outside the EN 16931 world — the ETA defines its own document schema, so European format work doesn''t carry over directly and product-code mapping is usually the largest one-off integration task.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Identifiers & registration', '[["Taxpayer identity", "Egyptian tax registration number"], ["Certificate", "ETA-issued digital certificate for signing"], ["Registration", "Via the ETA e-invoicing portal (invoicing.eta.gov.eg)"], ["POS devices", "Each device registered with a serial in the e-receipt system"]]', 'Registration is per-entity but integration is per-channel: an entity selling B2B and B2C needs both its invoicing integration and every POS device enrolled in the receipt system.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Mandatory content', '[["Party data", "Seller and buyer tax registration numbers"], ["Line level", "Standardized product codes, quantities, values"], ["On clearance", "ETA UUID embedded in the validated document"], ["Printed e-receipts", "QR code linking to the validated ETA record (from 2026)"]]', 'Missing content is treated as non-compliance, not a formality — an invoice without the buyer''s tax number or the required coding can be rejected or penalized, and from 2026 a printed receipt without its QR code is itself a violation.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Archiving', '[["Retention period", "5 years under Egyptian tax procedures"], ["What to keep", "The cleared document (with its ETA UUID) plus submission records"]]', 'The cleared record in the ETA platform is the authoritative one — keep your own archive reconciled against it, since disputes are settled by what the platform holds.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Network model', '[["Model", "Centralized clearance via the ETA platform"], ["Tracks", "E-invoicing (B2B/B2G) and a separate e-receipt system (B2C)"], ["Timing", "Real or near-real-time submission; legacy grace windows phasing out"], ["Legal basis", "Law No. 206 of 2020 (Unified Tax Procedures Law)"]]', 'The two tracks are operationally separate — being fully compliant on invoicing says nothing about your POS estate, and vice versa. Treat them as two integrations under one authority.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Channels', '[["ERP integration", "ETA SDK / APIs for direct system-to-system submission"], ["Web portal", "Manual issuance for lower volumes"], ["Mobile app", "Free ETA app aimed at small taxpayers"], ["POS", "Point-of-sale or ERP integration with the e-receipt system for B2C"]]', 'The free portal and mobile app exist so the threshold cut to EGP 250,000 doesn''t strand small businesses without software — but anything with real volume needs the API route.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'The 2026 shift: onboarding to enforcement', '[["Registration threshold", "Cut from EGP 500,000 to EGP 250,000 gross annual revenue"], ["Registration deadline", "31 March 2026 (passed — daily penalties accrue for the unregistered)"], ["E-receipt expansion", "Eighth sub-phase in force since 15 September 2025 (Decision 281/2025)"]]', 'The ETA''s posture changed in January 2026 from growing the system to policing it — if any Egyptian entity in your group has been coasting on being small or unnoticed, that assumption is now expensive.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚖️ Fines with a daily clock', NULL, NULL, 'Missing the registration deadline triggers an EGP 20,000 fine plus EGP 1,000 per day until resolved, and since January 2026 an explicit penalty regime applies to late submission of e-invoices and e-receipts. At the severe end — non-compliant or fraudulent documents — fines reach EGP 50,000 with potential imprisonment.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🧾 VAT consequences', NULL, NULL, 'Paper invoices have not supported VAT deduction since July 2023 — only ETA-cleared electronic invoices allow input VAT recovery. A supplier outside the system doesn''t just risk fines; their invoices are worthless to their business customers, which is the mandate''s real enforcement engine.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🚫 Consequence-based enforcement', NULL, NULL, 'Beyond fines, the tiered enforcement framework can suspend a business''s ability to issue valid invoices, and non-compliance can mean exclusion from government contracts and import/export restrictions — the ETA cross-references VAT filings against exemption claims automatically.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm scope for each entity and channel', 'Use the ETA''s lookup with your tax registration number — the invoice and receipt tracks have separate wave decisions, so check both, and remember the threshold is gross revenue before expenses.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Register with the ETA and obtain your certificate', 'Register on the e-invoicing portal and obtain the digital certificate used to sign documents; without it nothing you submit is valid.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Map your product catalogue to GS1 or EGS codes', 'This is usually the largest one-off task — every line item needs a standardized code, and uncoded items are a rejection risk.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Integrate your issuing systems', 'High-volume entities should integrate ERP systems via the ETA SDK/APIs; the web portal and free mobile app cover low-volume and small-taxpayer cases.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Bring your POS estate into the e-receipt system', 'Register each device, integrate with the central platform for real-time verification, and make sure printed receipts carry the QR code linking to the validated record.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Audit timeliness and reconcile against the platform', 'Since January 2026, late submission attracts explicit penalties — monitor submission SLAs and reconcile your archive against the ETA''s cleared records on a schedule.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://invoicing.eta.gov.eg', 0 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'ETA e-invoicing portal');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.eta.gov.eg', 1 FROM countries WHERE name_en = 'Egypt';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Egyptian Tax Authority');
