-- Netherlands deep-dive content (English). Distinct shape from most
-- countries: the compliance_model is 'voluntary, market-driven' rather
-- than a clearance/mandate model, and penalties are covered narratively
-- since there is no domestic B2B enforcement regime today -- the real
-- 'penalty' is contractual (counterparties requiring Peppol) and future
-- (the 2030 EU floor).

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-02' FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en', 'Voluntary B2B (market-driven Peppol adoption) — B2G mandatory since 2017/2019', 'This deep-dive page reflects publicly available guidance and reporting as of August 2026 and is provided for general awareness, not legal or tax advice. The Dutch cabinet''s position on a domestic B2B mandate was still undecided at time of writing, with a formal direction expected summer 2026 and draft legislation planned for Q4 2026 — confirm current status directly with the Belastingdienst or Logius before building against it.', 'The Netherlands took a market-driven path that most of Europe hasn''t: B2G e-invoicing has been mandatory since 2017, but B2B remains voluntary today, backed by unusually high Peppol adoption. That is now under active review — a March 2026 advisory report recommended a domestic mandate, and the cabinet''s decision is expected imminently, against a firm EU-law floor of July 2030 for cross-border B2B regardless of the outcome.', 'Where B2G exchange happens, it runs on Peppol BIS 3.0 / SI-UBL 2.0 — the same standard voluntarily used by most B2B traffic today, so businesses already exchanging Peppol invoices with government counterparties are largely pre-adapted for whatever the domestic B2B decision brings.', 'Three channels serve B2G traffic today — the Peppol network (recommended), Digipoort (a direct gateway for high-volume suppliers), and the Government Supplier Portal (manual entry for low-volume suppliers) — while B2B exchange happens by mutual agreement, typically also over Peppol.', 'Because B2B is voluntary today, most businesses'' near-term work is about readiness rather than compliance: confirming Peppol capability, watching the cabinet''s scope decision, and preparing for the confirmed 2030 EU cross-border floor regardless of what the domestic mandate ultimately covers.', 'There is no domestic B2B penalty regime today because there is no domestic B2B mandate — but two real pressures already apply: contractual exclusion (counterparties increasingly requiring Peppol to do business at all) and the approaching EU-law floor that applies regardless of the domestic outcome.', 'The Netherlands has run mandatory B2G e-invoicing since 2017 (central government) and 2019 (all public bodies), but B2B remains voluntary — a deliberate market-driven approach with unusually high Peppol adoption. A March 2026 government-commissioned report recommended extending the mandate to domestic B2B on Peppol, phased 2030–2032; the cabinet''s formal decision was expected by summer 2026, with draft legislation planned for Q4 2026. Separately, ViDA''s cross-border B2B e-invoicing and reporting mandate is confirmed EU law from 1 July 2030, regardless of the domestic outcome.', '🌷' FROM countries WHERE name_en = 'Netherlands';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Voluntary', 'B2B e-invoicing (today)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2017/2019', 'B2G mandate in force');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'High', 'Voluntary Peppol adoption');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2030', 'EU cross-border floor (confirmed)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2030–32', 'Proposed domestic phase-in');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & standard', '[["Standard", "Peppol BIS Billing 3.0 / SI-UBL 2.0 (EN 16931-aligned)"], ["Legal basis", "B2G: EU Directive 2014/55/EU, transposed 2017/2019"], ["B2B today", "No mandated format — Peppol is the de facto market standard"], ["Future B2B (proposed)", "EN 16931, most likely via Peppol, per the March 2026 report"]]', 'There is no separate Dutch national format to learn — SI-UBL is fully aligned with international Peppol BIS 3.0, so a business already Peppol-capable for one counterparty (government or commercial) is capable for essentially all of them.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Identifiers & registration', '[["B2G registration", "Via Logius (Digipoort) or a Peppol Access Point"], ["Peppol identity", "Peppol Participant ID, issued by an Access Point provider"], ["Governing body", "Netherlands Peppol Authority (formerly SimplerInvoicing), under the Ministry of the Interior"], ["B2B today", "No registration required — bilateral agreement between trading partners"]]', 'Because B2B has no mandate, there is no national B2B registry to enrol in — the only formal registration step today is for B2G traffic, or for any business that chooses to obtain its own Peppol Access Point capability.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Mandatory content', '[["B2G", "Full EN 16931 core invoice model via Peppol BIS 3.0"], ["B2B today", "Whatever the trading partners agree — commonly the same Peppol BIS 3.0 fields in practice"], ["Archiving", "7 years, standard Dutch record-keeping requirement"]]', 'Because Peppol BIS 3.0 already dominates voluntary B2B exchange, most businesses'' invoice content is already EN 16931-shaped in practice, even without a legal requirement forcing it.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Network model', '[["B2G model", "Peppol four-corner network, or direct Digipoort integration"], ["B2B model", "Voluntary bilateral exchange, typically also over Peppol"], ["Real-time reporting", "None today — the Netherlands has no domestic clearance or CTC regime"], ["Peppol authority", "Netherlands Peppol Authority (formerly SimplerInvoicing)"]]', 'Unlike most of the tracker, there is no clearance model here to describe for B2B — invoices move directly between trading partners'' systems, with the tax authority receiving no real-time visibility, a deliberate contrast to Belgium, France, Italy, and Poland.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Channels', '[["Peppol network", "The recommended channel for both B2G and voluntary B2B"], ["Digipoort", "Direct gateway for high-volume B2G suppliers (roughly 50+ invoices/week)"], ["Government Supplier Portal", "Manual web entry for low-volume B2G suppliers"], ["ROAP", "Rijksoverheid Access Point op Peppol — the central government''s own Peppol access point"]]', 'The three-tier B2G channel structure (Peppol / Digipoort / manual portal) exists specifically so smaller suppliers aren''t shut out by the mandate — a design pattern worth noting given the domestic B2B mandate under discussion would need something similar.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'The pending domestic decision', '[["Under review", "ViDA-A (cross-border only) vs. ViDA-B (extend to domestic B2B)"], ["Advisory recommendation", "ViDA-B, on Peppol, phased 2030–2032 (March 2026 report)"], ["Cabinet decision", "Expected summer 2026 (not yet formally announced at time of writing)"], ["Firm floor regardless", "1 July 2030 — ViDA cross-border B2B, confirmed EU law"]]', 'This is the one entry on this page that is genuinely undecided — track the sources page and the tracker board for the cabinet''s formal position once announced, since it will determine whether virtually every Dutch VAT-registered business eventually needs Peppol capability, or only those trading cross-border.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🤝 Contractual exclusion, not statutory fines', NULL, NULL, 'There is no legal penalty for B2B non-compliance today, because there is no legal B2B requirement — but major counterparties increasingly require Peppol capability as a procurement condition. In practice, the cost of staying outside the voluntary system is losing business, not a fine.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🇪🇺 The approaching EU floor', NULL, NULL, 'Regardless of what the Netherlands decides on domestic B2B, ViDA''s cross-border requirement is confirmed EU law from 1 July 2030 — every Dutch business doing intra-EU B2B trade will need EN 16931-compliant e-invoicing and digital reporting for those transactions, mandate or no mandate.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚖️ B2G exceptions', NULL, NULL, 'For B2G traffic, non-compliant invoices can be rejected under public procurement rules — the closest thing to an enforcement mechanism that exists today, and confined to government trade rather than the broader economy.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm your current Peppol capability', 'Since most Dutch B2B traffic already runs on Peppol voluntarily, check whether your ERP or accounting software already supports BIS 3.0 / SI-UBL 2.0 — many mainstream Dutch platforms do natively.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Establish or verify your B2G channel if applicable', 'Suppliers to Dutch public bodies should confirm they''re using Peppol, Digipoort, or the Government Supplier Portal correctly, and that receipt capability is in place for sub-central bodies.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Track the cabinet''s ViDA-A/ViDA-B decision', 'This is the single most consequential open question for Dutch e-invoicing — the domestic scope decision determines whether the coming mandate covers only cross-border trade or virtually every VAT-registered business.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Prepare for the confirmed 2030 cross-border floor regardless', 'Even if the Netherlands opts for the minimal ViDA-A scope, every business doing intra-EU B2B trade needs EN 16931 e-invoicing and digital reporting capability from 1 July 2030 — this date is fixed by EU directive, not Dutch discretion.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Revisit counterparty contracts for Peppol requirements', 'With adoption already high and rising, expect more trading partners to make Peppol capability a procurement condition ahead of any formal domestic mandate.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.logius.nl/onze-dienstverlening/gegevensuitwisseling/e-factureren', 0 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Logius — e-Factureren');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.logius.nl/onze-dienstverlening/domeinen/gegevensuitwisseling/peppol', 1 FROM countries WHERE name_en = 'Netherlands';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Netherlands Peppol Authority');
