-- Netherlands story arc, 5 stories spanning Aug 2025 - Aug 2026 (all
-- 4 languages), giving the new country's archive real depth on day
-- one rather than a single launch post. Story 3 (March 2026) doubles
-- as the country's launch coverage, tied to the nl-eyreport-2026
-- board milestone. All sourced and fact-checked against the
-- milestone dates already on the board -- no board corrections
-- needed.

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-08-15-netherlands-vida-roadmap', '2025-08-15', '2025-08', 'A parliamentary letter from the State Secretary for Finance lays out a four-phase roadmap toward the EU''s 2030 e-invoicing and digital reporting deadline — policy research, legislation, technical build, and rollout.', '<h3>🇳🇱 Netherlands sets out its path to the 2030 ViDA deadline</h3>
<p>The Dutch State Secretary for Finance has sent Parliament a letter (Nr. 4090, 26 June 2025) setting out how the Netherlands intends to approach the EU''s VAT in the Digital Age (ViDA) e-invoicing and digital reporting pillar, which becomes mandatory for cross-border B2B transactions from 1 July 2030 across every EU member state.</p>
<p>The roadmap runs in four phases: policy research and stakeholder consultation running to 2028, delivery of the legislative framework by 2028, technical development from 2028 to 2030, and full enforcement beginning July 2030. The approach is characteristically methodical — the Netherlands is treating the ViDA deadline less as a single cliff-edge and more as a multi-year programme, giving businesses, especially smaller ones, a long runway to adapt.</p>
<p>The letter leaves open the single biggest question for Dutch businesses: whether the country will confine itself to the EU''s cross-border minimum, or extend the same obligations to domestic B2B trade — a decision that would affect virtually every VAT-registered business in the country rather than only those trading across borders. That question is now the subject of a commissioned advisory study, due to report within the year.</p>', 'https://www.rijksoverheid.nl', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-08-15-netherlands-vida-roadmap', id FROM countries WHERE name_en = 'Netherlands';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-08-15-netherlands-vida-roadmap', 'en', 'Netherlands sets out its path to the 2030 ViDA deadline', 'A parliamentary letter from the State Secretary for Finance lays out a four-phase roadmap toward the EU''s 2030 e-invoicing and digital reporting deadline — policy research, legislation, technical build, and rollout.', '<h3>🇳🇱 Netherlands sets out its path to the 2030 ViDA deadline</h3>
<p>The Dutch State Secretary for Finance has sent Parliament a letter (Nr. 4090, 26 June 2025) setting out how the Netherlands intends to approach the EU''s VAT in the Digital Age (ViDA) e-invoicing and digital reporting pillar, which becomes mandatory for cross-border B2B transactions from 1 July 2030 across every EU member state.</p>
<p>The roadmap runs in four phases: policy research and stakeholder consultation running to 2028, delivery of the legislative framework by 2028, technical development from 2028 to 2030, and full enforcement beginning July 2030. The approach is characteristically methodical — the Netherlands is treating the ViDA deadline less as a single cliff-edge and more as a multi-year programme, giving businesses, especially smaller ones, a long runway to adapt.</p>
<p>The letter leaves open the single biggest question for Dutch businesses: whether the country will confine itself to the EU''s cross-border minimum, or extend the same obligations to domestic B2B trade — a decision that would affect virtually every VAT-registered business in the country rather than only those trading across borders. That question is now the subject of a commissioned advisory study, due to report within the year.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-08-15-netherlands-vida-roadmap', 'es', 'Los Países Bajos trazan su hoja de ruta hacia el plazo de ViDA de 2030', 'Una carta parlamentaria del Secretario de Estado de Hacienda expone una hoja de ruta en cuatro fases hacia el plazo de la UE de 2030 para la facturación electrónica y el reporte digital — investigación de políticas, legislación, desarrollo técnico y despliegue.', '<h3>🇳🇱 Los Países Bajos trazan su hoja de ruta hacia el plazo de ViDA de 2030</h3>
<p>El Secretario de Estado de Hacienda neerlandés ha enviado al Parlamento una carta (N.º 4090, 26 de junio de 2025) que expone cómo pretenden los Países Bajos abordar el pilar de facturación electrónica y reporte digital del IVA en la Era Digital (ViDA) de la UE, que será obligatorio para las transacciones B2B transfronterizas desde el 1 de julio de 2030 en todos los Estados miembros.</p>
<p>La hoja de ruta se desarrolla en cuatro fases: investigación de políticas y consulta con las partes interesadas hasta 2028, entrega del marco legislativo para 2028, desarrollo técnico entre 2028 y 2030, y plena aplicación a partir de julio de 2030. El enfoque es característicamente metódico — los Países Bajos tratan el plazo de ViDA menos como un único punto de inflexión y más como un programa plurianual, dando a las empresas, especialmente a las más pequeñas, un largo margen para adaptarse.</p>
<p>La carta deja abierta la mayor pregunta para las empresas neerlandesas: si el país se limitará al mínimo transfronterizo de la UE, o ampliará las mismas obligaciones al comercio B2B nacional — una decisión que afectaría prácticamente a todas las empresas registradas a efectos de IVA del país, no solo a las que comercian a través de fronteras. Esa pregunta es ahora objeto de un estudio consultivo encargado, que se espera dentro del año.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-08-15-netherlands-vida-roadmap', 'de', 'Niederlande legen Fahrplan zur ViDA-Frist 2030 vor', 'Ein Parlamentsschreiben des Staatssekretärs für Finanzen skizziert einen vierstufigen Fahrplan zur EU-Frist 2030 für E-Rechnung und digitale Meldung — Politikforschung, Gesetzgebung, technischer Aufbau und Rollout.', '<h3>🇳🇱 Niederlande legen Fahrplan zur ViDA-Frist 2030 vor</h3>
<p>Der niederländische Staatssekretär für Finanzen hat dem Parlament ein Schreiben (Nr. 4090, 26. Juni 2025) übermittelt, das darlegt, wie die Niederlande die E-Rechnungs- und Meldepflicht-Säule der EU-Initiative VAT in the Digital Age (ViDA) angehen wollen, die ab dem 1. Juli 2030 für grenzüberschreitende B2B-Umsätze in jedem EU-Mitgliedstaat verpflichtend wird.</p>
<p>Der Fahrplan verläuft in vier Phasen: Politikforschung und Stakeholder-Konsultation bis 2028, Fertigstellung des Gesetzesrahmens bis 2028, technische Entwicklung von 2028 bis 2030 und vollständige Durchsetzung ab Juli 2030. Der Ansatz ist typisch methodisch — die Niederlande behandeln die ViDA-Frist weniger als einen einzelnen Stichtag, sondern eher als ein mehrjähriges Programm, das Unternehmen, insbesondere kleineren, viel Zeit zur Anpassung gibt.</p>
<p>Das Schreiben lässt die für niederländische Unternehmen größte Frage offen: ob sich das Land auf das grenzüberschreitende EU-Minimum beschränkt oder dieselben Pflichten auf den inländischen B2B-Handel ausweitet — eine Entscheidung, die praktisch jedes umsatzsteuerregistrierte Unternehmen im Land betreffen würde, nicht nur die grenzüberschreitend Handelnden. Diese Frage ist nun Gegenstand eines in Auftrag gegebenen Gutachtens, das innerhalb eines Jahres vorliegen soll.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-08-15-netherlands-vida-roadmap', 'fr', 'Les Pays-Bas tracent leur trajectoire vers l''échéance ViDA de 2030', 'Une lettre parlementaire du secrétaire d''État aux Finances expose une feuille de route en quatre phases vers l''échéance européenne de 2030 pour la facturation électronique et la déclaration numérique — recherche politique, législation, développement technique et déploiement.', '<h3>🇳🇱 Les Pays-Bas tracent leur trajectoire vers l''échéance ViDA de 2030</h3>
<p>Le secrétaire d''État néerlandais aux Finances a transmis au Parlement une lettre (n° 4090, 26 juin 2025) exposant la manière dont les Pays-Bas comptent aborder le volet facturation électronique et déclaration numérique de l''initiative européenne TVA à l''ère numérique (ViDA), qui deviendra obligatoire pour les transactions B2B transfrontalières à compter du 1er juillet 2030 dans chaque État membre de l''UE.</p>
<p>La feuille de route se déroule en quatre phases : recherche politique et consultation des parties prenantes jusqu''en 2028, livraison du cadre législatif d''ici 2028, développement technique de 2028 à 2030, et application intégrale à partir de juillet 2030. L''approche est typiquement méthodique — les Pays-Bas traitent l''échéance ViDA moins comme une falaise unique que comme un programme pluriannuel, laissant aux entreprises, notamment les plus petites, une longue marge d''adaptation.</p>
<p>La lettre laisse ouverte la question la plus déterminante pour les entreprises néerlandaises : le pays se limitera-t-il au minimum transfrontalier de l''UE, ou étendra-t-il les mêmes obligations au commerce B2B national — une décision qui toucherait pratiquement toutes les entreprises assujetties à la TVA du pays, et non les seules opérant à travers les frontières. Cette question fait désormais l''objet d''une étude consultative commandée, attendue dans l''année.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-02-01-netherlands-ey-report-published', '2026-02-01', '2026-02', 'A commissioned advisory study, published by the Ministry of Finance, recommends extending mandatory e-invoicing beyond the EU''s cross-border minimum to cover domestic B2B transactions as well, built on Peppol.', '<h3>🇳🇱 Independent report tells Dutch Ministry of Finance: go broad on ViDA</h3>
<p>On 26 January 2026, the Dutch Ministry of Finance published an independent advisory report examining how the Netherlands should implement the EU''s VAT in the Digital Age (ViDA) e-invoicing and digital reporting pillar. The report weighs two scenarios: ViDA-A, limited strictly to the EU''s cross-border B2B minimum, and ViDA-B, extending the same obligations to domestic B2B transactions.</p>
<p>Drawing on stakeholder interviews, a comparative study of six EU countries, and a cost-benefit analysis, the report''s conclusion is unambiguous: it recommends ViDA-B, built on a single prescribed infrastructure — Peppol — to maximise standardisation and interoperability. The report also points to Italy''s experience, where a comparable clearance-style mandate has been credited with materially reducing the national VAT gap.</p>
<p>The report is explicitly advisory — a third-party study, not government policy — but it sets the terms of the debate the cabinet must now resolve. A formal government position was expected within months, putting the Netherlands on a similar trajectory to Belgium, France, and Italy, all of which chose comprehensive domestic mandates rather than the EU''s bare minimum.</p>', 'https://www.rijksoverheid.nl', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-02-01-netherlands-ey-report-published', id FROM countries WHERE name_en = 'Netherlands';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-02-01-netherlands-ey-report-published', 'en', 'Independent report tells Dutch Ministry of Finance: go broad on ViDA', 'A commissioned advisory study, published by the Ministry of Finance, recommends extending mandatory e-invoicing beyond the EU''s cross-border minimum to cover domestic B2B transactions as well, built on Peppol.', '<h3>🇳🇱 Independent report tells Dutch Ministry of Finance: go broad on ViDA</h3>
<p>On 26 January 2026, the Dutch Ministry of Finance published an independent advisory report examining how the Netherlands should implement the EU''s VAT in the Digital Age (ViDA) e-invoicing and digital reporting pillar. The report weighs two scenarios: ViDA-A, limited strictly to the EU''s cross-border B2B minimum, and ViDA-B, extending the same obligations to domestic B2B transactions.</p>
<p>Drawing on stakeholder interviews, a comparative study of six EU countries, and a cost-benefit analysis, the report''s conclusion is unambiguous: it recommends ViDA-B, built on a single prescribed infrastructure — Peppol — to maximise standardisation and interoperability. The report also points to Italy''s experience, where a comparable clearance-style mandate has been credited with materially reducing the national VAT gap.</p>
<p>The report is explicitly advisory — a third-party study, not government policy — but it sets the terms of the debate the cabinet must now resolve. A formal government position was expected within months, putting the Netherlands on a similar trajectory to Belgium, France, and Italy, all of which chose comprehensive domestic mandates rather than the EU''s bare minimum.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-02-01-netherlands-ey-report-published', 'es', 'Un informe independiente recomienda al Ministerio de Hacienda neerlandés ampliar el alcance de ViDA', 'Un estudio consultivo encargado, publicado por el Ministerio de Hacienda, recomienda ampliar la facturación electrónica obligatoria más allá del mínimo transfronterizo de la UE para cubrir también las transacciones B2B nacionales, basándose en Peppol.', '<h3>🇳🇱 Un informe independiente recomienda al Ministerio de Hacienda neerlandés ampliar el alcance de ViDA</h3>
<p>El 26 de enero de 2026, el Ministerio de Hacienda neerlandés publicó un informe consultivo independiente que examina cómo deberían los Países Bajos aplicar el pilar de facturación electrónica y reporte digital del IVA en la Era Digital (ViDA) de la UE. El informe sopesa dos escenarios: ViDA-A, limitado estrictamente al mínimo transfronterizo B2B de la UE, y ViDA-B, que amplía las mismas obligaciones a las transacciones B2B nacionales.</p>
<p>Basándose en entrevistas con las partes interesadas, un estudio comparativo de seis países de la UE y un análisis coste-beneficio, la conclusión del informe es inequívoca: recomienda ViDA-B, construido sobre una única infraestructura prescrita — Peppol — para maximizar la estandarización y la interoperabilidad. El informe también señala la experiencia de Italia, donde un mandato de tipo compensación comparable se ha atribuido una reducción sustancial de la brecha nacional del IVA.</p>
<p>El informe es explícitamente consultivo — un estudio de terceros, no política gubernamental — pero fija los términos del debate que el gabinete debe resolver ahora. Se esperaba una postura formal del gobierno en los meses siguientes, situando a los Países Bajos en una trayectoria similar a la de Bélgica, Francia e Italia, que optaron por mandatos nacionales integrales en lugar del mínimo de la UE.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-02-01-netherlands-ey-report-published', 'de', 'Unabhängiges Gutachten rät niederländischem Finanzministerium zu einer breiten ViDA-Umsetzung', 'Ein in Auftrag gegebenes Gutachten, veröffentlicht vom Finanzministerium, empfiehlt, die verpflichtende E-Rechnung über das grenzüberschreitende EU-Minimum hinaus auch auf inländische B2B-Umsätze auszuweiten, gestützt auf Peppol.', '<h3>🇳🇱 Unabhängiges Gutachten rät niederländischem Finanzministerium zu einer breiten ViDA-Umsetzung</h3>
<p>Am 26. Januar 2026 veröffentlichte das niederländische Finanzministerium ein unabhängiges Gutachten darüber, wie die Niederlande die E-Rechnungs- und Meldepflicht-Säule der EU-Initiative VAT in the Digital Age (ViDA) umsetzen sollten. Das Gutachten wägt zwei Szenarien ab: ViDA-A, strikt beschränkt auf das grenzüberschreitende EU-B2B-Minimum, und ViDA-B, das dieselben Pflichten auf inländische B2B-Umsätze ausweitet.</p>
<p>Gestützt auf Stakeholder-Interviews, eine Vergleichsstudie von sechs EU-Ländern und eine Kosten-Nutzen-Analyse, ist die Schlussfolgerung des Gutachtens eindeutig: Es empfiehlt ViDA-B, aufgebaut auf einer einzigen vorgeschriebenen Infrastruktur — Peppol —, um Standardisierung und Interoperabilität zu maximieren. Das Gutachten verweist auch auf die Erfahrung Italiens, wo eine vergleichbare Clearance-artige Pflicht zu einer erheblichen Verringerung der nationalen Umsatzsteuerlücke beigetragen haben soll.</p>
<p>Das Gutachten ist ausdrücklich beratender Natur — eine Studie eines Dritten, keine Regierungspolitik —, setzt aber die Bedingungen für die Debatte, die das Kabinett nun entscheiden muss. Eine formelle Regierungsposition wurde innerhalb weniger Monate erwartet, was die Niederlande auf einen ähnlichen Kurs wie Belgien, Frankreich und Italien bringt, die sich alle für umfassende inländische Pflichten statt des EU-Minimums entschieden haben.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-02-01-netherlands-ey-report-published', 'fr', 'Un rapport indépendant recommande au ministère néerlandais des Finances d''élargir ViDA', 'Une étude consultative commandée, publiée par le ministère des Finances, recommande d''étendre la facturation électronique obligatoire au-delà du minimum transfrontalier de l''UE afin de couvrir aussi les transactions B2B nationales, sur la base de Peppol.', '<h3>🇳🇱 Un rapport indépendant recommande au ministère néerlandais des Finances d''élargir ViDA</h3>
<p>Le 26 janvier 2026, le ministère néerlandais des Finances a publié un rapport consultatif indépendant examinant comment les Pays-Bas devraient mettre en œuvre le volet facturation électronique et déclaration numérique de l''initiative européenne TVA à l''ère numérique (ViDA). Le rapport pèse deux scénarios : ViDA-A, strictement limité au minimum B2B transfrontalier de l''UE, et ViDA-B, étendant les mêmes obligations aux transactions B2B nationales.</p>
<p>S''appuyant sur des entretiens avec les parties prenantes, une étude comparative de six pays de l''UE et une analyse coûts-avantages, la conclusion du rapport est sans ambiguïté : il recommande ViDA-B, construit sur une infrastructure unique prescrite — Peppol — afin de maximiser la standardisation et l''interopérabilité. Le rapport souligne également l''expérience de l''Italie, où une obligation de type validation préalable comparable aurait sensiblement réduit l''écart de TVA national.</p>
<p>Le rapport est explicitement consultatif — une étude tierce, non une politique gouvernementale — mais il fixe les termes du débat que le cabinet doit désormais trancher. Une position gouvernementale formelle était attendue dans les mois suivants, plaçant les Pays-Bas sur une trajectoire similaire à celle de la Belgique, de la France et de l''Italie, qui ont toutes opté pour des obligations nationales complètes plutôt que le minimum de l''UE.</p>');

