-- Greece story arc continued: stories 2-3 (migration 243 has story 1).

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-03-02-greece-b2b-phase1-live', '2026-03-02', '2026-03', 'Phase 1 of Greece''s domestic B2B e-invoicing mandate takes effect for businesses with annual revenue over €1 million, under an EU derogation permitting Greece to require clearance ahead of the general ViDA timeline.', '<h3>🇬🇷 Greece''s domestic B2B e-invoicing mandate goes live for large businesses</h3>
<p>Structured B2B e-invoicing became mandatory today for Greek businesses with annual revenue above €1 million — Phase 1 of a domestic mandate that will extend to every remaining business from 1 October 2026. The launch was delayed by one month from an original 1 February 2026 target, with AADE opting for a two-month soft-launch period through 3 May 2026, during which isolated technical failures won''t trigger the full penalty framework.</p>
<p>The mandate rests on an EU derogation: Council Implementing Decision (EU) 2025/502 authorises Greece to depart from Articles 218 and 232 of the VAT Directive, permitting a domestic clearance-style requirement ahead of ViDA''s general 2030 cross-border timeline. Invoices are validated through the existing myDATA system — the same platform that has required real-time reporting since 2021 — and assigned a MARK before they have legal effect.</p>
<p>Notably, the mandate''s scope has real edges: it covers domestic B2B transactions and B2B sales to non-EU entities, but intra-EU B2B invoicing remains optional for now. A Greek business selling to a German counterpart isn''t yet required to e-invoice that specific transaction, even though its domestic sales already are. Compliance routes include certified commercial e-invoicing providers, AADE''s free "Timologio" application, or direct ERP integration via the myDATA REST API.</p>', 'https://www.vatcalc.com/greece/greece-mydata-e-book-and-e-invoices-update/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-03-02-greece-b2b-phase1-live', id FROM countries WHERE name_en = 'Greece';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-03-02-greece-b2b-phase1-live', 'en', 'Greece''s domestic B2B e-invoicing mandate goes live for large businesses', 'Phase 1 of Greece''s domestic B2B e-invoicing mandate takes effect for businesses with annual revenue over €1 million, under an EU derogation permitting Greece to require clearance ahead of the general ViDA timeline.', '<h3>🇬🇷 Greece''s domestic B2B e-invoicing mandate goes live for large businesses</h3>
<p>Structured B2B e-invoicing became mandatory today for Greek businesses with annual revenue above €1 million — Phase 1 of a domestic mandate that will extend to every remaining business from 1 October 2026. The launch was delayed by one month from an original 1 February 2026 target, with AADE opting for a two-month soft-launch period through 3 May 2026, during which isolated technical failures won''t trigger the full penalty framework.</p>
<p>The mandate rests on an EU derogation: Council Implementing Decision (EU) 2025/502 authorises Greece to depart from Articles 218 and 232 of the VAT Directive, permitting a domestic clearance-style requirement ahead of ViDA''s general 2030 cross-border timeline. Invoices are validated through the existing myDATA system — the same platform that has required real-time reporting since 2021 — and assigned a MARK before they have legal effect.</p>
<p>Notably, the mandate''s scope has real edges: it covers domestic B2B transactions and B2B sales to non-EU entities, but intra-EU B2B invoicing remains optional for now. A Greek business selling to a German counterpart isn''t yet required to e-invoice that specific transaction, even though its domestic sales already are. Compliance routes include certified commercial e-invoicing providers, AADE''s free "Timologio" application, or direct ERP integration via the myDATA REST API.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-03-02-greece-b2b-phase1-live', 'es', 'El mandato griego de facturación electrónica B2B nacional entra en vigor para las grandes empresas', 'La Fase 1 del mandato griego de facturación electrónica B2B nacional entra en vigor para empresas con ingresos anuales superiores a 1 millón de euros, bajo una excepción de la UE que permite a Grecia exigir la compensación antes del calendario general de ViDA.', '<h3>🇬🇷 El mandato griego de facturación electrónica B2B nacional entra en vigor para las grandes empresas</h3>
<p>La facturación electrónica B2B estructurada se volvió obligatoria hoy para las empresas griegas con ingresos anuales superiores a 1 millón de euros — la Fase 1 de un mandato nacional que se ampliará a todas las empresas restantes a partir del 1 de octubre de 2026. El lanzamiento se retrasó un mes respecto al objetivo original del 1 de febrero de 2026, con AADE optando por un período de lanzamiento suave de dos meses hasta el 3 de mayo de 2026, durante el cual los fallos técnicos aislados no activarán el marco sancionador completo.</p>
<p>El mandato se apoya en una excepción de la UE: la Decisión de Ejecución (UE) 2025/502 del Consejo autoriza a Grecia a apartarse de los artículos 218 y 232 de la Directiva del IVA, permitiendo un requisito de compensación nacional antes del calendario general de ViDA de 2030 para el transfronterizo. Las facturas se validan a través del sistema myDATA ya existente — la misma plataforma que exige el reporte en tiempo real desde 2021 — y reciben una MARK antes de tener efecto legal.</p>
<p>Cabe destacar que el alcance del mandato tiene límites reales: cubre las transacciones B2B nacionales y las ventas B2B a entidades no pertenecientes a la UE, pero la facturación B2B intracomunitaria sigue siendo opcional por ahora. Una empresa griega que vende a una contraparte alemana aún no está obligada a facturar electrónicamente esa transacción concreta, aunque sí lo estén ya sus ventas nacionales. Las vías de cumplimiento incluyen proveedores comerciales certificados de facturación electrónica, la aplicación gratuita "Timologio" de AADE, o la integración directa del ERP a través de la API REST de myDATA.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-03-02-greece-b2b-phase1-live', 'de', 'Griechenlands inländische B2B-E-Rechnungspflicht tritt für Großunternehmen in Kraft', 'Phase 1 der griechischen inländischen B2B-E-Rechnungspflicht tritt für Unternehmen mit einem Jahresumsatz über 1 Million Euro in Kraft, im Rahmen einer EU-Ausnahmeregelung, die es Griechenland erlaubt, ein Clearance-Verfahren vor dem allgemeinen ViDA-Zeitplan einzuführen.', '<h3>🇬🇷 Griechenlands inländische B2B-E-Rechnungspflicht tritt für Großunternehmen in Kraft</h3>
<p>Strukturierte B2B-E-Rechnung wurde heute für griechische Unternehmen mit einem Jahresumsatz über 1 Million Euro verpflichtend — Phase 1 einer inländischen Pflicht, die ab dem 1. Oktober 2026 auf alle verbleibenden Unternehmen ausgeweitet wird. Der Start verzögerte sich um einen Monat gegenüber dem ursprünglichen Ziel vom 1. Februar 2026, wobei sich die AADE für eine zweimonatige sanfte Einführungsphase bis zum 3. Mai 2026 entschied, in der isolierte technische Ausfälle nicht das volle Sanktionsregime auslösen.</p>
<p>Die Pflicht stützt sich auf eine EU-Ausnahmeregelung: Der Durchführungsbeschluss (EU) 2025/502 des Rates ermächtigt Griechenland, von den Artikeln 218 und 232 der Mehrwertsteuerrichtlinie abzuweichen, und erlaubt eine inländische Clearance-artige Anforderung vor dem allgemeinen grenzüberschreitenden ViDA-Zeitplan von 2030. Rechnungen werden über das bestehende myDATA-System validiert — dieselbe Plattform, die bereits seit 2021 die Echtzeitmeldung verlangt — und erhalten vor Rechtswirksamkeit ein MARK.</p>
<p>Bemerkenswert ist, dass die Pflicht echte Grenzen hat: Sie umfasst inländische B2B-Umsätze und B2B-Verkäufe an Nicht-EU-Einheiten, aber innergemeinschaftliches B2B bleibt vorerst freiwillig. Ein griechisches Unternehmen, das an einen deutschen Geschäftspartner verkauft, ist für diesen konkreten Umsatz noch nicht zur E-Rechnung verpflichtet, obwohl dies für seine inländischen Verkäufe bereits gilt. Zu den Erfüllungswegen zählen zertifizierte kommerzielle E-Rechnungsanbieter, die kostenlose Anwendung "Timologio" der AADE, oder die direkte ERP-Integration über die myDATA-REST-API.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-03-02-greece-b2b-phase1-live', 'fr', 'L''obligation grecque de facturation électronique B2B nationale entre en vigueur pour les grandes entreprises', 'La phase 1 de l''obligation grecque de facturation électronique B2B nationale entre en vigueur pour les entreprises dont le chiffre d''affaires annuel dépasse 1 million d''euros, dans le cadre d''une dérogation de l''UE permettant à la Grèce d''exiger une validation préalable avant le calendrier général de ViDA.', '<h3>🇬🇷 L''obligation grecque de facturation électronique B2B nationale entre en vigueur pour les grandes entreprises</h3>
<p>La facturation électronique B2B structurée est devenue obligatoire aujourd''hui pour les entreprises grecques dont le chiffre d''affaires annuel dépasse 1 million d''euros — phase 1 d''une obligation nationale qui s''étendra à toutes les entreprises restantes à partir du 1er octobre 2026. Le lancement a été retardé d''un mois par rapport à l''objectif initial du 1er février 2026, l''AADE ayant opté pour une période de lancement en douceur de deux mois jusqu''au 3 mai 2026, durant laquelle des défaillances techniques isolées ne déclencheront pas le régime de sanctions complet.</p>
<p>L''obligation repose sur une dérogation de l''UE : la décision d''exécution (UE) 2025/502 du Conseil autorise la Grèce à déroger aux articles 218 et 232 de la directive TVA, permettant une exigence nationale de type validation préalable avant le calendrier transfrontalier général de ViDA de 2030. Les factures sont validées via le système myDATA existant — la même plateforme qui exige la déclaration en temps réel depuis 2021 — et reçoivent une MARK avant d''avoir un effet juridique.</p>
<p>Notamment, le périmètre de l''obligation a des limites réelles : elle couvre les transactions B2B nationales et les ventes B2B à des entités hors UE, mais la facturation B2B intracommunautaire reste optionnelle pour l''instant. Une entreprise grecque vendant à une contrepartie allemande n''est pas encore tenue de facturer électroniquement cette transaction spécifique, même si ses ventes nationales le sont déjà. Les voies de conformité incluent des fournisseurs commerciaux certifiés de facturation électronique, l''application gratuite "Timologio" de l''AADE, ou l''intégration ERP directe via l''API REST myDATA.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-06-10-greece-b2b-phase2-approaching', '2026-06-10', '2026-06', 'With Phase 1 already in force for large businesses, Greece''s domestic B2B e-invoicing mandate is set to extend to every remaining business from 1 October 2026.', '<h3>🇬🇷 Greece''s B2B mandate prepares to reach every remaining business</h3>
<p>Four months after Phase 1 took effect for businesses above €1 million in annual revenue, Greece''s domestic B2B e-invoicing mandate is approaching its second and final phase: from 1 October 2026, every remaining Greek business — regardless of size — must issue structured B2B e-invoices validated through the myDATA system, with an adjustment period running through the end of the year.</p>
<p>For smaller businesses now facing the October deadline, the compliance landscape looks the same as it did for Phase 1''s larger companies: three routes are available — a certified commercial e-invoicing provider, AADE''s free "Timologio" application (a genuine no-cost option, unusual among the tracker''s clearance-model countries), or direct ERP integration via the myDATA REST API. The scope carve-out also remains unchanged — the mandate covers domestic B2B and B2B sales to non-EU entities, while intra-EU B2B invoicing stays optional pending any future alignment with the EU''s own 2030 ViDA cross-border timeline.</p>
<p>The stakes for getting this right are real: failure to issue a required e-invoice is treated in law as non-issuance of the invoice itself, carrying a fine of 50% of the VAT that would otherwise have resulted — a genuinely substantial, revenue-linked penalty rather than a routine administrative fee.</p>', 'https://rtcsuite.com/e-invoicing-greece/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-06-10-greece-b2b-phase2-approaching', id FROM countries WHERE name_en = 'Greece';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-10-greece-b2b-phase2-approaching', 'en', 'Greece''s B2B mandate prepares to reach every remaining business', 'With Phase 1 already in force for large businesses, Greece''s domestic B2B e-invoicing mandate is set to extend to every remaining business from 1 October 2026.', '<h3>🇬🇷 Greece''s B2B mandate prepares to reach every remaining business</h3>
<p>Four months after Phase 1 took effect for businesses above €1 million in annual revenue, Greece''s domestic B2B e-invoicing mandate is approaching its second and final phase: from 1 October 2026, every remaining Greek business — regardless of size — must issue structured B2B e-invoices validated through the myDATA system, with an adjustment period running through the end of the year.</p>
<p>For smaller businesses now facing the October deadline, the compliance landscape looks the same as it did for Phase 1''s larger companies: three routes are available — a certified commercial e-invoicing provider, AADE''s free "Timologio" application (a genuine no-cost option, unusual among the tracker''s clearance-model countries), or direct ERP integration via the myDATA REST API. The scope carve-out also remains unchanged — the mandate covers domestic B2B and B2B sales to non-EU entities, while intra-EU B2B invoicing stays optional pending any future alignment with the EU''s own 2030 ViDA cross-border timeline.</p>
<p>The stakes for getting this right are real: failure to issue a required e-invoice is treated in law as non-issuance of the invoice itself, carrying a fine of 50% of the VAT that would otherwise have resulted — a genuinely substantial, revenue-linked penalty rather than a routine administrative fee.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-10-greece-b2b-phase2-approaching', 'es', 'El mandato B2B de Grecia se prepara para alcanzar a todas las empresas restantes', 'Con la Fase 1 ya vigente para las grandes empresas, el mandato griego de facturación electrónica B2B nacional está a punto de ampliarse a todas las empresas restantes a partir del 1 de octubre de 2026.', '<h3>🇬🇷 El mandato B2B de Grecia se prepara para alcanzar a todas las empresas restantes</h3>
<p>Cuatro meses después de que la Fase 1 entrara en vigor para las empresas con más de 1 millón de euros de ingresos anuales, el mandato griego de facturación electrónica B2B nacional se acerca a su segunda y última fase: a partir del 1 de octubre de 2026, todas las empresas griegas restantes — independientemente de su tamaño — deberán emitir facturas electrónicas B2B estructuradas validadas a través del sistema myDATA, con un período de adaptación que se extiende hasta finales de año.</p>
<p>Para las empresas más pequeñas que ahora se enfrentan al plazo de octubre, el panorama de cumplimiento es el mismo que para las grandes empresas de la Fase 1: hay tres vías disponibles — un proveedor comercial certificado de facturación electrónica, la aplicación gratuita "Timologio" de AADE (una opción genuinamente gratuita, poco habitual entre los países de este rastreador con modelo de compensación), o la integración directa del ERP a través de la API REST de myDATA. La exclusión de alcance también se mantiene sin cambios — el mandato cubre el B2B nacional y las ventas B2B a entidades no pertenecientes a la UE, mientras que la facturación B2B intracomunitaria sigue siendo opcional a la espera de cualquier futura alineación con el propio calendario transfronterizo de ViDA de 2030 de la UE.</p>
<p>Lo que está en juego por hacerlo bien es real: no emitir una factura electrónica requerida se trata legalmente como la no emisión de la propia factura, con una multa del 50% del IVA que de otro modo hubiera resultado — una sanción genuinamente sustancial y vinculada a los ingresos, no una tarifa administrativa rutinaria.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-10-greece-b2b-phase2-approaching', 'de', 'Griechenlands B2B-Pflicht bereitet sich darauf vor, alle verbleibenden Unternehmen zu erfassen', 'Da Phase 1 für Großunternehmen bereits in Kraft ist, soll Griechenlands inländische B2B-E-Rechnungspflicht ab dem 1. Oktober 2026 auf alle verbleibenden Unternehmen ausgeweitet werden.', '<h3>🇬🇷 Griechenlands B2B-Pflicht bereitet sich darauf vor, alle verbleibenden Unternehmen zu erfassen</h3>
<p>Vier Monate nachdem Phase 1 für Unternehmen mit einem Jahresumsatz über 1 Million Euro in Kraft trat, nähert sich Griechenlands inländische B2B-E-Rechnungspflicht ihrer zweiten und letzten Phase: Ab dem 1. Oktober 2026 müssen alle verbleibenden griechischen Unternehmen — unabhängig von ihrer Größe — strukturierte, über das myDATA-System validierte B2B-E-Rechnungen ausstellen, mit einer bis Jahresende laufenden Anpassungsfrist.</p>
<p>Für kleinere Unternehmen, die nun vor der Oktober-Frist stehen, sieht die Compliance-Landschaft genauso aus wie zuvor für die größeren Unternehmen in Phase 1: Drei Wege stehen zur Verfügung — ein zertifizierter kommerzieller E-Rechnungsanbieter, die kostenlose Anwendung "Timologio" der AADE (eine echte kostenlose Option, ungewöhnlich unter den Clearance-Modell-Ländern dieses Trackers), oder die direkte ERP-Integration über die myDATA-REST-API. Auch die Umfangsausnahme bleibt unverändert — die Pflicht umfasst inländisches B2B und B2B-Verkäufe an Nicht-EU-Einheiten, während innergemeinschaftliches B2B freiwillig bleibt, bis zu einer künftigen Angleichung an den eigenen grenzüberschreitenden ViDA-Zeitplan der EU von 2030.</p>
<p>Was auf dem Spiel steht, ist real: Die Nichtausstellung einer erforderlichen E-Rechnung wird rechtlich als Nichtausstellung der Rechnung selbst behandelt und zieht eine Geldstrafe in Höhe von 50 % der andernfalls entstandenen Umsatzsteuer nach sich — eine echte, erhebliche, umsatzbezogene Sanktion und keine routinemäßige Verwaltungsgebühr.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-10-greece-b2b-phase2-approaching', 'fr', 'L''obligation B2B de la Grèce se prépare à atteindre toutes les entreprises restantes', 'Alors que la phase 1 est déjà en vigueur pour les grandes entreprises, l''obligation nationale de facturation électronique B2B de la Grèce doit s''étendre à toutes les entreprises restantes à partir du 1er octobre 2026.', '<h3>🇬🇷 L''obligation B2B de la Grèce se prépare à atteindre toutes les entreprises restantes</h3>
<p>Quatre mois après l''entrée en vigueur de la phase 1 pour les entreprises dont le chiffre d''affaires annuel dépasse 1 million d''euros, l''obligation nationale de facturation électronique B2B de la Grèce approche de sa deuxième et dernière phase : à partir du 1er octobre 2026, toutes les entreprises grecques restantes — quelle que soit leur taille — devront émettre des factures électroniques B2B structurées validées via le système myDATA, avec une période d''adaptation courant jusqu''à la fin de l''année.</p>
<p>Pour les petites entreprises désormais confrontées à l''échéance d''octobre, le paysage de conformité ressemble à celui des grandes entreprises de la phase 1 : trois voies sont disponibles — un fournisseur commercial certifié de facturation électronique, l''application gratuite "Timologio" de l''AADE (une option véritablement gratuite, inhabituelle parmi les pays à modèle de validation préalable de ce tracker), ou l''intégration ERP directe via l''API REST myDATA. L''exclusion de périmètre reste également inchangée — l''obligation couvre le B2B national et les ventes B2B à des entités hors UE, tandis que la facturation B2B intracommunautaire reste optionnelle en attendant tout futur alignement avec le propre calendrier transfrontalier ViDA de 2030 de l''UE.</p>
<p>Les enjeux d''une bonne mise en conformité sont réels : le défaut d''émission d''une facture électronique requise est traité juridiquement comme une non-émission de la facture elle-même, entraînant une amende de 50 % de la TVA qui en aurait autrement résulté — une sanction véritablement substantielle et liée au chiffre d''affaires, non des frais administratifs de routine.</p>');

