-- Oman: country row + name translations. Generated by
-- new_country_scaffold.py; INSERT OR IGNORE throughout (idempotent).

INSERT OR IGNORE INTO countries (code, name_en, region, slug, in_picker) VALUES ('OM', 'Oman', 'Middle East', 'oman', 1);

INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'en', 'Oman' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'es', 'Omán' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'de', 'Oman' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'fr', 'Oman' FROM countries WHERE code = 'OM';
