-- Oman: milestones + English translations. Generated in the same shape
-- as new_country_scaffold.py's output; INSERT OR IGNORE throughout
-- (idempotent). Oman's mandate is genuinely new -- announced October
-- 2025, rolling out in four dated phases via the OTA's Fawtara
-- platform through August 2028. Sourced from KPMG Oman Tax Flash
-- alerts (Oct 2025, Nov 2025, Mar 2026) and the OTA's own Tax Portal
-- (tms.taxoman.gov.om), cross-checked against each other for the
-- phase dates and taxpayer groups.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'om-specs', id, '2025-11-01', 1, 'https://kpmg.com/om/en/insights/2025/10/oman-to-implement-e-invoicing-from-august-2026-in-a-phased-manner.html', 0, '[]', NULL, 'none' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('om-specs', 'en', 'Oman Tax Authority launches the Fawtara e-invoicing programme', 'The Oman Tax Authority (OTA) published the technical specifications for a new national e-invoicing programme, Fawtara, beginning a structured rollout toward mandatory e-invoicing for VAT-registered businesses. This followed consultations that began the previous month and precedes a phased mandate running through 2028.', '["No action required yet unless the OTA has already identified your business as a Phase 1 or Phase 2 candidate", "Begin monitoring OTA communications if your business is among Oman''s largest taxpayers by size, transaction volume, or sector"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'om-asp', id, '2026-05-01', 0, 'https://tms.taxoman.gov.om/portal/service-provider', 1, '[{"label": "Oman Tax Authority — Service Provider Registration", "url": "https://tms.taxoman.gov.om/portal/service-provider"}]', NULL, 'none' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('om-asp', 'en', 'Accredited Service Provider (ASP) registration opens', 'The OTA opened its online registration portal for Accredited Service Providers (ASPs) — the certified intermediaries every business will need in order to issue and receive e-invoices under Fawtara''s Peppol five-corner model. This followed the December 2025 publication of ASP accreditation standards and the February 2026 launch of a developer/test portal.', '["If notified as a Phase 1 or Phase 2 taxpayer, begin evaluating and appointing an ASP", "Confirm your principal officer''s contact details are current with the OTA so phase notifications are received"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'om-phase1', id, '2026-08-01', 0, 'https://tms.taxoman.gov.om/portal/e-invoicing', 1, '[{"label": "Oman Tax Authority — e-Invoicing (Fawtara)", "url": "https://tms.taxoman.gov.om/portal/e-invoicing"}]', NULL, 'b2b' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('om-phase1', 'en', 'Phase 1 — Oman''s 100 largest taxpayers must issue and receive e-invoices', 'Mandatory e-invoicing via the Fawtara platform takes effect for roughly the 100 largest taxpayers selected by the OTA, based on business size, transaction volume, sector diversity, geographic distribution, and risk profile. Businesses outside this first wave may participate voluntarily. This is the first genuinely binding phase of Oman''s e-invoicing mandate.', '["Confirm directly with the OTA whether your business has been selected for Phase 1", "If selected, ensure your ASP integration and ERP systems are live before this date"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'om-phase2', id, '2027-02-01', 0, 'https://tms.taxoman.gov.om/portal/e-invoicing', 1, '[{"label": "Oman Tax Authority — e-Invoicing (Fawtara)", "url": "https://tms.taxoman.gov.om/portal/e-invoicing"}]', NULL, 'b2b' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('om-phase2', 'en', 'Phase 2 — remaining large taxpayers become mandatory', 'The mandate expands to all remaining large taxpayers not already covered by Phase 1, roughly six months after Phase 1''s go-live. Affected businesses were notified from March 2026 and asked to confirm their technical readiness via an OTA survey.', '["Check whether the OTA has notified your business as a Phase 2 taxpayer", "Complete any OTA technical-readiness survey by its stated deadline"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'om-phase3', id, '2027-08-01', 0, 'https://tms.taxoman.gov.om/portal/e-invoicing', 1, '[{"label": "Oman Tax Authority — e-Invoicing (Fawtara)", "url": "https://tms.taxoman.gov.om/portal/e-invoicing"}]', NULL, 'b2b' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('om-phase3', 'en', 'Phase 3 — all remaining VAT-registered taxpayers, including SMEs', 'Mandatory e-invoicing extends to every remaining VAT-registered taxpayer in Oman, including small and medium-sized enterprises, completing the domestic B2B rollout roughly one year after Phase 1 began.', '["Register with an OTA-Accredited Service Provider well ahead of this date if you haven''t already", "Budget for ERP or invoicing-software changes if your systems don''t yet support structured UBL 2.1 / PINT-OM output"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'om-phase4-b2g', id, '2028-08-01', 0, 'https://tms.taxoman.gov.om/portal/e-invoicing', 1, '[{"label": "Oman Tax Authority — e-Invoicing (Fawtara)", "url": "https://tms.taxoman.gov.om/portal/e-invoicing"}]', NULL, 'b2g_only' FROM countries WHERE code = 'OM';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('om-phase4-b2g', 'en', 'Phase 4 — mandatory e-invoicing completes for government-counterparty transactions', 'The rollout''s final phase brings government entities fully into scope as e-invoicing counterparties, one year after Phase 3, marking the completion of Oman''s phased Fawtara implementation.', '["If you supply Omani government entities, confirm your invoicing process covers government-counterparty transactions specifically by this date"]');
