-- Oman story arc: 3 stories tracking the Fawtara programme from its
-- October 2025 announcement through the run-up to the August 2026
-- Phase 1 go-live. Sourced from KPMG Oman Tax Flash alerts (Oct 2025,
-- Nov 2025, Mar 2026), VATupdate reporting, and the OTA's own Tax
-- Portal (tms.taxoman.gov.om), cross-checked against each other for
-- dates and the "100 largest taxpayers" figure (resolving an
-- inconsistent "153" figure seen in a single secondary source).

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-10-15-oman-fawtara-announced', '2025-10-15', '2025-10', 'The Oman Tax Authority published technical specifications for Fawtara, a new national e-invoicing programme built on a Peppol five-corner model, opening a phased rollout that runs through August 2028.', '<h3>🇴🇲 Oman announces Fawtara — a new e-invoicing programme built on Peppol''s five-corner model</h3>
<p>The Oman Tax Authority (OTA) published technical specifications for Fawtara, a new national e-invoicing programme, following consultations that had begun the previous month. Fawtara is designed around a decentralised, Peppol-style five-corner model rather than a centralised government clearance platform — invoices move directly between accredited service providers (ASPs) rather than through a single government portal, with the OTA receiving reporting data rather than clearing each invoice individually.</p>
<p>The announcement set out a structured, multi-year path to mandatory e-invoicing rather than a single flip-the-switch date: an initial phase covering only Oman''s largest taxpayers, followed by successive phases extending to all remaining VAT-registered businesses, and a final phase bringing government-counterparty transactions fully into scope. The OTA framed the phasing as designed to let its largest, most technically capable taxpayers validate the system before extending it economy-wide.</p>
<p>For businesses trading with or operating in Oman, this is the point at which Fawtara moved from concept to a dated, published programme. Nothing was mandatory yet as of this announcement, but the specification represented the technical foundation every later phase would build on.</p>', 'https://kpmg.com/om/en/insights/2025/10/oman-to-implement-e-invoicing-from-august-2026-in-a-phased-manner.html', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-10-15-oman-fawtara-announced', id FROM countries WHERE name_en = 'Oman';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-15-oman-fawtara-announced', 'en', 'Oman announces Fawtara — a new e-invoicing programme built on Peppol''s five-corner model', 'The Oman Tax Authority published technical specifications for Fawtara, a new national e-invoicing programme built on a Peppol five-corner model, opening a phased rollout that runs through August 2028.', '<h3>🇴🇲 Oman announces Fawtara — a new e-invoicing programme built on Peppol''s five-corner model</h3>
<p>The Oman Tax Authority (OTA) published technical specifications for Fawtara, a new national e-invoicing programme, following consultations that had begun the previous month. Fawtara is designed around a decentralised, Peppol-style five-corner model rather than a centralised government clearance platform — invoices move directly between accredited service providers (ASPs) rather than through a single government portal, with the OTA receiving reporting data rather than clearing each invoice individually.</p>
<p>The announcement set out a structured, multi-year path to mandatory e-invoicing rather than a single flip-the-switch date: an initial phase covering only Oman''s largest taxpayers, followed by successive phases extending to all remaining VAT-registered businesses, and a final phase bringing government-counterparty transactions fully into scope. The OTA framed the phasing as designed to let its largest, most technically capable taxpayers validate the system before extending it economy-wide.</p>
<p>For businesses trading with or operating in Oman, this is the point at which Fawtara moved from concept to a dated, published programme. Nothing was mandatory yet as of this announcement, but the specification represented the technical foundation every later phase would build on.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-15-oman-fawtara-announced', 'es', 'Omán anuncia Fawtara — un nuevo programa de facturación electrónica basado en el modelo de cinco esquinas de Peppol', 'La Autoridad Tributaria de Omán publicó especificaciones técnicas para Fawtara, un nuevo programa nacional de facturación electrónica basado en un modelo Peppol de cinco esquinas, iniciando un despliegue por fases que se extiende hasta agosto de 2028.', '<h3>🇴🇲 Omán anuncia Fawtara — un nuevo programa de facturación electrónica basado en el modelo de cinco esquinas de Peppol</h3>
<p>La Autoridad Tributaria de Omán (OTA) publicó las especificaciones técnicas de Fawtara, un nuevo programa nacional de facturación electrónica, tras consultas iniciadas el mes anterior. Fawtara está diseñado en torno a un modelo descentralizado de cinco esquinas al estilo Peppol, en lugar de una plataforma centralizada de validación gubernamental — las facturas circulan directamente entre proveedores de servicios acreditados (ASP) en lugar de a través de un único portal gubernamental, y la OTA recibe datos de reporte en lugar de validar cada factura individualmente.</p>
<p>El anuncio estableció una vía estructurada y plurianual hacia la facturación electrónica obligatoria, en lugar de una única fecha de activación: una fase inicial que cubre solo a los mayores contribuyentes de Omán, seguida de fases sucesivas que se extienden a todas las empresas restantes registradas a efectos del IVA, y una fase final que incorpora plenamente las transacciones con contrapartes gubernamentales. La OTA planteó esta fasificación como un modo de permitir que sus mayores contribuyentes, los más capacitados técnicamente, validasen el sistema antes de extenderlo a toda la economía.</p>
<p>Para las empresas que comercian con Omán u operan allí, este es el momento en que Fawtara pasó de ser un concepto a un programa fechado y publicado. Nada era aún obligatorio en el momento de este anuncio, pero la especificación representó la base técnica sobre la que se construiría cada fase posterior.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-15-oman-fawtara-announced', 'de', 'Oman kündigt Fawtara an — ein neues E-Rechnungsprogramm nach Peppols Fünf-Ecken-Modell', 'Die omanische Steuerbehörde veröffentlichte technische Spezifikationen für Fawtara, ein neues nationales E-Rechnungsprogramm nach einem Peppol-Fünf-Ecken-Modell, und eröffnete damit eine stufenweise Einführung, die bis August 2028 läuft.', '<h3>🇴🇲 Oman kündigt Fawtara an — ein neues E-Rechnungsprogramm nach Peppols Fünf-Ecken-Modell</h3>
<p>Die omanische Steuerbehörde (OTA) veröffentlichte technische Spezifikationen für Fawtara, ein neues nationales E-Rechnungsprogramm, nach Konsultationen, die im Vormonat begonnen hatten. Fawtara ist um ein dezentrales Fünf-Ecken-Modell nach Peppol-Art konzipiert statt um eine zentrale staatliche Clearing-Plattform — Rechnungen bewegen sich direkt zwischen akkreditierten Dienstleistern (ASPs) statt über ein einziges Regierungsportal, wobei die OTA Meldedaten erhält, statt jede Rechnung einzeln zu prüfen.</p>
<p>Die Ankündigung legte einen strukturierten, mehrjährigen Weg zur verpflichtenden E-Rechnung fest statt eines einzigen Umschalttermins: eine erste Phase, die nur Omans größte Steuerzahler erfasst, gefolgt von aufeinanderfolgenden Phasen, die sich auf alle verbleibenden umsatzsteuerpflichtigen Unternehmen ausweiten, sowie eine Abschlussphase, die Transaktionen mit staatlichen Gegenparteien vollständig einbezieht. Die OTA begründete die Staffelung damit, ihren größten, technisch fähigsten Steuerzahlern zu erlauben, das System zu validieren, bevor es auf die gesamte Wirtschaft ausgeweitet wird.</p>
<p>Für Unternehmen, die mit Oman Handel treiben oder dort tätig sind, ist dies der Zeitpunkt, an dem Fawtara vom Konzept zu einem terminierten, veröffentlichten Programm wurde. Zum Zeitpunkt dieser Ankündigung war noch nichts verpflichtend, doch die Spezifikation bildete die technische Grundlage, auf der jede spätere Phase aufbauen würde.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-15-oman-fawtara-announced', 'fr', 'Oman annonce Fawtara — un nouveau programme de facturation électronique fondé sur le modèle Peppol à cinq coins', 'L''Autorité fiscale omanaise a publié les spécifications techniques de Fawtara, un nouveau programme national de facturation électronique fondé sur un modèle Peppol à cinq coins, ouvrant un déploiement par phases qui s''étend jusqu''en août 2028.', '<h3>🇴🇲 Oman annonce Fawtara — un nouveau programme de facturation électronique fondé sur le modèle Peppol à cinq coins</h3>
<p>L''Autorité fiscale omanaise (OTA) a publié les spécifications techniques de Fawtara, un nouveau programme national de facturation électronique, à la suite de consultations entamées le mois précédent. Fawtara est conçu autour d''un modèle décentralisé à cinq coins de type Peppol plutôt qu''une plateforme gouvernementale centralisée de validation — les factures circulent directement entre prestataires de services accrédités (ASP) plutôt que via un portail gouvernemental unique, l''OTA recevant des données de déclaration plutôt que de valider chaque facture individuellement.</p>
<p>L''annonce a fixé une trajectoire structurée et pluriannuelle vers la facturation électronique obligatoire plutôt qu''une date d''activation unique : une première phase ne couvrant que les plus grands contribuables d''Oman, suivie de phases successives s''étendant à toutes les entreprises restantes assujetties à la TVA, et une phase finale intégrant pleinement les transactions avec des contreparties gouvernementales. L''OTA a présenté cette progression par phases comme un moyen de permettre à ses plus grands contribuables, les plus aptes techniquement, de valider le système avant de l''étendre à l''ensemble de l''économie.</p>
<p>Pour les entreprises commerçant avec Oman ou y opérant, c''est le moment où Fawtara est passé du concept à un programme daté et publié. Rien n''était encore obligatoire au moment de cette annonce, mais la spécification représentait le socle technique sur lequel chaque phase ultérieure allait s''appuyer.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-05-20-oman-asp-portal-opens', '2026-05-20', '2026-05', 'The OTA opened online registration for Accredited Service Providers (ASPs) — the certified intermediaries every business will need to issue and receive e-invoices under Fawtara''s Peppol five-corner model.', '<h3>🇴🇲 Oman opens Accredited Service Provider registration ahead of Phase 1</h3>
<p>The Oman Tax Authority opened its online registration portal for Accredited Service Providers (ASPs), the certified intermediaries that businesses will rely on to issue and receive e-invoices once Fawtara''s mandate takes effect. Registration followed the OTA''s publication of ASP accreditation standards the previous December and the launch of a developer/test portal in February 2026, giving prospective ASPs several months to prepare before registration itself opened.</p>
<p>Because Fawtara uses a decentralised five-corner model rather than a single government clearance platform, ASPs sit at the centre of how the mandate actually works in practice: a taxpayer''s own system (corner 1) hands an invoice to its ASP (corner 2), which exchanges it with the recipient''s ASP (corner 4) before it reaches the recipient (corner 5), with the OTA (corner 3) receiving reporting data throughout. Getting this layer right was a prerequisite for the OTA to credibly hold to its August 2026 Phase 1 date.</p>
<p>For businesses expecting to be part of Phase 1 — provisionally Oman''s roughly 100 largest taxpayers — ASP registration opening is the practical signal that the technical plumbing needed for the mandate is now in place, and that appointing an ASP is no longer something to defer.</p>', 'https://tms.taxoman.gov.om/portal/service-provider', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-05-20-oman-asp-portal-opens', id FROM countries WHERE name_en = 'Oman';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-05-20-oman-asp-portal-opens', 'en', 'Oman opens Accredited Service Provider registration ahead of Phase 1', 'The OTA opened online registration for Accredited Service Providers (ASPs) — the certified intermediaries every business will need to issue and receive e-invoices under Fawtara''s Peppol five-corner model.', '<h3>🇴🇲 Oman opens Accredited Service Provider registration ahead of Phase 1</h3>
<p>The Oman Tax Authority opened its online registration portal for Accredited Service Providers (ASPs), the certified intermediaries that businesses will rely on to issue and receive e-invoices once Fawtara''s mandate takes effect. Registration followed the OTA''s publication of ASP accreditation standards the previous December and the launch of a developer/test portal in February 2026, giving prospective ASPs several months to prepare before registration itself opened.</p>
<p>Because Fawtara uses a decentralised five-corner model rather than a single government clearance platform, ASPs sit at the centre of how the mandate actually works in practice: a taxpayer''s own system (corner 1) hands an invoice to its ASP (corner 2), which exchanges it with the recipient''s ASP (corner 4) before it reaches the recipient (corner 5), with the OTA (corner 3) receiving reporting data throughout. Getting this layer right was a prerequisite for the OTA to credibly hold to its August 2026 Phase 1 date.</p>
<p>For businesses expecting to be part of Phase 1 — provisionally Oman''s roughly 100 largest taxpayers — ASP registration opening is the practical signal that the technical plumbing needed for the mandate is now in place, and that appointing an ASP is no longer something to defer.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-05-20-oman-asp-portal-opens', 'es', 'Omán abre el registro de Proveedores de Servicios Acreditados antes de la Fase 1', 'La OTA abrió el registro en línea para los Proveedores de Servicios Acreditados (ASP) — los intermediarios certificados que toda empresa necesitará para emitir y recibir facturas electrónicas bajo el modelo Peppol de cinco esquinas de Fawtara.', '<h3>🇴🇲 Omán abre el registro de Proveedores de Servicios Acreditados antes de la Fase 1</h3>
<p>La Autoridad Tributaria de Omán abrió su portal de registro en línea para los Proveedores de Servicios Acreditados (ASP), los intermediarios certificados en los que las empresas se apoyarán para emitir y recibir facturas electrónicas una vez que entre en vigor el mandato de Fawtara. El registro siguió a la publicación por parte de la OTA de las normas de acreditación de ASP en diciembre anterior y al lanzamiento de un portal de desarrolladores/pruebas en febrero de 2026, lo que dio a los futuros ASP varios meses para prepararse antes de que se abriera el propio registro.</p>
<p>Dado que Fawtara utiliza un modelo descentralizado de cinco esquinas en lugar de una única plataforma gubernamental de validación, los ASP están en el centro de cómo funciona realmente el mandato en la práctica: el propio sistema de un contribuyente (esquina 1) entrega una factura a su ASP (esquina 2), que la intercambia con el ASP del destinatario (esquina 4) antes de que llegue al destinatario (esquina 5), mientras la OTA (esquina 3) recibe datos de reporte durante todo el proceso. Conseguir que esta capa funcionase era un requisito previo para que la OTA pudiera mantener de forma creíble su fecha de la Fase 1 en agosto de 2026.</p>
<p>Para las empresas que esperan formar parte de la Fase 1 — provisionalmente, los aproximadamente 100 mayores contribuyentes de Omán — la apertura del registro de ASP es la señal práctica de que la infraestructura técnica necesaria para el mandato ya está en marcha, y que designar un ASP ya no es algo que se pueda posponer.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-05-20-oman-asp-portal-opens', 'de', 'Oman eröffnet Registrierung für akkreditierte Dienstleister vor Phase 1', 'Die OTA eröffnete die Online-Registrierung für akkreditierte Dienstleister (ASPs) — die zertifizierten Vermittler, die jedes Unternehmen benötigt, um E-Rechnungen unter Fawtaras Peppol-Fünf-Ecken-Modell auszustellen und zu empfangen.', '<h3>🇴🇲 Oman eröffnet Registrierung für akkreditierte Dienstleister vor Phase 1</h3>
<p>Die omanische Steuerbehörde eröffnete ihr Online-Registrierungsportal für akkreditierte Dienstleister (ASPs), die zertifizierten Vermittler, auf die sich Unternehmen verlassen werden, um E-Rechnungen auszustellen und zu empfangen, sobald Fawtaras Pflicht in Kraft tritt. Die Registrierung folgte auf die Veröffentlichung der ASP-Akkreditierungsstandards durch die OTA im Dezember zuvor und die Einführung eines Entwickler-/Testportals im Februar 2026, was künftigen ASPs mehrere Monate zur Vorbereitung gab, bevor die Registrierung selbst eröffnet wurde.</p>
<p>Da Fawtara ein dezentrales Fünf-Ecken-Modell statt einer einzigen staatlichen Clearing-Plattform verwendet, stehen ASPs im Zentrum dessen, wie die Pflicht in der Praxis tatsächlich funktioniert: Das eigene System eines Steuerzahlers (Ecke 1) übergibt eine Rechnung an seinen ASP (Ecke 2), der sie mit dem ASP des Empfängers (Ecke 4) austauscht, bevor sie den Empfänger erreicht (Ecke 5), während die OTA (Ecke 3) durchgehend Meldedaten erhält. Diese Ebene richtig hinzubekommen, war eine Voraussetzung dafür, dass die OTA glaubwürdig an ihrem Phase-1-Termin im August 2026 festhalten konnte.</p>
<p>Für Unternehmen, die erwarten, Teil von Phase 1 zu sein — vorläufig Omans rund 100 größte Steuerzahler —, ist die Eröffnung der ASP-Registrierung das praktische Signal, dass die für die Pflicht nötige technische Infrastruktur nun vorhanden ist und die Benennung eines ASP nicht länger aufgeschoben werden sollte.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-05-20-oman-asp-portal-opens', 'fr', 'Oman ouvre l''enregistrement des prestataires de services accrédités avant la Phase 1', 'L''OTA a ouvert l''enregistrement en ligne des prestataires de services accrédités (ASP) — les intermédiaires certifiés dont chaque entreprise aura besoin pour émettre et recevoir des factures électroniques dans le modèle Peppol à cinq coins de Fawtara.', '<h3>🇴🇲 Oman ouvre l''enregistrement des prestataires de services accrédités avant la Phase 1</h3>
<p>L''Autorité fiscale omanaise a ouvert son portail d''enregistrement en ligne pour les prestataires de services accrédités (ASP), les intermédiaires certifiés sur lesquels les entreprises s''appuieront pour émettre et recevoir des factures électroniques une fois l''obligation Fawtara entrée en vigueur. Cet enregistrement a suivi la publication par l''OTA des normes d''accréditation des ASP en décembre précédent et le lancement d''un portail développeur/test en février 2026, laissant plusieurs mois aux futurs ASP pour se préparer avant l''ouverture de l''enregistrement lui-même.</p>
<p>Comme Fawtara utilise un modèle décentralisé à cinq coins plutôt qu''une plateforme gouvernementale unique de validation, les ASP sont au cœur du fonctionnement pratique de l''obligation : le système propre d''un contribuable (coin 1) remet une facture à son ASP (coin 2), qui l''échange avec l''ASP du destinataire (coin 4) avant qu''elle n''atteigne le destinataire (coin 5), l''OTA (coin 3) recevant des données de déclaration tout au long du processus. Réussir cette couche était un préalable pour que l''OTA puisse tenir de manière crédible sa date de Phase 1 d''août 2026.</p>
<p>Pour les entreprises qui s''attendent à faire partie de la Phase 1 — provisoirement les quelque 100 plus grands contribuables d''Oman — l''ouverture de l''enregistrement des ASP est le signal concret que l''infrastructure technique nécessaire à l''obligation est désormais en place, et que la désignation d''un ASP n''est plus quelque chose à différer.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-06-18-oman-phase1-scope-confirmed', '2026-06-18', '2026-06', 'The OTA confirmed Phase 1 of Fawtara will begin with roughly Oman''s 100 largest taxpayers on 1 August 2026, with voluntary participation open to any other business that wants to start early.', '<h3>🇴🇲 Oman confirms Phase 1 scope: around 100 largest taxpayers, mandatory from August 2026</h3>
<p>With roughly six weeks to go before Fawtara''s first mandatory phase, the OTA confirmed the scope of Phase 1: approximately 100 taxpayers, selected based on business size, transaction volume, sector diversity, geographic distribution, and risk profile, rather than a simple revenue-threshold cutoff. This resolved earlier ambiguity in some secondary reporting — a figure of 153 businesses had circulated in at least one industry summary — with KPMG''s own advisory alerts and the OTA''s messaging both consistently pointing to roughly 100.</p>
<p>The confirmation also clarified that participation isn''t limited to the selected group: any VAT-registered business that wants to start issuing and receiving e-invoices via an Accredited Service Provider ahead of its own mandatory phase may do so voluntarily. For businesses anticipating inclusion in Phase 2 (expected around February 2027) or Phase 3 (expected around August 2027), early voluntary adoption offers a way to iron out ASP integration issues well before a compliance deadline applies.</p>
<p>Businesses uncertain whether they fall inside the initial ~100 should confirm their status directly with the OTA rather than relying on self-assessment against the selection criteria, since the final list reflects the OTA''s own internal risk and size analysis rather than a published threshold businesses can check themselves against.</p>', 'https://www.vatupdate.com/2026/06/oman-tax-authority-to-launch-e-invoicing-for-top-100-taxpayers/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-06-18-oman-phase1-scope-confirmed', id FROM countries WHERE name_en = 'Oman';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-18-oman-phase1-scope-confirmed', 'en', 'Oman confirms Phase 1 scope: around 100 largest taxpayers, mandatory from August 2026', 'The OTA confirmed Phase 1 of Fawtara will begin with roughly Oman''s 100 largest taxpayers on 1 August 2026, with voluntary participation open to any other business that wants to start early.', '<h3>🇴🇲 Oman confirms Phase 1 scope: around 100 largest taxpayers, mandatory from August 2026</h3>
<p>With roughly six weeks to go before Fawtara''s first mandatory phase, the OTA confirmed the scope of Phase 1: approximately 100 taxpayers, selected based on business size, transaction volume, sector diversity, geographic distribution, and risk profile, rather than a simple revenue-threshold cutoff. This resolved earlier ambiguity in some secondary reporting — a figure of 153 businesses had circulated in at least one industry summary — with KPMG''s own advisory alerts and the OTA''s messaging both consistently pointing to roughly 100.</p>
<p>The confirmation also clarified that participation isn''t limited to the selected group: any VAT-registered business that wants to start issuing and receiving e-invoices via an Accredited Service Provider ahead of its own mandatory phase may do so voluntarily. For businesses anticipating inclusion in Phase 2 (expected around February 2027) or Phase 3 (expected around August 2027), early voluntary adoption offers a way to iron out ASP integration issues well before a compliance deadline applies.</p>
<p>Businesses uncertain whether they fall inside the initial ~100 should confirm their status directly with the OTA rather than relying on self-assessment against the selection criteria, since the final list reflects the OTA''s own internal risk and size analysis rather than a published threshold businesses can check themselves against.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-18-oman-phase1-scope-confirmed', 'es', 'Omán confirma el alcance de la Fase 1: alrededor de 100 mayores contribuyentes, obligatorio desde agosto de 2026', 'La OTA confirmó que la Fase 1 de Fawtara comenzará con aproximadamente los 100 mayores contribuyentes de Omán el 1 de agosto de 2026, con participación voluntaria abierta a cualquier otra empresa que desee empezar antes.', '<h3>🇴🇲 Omán confirma el alcance de la Fase 1: alrededor de 100 mayores contribuyentes, obligatorio desde agosto de 2026</h3>
<p>Con aproximadamente seis semanas por delante antes de la primera fase obligatoria de Fawtara, la OTA confirmó el alcance de la Fase 1: aproximadamente 100 contribuyentes, seleccionados en función del tamaño de la empresa, el volumen de transacciones, la diversidad sectorial, la distribución geográfica y el perfil de riesgo, en lugar de un simple umbral de ingresos. Esto resolvió una ambigüedad anterior en algunos informes secundarios — una cifra de 153 empresas había circulado en al menos un resumen del sector — ya que tanto las alertas de asesoría propias de KPMG como los mensajes de la OTA apuntaban de forma consistente a alrededor de 100.</p>
<p>La confirmación también aclaró que la participación no se limita al grupo seleccionado: cualquier empresa registrada a efectos del IVA que desee comenzar a emitir y recibir facturas electrónicas a través de un Proveedor de Servicios Acreditado antes de su propia fase obligatoria puede hacerlo de forma voluntaria. Para las empresas que anticipan su inclusión en la Fase 2 (prevista en torno a febrero de 2027) o la Fase 3 (prevista en torno a agosto de 2027), la adopción voluntaria temprana ofrece una forma de resolver los problemas de integración con el ASP mucho antes de que se aplique un plazo de cumplimiento.</p>
<p>Las empresas que no estén seguras de si se encuentran dentro del grupo inicial de ~100 deben confirmar su situación directamente con la OTA en lugar de basarse en una autoevaluación frente a los criterios de selección, ya que la lista final refleja el propio análisis interno de riesgo y tamaño de la OTA, no un umbral publicado que las empresas puedan verificar por sí mismas.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-18-oman-phase1-scope-confirmed', 'de', 'Oman bestätigt Umfang von Phase 1: rund 100 größte Steuerzahler, verpflichtend ab August 2026', 'Die OTA bestätigte, dass Phase 1 von Fawtara am 1. August 2026 mit rund 100 der größten Steuerzahler Omans beginnt, mit freiwilliger Teilnahme für jedes andere Unternehmen, das früher beginnen möchte.', '<h3>🇴🇲 Oman bestätigt Umfang von Phase 1: rund 100 größte Steuerzahler, verpflichtend ab August 2026</h3>
<p>Rund sechs Wochen vor der ersten verpflichtenden Phase von Fawtara bestätigte die OTA den Umfang von Phase 1: etwa 100 Steuerzahler, ausgewählt anhand von Unternehmensgröße, Transaktionsvolumen, Branchenvielfalt, geografischer Verteilung und Risikoprofil, statt eines einfachen Umsatzschwellenwerts. Dies löste eine frühere Unklarheit in einigen Sekundärberichten auf — eine Zahl von 153 Unternehmen war in mindestens einer Branchenübersicht kursiert —, da sowohl KPMGs eigene Beratungshinweise als auch die Kommunikation der OTA übereinstimmend auf rund 100 verwiesen.</p>
<p>Die Bestätigung stellte zudem klar, dass die Teilnahme nicht auf die ausgewählte Gruppe beschränkt ist: Jedes umsatzsteuerpflichtige Unternehmen, das vor seiner eigenen verpflichtenden Phase beginnen möchte, E-Rechnungen über einen akkreditierten Dienstleister auszustellen und zu empfangen, kann dies freiwillig tun. Für Unternehmen, die mit einer Einbeziehung in Phase 2 (voraussichtlich ab Februar 2027) oder Phase 3 (voraussichtlich ab August 2027) rechnen, bietet die frühzeitige freiwillige Teilnahme eine Möglichkeit, ASP-Integrationsprobleme lange vor einer verbindlichen Frist zu klären.</p>
<p>Unternehmen, die unsicher sind, ob sie zu den anfänglichen ~100 gehören, sollten ihren Status direkt bei der OTA bestätigen, statt sich auf eine Selbsteinschätzung anhand der Auswahlkriterien zu verlassen, da die endgültige Liste die eigene interne Risiko- und Größenanalyse der OTA widerspiegelt und keinen veröffentlichten Schwellenwert, den Unternehmen selbst prüfen könnten.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-06-18-oman-phase1-scope-confirmed', 'fr', 'Oman confirme le périmètre de la Phase 1 : environ 100 plus grands contribuables, obligatoire dès août 2026', 'L''OTA a confirmé que la Phase 1 de Fawtara débutera avec environ les 100 plus grands contribuables d''Oman le 1er août 2026, avec une participation volontaire ouverte à toute autre entreprise souhaitant commencer plus tôt.', '<h3>🇴🇲 Oman confirme le périmètre de la Phase 1 : environ 100 plus grands contribuables, obligatoire dès août 2026</h3>
<p>À environ six semaines de la première phase obligatoire de Fawtara, l''OTA a confirmé le périmètre de la Phase 1 : environ 100 contribuables, sélectionnés en fonction de la taille de l''entreprise, du volume de transactions, de la diversité sectorielle, de la répartition géographique et du profil de risque, plutôt qu''un simple seuil de chiffre d''affaires. Cela a résolu une ambiguïté antérieure dans certains rapports secondaires — un chiffre de 153 entreprises avait circulé dans au moins une synthèse sectorielle —, les alertes consultatives propres de KPMG et la communication de l''OTA pointant toutes deux de manière cohérente vers environ 100.</p>
<p>La confirmation a également précisé que la participation n''est pas limitée au groupe sélectionné : toute entreprise assujettie à la TVA souhaitant commencer à émettre et recevoir des factures électroniques via un prestataire de services accrédité avant sa propre phase obligatoire peut le faire volontairement. Pour les entreprises anticipant leur inclusion en Phase 2 (prévue vers février 2027) ou en Phase 3 (prévue vers août 2027), l''adoption volontaire précoce offre un moyen de résoudre les problèmes d''intégration ASP bien avant qu''une échéance de conformité ne s''applique.</p>
<p>Les entreprises incertaines de leur appartenance au groupe initial d''environ 100 devraient confirmer leur statut directement auprès de l''OTA plutôt que de se fier à une auto-évaluation par rapport aux critères de sélection, la liste finale reflétant la propre analyse interne de risque et de taille de l''OTA plutôt qu''un seuil publié que les entreprises pourraient vérifier elles-mêmes.</p>');
