-- Jordan: milestones + English translations. Generated in the same
-- shape as new_country_scaffold.py's output; INSERT OR IGNORE
-- throughout (idempotent). Jordan's JoFotara (National Electronic
-- Invoicing System) is the most mature mandate in this session's
-- Middle East evaluation -- voluntary since December 2022, with real
-- legal teeth (VAT-deduction invalidity, JOD fines) since April 2025.
-- Sourced from the Income and Sales Tax Department (ISTD, istd.gov.jo)
-- and cross-checked against VATupdate, EDICOM, and vatit.com/Flick
-- Network compliance guides, which independently agree on the phase
-- dates below.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'jo-launch', id, '2022-12-01', 1, 'https://portal.jofotara.gov.jo', 0, '[]', NULL, 'none' FROM countries WHERE code = 'JO';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('jo-launch', 'en', 'JoFotara — Jordan''s National Electronic Invoicing System — launches', 'The Income and Sales Tax Department (ISTD), together with the Ministry of Digital Economy and Entrepreneurship, launched JoFotara, a centralized e-invoicing platform, on a voluntary basis. Businesses could begin registering and integrating ahead of the mandatory phases that followed.', '["No action required yet unless the ISTD has already contacted your business about early registration", "Large taxpayers should begin monitoring ISTD communications, since Phase 1 onboarding follows within weeks"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'jo-phase1', id, '2023-01-01', 0, 'https://portal.jofotara.gov.jo', 1, '[{"label": "JoFotara — registration portal", "url": "https://portal.jofotara.gov.jo"}]', NULL, 'b2b' FROM countries WHERE code = 'JO';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('jo-phase1', 'en', 'Phase 1 — mandatory onboarding begins for large taxpayers', 'JoFotara registration and integration became mandatory for Jordan''s large taxpayers, the first group required to move off voluntary participation. Invoices are cleared through JoFotara in real time — a centralized clearance model, not post-audit reporting — with a QR code issued by the ISTD confirming validation.', '["If you''re a large taxpayer, confirm your registration and integration status with the ISTD directly", "Choose an integration route: direct API, the free JoFotara web portal, or a certified third-party service provider"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'jo-universal-registration', id, '2024-05-31', 0, 'https://portal.jofotara.gov.jo', 1, '[{"label": "JoFotara — registration portal", "url": "https://portal.jofotara.gov.jo"}]', NULL, 'b2b' FROM countries WHERE code = 'JO';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('jo-universal-registration', 'en', 'Universal registration deadline — all VAT-registered taxpayers', 'The onboarding wave that began with large taxpayers in Phase 1 completed: every VAT-registered business and individual (with no SME or small-business exemption) was required to be registered and integrated with JoFotara by this date, ahead of full legal enforcement the following year.', '["Confirm your business is registered with JoFotara if it wasn''t already covered under Phase 1", "SMEs and individual professionals (e.g. consultants) without in-house systems can register free via the JoFotara web portal"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'jo-phase2', id, '2025-04-01', 0, 'https://portal.jofotara.gov.jo', 1, '[{"label": "JoFotara — registration portal", "url": "https://portal.jofotara.gov.jo"}, {"label": "JoFotara — dashboard", "url": "https://dashboard.jofotara.gov.jo"}]', NULL, 'b2b' FROM countries WHERE code = 'JO';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('jo-phase2', 'en', 'Phase 2 — full enforcement across B2B, B2G, and B2C', 'JoFotara clearance became mandatory in practice, not just in registration, for all domestic B2B, B2G, and B2C transactions, plus cross-border trade for resident taxpayers. An invoice not transmitted through JoFotara is invalid for VAT input deduction and accounting purposes — the mandate''s real enforcement engine.', '["Verify every sales channel routes through JoFotara before issuing invoices, including POS and e-commerce", "Confirm your customers'' invoices carry a valid ISTD-issued QR code before relying on them for VAT deduction"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'jo-penalty-grace-end', id, '2025-05-31', 0, 'https://www.vatupdate.com/2025/07/17/jordans-e-invoicing-phase-2-mandatory-compliance-begins-april-1-2025/', 1, '[{"label": "JoFotara — registration portal", "url": "https://portal.jofotara.gov.jo"}]', NULL, 'b2b' FROM countries WHERE code = 'JO';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('jo-penalty-grace-end', 'en', 'Penalty waiver grace period expires', 'A grace period waiving accrued fines for businesses that registered late closed on this date. From here, the full penalty regime applies without exception: fines of roughly JOD 500 per violation under the Billing and Control Regulation, escalating to imprisonment (3-6 months) or fines up to JOD 1,000 for persistent non-compliance, plus exclusion from government tenders.', '["Register immediately if you haven''t already — the fine waiver is no longer available", "Review past invoices for JoFotara compliance gaps before an ISTD audit finds them first"]');
