-- Jordan story arc: 3 stories tracing JoFotara from mandatory Phase 1
-- onboarding through full legal enforcement. Sourced from VATupdate,
-- EDICOM, and vatit.com/Flick Network compliance guides, cross-checked
-- against each other for phase dates and penalty figures.

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2023-01-15-jordan-phase1-large-taxpayers', '2023-01-15', '2023-01', 'JoFotara registration and integration became mandatory for Jordan''s large taxpayers, the first group required to move off voluntary participation since the platform''s December 2022 launch.', '<h3>🇯🇴 Jordan''s JoFotara becomes mandatory for large taxpayers</h3>
<p>Barely a month after the Income and Sales Tax Department (ISTD) launched JoFotara — Jordan''s National Electronic Invoicing System — on a voluntary basis, mandatory onboarding began for the country''s large taxpayers. Invoices are now cleared through the platform in real time, with the ISTD issuing a QR code confirming validation before an invoice reaches its customer.</p>
<p>This is a genuine centralized clearance model, not a post-transaction reporting system: JoFotara sits between the seller and the buyer, checking each invoice as it moves. Large taxpayers can integrate directly via API, use the free JoFotara web portal, or work through a certified third-party service provider.</p>
<p>For large businesses not yet onboarded, this is the point where voluntary participation stopped being optional — and where the multi-year path toward universal, fully-enforced e-invoicing genuinely began.</p>', 'https://portal.jofotara.gov.jo', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2023-01-15-jordan-phase1-large-taxpayers', id FROM countries WHERE name_en = 'Jordan';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2023-01-15-jordan-phase1-large-taxpayers', 'en', 'Jordan''s JoFotara becomes mandatory for large taxpayers', 'JoFotara registration and integration became mandatory for Jordan''s large taxpayers, the first group required to move off voluntary participation since the platform''s December 2022 launch.', '<h3>🇯🇴 Jordan''s JoFotara becomes mandatory for large taxpayers</h3>
<p>Barely a month after the Income and Sales Tax Department (ISTD) launched JoFotara — Jordan''s National Electronic Invoicing System — on a voluntary basis, mandatory onboarding began for the country''s large taxpayers. Invoices are now cleared through the platform in real time, with the ISTD issuing a QR code confirming validation before an invoice reaches its customer.</p>
<p>This is a genuine centralized clearance model, not a post-transaction reporting system: JoFotara sits between the seller and the buyer, checking each invoice as it moves. Large taxpayers can integrate directly via API, use the free JoFotara web portal, or work through a certified third-party service provider.</p>
<p>For large businesses not yet onboarded, this is the point where voluntary participation stopped being optional — and where the multi-year path toward universal, fully-enforced e-invoicing genuinely began.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2023-01-15-jordan-phase1-large-taxpayers', 'es', 'JoFotara se vuelve obligatorio en Jordania para los grandes contribuyentes', 'El registro e integración con JoFotara se convirtió en obligatorio para los grandes contribuyentes de Jordania, el primer grupo que debía dejar de participar de forma voluntaria desde el lanzamiento de la plataforma en diciembre de 2022.', '<h3>🇯🇴 JoFotara se vuelve obligatorio en Jordania para los grandes contribuyentes</h3>
<p>Apenas un mes después de que el Departamento de Impuesto sobre la Renta y las Ventas (ISTD) lanzara JoFotara — el Sistema Nacional de Facturación Electrónica de Jordania — con carácter voluntario, comenzó la incorporación obligatoria para los grandes contribuyentes del país. Las facturas ahora se validan a través de la plataforma en tiempo real, y el ISTD emite un código QR que confirma la validación antes de que la factura llegue a su cliente.</p>
<p>Este es un verdadero modelo de validación centralizada, no un sistema de reporte posterior a la transacción: JoFotara se sitúa entre el vendedor y el comprador, verificando cada factura a medida que se mueve. Los grandes contribuyentes pueden integrarse directamente mediante API, usar el portal web gratuito de JoFotara, o trabajar a través de un proveedor de servicios externo certificado.</p>
<p>Para las grandes empresas que aún no se habían incorporado, este es el momento en que la participación voluntaria dejó de ser opcional — y donde comenzó realmente el camino plurianual hacia una facturación electrónica universal y plenamente aplicada.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2023-01-15-jordan-phase1-large-taxpayers', 'de', 'Jordaniens JoFotara wird für Großsteuerzahler verpflichtend', 'Die Registrierung und Integration mit JoFotara wurde für Jordaniens Großsteuerzahler verpflichtend — die erste Gruppe, die seit dem Start der Plattform im Dezember 2022 von der freiwilligen Teilnahme abrücken musste.', '<h3>🇯🇴 Jordaniens JoFotara wird für Großsteuerzahler verpflichtend</h3>
<p>Kaum einen Monat, nachdem die Einkommen- und Umsatzsteuerbehörde (ISTD) JoFotara — Jordaniens nationales elektronisches Rechnungssystem — auf freiwilliger Basis gestartet hatte, begann die verpflichtende Einführung für die Großsteuerzahler des Landes. Rechnungen werden nun in Echtzeit über die Plattform geprüft, wobei die ISTD einen QR-Code ausstellt, der die Validierung bestätigt, bevor eine Rechnung ihren Kunden erreicht.</p>
<p>Dies ist ein echtes zentralisiertes Clearing-Modell, kein Meldesystem nach der Transaktion: JoFotara steht zwischen Verkäufer und Käufer und prüft jede Rechnung während ihrer Bewegung. Großsteuerzahler können sich direkt über eine API integrieren, das kostenlose JoFotara-Webportal nutzen oder mit einem zertifizierten Drittanbieter zusammenarbeiten.</p>
<p>Für große Unternehmen, die noch nicht integriert waren, ist dies der Zeitpunkt, an dem die freiwillige Teilnahme aufhörte, optional zu sein — und an dem der mehrjährige Weg zu einer universellen, vollständig durchgesetzten E-Rechnung tatsächlich begann.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2023-01-15-jordan-phase1-large-taxpayers', 'fr', 'Le JoFotara jordanien devient obligatoire pour les grands contribuables', 'L''enregistrement et l''intégration à JoFotara sont devenus obligatoires pour les grands contribuables de Jordanie, le premier groupe tenu de quitter la participation volontaire depuis le lancement de la plateforme en décembre 2022.', '<h3>🇯🇴 Le JoFotara jordanien devient obligatoire pour les grands contribuables</h3>
<p>À peine un mois après que le Département des impôts sur le revenu et des ventes (ISTD) a lancé JoFotara — le système national de facturation électronique de la Jordanie — sur une base volontaire, l''intégration obligatoire a commencé pour les grands contribuables du pays. Les factures sont désormais validées via la plateforme en temps réel, l''ISTD délivrant un code QR confirmant la validation avant qu''une facture n''atteigne son client.</p>
<p>Il s''agit d''un véritable modèle de validation centralisée, non d''un système de déclaration après transaction : JoFotara se situe entre le vendeur et l''acheteur, vérifiant chaque facture au fil de son parcours. Les grands contribuables peuvent s''intégrer directement via une API, utiliser le portail web gratuit de JoFotara, ou passer par un prestataire de services tiers certifié.</p>
<p>Pour les grandes entreprises pas encore intégrées, c''est le moment où la participation volontaire a cessé d''être facultative — et où le parcours pluriannuel vers une facturation électronique universelle et pleinement appliquée a véritablement commencé.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2024-05-20-jordan-universal-registration', '2024-05-20', '2024-05', 'The onboarding wave that began with large taxpayers in 2023 reached its universal registration deadline: every VAT-registered business and individual in Jordan, with no SME exemption, had to be registered with JoFotara by 31 May 2024.', '<h3>🇯🇴 Universal JoFotara registration deadline arrives</h3>
<p>Jordan''s e-invoicing rollout reached a genuinely universal milestone: every VAT-registered taxpayer — not just the large taxpayers already onboarded under Phase 1 — had to be registered and integrated with JoFotara by 31 May 2024. Notably, this includes individual professionals such as consultants, doctors, and lawyers, alongside small and medium-sized enterprises. There is no size-based carve-out anywhere in the mandate.</p>
<p>The free JoFotara web portal exists precisely for this reason — small taxpayers without in-house invoicing or accounting systems can register and issue invoices without needing to buy new software. Larger businesses continue to have the option of direct API integration or working through a certified service provider.</p>
<p>Registration alone didn''t yet carry the mandate''s full legal weight — that came the following year, when non-compliant invoices actually became invalid for VAT purposes. But this deadline is what closed off the option of simply not yet being in the system.</p>', 'https://mozon-tech.com/en/blog/the-ultimate-guide-to-jofotara/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2024-05-20-jordan-universal-registration', id FROM countries WHERE name_en = 'Jordan';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2024-05-20-jordan-universal-registration', 'en', 'Universal JoFotara registration deadline arrives', 'The onboarding wave that began with large taxpayers in 2023 reached its universal registration deadline: every VAT-registered business and individual in Jordan, with no SME exemption, had to be registered with JoFotara by 31 May 2024.', '<h3>🇯🇴 Universal JoFotara registration deadline arrives</h3>
<p>Jordan''s e-invoicing rollout reached a genuinely universal milestone: every VAT-registered taxpayer — not just the large taxpayers already onboarded under Phase 1 — had to be registered and integrated with JoFotara by 31 May 2024. Notably, this includes individual professionals such as consultants, doctors, and lawyers, alongside small and medium-sized enterprises. There is no size-based carve-out anywhere in the mandate.</p>
<p>The free JoFotara web portal exists precisely for this reason — small taxpayers without in-house invoicing or accounting systems can register and issue invoices without needing to buy new software. Larger businesses continue to have the option of direct API integration or working through a certified service provider.</p>
<p>Registration alone didn''t yet carry the mandate''s full legal weight — that came the following year, when non-compliant invoices actually became invalid for VAT purposes. But this deadline is what closed off the option of simply not yet being in the system.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2024-05-20-jordan-universal-registration', 'es', 'Llega el plazo de registro universal en JoFotara', 'La ola de incorporación que comenzó con los grandes contribuyentes en 2023 alcanzó su plazo de registro universal: toda empresa y persona registrada a efectos del IVA en Jordania, sin exención para pymes, debía estar registrada en JoFotara antes del 31 de mayo de 2024.', '<h3>🇯🇴 Llega el plazo de registro universal en JoFotara</h3>
<p>El despliegue de facturación electrónica de Jordania alcanzó un hito verdaderamente universal: todo contribuyente registrado a efectos del IVA — no solo los grandes contribuyentes ya incorporados en la Fase 1 — debía estar registrado e integrado con JoFotara antes del 31 de mayo de 2024. Cabe destacar que esto incluye a profesionales independientes como consultores, médicos y abogados, además de pequeñas y medianas empresas. No existe ninguna excepción por tamaño en ningún punto del mandato.</p>
<p>El portal web gratuito de JoFotara existe precisamente por esta razón — los pequeños contribuyentes sin sistemas propios de facturación o contabilidad pueden registrarse y emitir facturas sin necesidad de comprar nuevo software. Las empresas más grandes siguen teniendo la opción de la integración directa por API o de trabajar a través de un proveedor de servicios certificado.</p>
<p>El registro por sí solo aún no conllevaba todo el peso legal del mandato — eso llegó al año siguiente, cuando las facturas no conformes realmente se volvieron inválidas a efectos del IVA. Pero este plazo fue el que cerró la opción de simplemente no estar todavía en el sistema.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2024-05-20-jordan-universal-registration', 'de', 'Frist für die universelle JoFotara-Registrierung erreicht', 'Die mit den Großsteuerzahlern 2023 begonnene Einführungswelle erreichte ihre universelle Registrierungsfrist: Jedes umsatzsteuerregistrierte Unternehmen und jede Einzelperson in Jordanien musste ohne KMU-Ausnahme bis zum 31. Mai 2024 bei JoFotara registriert sein.', '<h3>🇯🇴 Frist für die universelle JoFotara-Registrierung erreicht</h3>
<p>Jordaniens E-Rechnungs-Rollout erreichte einen wirklich universellen Meilenstein: Jeder umsatzsteuerregistrierte Steuerzahler — nicht nur die bereits unter Phase 1 integrierten Großsteuerzahler — musste bis zum 31. Mai 2024 bei JoFotara registriert und integriert sein. Bemerkenswert ist, dass dies auch selbstständige Fachleute wie Berater, Ärzte und Anwälte sowie kleine und mittlere Unternehmen einschließt. Es gibt nirgendwo in der Pflicht eine größenbasierte Ausnahme.</p>
<p>Das kostenlose JoFotara-Webportal existiert genau aus diesem Grund — kleine Steuerzahler ohne eigene Rechnungs- oder Buchhaltungssysteme können sich registrieren und Rechnungen ausstellen, ohne neue Software kaufen zu müssen. Größere Unternehmen haben weiterhin die Wahl zwischen direkter API-Integration oder der Zusammenarbeit mit einem zertifizierten Dienstleister.</p>
<p>Die Registrierung allein trug noch nicht das volle rechtliche Gewicht der Pflicht — das kam im folgenden Jahr, als nicht konforme Rechnungen tatsächlich für Mehrwertsteuerzwecke ungültig wurden. Aber diese Frist war es, die die Option, einfach noch nicht im System zu sein, schloss.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2024-05-20-jordan-universal-registration', 'fr', 'L''échéance d''enregistrement universel de JoFotara arrive', 'La vague d''intégration entamée avec les grands contribuables en 2023 a atteint son échéance d''enregistrement universel : toute entreprise et personne assujettie à la TVA en Jordanie, sans exemption pour les PME, devait être enregistrée auprès de JoFotara avant le 31 mai 2024.', '<h3>🇯🇴 L''échéance d''enregistrement universel de JoFotara arrive</h3>
<p>Le déploiement de la facturation électronique en Jordanie a atteint une étape véritablement universelle : tout contribuable assujetti à la TVA — pas seulement les grands contribuables déjà intégrés sous la Phase 1 — devait être enregistré et intégré à JoFotara avant le 31 mai 2024. Notamment, cela inclut les professionnels indépendants tels que les consultants, médecins et avocats, ainsi que les petites et moyennes entreprises. Il n''existe aucune exception basée sur la taille nulle part dans l''obligation.</p>
<p>Le portail web gratuit de JoFotara existe précisément pour cette raison — les petits contribuables sans systèmes internes de facturation ou de comptabilité peuvent s''enregistrer et émettre des factures sans avoir besoin d''acheter un nouveau logiciel. Les entreprises plus grandes continuent d''avoir le choix entre une intégration API directe ou le recours à un prestataire de services certifié.</p>
<p>L''enregistrement seul ne portait pas encore tout le poids légal de l''obligation — cela est venu l''année suivante, lorsque les factures non conformes sont réellement devenues invalides à des fins de TVA. Mais cette échéance est celle qui a fermé l''option de simplement ne pas encore être dans le système.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-04-15-jordan-phase2-full-enforcement', '2025-04-15', '2025-04', 'Jordan''s JoFotara mandate reached full legal enforcement on 1 April 2025: invoices not transmitted through the platform are now invalid for VAT deduction, backed by fines of roughly JOD 500 per violation and possible imprisonment for persistent non-compliance.', '<h3>🇯🇴 JoFotara''s Phase 2: full legal enforcement takes effect</h3>
<p>1 April 2025 marked the shift from registration to genuine enforcement for Jordan''s e-invoicing mandate. JoFotara clearance became mandatory in practice, not just on paper, for all domestic B2B, B2G, and B2C transactions, plus cross-border trade for resident taxpayers. The rule with real teeth: an invoice not transmitted through JoFotara is invalid for VAT input deduction and accounting purposes.</p>
<p>The Billing and Control Regulation backs this with escalating penalties — a fine of approximately JOD 500 per violation for initial non-compliance, rising to fines of up to JOD 1,000 or imprisonment of three to six months for persistent violations. Non-compliant businesses also lose eligibility for government tenders and contracts.</p>
<p>A grace period waiving accrued fines for late registrants ran until 31 May 2025 — after which the full penalty structure applies without exception. For any Jordanian business still treating JoFotara as optional, this is the point where that assumption became genuinely expensive.</p>', 'https://www.vatupdate.com/2025/07/17/jordans-e-invoicing-phase-2-mandatory-compliance-begins-april-1-2025/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-04-15-jordan-phase2-full-enforcement', id FROM countries WHERE name_en = 'Jordan';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-04-15-jordan-phase2-full-enforcement', 'en', 'JoFotara''s Phase 2: full legal enforcement takes effect', 'Jordan''s JoFotara mandate reached full legal enforcement on 1 April 2025: invoices not transmitted through the platform are now invalid for VAT deduction, backed by fines of roughly JOD 500 per violation and possible imprisonment for persistent non-compliance.', '<h3>🇯🇴 JoFotara''s Phase 2: full legal enforcement takes effect</h3>
<p>1 April 2025 marked the shift from registration to genuine enforcement for Jordan''s e-invoicing mandate. JoFotara clearance became mandatory in practice, not just on paper, for all domestic B2B, B2G, and B2C transactions, plus cross-border trade for resident taxpayers. The rule with real teeth: an invoice not transmitted through JoFotara is invalid for VAT input deduction and accounting purposes.</p>
<p>The Billing and Control Regulation backs this with escalating penalties — a fine of approximately JOD 500 per violation for initial non-compliance, rising to fines of up to JOD 1,000 or imprisonment of three to six months for persistent violations. Non-compliant businesses also lose eligibility for government tenders and contracts.</p>
<p>A grace period waiving accrued fines for late registrants ran until 31 May 2025 — after which the full penalty structure applies without exception. For any Jordanian business still treating JoFotara as optional, this is the point where that assumption became genuinely expensive.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-04-15-jordan-phase2-full-enforcement', 'es', 'Fase 2 de JoFotara: entra en vigor la plena aplicación legal', 'El mandato JoFotara de Jordania alcanzó la plena aplicación legal el 1 de abril de 2025: las facturas no transmitidas a través de la plataforma ahora no son válidas para la deducción del IVA, respaldado por multas de aproximadamente JOD 500 por infracción y posible prisión por incumplimiento persistente.', '<h3>🇯🇴 Fase 2 de JoFotara: entra en vigor la plena aplicación legal</h3>
<p>El 1 de abril de 2025 marcó el cambio del registro a la aplicación genuina para el mandato de facturación electrónica de Jordania. La validación a través de JoFotara se volvió obligatoria en la práctica, no solo sobre el papel, para todas las transacciones nacionales B2B, B2G y B2C, además del comercio transfronterizo para los contribuyentes residentes. La regla con dientes reales: una factura no transmitida a través de JoFotara no es válida para la deducción del IVA soportado ni a efectos contables.</p>
<p>El Reglamento de Facturación y Control respalda esto con sanciones escalonadas — una multa de aproximadamente JOD 500 por infracción para el incumplimiento inicial, que aumenta hasta multas de hasta JOD 1.000 o prisión de tres a seis meses por infracciones persistentes. Las empresas incumplidoras también pierden la elegibilidad para licitaciones y contratos gubernamentales.</p>
<p>Un periodo de gracia que eximía de las multas acumuladas a los registros tardíos se extendió hasta el 31 de mayo de 2025 — después de lo cual se aplica la estructura sancionadora completa sin excepción. Para cualquier empresa jordana que aún tratara a JoFotara como opcional, este es el momento en que esa suposición se volvió realmente costosa.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-04-15-jordan-phase2-full-enforcement', 'de', 'JoFotara Phase 2: vollständige rechtliche Durchsetzung tritt in Kraft', 'Jordaniens JoFotara-Pflicht erreichte am 1. April 2025 die vollständige rechtliche Durchsetzung: Nicht über die Plattform übermittelte Rechnungen sind nun für den Vorsteuerabzug ungültig, untermauert durch Bußgelder von etwa JOD 500 pro Verstoß und mögliche Freiheitsstrafe bei anhaltender Nichteinhaltung.', '<h3>🇯🇴 JoFotara Phase 2: vollständige rechtliche Durchsetzung tritt in Kraft</h3>
<p>Der 1. April 2025 markierte den Übergang von der Registrierung zur echten Durchsetzung von Jordaniens E-Rechnungspflicht. Die JoFotara-Validierung wurde in der Praxis verpflichtend, nicht nur auf dem Papier, für alle inländischen B2B-, B2G- und B2C-Transaktionen sowie den grenzüberschreitenden Handel gebietsansässiger Steuerzahler. Die Regel mit echten Konsequenzen: Eine nicht über JoFotara übermittelte Rechnung ist für den Vorsteuerabzug und buchhalterische Zwecke ungültig.</p>
<p>Die Abrechnungs- und Kontrollverordnung untermauert dies mit eskalierenden Sanktionen — einem Bußgeld von etwa JOD 500 pro Verstoß bei anfänglicher Nichteinhaltung, das bei anhaltenden Verstößen auf Bußgelder bis zu JOD 1.000 oder Freiheitsstrafe von drei bis sechs Monaten ansteigt. Nicht konforme Unternehmen verlieren zudem die Berechtigung für staatliche Ausschreibungen und Aufträge.</p>
<p>Eine Kulanzfrist, die aufgelaufene Bußgelder für verspätete Registrierungen erließ, lief bis zum 31. Mai 2025 — danach gilt die vollständige Bußgeldstruktur ohne Ausnahme. Für jedes jordanische Unternehmen, das JoFotara noch als optional behandelte, ist dies der Zeitpunkt, an dem diese Annahme tatsächlich teuer wurde.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-04-15-jordan-phase2-full-enforcement', 'fr', 'Phase 2 de JoFotara : l''application légale intégrale entre en vigueur', 'L''obligation JoFotara de la Jordanie a atteint l''application légale intégrale le 1er avril 2025 : les factures non transmises via la plateforme ne sont désormais plus valables pour la déduction de la TVA, appuyées par des amendes d''environ 500 JOD par infraction et une possible peine d''emprisonnement en cas de non-conformité persistante.', '<h3>🇯🇴 Phase 2 de JoFotara : l''application légale intégrale entre en vigueur</h3>
<p>Le 1er avril 2025 a marqué le passage de l''enregistrement à une application véritable de l''obligation de facturation électronique de la Jordanie. La validation via JoFotara est devenue obligatoire dans la pratique, pas seulement sur le papier, pour toutes les transactions nationales B2B, B2G et B2C, ainsi que pour le commerce transfrontalier des contribuables résidents. La règle qui a de vraies conséquences : une facture non transmise via JoFotara n''est pas valable pour la déduction de la TVA en amont ni à des fins comptables.</p>
<p>Le règlement sur la facturation et le contrôle appuie cela par des sanctions progressives — une amende d''environ 500 JOD par infraction pour la non-conformité initiale, pouvant atteindre 1 000 JOD ou une peine d''emprisonnement de trois à six mois en cas d''infractions persistantes. Les entreprises non conformes perdent également leur éligibilité aux appels d''offres et contrats gouvernementaux.</p>
<p>Un délai de grâce exonérant des amendes accumulées les enregistrements tardifs a couru jusqu''au 31 mai 2025 — après quoi la structure de sanctions complète s''applique sans exception. Pour toute entreprise jordanienne qui traitait encore JoFotara comme facultatif, c''est le moment où cette hypothèse est devenue véritablement coûteuse.</p>');
