-- South Korea: milestone translations (ES/DE/FR) for the 6 milestones
-- introduced in 281_south_korea_milestones.sql. INSERT OR IGNORE
-- throughout (idempotent), following the exact pattern of
-- 274_israel_milestone_translations.sql.

-- kr-corporate-mandate-2011
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-corporate-mandate-2011', 'es', 'La e-Tax Invoice se vuelve obligatoria para todas las corporaciones', 'Corea del Sur exigió a todos los contribuyentes corporativos emitir facturas del Impuesto al Valor Agregado electrónicamente y reportarlas al Servicio Nacional de Impuestos (NTS) antes del siguiente día hábil. Se trata de un modelo de reporte posterior a la emisión, no de un modelo de validación: la factura surte efecto legal al ser entregada al comprador, y la transmisión al NTS al día siguiente es una obligación de reporte independiente, no una condición previa para la validez de la factura.', '["No se requiere ninguna acción hoy -- este hito es contexto histórico sobre cuánto tiempo lleva vigente el sistema de e-Tax Invoice de Corea del Sur", "Si su empresa es una corporación coreana, la facturación electrónica ya es obligatoria para usted desde 2011, sin importar su tamaño"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-corporate-mandate-2011', 'de', 'e-Tax Invoice wird für alle Kapitalgesellschaften verpflichtend', 'Südkorea verpflichtete alle körperschaftsteuerpflichtigen Unternehmen, Mehrwertsteuerrechnungen elektronisch auszustellen und bis zum nächsten Werktag an die nationale Steuerbehörde (NTS) zu melden. Dies ist ein Meldemodell nach Rechnungsausstellung, kein Freigabemodell: Die Rechnung wird mit Zustellung an den Käufer rechtswirksam, und die Übermittlung an die NTS am nächsten Tag ist eine gesonderte Meldepflicht, keine Voraussetzung für die Gültigkeit der Rechnung.', '["Heute ist keine Handlung erforderlich -- dieser Meilenstein ist historischer Kontext dazu, wie lange Südkoreas e-Tax-Invoice-System bereits in Kraft ist", "Wenn Ihr Unternehmen eine koreanische Kapitalgesellschaft ist, ist die elektronische Rechnungsstellung für Sie unabhängig von der Größe bereits seit 2011 verpflichtend"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-corporate-mandate-2011', 'fr', 'La e-Tax Invoice devient obligatoire pour toutes les sociétés', 'La Corée du Sud a exigé de tous les contribuables constitués en société qu''ils émettent des factures de taxe sur la valeur ajoutée électroniquement et les déclarent à l''Administration fiscale nationale (NTS) au plus tard le jour ouvré suivant. Il s''agit d''un modèle de déclaration postérieure à l''émission, pas d''un modèle de validation : la facture prend effet juridique dès sa remise à l''acheteur, et la transmission à la NTS le lendemain constitue une obligation déclarative distincte, non une condition préalable à la validité de la facture.', '["Aucune action requise aujourd''hui -- cette étape est un contexte historique sur la durée pendant laquelle le système e-Tax Invoice de la Corée du Sud est déjà en vigueur", "Si votre entreprise est une société coréenne, la facturation électronique vous est déjà obligatoire depuis 2011, quelle que soit sa taille"]');

-- kr-individual-2012
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-individual-2012', 'es', 'Los empresarios individuales por encima de 1.000 millones de KRW entran en el ámbito', 'El mandato de e-Tax Invoice se extendió más allá de las corporaciones a los empresarios individuales (autónomos) con un valor de suministro anual superior a 1.000 millones de KRW -- la primera de lo que se convertiría en una serie de reducciones del umbral que ampliarían constantemente el alcance del mandato durante la década siguiente.', '["Solo contexto histórico -- vea las reducciones de umbral más recientes más abajo para conocer la cifra que importa hoy"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-individual-2012', 'de', 'Einzelunternehmer über 1 Milliarde KRW werden einbezogen', 'Die e-Tax-Invoice-Pflicht wurde über Kapitalgesellschaften hinaus auf Einzelunternehmer mit einem jährlichen Lieferwert von über 1 Milliarde KRW ausgeweitet -- die erste einer Reihe von Schwellenwertsenkungen, die die Reichweite der Pflicht im folgenden Jahrzehnt stetig vergrößern sollten.', '["Nur historischer Kontext -- die aktuell relevante Zahl finden Sie bei den jüngeren Schwellenwertsenkungen weiter unten"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-individual-2012', 'fr', 'Les entrepreneurs individuels au-delà de 1 milliard de KRW entrent dans le champ', 'L''obligation de e-Tax Invoice s''est étendue au-delà des sociétés aux entrepreneurs individuels dont la valeur de fourniture annuelle dépassait 1 milliard de KRW -- la première d''une série de réductions de seuil qui allaient constamment élargir la portée de l''obligation au cours de la décennie suivante.', '["Contexte historique uniquement -- voir les réductions de seuil plus récentes ci-dessous pour le chiffre qui compte aujourd''hui"]');

-- kr-threshold-300m-2014
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-300m-2014', 'es', 'El umbral para empresarios individuales baja a 300 millones de KRW', 'El umbral de ingresos que incorpora a los empresarios individuales al mandato de e-Tax Invoice bajó de 1.000 millones de KRW a 300 millones de KRW, la primera de varias reducciones que continuarían durante la década de 2020.', '["Solo contexto histórico -- vea las reducciones de umbral más recientes más abajo para conocer la cifra que importa hoy"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-300m-2014', 'de', 'Schwellenwert für Einzelunternehmer sinkt auf 300 Millionen KRW', 'Der Umsatzschwellenwert, der Einzelunternehmer in die e-Tax-Invoice-Pflicht einbezieht, sank von 1 Milliarde KRW auf 300 Millionen KRW -- die erste von mehreren Senkungen, die sich bis in die 2020er Jahre fortsetzen sollten.', '["Nur historischer Kontext -- die aktuell relevante Zahl finden Sie bei den jüngeren Schwellenwertsenkungen weiter unten"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-300m-2014', 'fr', 'Le seuil pour les entrepreneurs individuels baisse à 300 millions de KRW', 'Le seuil de revenu faisant entrer les entrepreneurs individuels dans l''obligation de e-Tax Invoice est passé de 1 milliard de KRW à 300 millions de KRW, la première d''une série de réductions qui allaient se poursuivre jusque dans les années 2020.', '["Contexte historique uniquement -- voir les réductions de seuil plus récentes ci-dessous pour le chiffre qui compte aujourd''hui"]');

-- kr-threshold-200m-2022
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-200m-2022', 'es', 'El umbral para empresarios individuales baja a 200 millones de KRW', 'El umbral de ingresos volvió a bajar, de 300 millones de KRW a 200 millones de KRW, incorporando a una franja más amplia de empresarios individuales al sistema obligatorio de e-Tax Invoice -- parte de un impulso sostenido de varios años hacia una cobertura casi universal.', '["Si su valor de suministro anual como empresario individual supera los 200 millones de KRW, confirme que está emitiendo facturas e-Tax Invoice a través de NTS Hometax o un canal equivalente", "Las empresas por debajo de este umbral aún pueden participar voluntariamente"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-200m-2022', 'de', 'Schwellenwert für Einzelunternehmer sinkt auf 200 Millionen KRW', 'Der Umsatzschwellenwert sank erneut, von 300 Millionen KRW auf 200 Millionen KRW, wodurch ein breiteres Band von Einzelunternehmern in das verpflichtende e-Tax-Invoice-System einbezogen wurde -- Teil eines über mehrere Jahre andauernden Vorstoßes hin zu einer nahezu universellen Abdeckung.', '["Wenn Ihr jährlicher Lieferwert als Einzelunternehmer 200 Millionen KRW übersteigt, bestätigen Sie, dass Sie e-Tax-Invoices über NTS Hometax oder einen gleichwertigen Kanal ausstellen", "Unternehmen unterhalb dieser Schwelle können weiterhin freiwillig teilnehmen"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-200m-2022', 'fr', 'Le seuil pour les entrepreneurs individuels baisse à 200 millions de KRW', 'Le seuil de revenu a de nouveau baissé, passant de 300 millions de KRW à 200 millions de KRW, faisant entrer une tranche plus large d''entrepreneurs individuels dans le système obligatoire de e-Tax Invoice -- élément d''une poussée soutenue sur plusieurs années vers une couverture quasi universelle.', '["Si votre valeur de fourniture annuelle en tant qu''entrepreneur individuel dépasse 200 millions de KRW, vérifiez que vous émettez des factures e-Tax Invoice via NTS Hometax ou un canal équivalent", "Les entreprises sous ce seuil peuvent toujours participer volontairement"]');

-- kr-threshold-100m-2023
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-100m-2023', 'es', 'El umbral baja a 100 millones de KRW; se introducen las facturas de autofacturación', 'El umbral para empresarios individuales bajó a 100 millones de KRW, y el NTS introdujo las facturas de autofacturación: cuando un proveedor no puede emitir una e-Tax Invoice, el comprador puede crear una en su lugar para suministros sujetos al IVA, sujeto a confirmación por una oficina tributaria de distrito.', '["Confirme si su valor de suministro anual ahora supera los 100 millones de KRW y, de ser así, que está emitiendo facturas e-Tax Invoice", "Si un proveedor suyo no puede emitir una e-Tax Invoice, compruebe si la autofacturación está disponible para usted como comprador"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-100m-2023', 'de', 'Schwellenwert sinkt auf 100 Millionen KRW; Selbstfakturierung eingeführt', 'Der Schwellenwert für Einzelunternehmer sank auf 100 Millionen KRW, und die NTS führte die Selbstfakturierung ein: Kann ein Lieferant keine e-Tax Invoice ausstellen, darf der Käufer stattdessen selbst eine für umsatzsteuerpflichtige Lieferungen erstellen, vorbehaltlich der Bestätigung durch ein Bezirksfinanzamt.', '["Prüfen Sie, ob Ihr jährlicher Lieferwert nun 100 Millionen KRW übersteigt, und stellen Sie in diesem Fall sicher, dass Sie e-Tax Invoices ausstellen", "Wenn einer Ihrer Lieferanten keine e-Tax Invoice ausstellen kann, prüfen Sie, ob Ihnen als Käufer die Selbstfakturierung zur Verfügung steht"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-100m-2023', 'fr', 'Le seuil baisse à 100 millions de KRW ; l''autofacturation est introduite', 'Le seuil pour les entrepreneurs individuels est tombé à 100 millions de KRW, et la NTS a introduit l''autofacturation : lorsqu''un fournisseur ne peut pas émettre de e-Tax Invoice, l''acheteur peut en créer une à sa place pour les fournitures soumises à la TVA, sous réserve de confirmation par un bureau des impôts de district.', '["Vérifiez si votre valeur de fourniture annuelle dépasse désormais 100 millions de KRW et, si oui, que vous émettez des factures e-Tax Invoice", "Si un de vos fournisseurs ne peut pas émettre de e-Tax Invoice, vérifiez si l''autofacturation vous est accessible en tant qu''acheteur"]');

-- kr-threshold-80m-2024
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-80m-2024', 'es', 'El umbral baja a 80 millones de KRW -- el más bajo hasta la fecha', 'El umbral para empresarios individuales volvió a bajar, a 80 millones de KRW de suministro del año anterior, el nivel más bajo desde que el mandato se extendió por primera vez más allá de las corporaciones en 2012. Este es el umbral actual según la última actualización de este seguimiento; se espera ampliamente que continúen nuevas reducciones para proseguir la tendencia hacia una cobertura universal, aunque todavía no se ha legislado ninguna fecha específica adicional.', '["Compare el valor de suministro del año anterior con el umbral actual de 80 millones de KRW, no con una cifra más antigua que pueda recordar de hace unos años", "Si está cerca del umbral, planifique ya la emisión de e-Tax Invoice en lugar de esperar a que la próxima reducción le tome por sorpresa"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-80m-2024', 'de', 'Schwellenwert sinkt auf 80 Millionen KRW -- der bisher niedrigste', 'Der Schwellenwert für Einzelunternehmer sank erneut, auf 80 Millionen KRW des Vorjahresumsatzes -- das niedrigste Niveau, seit die Pflicht 2012 erstmals über Kapitalgesellschaften hinaus ausgeweitet wurde. Dies ist der aktuelle Schwellenwert zum Zeitpunkt der letzten Aktualisierung dieses Trackers; weitere Senkungen werden allgemein erwartet, um den Trend zu einer universellen Abdeckung fortzusetzen, wenngleich noch kein weiteres konkretes Datum gesetzlich festgelegt wurde.', '["Vergleichen Sie Ihren Vorjahresumsatz mit dem aktuellen Schwellenwert von 80 Millionen KRW, nicht mit einer älteren Zahl, an die Sie sich vielleicht noch aus früheren Jahren erinnern", "Wenn Sie nahe am Schwellenwert liegen, planen Sie die e-Tax-Invoice-Ausstellung bereits jetzt, statt abzuwarten, bis Sie die nächste Senkung überrascht"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('kr-threshold-80m-2024', 'fr', 'Le seuil baisse à 80 millions de KRW -- le plus bas à ce jour', 'Le seuil pour les entrepreneurs individuels a de nouveau baissé, à 80 millions de KRW de fourniture de l''année précédente, le niveau le plus bas depuis que l''obligation s''est étendue pour la première fois au-delà des sociétés en 2012. Il s''agit du seuil actuel à la dernière mise à jour de ce suivi ; de nouvelles réductions sont largement attendues pour poursuivre la tendance vers une couverture universelle, bien qu''aucune autre date précise n''ait encore été légiférée.', '["Comparez votre valeur de fourniture de l''année précédente au seuil actuel de 80 millions de KRW, et non à un chiffre plus ancien dont vous pourriez vous souvenir", "Si vous êtes proche du seuil, planifiez dès maintenant l''émission de e-Tax Invoice plutôt que d''attendre que la prochaine réduction vous prenne au dépourvu"]');
