-- Vietnam: country row + name translations. Generated by
-- new_country_scaffold.py; INSERT OR IGNORE throughout (idempotent).

INSERT OR IGNORE INTO countries (code, name_en, region, slug, in_picker) VALUES ('VN', 'Vietnam', 'Asia-Pacific', 'vietnam', 1);

INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'en', 'Vietnam' FROM countries WHERE code = 'VN';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'es', 'Vietnam' FROM countries WHERE code = 'VN';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'de', 'Vietnam' FROM countries WHERE code = 'VN';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'fr', 'Viêt Nam' FROM countries WHERE code = 'VN';
