-- Vietnam story arc: 3 stories tracing the mandate from its July 2022
-- nationwide launch, through Decree 70/2025's June 2025 scope
-- expansion, to the January 2026 penalty-framework restructuring.
-- Sourced from the GDT, china-briefing.com, vietnamplus.vn, and
-- alitium.com, cross-checked against each other for dates and figures.

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2022-07-01-vietnam-nationwide-mandate', '2022-07-01', '2022-07', 'E-invoicing became mandatory nationwide across Vietnam, and paper invoices ceased to have legal validity for VAT purposes -- the culmination of a rollout that began with Decree 123/2020/ND-CP and a 2021 pilot in Hanoi and Ho Chi Minh City.', '<h3>🇻🇳 E-invoicing becomes mandatory nationwide in Vietnam</h3>
<p>From 1 July 2022, structured e-invoices became compulsory for every registered business, business household, and individual entrepreneur under the declared tax method across all of Vietnam. Paper invoices lost their legal validity for VAT purposes on the same date -- a hard cutover, not a gradual phase-out.</p>
<p>The mandate covers domestic B2B, B2C retail, B2G, and export sales, and follows a rollout that began with Decree 123/2020/ND-CP in December 2020 and a pilot across six provinces and cities, including Hanoi and Ho Chi Minh City, from November 2021. Two transmission models coexist: real-time clearance with a General Department of Taxation (GDT)-issued code, or same-day reporting without one.</p>
<p>For any business still relying on paper invoices, this date marked the end of that option entirely -- not a recommendation, but a legal requirement enforced from day one.</p>', 'https://gdt.gov.vn/wps/portal/english', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2022-07-01-vietnam-nationwide-mandate', id FROM countries WHERE name_en = 'Vietnam';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2022-07-01-vietnam-nationwide-mandate', 'en', 'E-invoicing becomes mandatory nationwide in Vietnam', 'E-invoicing became mandatory nationwide across Vietnam, and paper invoices ceased to have legal validity for VAT purposes -- the culmination of a rollout that began with Decree 123/2020/ND-CP and a 2021 pilot in Hanoi and Ho Chi Minh City.', '<h3>🇻🇳 E-invoicing becomes mandatory nationwide in Vietnam</h3>
<p>From 1 July 2022, structured e-invoices became compulsory for every registered business, business household, and individual entrepreneur under the declared tax method across all of Vietnam. Paper invoices lost their legal validity for VAT purposes on the same date -- a hard cutover, not a gradual phase-out.</p>
<p>The mandate covers domestic B2B, B2C retail, B2G, and export sales, and follows a rollout that began with Decree 123/2020/ND-CP in December 2020 and a pilot across six provinces and cities, including Hanoi and Ho Chi Minh City, from November 2021. Two transmission models coexist: real-time clearance with a General Department of Taxation (GDT)-issued code, or same-day reporting without one.</p>
<p>For any business still relying on paper invoices, this date marked the end of that option entirely -- not a recommendation, but a legal requirement enforced from day one.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2022-07-01-vietnam-nationwide-mandate', 'es', 'La facturación electrónica se vuelve obligatoria en todo Vietnam', 'La facturación electrónica se volvió obligatoria en todo Vietnam, y las facturas en papel dejaron de tener validez legal a efectos del IVA -- la culminación de un despliegue que comenzó con el Decreto 123/2020/ND-CP y un piloto en 2021 en Hanói y Ciudad Ho Chi Minh.', '<h3>🇻🇳 La facturación electrónica se vuelve obligatoria en todo Vietnam</h3>
<p>A partir del 1 de julio de 2022, las facturas electrónicas estructuradas se volvieron obligatorias para toda empresa registrada, hogar empresarial y autónomo bajo el método de declaración en todo Vietnam. Las facturas en papel perdieron su validez legal a efectos del IVA en la misma fecha -- un cambio inmediato, no una eliminación gradual.</p>
<p>El mandato cubre las ventas nacionales B2B, B2C minoristas, B2G y de exportación, y sigue un despliegue que comenzó con el Decreto 123/2020/ND-CP en diciembre de 2020 y un piloto en seis provincias y ciudades, entre ellas Hanói y Ciudad Ho Chi Minh, a partir de noviembre de 2021. Coexisten dos modelos de transmisión: la validación en tiempo real con un código emitido por la Dirección General de Tributación (GDT), o el reporte el mismo día sin código.</p>
<p>Para cualquier empresa que aún dependiera de facturas en papel, esta fecha marcó el fin total de esa opción -- no una recomendación, sino un requisito legal exigido desde el primer día.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2022-07-01-vietnam-nationwide-mandate', 'de', 'E-Invoicing wird in ganz Vietnam verpflichtend', 'E-Invoicing wurde in ganz Vietnam verpflichtend, und Papierrechnungen verloren ihre umsatzsteuerliche Gültigkeit -- der Abschluss eines Prozesses, der mit dem Dekret 123/2020/ND-CP und einem Pilotprojekt 2021 in Hanoi und Ho-Chi-Minh-Stadt begann.', '<h3>🇻🇳 E-Invoicing wird in ganz Vietnam verpflichtend</h3>
<p>Ab dem 1. Juli 2022 wurden strukturierte E-Rechnungen für jedes registrierte Unternehmen, jeden Gewerbehaushalt und jeden Einzelunternehmer im Deklarationsverfahren in ganz Vietnam verpflichtend. Papierrechnungen verloren zum selben Datum ihre umsatzsteuerliche Gültigkeit -- ein harter Stichtag, kein schrittweiser Ausstieg.</p>
<p>Die Pflicht umfasst inländisches B2B, B2C-Einzelhandel, B2G und Exportumsätze und folgt auf einen Prozess, der im Dezember 2020 mit dem Dekret 123/2020/ND-CP begann, gefolgt von einem Pilotprojekt in sechs Provinzen und Städten, darunter Hanoi und Ho-Chi-Minh-Stadt, ab November 2021. Zwei Übermittlungsmodelle bestehen nebeneinander: Echtzeit-Freigabe mit einem von der Generaldirektion für Steuern (GDT) ausgestellten Code, oder tagesgleiche Meldung ohne Code.</p>
<p>Für jedes Unternehmen, das noch auf Papierrechnungen setzte, markierte dieses Datum das vollständige Ende dieser Option -- keine Empfehlung, sondern eine ab dem ersten Tag durchgesetzte gesetzliche Pflicht.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2022-07-01-vietnam-nationwide-mandate', 'fr', 'La facturation électronique devient obligatoire dans tout le Viêt Nam', 'La facturation électronique est devenue obligatoire dans tout le Viêt Nam, et les factures papier ont perdu toute validité légale au regard de la TVA -- l''aboutissement d''un déploiement amorcé par le décret 123/2020/ND-CP et un projet pilote mené en 2021 à Hanoï et Hô-Chi-Minh-Ville.', '<h3>🇻🇳 La facturation électronique devient obligatoire dans tout le Viêt Nam</h3>
<p>À partir du 1er juillet 2022, les factures électroniques structurées sont devenues obligatoires pour toute entreprise enregistrée, tout foyer d''entreprise et tout entrepreneur individuel soumis au régime déclaratif, dans tout le Viêt Nam. Les factures papier ont perdu leur validité légale au regard de la TVA à la même date -- un basculement net, non une suppression progressive.</p>
<p>L''obligation couvre les ventes B2B domestiques, B2C au détail, B2G et à l''exportation, et fait suite à un déploiement amorcé par le décret 123/2020/ND-CP en décembre 2020 et un projet pilote mené dans six provinces et villes, dont Hanoï et Hô-Chi-Minh-Ville, à partir de novembre 2021. Deux modèles de transmission coexistent : la validation en temps réel avec un code délivré par la Direction générale de la fiscalité (GDT), ou la déclaration le jour même sans code.</p>
<p>Pour toute entreprise encore dépendante des factures papier, cette date a marqué la fin totale de cette option -- non une recommandation, mais une obligation légale appliquée dès le premier jour.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-06-01-vietnam-decree-70-expands-scope', '2025-06-01', '2025-06', 'Decree 70/2025/ND-CP took effect, bringing large business households and foreign e-commerce suppliers into Vietnam''s e-invoicing mandate for the first time, alongside standardized invoice-issuance timing rules.', '<h3>🇻🇳 Decree 70/2025 expands Vietnam''s e-invoicing mandate</h3>
<p>Three years after e-invoicing became compulsory nationwide, Decree 70/2025/ND-CP took effect, amending Decree 123 to close two real gaps in coverage. Business households and individual businesses with annual revenue of VND 1 billion (about USD 38,000) or more must now use POS cash registers connected in real time to the General Department of Taxation (GDT) -- as must consumer-facing sectors like shopping malls, supermarkets, restaurants, hotels, passenger transport, and personal services, regardless of their revenue.</p>
<p>Separately, foreign e-commerce and digital-service suppliers with no permanent establishment in Vietnam can now register directly to issue Vietnamese VAT invoices, rather than relying on a local intermediary -- a genuinely new channel, not just an extension of an existing one. The decree also standardized invoice-issuance timing rules across transaction types, replacing what had been ambiguous guidance for goods, services, exports, and utilities.</p>
<p>Early implementation reports describe most business households cooperating, though some merchants faced real friction over software costs and unfamiliar procedures -- tax authorities set up steering committees and extended support, including on public holidays, to help affected businesses through the transition.</p>', 'https://en.vietnamplus.vn/e-invoices-mandatory-for-large-business-households-post320405.vnp', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-06-01-vietnam-decree-70-expands-scope', id FROM countries WHERE name_en = 'Vietnam';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-06-01-vietnam-decree-70-expands-scope', 'en', 'Decree 70/2025 expands Vietnam''s e-invoicing mandate', 'Decree 70/2025/ND-CP took effect, bringing large business households and foreign e-commerce suppliers into Vietnam''s e-invoicing mandate for the first time, alongside standardized invoice-issuance timing rules.', '<h3>🇻🇳 Decree 70/2025 expands Vietnam''s e-invoicing mandate</h3>
<p>Three years after e-invoicing became compulsory nationwide, Decree 70/2025/ND-CP took effect, amending Decree 123 to close two real gaps in coverage. Business households and individual businesses with annual revenue of VND 1 billion (about USD 38,000) or more must now use POS cash registers connected in real time to the General Department of Taxation (GDT) -- as must consumer-facing sectors like shopping malls, supermarkets, restaurants, hotels, passenger transport, and personal services, regardless of their revenue.</p>
<p>Separately, foreign e-commerce and digital-service suppliers with no permanent establishment in Vietnam can now register directly to issue Vietnamese VAT invoices, rather than relying on a local intermediary -- a genuinely new channel, not just an extension of an existing one. The decree also standardized invoice-issuance timing rules across transaction types, replacing what had been ambiguous guidance for goods, services, exports, and utilities.</p>
<p>Early implementation reports describe most business households cooperating, though some merchants faced real friction over software costs and unfamiliar procedures -- tax authorities set up steering committees and extended support, including on public holidays, to help affected businesses through the transition.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-06-01-vietnam-decree-70-expands-scope', 'es', 'El Decreto 70/2025 amplía el mandato de facturación electrónica de Vietnam', 'El Decreto 70/2025/ND-CP entró en vigor, incorporando por primera vez a los grandes hogares empresariales y a los proveedores extranjeros de comercio electrónico al mandato de facturación electrónica de Vietnam, junto con normas uniformes sobre el momento de emisión de facturas.', '<h3>🇻🇳 El Decreto 70/2025 amplía el mandato de facturación electrónica de Vietnam</h3>
<p>Tres años después de que la facturación electrónica se volviera obligatoria en todo el país, entró en vigor el Decreto 70/2025/ND-CP, que modificó el Decreto 123 para cerrar dos vacíos reales de cobertura. Los hogares empresariales y autónomos con una facturación anual de 1.000 millones de VND (unos 38.000 USD) o más deben ahora usar cajas registradoras POS conectadas en tiempo real a la Dirección General de Tributación (GDT), al igual que los sectores de cara al consumidor como centros comerciales, supermercados, restaurantes, hoteles, transporte de pasajeros y servicios personales, sin importar su facturación.</p>
<p>Por separado, los proveedores extranjeros de comercio electrónico y de servicios digitales sin establecimiento permanente en Vietnam ya pueden registrarse directamente para emitir facturas de IVA vietnamitas, en lugar de depender de un intermediario local -- un canal genuinamente nuevo, no solo una extensión de uno existente. El decreto también uniformó los plazos de emisión de facturas según el tipo de operación, sustituyendo lo que hasta entonces era una guía ambigua para bienes, servicios, exportaciones y suministros.</p>
<p>Los primeros informes de implementación describen la cooperación de la mayoría de los hogares empresariales, aunque algunos comerciantes se encontraron con fricciones reales por los costes del software y procedimientos poco familiares -- las autoridades fiscales crearon comités de seguimiento y ampliaron el apoyo, incluso en días festivos, para ayudar a las empresas afectadas durante la transición.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-06-01-vietnam-decree-70-expands-scope', 'de', 'Dekret 70/2025 weitet Vietnams E-Invoicing-Pflicht aus', 'Das Dekret 70/2025/ND-CP trat in Kraft und nahm erstmals große Gewerbehaushalte und ausländische E-Commerce-Anbieter in Vietnams E-Invoicing-Pflicht auf, zusammen mit einheitlichen Regeln zum Zeitpunkt der Rechnungsstellung.', '<h3>🇻🇳 Dekret 70/2025 weitet Vietnams E-Invoicing-Pflicht aus</h3>
<p>Drei Jahre nachdem E-Invoicing landesweit verpflichtend wurde, trat das Dekret 70/2025/ND-CP in Kraft, das Dekret 123 änderte, um zwei echte Erfassungslücken zu schließen. Gewerbehaushalte und Einzelunternehmer mit einem Jahresumsatz von 1 Milliarde VND (rund 38.000 USD) oder mehr müssen nun POS-Registrierkassen nutzen, die in Echtzeit mit der Generaldirektion für Steuern (GDT) verbunden sind -- ebenso wie verbraucherorientierte Branchen wie Einkaufszentren, Supermärkte, Restaurants, Hotels, Personenverkehr und persönliche Dienstleistungen, unabhängig von ihrem Umsatz.</p>
<p>Separat können sich ausländische E-Commerce- und Digitaldienstanbieter ohne dauerhafte Niederlassung in Vietnam nun direkt registrieren, um vietnamesische Umsatzsteuerrechnungen auszustellen, statt sich auf einen lokalen Vermittler zu verlassen -- ein wirklich neuer Kanal, nicht nur eine Erweiterung eines bestehenden. Das Dekret vereinheitlichte zudem die Fristen für die Rechnungsstellung je nach Transaktionsart und ersetzte damit bislang uneinheitliche Vorgaben für Waren, Dienstleistungen, Exporte und Versorgungsleistungen.</p>
<p>Frühe Umsetzungsberichte beschreiben eine überwiegend kooperative Haltung der Gewerbehaushalte, wobei einige Händler jedoch mit echten Reibungspunkten bei Softwarekosten und ungewohnten Verfahren zu kämpfen hatten -- die Steuerbehörden richteten Lenkungsausschüsse ein und weiteten die Unterstützung aus, auch an Feiertagen, um betroffenen Unternehmen durch den Übergang zu helfen.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-06-01-vietnam-decree-70-expands-scope', 'fr', 'Le décret 70/2025 étend l''obligation de facturation électronique du Viêt Nam', 'Le décret 70/2025/ND-CP est entré en vigueur, faisant entrer pour la première fois les grands foyers d''entreprise et les fournisseurs étrangers de commerce électronique dans l''obligation de facturation électronique du Viêt Nam, avec des règles harmonisées sur le moment d''émission des factures.', '<h3>🇻🇳 Le décret 70/2025 étend l''obligation de facturation électronique du Viêt Nam</h3>
<p>Trois ans après que la facturation électronique est devenue obligatoire dans tout le pays, le décret 70/2025/ND-CP est entré en vigueur, modifiant le décret 123 pour combler deux véritables lacunes de couverture. Les foyers d''entreprise et entrepreneurs individuels réalisant un chiffre d''affaires annuel d''1 milliard de VND (environ 38 000 USD) ou plus doivent désormais utiliser des caisses enregistreuses POS connectées en temps réel à la Direction générale de la fiscalité (GDT) -- tout comme les secteurs en contact avec les consommateurs tels que les centres commerciaux, supermarchés, restaurants, hôtels, transport de voyageurs et services à la personne, quel que soit leur chiffre d''affaires.</p>
<p>Par ailleurs, les fournisseurs étrangers de commerce électronique et de services numériques sans établissement permanent au Viêt Nam peuvent désormais s''enregistrer directement pour émettre des factures de TVA vietnamiennes, plutôt que de dépendre d''un intermédiaire local -- un canal véritablement nouveau, pas seulement l''extension d''un canal existant. Le décret a également harmonisé les délais d''émission des factures selon le type d''opération, remplaçant des indications jusque-là ambiguës pour les biens, les services, les exportations et les services collectifs.</p>
<p>Les premiers retours de mise en œuvre décrivent une coopération de la plupart des foyers d''entreprise, bien que certains commerçants aient rencontré de réelles difficultés liées aux coûts logiciels et à des procédures peu familières -- les autorités fiscales ont mis en place des comités de pilotage et étendu leur accompagnement, y compris les jours fériés, pour aider les entreprises concernées pendant la transition.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-01-16-vietnam-penalty-framework-restructured', '2026-01-16', '2026-01', 'Decree 310/2025/ND-CP replaced Vietnam''s flat e-invoicing fine structure with a schedule that escalates by the number of violating invoices found within an inspection period, taking effect 16 January 2026.', '<h3>🇻🇳 Vietnam''s e-invoicing penalties restructured by violation count</h3>
<p>From 16 January 2026, Decree 310/2025/ND-CP replaced Vietnam''s previous flat-fine approach to e-invoicing non-compliance with a schedule that scales by how many violating invoices a tax inspection actually finds. A single late or missing invoice now draws a modest fine -- as little as VND 500,000 for incorrect timing, or VND 1 million for a missing invoice -- but the same violation found across 100 or more invoices draws a fine tens of times larger, up to VND 70-80 million.</p>
<p>The new framework also formally separates revenue-generating sales (goods and services) from non-commercial or internal-use invoices -- promotions, samples, gifts, internal consumption, and lending arrangements -- which sit on their own, lighter penalty schedule. Multiple violations discovered on the same day count as a single penalty at the highest applicable tier, not one penalty per invoice.</p>
<p>The underlying e-invoicing mandate itself didn''t change with this decree -- businesses that have been compliant since 2022 see no new obligations. What changed is the cost of getting it wrong at scale, which is now explicitly tied to how widespread the failure actually was.</p>', 'https://www.alitium.com/invoice-issuance-timing-in-vietnam-2026-rules-and-penalty-framework-explained/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-01-16-vietnam-penalty-framework-restructured', id FROM countries WHERE name_en = 'Vietnam';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-01-16-vietnam-penalty-framework-restructured', 'en', 'Vietnam''s e-invoicing penalties restructured by violation count', 'Decree 310/2025/ND-CP replaced Vietnam''s flat e-invoicing fine structure with a schedule that escalates by the number of violating invoices found within an inspection period, taking effect 16 January 2026.', '<h3>🇻🇳 Vietnam''s e-invoicing penalties restructured by violation count</h3>
<p>From 16 January 2026, Decree 310/2025/ND-CP replaced Vietnam''s previous flat-fine approach to e-invoicing non-compliance with a schedule that scales by how many violating invoices a tax inspection actually finds. A single late or missing invoice now draws a modest fine -- as little as VND 500,000 for incorrect timing, or VND 1 million for a missing invoice -- but the same violation found across 100 or more invoices draws a fine tens of times larger, up to VND 70-80 million.</p>
<p>The new framework also formally separates revenue-generating sales (goods and services) from non-commercial or internal-use invoices -- promotions, samples, gifts, internal consumption, and lending arrangements -- which sit on their own, lighter penalty schedule. Multiple violations discovered on the same day count as a single penalty at the highest applicable tier, not one penalty per invoice.</p>
<p>The underlying e-invoicing mandate itself didn''t change with this decree -- businesses that have been compliant since 2022 see no new obligations. What changed is the cost of getting it wrong at scale, which is now explicitly tied to how widespread the failure actually was.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-01-16-vietnam-penalty-framework-restructured', 'es', 'Las sanciones de facturación electrónica de Vietnam se reestructuran según el número de infracciones', 'El Decreto 310/2025/ND-CP sustituyó la estructura de multa fija de Vietnam para el incumplimiento de la facturación electrónica por una tabla que se gradúa según el número de facturas infractoras detectadas en un período de inspección, en vigor desde el 16 de enero de 2026.', '<h3>🇻🇳 Las sanciones de facturación electrónica de Vietnam se reestructuran según el número de infracciones</h3>
<p>Desde el 16 de enero de 2026, el Decreto 310/2025/ND-CP sustituyó el anterior enfoque de multa fija de Vietnam para el incumplimiento de la facturación electrónica por una tabla que se gradúa según cuántas facturas infractoras detecta realmente una inspección fiscal. Una única factura tardía o faltante conlleva ahora una multa modesta -- tan solo 500.000 VND por un momento de emisión incorrecto, o 1 millón de VND por una factura faltante -- pero la misma infracción detectada en 100 o más facturas conlleva una multa decenas de veces mayor, de hasta 70-80 millones de VND.</p>
<p>El nuevo régimen también separa formalmente las ventas generadoras de ingresos (bienes y servicios) de las facturas no comerciales o de uso interno -- promociones, muestras, regalos, consumo interno y operaciones de préstamo --, que tienen su propio régimen sancionador, más leve. Varias infracciones detectadas el mismo día cuentan como una sola sanción al nivel más alto aplicable, no como una sanción por factura.</p>
<p>El mandato de facturación electrónica en sí no cambió con este decreto -- las empresas que han cumplido desde 2022 no ven nuevas obligaciones. Lo que cambió es el coste de incumplirlo a gran escala, ahora vinculado explícitamente a la magnitud real del incumplimiento.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-01-16-vietnam-penalty-framework-restructured', 'de', 'Vietnams E-Invoicing-Sanktionen werden nach Verstoßzahl neu gestaffelt', 'Das Dekret 310/2025/ND-CP ersetzte Vietnams feste Bußgeldstruktur für E-Invoicing-Verstöße durch eine Tabelle, die sich nach der Anzahl der innerhalb eines Prüfungszeitraums festgestellten verstoßenden Rechnungen richtet, gültig ab dem 16. Januar 2026.', '<h3>🇻🇳 Vietnams E-Invoicing-Sanktionen werden nach Verstoßzahl neu gestaffelt</h3>
<p>Seit dem 16. Januar 2026 ersetzte das Dekret 310/2025/ND-CP Vietnams bisherigen festen Bußgeldansatz bei E-Invoicing-Verstößen durch eine Tabelle, die sich danach richtet, wie viele verstoßende Rechnungen eine Steuerprüfung tatsächlich findet. Eine einzelne verspätete oder fehlende Rechnung zieht nun ein moderates Bußgeld nach sich -- so wenig wie 500.000 VND bei falschem Zeitpunkt oder 1 Million VND bei einer fehlenden Rechnung --, doch dieselbe Pflichtverletzung bei 100 oder mehr Rechnungen zieht ein um ein Vielfaches höheres Bußgeld nach sich, bis zu 70-80 Millionen VND.</p>
<p>Der neue Rahmen trennt zudem formal umsatzgenerierende Verkäufe (Waren und Dienstleistungen) von nichtkommerziellen Rechnungen oder Rechnungen zum internen Gebrauch -- Werbeaktionen, Muster, Geschenke, interner Verbrauch und Verleihvorgänge --, die einem eigenen, milderen Bußgeldkatalog unterliegen. Mehrere am selben Tag festgestellte Verstöße zählen als eine einzige Sanktion auf der höchsten anwendbaren Stufe, nicht als eine Sanktion pro Rechnung.</p>
<p>Die zugrunde liegende E-Invoicing-Pflicht selbst änderte sich mit diesem Dekret nicht -- Unternehmen, die seit 2022 konform sind, haben keine neuen Pflichten. Verändert haben sich die Kosten, es im großen Maßstab falsch zu machen, die nun ausdrücklich an das tatsächliche Ausmaß des Verstoßes geknüpft sind.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-01-16-vietnam-penalty-framework-restructured', 'fr', 'Les sanctions de facturation électronique du Viêt Nam restructurées selon le nombre d''infractions', 'Le décret 310/2025/ND-CP a remplacé la structure d''amende fixe du Viêt Nam en cas de non-conformité de la facturation électronique par un barème échelonné selon le nombre de factures en infraction constatées lors d''une période de contrôle, en vigueur depuis le 16 janvier 2026.', '<h3>🇻🇳 Les sanctions de facturation électronique du Viêt Nam restructurées selon le nombre d''infractions</h3>
<p>Depuis le 16 janvier 2026, le décret 310/2025/ND-CP a remplacé l''ancienne approche vietnamienne d''amende fixe en cas de non-conformité de la facturation électronique par un barème qui s''échelonne selon le nombre de factures en infraction qu''un contrôle fiscal constate réellement. Une seule facture tardive ou manquante entraîne désormais une amende modeste -- à peine 500 000 VND pour un délai incorrect, ou 1 million de VND pour une facture manquante -- mais la même infraction constatée sur 100 factures ou plus entraîne une amende des dizaines de fois supérieure, jusqu''à 70-80 millions de VND.</p>
<p>Le nouveau cadre distingue aussi formellement les ventes génératrices de revenus (biens et services) des factures non commerciales ou à usage interne -- promotions, échantillons, cadeaux, consommation interne et opérations de prêt --, qui relèvent de leur propre barème, plus léger. Plusieurs infractions constatées le même jour comptent comme une seule sanction au niveau le plus élevé applicable, et non comme une sanction par facture.</p>
<p>L''obligation de facturation électronique elle-même n''a pas changé avec ce décret -- les entreprises conformes depuis 2022 ne voient apparaître aucune nouvelle obligation. Ce qui a changé, c''est le coût d''un manquement à grande échelle, désormais explicitement lié à l''ampleur réelle du manquement.</p>');
