-- Turkey deep-dive content (English). Turkey is the most mature
-- mandate added this session outside South Korea -- e-Fatura has been
-- mandatory since 1 April 2014 -- and, like Vietnam, genuinely has two
-- coexisting systems rather than one: e-Fatura (centralized clearance
-- through the Revenue Administration, GİB, for registered recipients)
-- and e-Arşiv (post-issuance reporting for everyone else, including
-- consumers). Modeled as two separate lifecycle pill cards per the
-- same Malaysia/Vietnam precedent of multiple genuinely-distinct
-- pill-list cards in one section. The penalty structure is also its
-- own shape: a percentage-of-invoice-value fine with an inflation-
-- indexed minimum (Vergi Usul Kanunu, Mükerrer Madde 355), applied
-- unusually to BOTH the issuer and the recipient who accepts a
-- non-compliant invoice.

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-03' FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en', 'Dual model — centralized clearance (e-Fatura) or post-issuance reporting (e-Arşiv), both routed through the Revenue Administration (GİB)', 'This deep-dive page reflects publicly available GİB guidance and industry reporting as of August 2026 and is provided for general awareness, not legal or tax advice. Threshold amounts are inflation-indexed and change annually — confirm current figures directly with the Revenue Administration (GİB) or your integration provider before building against them.', 'Turkey''s e-invoicing framework is the most mature in this tracker outside South Korea: e-Fatura became mandatory for larger taxpayers on 1 April 2014, building on e-Transformation groundwork the Revenue Administration (GİB) had been laying since 2012. e-Defter (electronic ledgers) followed in 2015, e-İrsaliye (electronic waybills) in 2023, and the mandate continues to tighten in 2026 with a lower general threshold and the removal of e-Arşiv''s monetary floor entirely.', 'Invoices are authored as structured XML in UBL-TR format and digitally signed. Which of Turkey''s two parallel e-document systems applies — e-Fatura or e-Arşiv — depends on whether the recipient is itself registered for e-Fatura, not on the seller''s own choice.', 'Turkey''s mandate is revenue-threshold based rather than universal, but the thresholds have fallen steadily since 2014 and several sectors are in scope regardless of size.', 'Getting compliant means checking your turnover against the current e-Fatura and e-İrsaliye thresholds, confirming every invoice below those thresholds is still issued as an e-Arşiv invoice, and choosing an access route — GİB''s own portal, a private integrator (özel entegratör), or a direct in-house integration.', 'Turkey enforces e-invoicing compliance through the Tax Procedure Law''s (Vergi Usul Kanunu) special irregularity fines, calculated as a percentage of the invoice value with an inflation-indexed minimum — applied to both the issuer and, unusually among this tracker''s countries, the recipient who accepts a non-compliant invoice.', 'Turkey''s e-Fatura mandate has been in force since 1 April 2014, one of the longest-running e-invoicing regimes this tracker covers, and continues to tighten: e-İrsaliye (e-Waybill) joined the framework in 2023, and from January 2026 the e-Arşiv monetary floor was removed entirely, alongside a lower general e-Fatura threshold.', '🇹🇷' FROM countries WHERE name_en = 'Turkey';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2014', 'e-Fatura mandatory since');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '2 systems', 'e-Fatura (clearance) or e-Arşiv (reporting)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'UBL-TR XML', 'Structured invoice format');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'TRY 3M', '2026 general e-Fatura threshold, on 2025 revenue');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'TRY 2,200', 'Minimum fine for a non-issued e-invoice');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & standard', '[["Authoring format", "Structured XML (UBL-TR), digitally signed"], ["Verification artifact", "GİB clearance record (e-Fatura) or a same-day GİB report (e-Arşiv)"], ["Legal basis", "Tax Procedure Law (Vergi Usul Kanunu) general communiqués covering e-Fatura, e-Arşiv, e-Defter, and e-İrsaliye"], ["Access routes", "GİB''s own e-Belge portal, a private integrator (özel entegratör), or direct in-house integration"]]', 'Every invoice is the same underlying XML format regardless of route — e-Fatura and e-Arşiv differ in who the recipient is and how GİB sees the data, not in the document''s own structure.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Identifiers & registration', '[["Taxpayer identity", "Turkish tax identification number (VKN), or national ID number (TCKN) for individuals"], ["e-Fatura registration", "Required once turnover crosses the current threshold, or if in an always-mandatory sector"], ["e-İrsaliye registration", "Required separately once turnover crosses its own, higher threshold"], ["Foreign suppliers", "Non-resident digital-service providers register for VAT but generally issue e-Arşiv rather than e-Fatura to end consumers"]]', 'e-Fatura and e-İrsaliye registration are tracked against two different thresholds — crossing one doesn''t automatically mean you''ve crossed the other.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Mandatory content & archiving', '[["Party data", "Seller and buyer tax identification numbers (VKN/TCKN)"], ["Invoice types", "e-Fatura (cleared, registered recipients) or e-Arşiv (everyone else, including consumers)"], ["Retention period", "10 years, alongside all other accounting records under the Tax Procedure Law"], ["e-Defter", "Electronic general ledger/journal filing required for every e-Fatura user"]]', 'Ten years'' retention lines up with Turkey''s general Tax Procedure Law bookkeeping duty, not a rule unique to e-invoicing.', NULL);

INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 0, 'pills' FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'e-Fatura — centralized clearance (registered recipients)', 'When both parties are registered e-Fatura users, an invoice follows this sequence:', 'The seller and buyer never exchange the invoice directly — GİB sits in the middle of every e-Fatura, a genuine clearance model, the same shape as Jordan and Israel elsewhere in this tracker, though centralized through a single government platform rather than a decentralized exchange.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Invoice drafted in UBL-TR XML, digitally signed');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Submitted to GİB''s central platform');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'GİB validates and clears the invoice');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 3, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Cleared invoice distributed to the registered buyer');

INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 1, 'pills' FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'e-Arşiv — post-issuance reporting (everyone else)', 'When the recipient isn''t registered for e-Fatura — most consumers, and many smaller businesses — the invoice instead follows this sequence:', 'This is the flow most similar to South Korea''s post-issuance model elsewhere in this tracker — the invoice is valid on delivery, and reporting to GİB is a parallel duty, not a precondition for validity. Since January 2026 there''s no minimum invoice value below which e-Arşiv can revert to paper.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Invoice issued and delivered directly to the buyer');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Invoice data reported to GİB, generally the same day');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'GİB retains the reported data for its own records');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Who''s in scope, and since when', '[["Turnover above TRY 5 million (2014 launch threshold)", "e-Fatura mandatory since 1 April 2014"], ["Turnover above TRY 3 million (2026 general threshold, on 2025 revenue)", "e-Fatura mandatory; register by 1 July 2026"], ["E-commerce, real estate, motor vehicles, licensed accommodation", "Lower TRY 500,000 e-Fatura threshold applies"], ["Energy, fruit/vegetable wholesale, online marketplaces, importers", "e-Fatura mandatory regardless of turnover"], ["Turnover above TRY 10 million", "e-İrsaliye (e-Waybill) mandatory since 1 July 2023, tracked separately"]]', 'The e-Fatura threshold has fallen from TRY 5 million at launch to as low as TRY 500,000 for specific sectors by 2026 — a steady tightening rather than a single cutover, similar in shape to South Korea''s own threshold history.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 3 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'What''s covered', '[["Domestic B2B (registered recipients)", "e-Fatura"], ["Domestic B2B/B2C (unregistered recipients)", "e-Arşiv, mandatory regardless of value since Jan 2026"], ["B2G", "e-Fatura, where the government body is itself e-Fatura-registered"], ["Goods movement/dispatch", "e-İrsaliye, tracked separately from the invoice itself"], ["Exports", "Standard customs documentation applies; not itself an e-Fatura requirement"]]', 'Between e-Fatura and e-Arşiv, essentially every domestic sale is covered electronically in some form — the open question for a given transaction is which of the two systems applies, not whether either does.', NULL);

INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Failure to issue a required e-invoice (issuer)', '10% of the invoice value, minimum TRY 2,200', NULL);
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Accepting/recording a non-compliant invoice (recipient)', '10% of the invoice value, minimum TRY 2,200', NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚖️ Both sides of the transaction are on the hook', NULL, NULL, 'Unlike most countries in this tracker, Turkey''s special irregularity fine (Vergi Usul Kanunu, Mükerrer Madde 355) applies to both the issuer who fails to issue a required e-invoice and the recipient who knowingly accepts or records a non-compliant one — a dual-accountability structure that puts pressure on both parties to get the document type right, not just the seller.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📈 A percentage fine, not a flat fee', NULL, NULL, 'The 10%-of-invoice-value structure means the fine scales automatically with transaction size, with a fixed minimum (TRY 2,200, adjusted periodically for inflation) as the floor for low-value invoices — a genuinely different shape from Vietnam''s violation-count scaling or Jordan''s flat JOD fine elsewhere in this tracker.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📅 Late e-Arşiv and e-Defter reporting carry their own fines', NULL, NULL, 'Beyond the non-issuance penalty above, late e-Arşiv reporting or late e-Defter (electronic ledger) submission each trigger additional fines under the same general irregularity-penalty framework — publicly available sources don''t converge on a single current figure for these, so treat this page''s penalty table as covering issuance only, and confirm late-filing fines directly with GİB or your integration provider before relying on a specific number.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Check your 2025 turnover against the 2026 e-Fatura thresholds', 'Compare your 2025 revenue to the TRY 3 million general threshold, or the TRY 500,000 threshold if you''re in e-commerce, real estate, motor vehicles, or licensed accommodation — and register for e-Fatura by 1 July 2026 if you cross it.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm every unregistered-recipient invoice is issued as e-Arşiv', 'Since January 2026 there''s no minimum value below which a paper invoice is acceptable for a non-e-Fatura-registered recipient — confirm your invoicing system issues e-Arşiv electronically for every such sale, not just larger ones.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Check the e-İrsaliye threshold separately', 'If your turnover exceeds TRY 10 million and you dispatch physical goods, confirm e-İrsaliye (e-Waybill) issuance is integrated alongside your invoicing — it''s tracked against its own threshold, not the e-Fatura one.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Choose an access route', 'Decide between GİB''s own free e-Belge portal (suited to lower invoice volumes), a private integrator (özel entegratör) offering additional tooling, or a direct in-house integration for higher-volume issuers.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm e-Defter filings are current', 'Every e-Fatura user, and any company subject to independent audit under Turkish Commercial Code thresholds, must also file e-Defter (electronic ledgers) — confirm this is integrated alongside your invoicing, not treated as a separate, optional step.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Retain every e-document for 10 years', 'e-Fatura, e-Arşiv, e-Defter, and e-İrsaliye records all fall under the Tax Procedure Law''s general 10-year retention duty — keep the original signed electronic files, not just PDF renderings.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://ebelge.gib.gov.tr', 0 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Revenue Administration (GİB) — e-Belge portal');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.gib.gov.tr', 1 FROM countries WHERE name_en = 'Turkey';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Revenue Administration (Gelir İdaresi Başkanlığı, GİB)');
