-- Argentina: country row + name translations. Generated by
-- new_country_scaffold.py; INSERT OR IGNORE throughout (idempotent).

INSERT OR IGNORE INTO countries (code, name_en, region, slug, in_picker) VALUES ('AR', 'Argentina', 'Americas', 'argentina', 1);

INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'en', 'Argentina' FROM countries WHERE code = 'AR';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'es', 'Argentina' FROM countries WHERE code = 'AR';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'de', 'Argentinien' FROM countries WHERE code = 'AR';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'fr', 'Argentine' FROM countries WHERE code = 'AR';
