-- Philippines story arc: 2 stories -- the January 2025 Joint Administrative
-- Order (JAO 001-2025) launching the cross-border e-invoicing / pre-border
-- technical verification system for imports (a genuinely distinctive side
-- story, separate from the domestic EIS mandate), and the October 2025
-- Revenue Regulations No. 26-2025 deadline extension for Phase 1 of the
-- domestic mandate, matching the multi-story arc pattern used for other
-- countries with more than one newsworthy development (see Colombia's 327).

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-01-24-philippines-cross-border-jao', '2025-01-24', '2025-01', 'The Department of Finance issued Joint Administrative Order No. 001-2025, launching a cross-border e-invoicing system for imports -- a separate initiative from the BIR''s domestic EIS mandate, aimed at customs verification rather than sales-tax reporting.', '<h3>🇵🇭 A second, separate e-invoicing system -- this one for imports at the border</h3>
<p>On 24 January 2025, the Philippines'' Department of Finance issued Joint Administrative Order No. 001-2025, implementing Administrative Order No. 23 (series of 2024) to stand up a Pre-Border Technical Verification and Cross-Border Electronic Invoicing System. It is easy to conflate this with the BIR''s domestic e-invoicing mandate covered elsewhere on this page, but the two are genuinely distinct: this one sits with the Bureau of Customs and targets imported goods, not domestic sales.</p>
<p>The committee overseeing it spans the Bureau of Customs, the Departments of Agriculture, Trade and Industry, Energy, Health, and Environment and Natural Resources, the Department of Information and Communications Technology, the Philippine Drug Enforcement Agency, and industry representatives from the Philippine Chamber of Commerce and Industry and the Chemical and Pharmaceutical Industry Organization of the Philippines. Its stated goals: streamline customs procedures, speed up inspection of imported goods, strengthen border security, verify compliance with Philippine safety standards, and improve inter-agency coordination against smuggling, misdeclaration, and undervaluation.</p>
<p>Finance Secretary Ralph G. Recto framed it as a border-protection measure: "With the freshly issued JAO, we can now begin our collective efforts towards strengthening our border protection through digitalization." For businesses tracking the BIR''s domestic e-invoicing timeline, the practical takeaway is simply to keep the two systems separate in your compliance planning -- one covers what you sell, the other covers what you import.</p>', 'https://www.dof.gov.ph/dof-successfully-issues-jao-to-implement-pre-border-technical-verification-and-cross-border-e-invoicing-system-that-will-protect-consumers-from-unsafe-goods/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-01-24-philippines-cross-border-jao', id FROM countries WHERE name_en = 'Philippines';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-24-philippines-cross-border-jao', 'en', 'A second, separate e-invoicing system -- this one for imports at the border', 'The Department of Finance issued Joint Administrative Order No. 001-2025, launching a cross-border e-invoicing system for imports -- a separate initiative from the BIR''s domestic EIS mandate, aimed at customs verification rather than sales-tax reporting.', '<h3>🇵🇭 A second, separate e-invoicing system -- this one for imports at the border</h3>
<p>On 24 January 2025, the Philippines'' Department of Finance issued Joint Administrative Order No. 001-2025, implementing Administrative Order No. 23 (series of 2024) to stand up a Pre-Border Technical Verification and Cross-Border Electronic Invoicing System. It is easy to conflate this with the BIR''s domestic e-invoicing mandate covered elsewhere on this page, but the two are genuinely distinct: this one sits with the Bureau of Customs and targets imported goods, not domestic sales.</p>
<p>The committee overseeing it spans the Bureau of Customs, the Departments of Agriculture, Trade and Industry, Energy, Health, and Environment and Natural Resources, the Department of Information and Communications Technology, the Philippine Drug Enforcement Agency, and industry representatives from the Philippine Chamber of Commerce and Industry and the Chemical and Pharmaceutical Industry Organization of the Philippines. Its stated goals: streamline customs procedures, speed up inspection of imported goods, strengthen border security, verify compliance with Philippine safety standards, and improve inter-agency coordination against smuggling, misdeclaration, and undervaluation.</p>
<p>Finance Secretary Ralph G. Recto framed it as a border-protection measure: "With the freshly issued JAO, we can now begin our collective efforts towards strengthening our border protection through digitalization." For businesses tracking the BIR''s domestic e-invoicing timeline, the practical takeaway is simply to keep the two systems separate in your compliance planning -- one covers what you sell, the other covers what you import.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-24-philippines-cross-border-jao', 'es', 'Un segundo sistema de facturación electrónica, aparte -- este para las importaciones en la frontera', 'El Departamento de Finanzas emitió la Orden Administrativa Conjunta N.º 001-2025, que lanza un sistema de facturación electrónica transfronteriza para importaciones -- una iniciativa separada del mandato EIS nacional del BIR, orientada a la verificación aduanera y no al reporte del impuesto sobre las ventas.', '<h3>🇵🇭 Un segundo sistema de facturación electrónica, aparte -- este para las importaciones en la frontera</h3>
<p>El 24 de enero de 2025, el Departamento de Finanzas de Filipinas emitió la Orden Administrativa Conjunta N.º 001-2025, que implementa la Orden Administrativa N.º 23 (serie de 2024) para poner en marcha un Sistema de Verificación Técnica Pre-Frontera y de Facturación Electrónica Transfronteriza. Es fácil confundir esto con el mandato nacional de facturación electrónica del BIR tratado en otras partes de esta página, pero ambos son realmente distintos: este corresponde al Buró de Aduanas y se dirige a los bienes importados, no a las ventas nacionales.</p>
<p>El comité que lo supervisa abarca al Buró de Aduanas, los Departamentos de Agricultura, Comercio e Industria, Energía, Salud, y Medio Ambiente y Recursos Naturales, el Departamento de Tecnologías de la Información y las Comunicaciones, el Organismo Filipino de Control de Drogas, y representantes de la industria de la Cámara de Comercio e Industria de Filipinas y de la Organización de la Industria Química y Farmacéutica de Filipinas. Sus objetivos declarados: agilizar los procedimientos aduaneros, acelerar la inspección de los bienes importados, reforzar la seguridad fronteriza, verificar el cumplimiento de las normas de seguridad filipinas y mejorar la coordinación interinstitucional contra el contrabando, la declaración incorrecta y la subvaluación.</p>
<p>El Secretario de Finanzas Ralph G. Recto lo presentó como una medida de protección fronteriza: "With the freshly issued JAO, we can now begin our collective efforts towards strengthening our border protection through digitalization." Para las empresas que siguen el cronograma nacional de facturación electrónica del BIR, la conclusión práctica es simplemente mantener ambos sistemas separados en su planificación de cumplimiento -- uno cubre lo que vende, el otro lo que importa.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-24-philippines-cross-border-jao', 'de', 'Ein zweites, eigenständiges E-Invoicing-System -- dieses für Importe an der Grenze', 'Das Finanzministerium erließ die Joint Administrative Order Nr. 001-2025 und startete damit ein grenzüberschreitendes E-Invoicing-System für Importe -- eine vom inländischen EIS-Mandat des BIR getrennte Initiative, die auf die Zollverifizierung und nicht auf die Umsatzsteuermeldung abzielt.', '<h3>🇵🇭 Ein zweites, eigenständiges E-Invoicing-System -- dieses für Importe an der Grenze</h3>
<p>Am 24. Januar 2025 erließ das philippinische Finanzministerium die Joint Administrative Order Nr. 001-2025 zur Umsetzung der Administrative Order Nr. 23 (Serie 2024) und richtete damit ein Pre-Border Technical Verification and Cross-Border Electronic Invoicing System ein. Es liegt nahe, dies mit dem an anderer Stelle auf dieser Seite behandelten inländischen E-Invoicing-Mandat des BIR zu verwechseln, doch beide sind tatsächlich eigenständig: Dieses liegt beim Bureau of Customs und richtet sich an importierte Waren, nicht an den inländischen Verkauf.</p>
<p>Das aufsichtsführende Komitee umfasst das Bureau of Customs, die Ministerien für Landwirtschaft, Handel und Industrie, Energie, Gesundheit sowie Umwelt und natürliche Ressourcen, das Ministerium für Informations- und Kommunikationstechnologie, die philippinische Drogenbekämpfungsbehörde sowie Branchenvertreter der Philippine Chamber of Commerce and Industry und der Chemical and Pharmaceutical Industry Organization of the Philippines. Erklärte Ziele: Zollverfahren straffen, die Inspektion importierter Waren beschleunigen, die Grenzsicherheit stärken, die Einhaltung philippinischer Sicherheitsstandards überprüfen und die behördenübergreifende Koordination gegen Schmuggel, Falschdeklaration und Unterbewertung verbessern.</p>
<p>Finanzminister Ralph G. Recto bezeichnete dies als Maßnahme zum Grenzschutz: "With the freshly issued JAO, we can now begin our collective efforts towards strengthening our border protection through digitalization." Für Unternehmen, die den inländischen E-Invoicing-Zeitplan des BIR verfolgen, besteht die praktische Konsequenz schlicht darin, beide Systeme in der eigenen Compliance-Planung getrennt zu halten -- eines betrifft, was Sie verkaufen, das andere, was Sie importieren.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-24-philippines-cross-border-jao', 'fr', 'Un second système de facturation électronique, distinct -- celui-ci pour les importations à la frontière', 'Le ministère des Finances a publié l''arrêté administratif conjoint n° 001-2025, lançant un système de facturation électronique transfrontalière pour les importations -- une initiative distincte du mandat EIS national du BIR, axée sur la vérification douanière plutôt que sur la déclaration de la taxe sur les ventes.', '<h3>🇵🇭 Un second système de facturation électronique, distinct -- celui-ci pour les importations à la frontière</h3>
<p>Le 24 janvier 2025, le ministère des Finances des Philippines a publié l''arrêté administratif conjoint n° 001-2025, mettant en œuvre l''arrêté administratif n° 23 (série 2024) pour mettre en place un système de vérification technique pré-frontière et de facturation électronique transfrontalière. Il est facile de confondre ceci avec le mandat national de facturation électronique du BIR traité ailleurs sur cette page, mais les deux sont réellement distincts : celui-ci relève du Bureau of Customs et vise les marchandises importées, non les ventes domestiques.</p>
<p>Le comité qui le supervise réunit le Bureau of Customs, les ministères de l''Agriculture, du Commerce et de l''Industrie, de l''Énergie, de la Santé, ainsi que de l''Environnement et des Ressources naturelles, le ministère des Technologies de l''information et de la communication, l''agence philippine de lutte contre la drogue, ainsi que des représentants de l''industrie issus de la Chambre de commerce et d''industrie des Philippines et de l''organisation philippine de l''industrie chimique et pharmaceutique. Objectifs déclarés : simplifier les procédures douanières, accélérer l''inspection des marchandises importées, renforcer la sécurité aux frontières, vérifier la conformité aux normes de sécurité philippines et améliorer la coordination interinstitutionnelle contre la contrebande, les fausses déclarations et la sous-évaluation.</p>
<p>Le secrétaire aux Finances Ralph G. Recto a présenté cela comme une mesure de protection des frontières : "With the freshly issued JAO, we can now begin our collective efforts towards strengthening our border protection through digitalization." Pour les entreprises qui suivent le calendrier national de facturation électronique du BIR, la conséquence pratique est simplement de garder les deux systèmes distincts dans leur planification de conformité -- l''un couvre ce que vous vendez, l''autre ce que vous importez.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-10-16-philippines-rr26-2025-extension', '2025-10-16', '2025-10', 'The BIR issued Revenue Regulations No. 26-2025, pushing the Phase 1 e-invoicing compliance deadline from 14 March 2026 to 31 December 2026 -- the mandate''s second documented slip after its 2022 pilot paused for roughly two years.', '<h3>🇵🇭 BIR gives Phase 1 taxpayers another nine months before e-invoicing is mandatory</h3>
<p>Revenue Regulations No. 26-2025, issued 16 October 2025, extends the Phase 1 compliance deadline for structured e-invoicing under the Electronic Invoicing/Receipting System (EIS) from 14 March 2026 -- the date set by RR 11-2025 -- to 31 December 2026. The extension covers the taxpayers named under RR 11-2025: e-commerce and internet-transaction businesses of any size, Large Taxpayers Service taxpayers, other large taxpayers under the Ease of Paying Taxes Act, and users of computerized accounting systems with e-invoicing software.</p>
<p>The core requirement is unchanged, only the date has moved: covered taxpayers must issue e-invoices "in a structured data format that can be easily extracted and transmitted electronically" -- PDFs and other non-structured formats will no longer qualify once the deadline arrives. Other categories named in RR 11-2025 -- exporters, Registered Business Enterprises with tax incentives, and POS system users -- will be brought in later, once the BIR has the necessary systems in place.</p>
<p>This is the second time this specific deadline has moved. The mandate''s original 2022 pilot with 100 selected large taxpayers paused for roughly two years after technical and capacity problems, and RR 11-2025''s own March 2026 target lasted less than eight months before RR 26-2025 superseded it. Businesses building compliance timelines around the December 2026 date should treat it as the current official target, not a settled certainty.</p>', 'https://sovos.com/regulatory-updates/vat/philippines-deadline-for-mandatory-structured-e-invoicing-extended/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-10-16-philippines-rr26-2025-extension', id FROM countries WHERE name_en = 'Philippines';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-16-philippines-rr26-2025-extension', 'en', 'BIR gives Phase 1 taxpayers another nine months before e-invoicing is mandatory', 'The BIR issued Revenue Regulations No. 26-2025, pushing the Phase 1 e-invoicing compliance deadline from 14 March 2026 to 31 December 2026 -- the mandate''s second documented slip after its 2022 pilot paused for roughly two years.', '<h3>🇵🇭 BIR gives Phase 1 taxpayers another nine months before e-invoicing is mandatory</h3>
<p>Revenue Regulations No. 26-2025, issued 16 October 2025, extends the Phase 1 compliance deadline for structured e-invoicing under the Electronic Invoicing/Receipting System (EIS) from 14 March 2026 -- the date set by RR 11-2025 -- to 31 December 2026. The extension covers the taxpayers named under RR 11-2025: e-commerce and internet-transaction businesses of any size, Large Taxpayers Service taxpayers, other large taxpayers under the Ease of Paying Taxes Act, and users of computerized accounting systems with e-invoicing software.</p>
<p>The core requirement is unchanged, only the date has moved: covered taxpayers must issue e-invoices "in a structured data format that can be easily extracted and transmitted electronically" -- PDFs and other non-structured formats will no longer qualify once the deadline arrives. Other categories named in RR 11-2025 -- exporters, Registered Business Enterprises with tax incentives, and POS system users -- will be brought in later, once the BIR has the necessary systems in place.</p>
<p>This is the second time this specific deadline has moved. The mandate''s original 2022 pilot with 100 selected large taxpayers paused for roughly two years after technical and capacity problems, and RR 11-2025''s own March 2026 target lasted less than eight months before RR 26-2025 superseded it. Businesses building compliance timelines around the December 2026 date should treat it as the current official target, not a settled certainty.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-16-philippines-rr26-2025-extension', 'es', 'El BIR concede a los contribuyentes de la Fase 1 nueve meses más antes de que la facturación electrónica sea obligatoria', 'El BIR emitió el Reglamento de Rentas N.º 26-2025, que extiende el plazo de cumplimiento de la Fase 1 de facturación electrónica del 14 de marzo de 2026 al 31 de diciembre de 2026 -- el segundo retraso documentado del mandato tras la pausa de aproximadamente dos años de su piloto de 2022.', '<h3>🇵🇭 El BIR concede a los contribuyentes de la Fase 1 nueve meses más antes de que la facturación electrónica sea obligatoria</h3>
<p>El Reglamento de Rentas N.º 26-2025, emitido el 16 de octubre de 2025, extiende el plazo de cumplimiento de la Fase 1 para la facturación electrónica estructurada bajo el Sistema de Facturación/Recibos Electrónicos (EIS) del 14 de marzo de 2026 -- la fecha fijada por el RR 11-2025 -- al 31 de diciembre de 2026. La extensión cubre a los contribuyentes designados bajo el RR 11-2025: empresas de comercio electrónico y de transacciones por internet de cualquier tamaño, contribuyentes del Servicio de Grandes Contribuyentes, otros grandes contribuyentes bajo la Ley de Facilitación del Pago de Impuestos, y usuarios de sistemas contables computarizados con software de facturación electrónica.</p>
<p>El requisito principal no cambia, solo se movió la fecha: los contribuyentes cubiertos deben emitir facturas electrónicas "en un formato de datos estructurado que pueda extraerse y transmitirse fácilmente de forma electrónica" -- los PDF y otros formatos no estructurados ya no calificarán una vez que llegue el plazo. Otras categorías mencionadas en el RR 11-2025 -- exportadores, Empresas Registradas con incentivos fiscales, y usuarios de sistemas POS -- se incorporarán más adelante, una vez que el BIR tenga listos los sistemas necesarios.</p>
<p>Esta es la segunda vez que este plazo específico se mueve. El piloto original del mandato de 2022 con 100 grandes contribuyentes seleccionados se pausó durante aproximadamente dos años tras problemas técnicos y de capacidad, y el propio objetivo de marzo de 2026 del RR 11-2025 duró menos de ocho meses antes de que el RR 26-2025 lo sustituyera. Las empresas que planifiquen sus cronogramas de cumplimiento en torno a la fecha de diciembre de 2026 deberían tratarla como el objetivo oficial vigente, no como una certeza definitiva.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-16-philippines-rr26-2025-extension', 'de', 'BIR gewährt Phase-1-Steuerpflichtigen neun weitere Monate, bevor E-Invoicing verpflichtend wird', 'Das BIR erließ die Revenue Regulations No. 26-2025 und verschob die Frist zur Einhaltung von Phase 1 der elektronischen Rechnungsstellung vom 14. März 2026 auf den 31. Dezember 2026 -- die zweite dokumentierte Verzögerung des Mandats, nachdem dessen Pilotprojekt von 2022 für rund zwei Jahre pausiert worden war.', '<h3>🇵🇭 BIR gewährt Phase-1-Steuerpflichtigen neun weitere Monate, bevor E-Invoicing verpflichtend wird</h3>
<p>Die am 16. Oktober 2025 erlassene Revenue Regulations No. 26-2025 verlängert die Frist zur Einhaltung von Phase 1 für die strukturierte elektronische Rechnungsstellung im Rahmen des Electronic Invoicing/Receipting System (EIS) vom 14. März 2026 -- dem durch die RR 11-2025 festgelegten Datum -- auf den 31. Dezember 2026. Die Verlängerung gilt für die unter der RR 11-2025 genannten Steuerpflichtigen: E-Commerce- und Internet-Transaktionsunternehmen jeder Größe, Steuerpflichtige des Large Taxpayers Service, weitere Großsteuerpflichtige nach dem Ease-of-Paying-Taxes-Gesetz sowie Nutzer computerisierter Buchhaltungssysteme mit E-Invoicing-Software.</p>
<p>Die Kernanforderung bleibt unverändert, lediglich der Termin hat sich verschoben: Erfasste Steuerpflichtige müssen E-Rechnungen "in einem strukturierten Datenformat, das sich leicht extrahieren und elektronisch übermitteln lässt" ausstellen -- PDFs und andere unstrukturierte Formate gelten nach Ablauf der Frist nicht mehr. Weitere in der RR 11-2025 genannte Kategorien -- Exporteure, registrierte Unternehmen mit Steueranreizen und Nutzer von POS-Systemen -- werden später einbezogen, sobald das BIR die notwendigen Systeme bereitgestellt hat.</p>
<p>Dies ist bereits die zweite Verschiebung dieser konkreten Frist. Das ursprüngliche Pilotprojekt des Mandats von 2022 mit 100 ausgewählten Großsteuerpflichtigen wurde nach technischen Problemen und Kapazitätsengpässen für rund zwei Jahre pausiert, und das eigene Märzziel 2026 der RR 11-2025 hielt weniger als acht Monate, bevor es durch die RR 26-2025 ersetzt wurde. Unternehmen, die ihre Compliance-Zeitpläne rund um den Dezember-2026-Termin aufbauen, sollten ihn als das aktuelle offizielle Ziel behandeln, nicht als endgültig feststehend.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-10-16-philippines-rr26-2025-extension', 'fr', 'Le BIR accorde neuf mois supplémentaires aux contribuables de la Phase 1 avant que la facturation électronique ne devienne obligatoire', 'Le BIR a publié le règlement fiscal n° 26-2025, repoussant l''échéance de conformité de la Phase 1 de facturation électronique du 14 mars 2026 au 31 décembre 2026 -- le deuxième retard documenté du mandat après la suspension d''environ deux ans de son projet pilote de 2022.', '<h3>🇵🇭 Le BIR accorde neuf mois supplémentaires aux contribuables de la Phase 1 avant que la facturation électronique ne devienne obligatoire</h3>
<p>Le règlement fiscal n° 26-2025, publié le 16 octobre 2025, prolonge l''échéance de conformité de la Phase 1 pour la facturation électronique structurée dans le cadre du système Electronic Invoicing/Receipting System (EIS), du 14 mars 2026 -- la date fixée par le RR 11-2025 -- au 31 décembre 2026. La prolongation couvre les contribuables désignés par le RR 11-2025 : entreprises de commerce électronique et de transactions par internet de toute taille, contribuables du Large Taxpayers Service, autres grands contribuables relevant de la loi sur la facilitation du paiement des impôts, et utilisateurs de systèmes comptables informatisés dotés d''un logiciel de facturation électronique.</p>
<p>L''exigence essentielle reste inchangée, seule la date a changé : les contribuables concernés doivent émettre des factures électroniques "dans un format de données structuré pouvant être facilement extrait et transmis électroniquement" -- les PDF et autres formats non structurés ne seront plus valables une fois l''échéance atteinte. D''autres catégories mentionnées dans le RR 11-2025 -- exportateurs, entreprises enregistrées bénéficiant d''incitations fiscales et utilisateurs de systèmes de point de vente -- seront intégrées plus tard, une fois que le BIR disposera des systèmes nécessaires.</p>
<p>C''est la deuxième fois que cette échéance précise est déplacée. Le projet pilote initial du mandat en 2022, avec 100 grands contribuables sélectionnés, avait été suspendu pendant environ deux ans après des problèmes techniques et de capacité, et l''objectif de mars 2026 fixé par le RR 11-2025 lui-même n''a duré que moins de huit mois avant d''être remplacé par le RR 26-2025. Les entreprises qui construisent leurs calendriers de conformité autour de la date de décembre 2026 devraient la considérer comme l''objectif officiel actuel, non comme une certitude définitive.</p>');
