-- Taiwan: milestones + English translations. Mirrors the shape produced by
-- new_country_scaffold.py; INSERT OR IGNORE throughout (idempotent).

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'tw-foreign-provider-vat-2017', id, '2017-05-01', 1, 'https://support.taxually.com/support/solutions/articles/80001216447-taiwan-eguis-explained-egui-obligations-for-foreign-providers-of-digital-services', 0, '[]', NULL, 'none' FROM countries WHERE code = 'TW';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('tw-foreign-provider-vat-2017', 'en', 'Cross-border digital services regime brings foreign providers into VAT/eGUI scope', 'Taiwan''s Regulations Governing the Collection of VAT on Cross-Border Electronic Services Provided by Foreign Enterprises took effect on 1 May 2017, requiring foreign digital service providers that met a registration threshold to register for VAT and begin filing, with electronic Government Uniform Invoice (eGUI) issuance obligations for these registrants following over the next several years. This established the cross-border piece of what became a universal domestic mandate in 2021; it created no obligation yet for domestic businesses.', '["No action required for domestic businesses at this stage.", "Foreign digital service providers selling into Taiwan should confirm whether the registration threshold applies to them."]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'tw-mandate-2021', id, '2021-01-01', 0, 'https://ecosio.com/en/compliance/taiwan/e-invoicing/', 1, '[{"label": "Ministry of Finance E-Invoice Platform", "url": "https://www.einvoice.nat.gov.tw/"}]', NULL, 'b2b' FROM countries WHERE code = 'TW';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('tw-mandate-2021', 'en', 'eGUI becomes mandatory for all business-tax-registered entities', 'From 1 January 2021, all business-tax-registered entities in Taiwan -- domestic and foreign -- must issue electronic Government Uniform Invoices (eGUI) in structured format, covering both B2B and B2C transactions. This is the headline "universal mandate" date: it moved eGUI from a cross-border-only and gradually-adopted requirement to a blanket obligation across the entire tax-registered business population, administered by the Ministry of Finance''s E-Invoice Platform (operated with the Fiscal Information Agency).', '["Confirm your invoicing system issues structured eGUI records via the MOF platform rather than paper or unstructured PDF invoices.", "Register with the Fiscal Information Agency''s e-invoice platform if not already onboarded.", "Foreign businesses without a Taiwan presence should confirm their local agent or certified invoicing partner is filing on their behalf."]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'tw-bta-amendment-2024', id, '2024-08-07', 0, 'https://rtcsuite.com/taiwan-updates-electronic-invoice-procedures-with-new-amendments-to-the-business-tax-act/', 1, '[]', NULL, 'none' FROM countries WHERE code = 'TW';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('tw-bta-amendment-2024', 'en', 'Business Tax Act amendment sets transmission deadlines and penalties', 'An amendment to the Value-Added and Non-Value-Added Business Tax Act, published 3 September 2024, formalized transmission deadlines for eGUIs already in force: B2B invoices must be transmitted to the MOF platform within 7 calendar days, and B2C invoices within 2 calendar days. It also strengthened penalties for late or missing transmission and for inaccurate invoice data, with fines ranging from TWD 1,500 to TWD 15,000 and escalating penalties for repeat violations. This is a procedural and enforcement change -- it does not alter who is covered by the 2021 universal mandate.', '["Confirm your invoicing workflow transmits B2B eGUIs within 7 days and B2C eGUIs within 2 days of issuance.", "Review error-correction procedures -- inaccurate transmitted data can trigger penalties separate from late-transmission fines.", "Budget for fines of TWD 1,500-15,000 per violation as a compliance risk if transmission processes are not automated."]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'tw-mig4-mandatory-2026', id, '2026-01-01', 0, 'https://ecosio.com/en/compliance/taiwan/e-invoicing/', 1, '[]', NULL, 'none' FROM countries WHERE code = 'TW';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('tw-mig4-mandatory-2026', 'en', 'MIG 4.0 becomes the sole valid eGUI format', 'Message Implementation Guideline (MIG) version 4.0 was introduced as the new eGUI XML format standard from 1 January 2024, running in parallel with the older MIG 3.1/3.2 formats through a transition period. That transition period closed on 31 December 2025 -- from 1 January 2026, MIG 3.1/3.2 submissions are no longer accepted and MIG 4.0 is the only valid format for eGUI transmission. This is a technical format upgrade, not a change to who is covered by the mandate.', '["Confirm your invoicing or ERP system''s eGUI output has been upgraded to MIG 4.0 -- MIG 3.1/3.2 submissions are now rejected.", "If a software vendor or certified service provider handles transmission on your behalf, confirm they completed the MIG 4.0 migration before the cutover."]');
