-- Indonesia story arc: 3 stories, spanning the Coretax launch, the
-- PER-11/PJ/2025 deadline change, and a current-development story
-- framed close to today's date (2026-08-05), reflecting Coretax's full
-- enforcement having taken effect eight months earlier on 31 December
-- 2025. Matches the richer-country pattern (Argentina, Colombia,
-- Philippines, Taiwan, Hungary) rather than a single launch post.

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-01-01-indonesia-coretax-launch', '2025-01-01', '2025-01', 'Indonesia''s DJP launched Coretax on 1 January 2025, a new unified platform intended to eventually replace e-Faktur and move the country toward real-time invoice validation -- though early technical issues forced a temporary fallback to the legacy e-Faktur Client Desktop.', '<h3>🇮🇩 Indonesia launches Coretax, its new unified tax platform</h3>
<p>On 1 January 2025, Indonesia''s Directorate General of Taxes (DJP) launched Coretax, a new administration platform intended to eventually replace the e-Faktur Pajak system that has required electronic VAT invoices nationwide since 1 July 2016. Coretax is designed to unify VAT invoicing, filing, and payment in one system, auto-generating each invoice''s Tax Invoice Serial Number (Nomor Seri Faktur Pajak, NSFP) rather than relying on the older, separately-issued numbering under e-Faktur.</p>
<p>The early rollout wasn''t smooth. Technical issues were significant enough that DJP reopened the legacy e-Faktur Client Desktop application as a fallback channel via decree KEP-54/PJ/2025, issued 12 February 2025 -- an acknowledgment that businesses needed a working alternative while Coretax''s own systems stabilized.</p>
<p>Coretax is a genuine step toward a real-time validation model, moving Indonesia closer to the clearance-style regimes already running in Colombia and Argentina, though as of launch DJP had not yet made clearance a strict legal precondition for invoice validity -- that shift came later, from 31 December 2025.</p>', 'https://hanumaglobal.com/mandates/indonesia', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-01-01-indonesia-coretax-launch', id FROM countries WHERE name_en = 'Indonesia';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-01-indonesia-coretax-launch', 'en', 'Indonesia launches Coretax, its new unified tax platform', 'Indonesia''s DJP launched Coretax on 1 January 2025, a new unified platform intended to eventually replace e-Faktur and move the country toward real-time invoice validation -- though early technical issues forced a temporary fallback to the legacy e-Faktur Client Desktop.', '<h3>🇮🇩 Indonesia launches Coretax, its new unified tax platform</h3>
<p>On 1 January 2025, Indonesia''s Directorate General of Taxes (DJP) launched Coretax, a new administration platform intended to eventually replace the e-Faktur Pajak system that has required electronic VAT invoices nationwide since 1 July 2016. Coretax is designed to unify VAT invoicing, filing, and payment in one system, auto-generating each invoice''s Tax Invoice Serial Number (Nomor Seri Faktur Pajak, NSFP) rather than relying on the older, separately-issued numbering under e-Faktur.</p>
<p>The early rollout wasn''t smooth. Technical issues were significant enough that DJP reopened the legacy e-Faktur Client Desktop application as a fallback channel via decree KEP-54/PJ/2025, issued 12 February 2025 -- an acknowledgment that businesses needed a working alternative while Coretax''s own systems stabilized.</p>
<p>Coretax is a genuine step toward a real-time validation model, moving Indonesia closer to the clearance-style regimes already running in Colombia and Argentina, though as of launch DJP had not yet made clearance a strict legal precondition for invoice validity -- that shift came later, from 31 December 2025.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-01-indonesia-coretax-launch', 'es', 'Indonesia lanza Coretax, su nueva plataforma fiscal unificada', 'La DJP de Indonesia lanzó Coretax el 1 de enero de 2025, una nueva plataforma unificada destinada a sustituir eventualmente a e-Faktur y llevar al país hacia la validación de facturas en tiempo real -- aunque los problemas técnicos iniciales obligaron a un respaldo temporal en la aplicación heredada e-Faktur Client Desktop.', '<h3>🇮🇩 Indonesia lanza Coretax, su nueva plataforma fiscal unificada</h3>
<p>El 1 de enero de 2025, la Dirección General de Impuestos de Indonesia (DJP) lanzó Coretax, una nueva plataforma de administración destinada a sustituir eventualmente al sistema e-Faktur Pajak, que exige facturas electrónicas de IVA en todo el país desde el 1 de julio de 2016. Coretax está diseñada para unificar la facturación, la declaración y el pago del IVA en un solo sistema, generando automáticamente el Número de Serie de Factura Fiscal (Nomor Seri Faktur Pajak, NSFP) de cada factura, en lugar de depender de la numeración anterior, emitida por separado bajo e-Faktur.</p>
<p>El despliegue inicial no fue sencillo. Los problemas técnicos fueron lo bastante importantes como para que la DJP reabriera la aplicación heredada e-Faktur Client Desktop como canal de respaldo mediante el decreto KEP-54/PJ/2025, emitido el 12 de febrero de 2025 -- un reconocimiento de que las empresas necesitaban una alternativa funcional mientras se estabilizaban los propios sistemas de Coretax.</p>
<p>Coretax representa un paso real hacia un modelo de validación en tiempo real, acercando a Indonesia a los regímenes de tipo clearance ya vigentes en Colombia y Argentina, aunque en el momento del lanzamiento la DJP todavía no había convertido el clearance en un requisito legal estricto y previo para la validez de la factura -- ese cambio llegó después, a partir del 31 de diciembre de 2025.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-01-indonesia-coretax-launch', 'de', 'Indonesien führt Coretax ein, seine neue einheitliche Steuerplattform', 'Indonesiens DJP führte Coretax am 1. Januar 2025 ein, eine neue einheitliche Plattform, die e-Faktur langfristig ersetzen und das Land näher an eine Echtzeit-Rechnungsvalidierung bringen soll -- allerdings zwangen frühe technische Probleme zu einem vorübergehenden Rückgriff auf die veraltete Anwendung e-Faktur Client Desktop.', '<h3>🇮🇩 Indonesien führt Coretax ein, seine neue einheitliche Steuerplattform</h3>
<p>Am 1. Januar 2025 führte Indonesiens Generaldirektion für Steuern (DJP) Coretax ein, eine neue Verwaltungsplattform, die das System e-Faktur Pajak, das seit dem 1. Juli 2016 landesweit elektronische USt-Rechnungen vorschreibt, langfristig ersetzen soll. Coretax soll USt-Rechnungsstellung, -Einreichung und -Zahlung in einem System vereinen und generiert die Steuerrechnungs-Seriennummer (Nomor Seri Faktur Pajak, NSFP) jeder Rechnung automatisch, statt sich auf die ältere, separat vergebene Nummerierung unter e-Faktur zu verlassen.</p>
<p>Der frühe Rollout verlief nicht reibungslos. Die technischen Probleme waren bedeutend genug, dass die DJP mit dem Erlass KEP-54/PJ/2025 vom 12. Februar 2025 die veraltete Anwendung e-Faktur Client Desktop als Ausweichkanal wieder öffnete -- ein Eingeständnis, dass Unternehmen eine funktionierende Alternative brauchten, während sich Coretax'' eigene Systeme stabilisierten.</p>
<p>Coretax ist ein echter Schritt hin zu einem Echtzeit-Validierungsmodell und bringt Indonesien näher an die bereits in Kolumbien und Argentinien laufenden Freigabemodelle heran, auch wenn die DJP zum Zeitpunkt der Einführung die Freigabe noch nicht zur strengen rechtlichen Voraussetzung für die Rechnungsgültigkeit gemacht hatte -- dieser Wechsel folgte erst später, ab dem 31. Dezember 2025.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-01-01-indonesia-coretax-launch', 'fr', 'L''Indonésie lance Coretax, sa nouvelle plateforme fiscale unifiée', 'La DJP indonésienne a lancé Coretax le 1er janvier 2025, une nouvelle plateforme unifiée destinée à remplacer à terme l''e-Faktur et à rapprocher le pays d''une validation des factures en temps réel -- bien que des problèmes techniques initiaux aient imposé un recours temporaire à l''ancienne application e-Faktur Client Desktop.', '<h3>🇮🇩 L''Indonésie lance Coretax, sa nouvelle plateforme fiscale unifiée</h3>
<p>Le 1er janvier 2025, la Direction générale des impôts d''Indonésie (DJP) a lancé Coretax, une nouvelle plateforme d''administration destinée à remplacer à terme le système e-Faktur Pajak, qui exige des factures électroniques de TVA dans tout le pays depuis le 1er juillet 2016. Coretax est conçue pour unifier la facturation, la déclaration et le paiement de la TVA en un seul système, générant automatiquement le numéro de série de facture fiscale (Nomor Seri Faktur Pajak, NSFP) de chaque facture, plutôt que de dépendre de l''ancienne numérotation, délivrée séparément sous e-Faktur.</p>
<p>Le déploiement initial n''a pas été fluide. Les problèmes techniques ont été suffisamment importants pour que la DJP rouvre l''ancienne application e-Faktur Client Desktop comme canal de secours via le décret KEP-54/PJ/2025, publié le 12 février 2025 -- une reconnaissance que les entreprises avaient besoin d''une alternative fonctionnelle pendant que les propres systèmes de Coretax se stabilisaient.</p>
<p>Coretax constitue une véritable avancée vers un modèle de validation en temps réel, rapprochant l''Indonésie des régimes de type dédouanement déjà en place en Colombie et en Argentine, bien qu''au moment du lancement la DJP n''ait pas encore fait du dédouanement une condition légale stricte et préalable à la validité des factures -- ce basculement est intervenu plus tard, à compter du 31 décembre 2025.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-05-22-indonesia-per11-upload-deadline', '2025-05-22', '2025-05', 'DJP regulation PER-11/PJ/2025 moved the Coretax invoice upload deadline from the 15th to the 20th of the following month -- but a missed deadline now costs the buyer their VAT input tax credit.', '<h3>🇮🇩 PER-11/PJ/2025 gives Coretax users five extra days to upload invoices -- but raises the stakes for missing the deadline</h3>
<p>DJP regulation PER-11/PJ/2025, issued 22 May 2025, changed the deadline for uploading tax invoices to Coretax from the 15th to the 20th of the month following issuance. The regulation, coordinated alongside a related rule (PER-8/PJ/2025), also revised serial and transaction code rules for invoices processed through the platform.</p>
<p>The extra five days are a real, practical concession to businesses still adjusting to Coretax -- but the consequence for missing even the new deadline is unchanged and significant: a tax invoice uploaded after the 20th means the buyer loses eligibility to claim VAT input tax credit on it. For accounts-payable teams, that turns a seller''s late upload into the buyer''s financial problem.</p>
<p>Combined with Coretax''s move toward full enforcement later in 2025, PER-11/PJ/2025 is best read as part of DJP''s broader effort to stabilize the platform''s rules before the clearance model becomes mandatory nationwide.</p>', 'https://muc.co.id/en/article/key-highlights-of-per-11pj2025', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-05-22-indonesia-per11-upload-deadline', id FROM countries WHERE name_en = 'Indonesia';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-05-22-indonesia-per11-upload-deadline', 'en', 'PER-11/PJ/2025 gives Coretax users five extra days to upload invoices -- but raises the stakes for missing the deadline', 'DJP regulation PER-11/PJ/2025 moved the Coretax invoice upload deadline from the 15th to the 20th of the following month -- but a missed deadline now costs the buyer their VAT input tax credit.', '<h3>🇮🇩 PER-11/PJ/2025 gives Coretax users five extra days to upload invoices -- but raises the stakes for missing the deadline</h3>
<p>DJP regulation PER-11/PJ/2025, issued 22 May 2025, changed the deadline for uploading tax invoices to Coretax from the 15th to the 20th of the month following issuance. The regulation, coordinated alongside a related rule (PER-8/PJ/2025), also revised serial and transaction code rules for invoices processed through the platform.</p>
<p>The extra five days are a real, practical concession to businesses still adjusting to Coretax -- but the consequence for missing even the new deadline is unchanged and significant: a tax invoice uploaded after the 20th means the buyer loses eligibility to claim VAT input tax credit on it. For accounts-payable teams, that turns a seller''s late upload into the buyer''s financial problem.</p>
<p>Combined with Coretax''s move toward full enforcement later in 2025, PER-11/PJ/2025 is best read as part of DJP''s broader effort to stabilize the platform''s rules before the clearance model becomes mandatory nationwide.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-05-22-indonesia-per11-upload-deadline', 'es', 'PER-11/PJ/2025 concede cinco días adicionales para cargar facturas en Coretax -- pero eleva el riesgo de incumplir el plazo', 'El reglamento de la DJP PER-11/PJ/2025 trasladó el plazo de carga de facturas en Coretax del día 15 al día 20 del mes siguiente -- pero un plazo incumplido ahora hace que el comprador pierda su crédito fiscal de IVA.', '<h3>🇮🇩 PER-11/PJ/2025 concede cinco días adicionales para cargar facturas en Coretax -- pero eleva el riesgo de incumplir el plazo</h3>
<p>El reglamento de la DJP PER-11/PJ/2025, emitido el 22 de mayo de 2025, cambió el plazo para cargar las facturas fiscales en Coretax del día 15 al día 20 del mes siguiente a su emisión. El reglamento, coordinado junto con una norma relacionada (PER-8/PJ/2025), también revisó las normas de series y códigos de transacción para las facturas procesadas a través de la plataforma.</p>
<p>Los cinco días adicionales son una concesión real y práctica para las empresas que todavía se están adaptando a Coretax -- pero la consecuencia de incumplir incluso el nuevo plazo sigue siendo la misma y significativa: una factura fiscal cargada después del día 20 hace que el comprador pierda la posibilidad de reclamar el crédito fiscal de IVA sobre ella. Para los equipos de cuentas por pagar, esto convierte la carga tardía del vendedor en un problema financiero del comprador.</p>
<p>Junto con el avance de Coretax hacia la plena vigencia más adelante en 2025, la PER-11/PJ/2025 se entiende mejor como parte del esfuerzo más amplio de la DJP por estabilizar las normas de la plataforma antes de que el modelo de clearance se vuelva obligatorio en todo el país.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-05-22-indonesia-per11-upload-deadline', 'de', 'PER-11/PJ/2025 gibt Coretax-Nutzern fünf zusätzliche Tage zum Hochladen von Rechnungen -- erhöht aber die Folgen bei Fristversäumnis', 'Die DJP-Verordnung PER-11/PJ/2025 verschob die Coretax-Hochladefrist für Rechnungen vom 15. auf den 20. des Folgemonats -- doch eine verpasste Frist kostet den Käufer nun seinen USt-Vorsteuerabzug.', '<h3>🇮🇩 PER-11/PJ/2025 gibt Coretax-Nutzern fünf zusätzliche Tage zum Hochladen von Rechnungen -- erhöht aber die Folgen bei Fristversäumnis</h3>
<p>Die DJP-Verordnung PER-11/PJ/2025 vom 22. Mai 2025 änderte die Frist für das Hochladen von Steuerrechnungen auf Coretax vom 15. auf den 20. des auf die Ausstellung folgenden Monats. Die Verordnung, koordiniert mit einer verwandten Regel (PER-8/PJ/2025), überarbeitete zudem die Regeln für Serien- und Transaktionscodes für über die Plattform verarbeitete Rechnungen.</p>
<p>Die fünf zusätzlichen Tage sind ein echtes, praktisches Zugeständnis an Unternehmen, die sich noch auf Coretax einstellen -- doch die Folge bei Verpassen selbst der neuen Frist bleibt unverändert erheblich: Eine erst nach dem 20. hochgeladene Steuerrechnung führt dazu, dass der Käufer die Möglichkeit verliert, den USt-Vorsteuerabzug dafür geltend zu machen. Für Kreditorenbuchhaltungsteams macht das aus einem verspäteten Upload des Verkäufers ein finanzielles Problem des Käufers.</p>
<p>Zusammen mit Coretax'' Weg zur vollständigen Durchsetzung später im Jahr 2025 lässt sich die PER-11/PJ/2025 am besten als Teil der umfassenderen Bemühungen der DJP verstehen, die Regeln der Plattform zu stabilisieren, bevor das Freigabemodell landesweit verpflichtend wird.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-05-22-indonesia-per11-upload-deadline', 'fr', 'PER-11/PJ/2025 accorde cinq jours supplémentaires aux utilisateurs de Coretax pour téléverser leurs factures -- mais durcit les conséquences d''un retard', 'Le règlement de la DJP PER-11/PJ/2025 a déplacé l''échéance de téléversement des factures sur Coretax du 15 au 20 du mois suivant -- mais une échéance manquée fait désormais perdre à l''acheteur son crédit de TVA en amont.', '<h3>🇮🇩 PER-11/PJ/2025 accorde cinq jours supplémentaires aux utilisateurs de Coretax pour téléverser leurs factures -- mais durcit les conséquences d''un retard</h3>
<p>Le règlement de la DJP PER-11/PJ/2025, publié le 22 mai 2025, a déplacé la date limite de téléversement des factures fiscales vers Coretax du 15 au 20 du mois suivant leur émission. Le règlement, coordonné avec une règle connexe (PER-8/PJ/2025), a également révisé les règles de séries et de codes de transaction pour les factures traitées via la plateforme.</p>
<p>Les cinq jours supplémentaires constituent une concession réelle et pratique pour les entreprises encore en train de s''adapter à Coretax -- mais la conséquence d''un manquement, même à la nouvelle échéance, reste inchangée et significative : une facture fiscale téléversée après le 20 fait perdre à l''acheteur le droit de réclamer le crédit de TVA en amont correspondant. Pour les équipes comptes fournisseurs, cela transforme un téléversement tardif du vendeur en un problème financier pour l''acheteur.</p>
<p>Associée à la progression de Coretax vers une entrée en vigueur intégrale plus tard en 2025, la PER-11/PJ/2025 s''inscrit surtout dans l''effort plus large de la DJP pour stabiliser les règles de la plateforme avant que le modèle de dédouanement ne devienne obligatoire dans tout le pays.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-08-04-indonesia-coretax-full-enforcement', '2026-08-04', '2026-08', 'Since Coretax became fully enforced on 31 December 2025, DJP approval has been a legal precondition for a valid tax invoice nationwide -- a genuine shift from e-Faktur''s old post-creation checks, with real consequences for uncleared invoices and late uploads.', '<h3>🇮🇩 Eight months into full Coretax enforcement, DJP clearance is now simply how Indonesian invoicing works</h3>
<p>Indonesia''s e-invoicing story has moved in clear stages: e-Faktur Pajak required electronic VAT invoices for designated taxpayers from 1 April 2014, extended to Java and Bali from 1 July 2015, and became mandatory nationwide from 1 July 2016. That was already one of the more mature e-invoicing mandates in Southeast Asia -- but it was still a post-creation validation model, not a clearance one.</p>
<p>That changed on 31 December 2025, when Coretax -- launched almost exactly a year earlier -- became fully enforced nationwide for nearly all VAT-registered taxpayers (PKP). DJP approval is now a legal precondition for a tax invoice to be valid at all. An invoice DJP hasn''t cleared cannot support the buyer''s VAT input tax deduction, a real and immediate financial consequence rather than a nominal compliance gap.</p>
<p>Eight months on, the practical reality for most PKP is that Coretax clearance has simply become how invoicing works: invoices are created in XML, uploaded for real-time DJP validation, and returned as QR-coded PDFs carrying an auto-generated NSFP. Large taxpayers can still use e-Faktur Desktop or Host-to-Host (H2H) channels, but those now feed into Coretax''s validation rather than operating independently. Businesses that haven''t yet confirmed their invoicing and accounts-payable workflows fully respect this clearance requirement -- and the 20th-of-the-month upload deadline set by PER-11/PJ/2025 -- should treat that as unfinished, not optional, work.</p>', 'https://www.fiscal-requirements.com/news/4767-indonesia-coretax-e-invoicing-mandatory-for-all-vat-registered-taxpayers-by-end-of-2025', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-08-04-indonesia-coretax-full-enforcement', id FROM countries WHERE name_en = 'Indonesia';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-08-04-indonesia-coretax-full-enforcement', 'en', 'Eight months into full Coretax enforcement, DJP clearance is now simply how Indonesian invoicing works', 'Since Coretax became fully enforced on 31 December 2025, DJP approval has been a legal precondition for a valid tax invoice nationwide -- a genuine shift from e-Faktur''s old post-creation checks, with real consequences for uncleared invoices and late uploads.', '<h3>🇮🇩 Eight months into full Coretax enforcement, DJP clearance is now simply how Indonesian invoicing works</h3>
<p>Indonesia''s e-invoicing story has moved in clear stages: e-Faktur Pajak required electronic VAT invoices for designated taxpayers from 1 April 2014, extended to Java and Bali from 1 July 2015, and became mandatory nationwide from 1 July 2016. That was already one of the more mature e-invoicing mandates in Southeast Asia -- but it was still a post-creation validation model, not a clearance one.</p>
<p>That changed on 31 December 2025, when Coretax -- launched almost exactly a year earlier -- became fully enforced nationwide for nearly all VAT-registered taxpayers (PKP). DJP approval is now a legal precondition for a tax invoice to be valid at all. An invoice DJP hasn''t cleared cannot support the buyer''s VAT input tax deduction, a real and immediate financial consequence rather than a nominal compliance gap.</p>
<p>Eight months on, the practical reality for most PKP is that Coretax clearance has simply become how invoicing works: invoices are created in XML, uploaded for real-time DJP validation, and returned as QR-coded PDFs carrying an auto-generated NSFP. Large taxpayers can still use e-Faktur Desktop or Host-to-Host (H2H) channels, but those now feed into Coretax''s validation rather than operating independently. Businesses that haven''t yet confirmed their invoicing and accounts-payable workflows fully respect this clearance requirement -- and the 20th-of-the-month upload deadline set by PER-11/PJ/2025 -- should treat that as unfinished, not optional, work.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-08-04-indonesia-coretax-full-enforcement', 'es', 'Ocho meses después de la plena vigencia de Coretax, el clearance de la DJP es ya sencillamente cómo funciona la facturación indonesia', 'Desde que Coretax pasó a estar plenamente vigente el 31 de diciembre de 2025, la aprobación de la DJP es un requisito legal previo para que una factura fiscal sea válida en todo el país -- un cambio real respecto a las antiguas comprobaciones posteriores a la creación de e-Faktur, con consecuencias reales para las facturas sin aprobar y las cargas tardías.', '<h3>🇮🇩 Ocho meses después de la plena vigencia de Coretax, el clearance de la DJP es ya sencillamente cómo funciona la facturación indonesia</h3>
<p>La historia de la facturación electrónica de Indonesia ha avanzado en etapas claras: el e-Faktur Pajak exigió facturas electrónicas de IVA a contribuyentes designados desde el 1 de abril de 2014, se extendió a Java y Bali desde el 1 de julio de 2015 y se volvió obligatorio en todo el país desde el 1 de julio de 2016. Aquello ya era uno de los mandatos de facturación electrónica más maduros del sudeste asiático -- pero seguía siendo un modelo de validación posterior a la creación, no de clearance.</p>
<p>Eso cambió el 31 de diciembre de 2025, cuando Coretax -- lanzado casi exactamente un año antes -- pasó a estar plenamente vigente en todo el país para prácticamente todos los contribuyentes registrados a efectos de IVA (PKP). La aprobación de la DJP es ahora un requisito legal previo para que una factura fiscal sea válida en absoluto. Una factura que la DJP no haya aprobado no puede sustentar la deducción del IVA soportado del comprador, una consecuencia financiera real e inmediata, no una laguna de cumplimiento nominal.</p>
<p>Ocho meses después, la realidad práctica para la mayoría de los PKP es que el clearance de Coretax se ha convertido sencillamente en cómo funciona la facturación: las facturas se crean en XML, se cargan para su validación en tiempo real por parte de la DJP y se devuelven como PDF con código QR que llevan un NSFP generado automáticamente. Los grandes contribuyentes todavía pueden usar e-Faktur Desktop o los canales Host-to-Host (H2H), pero estos ahora alimentan la validación de Coretax en lugar de operar de forma independiente. Las empresas que todavía no hayan confirmado que sus flujos de facturación y cuentas por pagar respetan plenamente este requisito de clearance -- y el plazo de carga del día 20 del mes establecido por la PER-11/PJ/2025 -- deberían tratarlo como trabajo pendiente, no opcional.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-08-04-indonesia-coretax-full-enforcement', 'de', 'Acht Monate nach der vollständigen Durchsetzung von Coretax ist die DJP-Freigabe schlicht der normale Ablauf der indonesischen Rechnungsstellung', 'Seit Coretax am 31. Dezember 2025 vollständig durchgesetzt wurde, ist die Genehmigung der DJP landesweit eine rechtliche Voraussetzung für eine gültige Steuerrechnung -- ein echter Wechsel gegenüber den alten nachträglichen Prüfungen von e-Faktur, mit realen Folgen für nicht freigegebene Rechnungen und verspätete Uploads.', '<h3>🇮🇩 Acht Monate nach der vollständigen Durchsetzung von Coretax ist die DJP-Freigabe schlicht der normale Ablauf der indonesischen Rechnungsstellung</h3>
<p>Indonesiens E-Rechnungsgeschichte verlief in klaren Etappen: e-Faktur Pajak verlangte ab dem 1. April 2014 elektronische USt-Rechnungen für designierte Steuerpflichtige, weitete sich ab dem 1. Juli 2015 auf Java und Bali aus und wurde ab dem 1. Juli 2016 landesweit verpflichtend. Das war bereits eine der ausgereifteren E-Rechnungspflichten Südostasiens -- aber immer noch ein nachträgliches Validierungsmodell, kein Freigabemodell.</p>
<p>Das änderte sich am 31. Dezember 2025, als Coretax -- fast genau ein Jahr zuvor gestartet -- landesweit für nahezu alle umsatzsteuerlich registrierten Steuerpflichtigen (PKP) vollständig durchgesetzt wurde. Die Genehmigung der DJP ist nun eine rechtliche Voraussetzung dafür, dass eine Steuerrechnung überhaupt gültig ist. Eine von der DJP nicht freigegebene Rechnung kann den USt-Vorsteuerabzug des Käufers nicht stützen -- eine echte und unmittelbare finanzielle Folge, keine nominelle Compliance-Lücke.</p>
<p>Acht Monate später ist für die meisten PKP die praktische Realität, dass die Coretax-Freigabe schlicht zum normalen Ablauf der Rechnungsstellung geworden ist: Rechnungen werden im XML-Format erstellt, zur Echtzeitvalidierung durch die DJP hochgeladen und als PDF mit QR-Code und automatisch generierter NSFP zurückgegeben. Großsteuerpflichtige können weiterhin e-Faktur Desktop oder Host-to-Host-Kanäle (H2H) nutzen, doch diese fließen nun in Coretax'' Validierung ein, statt unabhängig zu arbeiten. Unternehmen, die noch nicht bestätigt haben, dass ihre Rechnungs- und Kreditorenworkflows diese Freigabepflicht -- und die von der PER-11/PJ/2025 festgelegte Hochladefrist zum 20. des Monats -- vollständig einhalten, sollten dies als unerledigte, nicht optionale Aufgabe betrachten.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-08-04-indonesia-coretax-full-enforcement', 'fr', 'Huit mois après l''entrée en vigueur intégrale de Coretax, le dédouanement de la DJP est désormais simplement la façon dont fonctionne la facturation indonésienne', 'Depuis que Coretax est devenu pleinement applicable le 31 décembre 2025, l''approbation de la DJP est une condition légale préalable à la validité d''une facture fiscale dans tout le pays -- un véritable basculement par rapport aux anciens contrôles a posteriori d''e-Faktur, avec des conséquences réelles pour les factures non dédouanées et les téléversements tardifs.', '<h3>🇮🇩 Huit mois après l''entrée en vigueur intégrale de Coretax, le dédouanement de la DJP est désormais simplement la façon dont fonctionne la facturation indonésienne</h3>
<p>L''histoire de la facturation électronique en Indonésie a progressé par étapes claires : l''e-Faktur Pajak a exigé des factures électroniques de TVA pour les contribuables désignés à partir du 1er avril 2014, s''est étendu à Java et Bali à partir du 1er juillet 2015, et est devenu obligatoire dans tout le pays à partir du 1er juillet 2016. C''était déjà l''une des obligations de facturation électronique les plus matures d''Asie du Sud-Est -- mais elle reposait encore sur un modèle de validation a posteriori, non de dédouanement.</p>
<p>Cela a changé le 31 décembre 2025, lorsque Coretax -- lancé presque exactement un an plus tôt -- est devenu pleinement applicable dans tout le pays pour la quasi-totalité des contribuables assujettis à la TVA (PKP). L''approbation de la DJP est désormais une condition légale préalable à la validité même d''une facture fiscale. Une facture que la DJP n''a pas dédouanée ne peut justifier la déduction de la TVA en amont de l''acheteur -- une conséquence financière réelle et immédiate, non un simple écart de conformité symbolique.</p>
<p>Huit mois plus tard, la réalité pratique pour la plupart des PKP est que le dédouanement Coretax est tout simplement devenu la façon dont fonctionne la facturation : les factures sont créées au format XML, téléversées pour une validation en temps réel par la DJP, puis renvoyées sous forme de PDF à code QR portant un NSFP généré automatiquement. Les grands contribuables peuvent encore utiliser e-Faktur Desktop ou les canaux Host-to-Host (H2H), mais ceux-ci alimentent désormais la validation de Coretax plutôt que de fonctionner de manière indépendante. Les entreprises qui n''ont pas encore vérifié que leurs flux de facturation et de comptes fournisseurs respectent pleinement cette exigence de dédouanement -- et l''échéance de téléversement du 20 du mois fixée par la PER-11/PJ/2025 -- doivent considérer cela comme un travail inachevé, non facultatif.</p>');
