-- Ecuador: milestones + English translations. Hand-written, following
-- the Indonesia (357_indonesia_milestones.sql) pattern. Six milestones,
-- live-researched via direct reads of SRI's own resolution PDFs
-- (sri.gob.ec) plus Primicias, El Comercio, AVL Abogados, Sovos, and
-- EDICOM:
--
-- 1. ec-first-mandate-2014 (2014-09-03, anchor, off-board,
--    mandate_scope='b2b') -- Resolution NAC-DGERCGC14-00790 replaces
--    the 2012 voluntary pilot with a real, binding near-real-time
--    validation requirement for designated taxpayer groups. The origin
--    of Ecuador's e-invoicing mandate.
-- 2. ec-base-resolution-2018 (2018-05-22, off-board, mandate_scope=
--    'none') -- Resolution NAC-DGERCGC18-00000233 replaces the 2014
--    resolution with the long-standing base framework, still
--    near-real-time with a 72-hour high-volume allowance. A technical/
--    procedural framework update, not itself a scope change.
-- 3. ec-universal-2022 (2022-11-30, on-board, mandate_scope='b2b') --
--    the "goes universal" flagship milestone: ~100% coverage,
--    1,212,712 taxpayers authorized, with the RIMPE Negocios Populares
--    (income <= $20,000) carve-out noted honestly.
-- 4. ec-emergency-relaxation-2024 (2024-11-05, on-board, mandate_scope=
--    'none') -- Resolution NAC-DGERCGC24-00000035, issued amid
--    Ecuador's national electrical-emergency/blackout crisis, grants a
--    temporary 4-business-day transmission relief. Necessary context
--    for milestone 5.
-- 5. ec-realtime-transmission-2026 (2026-01-01, on-board, mandate_scope=
--    'none') -- the current-news flagship milestone: closes the 2024
--    emergency relaxation, reverting to immediate transmission per
--    Resolutions NAC-DGERCGC25-00000014/017. A tightening within the
--    existing mandate, not a scope expansion -- consistent with how
--    this project classifies similar procedural-tightening milestones
--    elsewhere (Argentina's RG 5616/2024, Czech Republic's EET 2.0).
-- 6. ec-traceability-decree-2026 (2026-06-03, on-board, mandate_scope=
--    'none') -- Executive Decree 398 modernizes traceability/
--    authentication mechanisms, explicitly framed by press coverage as
--    building on the new continuous real-time invoice data stream.

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'ec-first-mandate-2014', id, '2014-09-03', 1, 'https://www.sri.gob.ec/o/sri-portlet-biblioteca-alfresco-internet/descargar?id=NAC-DGERCGC14-00790', 0, '[]', NULL, 'b2b' FROM countries WHERE code = 'EC';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ec-first-mandate-2014', 'en', 'Resolution NAC-DGERCGC14-00790 introduces real-time e-invoicing validation', 'On 3 September 2014 (published 2 October 2014), Ecuador''s Servicio de Rentas Internas (SRI) issued Resolution NAC-DGERCGC14-00790, replacing the voluntary 2012 pilot scheme (Resolution NAC-DGERCGC12-00105) with a real, binding requirement for designated taxpayer groups to transmit electronic invoices to SRI for web-service-based validation at the moment the transaction takes place. This is the origin of Ecuador''s long-running near-real-time e-invoicing mandate -- the old 2012 scheme remained usable only through 31 December 2015 for taxpayers not yet migrated.', '["No action required for this historical milestone -- included for context ahead of the entries below", "If your business predates Ecuador''s e-invoicing rollout, note the requirement widened through further resolutions in 2018 and beyond -- see the following milestones"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'ec-base-resolution-2018', id, '2018-05-22', 0, 'https://www.sri.gob.ec/o/sri-portlet-biblioteca-alfresco-internet/descargar?id=NAC-DGERCGC18-00000233', 0, '[]', NULL, 'none' FROM countries WHERE code = 'EC';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ec-base-resolution-2018', 'en', 'Resolution NAC-DGERCGC18-00000233 replaces the 2014 resolution with the long-standing base framework', 'On 22 May 2018 (published 5 June 2018), SRI issued Resolution NAC-DGERCGC18-00000233, replacing the 2014 resolution while keeping the same near-real-time validation principle, and adding a 72-hour transmission allowance for high-volume issuers. This became the long-standing base resolution that SRI amended repeatedly through 2025 -- a technical and procedural framework update, not itself a change to who is in scope.', '["No action required for this historical milestone -- included for context ahead of the entries below", "If your invoicing software was configured against the 2014 resolution''s rules, confirm it also reflects the 72-hour allowance introduced here"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'ec-universal-2022', id, '2022-11-30', 0, 'https://www.sri.gob.ec/facturacion-electronica', 1, '[{"label": "SRI — Facturación Electrónica", "url": "https://www.sri.gob.ec/facturacion-electronica"}]', NULL, 'b2b' FROM countries WHERE code = 'EC';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ec-universal-2022', 'en', 'Electronic invoicing reaches effectively universal coverage', 'By 29-30 November 2022, SRI had authorized 1,212,712 taxpayers for electronic invoicing, following waves of sector- and threshold-based mandatory rollout through 2020-2022 (heavy machinery and LPG distributors in 2020, B2G supplies over $1,000 in 2021, the RIMPE simplified regime created 1 January 2022, and the $200,000-$300,000 income bracket in 2022). Coverage is effectively universal outside one carve-out: RIMPE ''Negocios Populares'' taxpayers (income up to $20,000) remain exempt and may still use paper ''notas de venta RISE'' -- only RIMPE ''Emprendedores'' (up to $300,000) and larger taxpayers are actually obligated to issue electronic invoices.', '["Confirm which RIMPE category your business falls into -- Negocios Populares remains exempt, but Emprendedores and above must issue electronic invoices", "If you supply goods or services to Negocios Populares counterparties, don''t assume every Ecuadorian trading partner is on electronic invoicing"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'ec-emergency-relaxation-2024', id, '2024-11-05', 0, 'https://www.sri.gob.ec/o/sri-portlet-biblioteca-alfresco-internet/descargar?id=NAC-DGERCGC24-00000035', 1, '[{"label": "SRI — Facturación Electrónica", "url": "https://www.sri.gob.ec/facturacion-electronica"}]', NULL, 'none' FROM countries WHERE code = 'EC';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ec-emergency-relaxation-2024', 'en', 'SRI grants a temporary 4-business-day transmission window amid the national electrical emergency', 'On 5 November 2024, amid Ecuador''s national electrical-emergency and blackout crisis, SRI issued Resolution NAC-DGERCGC24-00000035, relaxing the standing immediate-transmission rule to allow electronic documents to be transmitted immediately, or within a maximum of 4 business days of being generated. This was explicitly framed as a temporary relief measure responding to the power crisis, not a further tightening of the mandate -- and it was closed out just over a year later (see the January 2026 milestone).', '["If your business relied on the 4-business-day window during 2024-2025, confirm your processes have since reverted to immediate transmission -- see the January 2026 milestone", "Don''t assume this relief measure is still in effect; it was a temporary, crisis-specific allowance"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'ec-realtime-transmission-2026', id, '2026-01-01', 0, 'https://www.sri.gob.ec/o/sri-portlet-biblioteca-alfresco-internet/descargar?id=e98fc8a6-299e-4ea9-8de7-2f6c70dbb4f5&nombre=NAC-DGERCGC25-00000017.pdf', 1, '[{"label": "SRI — Facturación Electrónica", "url": "https://www.sri.gob.ec/facturacion-electronica"}]', NULL, 'none' FROM countries WHERE code = 'EC';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ec-realtime-transmission-2026', 'en', 'Immediate transmission becomes mandatory again, closing the 2024 emergency relaxation', 'From 1 January 2026, the 4-business-day transmission allowance granted in November 2024 during the electrical emergency was eliminated, reverting Ecuador to its standing immediate-transmission baseline. The change was originally set to take effect 1 August 2025 under Resolution NAC-DGERCGC25-00000014 (which deleted the ''or up to a maximum of four business days'' clause from Article 7), but Resolution NAC-DGERCGC25-00000017 (29-30 July 2025) deferred its effective date to 1 January 2026, giving taxpayers roughly five extra months to adjust, and also shortened the cancellation-window deadline from the 10th to the 7th of the following month. This is a genuine tightening -- closing a temporary emergency-era relaxation, not introducing real-time reporting for the first time, since near-real-time transmission has been Ecuador''s standing rule since 2014. ''Consumidor final'' invoices also became non-cancellable from this date.', '["Confirm your invoicing systems transmit to SRI immediately again, not on the now-eliminated 4-business-day emergency window", "Update your invoice-cancellation workflows to the new 7th-of-the-following-month deadline for ''consumidor final'' documents"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope) SELECT 'ec-traceability-decree-2026', id, '2026-06-03', 0, 'https://www.elcomercio.com/', 1, '[{"label": "SRI — Facturación Electrónica", "url": "https://www.sri.gob.ec/facturacion-electronica"}]', NULL, 'none' FROM countries WHERE code = 'EC';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ec-traceability-decree-2026', 'en', 'Executive Decree 398 modernizes traceability and authentication for goods and services', 'On 3 June 2026, Ecuador''s government issued Executive Decree 398, modernizing traceability and authentication mechanisms for goods and certain services. Press coverage (El Comercio) explicitly frames the decree as building on the continuous, real-time invoice data stream SRI now receives -- since immediate transmission was restored in January 2026 -- to enable ongoing tax monitoring rather than the older model of reviewing data only after periodic declarations were filed.', '["Watch for implementing regulations detailing which goods and services fall under the new traceability requirements", "If your business handles goods subject to traceability rules, expect SRI''s monitoring of your invoice data to become more continuous, not just point-in-time at filing"]');
