-- Migration 409: German/Spanish/French translation sync for the 23
-- milestones whose system/desc content was corrected in migration 408.
--
-- Migration 408 fixed the EN content (and, where the underlying claim was
-- wrong, the date/source_url) for 37 flagged milestones, but only updated
-- the lang='en' row on milestone_translations. This migration brings the
-- de/es/fr rows for the 23 of those 37 whose system/desc actually changed
-- back into sync with the corrected English -- translated fresh from the
-- corrected EN text (not patched from the old, now-wrong translations),
-- preserving proper nouns, legal citation numbers/names, currency figures,
-- and technical standard names untranslated per this project's convention.

UPDATE milestone_translations SET system = 'Noch kein formeller inländischer B2B-Vorschlag; BMF signalisiert allgemeine Richtung', desc = 'Österreich hat heute keine inländische B2B-E-Rechnungs- oder Echtzeitmeldepflicht — strukturierte B2B-Rechnungsstellung bleibt freiwillig, wenn auch weit verbreitet, insbesondere bei Unternehmen mit EU-Handelspartnern, die bereits verpflichtenden Regelungen unterliegen. Das Finanzministerium (BMF) hat signalisiert, dass es möglicherweise künftig einen Peppol-basierten Ansatz verfolgen wird, analog zu Belgien und den Niederlanden, doch Stand August 2026 wurden weder ein formeller Vorschlag noch eine Konsultation oder ein konkreter Zeitplan veröffentlicht.' WHERE milestone_id = 'at-b2b-proposal-2026' AND lang = 'de';
UPDATE milestone_translations SET system = 'Aún no hay una propuesta formal de B2B nacional; el BMF señala una dirección general', desc = 'Austria no tiene hoy ningún mandato nacional de facturación electrónica B2B ni de reporte en tiempo real — la facturación estructurada B2B sigue siendo voluntaria, aunque ampliamente adoptada, especialmente entre empresas con socios comerciales de la UE ya sujetos a regímenes obligatorios. El Ministerio de Hacienda (BMF) ha señalado que podría adoptar eventualmente un enfoque basado en Peppol, siguiendo el ejemplo de Bélgica y los Países Bajos, pero a agosto de 2026 no se ha publicado ninguna propuesta formal, consulta ni cronograma específico.' WHERE milestone_id = 'at-b2b-proposal-2026' AND lang = 'es';
UPDATE milestone_translations SET system = 'Aucune proposition B2B nationale formelle pour l''instant ; le BMF indique une orientation générale', desc = 'L''Autriche n''a aujourd''hui aucune obligation nationale de facturation électronique B2B ni de déclaration en temps réel — la facturation structurée B2B reste volontaire, bien que largement adoptée, notamment parmi les entreprises ayant des partenaires commerciaux européens déjà soumis à des régimes obligatoires. Le ministère des Finances (BMF) a signalé qu''il pourrait éventuellement adopter une approche basée sur Peppol, à l''instar de la Belgique et des Pays-Bas, mais à ce jour, en août 2026, aucune proposition formelle, consultation ni calendrier précis n''a été publié.' WHERE milestone_id = 'at-b2b-proposal-2026' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Das australische Finanzamt (ATO) macht die E-Rechnung zur Standardmethode für den Rechnungsaustausch für Non-Corporate Commonwealth Entities, im Zuge des umfassenderen Wandels hin zur vollständigen Automatisierung, als Teil einer Strategie zur Senkung des Verwaltungsaufwands und zur Beschleunigung der Zahlungszyklen.' WHERE milestone_id = 'au-default-2025' AND lang = 'de';
UPDATE milestone_translations SET desc = 'La Oficina de Impuestos de Australia (ATO) convierte la facturación electrónica en el método predeterminado de intercambio de facturas para las Entidades del Commonwealth No Corporativas, junto con el cambio más amplio hacia la automatización completa, como parte de una estrategia para reducir la carga administrativa y acelerar los ciclos de pago.' WHERE milestone_id = 'au-default-2025' AND lang = 'es';
UPDATE milestone_translations SET desc = 'L''administration fiscale australienne (ATO) fait de la facturation électronique la méthode d''échange de factures par défaut pour les Non-Corporate Commonwealth Entities, dans le cadre d''une transition plus large vers l''automatisation complète, ainsi que d''une stratégie visant à réduire la charge administrative et à accélérer les cycles de paiement.' WHERE milestone_id = 'au-default-2025' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'November 2022: Verträge/Konzessionen ≥215.000 €. Mai 2023: ≥30.000 €. November 2023: unter 30.000 €. März 2024: alle föderalen öffentlichen Verträge und Konzessionen über 3.000 €, womit die EU-Richtlinie 2014/55/EU vollständig umgesetzt wird.' WHERE milestone_id = 'be-b2g-phasein' AND lang = 'de';
UPDATE milestone_translations SET desc = 'Noviembre de 2022: contratos/concesiones ≥215.000 €. Mayo de 2023: ≥30.000 €. Noviembre de 2023: por debajo de 30.000 €. Marzo de 2024: todos los contratos y concesiones públicos federales superiores a 3.000 €, transponiendo íntegramente la Directiva UE 2014/55/UE.' WHERE milestone_id = 'be-b2g-phasein' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Novembre 2022 : contrats/concessions ≥215 000 €. Mai 2023 : ≥30 000 €. Novembre 2023 : en dessous de 30 000 €. Mars 2024 : tous les contrats et concessions publics fédéraux supérieurs à 3 000 €, transposant intégralement la directive UE 2014/55/UE.' WHERE milestone_id = 'be-b2g-phasein' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Belgiens zentrale Anlaufstelle für die elektronische Rechnungsstellung zwischen Unternehmen und Behörden geht live, von Anfang an auf dem Peppol-Netzwerk aufgebaut und angetrieben von der Integrationstechnologie von Babelway — dieselbe Infrastruktur, die das B2B-Mandat 2026 später erweitern würde.' WHERE milestone_id = 'be-mercurius' AND lang = 'de';
UPDATE milestone_translations SET desc = 'El centro central de Bélgica para la facturación electrónica entre empresas y administración pública entra en funcionamiento, construido sobre la red Peppol desde el principio y impulsado por la tecnología de integración de Babelway — la misma infraestructura que el mandato B2B de 2026 ampliaría más tarde.' WHERE milestone_id = 'be-mercurius' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Le pôle central belge pour la facturation électronique entre entreprises et administration entre en service, construit dès le départ sur le réseau Peppol et propulsé par la technologie d''intégration de Babelway — la même infrastructure que l''obligation B2B de 2026 étendra plus tard.' WHERE milestone_id = 'be-mercurius' AND lang = 'fr';

UPDATE milestone_translations SET system = 'Verpflichtende Meldung der IBS/CBS-Felder beginnt (informative Phase)', desc = 'Gemäß Technischer Note 2025.002-RTC v1.40 müssen Steuerzahler des allgemeinen Steuerregimes IBS- und CBS-Gruppen in NF-e und NFC-e melden — die gemeldeten Werte bleiben in dieser Phase jedoch rein informativ und ohne steuerliche Wirkung, vor der vollständigen Durchsetzung später im Jahr 2026.' WHERE milestone_id = 'br-mandatory' AND lang = 'de';
UPDATE milestone_translations SET system = 'Comienza el reporte obligatorio de los campos IBS/CBS (fase informativa)', desc = 'Según la Nota Técnica 2025.002-RTC v1.40, los contribuyentes del Régimen Tributario General deben reportar los grupos IBS y CBS en NF-e y NFC-e — aunque durante este período las cifras reportadas siguen siendo únicamente informativas, sin efectos fiscales, antes de la plena entrada en vigor a finales de 2026.' WHERE milestone_id = 'br-mandatory' AND lang = 'es';
UPDATE milestone_translations SET system = 'Début du signalement obligatoire des champs IBS/CBS (phase informative)', desc = 'Selon la Note Technique 2025.002-RTC v1.40, les contribuables du régime fiscal général doivent déclarer les groupes IBS et CBS dans les NF-e et NFC-e — bien que, durant cette période, les chiffres déclarés restent purement informatifs et sans effet fiscal, avant l''application intégrale plus tard en 2026.' WHERE milestone_id = 'br-mandatory' AND lang = 'fr';

UPDATE milestone_translations SET system = 'CRA beginnt mit der Untersuchung der Machbarkeit der elektronischen Rechnungsstellung', desc = 'Die kanadische Steuerbehörde (CRA) beginnt mit vorläufigen Untersuchungen zur Machbarkeit einer inländischen B2B-E-Rechnungspflicht, vor der Einbindung von Interessenträgern, die später im selben Jahr folgt.' WHERE milestone_id = 'ca-cra-research-2018' AND lang = 'de';
UPDATE milestone_translations SET system = 'La CRA comienza a investigar la viabilidad de la facturación electrónica', desc = 'La Agencia de Ingresos de Canadá (CRA) inicia una investigación preliminar sobre la viabilidad de un mandato nacional de facturación electrónica B2B, antes de la consulta con las partes interesadas que tiene lugar más adelante ese mismo año.' WHERE milestone_id = 'ca-cra-research-2018' AND lang = 'es';
UPDATE milestone_translations SET system = 'L''ARC commence à étudier la faisabilité de la facturation électronique', desc = 'L''Agence du revenu du Canada (ARC) entame une recherche préliminaire sur la faisabilité d''une obligation nationale de facturation électronique B2B, avant la concertation avec les parties prenantes qui suit plus tard dans l''année.' WHERE milestone_id = 'ca-cra-research-2018' AND lang = 'fr';

UPDATE milestone_translations SET system = 'Ministerialerlass 188/2020 und erste E-Rechnungs-Welle', desc = 'Der Ministerialerlass Nr. 188/2020 (26. März 2020) schuf die Rechtsgrundlage für Ägyptens elektronisches Rechnungsstellungsregime und verlieh elektronischen Signaturen dieselbe Rechtswirkung wie handschriftlichen; das umfassendere Gesetz über einheitliche Steuerverfahren (206/2020) bekräftigte die Pflicht später zusätzlich. Die erste Welle von Großsteuerzahlern, die beim Großsteuerzahler-Zentrum der ETA registriert waren, begann im November 2020 mit der verpflichtenden elektronischen Rechnungsstellung — der Auftakt eines stufenweisen Rollouts, der schließlich jedes umsatzsteuerregistrierte Unternehmen erreichen sollte.' WHERE milestone_id = 'eg-law-2020' AND lang = 'de';
UPDATE milestone_translations SET system = 'Decreto Ministerial 188/2020 y primera ola de facturación electrónica', desc = 'El Decreto Ministerial n.º 188/2020 (26 de marzo de 2020) estableció la base legal del régimen de facturación electrónica de Egipto, otorgando a las firmas electrónicas el mismo valor legal que a las manuscritas; la más amplia Ley de Procedimientos Tributarios Unificados (206/2020) reforzó posteriormente el mandato. La primera ola de grandes contribuyentes registrados en el Centro de Grandes Contribuyentes de la ETA comenzó la facturación electrónica obligatoria en noviembre de 2020, abriendo un despliegue por fases que acabaría alcanzando a todas las empresas registradas a efectos de IVA.' WHERE milestone_id = 'eg-law-2020' AND lang = 'es';
UPDATE milestone_translations SET system = 'Décret ministériel 188/2020 et première vague de facturation électronique', desc = 'Le décret ministériel n° 188/2020 (26 mars 2020) a établi la base légale du régime de facturation électronique de l''Égypte, conférant aux signatures électroniques la même valeur juridique qu''aux signatures manuscrites ; la loi plus large sur les procédures fiscales unifiées (206/2020) est venue renforcer par la suite cette obligation. La première vague de grands contribuables enregistrés auprès du Centre des grands contribuables de l''ETA a commencé la facturation électronique obligatoire en novembre 2020, ouvrant un déploiement par phases qui finirait par atteindre toutes les entreprises assujetties à la TVA.' WHERE milestone_id = 'eg-law-2020' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Die Mitgliedstaaten müssen die Bestimmungen zur einheitlichen USt-Registrierung (Single VAT Registration, SVR) der ViDA-Richtlinie bis zu diesem Datum in nationales Recht umsetzen. Diese Frist betrifft ausschließlich den SVR-Bereich — sie unterscheidet sich von den Umsetzungsfristen für ViDAs Plattformwirtschafts-Bereich (2028) und den Bereich E-Invoicing/Digitale Meldepflichten (2030) und liegt zeitlich vor diesen.' WHERE milestone_id = 'eu-transpose' AND lang = 'de';
UPDATE milestone_translations SET desc = 'Los Estados miembros deben transponer las disposiciones del Registro Único de IVA (SVR) de la Directiva ViDA a su legislación nacional antes de esta fecha. Este plazo es específico del pilar SVR — es distinto de, y anterior a, los calendarios de transposición del pilar de economía de plataformas de ViDA (2028) y de su pilar de facturación electrónica / Requisitos de Reporte Digital (2030).' WHERE milestone_id = 'eu-transpose' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Les États membres doivent transposer les dispositions relatives à l''immatriculation unique à la TVA (Single VAT Registration, SVR) de la directive ViDA dans leur droit national avant cette date. Cette échéance concerne spécifiquement le pilier SVR — elle est distincte des calendriers de transposition du pilier économie de plateformes de ViDA (2028) et de son pilier facturation électronique / obligations de déclaration numérique (2030), et leur est antérieure.' WHERE milestone_id = 'eu-transpose' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Ab dem 1. Juli 2014 verlangte Indonesiens Generaldirektion für Steuern (DJP) von einer ersten Gruppe designierter umsatzsteuerlich registrierter Steuerpflichtiger (Pengusaha Kena Pajak, PKP), e-Faktur Pajak -- eine elektronische Mehrwertsteuerrechnung -- statt Papierrechnungen auszustellen. Dies war der Ursprung von Indonesiens langjähriger Entwicklung hin zur verpflichtenden E-Rechnung, auch wenn die Pflicht zu diesem Zeitpunkt nur für eine begrenzte, von der DJP designierte Gruppe von Steuerpflichtigen galt, nicht für die gesamte umsatzsteuerlich registrierte Bevölkerung.' WHERE milestone_id = 'id-efaktur-mandatory-2014' AND lang = 'de';
UPDATE milestone_translations SET desc = 'A partir del 1 de julio de 2014, la Dirección General de Impuestos de Indonesia (DJP) exigió a un primer grupo de contribuyentes registrados a efectos de IVA designados (Pengusaha Kena Pajak, PKP) que emitieran e-Faktur Pajak -- una factura electrónica de impuesto al valor agregado -- en lugar de facturas en papel. Este fue el origen del largo camino de Indonesia hacia la facturación electrónica obligatoria, aunque en esta etapa el requisito se aplicaba solo a un conjunto limitado de contribuyentes designados por la DJP, no a toda la población registrada a efectos de IVA.' WHERE milestone_id = 'id-efaktur-mandatory-2014' AND lang = 'es';
UPDATE milestone_translations SET desc = 'À compter du 1er juillet 2014, la Direction générale des impôts d''Indonésie (DJP) a exigé d''un premier groupe de contribuables assujettis à la TVA désignés (Pengusaha Kena Pajak, PKP) qu''ils émettent des e-Faktur Pajak -- une facture électronique de taxe sur la valeur ajoutée -- plutôt que des factures papier. Ce fut l''origine de la longue transition de l''Indonésie vers la facturation électronique obligatoire, bien qu''à ce stade l''obligation ne s''appliquait qu''à un ensemble limité de contribuables désignés par la DJP, et non à l''ensemble des assujettis à la TVA.' WHERE milestone_id = 'id-efaktur-mandatory-2014' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Die Schwelle sank auf 10.000 NIS und übersprang damit die ursprünglich geplante Zwischenstufe von 15.000 NIS -- Teil einer im Dezember 2025 beschlossenen Beschleunigung im Rahmen des Gesetzes zur Erreichung der Haushaltsziele und Umsetzung der Wirtschaftspolitik für das Haushaltsjahr 2025, die den gesetzlich als fünfjährigen Rollout bis 2028 vorgesehenen Zeitplan auf zwei Jahre verkürzte und Mitte 2026 abschließt.' WHERE milestone_id = 'il-phase3-10k' AND lang = 'de';
UPDATE milestone_translations SET desc = 'El umbral bajó a 10.000 NIS, saltándose el escalón de 15.000 NIS previsto originalmente -- parte de una aceleración de diciembre de 2025 en el marco de la Ley para el Logro de los Objetivos Presupuestarios y la Implementación de la Política Económica para el Ejercicio Fiscal 2025, que comprimió en dos años lo que se había legislado como un despliegue de cinco años hasta 2028, concluyendo a mediados de 2026.' WHERE milestone_id = 'il-phase3-10k' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Le seuil est tombé à 10 000 NIS, sautant l''étape de 15 000 NIS initialement prévue -- dans le cadre d''une accélération de décembre 2025 au titre de la loi relative à la réalisation des objectifs budgétaires et à la mise en œuvre de la politique économique pour l''exercice budgétaire 2025, qui a comprimé en deux ans ce qui avait été légiféré comme un déploiement sur cinq ans jusqu''en 2028, pour s''achever mi-2026.' WHERE milestone_id = 'il-phase3-10k' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Eine Kulanzfrist, in der aufgelaufene Bußgelder für Unternehmen erlassen wurden, die sich verspätet registrierten, endete an diesem Datum. Ab jetzt gilt das vollständige Bußgeldregime ohne Ausnahme: Bußgelder von etwa JOD 500 pro Verstoß gemäß der Abrechnungs- und Kontrollverordnung, zuzüglich Ausschluss von öffentlichen Ausschreibungen und Ungültigkeit nicht konformer Rechnungen für den Vorsteuerabzug.' WHERE milestone_id = 'jo-penalty-grace-end' AND lang = 'de';
UPDATE milestone_translations SET desc = 'Un periodo de gracia que eximía de las multas acumuladas a las empresas que se registraron tarde se cerró en esta fecha. A partir de aquí, se aplica el régimen sancionador completo sin excepción: multas de aproximadamente JOD 500 por infracción según el Reglamento de Facturación y Control, además de la exclusión de las licitaciones públicas y la invalidación de las facturas no conformes a efectos de la deducción del IVA.' WHERE milestone_id = 'jo-penalty-grace-end' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Un délai de grâce exonérant des amendes accumulées les entreprises enregistrées tardivement a pris fin à cette date. Désormais, le régime de sanctions complet s''applique sans exception : amendes d''environ 500 JOD par infraction selon le règlement sur la facturation et le contrôle, ainsi que l''exclusion des marchés publics et l''invalidation des factures non conformes aux fins de la déduction de la TVA.' WHERE milestone_id = 'jo-penalty-grace-end' AND lang = 'fr';

UPDATE milestone_translations SET system = 'Vorschlag: Ausstellung von B2B-E-Rechnungen beginnt für Großunternehmen', desc = 'Große Unternehmen müssten strukturierte inländische B2B-E-Rechnungen über Peppol nicht nur empfangen, sondern auch ausstellen — ab demselben Datum, an dem die Empfangspflicht in Kraft tritt. Mittlere Unternehmen folgen sechs Monate später, ab dem 1. Juli 2028.' WHERE milestone_id = 'lx-b2b-issue-large' AND lang = 'de';
UPDATE milestone_translations SET system = 'Propuesta: comienza la emisión de facturas electrónicas B2B para grandes empresas', desc = 'Las empresas grandes estarían obligadas a emitir, y no solo recibir, facturas electrónicas B2B nacionales estructuradas a través de Peppol — a partir de la misma fecha en que entre en vigor la obligación de recepción. Las empresas medianas seguirán seis meses después, a partir del 1 de julio de 2028.' WHERE milestone_id = 'lx-b2b-issue-large' AND lang = 'es';
UPDATE milestone_translations SET system = 'Proposition : début de l''émission de factures électroniques B2B pour les grandes entreprises', desc = 'Les grandes entreprises seraient tenues d''émettre, et pas seulement de recevoir, des factures électroniques B2B nationales structurées via Peppol — à compter de la même date que celle de l''entrée en vigueur de l''obligation de réception. Les moyennes entreprises suivront six mois plus tard, à partir du 1er juillet 2028.' WHERE milestone_id = 'lx-b2b-issue-large' AND lang = 'fr';

UPDATE milestone_translations SET system = 'Konsultationspapier veröffentlicht' WHERE milestone_id = 'no-consultation-2024' AND lang = 'de';
UPDATE milestone_translations SET system = 'Se publica el documento de consulta' WHERE milestone_id = 'no-consultation-2024' AND lang = 'es';
UPDATE milestone_translations SET system = 'Document de consultation publié' WHERE milestone_id = 'no-consultation-2024' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Die Government Procurement Rules (fünfte Ausgabe) treten in Kraft und aktualisieren formell die Beschaffungspraxis des öffentlichen Sektors – die darin eingeführte spezifische E-Rechnungspflicht für große Lieferanten bindet die Behörden jedoch erst ab dem 1. Januar 2027.' WHERE milestone_id = 'nz-5th-edition-effect-2025' AND lang = 'de';
UPDATE milestone_translations SET desc = 'Las Government Procurement Rules (Quinta Edición) entran en vigor, actualizando formalmente la práctica de contratación del sector público, aunque el requisito específico de facturación electrónica para grandes proveedores que introducen no será vinculante para los organismos hasta el 1 de enero de 2027.' WHERE milestone_id = 'nz-5th-edition-effect-2025' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Les Government Procurement Rules (cinquième édition) entrent en vigueur, mettant formellement à jour la pratique de passation des marchés du secteur public — bien que l''exigence spécifique de facturation électronique pour les grands fournisseurs qu''elles introduisent ne s''impose aux organismes qu''à compter du 1er janvier 2027.' WHERE milestone_id = 'nz-5th-edition-effect-2025' AND lang = 'fr';

UPDATE milestone_translations SET system = 'Phase 4 (staatliche Gegenparteien) – Termin noch nicht bestätigt', desc = 'Die letzte Phase des Rollouts soll Regierungsstellen schließlich vollständig als E-Rechnungs-Gegenparteien einbeziehen und damit Omans gestaffelte Fawtara-Umsetzung abschließen – doch mit Stand Mitte 2026 hat die OTA für diese Phase noch kein bestätigtes Datum bekannt gegeben.' WHERE milestone_id = 'om-phase4-b2g' AND lang = 'de';
UPDATE milestone_translations SET system = 'Fase 4 (contrapartes gubernamentales) — fecha aún no confirmada', desc = 'Se espera que la fase final del despliegue incorpore finalmente a los organismos gubernamentales por completo como contrapartes de facturación electrónica, completando la implementación por fases de Fawtara en Omán — pero, a mediados de 2026, la OTA aún no ha anunciado una fecha confirmada para esta fase.' WHERE milestone_id = 'om-phase4-b2g' AND lang = 'es';
UPDATE milestone_translations SET system = 'Phase 4 (contreparties gouvernementales) — date non encore confirmée', desc = 'La dernière phase du déploiement devrait à terme intégrer pleinement les organismes gouvernementaux en tant que contreparties de facturation électronique, achevant ainsi la mise en œuvre échelonnée de Fawtara à Oman — mais, à la mi-2026, l''OTA n''a pas encore annoncé de date confirmée pour cette phase.' WHERE milestone_id = 'om-phase4-b2g' AND lang = 'fr';

UPDATE milestone_translations SET system = 'RR 8-2022 macht E-Invoicing für bestimmte Steuerpflichtigenkategorien verpflichtend', desc = 'Die Revenue Regulations Nr. 8-2022 (RR 8-2022) erließen die ersten Durchführungsvorschriften zu den E-Invoicing-Bestimmungen des TRAIN-Gesetzes und machten E-Invoicing/E-Receipting ab dem 1. Juli 2022 für Exporteure, E-Commerce-Betreiber und Mitglieder des Large Taxpayers Service verpflichtend, wobei zunächst rund 100 Großsteuerpflichtige in das Electronic Invoicing/Receipting System (EIS) aufgenommen wurden. Technische Probleme und Kapazitätsengpässe zwangen die BIR, das Programm noch im selben Jahr zu pausieren; es blieb rund zwei Jahre lang ausgesetzt, bevor es unter der RR 11-2025 formell wieder aufgenommen wurde.' WHERE milestone_id = 'ph-lt100-pilot-2022' AND lang = 'de';
UPDATE milestone_translations SET system = 'La RR 8-2022 hace obligatoria la facturación electrónica para categorías designadas de contribuyentes', desc = 'El Reglamento de Rentas N.º 8-2022 (RR 8-2022) emitió las primeras reglas de implementación de las disposiciones de facturación electrónica de la ley TRAIN, haciendo obligatoria la facturación/recepción electrónica desde el 1 de julio de 2022 para los exportadores, los operadores de comercio electrónico y los miembros del Large Taxpayers Service, con aproximadamente 100 grandes contribuyentes incorporados inicialmente al Sistema de Facturación/Recibos Electrónicos (EIS). Problemas técnicos y de capacidad obligaron a la BIR a pausar el programa más adelante ese mismo año, y permaneció estancado durante aproximadamente dos años antes de reanudarse formalmente bajo la RR 11-2025.' WHERE milestone_id = 'ph-lt100-pilot-2022' AND lang = 'es';
UPDATE milestone_translations SET system = 'Le RR 8-2022 rend la facturation électronique obligatoire pour des catégories désignées de contribuables', desc = 'Le règlement fiscal n° 8-2022 (RR 8-2022) a publié les premières règles d''application des dispositions de facturation électronique de la loi TRAIN, rendant la facturation/réception électronique obligatoire à compter du 1er juillet 2022 pour les exportateurs, les opérateurs de commerce électronique et les membres du Large Taxpayers Service, environ 100 grands contribuables ayant été initialement intégrés au système de facturation/réception électronique (EIS). Des problèmes techniques et de capacité ont contraint le BIR à suspendre le programme plus tard la même année, et celui-ci est resté à l''arrêt pendant environ deux ans avant de reprendre formellement sous le RR 11-2025.' WHERE milestone_id = 'ph-lt100-pilot-2022' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Die Rechnungsstellung des öffentlichen Sektors läuft über Peppol via die PEF-Plattform, vollständig getrennt von der KSeF-Plattform, die später B2B übernehmen sollte – die beiden Systeme teilen sich keine Infrastruktur. Die Verpflichtung zur Annahme von E-Rechnungen wurde stufenweise ab dem 18. April 2019 (Aufträge ≥ 30.000 €) bis zum 1. August 2019 (alle öffentlichen Auftraggeber) eingeführt, gemäß dem Gesetz vom 9. November 2018.' WHERE milestone_id = 'pl-b2g-peppol' AND lang = 'de';
UPDATE milestone_translations SET desc = 'La facturación del sector público funciona sobre Peppol a través de la plataforma PEF, completamente separada de la plataforma KSeF que más tarde gestionaría el B2B — los dos sistemas no comparten infraestructura. La obligación de aceptar facturas electrónicas se implementó de forma escalonada desde el 18 de abril de 2019 (contratos ≥ 30.000 €) hasta el 1 de agosto de 2019 (todos los poderes adjudicadores), en virtud de la Ley del 9 de noviembre de 2018.' WHERE milestone_id = 'pl-b2g-peppol' AND lang = 'es';
UPDATE milestone_translations SET desc = 'La facturation du secteur public fonctionne sur Peppol via la plateforme PEF, entièrement séparée de la plateforme KSeF qui gérerait plus tard le B2B — les deux systèmes ne partagent aucune infrastructure. L''obligation d''accepter les factures électroniques a été introduite progressivement du 18 avril 2019 (marchés ≥ 30 000 €) au 1er août 2019 (tous les pouvoirs adjudicateurs), en vertu de la loi du 9 novembre 2018.' WHERE milestone_id = 'pl-b2g-peppol' AND lang = 'fr';

UPDATE milestone_translations SET system = 'Decreto-Lei n.º 111-B/2017 setzt die EU-Richtlinie zur E-Rechnungsstellung bei öffentlichen Aufträgen um' WHERE milestone_id = 'pt-lei-111b' AND lang = 'de';
UPDATE milestone_translations SET system = 'El Decreto-Lei n.º 111-B/2017 transpone la directiva de la UE sobre facturación electrónica en la contratación pública' WHERE milestone_id = 'pt-lei-111b' AND lang = 'es';
UPDATE milestone_translations SET system = 'Le Decreto-Lei n.º 111-B/2017 transpose la directive de l''UE sur la facturation électronique dans les marchés publics' WHERE milestone_id = 'pt-lei-111b' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Jede Rechnung – Papier oder elektronisch, B2G oder anderweitig – muss einen QR-Code zur Validierung tragen. Die Pflicht zum eindeutigen ATCUD-Dokumentencode folgt ein Jahr später und wird ab dem 1. Januar 2023 verpflichtend.' WHERE milestone_id = 'pt-qr-code' AND lang = 'de';
UPDATE milestone_translations SET desc = 'Toda factura —en papel o electrónica, B2G o de otro tipo— debe llevar un código QR que permita su validación. El requisito del código único de documento ATCUD entra en vigor un año más tarde, siendo obligatorio a partir del 1 de enero de 2023.' WHERE milestone_id = 'pt-qr-code' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Chaque facture — papier ou électronique, B2G ou autre — doit porter un code QR permettant sa validation. L''exigence du code de document unique ATCUD suit un an plus tard, devenant obligatoire à compter du 1er janvier 2023.' WHERE milestone_id = 'pt-qr-code' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Das verpflichtende RO-e-Invoice-Register umfasst nun auch Vereine, Stiftungen und gemeinnützige Organisationen ohne Umsatzsteuerregistrierung sowie Einzellandwirte unter der besonderen landwirtschaftlichen Regelung. Einzelunternehmer, die ausschließlich über die persönliche Identifikationsnummer (CNP) identifiziert werden, folgen erst später, ab dem 1. Juni 2026.' WHERE milestone_id = 'ro-nonvat-register' AND lang = 'de';
UPDATE milestone_translations SET desc = 'El Registro obligatorio RO e-Invoice ahora también cubre a asociaciones, fundaciones y entidades sin ánimo de lucro no registradas a efectos de IVA, y a agricultores individuales bajo el régimen agrícola especial. Los autónomos identificados únicamente por su número de identificación personal (CNP) se incorporan más tarde, a partir del 1 de junio de 2026.' WHERE milestone_id = 'ro-nonvat-register' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Le registre obligatoire RO e-Invoice couvre désormais aussi les associations, fondations et organismes à but non lucratif non immatriculés à la TVA, ainsi que les agriculteurs individuels relevant du régime agricole spécial. Les entrepreneurs individuels identifiés uniquement par leur numéro d''identification personnel (CNP) ne seront concernés que plus tard, à compter du 1er juin 2026.' WHERE milestone_id = 'ro-nonvat-register' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Das Schema 0245 (SK:DIC) wird für die 10-stellige slowakische Steueridentifikationsnummer (DIČ) formalisiert — die Kennung, unter der sich slowakische Endnutzer im Peppol-Netzwerk registrieren werden.' WHERE milestone_id = 'sk-peppol-codelist-2025' AND lang = 'de';
UPDATE milestone_translations SET desc = 'Se formaliza el esquema 0245 (SK:DIC) para el Número de Identificación Fiscal eslovaco (DIČ) de 10 dígitos, el identificador con el que los usuarios finales eslovacos se registrarán en la red Peppol.' WHERE milestone_id = 'sk-peppol-codelist-2025' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Le schéma 0245 (SK:DIC) est formalisé pour le numéro d''identification fiscale slovaque à 10 chiffres (DIČ), l''identifiant sous lequel les utilisateurs finaux slovaques s''enregistreront sur le réseau Peppol.' WHERE milestone_id = 'sk-peppol-codelist-2025' AND lang = 'fr';

UPDATE milestone_translations SET desc = 'Die ausschließliche Nutzung zertifizierter Digital-Postman-Dienstanbieter für Übermittlung und Empfang wird zu einer festen Anforderung — die bußgeldfreie Übergangsfrist vom 1. Januar bis 31. März 2027 endet hier.' WHERE milestone_id = 'sk-postman-mandatory-2027' AND lang = 'de';
UPDATE milestone_translations SET desc = 'El uso exclusivo de proveedores de servicios Digital Postman certificados para la transmisión y recepción se convierte en un requisito firme — aquí finaliza el período de gracia sin sanciones que va del 1 de enero al 31 de marzo de 2027.' WHERE milestone_id = 'sk-postman-mandatory-2027' AND lang = 'es';
UPDATE milestone_translations SET desc = 'Le recours exclusif à des prestataires Digital Postman certifiés pour la transmission et la réception devient une exigence ferme — la période de grâce sans pénalité, qui court du 1er janvier au 31 mars 2027, se termine ici.' WHERE milestone_id = 'sk-postman-mandatory-2027' AND lang = 'fr';

UPDATE milestone_translations SET system = 'Kabinettsbeschluss Nr. 106 von 2025 legt den Sanktionsrahmen fest', desc = 'Fünf spezifische Kategorien von E-Invoicing-Verstößen werden mit festen Bußgeldern definiert: verspätete Einführung des Systems, Nichtausstellung von E-Rechnungen oder E-Gutschriften, Nichtmeldung von Systemausfällen sowie verspätete Aktualisierung der Stammdaten.' WHERE milestone_id = 'uae-penalty-framework' AND lang = 'de';
UPDATE milestone_translations SET system = 'La Decisión del Gabinete n.º 106 de 2025 establece el régimen sancionador', desc = 'Se definen cinco categorías específicas de infracciones de facturación electrónica con sanciones fijas: no implementar el sistema a tiempo, no emitir facturas electrónicas o notas de crédito electrónicas, no informar sobre fallos del sistema, y actualizaciones tardías de los datos maestros.' WHERE milestone_id = 'uae-penalty-framework' AND lang = 'es';
UPDATE milestone_translations SET system = 'La décision du Cabinet n° 106 de 2025 fixe le régime des sanctions', desc = 'Cinq catégories spécifiques d''infractions à la facturation électronique sont définies avec des sanctions fixes : le non-respect du délai de mise en œuvre du système, la non-émission de factures électroniques ou de notes de crédit électroniques, le défaut de signalement des pannes du système, et la mise à jour tardive des données de référence.' WHERE milestone_id = 'uae-penalty-framework' AND lang = 'fr';
