-- Migration 410: Dan's decisions on the 4 outstanding items from the
-- follow-up citation-audit report (see PROGRESS.md's migration 408 entry).
--
-- 1) ie-phase1-criteria-reconfirmed: Dan supplied a real Revenue.ie source.
--    The old 'Phase 1 scope reconfirmed ~8 months after initial
--    confirmation' framing wasn't supported by anything found during the
--    audit. The supplied page (published 20 Jul 2026) is Revenue's
--    detailed Phase-1 large-corporates guidance -- a genuinely distinct,
--    later touchpoint from ie-phase1-criteria-2026 (the 10 Feb 2026 general
--    criteria confirmation). Rewritten to describe what the page actually
--    says, date corrected to match its real publish date.
--
-- 2) uk-nhs-peppol: removed entirely per Dan's decision -- the 2018/2019
--    date genuinely couldn't be resolved after real search effort.
--
-- 3) ca-cra-research-2018 merged into ca-watch per Dan's decision -- both
--    covered the same 2021 CRA e-invoicing feasibility study. ca-watch's
--    desc now credits the Jan 2021 preliminary research phase that
--    ca-cra-research-2018 had captured, so no factual detail is lost.
--
-- 4) au-default-2025 merged into au-automate per Dan's decision -- both
--    described the same Dec 2026 ATO reform (default exchange method +
--    mandatory automated processing) once migration 408 corrected
--    au-default-2025's date to match the only corroborated sources.
--    au-automate's system/desc now cover both aspects.

-- ie-phase1-criteria-reconfirmed: corrected date, source, and content (all 4 languages)
UPDATE milestones SET date = '2026-07-20', source_url = 'https://www.revenue.ie/en/vat/vida-vat-modernisation/large-corporates-vat-modernisation.aspx' WHERE id = 'ie-phase1-criteria-reconfirmed';
UPDATE milestone_translations SET system = 'Revenue publishes detailed Phase 1 large-corporates guidance', desc = 'Revenue''s VAT Modernisation guidance page sets out exactly who Phase 1 covers: VAT-registered businesses managed by Revenue''s Large Corporates Division that are established, or have a fixed establishment, in Ireland. These large corporates must send e-invoices to Irish business customers and report a subset of e-invoice data to Revenue from Phase 1 go-live on 1 November 2028 — Revenue will write to each affected business to confirm its inclusion. All Irish businesses, regardless of size, must be able to receive structured e-invoices from that same date.' WHERE milestone_id = 'ie-phase1-criteria-reconfirmed' AND lang = 'en';
UPDATE milestone_translations SET system = 'Revenue veröffentlicht detaillierte Leitlinien zu Phase 1 für Großunternehmen', desc = 'Die Leitlinien von Revenue zur USt-Modernisierung legen genau fest, wer unter Phase 1 fällt: umsatzsteuerlich registrierte Unternehmen, die von der Large Corporates Division von Revenue betreut werden und in Irland ansässig sind oder dort eine feste Niederlassung haben. Diese Großunternehmen müssen ab dem Start von Phase 1 am 1. November 2028 E-Rechnungen an irische Geschäftskunden senden und einen Teil der E-Rechnungsdaten an Revenue melden — Revenue wird jedes betroffene Unternehmen schriftlich über seine Einbeziehung informieren. Alle irischen Unternehmen, unabhängig von ihrer Größe, müssen ab demselben Datum in der Lage sein, strukturierte E-Rechnungen zu empfangen.' WHERE milestone_id = 'ie-phase1-criteria-reconfirmed' AND lang = 'de';
UPDATE milestone_translations SET system = 'Revenue publica una guía detallada de la Fase 1 para grandes corporativos', desc = 'La guía de modernización del IVA de Revenue especifica exactamente a quién cubre la Fase 1: empresas registradas a efectos de IVA gestionadas por la División de Grandes Corporativos de Revenue que están establecidas, o tienen un establecimiento permanente, en Irlanda. Estos grandes corporativos deberán enviar facturas electrónicas a sus clientes empresariales irlandeses y reportar un subconjunto de los datos de la factura electrónica a Revenue desde la entrada en vigor de la Fase 1 el 1 de noviembre de 2028 — Revenue escribirá a cada empresa afectada para confirmar su inclusión. Todas las empresas irlandesas, sin importar su tamaño, deberán poder recibir facturas electrónicas estructuradas desde esa misma fecha.' WHERE milestone_id = 'ie-phase1-criteria-reconfirmed' AND lang = 'es';
UPDATE milestone_translations SET system = 'Revenue publie des lignes directrices détaillées sur la Phase 1 pour les grandes entreprises', desc = 'Les lignes directrices de Revenue sur la modernisation de la TVA précisent exactement qui est couvert par la Phase 1 : les entreprises immatriculées à la TVA gérées par la Large Corporates Division de Revenue, établies ou disposant d''un établissement stable en Irlande. Ces grandes entreprises devront envoyer des factures électroniques à leurs clients professionnels irlandais et déclarer un sous-ensemble des données de la facture électronique à Revenue dès l''entrée en vigueur de la Phase 1, le 1er novembre 2028 — Revenue écrira à chaque entreprise concernée pour confirmer son inclusion. Toutes les entreprises irlandaises, quelle que soit leur taille, devront être en mesure de recevoir des factures électroniques structurées à compter de cette même date.' WHERE milestone_id = 'ie-phase1-criteria-reconfirmed' AND lang = 'fr';

-- uk-nhs-peppol: removed (genuinely unresolvable citation, Dan's call)
DELETE FROM milestone_translations WHERE milestone_id = 'uk-nhs-peppol';
DELETE FROM milestones WHERE id = 'uk-nhs-peppol';

-- ca-cra-research-2018 merged into ca-watch
DELETE FROM milestone_translations WHERE milestone_id = 'ca-cra-research-2018';
DELETE FROM milestones WHERE id = 'ca-cra-research-2018';
UPDATE milestone_translations SET desc = 'The Canada Revenue Agency began preliminary feasibility research in January 2021, followed by broader stakeholder research into a possible domestic B2B e-invoicing mandate. No legislation or firm timeline has followed — GST/HST rules remain format-neutral, and paper, PDF, and EDI invoices are all currently acceptable provided they carry the required tax information.' WHERE milestone_id = 'ca-watch' AND lang = 'en';
UPDATE milestone_translations SET desc = 'Die Canada Revenue Agency (CRA) begann im Januar 2021 mit einer vorläufigen Machbarkeitsuntersuchung, gefolgt von einer breiter angelegten Stakeholder-Untersuchung zu einer möglichen inländischen B2B-E-Invoicing-Pflicht. Es folgten weder Gesetzgebung noch ein fester Zeitplan — die GST-/HST-Vorschriften bleiben formatneutral, und Papier-, PDF- und EDI-Rechnungen sind derzeit alle zulässig, sofern sie die erforderlichen Steuerangaben enthalten.' WHERE milestone_id = 'ca-watch' AND lang = 'de';
UPDATE milestone_translations SET desc = 'La Agencia de Ingresos de Canadá (CRA) inició en enero de 2021 una investigación preliminar de viabilidad, seguida de una investigación más amplia con partes interesadas sobre un posible mandato nacional de facturación electrónica B2B. No se ha seguido de ninguna legislación ni plazo firme — las normas de GST/HST siguen siendo neutrales en cuanto al formato, y las facturas en papel, PDF y EDI son actualmente todas aceptables siempre que contengan la información fiscal requerida.' WHERE milestone_id = 'ca-watch' AND lang = 'es';
UPDATE milestone_translations SET desc = 'L''Agence du revenu du Canada (ARC) a entamé en janvier 2021 une recherche préliminaire de faisabilité, suivie d''une étude plus large auprès des parties prenantes sur une éventuelle obligation nationale de facturation électronique B2B. Aucune législation ni calendrier ferme n''a suivi — les règles de TPS/TVH restent neutres quant au format, et les factures papier, PDF et EDI sont actuellement toutes acceptables dès lors qu''elles comportent les informations fiscales requises.' WHERE milestone_id = 'ca-watch' AND lang = 'fr';

-- au-default-2025 merged into au-automate
DELETE FROM milestone_translations WHERE milestone_id = 'au-default-2025';
DELETE FROM milestones WHERE id = 'au-default-2025';
UPDATE milestone_translations SET system = 'ATO establishes e-invoicing as the default and requires automated processing for NCEs', desc = 'The Australian Taxation Office makes e-invoicing the default invoice exchange method for Non-Corporate Commonwealth Entities, which must also be able to automatically process received e-invoices and send e-invoices, with quarterly progress reporting to the Australian Peppol Authority — part of a broader strategy to cut administrative overhead and speed up payment cycles.' WHERE milestone_id = 'au-automate' AND lang = 'en';
UPDATE milestone_translations SET system = 'ATO legt E-Rechnung als Standard fest und verlangt automatisierte Verarbeitung für NCEs', desc = 'Das australische Finanzamt (ATO) macht die E-Rechnung zur Standardmethode für den Rechnungsaustausch für Non-Corporate Commonwealth Entities, die zudem empfangene E-Rechnungen automatisch verarbeiten und E-Rechnungen versenden können müssen, mit vierteljährlicher Fortschrittsberichterstattung an die Australian Peppol Authority — Teil einer umfassenderen Strategie zur Senkung des Verwaltungsaufwands und zur Beschleunigung der Zahlungszyklen.' WHERE milestone_id = 'au-automate' AND lang = 'de';
UPDATE milestone_translations SET system = 'La ATO establece la facturación electrónica como predeterminada y exige procesamiento automatizado para las NCE', desc = 'La Oficina de Impuestos de Australia (ATO) convierte la facturación electrónica en el método predeterminado de intercambio de facturas para las Entidades del Commonwealth No Corporativas, que también deberán poder procesar automáticamente las facturas electrónicas recibidas y enviar facturas electrónicas, con reporte trimestral de avance a la Autoridad Peppol Australiana — parte de una estrategia más amplia para reducir la carga administrativa y acelerar los ciclos de pago.' WHERE milestone_id = 'au-automate' AND lang = 'es';
UPDATE milestone_translations SET system = 'L''ATO établit la facturation électronique comme méthode par défaut et exige un traitement automatisé pour les NCE', desc = 'L''administration fiscale australienne (ATO) fait de la facturation électronique la méthode d''échange de factures par défaut pour les Non-Corporate Commonwealth Entities, qui doivent également pouvoir traiter automatiquement les factures électroniques reçues et envoyer des factures électroniques, avec un reporting trimestriel des progrès à l''Australian Peppol Authority — dans le cadre d''une stratégie plus large visant à réduire la charge administrative et à accélérer les cycles de paiement.' WHERE milestone_id = 'au-automate' AND lang = 'fr';
