-- Slovenia deep-dive content (English). Two-tier regime: a long-standing
-- B2G obligation (ZOPSPU/ZOPSPU-A, public sector required to receive
-- e-invoices since 1 Jan 2015, via UJP's EVIT hub) and a brand-new B2B
-- law, ZIERDED (Zakon o izmenjavi elektronskih racunov in drugih
-- elektronskih dokumentov), enacted 2025 with a two-stage 2027/2028
-- rollout. Live-researched against Slovenia's Official Gazette
-- (uradni-list.si -- ZIERDED text and the original ZOPSPU-A gazette
-- entry), a gov.si government notice (stopbirokraciji.gov.si) on the
-- 2015 B2G mandate, UJP's own e-Racuni portal, GZS/epos.si (the
-- e-SLOG standard's semi-official maintainer body, flagged as
-- industry rather than pure government), and FURS. Every URL cited as
-- a milestone source_url or deep-dive portal was independently
-- fetched and confirmed in this session -- see PROGRESS.md's dated
-- build entry for the full citation trail. One flagged gap, carried
-- into the cards below rather than papered over: no source confirms
-- Slovenia has a formally registered OpenPeppol "Peppol Authority" --
-- UJP's real role (EVIT hub operator) is described without asserting
-- that title.

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-06' FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en',
  'Two-tier regime: a long-standing B2G obligation via UJP''s central hub, plus a brand-new B2B law (ZIERDED) enacted in late 2025 with a two-stage rollout landing in 2027 and 2028',
  'This deep-dive page reflects the ZIERDED law as published in Slovenia''s Official Gazette and publicly available government guidance as of early August 2026, and is provided for general awareness, not legal or tax advice. Confirm current requirements directly with FURS, UJP, or a Slovenian tax/legal adviser before relying on this page for compliance decisions.',
  'Slovenia''s public sector has required e-invoices since 1 January 2015 under ZOPSPU/ZOPSPU-A, routed through UJP''s central EVIT hub. B2B e-invoicing had no general mandate until 2025, when parliament passed ZIERDED (published in the Official Gazette as Uradni list RS, st. 85/2025, 6 November 2025) -- Slovenia''s first mandatory business-to-business e-invoicing law, with a certified e-path provider regime taking effect 1 April 2027 and the core exchange obligation following on 1 January 2028.',
  'A ZIERDED-compliant invoice is exchanged through one of three permitted channels -- a certified e-path ("e-pot") provider, a direct system-to-system link, or Peppol -- formatted to the e-SLOG 2.0 standard, Slovenia''s EN 16931-aligned national specification maintained by GZS (the Chamber of Commerce and Industry). This is a decentralized exchange model, not a government clearance platform: there is no single mandatory government portal for B2B invoices the way UJP''s e-Racuni portal serves the public sector.',
  'The B2B mandate applies universally -- every entity registered in Slovenia''s Business Register and every self-employed person, with no size threshold or phased carve-out found in the law''s text. B2G invoicing has applied to the entire public sector since 2015. This is a genuinely new B2B obligation, not an expansion of an existing one -- most Slovenian businesses have no current legal requirement to exchange e-invoices with each other, and that changes on 1 January 2028.',
  'Most businesses reading this have no current B2B e-invoicing obligation in Slovenia -- the work ahead is choosing and testing one of ZIERDED''s three permitted exchange channels well before the 1 January 2028 deadline, not reacting to something already in force.',
  'ZIERDED backs its B2B mandate with real, article-specific fines under Art. 24 (core exchange violations) and a separate, lower Art. 25 range for consumer-invoice violations -- both independently confirmed against the Official Gazette text in this session, not taken from a secondary summary.',
  'Slovenia requires public-sector bodies to receive e-invoices since 1 January 2015 (ZOPSPU/ZOPSPU-A, via UJP''s central hub). A new law, ZIERDED, adds Slovenia''s first mandatory B2B e-invoicing regime: certified e-path providers from 1 April 2027, and mandatory e-invoice exchange for essentially all businesses and self-employed persons from 1 January 2028, using the e-SLOG 2.0 standard over one of three permitted channels including Peppol.',
  '🇸🇮'
FROM countries WHERE code = 'SI';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1 Jan 2015', 'Public sector required to receive e-invoices (ZOPSPU/ZOPSPU-A)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '6 Nov 2025', 'ZIERDED -- Slovenia''s first B2B e-invoicing law -- published in the Official Gazette');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1 Apr 2027', 'Certified e-path provider regime takes effect');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1 Jan 2028', 'Mandatory B2B e-invoice exchange begins');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '€1,000-3,000', 'Core Art. 24 fine range for legal entities');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & channels', '[["B2B invoice format", "e-SLOG 2.0 -- Slovenia''s own EN 16931-aligned XML standard, maintained by GZS (Chamber of Commerce and Industry)"], ["B2B exchange model", "Decentralized -- no single mandatory government clearance platform for B2B, unlike UJP''s role in B2G"], ["Permitted channels (ZIERDED Art. 9)", "Certified e-path (\"e-pot\") provider; direct system-to-system link; or Peppol"], ["B2G invoice format", "Also e-SLOG, submitted via UJP''s EVIT hub (banks, contracted processors, or the e-Racuni portal)"]]', 'ZIERDED does not name a single mandatory transmission network the way some CTC-model countries do -- businesses choose among the three permitted channels, so your choice of provider matters more in Slovenia than in a single-platform regime.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'UJP''s role in B2G', '[["EVIT hub", "UJP operates the \"enotna vstopna in izstopna tocka\" (single entry/exit point) for budget-user e-invoice exchange"], ["e-Racuni portal", "Free submission route for suppliers without a bank or contracted processor -- https://eracuni.ujp.gov.si/"], ["Bank / processor routes", "Participating banks and UJP-contracted data processors can also carry e-invoices to budget users"], ["Peppol Authority status", "Not established -- no source confirms Slovenia has a formally registered OpenPeppol Peppol Authority"]]', 'UJP is sometimes described informally as Slovenia''s "Peppol Authority" -- that title does not appear on OpenPeppol''s own current authorities list, and UJP''s government page describes its role as the EVIT hub operator, not a Peppol governance body. Treat UJP as the B2G hub, not a confirmed Peppol Authority, until a primary source says otherwise.', NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Who ZIERDED covers', '[["Scope (Art. 7)", "Every entity registered in Slovenia''s Business Register, and every self-employed person"], ["Size threshold", "None found -- the law applies uniformly, with no small-business carve-out identified in the gazette text"], ["Consumer invoices", "Covered separately, under the lower Art. 25 penalty range rather than Art. 24"], ["Public sector (B2G)", "Already covered separately since 2015 under ZOPSPU/ZOPSPU-A -- ZIERDED is a B2B-focused addition, not a replacement"]]', 'ZIERDED Art. 1 explicitly ties the law to transposing elements of the EU''s ViDA directive (2025/516) -- expect further detail (e.g. any future digital reporting requirement) to develop as ViDA''s own e-invoicing/digital-reporting pillar phases in across the EU toward 2030.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'The two-stage rollout', '[["1 April 2027", "ZIERDED Chapter 4''s certified e-path provider regime takes effect -- providers can seek certification and businesses can begin using certified providers"], ["1 January 2028", "The core mandatory exchange obligation applies to all in-scope entities, across all three permitted channels"], ["No pre-2027 registration requirement found", "Nothing in the gazette text requires businesses to register or prepare formally before the 2027 date"]]', NULL, NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚠️ Core exchange violations (Art. 24)', NULL, NULL, 'ZIERDED Art. 24 sets the core penalty range for failing to comply with the mandatory B2B exchange obligation once it applies: EUR 1,000-3,000 for legal entities, EUR 500-1,500 for sole proprietors, and EUR 100-500 for a responsible person within an organization. These figures were independently confirmed by direct fetch of the Official Gazette text in this session, not carried over from a secondary source.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🧾 Consumer-invoice violations (Art. 25)', NULL, NULL, 'A separate, lower penalty range applies specifically to consumer-invoice violations under Art. 25: EUR 500-1,500 for legal entities, EUR 100-500 for sole proprietors, and EUR 50-250 for a responsible person. This is a distinct violation category from Art. 24''s core B2B exchange fines, not an alternative or reduced version of the same fine.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔍 What we could not confirm', NULL, NULL, 'ZIERDED''s penalty articles are new law -- there is no enforcement track record yet to cite the way Costa Rica''s or Jordan''s deep dives can. Two secondary-only claims sometimes repeated about Slovenia''s e-invoicing ecosystem -- that ZZI operates a formally branded "Exchange Hub," and that FURS offers a "miniBlagajna" tool usable in this context -- were not independently corroborated on a primary government page in this round of research and are deliberately left out of this page rather than repeated as fact.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm your current B2G e-invoicing route, if you sell to Slovenian public bodies', 'Check whether your business already reaches Slovenian budget users through a bank, a UJP-contracted processor, or the UJP e-Racuni portal -- this obligation has applied since 2015 and is separate from the new B2B law.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Read ZIERDED''s official text before choosing a B2B exchange channel', 'The law permits three channels -- a certified e-path provider, a direct system-to-system link, or Peppol -- with no single mandatory platform; understand the trade-offs before committing.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm your invoicing software can produce e-SLOG 2.0 / EN 16931-compliant output', 'e-SLOG 2.0 is Slovenia''s national standard for both the existing B2G obligation and the new B2B law -- confirm your provider supports it rather than assuming generic EN 16931 support is sufficient.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'If choosing a certified e-path provider, wait for the 1 April 2027 certification regime before selecting one', 'ZIERDED''s Chapter 4 certification rules only take effect on this date -- confirm any provider''s certification is actually in force under the regime before relying on it.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Test your chosen exchange channel well ahead of 1 January 2028', 'The core mandatory exchange obligation applies to essentially all Business-Register-registered entities and self-employed persons from this date, with real fines under Art. 24/25 for non-compliance -- don''t leave testing until the deadline.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.uradni-list.si/glasilo-uradni-list-rs/vsebina/2025-01-3032/zakon-o-izmenjavi-elektronskih-racunov-in-drugih-elektronskih-dokumentov-zierded', 0 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Official Gazette -- ZIERDED full legal text (Uradni list RS, st. 85/2025)');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://eracuni.ujp.gov.si/', 1 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'UJP e-Racuni -- the public-sector (B2G) e-invoice submission portal');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.fu.gov.si', 2 FROM countries WHERE code = 'SI';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'FURS -- Slovenian Financial Administration');
