-- Slovenia story: EN/ES/DE/FR, covering ZIERDED's enactment -- a real,
-- dated news event (Official Gazette publication) independently
-- fetched and confirmed in this session. No Iceland story is included
-- in this batch: Iceland's e-invoicing mandate has been stable since
-- its 2019-2020 rollout completed, with no dated 2023-2026 news event
-- found in this session's research to hang a genuine story on -- see
-- PROGRESS.md's build entry. Writing one anyway would mean inventing
-- news where none exists, which this project's sourcing standard
-- doesn't allow.

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-11-06-slovenia-zierded-enacted', '2025-11-06', '2025-11', 'Slovenia published ZIERDED -- its first mandatory B2B e-invoicing law -- in the Official Gazette on 6 November 2025. The law sets a two-stage rollout: a certified "e-path" provider regime from 1 April 2027, and a universal B2B e-invoice exchange obligation from 1 January 2028, backed by real fines for non-compliance.', '<h3>🇸🇮 Slovenia enacts ZIERDED, its first B2B e-invoicing law</h3>
<p>On 6 November 2025, Slovenia published the Zakon o izmenjavi elektronskih računov in drugih elektronskih dokumentov (ZIERDED) in the Official Gazette (Uradni list RS, št. 85/2025) -- the country''s first mandatory business-to-business e-invoicing law. Slovenia''s public sector has required e-invoices since 2015 under a separate law, but until now there has been no general B2B mandate.</p>
<p>ZIERDED applies to every entity registered in Slovenia''s Business Register and every self-employed person, with no size threshold identified in the law''s text. It permits three exchange channels -- a certified e-path provider, a direct system-to-system link, or Peppol -- rather than mandating a single government platform, formatted to the e-SLOG 2.0 standard (aligned with EN 16931). The law explicitly ties itself to transposing elements of the EU''s ViDA directive (2025/516).</p>
<p>The rollout is staged: the certified e-path provider regime takes effect 1 April 2027, with the core mandatory exchange obligation following on 1 January 2028. Non-compliance draws fines under Art. 24 (EUR 1,000-3,000 for legal entities, lower amounts for sole proprietors and individuals) and a separate, lower Art. 25 range for consumer-invoice violations. Businesses trading with Slovenia have roughly two years to choose and test an exchange channel before the mandatory date.</p>', 'https://www.uradni-list.si/glasilo-uradni-list-rs/vsebina/2025-01-3032/zakon-o-izmenjavi-elektronskih-racunov-in-drugih-elektronskih-dokumentov-zierded', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-11-06-slovenia-zierded-enacted', id FROM countries WHERE code = 'SI';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-11-06-slovenia-zierded-enacted', 'en', 'Slovenia enacts ZIERDED, its first B2B e-invoicing law', 'Slovenia published ZIERDED -- its first mandatory B2B e-invoicing law -- in the Official Gazette on 6 November 2025. The law sets a two-stage rollout: a certified "e-path" provider regime from 1 April 2027, and a universal B2B e-invoice exchange obligation from 1 January 2028, backed by real fines for non-compliance.', '<h3>🇸🇮 Slovenia enacts ZIERDED, its first B2B e-invoicing law</h3>
<p>On 6 November 2025, Slovenia published the Zakon o izmenjavi elektronskih računov in drugih elektronskih dokumentov (ZIERDED) in the Official Gazette (Uradni list RS, št. 85/2025) -- the country''s first mandatory business-to-business e-invoicing law. Slovenia''s public sector has required e-invoices since 2015 under a separate law, but until now there has been no general B2B mandate.</p>
<p>ZIERDED applies to every entity registered in Slovenia''s Business Register and every self-employed person, with no size threshold identified in the law''s text. It permits three exchange channels -- a certified e-path provider, a direct system-to-system link, or Peppol -- rather than mandating a single government platform, formatted to the e-SLOG 2.0 standard (aligned with EN 16931). The law explicitly ties itself to transposing elements of the EU''s ViDA directive (2025/516).</p>
<p>The rollout is staged: the certified e-path provider regime takes effect 1 April 2027, with the core mandatory exchange obligation following on 1 January 2028. Non-compliance draws fines under Art. 24 (EUR 1,000-3,000 for legal entities, lower amounts for sole proprietors and individuals) and a separate, lower Art. 25 range for consumer-invoice violations. Businesses trading with Slovenia have roughly two years to choose and test an exchange channel before the mandatory date.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-11-06-slovenia-zierded-enacted', 'es', 'Eslovenia promulga la ZIERDED, su primera ley de facturación electrónica B2B', 'Eslovenia publicó la ZIERDED -- su primera ley obligatoria de facturación electrónica B2B -- en el Diario Oficial el 6 de noviembre de 2025. La ley establece un despliegue en dos etapas: un régimen de proveedores certificados de "vía electrónica" desde el 1 de abril de 2027, y una obligación universal de intercambio de facturas electrónicas B2B desde el 1 de enero de 2028, respaldada por multas reales en caso de incumplimiento.', '<h3>🇸🇮 Eslovenia promulga la ZIERDED, su primera ley de facturación electrónica B2B</h3>
<p>El 6 de noviembre de 2025, Eslovenia publicó la Zakon o izmenjavi elektronskih računov in drugih elektronskih dokumentov (ZIERDED) en el Diario Oficial (Uradni list RS, št. 85/2025) -- la primera ley obligatoria de facturación electrónica entre empresas (B2B) del país. El sector público esloveno exige facturas electrónicas desde 2015 en virtud de una ley distinta, pero hasta ahora no existía un mandato B2B general.</p>
<p>La ZIERDED se aplica a toda entidad inscrita en el Registro Mercantil de Eslovenia y a toda persona autónoma, sin ningún umbral de tamaño identificado en el texto de la ley. Permite tres canales de intercambio -- un proveedor certificado de vía electrónica, un enlace directo de sistema a sistema, o Peppol -- en lugar de imponer una única plataforma gubernamental, con el formato del estándar e-SLOG 2.0 (alineado con EN 16931). La ley vincula explícitamente su origen a la transposición de elementos de la directiva ViDA de la UE (2025/516).</p>
<p>El despliegue se realiza por etapas: el régimen de proveedores certificados de vía electrónica entra en vigor el 1 de abril de 2027, y la obligación central de intercambio le sigue el 1 de enero de 2028. El incumplimiento conlleva multas bajo el art. 24 (1.000-3.000 € para personas jurídicas, importes menores para autónomos y particulares) y un rango independiente y más bajo bajo el art. 25 para las infracciones relativas a facturas de consumo. Las empresas que comercian con Eslovenia disponen de unos dos años para elegir y probar un canal de intercambio antes de la fecha obligatoria.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-11-06-slovenia-zierded-enacted', 'de', 'Slowenien erlässt ZIERDED, sein erstes B2B-E-Rechnungsgesetz', 'Slowenien veröffentlichte ZIERDED -- sein erstes verpflichtendes B2B-E-Rechnungsgesetz -- am 6. November 2025 im Amtsblatt. Das Gesetz sieht eine zweistufige Einführung vor: ein Regime für zertifizierte "E-Weg"-Anbieter ab 1. April 2027 und eine allgemeine B2B-E-Rechnungsaustauschpflicht ab 1. Januar 2028, abgesichert durch reale Bußgelder bei Nichteinhaltung.', '<h3>🇸🇮 Slowenien erlässt ZIERDED, sein erstes B2B-E-Rechnungsgesetz</h3>
<p>Am 6. November 2025 veröffentlichte Slowenien das Zakon o izmenjavi elektronskih računov in drugih elektronskih dokumentov (ZIERDED) im Amtsblatt (Uradni list RS, št. 85/2025) -- das erste verpflichtende Gesetz des Landes zur elektronischen Rechnungsstellung zwischen Unternehmen (B2B). Der öffentliche Sektor Sloweniens verlangt bereits seit 2015 nach einem gesonderten Gesetz elektronische Rechnungen, doch bislang gab es keine allgemeine B2B-Pflicht.</p>
<p>ZIERDED gilt für jede im slowenischen Handelsregister eingetragene Einheit und jede selbstständige Person, ohne dass der Gesetzestext eine Größenschwelle vorsieht. Es lässt drei Austauschkanäle zu -- einen zertifizierten E-Weg-Anbieter, eine direkte System-zu-System-Verbindung oder Peppol -- statt eine einzige staatliche Plattform vorzuschreiben, formatiert nach dem Standard e-SLOG 2.0 (an EN 16931 angelehnt). Das Gesetz verknüpft sich ausdrücklich mit der Umsetzung von Elementen der ViDA-Richtlinie der EU (2025/516).</p>
<p>Die Einführung erfolgt gestaffelt: Das Regime für zertifizierte E-Weg-Anbieter tritt am 1. April 2027 in Kraft, die zentrale verpflichtende Austauschpflicht folgt am 1. Januar 2028. Nichteinhaltung zieht Bußgelder nach Art. 24 nach sich (1.000-3.000 € für juristische Personen, niedrigere Beträge für Einzelunternehmer und Privatpersonen) sowie einen eigenen, niedrigeren Rahmen nach Art. 25 für Verstöße bei Verbraucherrechnungen. Unternehmen, die mit Slowenien Handel treiben, haben rund zwei Jahre Zeit, um vor dem verpflichtenden Stichtag einen Austauschkanal auszuwählen und zu testen.</p>');
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-11-06-slovenia-zierded-enacted', 'fr', 'La Slovénie promulgue la ZIERDED, sa première loi de facturation électronique B2B', 'La Slovénie a publié la ZIERDED -- sa première loi obligatoire de facturation électronique B2B -- au Journal officiel le 6 novembre 2025. La loi instaure un déploiement en deux étapes : un régime de prestataires certifiés de « voie électronique » à partir du 1er avril 2027, et une obligation universelle d''échange de factures électroniques B2B à partir du 1er janvier 2028, assortie d''amendes réelles en cas de non-conformité.', '<h3>🇸🇮 La Slovénie promulgue la ZIERDED, sa première loi de facturation électronique B2B</h3>
<p>Le 6 novembre 2025, la Slovénie a publié la Zakon o izmenjavi elektronskih računov in drugih elektronskih dokumentov (ZIERDED) au Journal officiel (Uradni list RS, št. 85/2025) -- la première loi du pays rendant obligatoire la facturation électronique entre entreprises (B2B). Le secteur public slovène exige des factures électroniques depuis 2015 en vertu d''une loi distincte, mais il n''existait jusqu''ici aucune obligation B2B générale.</p>
<p>La ZIERDED s''applique à toute entité inscrite au Registre du commerce slovène et à toute personne exerçant à titre indépendant, sans qu''aucun seuil de taille ne soit identifié dans le texte de la loi. Elle autorise trois canaux d''échange -- un prestataire de voie électronique certifié, une liaison directe système à système, ou Peppol -- plutôt que d''imposer une plateforme gouvernementale unique, au format de la norme e-SLOG 2.0 (alignée sur EN 16931). La loi rattache explicitement son origine à la transposition d''éléments de la directive ViDA de l''UE (2025/516).</p>
<p>Le déploiement se fait par étapes : le régime des prestataires de voie électronique certifiés entre en vigueur le 1er avril 2027, suivi de l''obligation centrale d''échange le 1er janvier 2028. Le non-respect entraîne des amendes au titre de l''art. 24 (1 000-3 000 € pour les personnes morales, des montants inférieurs pour les entrepreneurs individuels et les particuliers) et une fourchette distincte et plus basse au titre de l''art. 25 pour les infractions relatives aux factures aux consommateurs. Les entreprises commerçant avec la Slovénie disposent d''environ deux ans pour choisir et tester un canal d''échange avant l''échéance obligatoire.</p>');
