-- Serbia deep-dive ES/DE/FR translations, completing 428 (deep-dive
-- content) and 426 (milestones) against their English content. This is
-- a SEPARATE migration file, so every deep-dive translation row looks
-- up its parent row via a JOIN on stable identifying columns (country
-- code / section / sort_order), never via (SELECT MAX(id) ...).
-- milestone_translations has a natural PK on (milestone_id, lang), so
-- those rows are plain INSERT OR IGNORE statements keyed on the
-- hardcoded milestone id strings from 426 -- no JOIN needed. INSERT OR
-- IGNORE throughout. Every proper noun, law name (Zakon o elektronskom
-- fakturisanju, Zakon o elektronskim otpremnicama, SEF, e-otpremnica,
-- Sl. glasnik RS), article number, URL, and version number (SEF v4.0.0,
-- v4.1.0) is preserved unchanged from the English source; only the
-- surrounding prose is translated.

-- ==================== es ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'es',
  'Régimen maduro de clearance centralizado: la facturación electrónica B2B/B2G obligatoria está vigente desde 2023 a través de la plataforma SEF, y ahora se añade un sistema independiente de albarán electrónico (e-otpremnica) para el movimiento de mercancías, desplegado en dos fases entre 2026 y 2027',
  'Esta página de análisis refleja la Zakon o elektronskom fakturisanju y la Zakon o elektronskim otpremnicama tal como se publicaron en el Diario Oficial de Serbia (Sl. glasnik RS), y la orientación pública gubernamental disponible a inicios de agosto de 2026, y se ofrece a título informativo general, no como asesoría legal o tributaria. Confirme los requisitos vigentes directamente con el Ministerio de Finanzas de Serbia, los canales de soporte de SEF, o un asesor fiscal/legal serbio antes de basar en esta página sus decisiones de cumplimiento.',
  'El despliegue de la facturación electrónica en Serbia comenzó con el sector público: los proveedores de compradores del sector público debieron emitir facturas electrónicas a través de SEF desde el 1 de mayo de 2022, y las entidades del sector público debieron emitirlas a empresas desde el 1 de julio de 2022. El mandato general B2B llegó después, el 1 de enero de 2023, haciendo obligatoria la facturación electrónica (emisión y recepción) en todo el sector privado para los contribuyentes registrados a efectos del IVA. Una ley independiente, la Zakon o elektronskim otpremnicama, añade ahora un sistema paralelo de albarán electrónico, desplegado en dos fases: el sector público, los comerciantes de bienes sujetos a impuestos especiales y los transportistas desde el 1 de enero de 2026, ampliándose al movimiento general de mercancías B2B del sector privado desde el 1 de octubre de 2027.',
  'Una factura electrónica conforme con SEF es un XML basado en UBL 2.1, con una CIUS específica de Serbia alineada con el estándar semántico EN 16931 de la UE. La transmisión sigue un modelo de clearance centralizado (CTC) -- toda factura se envía a SEF (Sistem elektronskih faktura) y es validada por este antes de llegar al destinatario, de forma funcionalmente similar al SDI italiano, y SEF actúa además como repositorio de facturas. El sistema e-otpremnica utiliza el mismo enfoque basado en UBL 2.1, gestionado por un "Intermediario Central de Información", accesible a través del portal nacional de eID, la interfaz web, la aplicación móvil o la API.',
  'El mandato de facturación electrónica se aplica a todos los contribuyentes registrados a efectos del IVA y a todas las entidades que utilizan el sistema de contratación pública, sin ningún umbral de tamaño de empresa o de ingresos identificado en el texto de la ley -- las empresas extranjeras que operan mediante un número de identificación fiscal local o un representante fiscal quedan incluidas. El mandato e-otpremnica, en cambio, se aplica por fases según la categoría de actividad: la Fase 1 cubre al sector público, a los comerciantes de bienes sujetos a impuestos especiales y a los transportistas; la Fase 2 (1 de octubre de 2027) se amplía al movimiento general de mercancías B2B del sector privado. Si la facturación B2C/de recibo fiscal se encuentra dentro o fuera del mandato central de e-Faktura no pudo confirmarse de forma independiente en esta investigación.',
  'La mayoría de las empresas que comercian con Serbia ya tienen una obligación vigente de facturación electrónica en SEF -- el mandato está en vigor desde 2023. El trabajo más reciente es el sistema e-otpremnica (albarán electrónico): las empresas de las categorías de la Fase 1 (sector público, bienes sujetos a impuestos especiales, transportistas) debían estar preparadas antes del 1 de enero de 2026, y la aplicación de las inspecciones ya está plenamente vigente, mientras que otras empresas que mueven mercancías B2B deben planificar con antelación a la fecha de la Fase 2, el 1 de octubre de 2027.',
  'Serbia respalda ambas leyes con multas reales y escalonadas. Tanto la ley de facturación electrónica (arts. 18-21) como la ley de albarán electrónico (arts. 13-14) establecen rangos de sanción según la categoría del infractor (personas jurídicas, empresarios, personas responsables), obtenidos aquí a través del texto legal consolidado de Paragraf.rs -- un compilador secundario de buena reputación, pero no la gaceta original, por lo que la atribución artículo por artículo debe considerarse indicativa hasta su verificación directa contra el texto de la gaceta.',
  'Serbia exige la facturación electrónica B2G desde mayo-julio de 2022, y la facturación electrónica B2B obligatoria (emisión y recepción, a través de la plataforma centralizada SEF) desde el 1 de enero de 2023, para todos los contribuyentes registrados a efectos del IVA. Una ley independiente y más reciente añade los albaranes electrónicos (e-otpremnica): obligatorios desde el 1 de enero de 2026 para el sector público, los comerciantes de bienes sujetos a impuestos especiales y los transportistas, ampliándose al movimiento general de mercancías B2B del sector privado desde el 1 de octubre de 2027. Fuentes secundarias han informado de un paquete adicional de reforma de facturación electrónica "B2B ampliado" (nuevos campos, validación más estricta, un nuevo régimen sancionador) que se habría pospuesto a "finales de 2026", pero su fecha exacta no pudo confirmarse frente a un anuncio gubernamental primario.',
  '🇷🇸'
FROM countries WHERE code = 'RS';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '1 ene 2023', 'La facturación electrónica B2B (emisión y recepción) se vuelve obligatoria en todo el país' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '1 ene 2026', 'Fase 1 del albarán electrónico (e-otpremnica): sector público, bienes sujetos a impuestos especiales, transportistas' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '1 oct 2027', 'La Fase 2 de e-otpremnica se amplía al movimiento general de mercancías B2B del sector privado' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', 'RSD 200.000-2.000.000', 'Rango de multa central de facturación electrónica para personas jurídicas (arts. 18-19)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '109/2025', 'Última enmienda del Diario Oficial a la ley central de facturación electrónica (adoptada el 4 de diciembre de 2025)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'Formato y modelo de transmisión', '[["Formato de factura", "XML basado en UBL 2.1, con una CIUS específica de Serbia alineada con EN 16931"], ["Modelo de transmisión", "Clearance centralizado (CTC) -- toda factura es validada por SEF antes de llegar al destinatario, de forma similar al SDI italiano"], ["Formato de e-otpremnica", "También basado en UBL 2.1, gestionado por un \"Intermediario Central de Información\""], ["Canales de acceso", "Portal nacional de eID de SEF/e-otpremnica, interfaz web, aplicación móvil o API"]]', 'A diferencia del modelo descentralizado ZIERDED de Eslovenia, el SEF de Serbia es una auténtica plataforma gubernamental de clearance -- no existe ningún canal de transmisión alternativo permitido para el mandato central de facturación electrónica.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'file_format' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'Portal SEF y entornos', '[["Portal de producción", "efaktura.gov.rs"], ["Entorno de prueba/demo", "demoefaktura.mfin.gov.rs"], ["Portal e-otpremnica", "eotpremnica.efaktura.gov.rs"], ["Última versión", "SEF v4.1.0, publicada en producción el 2 de agosto de 2026"]]', 'El despliegue en producción de SEF v4.0.0 fue oficialmente pospuesto (anunciado el 24 de julio de 2026) sin indicar una nueva fecha -- la relación entre v4.1.0 y la versión v4.0.0 pospuesta no pudo confirmarse de forma independiente en esta investigación; verifique el comportamiento de la versión actual directamente con SEF antes de basarse en esta nota.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'file_format' AND cd.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'A quién cubre el mandato de facturación electrónica', '[["Alcance", "Todos los contribuyentes registrados a efectos del IVA, y todas las entidades que utilizan el sistema de contratación pública"], ["Umbral de tamaño", "Ninguno identificado en el texto de la ley"], ["B2G", "Obligatorio desde mayo-julio de 2022"], ["B2B", "Obligatorio desde el 1 de enero de 2023 (emisión y recepción)"], ["Registro del IVA", "El registro electrónico de la autoliquidación del IVA en SEF también es obligatorio desde el 1 de enero de 2023"]]', 'Si la facturación B2C (consumidor/minorista, recibo fiscal) queda dentro o fuera del mandato de e-Faktura no pudo confirmarse de forma independiente frente al texto de la ley en esta investigación -- fuentes secundarias sugieren que se rige por separado mediante las normas de las cajas registradoras fiscales, pero esto debe tratarse como no confirmado.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'scope_transmission' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'Despliegue del albarán electrónico (e-otpremnica)', '[["Base legal", "Zakon o elektronskim otpremnicama (Sl. glasnik RS 94/2024 i 109/2025) -- una ley independiente de la ley de facturación electrónica"], ["Fase 1 (1 de enero de 2026)", "Sector público, comerciantes de bienes sujetos a impuestos especiales (combustible, alcohol, tabaco, cigarrillos electrónicos, electricidad, café) y transportistas"], ["Período de gracia", "La aplicación plena de las inspecciones comenzó después del 30 de junio de 2026"], ["Fase 2 (1 de octubre de 2027)", "Se amplía al movimiento general de mercancías B2B del sector privado"]]', 'No confunda la Fase 2 de e-otpremnica con el paquete de reforma de facturación electrónica "B2B ampliado" reportado por separado (nuevos campos en SEF, validación más estricta, archivo completo de documentos, un nuevo régimen sancionador) -- fuentes secundarias describen ese paquete como pospuesto a "finales de 2026", un desarrollo distinto cuya fecha exacta no pudo confirmarse frente a un anuncio primario del Ministerio de Finanzas.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'scope_transmission' AND cd.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', '⚠️ Sanciones de facturación electrónica (arts. 18-21)', NULL, NULL, 'La Zakon o elektronskom fakturisanju establece multas escalonadas: RSD 200.000-2.000.000 para personas jurídicas/empresas públicas (por no emitir facturas electrónicas, registro incorrecto del IVA o incumplimiento del sistema), RSD 50.000-500.000 para empresarios, y RSD 50.000-150.000 para una persona responsable dentro de una entidad, aplicándose los mismos rangos a la obstrucción de la inspección (art. 21) y a los intermediarios de información que comprometan la seguridad del sistema (art. 19). Estas cifras provienen del texto legal consolidado de Paragraf.rs -- un editor jurídico serbio de buena reputación, pero un compilador secundario y no la Gaceta Oficial en bruto -- por lo que la atribución exacta de los artículos debe tratarse como indicativa hasta su verificación directa contra el texto en PDF de la gaceta.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', '🚚 Sanciones del albarán electrónico (arts. 13-14)', NULL, NULL, 'La Zakon o elektronskim otpremnicama establece sus propias multas escalonadas: RSD 200.000-2.000.000 para personas jurídicas (sector privado, transportistas, empresas públicas, por fallos de transmisión, infracciones de representación o incumplimientos de conservación de datos), RSD 50.000-150.000 para personas responsables, y RSD 50.000-500.000 para empresarios individuales, con multas fijas por obstrucción de la inspección (RSD 300.000 para personas jurídicas, RSD 50.000 para personas responsables, RSD 150.000 para empresarios individuales). Al igual que con las sanciones de facturación electrónica anteriores, estas cifras se obtienen del texto consolidado de Paragraf.rs, y no de una lectura directa del PDF de la gaceta.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', '🔍 Lo que no pudimos confirmar', NULL, NULL, 'Se señalan tres elementos de esta ronda de investigación en lugar de presentarlos como hechos establecidos: (1) la fecha exacta del paquete de reforma de facturación electrónica "B2B ampliado" reportado por separado, obtenida únicamente a través de un informe secundario (Fiscal Solutions) que cita un anuncio primario no localizado del Ministerio de Finanzas; (2) la relación entre la versión pospuesta SEF v4.0.0 y la versión v4.1.0 que entró en producción el 2 de agosto de 2026 -- no está claro si una sustituye o renombra a la otra; (3) si la facturación B2C/de recibo fiscal se encuentra dentro o fuera del mandato central de e-Faktura.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Confirme que su empresa ya emite y recibe facturas electrónicas a través de SEF', 'Esto es obligatorio para el comercio B2B con contrapartes serbias desde el 1 de enero de 2023 -- confirme que su software de facturación o su proveedor está conectado a SEF, y no depende del papel o de un PDF simple.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Si suministra bienes sujetos a impuestos especiales u opera como transportista en Serbia, confirme su preparación para e-otpremnica', 'La Fase 1 del mandato del albarán electrónico (sector público, comerciantes de bienes sujetos a impuestos especiales, transportistas) se aplica desde el 1 de enero de 2026, con la aplicación plena de las inspecciones ya vigente tras el período de gracia que finalizó el 30 de junio de 2026.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Si su empresa aún no está en una categoría de la Fase 1 de e-otpremnica, planifique con antelación a la Fase 2', 'A partir del 1 de octubre de 2027, la obligación del albarán electrónico se amplía al movimiento general de mercancías B2B del sector privado -- pruebe su proceso con suficiente antelación a esa fecha.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Siga los cambios de versión de SEF -- la fecha de producción de v4.0.0 sigue sin anunciarse', 'El Ministerio de Finanzas pospuso el despliegue en producción de SEF v4.0.0 (anunciado el 24 de julio de 2026) sin indicar una nueva fecha, mientras que una versión v4.1.0 entró en producción el 2 de agosto de 2026 -- confirme con el soporte de SEF qué versión se aplica a su integración.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Esté atento a la confirmación del paquete de reforma "B2B ampliado" reportado por separado', 'Fuentes secundarias han informado de nuevos campos de factura, validación más estricta, archivo completo de documentos y un nuevo régimen sancionador con objetivo para "finales de 2026", pero esto no se ha confirmado mediante un anuncio gubernamental primario -- no comprometa recursos de ingeniería en función de una fecha no confirmada.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'es', 'SEF -- Sistem elektronskih faktura, la plataforma central de facturación electrónica de Serbia' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'es', 'e-otpremnica -- la plataforma central de albarán electrónico' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'es', 'Sistema Oficial de Información Jurídica -- texto completo de la Zakon o elektronskom fakturisanju' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 2;

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-b2g-suppliers-2022', 'es',
  'Mandato B2G: los proveedores del sector público deben emitir facturas electrónicas',
  'Desde el 1 de mayo de 2022, todo proveedor del sector privado a un comprador del sector público serbio ha estado obligado a emitir facturas electrónicamente a través de SEF (Sistem elektronskih faktura), la plataforma central de facturación electrónica del gobierno, en virtud de la Zakon o elektronskom fakturisanju ("Sl. glasnik RS" br. 44/2021, 129/2021, 138/2022).',
  '["Confirme que su empresa emite facturas a compradores del sector público serbio a través de SEF, y no en papel o en PDF simple.","Regístrese para obtener una cuenta de SEF (efaktura.gov.rs) si aún no lo ha hecho."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-g2b-2022', 'es',
  'Se completa el tramo G2B: las entidades del sector público deben emitir facturas electrónicas a las empresas',
  'Desde el 1 de julio de 2022, las propias entidades del sector público serbio quedaron obligadas a emitir facturas electrónicas a empresas privadas a través de SEF, completando el tramo B2G/G2B del despliegue antes del mandato general B2B que siguió el 1 de enero de 2023.',
  '["Si recibe facturas de entidades del sector público serbio, confirme que su proceso de cuentas por pagar puede recibirlas a través de SEF."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-b2b-mandatory-2023', 'es',
  'La facturación electrónica B2B se vuelve obligatoria en todo el país',
  'Desde el 1 de enero de 2023, la facturación electrónica (tanto la emisión como la recepción) se volvió obligatoria en todo el sector privado de Serbia, para todos los contribuyentes registrados a efectos del IVA -- no se encontró ningún umbral de tamaño de empresa o de ingresos en el texto de la ley. Toda factura se envía a SEF y es validada por este antes de llegar al destinatario, un modelo de clearance centralizado (CTC) funcionalmente similar al SDI italiano, utilizando XML basado en UBL 2.1 con una CIUS específica de Serbia alineada con EN 16931.',
  '["Confirme que su software de facturación o su proveedor puede emitir y recibir facturas electrónicas conformes con SEF.","Si es una empresa extranjera que opera en Serbia mediante un número de identificación fiscal local o un representante fiscal, confirme que está registrada y conectada a SEF."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-vat-recording-2023', 'es',
  'El registro electrónico de la autoliquidación del IVA se vuelve obligatorio en SEF',
  'Junto con el mandato general de facturación electrónica B2B, los contribuyentes registrados a efectos del IVA también quedaron obligados a registrar electrónicamente el cálculo de su autoliquidación del IVA dentro de SEF desde el 1 de enero de 2023, en virtud del art. 4 de la ley central de facturación electrónica. Se trata de una obligación de registro del IVA que se añade al mandato de facturación electrónica, y no de un requisito de facturación independiente en sí mismo.',
  '["Confirme que su proceso de cumplimiento del IVA incluye el paso de registro electrónico del IVA en SEF, distinto de la simple emisión de facturas electrónicas."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-eotpremnica-phase1-2026', 'es',
  'Entra en vigor la Fase 1 del albarán electrónico (e-otpremnica)',
  'Una ley independiente, la Zakon o elektronskim otpremnicama ("Sl. glasnik RS" br. 94/2024 i 109/2025), hace obligatorios los albaranes electrónicos desde el 1 de enero de 2026 para las entidades del sector público, los comerciantes de bienes sujetos a impuestos especiales (combustible, alcohol, tabaco, cigarrillos electrónicos, electricidad, café) y los transportistas que presenten albaranes de transporte en controles de carretera. Se trata de un requisito de documentación del movimiento de mercancías, distinto del mandato de facturación electrónica -- un período de gracia se extendió hasta el 30 de junio de 2026 antes de que comenzara la aplicación plena de las inspecciones.',
  '["Si su empresa mueve bienes sujetos a impuestos especiales en Serbia u opera como transportista, confirme su preparación para e-otpremnica a través del portal eotpremnica.efaktura.gov.rs, la interfaz web, la aplicación móvil o la API.","Tenga en cuenta que esta obligación es independiente de la facturación electrónica de SEF -- el cumplimiento de una no cubre a la otra."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-eotpremnica-phase2-2027', 'es',
  'La Fase 2 del albarán electrónico (e-otpremnica) se amplía al sector privado en general',
  'A partir del 1 de octubre de 2027, la obligación de e-otpremnica se amplía más allá del alcance de la Fase 1 (sector público/bienes sujetos a impuestos especiales/transportistas) al movimiento general de mercancías B2B (y de recepción B2C) del sector privado. Nota: se trata de un desarrollo distinto del paquete de reforma de facturación electrónica "B2B ampliado" reportado por separado (nuevos campos de factura en SEF, validación más estricta, archivo completo de documentos, un nuevo régimen sancionador) que fuentes secundarias describen como pospuesto a "finales de 2026" -- la fecha exacta de esa reforma no pudo confirmarse frente a un anuncio primario del Ministerio de Finanzas al momento de escribir esto.',
  '["Si mueve mercancías B2B en Serbia fuera de las categorías de la Fase 1, planifique su preparación para e-otpremnica de cara a la fecha del 1 de octubre de 2027.","Esté atento a los canales oficiales de SEF/Ministerio de Finanzas para la confirmación del paquete de reforma de facturación electrónica \"B2B ampliado\" reportado por separado, cuya fecha exacta sigue sin confirmarse."]'
);

-- ==================== de ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'de',
  'Ausgereiftes zentrales Freigabesystem (Clearance): die verpflichtende B2B/B2G-E-Rechnungsstellung ist seit 2023 über die SEF-Plattform in Kraft, ergänzt nun um ein separates System für elektronische Lieferscheine (e-otpremnica) für den Warenverkehr, das in zwei Phasen zwischen 2026 und 2027 eingeführt wird',
  'Diese Analyseseite spiegelt das Zakon o elektronskom fakturisanju und das Zakon o elektronskim otpremnicama, wie sie im serbischen Amtsblatt (Sl. glasnik RS) veröffentlicht wurden, sowie öffentlich verfügbare behördliche Hinweise mit Stand Anfang August 2026 wider und dient allgemeinen Informationszwecken, nicht als Rechts- oder Steuerberatung. Bestätigen Sie aktuelle Anforderungen direkt beim serbischen Finanzministerium, den SEF-Support-Kanälen oder einem serbischen Steuer-/Rechtsberater, bevor Sie sich bei Compliance-Entscheidungen auf diese Seite verlassen.',
  'Die Einführung der E-Rechnungsstellung in Serbien begann im öffentlichen Sektor: Lieferanten öffentlicher Käufer mussten ab dem 1. Mai 2022 elektronische Rechnungen über SEF ausstellen, während öffentliche Stellen ab dem 1. Juli 2022 verpflichtet waren, Rechnungen an Unternehmen auszustellen. Die allgemeine B2B-Pflicht folgte am 1. Januar 2023 und machte die E-Rechnungsstellung (Ausstellung und Empfang) für den gesamten Privatsektor bei mehrwertsteuerpflichtigen Steuerpflichtigen verbindlich. Ein separates Gesetz, das Zakon o elektronskim otpremnicama, führt nun ein paralleles System elektronischer Lieferscheine ein, das in zwei Phasen eingeführt wird: öffentlicher Sektor, Händler verbrauchsteuerpflichtiger Waren und Frachtführer ab dem 1. Januar 2026, ausgeweitet auf den allgemeinen B2B-Warenverkehr des Privatsektors ab dem 1. Oktober 2027.',
  'Eine SEF-konforme E-Rechnung ist ein XML-Dokument auf Basis von UBL 2.1, mit einer serbienspezifischen CIUS, die am semantischen EU-Standard EN 16931 ausgerichtet ist. Die Übermittlung folgt einem zentralen Freigabemodell (CTC) -- jede Rechnung wird bei SEF (Sistem elektronskih faktura) eingereicht und von SEF validiert, bevor sie den Empfänger erreicht, funktional ähnlich dem italienischen SDI, wobei SEF auch als Rechnungsarchiv dient. Das e-otpremnica-System verwendet denselben UBL-2.1-basierten Ansatz und wird von einem \"zentralen Informationsvermittler\" verwaltet, zugänglich über das nationale eID-Portal, die Weboberfläche, die mobile App oder die API.',
  'Die E-Rechnungspflicht gilt für alle mehrwertsteuerpflichtigen Steuerpflichtigen und alle Einheiten, die das öffentliche Vergabesystem nutzen, ohne dass im Gesetzestext eine Unternehmensgrößen- oder Umsatzschwelle festgelegt wäre -- ausländische Unternehmen, die über eine lokale Steuernummer oder einen Fiskalvertreter tätig sind, sind eingeschlossen. Die e-otpremnica-Pflicht ist dagegen nach Tätigkeitskategorie gestaffelt: Phase 1 erfasst den öffentlichen Sektor, Händler verbrauchsteuerpflichtiger Waren und Frachtführer; Phase 2 (1. Oktober 2027) weitet sich auf den allgemeinen B2B-Warenverkehr des Privatsektors aus. Ob die B2C-/Kassenbeleg-Rechnungsstellung innerhalb oder außerhalb der zentralen e-Faktura-Pflicht liegt, konnte in dieser Recherche nicht unabhängig bestätigt werden.',
  'Die meisten Unternehmen, die mit Serbien Handel treiben, haben bereits eine bestehende SEF-E-Rechnungspflicht -- die Pflicht gilt seit 2023. Die neuere Aufgabe ist das e-otpremnica-System (elektronischer Lieferschein): Unternehmen in den Kategorien der Phase 1 (öffentlicher Sektor, verbrauchsteuerpflichtige Waren, Frachtführer) mussten bis zum 1. Januar 2026 bereit sein, wobei die Kontrolldurchsetzung inzwischen vollständig in Kraft ist, während andere Unternehmen, die B2B Waren bewegen, sich rechtzeitig vor dem Phase-2-Termin am 1. Oktober 2027 vorbereiten sollten.',
  'Serbien untermauert beide Gesetze mit realen, gestaffelten Bußgeldern. Sowohl das E-Rechnungsgesetz (Art. 18-21) als auch das Gesetz über elektronische Lieferscheine (Art. 13-14) legen Bußgeldrahmen nach Kategorie des Verstoßenden fest (juristische Personen, Unternehmer, verantwortliche Personen), hier bezogen aus dem konsolidierten Gesetzestext von Paragraf.rs -- einem angesehenen sekundären Kompilator, nicht dem Amtsblatt selbst, sodass die artikelweise Zuordnung bis zur direkten Verifizierung anhand des Amtsblatttexts als indikativ zu behandeln ist.',
  'Serbien verlangt seit Mai-Juli 2022 die B2G-E-Rechnungsstellung und seit dem 1. Januar 2023 die verpflichtende B2B-E-Rechnungsstellung (Ausstellung und Empfang, über die zentrale SEF-Plattform) für alle mehrwertsteuerpflichtigen Steuerpflichtigen. Ein separates, neueres Gesetz führt elektronische Lieferscheine (e-otpremnica) ein: verpflichtend ab dem 1. Januar 2026 für den öffentlichen Sektor, Händler verbrauchsteuerpflichtiger Waren und Frachtführer, ausgeweitet auf den allgemeinen B2B-Warenverkehr des Privatsektors ab dem 1. Oktober 2027. Ein weiteres \"erweitertes B2B\"-Reformpaket zur E-Rechnungsstellung (neue Felder, strengere Validierung, ein neues Bußgeldregime) wurde von Sekundärquellen als auf \"Ende 2026\" verschoben gemeldet, doch das genaue Datum konnte nicht anhand einer primären behördlichen Ankündigung bestätigt werden.',
  '🇷🇸'
FROM countries WHERE code = 'RS';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '1. Jan. 2023', 'B2B-E-Rechnungsstellung (Ausstellung und Empfang) wird landesweit verpflichtend' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '1. Jan. 2026', 'e-otpremnica (elektronischer Lieferschein) Phase 1: öffentlicher Sektor, verbrauchsteuerpflichtige Waren, Frachtführer' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '1. Okt. 2027', 'e-otpremnica Phase 2 weitet sich auf den allgemeinen B2B-Warenverkehr des Privatsektors aus' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', 'RSD 200.000-2.000.000', 'Zentraler Bußgeldrahmen der E-Rechnungsstellung für juristische Personen (Art. 18-19)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '109/2025', 'Jüngste Amtsblatt-Änderung des zentralen E-Rechnungsgesetzes (verabschiedet am 4. Dezember 2025)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'Format & Übermittlungsmodell', '[["Rechnungsformat", "XML auf Basis von UBL 2.1, mit einer serbienspezifischen CIUS, die an EN 16931 angelehnt ist"], ["Übermittlungsmodell", "Zentrale Freigabe (CTC) -- jede Rechnung wird von SEF validiert, bevor sie den Empfänger erreicht, ähnlich dem italienischen SDI"], ["e-otpremnica-Format", "Ebenfalls auf UBL 2.1 basierend, verwaltet von einem \"zentralen Informationsvermittler\""], ["Zugangskanäle", "Nationales eID-Portal von SEF/e-otpremnica, Weboberfläche, mobile App oder API"]]', 'Anders als Sloweniens dezentrales ZIERDED-Modell ist Serbiens SEF eine echte staatliche Freigabeplattform -- für die zentrale E-Rechnungspflicht gibt es keinen zulässigen alternativen Übermittlungskanal.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'file_format' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'SEF-Portal & Umgebungen', '[["Produktionsportal", "efaktura.gov.rs"], ["Test-/Demo-Umgebung", "demoefaktura.mfin.gov.rs"], ["e-otpremnica-Portal", "eotpremnica.efaktura.gov.rs"], ["Neueste Version", "SEF v4.1.0, am 2. Aug. 2026 in Produktion veröffentlicht"]]', 'Die Produktivsetzung von SEF v4.0.0 wurde offiziell verschoben (Ankündigung am 24. Juli 2026) ohne Angabe eines neuen Termins -- der Zusammenhang zwischen v4.1.0 und der verschobenen Version v4.0.0 konnte in dieser Recherche nicht unabhängig bestätigt werden; bestätigen Sie das aktuelle Versionsverhalten direkt bei SEF, bevor Sie sich auf diesen Hinweis verlassen.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'file_format' AND cd.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'Wen die E-Rechnungspflicht erfasst', '[["Anwendungsbereich", "Alle mehrwertsteuerpflichtigen Steuerpflichtigen und alle Einheiten, die das öffentliche Vergabesystem nutzen"], ["Größenschwelle", "Keine im Gesetzestext identifiziert"], ["B2G", "Verpflichtend seit Mai-Juli 2022"], ["B2B", "Verpflichtend seit 1. Januar 2023 (Ausstellung und Empfang)"], ["MwSt-Erfassung", "Die elektronische Erfassung der MwSt-Selbstveranlagung in SEF ist ebenfalls seit dem 1. Januar 2023 verpflichtend"]]', 'Ob die B2C-Rechnungsstellung (Verbraucher/Einzelhandel, Kassenbeleg) innerhalb oder außerhalb der e-Faktura-Pflicht liegt, konnte in dieser Recherche anhand des Gesetzestexts nicht unabhängig bestätigt werden -- Sekundärquellen deuten darauf hin, dass sie separat durch die Vorschriften zu Registrierkassen geregelt wird, doch dies sollte als unbestätigt behandelt werden.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'scope_transmission' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'Einführung des elektronischen Lieferscheins (e-otpremnica)', '[["Rechtsgrundlage", "Zakon o elektronskim otpremnicama (Sl. glasnik RS 94/2024 i 109/2025) -- ein von dem E-Rechnungsgesetz getrenntes Gesetz"], ["Phase 1 (1. Jan. 2026)", "Öffentlicher Sektor, Händler verbrauchsteuerpflichtiger Waren (Kraftstoff, Alkohol, Tabak, E-Zigaretten, Strom, Kaffee) und Frachtführer"], ["Übergangsfrist", "Die vollständige Kontrolldurchsetzung begann nach dem 30. Juni 2026"], ["Phase 2 (1. Okt. 2027)", "Ausweitung auf den allgemeinen B2B-Warenverkehr des Privatsektors"]]', 'Verwechseln Sie Phase 2 von e-otpremnica nicht mit dem separat gemeldeten \"erweiterten B2B\"-Reformpaket zur E-Rechnungsstellung (neue SEF-Felder, strengere Validierung, vollständige Dokumentenarchivierung, ein neues Bußgeldregime) -- Sekundärquellen beschreiben dieses Paket als auf \"Ende 2026\" verschoben, eine eigenständige Entwicklung, deren genaues Datum nicht anhand einer primären Ankündigung des Finanzministeriums bestätigt werden konnte.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'scope_transmission' AND cd.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', '⚠️ Sanktionen bei der E-Rechnungsstellung (Art. 18-21)', NULL, NULL, 'Das Zakon o elektronskom fakturisanju legt gestaffelte Bußgelder fest: RSD 200.000-2.000.000 für juristische Personen/öffentliche Unternehmen (Nichtausstellung von E-Rechnungen, fehlerhafte MwSt-Erfassung oder Systemverstöße), RSD 50.000-500.000 für Unternehmer, und RSD 50.000-150.000 für eine verantwortliche Person innerhalb einer Einheit, wobei dieselben Rahmen auch für die Behinderung von Kontrollen (Art. 21) und für Informationsvermittler gelten, die die Systemsicherheit gefährden (Art. 19). Diese Zahlen stammen aus dem konsolidierten Gesetzestext von Paragraf.rs -- einem angesehenen serbischen Rechtsverlag, jedoch einem sekundären Kompilator und nicht dem rohen Amtsblatt -- daher ist die genaue Artikelzuordnung als indikativ zu behandeln, bis sie direkt anhand des Amtsblatt-PDF-Texts verifiziert wird.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', '🚚 Sanktionen für den elektronischen Lieferschein (Art. 13-14)', NULL, NULL, 'Das Zakon o elektronskim otpremnicama legt eigene gestaffelte Bußgelder fest: RSD 200.000-2.000.000 für juristische Personen (Privatsektor, Frachtführer, öffentliche Unternehmen, bei Übermittlungsfehlern, Vertretungsverstößen oder Verstößen gegen die Datenaufbewahrung), RSD 50.000-150.000 für verantwortliche Personen, und RSD 50.000-500.000 für Einzelunternehmer, mit Pauschalbußgeldern bei Behinderung von Kontrollen (RSD 300.000 für juristische Personen, RSD 50.000 für verantwortliche Personen, RSD 150.000 für Einzelunternehmer). Wie bei den oben genannten E-Rechnungs-Sanktionen stammen diese Zahlen aus dem konsolidierten Text von Paragraf.rs und nicht aus einer direkten Lektüre des Amtsblatt-PDFs.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', '🔍 Was wir nicht bestätigen konnten', NULL, NULL, 'Drei Punkte werden aus dieser Rechercherunde als offen gekennzeichnet, statt als gesicherte Tatsache dargestellt: (1) das genaue neue Datum für das separat gemeldete \"erweiterte B2B\"-Reformpaket zur E-Rechnungsstellung, das ausschließlich über ein sekundäres Advisory (Fiscal Solutions) stammt, das sich auf eine nicht auffindbare primäre Ankündigung des Finanzministeriums beruft; (2) der Zusammenhang zwischen der verschobenen Version SEF v4.0.0 und der Version v4.1.0, die am 2. August 2026 in Produktion ging -- unklar, ob die eine die andere ersetzt oder umbenennt; (3) ob die B2C-/Kassenbeleg-Rechnungsstellung innerhalb oder außerhalb der zentralen e-Faktura-Pflicht liegt.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Bestätigen Sie, dass Ihr Unternehmen bereits E-Rechnungen über SEF ausstellt und empfängt', 'Dies ist für den B2B-Handel mit serbischen Geschäftspartnern seit dem 1. Januar 2023 verpflichtend -- bestätigen Sie, dass Ihre Rechnungssoftware oder Ihr Anbieter an SEF angebunden ist und sich nicht auf Papier oder einfaches PDF verlässt.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Wenn Sie in Serbien verbrauchsteuerpflichtige Waren liefern oder als Frachtführer tätig sind, bestätigen Sie Ihre e-otpremnica-Bereitschaft', 'Phase 1 der Pflicht zum elektronischen Lieferschein (öffentlicher Sektor, Händler verbrauchsteuerpflichtiger Waren, Frachtführer) gilt seit dem 1. Januar 2026, wobei die vollständige Kontrolldurchsetzung nach der bis 30. Juni 2026 laufenden Übergangsfrist nun in Kraft ist.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Wenn Ihr Unternehmen noch nicht zu einer e-otpremnica-Phase-1-Kategorie gehört, planen Sie rechtzeitig für Phase 2', 'Ab dem 1. Oktober 2027 weitet sich die Pflicht zum elektronischen Lieferschein auf den allgemeinen B2B-Warenverkehr des Privatsektors aus -- testen Sie Ihren Prozess rechtzeitig vor diesem Termin.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Verfolgen Sie SEF-Versionsänderungen -- der Produktionstermin von v4.0.0 bleibt unangekündigt', 'Das Finanzministerium verschob die Produktivsetzung von SEF v4.0.0 (Ankündigung am 24. Juli 2026), ohne einen neuen Termin zu nennen, während eine Version v4.1.0 am 2. August 2026 live ging -- bestätigen Sie beim SEF-Support, welche Version für Ihre Integration gilt.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Achten Sie auf die Bestätigung des separat gemeldeten \"erweiterten B2B\"-Reformpakets', 'Neue Rechnungsfelder, strengere Validierung, vollständige Dokumentenarchivierung und ein neues Bußgeldregime wurden von Sekundärquellen mit dem Zieltermin \"Ende 2026\" gemeldet, doch dies wurde nicht durch eine primäre behördliche Ankündigung bestätigt -- binden Sie keine Entwicklungsressourcen an ein unbestätigtes Datum.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'de', 'SEF -- Sistem elektronskih faktura, Serbiens zentrale E-Rechnungsplattform' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'de', 'e-otpremnica -- die zentrale Plattform für elektronische Lieferscheine' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'de', 'Offizielles Rechtsinformationssystem -- vollständiger Text des Zakon o elektronskom fakturisanju' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 2;

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-b2g-suppliers-2022', 'de',
  'B2G-Pflicht: Lieferanten des öffentlichen Sektors müssen E-Rechnungen ausstellen',
  'Seit dem 1. Mai 2022 ist jeder Lieferant des Privatsektors an einen serbischen öffentlichen Käufer verpflichtet, Rechnungen elektronisch über SEF (Sistem elektronskih faktura), die zentrale E-Rechnungsplattform der Regierung, auszustellen, gemäß dem Zakon o elektronskom fakturisanju ("Sl. glasnik RS" br. 44/2021, 129/2021, 138/2022).',
  '["Bestätigen Sie, dass Ihr Unternehmen Rechnungen an serbische öffentliche Käufer über SEF ausstellt, nicht per Papier oder einfachem PDF.","Registrieren Sie sich für ein SEF-Konto (efaktura.gov.rs), falls noch nicht geschehen."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-g2b-2022', 'de',
  'G2B-Teil abgeschlossen: öffentliche Stellen müssen E-Rechnungen an Unternehmen ausstellen',
  'Seit dem 1. Juli 2022 mussten serbische öffentliche Stellen selbst E-Rechnungen über SEF an private Unternehmen ausstellen und schlossen damit den B2G/G2B-Teil der Einführung vor der allgemeinen B2B-Pflicht ab, die am 1. Januar 2023 folgte.',
  '["Wenn Sie Rechnungen von serbischen öffentlichen Stellen erhalten, bestätigen Sie, dass Ihr Kreditorenprozess diese über SEF empfangen kann."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-b2b-mandatory-2023', 'de',
  'B2B-E-Rechnungsstellung wird landesweit verpflichtend',
  'Seit dem 1. Januar 2023 ist die E-Rechnungsstellung (sowohl Ausstellung als auch Empfang) im gesamten serbischen Privatsektor für alle mehrwertsteuerpflichtigen Steuerpflichtigen verpflichtend -- im Gesetzestext wurde keine Unternehmensgrößen- oder Umsatzschwelle gefunden. Jede Rechnung wird bei SEF eingereicht und von SEF validiert, bevor sie den Empfänger erreicht, ein zentrales Freigabemodell (CTC), das funktional dem italienischen SDI ähnelt, unter Verwendung von XML auf Basis von UBL 2.1 mit einer serbienspezifischen CIUS, die an EN 16931 angelehnt ist.',
  '["Bestätigen Sie, dass Ihre Rechnungssoftware oder Ihr Anbieter SEF-konforme E-Rechnungen ausstellen und empfangen kann.","Wenn Sie ein ausländisches Unternehmen sind, das in Serbien über eine lokale Steuernummer oder einen Fiskalvertreter tätig ist, bestätigen Sie, dass Sie registriert und mit SEF verbunden sind."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-vat-recording-2023', 'de',
  'Die elektronische Erfassung der MwSt-Selbstveranlagung wird in SEF verpflichtend',
  'Neben der allgemeinen B2B-E-Rechnungspflicht mussten mehrwertsteuerpflichtige Steuerpflichtige ab dem 1. Januar 2023 auch ihre MwSt-Selbstveranlagungsberechnung elektronisch innerhalb von SEF erfassen, gemäß Art. 4 des zentralen E-Rechnungsgesetzes. Dies ist eine der E-Rechnungspflicht übergeordnete MwSt-Erfassungspflicht, keine eigenständige separate Rechnungsanforderung.',
  '["Bestätigen Sie, dass Ihr MwSt-Compliance-Prozess den Schritt der elektronischen MwSt-Erfassung in SEF umfasst, getrennt von der bloßen Ausstellung von E-Rechnungen."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-eotpremnica-phase1-2026', 'de',
  'Phase 1 des elektronischen Lieferscheins (e-otpremnica) tritt in Kraft',
  'Ein separates Gesetz, das Zakon o elektronskim otpremnicama ("Sl. glasnik RS" br. 94/2024 i 109/2025), macht elektronische Lieferscheine ab dem 1. Januar 2026 für öffentliche Stellen, Händler verbrauchsteuerpflichtiger Waren (Kraftstoff, Alkohol, Tabak, E-Zigaretten, Strom, Kaffee) und Frachtführer, die bei Straßenkontrollen Frachtpapiere vorlegen, verpflichtend. Dies ist eine Dokumentationspflicht für den Warenverkehr, getrennt von der E-Rechnungspflicht -- eine Übergangsfrist lief bis zum 30. Juni 2026, bevor die vollständige Kontrolldurchsetzung begann.',
  '["Wenn Ihr Unternehmen in Serbien verbrauchsteuerpflichtige Waren bewegt oder als Frachtführer tätig ist, bestätigen Sie Ihre e-otpremnica-Bereitschaft über das Portal eotpremnica.efaktura.gov.rs, die Weboberfläche, die mobile App oder die API.","Beachten Sie, dass diese Pflicht getrennt von der SEF-E-Rechnungsstellung besteht -- die Einhaltung der einen deckt die andere nicht ab."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-eotpremnica-phase2-2027', 'de',
  'Phase 2 des elektronischen Lieferscheins (e-otpremnica) weitet sich auf den allgemeinen Privatsektor aus',
  'Ab dem 1. Oktober 2027 weitet sich die e-otpremnica-Pflicht über den Anwendungsbereich der Phase 1 (öffentlicher Sektor/verbrauchsteuerpflichtige Waren/Frachtführer) hinaus auf den allgemeinen B2B-Warenverkehr (und den B2C-Empfang) des Privatsektors aus. Hinweis: Dies ist eine eigenständige Entwicklung, getrennt von einem separat gemeldeten "erweiterten B2B-E-Rechnungsreformpaket" (neue SEF-Rechnungsfelder, strengere Validierung, vollständige Dokumentenarchivierung, ein neues Bußgeldregime), das Sekundärquellen als auf "Ende 2026" verschoben beschreiben -- das genaue Datum dieser Reform konnte zum Zeitpunkt der Abfassung nicht anhand einer primären Ankündigung des Finanzministeriums bestätigt werden.',
  '["Wenn Sie in Serbien B2B-Waren außerhalb der Phase-1-Kategorien bewegen, planen Sie Ihre e-otpremnica-Bereitschaft für den Termin am 1. Oktober 2027.","Beobachten Sie die offiziellen Kanäle von SEF/Finanzministerium auf eine Bestätigung des separat gemeldeten \"erweiterten B2B\"-E-Rechnungsreformpakets, dessen genaues Datum weiterhin unbestätigt ist."]'
);

-- ==================== fr ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'fr',
  'Régime mature de dédouanement centralisé : la facturation électronique B2B/B2G obligatoire est en vigueur depuis 2023 via la plateforme SEF, à laquelle s''ajoute désormais un système distinct de bon de livraison électronique (e-otpremnica) pour le mouvement des marchandises, déployé en deux phases entre 2026 et 2027',
  'Cette page d''analyse reflète la Zakon o elektronskom fakturisanju et la Zakon o elektronskim otpremnicama telles que publiées au Journal officiel de Serbie (Sl. glasnik RS), ainsi que les indications publiques des autorités disponibles début août 2026, et est fournie à titre d''information générale, non comme un conseil juridique ou fiscal. Confirmez les exigences actuelles directement auprès du ministère des Finances de Serbie, des canaux d''assistance de SEF, ou d''un conseiller fiscal/juridique serbe avant de fonder vos décisions de conformité sur cette page.',
  'Le déploiement de la facturation électronique en Serbie a débuté avec le secteur public : les fournisseurs d''acheteurs du secteur public ont été tenus d''émettre des factures électroniques via SEF à partir du 1er mai 2022, les entités du secteur public devant elles-mêmes en émettre aux entreprises à partir du 1er juillet 2022. L''obligation générale B2B a suivi le 1er janvier 2023, rendant la facturation électronique (émission et réception) obligatoire dans l''ensemble du secteur privé pour les assujettis à la TVA. Une loi distincte, la Zakon o elektronskim otpremnicama, ajoute désormais un système parallèle de bon de livraison électronique, déployé en deux phases : le secteur public, les négociants en produits soumis à accise et les transporteurs à partir du 1er janvier 2026, avant une extension au mouvement général de marchandises B2B du secteur privé à partir du 1er octobre 2027.',
  'Une facture électronique conforme à SEF est un fichier XML fondé sur UBL 2.1, avec une CIUS propre à la Serbie alignée sur la norme sémantique EN 16931 de l''UE. La transmission suit un modèle de dédouanement centralisé (CTC) -- chaque facture est soumise à SEF (Sistem elektronskih faktura) et validée par celui-ci avant d''atteindre le destinataire, de façon fonctionnellement similaire au SDI italien, SEF faisant également office de dépôt des factures. Le système e-otpremnica utilise la même approche fondée sur UBL 2.1, géré par un « intermédiaire central d''information », accessible via le portail national eID, l''interface web, l''application mobile ou l''API.',
  'L''obligation de facturation électronique s''applique à tous les assujettis à la TVA et à toutes les entités utilisant le système de marchés publics, sans aucun seuil de taille d''entreprise ou de chiffre d''affaires identifié dans le texte de la loi -- les entreprises étrangères opérant via un numéro fiscal local ou un représentant fiscal sont incluses. L''obligation e-otpremnica est en revanche échelonnée par catégorie d''activité : la Phase 1 couvre le secteur public, les négociants en produits soumis à accise et les transporteurs ; la Phase 2 (1er octobre 2027) s''étend au mouvement général de marchandises B2B du secteur privé. La question de savoir si la facturation B2C/au titre du reçu fiscal relève ou non de l''obligation centrale e-Faktura n''a pas pu être confirmée de manière indépendante au cours de cette recherche.',
  'La plupart des entreprises qui commercent avec la Serbie ont déjà une obligation active de facturation électronique via SEF -- l''obligation est en vigueur depuis 2023. Le chantier le plus récent est le système e-otpremnica (bon de livraison électronique) : les entreprises relevant des catégories de la Phase 1 (secteur public, produits soumis à accise, transporteurs) devaient être prêtes avant le 1er janvier 2026, le contrôle par inspection étant désormais pleinement effectif, tandis que les autres entreprises qui déplacent des marchandises en B2B devraient se préparer bien avant l''échéance de la Phase 2, le 1er octobre 2027.',
  'La Serbie appuie les deux lois sur des amendes réelles et échelonnées. La loi sur la facturation électronique (art. 18-21) et la loi sur le bon de livraison électronique (art. 13-14) fixent toutes deux des fourchettes de sanctions selon la catégorie du contrevenant (personnes morales, entrepreneurs, personnes responsables), obtenues ici via le texte juridique consolidé de Paragraf.rs -- un compilateur secondaire réputé, mais non le journal officiel lui-même, de sorte que l''attribution article par article doit être considérée comme indicative en attendant une vérification directe du texte du journal officiel.',
  'La Serbie exige la facturation électronique B2G depuis mai-juillet 2022, et la facturation électronique B2B obligatoire (émission et réception, via la plateforme centralisée SEF) depuis le 1er janvier 2023, pour tous les assujettis à la TVA. Une loi distincte, plus récente, ajoute les bons de livraison électroniques (e-otpremnica) : obligatoires à partir du 1er janvier 2026 pour le secteur public, les négociants en produits soumis à accise et les transporteurs, avec une extension au mouvement général de marchandises B2B du secteur privé à partir du 1er octobre 2027. Un autre train de réformes « B2B élargi » de la facturation électronique (nouveaux champs, validation plus stricte, nouveau régime de sanctions) aurait été reporté, selon des sources secondaires, à « fin 2026 », mais sa date exacte n''a pas pu être confirmée par une annonce gouvernementale primaire.',
  '🇷🇸'
FROM countries WHERE code = 'RS';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '1er janv. 2023', 'La facturation électronique B2B (émission et réception) devient obligatoire dans tout le pays' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '1er janv. 2026', 'Phase 1 du bon de livraison électronique (e-otpremnica) : secteur public, produits soumis à accise, transporteurs' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '1er oct. 2027', 'La Phase 2 d''e-otpremnica s''étend au mouvement général de marchandises B2B du secteur privé' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', 'RSD 200 000-2 000 000', 'Fourchette d''amende centrale de facturation électronique pour les personnes morales (art. 18-19)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '109/2025', 'Dernière modification du Journal officiel apportée à la loi centrale sur la facturation électronique (adoptée le 4 décembre 2025)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'RS' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'Format et modèle de transmission', '[["Format de facture", "XML fondé sur UBL 2.1, avec une CIUS propre à la Serbie alignée sur EN 16931"], ["Modèle de transmission", "Dédouanement centralisé (CTC) -- chaque facture est validée par SEF avant d''atteindre le destinataire, de façon similaire au SDI italien"], ["Format e-otpremnica", "Également fondé sur UBL 2.1, géré par un « intermédiaire central d''information »"], ["Canaux d''accès", "Portail national eID de SEF/e-otpremnica, interface web, application mobile, ou API"]]', 'Contrairement au modèle décentralisé ZIERDED de la Slovénie, le SEF serbe est une véritable plateforme gouvernementale de dédouanement -- il n''existe aucun canal de transmission alternatif autorisé pour l''obligation centrale de facturation électronique.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'file_format' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'Portail SEF et environnements', '[["Portail de production", "efaktura.gov.rs"], ["Environnement de test/démonstration", "demoefaktura.mfin.gov.rs"], ["Portail e-otpremnica", "eotpremnica.efaktura.gov.rs"], ["Dernière version", "SEF v4.1.0, mise en production le 2 août 2026"]]', 'Le déploiement en production de SEF v4.0.0 a été officiellement reporté (annonce du 24 juillet 2026) sans nouvelle date communiquée -- le lien entre la version v4.1.0 et la version v4.0.0 reportée n''a pas pu être confirmé de manière indépendante au cours de cette recherche ; vérifiez le comportement de la version actuelle directement auprès de SEF avant de vous fier à cette remarque.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'file_format' AND cd.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'Qui est couvert par l''obligation de facturation électronique', '[["Champ d''application", "Tous les assujettis à la TVA, et toutes les entités utilisant le système de marchés publics"], ["Seuil de taille", "Aucun identifié dans le texte de la loi"], ["B2G", "Obligatoire depuis mai-juillet 2022"], ["B2B", "Obligatoire depuis le 1er janvier 2023 (émission et réception)"], ["Enregistrement de la TVA", "L''enregistrement électronique de l''auto-liquidation de la TVA dans SEF est également obligatoire depuis le 1er janvier 2023"]]', 'La question de savoir si la facturation B2C (consommateur/détail, reçu fiscal) relève ou non de l''obligation e-Faktura n''a pas pu être confirmée de manière indépendante par rapport au texte de la loi au cours de cette recherche -- des sources secondaires suggèrent qu''elle est régie séparément par les règles relatives aux caisses enregistreuses fiscales, mais ce point doit être considéré comme non confirmé.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'scope_transmission' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'Déploiement du bon de livraison électronique (e-otpremnica)', '[["Base légale", "Zakon o elektronskim otpremnicama (Sl. glasnik RS 94/2024 i 109/2025) -- une loi distincte de la loi sur la facturation électronique"], ["Phase 1 (1er janvier 2026)", "Secteur public, négociants en produits soumis à accise (carburant, alcool, tabac, cigarettes électroniques, électricité, café), et transporteurs"], ["Période de grâce", "Le contrôle intégral par inspection a débuté après le 30 juin 2026"], ["Phase 2 (1er octobre 2027)", "Extension au mouvement général de marchandises B2B du secteur privé"]]', 'Ne confondez pas la Phase 2 d''e-otpremnica avec le train de réformes « B2B élargi » de la facturation électronique signalé séparément (nouveaux champs SEF, validation plus stricte, archivage complet des documents, nouveau régime de sanctions) -- des sources secondaires décrivent ce train de réformes comme reporté à « fin 2026 », un développement distinct dont la date exacte n''a pas pu être confirmée par une annonce primaire du ministère des Finances.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'scope_transmission' AND cd.sort_order = 1;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', '⚠️ Sanctions relatives à la facturation électronique (art. 18-21)', NULL, NULL, 'La Zakon o elektronskom fakturisanju fixe des amendes échelonnées : RSD 200 000-2 000 000 pour les personnes morales/entreprises publiques (défaut d''émission de factures électroniques, enregistrement incorrect de la TVA, ou non-conformité du système), RSD 50 000-500 000 pour les entrepreneurs, et RSD 50 000-150 000 pour une personne responsable au sein d''une entité, les mêmes fourchettes s''appliquant à l''entrave à l''inspection (art. 21) et aux intermédiaires d''information compromettant la sécurité du système (art. 19). Ces montants proviennent du texte juridique consolidé de Paragraf.rs -- un éditeur juridique serbe réputé, mais un compilateur secondaire et non le Journal officiel brut -- l''attribution exacte par article doit donc être considérée comme indicative en attendant une vérification directe du texte PDF du journal officiel.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', '🚚 Sanctions relatives au bon de livraison électronique (art. 13-14)', NULL, NULL, 'La Zakon o elektronskim otpremnicama fixe ses propres amendes échelonnées : RSD 200 000-2 000 000 pour les personnes morales (secteur privé, transporteurs, entreprises publiques, pour les défaillances de transmission, les violations de représentation, ou les manquements à la conservation des données), RSD 50 000-150 000 pour les personnes responsables, et RSD 50 000-500 000 pour les entrepreneurs individuels, avec des amendes forfaitaires en cas d''entrave à l''inspection (RSD 300 000 pour les personnes morales, RSD 50 000 pour les personnes responsables, RSD 150 000 pour les entrepreneurs individuels). Comme pour les sanctions de facturation électronique ci-dessus, ces montants proviennent du texte consolidé de Paragraf.rs, et non d''une lecture directe du PDF du journal officiel.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', '🔍 Ce que nous n''avons pas pu confirmer', NULL, NULL, 'Trois points sont signalés à l''issue de cette phase de recherche plutôt que présentés comme des faits établis : (1) la date exacte du train de réformes « B2B élargi » de la facturation électronique signalé séparément, obtenue uniquement via un avis secondaire (Fiscal Solutions) citant une annonce primaire introuvable du ministère des Finances ; (2) le lien entre la version SEF v4.0.0 reportée et la version v4.1.0 mise en production le 2 août 2026 -- on ignore si l''une remplace ou renomme l''autre ; (3) si la facturation B2C/au titre du reçu fiscal relève ou non de l''obligation centrale e-Faktura.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id WHERE c.code = 'RS' AND cd.section = 'penalties_related' AND cd.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Vérifiez que votre entreprise émet et reçoit déjà des factures électroniques via SEF', 'Cette obligation s''applique aux échanges B2B avec des contreparties serbes depuis le 1er janvier 2023 -- vérifiez que votre logiciel de facturation ou votre prestataire est connecté à SEF, sans dépendre du papier ou d''un simple PDF.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Si vous fournissez des produits soumis à accise ou opérez comme transporteur en Serbie, vérifiez votre état de préparation à e-otpremnica', 'La Phase 1 de l''obligation de bon de livraison électronique (secteur public, négociants en produits soumis à accise, transporteurs) s''applique depuis le 1er janvier 2026, le contrôle intégral par inspection étant désormais effectif après la période de grâce qui s''est achevée le 30 juin 2026.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Si votre entreprise ne relève pas encore d''une catégorie de la Phase 1 d''e-otpremnica, anticipez la Phase 2', 'À partir du 1er octobre 2027, l''obligation de bon de livraison électronique s''étend au mouvement général de marchandises B2B du secteur privé -- testez votre processus bien avant cette échéance.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Suivez les changements de version de SEF -- la date de production de v4.0.0 reste non annoncée', 'Le ministère des Finances a reporté la mise en production de SEF v4.0.0 (annonce du 24 juillet 2026) sans communiquer de nouvelle date, tandis qu''une version v4.1.0 est entrée en production le 2 août 2026 -- confirmez auprès de l''assistance SEF quelle version s''applique à votre intégration.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Surveillez la confirmation du train de réformes « B2B élargi » signalé séparément', 'De nouveaux champs de facture, une validation plus stricte, un archivage complet des documents et un nouveau régime de sanctions ont été signalés par des sources secondaires comme visant « fin 2026 », mais cela n''a pas été confirmé par une annonce gouvernementale primaire -- n''engagez pas de ressources d''ingénierie sur la base d''une date non confirmée.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'RS' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'fr', 'SEF -- Sistem elektronskih faktura, la plateforme centrale de facturation électronique de la Serbie' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'fr', 'e-otpremnica -- la plateforme centrale de bon de livraison électronique' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'fr', 'Système officiel d''information juridique -- texte intégral de la Zakon o elektronskom fakturisanju' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'RS' AND pt.sort_order = 2;

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-b2g-suppliers-2022', 'fr',
  'Obligation B2G : les fournisseurs du secteur public doivent émettre des factures électroniques',
  'Depuis le 1er mai 2022, tout fournisseur du secteur privé à un acheteur du secteur public serbe est tenu d''émettre ses factures électroniquement via SEF (Sistem elektronskih faktura), la plateforme centrale de facturation électronique du gouvernement, en vertu de la Zakon o elektronskom fakturisanju (« Sl. glasnik RS » br. 44/2021, 129/2021, 138/2022).',
  '["Vérifiez que votre entreprise émet ses factures aux acheteurs du secteur public serbe via SEF, et non sur papier ou en simple PDF.","Inscrivez-vous pour obtenir un compte SEF (efaktura.gov.rs) si ce n''est pas déjà fait."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-g2b-2022', 'fr',
  'Le volet G2B s''achève : les entités du secteur public doivent émettre des factures électroniques aux entreprises',
  'Depuis le 1er juillet 2022, les entités du secteur public serbe elles-mêmes ont été tenues d''émettre des factures électroniques à des entreprises privées via SEF, achevant ainsi le volet B2G/G2B du déploiement avant l''obligation générale B2B qui a suivi le 1er janvier 2023.',
  '["Si vous recevez des factures d''entités du secteur public serbe, vérifiez que votre processus de comptes fournisseurs peut les recevoir via SEF."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-b2b-mandatory-2023', 'fr',
  'La facturation électronique B2B devient obligatoire dans tout le pays',
  'Depuis le 1er janvier 2023, la facturation électronique (émission et réception) est devenue obligatoire dans l''ensemble du secteur privé serbe, pour tous les assujettis à la TVA -- aucun seuil de taille d''entreprise ou de chiffre d''affaires n''a été trouvé dans le texte de la loi. Chaque facture est soumise à SEF et validée par celui-ci avant d''atteindre le destinataire, un modèle de dédouanement centralisé (CTC) fonctionnellement similaire au SDI italien, utilisant un XML fondé sur UBL 2.1 avec une CIUS propre à la Serbie alignée sur EN 16931.',
  '["Vérifiez que votre logiciel de facturation ou votre prestataire peut émettre et recevoir des factures électroniques conformes à SEF.","Si vous êtes une entreprise étrangère opérant en Serbie via un numéro fiscal local ou un représentant fiscal, vérifiez que vous êtes inscrit et connecté à SEF."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-vat-recording-2023', 'fr',
  'L''enregistrement électronique de l''auto-liquidation de la TVA devient obligatoire dans SEF',
  'Parallèlement à l''obligation générale de facturation électronique B2B, les assujettis à la TVA ont également été tenus d''enregistrer électroniquement le calcul de leur auto-liquidation de la TVA au sein de SEF à partir du 1er janvier 2023, en vertu de l''art. 4 de la loi centrale sur la facturation électronique. Il s''agit d''une obligation d''enregistrement de la TVA qui se superpose à l''obligation de facturation électronique, et non d''une exigence de facturation distincte en soi.',
  '["Vérifiez que votre processus de conformité TVA inclut l''étape d''enregistrement électronique de la TVA dans SEF, distincte de la simple émission de factures électroniques."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-eotpremnica-phase1-2026', 'fr',
  'La Phase 1 du bon de livraison électronique (e-otpremnica) prend effet',
  'Une loi distincte, la Zakon o elektronskim otpremnicama (« Sl. glasnik RS » br. 94/2024 i 109/2025), rend les bons de livraison électroniques obligatoires à partir du 1er janvier 2026 pour les entités du secteur public, les négociants en produits soumis à accise (carburant, alcool, tabac, cigarettes électroniques, électricité, café), et les transporteurs présentant des lettres de voiture lors des contrôles routiers. Il s''agit d''une exigence de documentation du mouvement de marchandises, distincte de l''obligation de facturation électronique -- une période de grâce a couru jusqu''au 30 juin 2026 avant le début du contrôle intégral par inspection.',
  '["Si votre entreprise déplace des produits soumis à accise en Serbie ou opère comme transporteur, vérifiez votre état de préparation à e-otpremnica via le portail eotpremnica.efaktura.gov.rs, l''interface web, l''application mobile, ou l''API.","Notez que cette obligation est distincte de la facturation électronique SEF -- la conformité à l''une ne couvre pas l''autre."]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'rs-eotpremnica-phase2-2027', 'fr',
  'La Phase 2 du bon de livraison électronique (e-otpremnica) s''étend au secteur privé général',
  'À partir du 1er octobre 2027, l''obligation e-otpremnica s''étend au-delà du champ d''application de la Phase 1 (secteur public/produits soumis à accise/transporteurs) au mouvement général de marchandises B2B (et à la réception B2C) du secteur privé. Remarque : il s''agit d''un développement distinct du train de réformes « B2B élargi » de la facturation électronique signalé séparément (nouveaux champs de facture SEF, validation plus stricte, archivage complet des documents, nouveau régime de sanctions) que des sources secondaires décrivent comme reporté à « fin 2026 » -- la date exacte de cette réforme n''a pas pu être confirmée par une annonce primaire du ministère des Finances au moment de la rédaction.',
  '["Si vous déplacez des marchandises en B2B en Serbie en dehors des catégories de la Phase 1, planifiez votre préparation à e-otpremnica en vue de l''échéance du 1er octobre 2027.","Surveillez les canaux officiels de SEF/du ministère des Finances pour la confirmation du train de réformes « B2B élargi » de la facturation électronique signalé séparément, dont la date exacte demeure non confirmée."]'
);
