-- Dominican Republic deep-dive content (English). A real-time
-- pre-validation clearance regime (e-CF / Comprobante Fiscal
-- Electrónico), mandatory under Ley 32-23 (2023) and rolling out in
-- phased waves by DGII taxpayer-size category through Nov 2026.
-- Live-researched directly against DGII's own hosted documents (Ley
-- 32-23's full PDF text, Norma General 01-2020, DGII's own news
-- releases and avisosInformativos index, and DGII's own e-CF technical
-- report) -- all fetched directly. See PROGRESS.md's dated build entry
-- for the full citation trail, including flagged gaps: Decreto 587-24's
-- exact calendar day (three secondary sources disagree), the 2019
-- pilot's exact statistics (single-newspaper source), and the claim
-- that e-CF's XML format is UBL-based (a vendor-only claim, not
-- confirmed by DGII's own technical documentation).

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-06' FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en',
  'Real-time pre-validation clearance (CTC) regime: mandatory e-CF live since 2024 for Large National Taxpayers, rolling out in phased waves by DGII taxpayer-size category through the final 15 November 2026 deadline',
  'This deep-dive page reflects Ley 32-23, Norma General 01-2020, and DGII''s own avisos and technical documentation, as confirmed via direct fetches of DGII''s own hosted documents (dgii.gov.do) as of early August 2026, and is provided for general awareness, not legal or tax advice. Confirm current requirements directly with the Dirección General de Impuestos Internos (DGII), an authorized Proveedor de Servicios (PSFE), or a Dominican tax/legal adviser before relying on this page for compliance decisions.',
  'The Dominican Republic''s e-CF program began with a voluntary pilot (1 Feb-31 Dec 2019), formalized as a voluntary authorization regime by Norma General 01-2020. Ley 32-23, promulgated 16 May 2023, made e-CF mandatory on a phased timeline by DGII taxpayer-size category: Large National Taxpayers from 15 May 2024, Large Local & Medium Taxpayers from an extended 15 November 2025, and Small, Micro & Unclassified Taxpayers from an extended 15 November 2026 -- the current final wave.',
  'A compliant e-CF is XML, submitted to DGII for real-time pre-validation before it is valid for the buyer -- DGII''s own technical report confirms the issuer sends the XML, DGII validates it, and returns a TrackID plus one of four statuses (aceptado, aceptado condicional, rechazado, en proceso). Only a DGII-accepted e-CF supports the buyer''s commercial approval or tax deduction. Digital signing requires a certificate from an INDOTEL-accredited provider under Ley 126-02. One vendor source describes the XML schema as UBL-based; DGII''s own technical documentation does not itself name UBL, so this should be treated as a plausible but unconfirmed detail.',
  'The mandate is phased strictly by DGII''s own administrative taxpayer-size classification (Gran Contribuyente Nacional, Gran Contribuyente Local, Mediano, Pequeño, Micro, No Clasificado), frozen as of Ley 32-23''s 16 May 2023 effective date so no taxpayer can be reclassified to dodge a wave. No revenue-threshold figures in Dominican pesos were found publicly codifying these categories -- they are DGII''s own internal register. Government/state entities follow the same wave structure as their private-sector size-equivalents (large entities in the 2024 wave, others in the final 2026 wave).',
  'Large National Taxpayers have had a live e-CF obligation since May 2024, and since 1 January 2026 may issue e-CF exclusively -- paper vouchers no longer apply to this segment. Large Local & Medium Taxpayers followed in November 2025. The final wave -- Small, Micro & Unclassified Taxpayers -- has a current deadline of 15 November 2026, and DGII reports adoption accelerating fast in this segment even ahead of the deadline.',
  'Ley 32-23 backs the mandate with both administrative tax infractions (Art. 26-29, fines denominated in multiples of the minimum salary under the Código Tributario) and criminal offenses for e-CF fraud and unauthorized system access (Art. 30-31, carrying imprisonment).',
  'The Dominican Republic has required e-CF (Comprobante Fiscal Electrónico) from Large National Taxpayers since 15 May 2024, under Ley 32-23 (promulgated 16 May 2023). The mandate rolls out in phased waves by DGII taxpayer-size category: Large Local & Medium Taxpayers from an extended 15 November 2025, and Small, Micro & Unclassified Taxpayers from an extended 15 November 2026, the current final wave. From 1 January 2026, Large National Taxpayers may issue e-CF exclusively, with paper vouchers retired for that segment. By July 2026, DGII reported over 1.86 billion cumulative e-CF issued and registered electronic filers had more than tripled since January 2026.',
  '🇩🇴'
FROM countries WHERE code = 'DO';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '16 May 2023', 'Ley 32-23 promulgated, establishing the mandatory e-CF regime');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '15 Nov 2026', 'Final rollout wave: Small, Micro & Unclassified Taxpayers must issue e-CF');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1.86 billion+', 'Cumulative e-CF issued nationwide by 1 July 2026');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '76,762', 'Registered electronic filers by Jul 2026 -- more than tripled from 23,686 in Jan 2026');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '150/month', 'Free-tier cap on DGII''s own Facturador Gratuito invoicing tool');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & validation statuses', '[["Invoice format", "XML, per DGII''s own e-CF technical report"], ["Validation statuses", "aceptado / aceptado condicional / rechazado / en proceso, returned with a TrackID"], ["Legal effect", "Only a DGII-accepted e-CF supports the buyer''s commercial approval or tax deduction"], ["Digital signature", "Certificate from an INDOTEL-accredited provider, per Ley 126-02"]]', 'One vendor source (EDICOM) describes the XML as UBL-based; DGII''s own technical report does not itself name UBL as the base standard -- treat the UBL claim as plausible but vendor-sourced only, not DGII-confirmed.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'From pilot to mandate', '[["2018", "DGII announces a pilot for early 2019"], ["2019", "Voluntary pilot runs (10 companies enrolled, 7 completed certification)"], ["Jan 2020", "Norma General 01-2020 formalizes a voluntary authorization regime"], ["May 2023", "Ley 32-23 makes e-CF mandatory on a phased timeline"], ["Oct 2024", "Decreto 587-24 implements Ley 32-23''s operational rules (exact day disputed across sources -- see below)"]]', 'Three independent secondary sources give three different dates for Decreto 587-24 (10, 14, and 15 October 2024); this page cites October 2024 without a specific day pending direct confirmation from DGII''s own PDF, which could not be machine-read in this research round.', NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Rollout by DGII taxpayer category', '[["Grandes Contribuyentes Nacionales", "Mandatory from 15 May 2024 -- exclusive e-CF (paper retired) from 1 Jan 2026 per Aviso 25-25"], ["Grandes Contribuyentes Locales y Medianos", "Mandatory from 15 Nov 2025 (extended 6 months from the original 15 May 2025 deadline by Aviso 12-25)"], ["Pequeños, Micros y No Clasificados", "Mandatory from 15 Nov 2026 (extended 6 months from the original 15 May 2026 deadline by Aviso 06-26) -- the current final wave"], ["Government/state entities", "Follow the same wave structure as their private-sector size-equivalent"]]', 'No revenue-threshold figures in Dominican pesos were found publicly defining these DGII taxpayer-size categories -- they reflect DGII''s own internal administrative classification, frozen as of Ley 32-23''s 16 May 2023 effective date.', NULL);

INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 1, 'pills' FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'The clearance flow', 'A compliant e-CF moves through this sequence:', 'Only an e-CF DGII has returned as aceptado (or aceptado condicional) supports the recipient''s commercial approval or tax deduction.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Issuer generates and digitally signs the e-CF XML');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Document submitted to DGII for validation');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'DGII validates structure and content, returning a TrackID');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 3, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'DGII returns one of four statuses: aceptado, aceptado condicional, rechazado, or en proceso');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 4, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Accepted e-CF delivered to the recipient, who may grant commercial approval');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚠️ Tax infractions (Ley 32-23, Art. 26-29)', NULL, NULL, 'Article 26 lists 16 tax infractions -- failing to issue an e-CF when obligated, issuing without DGII authorization, a missing or invalid digital certificate, using an unauthorized certificate provider, post-signature alteration, non-standard XML, failure to retain printed representations, and late transmission, among others. Infractions 1-15 are sanctioned per Código Tributario (Ley 11-92) Art. 257 -- fines of 5 to 30 minimum salaries, plus possible accessory sanctions (suspension of concessions/privileges, closure). Late-submission infractions are sanctioned separately under Código Tributario Art. 205(3). No fixed peso amounts are given in the law itself -- all figures are expressed as multiples of the minimum salary.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚖️ Criminal offenses (Ley 32-23, Art. 30-31)', NULL, NULL, 'Article 30 (fraudulent e-CF) carries 1 to 5 years'' imprisonment plus a fine of 2x to 4x the invoice value, and possible permanent business closure. Article 31 (hacking, unauthorized system access, or data alteration) carries 5 to 10 years'' imprisonment plus a fine of 100 to 400 minimum public-sector salaries. Both figures are sourced directly from DGII''s own hosted PDF of Ley 32-23.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔍 What we could not confirm', NULL, NULL, 'Three items are flagged from this research round rather than presented as settled fact: (1) Decreto 587-24''s exact calendar day -- three independent secondary sources disagree (10, 14, or 15 October 2024), and DGII''s own PDF could not be machine-read in this session; (2) the 2019 pilot''s exact statistics (10 companies enrolled, 7 completed, ~723,000 e-CF issued), traced only to a single Dominican newspaper rather than a DGII primary source; (3) whether e-CF''s XML schema is genuinely UBL-based, a claim sourced only from a compliance vendor (EDICOM), not DGII''s own technical documentation.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm your DGII taxpayer-size category and applicable deadline', 'Your Art. 37 compliance deadline depends entirely on whether DGII classifies you as Gran Contribuyente Nacional, Gran Contribuyente Local, Mediano, Pequeño, Micro, or No Clasificado -- check your classification directly with DGII if unsure.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Large National, Local, or Medium Taxpayers: confirm e-CF certification is already complete', 'These categories'' deadlines (15 May 2024 and 15 November 2025) have already passed -- if not yet certified, this is a live compliance gap, not a future planning item.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Small, Micro, and previously-Unclassified taxpayers: prepare ahead of 15 November 2026', 'Register for DGII''s free Facturador Gratuito tool (capped at 150 invoices/month, DGII-adjustable) or select a certified paid solution well before the deadline -- DGII reports rapid adoption growth in this segment already.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Large National Taxpayers: confirm no invoicing workflow still relies on paper vouchers', 'From 1 January 2026, this segment may issue e-CF exclusively -- paper Type B vouchers no longer apply, per Aviso 25-25.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Obtain a digital certificate from an INDOTEL-accredited provider', 'Digital signing of your e-CF requires a certificate from a provider accredited under Ley 126-02 -- confirm your provider''s accreditation status before relying on it.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Check DGII''s avisosInformativos index for further deadline extensions', 'Both later waves (Large Local & Medium, and Small/Micro/Unclassified) have already received 6-month extensions via DGII avisos -- confirm the current status of your wave''s deadline rather than assuming Ley 32-23''s original dates still apply.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://dgii.gov.do/cicloContribuyente/facturacion/comprobantesFiscalesElectronicosE-CF/Paginas/default.aspx', 0 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'DGII -- e-CF program landing page');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://fg.dgii.gov.do/ecf/PortalFG/login', 1 FROM countries WHERE code = 'DO';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Facturador Gratuito -- DGII''s free e-CF invoicing tool');
