-- Dominican Republic story: EN, covering DGII's July 2026
-- registered-filer growth update -- a real, dated, DGII-original news
-- item directly fetched and confirmed in this session, and a strong
-- signal of the final rollout wave's momentum ahead of its 15 November
-- 2026 deadline.

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-07-24-dominican-republic-filer-growth', '2026-07-24', '2026-07', 'DGII reported that registered e-CF electronic filers in the Dominican Republic more than tripled in six months, from 23,686 in January 2026 to 76,762 by July 2026, with cumulative e-CF issued nationwide passing 1.86 billion. The growth comes ahead of the final rollout wave''s 15 November 2026 deadline for Small, Micro & Unclassified Taxpayers.', '<h3>🇩🇴 Dominican Republic''s e-CF adoption more than triples in six months</h3>
<p>The Dominican Republic''s e-CF (Comprobante Fiscal Electrónico) mandate, established by Ley 32-23 in 2023, has been rolling out in phased waves by DGII taxpayer-size category: Large National Taxpayers since May 2024, Large Local & Medium Taxpayers since an extended November 2025, and Small, Micro & Unclassified Taxpayers -- the final wave -- due by an extended 15 November 2026.</p>
<p>DGII reported on 24 July 2026 that registered electronic filers grew from 23,686 in January 2026 to 76,762 by July 2026 -- more than tripling in six months, according to DGII director Pedro Urrutia. Cumulative e-CF issued nationwide passed 1.86 billion by 1 July 2026, up from the 1 billion milestone DGII had reported less than a year earlier, in August 2025.</p>
<p>DGII is reportedly drafting a rule to eliminate the 30% ITBIS withholding for certified electronic filers, a further incentive aimed at accelerating adoption among small and micro taxpayers ahead of the final deadline. Since 1 January 2026, Large National Taxpayers have also been required to issue e-CF exclusively, with paper vouchers retired for that segment under DGII''s Aviso 25-25.</p>', 'https://acento.com.do/economia/mas-de-76000-contribuyentes-ya-emiten-facturas-electronicas-informa-impuestos-internos-9725216.html', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-07-24-dominican-republic-filer-growth', id FROM countries WHERE code = 'DO';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-07-24-dominican-republic-filer-growth', 'en', 'Dominican Republic''s e-CF adoption more than triples in six months', 'DGII reported that registered e-CF electronic filers in the Dominican Republic more than tripled in six months, from 23,686 in January 2026 to 76,762 by July 2026, with cumulative e-CF issued nationwide passing 1.86 billion. The growth comes ahead of the final rollout wave''s 15 November 2026 deadline for Small, Micro & Unclassified Taxpayers.', '<h3>🇩🇴 Dominican Republic''s e-CF adoption more than triples in six months</h3>
<p>The Dominican Republic''s e-CF (Comprobante Fiscal Electrónico) mandate, established by Ley 32-23 in 2023, has been rolling out in phased waves by DGII taxpayer-size category: Large National Taxpayers since May 2024, Large Local & Medium Taxpayers since an extended November 2025, and Small, Micro & Unclassified Taxpayers -- the final wave -- due by an extended 15 November 2026.</p>
<p>DGII reported on 24 July 2026 that registered electronic filers grew from 23,686 in January 2026 to 76,762 by July 2026 -- more than tripling in six months, according to DGII director Pedro Urrutia. Cumulative e-CF issued nationwide passed 1.86 billion by 1 July 2026, up from the 1 billion milestone DGII had reported less than a year earlier, in August 2025.</p>
<p>DGII is reportedly drafting a rule to eliminate the 30% ITBIS withholding for certified electronic filers, a further incentive aimed at accelerating adoption among small and micro taxpayers ahead of the final deadline. Since 1 January 2026, Large National Taxpayers have also been required to issue e-CF exclusively, with paper vouchers retired for that segment under DGII''s Aviso 25-25.</p>');
