-- ================================================================
-- Nigeria (NG) deep-dive content, EN. ES/DE/FR ride in a separate
-- translation migration (458), JOIN-lookup pattern. See 454's
-- header for the full sourcing notes, the resolved date-conflict
-- sequence, and exclusions (single-source items are confined to
-- the "What we could not confirm" card below).
-- ================================================================

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-07' FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en',
  'Phased pre-clearance CTC via the Merchant Buyer Solution (FIRSMBS): large taxpayers live since August 2025, medium from July 2026, smaller businesses from July 2027; B2C covered by 24-hour e-reporting; Peppol-based, under the first African tax authority on OpenPeppol''s authority list',
  'This deep-dive page reflects Nigeria''s e-invoicing regime as documented in FIRS/NRS public notices (reported via Nigerian press and professional-services alerts), the Nigeria Tax Administration Act 2025, and OpenPeppol''s authority listing, as of early August 2026, and is provided for general awareness, not legal or tax advice. The official portals (einvoice.firs.gov.ng, mbs.gov.ng) could not be machine-read during this research round, so operational details are sourced from reputable secondary coverage -- confirm current requirements directly with the Nigeria Revenue Service or a Nigerian tax adviser before relying on this page for compliance decisions.',
  'Nigeria moved fast: the Merchant Buyer Solution was announced in late 2024 (November, per Deloitte), unveiled in April 2025, and live for large taxpayers by 1 August 2025 -- with the compliance deadline extended once (to 1 November 2025), penalties becoming statutory on 1 January 2026 under the Nigeria Tax Administration Act, and a hard final large-taxpayer deadline of 31 July 2026. Medium taxpayers followed from 1 July 2026, and businesses below NGN 1 billion turnover join from 1 July 2027.',
  'Nigeria''s e-invoice schema follows UBL / Peppol BIS Billing 3.0 conventions, submitted as XML or JSON through certified service providers. Each B2B/B2G invoice is validated by the platform BEFORE delivery to the buyer -- pre-clearance -- receiving a unique Invoice Reference Number (IRN) and a Cryptographic Stamp Identifier (CSID), with a QR code embedded for verification of printed or PDF renderings. B2C sales are instead reported to the platform within 24 hours of issuance.',
  'The rollout is staged by annual turnover: NGN 5 billion and above (large) live since 1 August 2025 with enforcement from August 2026; NGN 1-5 billion (medium) from 1 July 2026 with enforcement from early 2027; below NGN 1 billion (emerging/small) from 1 July 2027 with enforcement from early 2028. Micro businesses below NGN 50 million turnover -- under Nigeria''s VAT registration threshold -- are exempt. Coverage spans B2B, B2G and B2C (via 24-hour reporting) for VAT-taxable supplies, including cross-border transactions.',
  'Large and medium taxpayers should already be live; the practical path runs through a valid TIN (migrating to the new Tax ID is the most-reported onboarding pain point), portal registration, a certified system integrator or access-point provider, sandbox testing, then production IRN transmission. Smaller businesses have runway to July 2027 -- and 16+ certified providers plus a portal channel to lower the entry cost.',
  'The Nigeria Tax Administration Act 2025 put the penalties on a statutory footing from 1 January 2026: NGN 200,000 plus 100% of the tax due plus interest for processing taxable supplies outside the fiscalisation system, escalating daily fines for refusing platform access, and -- the buyer-side lever -- denial of the input-VAT credit on any invoice issued outside the MBS.',
  'Nigeria''s Merchant Buyer Solution (FIRSMBS) applies pre-clearance CTC to B2B and B2G invoices -- every invoice validated and stamped with an IRN before it reaches the buyer -- plus 24-hour e-reporting for B2C. Live for large taxpayers (>= NGN 5bn) since 1 August 2025 with a final deadline of 31 July 2026, for medium taxpayers (NGN 1-5bn) since 1 July 2026, and reaching businesses under NGN 1bn from 1 July 2027 (micro businesses under NGN 50m exempt). Nigeria became the first African country on OpenPeppol''s Peppol Authority list on 26 September 2025, and its tax authority was renamed from FIRS to the Nigeria Revenue Service (NRS) on 1 January 2026.',
  '🇳🇬'
FROM countries WHERE code = 'NG';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1 Aug 2025', 'MBS goes live -- MTN, Huawei and IHS transmit Nigeria''s first cleared e-invoices');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '26 Sep 2025', 'First African tax authority on OpenPeppol''s Peppol Authority list');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '31 Jul 2026', 'Hard final deadline for large taxpayers (>= NGN 5bn) -- enforcement from August');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1 Jul 2027', 'Businesses below NGN 1bn turnover join (micro < NGN 50m exempt)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '16', 'Service providers certified at launch (system integrators + access points, via NITDA)');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & clearance mechanics', '[["Schema", "FIRS e-invoice schema following UBL / Peppol BIS Billing 3.0 conventions; submitted as XML or JSON"], ["Clearance", "B2B/B2G invoices validated by the platform BEFORE delivery to the buyer (pre-clearance)"], ["Stamping", "Unique Invoice Reference Number (IRN) + Cryptographic Stamp Identifier (CSID) per cleared invoice; QR code for verifying printed/PDF renderings"], ["B2C", "Reported to the platform within 24 hours of issuance rather than pre-cleared"], ["Buyer duty", "Buyers are expected to verify inbound invoices carry valid IRNs"]]', 'A reported ~55 mandatory data fields and a PDF/A-3-with-embedded-XML option appear in one industry briefing only -- treat as plausible. EY describes the exchange layer as a Peppol four-corner model with tax-authority clearance on top.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Legal & institutional framework', '[["Platform", "Merchant Buyer Solution (FIRSMBS), announced late 2024, unveiled 29 Apr 2025"], ["Statutory basis", "FIRS Establishment Act powers pre-2026; Nigeria Tax Administration Act 2025 (ss. 23, 103, 144, 200) and Nigeria Tax Act 2025 (ss. 104, 158) from 1 Jan 2026"], ["Authority", "FIRS renamed the Nigeria Revenue Service (NRS) from 1 Jan 2026, under the four tax reform acts signed 26 Jun 2025"], ["Technical guideline", "NITDA National Regulatory Guideline for Electronic Invoicing, effective 1 Sep 2025"], ["Peppol governance", "NRS is the national Peppol Authority (listed 26 Sep 2025); Nigeria''s TIN registered under ISO/IEC 6523"]]', NULL, NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Who must comply, and when', '[["Large (>= NGN 5bn turnover)", "Live 1 Aug 2025; deadline extended to 1 Nov 2025; hard final deadline 31 Jul 2026, enforcement from August 2026"], ["Medium (NGN 1-5bn)", "Pilot Apr-Jun 2026; mandatory from 1 Jul 2026; penalty soft-landing until enforcement Jan-Mar 2027"], ["Emerging/small (< NGN 1bn)", "Mandatory from 1 Jul 2027; enforcement from Jan-Mar 2028"], ["Micro (< NGN 50m)", "Exempt -- below Nigeria''s VAT registration threshold"], ["Transaction coverage", "B2B, B2G (pre-clearance) and B2C (24-hour reporting), for VAT-taxable supplies including cross-border"]]', NULL, NULL);

INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 1, 'pills' FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'The clearance flow', 'A compliant Nigerian B2B/B2G invoice moves through this sequence:', 'An invoice issued outside the MBS carries real consequences on both sides: the issuer faces the NGN 200,000 + 100%-of-tax penalty, and the buyer loses the input-VAT credit.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Generate the invoice against the FIRS/NRS schema (UBL / Peppol BIS 3.0 conventions, XML or JSON)');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Submit via a certified system integrator or access-point provider (portal channel for small volumes)');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Platform validates pre-delivery and issues the IRN + cryptographic stamp (CSID) with QR code');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 3, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Cleared invoice delivers to the buyer, who verifies the IRN');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 4, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'B2C sales route differently: reported to the platform within 24 hours of issuance');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Statutory penalties (NTAA 2025, enforceable from 1 Jan 2026)', '[["Processing taxable supplies outside the fiscalisation system", "NGN 200,000 + 100% of the tax due + interest at the CBN Monetary Policy Rate"], ["Refusing technology-deployment access after statutory notice", "NGN 1,000,000 on the first day + NGN 10,000 per day thereafter"], ["Buyer-side consequence", "Input-VAT credit denied on invoices issued outside the MBS"]]', 'Professional-services sources state the interest reference slightly differently (CBN MPR vs MPR + 2% per EY) -- the base penalty amounts are consistently reported across Mondaq/WTS, EY and industry trackers.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Enforcement timeline', '[["Large taxpayers", "Compliance monitoring and enforcement actions from August 2026 (after the 31 Jul 2026 hard deadline)"], ["Medium taxpayers", "Soft-landing until the Jan-Mar 2027 enforcement window"], ["Emerging/small", "Enforcement from the Jan-Mar 2028 window"], ["Adoption so far", "~1,000 of ~5,000 targeted large taxpayers onboarded in the first two weeks (Aug 2025); \"over 1,000 companies\" compliant as of Q1 2026 (NRS chairman)"]]', NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔍 What we could not confirm', '[["72-hour buyer rejection window", "Reported by one tracker only -- treat as plausible"], ["B2C late-reporting penalty (NGN 50,000/day)", "Industry-reported; not seen in an official notice this round"], ["Archiving period", "Sources conflict: 5-6 years (10 for cross-border) with in-Nigeria data localization vs 6 years standard / 7 on request -- unresolved"], ["Expense-deduction denial for non-MBS invoices", "Single-source; the input-VAT denial is the confirmed buyer-side consequence"], ["Direct platform access", "One source says all production traffic must route via certified SI/APPs; others describe a free direct portal + API -- likely both true by volume tier, but unconfirmed"]]', 'Items here are excluded from the milestone timeline and summary above under this site''s sourcing standard -- listed so you know what to double-check rather than silently omitted.', NULL);

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Sort your Tax ID first', 'Confirm your TIN is valid and complete the migration to the new Tax ID where applicable -- this is the most commonly reported onboarding blocker under the 2026 tax-reform transition.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Register on the e-invoicing portal', 'Onboard at einvoice.firs.gov.ng (email verification required) and confirm which rollout wave your turnover places you in.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Choose a certified provider', 'Select from the NITDA-certified system integrators and access-point providers (16 at launch, including Interswitch, Remita and eTranzact) for production integration via their RESTful APIs -- or use the portal channel for low volumes.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Test in the sandbox, then go live', 'Complete sandbox validation against the NRS guidelines before production cutover -- go-live means live IRN transmission on every B2B/B2G invoice, not just completed registration.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Stand up B2C reporting and verification routines', 'Set up the 24-hour B2C reporting flow, and train AP staff to verify that inbound supplier invoices carry valid IRNs -- an invoice outside the MBS costs you the input-VAT credit.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 5 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Archive and monitor', 'Retain cleared invoices and their IRN/CSID records (retention-period sources conflict -- see the note above; 6 years is the conservative floor reported), and watch NRS notices: the phased schedule has already shifted once.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://einvoice.firs.gov.ng', 0 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'FIRS/NRS e-invoicing portal');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://mbs.gov.ng', 1 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Merchant Buyer Solution (MBS)');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.nrs.gov.ng', 2 FROM countries WHERE code = 'NG';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Nigeria Revenue Service');
