-- ================================================================
-- Launch stories for Bulgaria (#63) and Estonia (#64), EN only.
-- ES/DE/FR ride in the countries' respective translation
-- migrations (JOIN-lookup pattern, per Kenya/Nigeria's 457/458).
--
-- Bulgaria: SAF-T Phase 1 begins for large enterprises, 1 Jan 2026
-- (EY Bulgaria + vatcalc.com corroborate the first-submission date
-- of 14 Feb 2026). Estonia: the 1 Jul 2025 Accounting Act
-- amendment giving registered buyers the right to require
-- e-invoices from suppliers (fin.ee official press release).
-- ================================================================

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2026-01-01-bulgaria-saft-phase1-launch', '2026-01-01', '2026-01', 'From 1 January 2026, Bulgaria''s largest taxpayers -- those exceeding BGN 300 million in 2023 revenue, or BGN 3.5 million in tax and social-security payments -- must start filing a monthly Standard Audit File for Tax (SAF-T) to the National Revenue Agency, with the first monthly submission due 14 February 2026. Bulgaria still has no B2B e-invoicing mandate of any kind.', '<h3>🇧🇬 Bulgaria''s SAF-T era begins -- but this still isn''t an e-invoicing mandate</h3>
<p>From 1 January 2026, Bulgaria''s largest taxpayers entered the first phase of a five-year rollout of Standard Audit File for Tax (SAF-T) reporting: businesses with 2023 annual net revenue above BGN 300 million, or annual tax and social-security payments above BGN 3.5 million, must now submit a monthly digital export of their general ledger, accounts payable/receivable, and purchase/sales invoice data to the National Revenue Agency (NAP) -- with the first monthly filing due 14 February 2026, and an annual fixed-asset report due each June.</p>
<p>It is worth being precise about what this is not: SAF-T is a periodic bookkeeping-data reporting obligation under the amended Tax and Social Insurance Procedure Code, not an e-invoicing mandate. Bulgaria has no requirement to issue structured e-invoices between businesses, no clearance platform, and no continuous transaction reporting for B2B trade -- that remains entirely voluntary. The SAF-T threshold will fall in four further steps through 2030, eventually reaching every VAT-registered entity including micro-enterprises, but the underlying invoicing regime is unaffected throughout.</p>', 'https://www.vatcalc.com/bulgaria/bulgaria-saf-t-introduction/', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2026-01-01-bulgaria-saft-phase1-launch', id FROM countries WHERE code = 'BG';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2026-01-01-bulgaria-saft-phase1-launch', 'en', 'Bulgaria''s SAF-T era begins -- but this still isn''t an e-invoicing mandate', 'From 1 January 2026, Bulgaria''s largest taxpayers -- those exceeding BGN 300 million in 2023 revenue, or BGN 3.5 million in tax and social-security payments -- must start filing a monthly Standard Audit File for Tax (SAF-T) to the National Revenue Agency, with the first monthly submission due 14 February 2026. Bulgaria still has no B2B e-invoicing mandate of any kind.', '<h3>🇧🇬 Bulgaria''s SAF-T era begins -- but this still isn''t an e-invoicing mandate</h3>
<p>From 1 January 2026, Bulgaria''s largest taxpayers entered the first phase of a five-year rollout of Standard Audit File for Tax (SAF-T) reporting: businesses with 2023 annual net revenue above BGN 300 million, or annual tax and social-security payments above BGN 3.5 million, must now submit a monthly digital export of their general ledger, accounts payable/receivable, and purchase/sales invoice data to the National Revenue Agency (NAP) -- with the first monthly filing due 14 February 2026, and an annual fixed-asset report due each June.</p>
<p>It is worth being precise about what this is not: SAF-T is a periodic bookkeeping-data reporting obligation under the amended Tax and Social Insurance Procedure Code, not an e-invoicing mandate. Bulgaria has no requirement to issue structured e-invoices between businesses, no clearance platform, and no continuous transaction reporting for B2B trade -- that remains entirely voluntary. The SAF-T threshold will fall in four further steps through 2030, eventually reaching every VAT-registered entity including micro-enterprises, but the underlying invoicing regime is unaffected throughout.</p>');

INSERT OR IGNORE INTO stories (id, date, month, summary_en, html_en, source_url, published) VALUES ('2025-07-01-estonia-buyer-request-einvoicing', '2025-07-01', '2025-07', 'From 1 July 2025, an Estonian Accounting Act amendment gives any entity registered in the Business Register as an e-invoice recipient the right to require its suppliers to issue e-invoices -- a conditional "buyer chooses" model rather than a blanket B2B mandate. Around 15,000-18,000 entities registered at rollout, and Estonia''s Ministry of Finance has separately flagged a universal B2B mandate for around 2027.', '<h3>🇪🇪 Estonia''s "buyer chooses" e-invoicing right takes effect</h3>
<p>Estonia has taken a distinctive path on B2B e-invoicing. Rather than a blanket mandate, a 1 July 2025 Accounting Act amendment gives the buyer the power: any entity registered in Estonia''s Business Register as an e-invoice recipient can now require its suppliers to issue e-invoices, using the EN 16931 European standard (typically over Peppol BIS Billing 3.0) unless the two parties agree otherwise. Suppliers retain no discretion once a registered buyer asks -- but outside that specific case, e-invoicing remains entirely voluntary. Around 15,000-18,000 Estonian entities had registered as e-invoice recipients at rollout.</p>
<p>The reform builds on Estonia''s B2G e-invoicing mandate, in force since July 2019, and gives the country a working Peppol-based e-invoicing base ahead of two bigger changes on the horizon: Estonia''s own Ministry of Finance has flagged a universal B2B e-invoicing mandate via a VAT Act amendment, anticipated around 2027 but still in draft, and the EU''s ViDA reform sets a firm 1 July 2030 floor for cross-border B2B e-invoicing regardless of what Estonia decides domestically.</p>', 'https://www.fin.ee/uudised/e-arveldamine-muutub-paindlikumaks', 1);
INSERT OR IGNORE INTO story_countries (story_id, country_id) SELECT '2025-07-01-estonia-buyer-request-einvoicing', id FROM countries WHERE code = 'EE';
INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES ('2025-07-01-estonia-buyer-request-einvoicing', 'en', 'Estonia''s "buyer chooses" e-invoicing right takes effect', 'From 1 July 2025, an Estonian Accounting Act amendment gives any entity registered in the Business Register as an e-invoice recipient the right to require its suppliers to issue e-invoices -- a conditional "buyer chooses" model rather than a blanket B2B mandate. Around 15,000-18,000 entities registered at rollout, and Estonia''s Ministry of Finance has separately flagged a universal B2B mandate for around 2027.', '<h3>🇪🇪 Estonia''s "buyer chooses" e-invoicing right takes effect</h3>
<p>Estonia has taken a distinctive path on B2B e-invoicing. Rather than a blanket mandate, a 1 July 2025 Accounting Act amendment gives the buyer the power: any entity registered in Estonia''s Business Register as an e-invoice recipient can now require its suppliers to issue e-invoices, using the EN 16931 European standard (typically over Peppol BIS Billing 3.0) unless the two parties agree otherwise. Suppliers retain no discretion once a registered buyer asks -- but outside that specific case, e-invoicing remains entirely voluntary. Around 15,000-18,000 Estonian entities had registered as e-invoice recipients at rollout.</p>
<p>The reform builds on Estonia''s B2G e-invoicing mandate, in force since July 2019, and gives the country a working Peppol-based e-invoicing base ahead of two bigger changes on the horizon: Estonia''s own Ministry of Finance has flagged a universal B2B e-invoicing mandate via a VAT Act amendment, anticipated around 2027 but still in draft, and the EU''s ViDA reform sets a firm 1 July 2030 floor for cross-border B2B e-invoicing regardless of what Estonia decides domestically.</p>');
