-- ================================================================
-- Lithuania (LT) ES/DE/FR translations, completing 474 (milestones),
-- 476 (deep-dive content) and 478 (launch story) against their
-- English content. Written 10 Aug 2026. Separate migration file, so
-- every deep-dive translation row looks up its parent row via a JOIN
-- on stable identifying columns (country code / section / sort_order
-- / English title text), never via (SELECT MAX(id) ...) -- pattern
-- reference: 442 (Kazakhstan), 457 (Kenya), 472 (Estonia), 471
-- (Bulgaria). milestone_translations and story_translations have
-- natural string PKs (milestone_id / story_id), so those rows are
-- plain INSERT OR IGNORE statements keyed on the hardcoded id
-- strings from 474/478 -- no JOIN needed. INSERT OR IGNORE
-- throughout.
--
-- Lithuania has no lifecycle card and no separate deep_dive_penalty_
-- rows entries (see 476's header -- the two penalties_related cards
-- carry the penalty narrative instead), so those tables are not
-- touched here.
--
-- IMPORTANT -- the disputed "2028" B2B target hedge (see 474's
-- header for full sourcing/self-contradiction notes) is translated
-- in full, not summarized, everywhere it appears in EN: the
-- lt-b2b-2028-target milestone, the "2028?" stat, the "disputed
-- '2028' B2B target, explained" card, and the SABIS launch story.
-- Never presented as confirmed in any language.
--
-- Kept unchanged across languages: proper nouns and official names
-- (SABIS, i.SAF, i.SAF-T, VMI, Peppol, EN 16931, BIS Billing 3.0,
-- CII, FR0600, ViDA, Council Directive (EU) 2025/516, "E. sąskaita",
-- Seimas, Law on Public Procurement / Lietuvos Respublikos viešųjų
-- pirkimų įstatymas). Lithuania's content has almost no currency
-- figures (unlike Bulgaria's BGN amounts) -- mostly dates and the
-- "20-100%" VAT-underpayment percentage range, kept as-is. Dates
-- localized per language convention: "1 July 2017" -> "1 de julio de
-- 2017" (es) / "1. Juli 2017" (de) / "1er juillet 2017" (fr), per
-- 471's precedent. mandate_summary_icon is always '🇱🇹', untranslated
-- in every language.
-- ================================================================


-- ==================== es ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'es',
  'Sin mandato B2B confirmado — B2G en vigor desde 2017, reporte del libro mayor de IVA i.SAF desde 2016, un disputado objetivo "2028" para el B2B',
  'Esta página de análisis refleja el régimen de facturación electrónica de Lituania, tal como se confirma a través de la ficha país de facturación electrónica de la Comisión Europea para Lituania (recuperada de forma independiente dos veces en esta ronda de investigación), junto con la propia página de i.SAF de la VMI (la Inspección Estatal de Impuestos) y fuentes sectoriales (Sovos, VATupdate) para las fechas de transición de plataforma, con fecha de 10 de agosto de 2026, y se ofrece a título informativo general, no como asesoría legal o tributaria. En esta página se señala en todo momento una fecha "2028" de facturación electrónica B2B ampliamente difundida como no confirmada — véase la nota específica más abajo — en lugar de presentarse como un hecho consolidado. Confirme los requisitos vigentes directamente con la VMI (vmi.lt) o con un asesor fiscal lituano antes de basar en esta página sus decisiones de cumplimiento.',
  'Lituania transpuso la directiva de facturación electrónica B2G de la UE el 1 de julio de 2017, aplicándola de forma más amplia que el mínimo de la UE (toda la contratación pública, no solo los contratos por encima del umbral). Desde alrededor de octubre de 2016, las empresas registradas a efectos del IVA presentan por separado un reporte mensual del libro mayor de IVA (i.SAF) — una obligación de reporte, no un mandato de facturación. En 2024, la plataforma B2G se consolidó en SABIS. La única cuestión abierta es si realmente llegará en 2028 un mandato general de facturación electrónica B2B — la propia ficha de la Comisión Europea menciona esa fecha mientras que, en la misma página, también afirma que actualmente no existe ningún mandato B2B.',
  'Lituania admite facturas electrónicas estructuradas conformes con la norma EN 16931 para el B2G a través de SABIS, mediante Peppol BIS Billing 3.0 o CII. Para la obligación separada de reporte i.SAF, la VMI acepta presentaciones XML (formato FR0600) a través de su propio portal — se trata de un reporte de *datos* de la factura, no de un formato de intercambio de facturas, y no incide en la forma en que realmente se emite o envía una factura a un cliente empresarial.',
  'El alcance de la facturación electrónica B2G cubre a todos los proveedores de contratación pública, sin valor mínimo de contrato — un alcance genuinamente más amplio que el de la mayoría de los países europeos comparables, que limitan el mandato a los contratos por encima del umbral. El alcance del reporte i.SAF cubre a toda entidad registrada a efectos del IVA en Lituania, nacional o extranjera, sin ningún umbral de tamaño. La facturación electrónica B2B en sí no tiene hoy ningún alcance definido porque no existe ningún mandato — véase la nota específica sobre el disputado objetivo de 2028 más abajo para lo que podría cambiar eso.',
  'La mayoría de las empresas que comercian con organismos públicos lituanos probablemente ya cumplan con el requisito B2G de 2017 a través de SABIS. La tarea de cumplimiento vigente para cualquier empresa registrada a efectos del IVA en Lituania es la presentación mensual de i.SAF, no la facturación electrónica en sí.',
  'No se establecieron cifras de sanción específicas y confirmadas de forma independiente para el incumplimiento de i.SAF/SAF-T durante esta ronda de investigación — dos fuentes sectoriales dan bandas en euros distintas, y esta página no repite ninguna de ellas como un hecho consolidado hasta que pueda leerse directamente el texto vigente del Código de Infracciones Administrativas. Lo que sí está confirmado: Lituania tiene sanciones generales por infrapago de IVA (20-100% del IVA no pagado según la Ley del IVA y la Ley de Administración Tributaria) que se aplicarían a los errores tributarios subyacentes puestos de manifiesto por una discrepancia en i.SAF, con independencia de cualquier multa específica por la presentación.',
  'Lituania tiene un mandato de facturación electrónica B2G (en vigor desde el 1 de julio de 2017, EN 16931 a través de SABIS, que cubre toda la contratación pública con independencia de su valor) y una obligación mensual de reporte del libro mayor de IVA a nivel de factura (i.SAF, desde alrededor de octubre de 2016, sin umbral de tamaño) — pero confirma directamente, en su propia ficha país de la Comisión Europea, que "no existe ningún mandato entre empresas (B2B)" y "no existe ningún sistema de reporte en tiempo real". La misma ficha menciona por separado un objetivo de "1 de enero de 2028" para la facturación electrónica obligatoria, que esta página trata como no confirmado y no como un plazo real — ninguna ley lituana promulgada lo corrobora, y podría confundirse con el propio mandato real de 2028, legislado por separado, de la vecina Letonia. El suelo confirmado a escala de la UE sigue siendo el 1 de julio de 2030 (ViDA).',
  '🇱🇹'
FROM countries WHERE code = 'LT';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '1 de jul. de 2017', 'Facturación electrónica B2G obligatoria en toda la contratación pública' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '~Oct. 2016', 'Comienza el reporte mensual del libro mayor de IVA i.SAF (sin umbral de tamaño)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', 'Sin mandato', 'La facturación electrónica B2B sigue siendo voluntaria (confirmado por la propia ficha de la CE)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '¿2028?', 'Objetivo B2B disputado de la ficha de la CE — no confirmado, posiblemente confundido con Letonia' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '2024', 'SABIS sustituye a la antigua plataforma B2G "E. sąskaita"' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'Formato y plataforma B2G (SABIS)', '[["Formato", "Factura electrónica estructurada conforme con la norma EN 16931"], ["Plataforma", "SABIS (Sąskaitų administravimo bendroji informacinė sistema), que sustituyó al antiguo sistema \"E. sąskaita\" en 2024"], ["Transmisión", "Introducción manual en el portal, o Peppol BIS Billing 3.0 / CII"], ["Alcance", "Todos los contratos de contratación pública, por encima y por debajo de los umbrales de la UE"]]', 'El alcance B2G de Lituania es más amplio que el de la mayoría de los países comparables de la UE -- se aplica a todos los contratos de contratación pública, no solo a los que superan los umbrales de contratación de la UE.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'file_format' AND dct.title = 'B2G format & platform (SABIS)';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'Formato del reporte i.SAF (independiente de la facturación)', '[["Formulario", "FR0600 -- libro mayor estructurado de facturas de IVA"], ["Contenido", "Registro de ventas (todas las facturas emitidas) y registro de compras (facturas recibidas de contribuyentes de IVA lituanos, más las operaciones de inversión del sujeto pasivo)"], ["Frecuencia", "Mensual, con vencimiento el día 20 del mes siguiente"], ["Presentación en blanco", "Obligatoria incluso cuando no se haya emitido ninguna factura"]]', 'i.SAF es un reporte periódico sobre sus facturas, presentado a la VMI a posteriori -- no cambia el formato que debe utilizar para emitir realmente una factura a un cliente, y no es un sistema en tiempo real ni de clearance.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'file_format' AND dct.title = 'i.SAF reporting format (separate from invoicing)';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'Qué está cubierto hoy', '[["B2G", "Todos los proveedores de contratación pública, sin valor mínimo de contrato -- obligatorio desde el 1 de jul. de 2017"], ["i.SAF (reporte de IVA)", "Toda entidad registrada a efectos del IVA, nacional o extranjera, sin umbral de tamaño -- desde ~oct. de 2016"], ["La facturación B2B en sí", "Ningún mandato de ningún tipo -- enteramente voluntaria, por acuerdo mutuo"], ["B2C", "No está cubierto por ninguna norma de facturación electrónica ni de reporte"]]', NULL, NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'scope_transmission' AND dct.title = 'What''s covered today';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', 'El disputado objetivo "2028" para el B2B, explicado', '[["Dónde aparece", "La propia Ficha País de facturación electrónica de Lituania de 2025 de la Comisión Europea"], ["La contradicción", "La misma página de la ficha también afirma sin rodeos: \"No existe ningún mandato entre empresas (B2B)\""], ["Qué lo corrobora", "No se encontró en ningún sitio ninguna ley lituana promulgada, orden de la VMI o acto del Seimas que confirme un mandato para 2028"], ["Una explicación plausible", "La vecina Letonia tiene un mandato B2B real, legislado por separado, confirmado como pospuesto a exactamente el 1 de enero de 2028 (KPMG, junio de 2025) -- varias fuentes sectoriales que repiten \"Lituania 2028\" podrían estar haciéndose eco de esto, de la redacción ambigua de la ficha, o de ambas cosas"]]', 'Esta tarjeta existe específicamente para que un lector que encuentre la cifra "2028" en otro lugar entienda por qué esta página no la trata como confirmada.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'scope_transmission' AND dct.title = 'The disputed "2028" B2B target, explained';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', '⚖️ No existe ninguna sanción de facturación electrónica B2B — porque no existe ningún mandato B2B', NULL, NULL, 'No hay nada que sancionar en el plano de la facturación: Lituania nunca ha legislado un requisito de facturación electrónica B2B o de clearance, por lo que no existe ningún régimen de multas vinculado a la forma de emitir o intercambiar facturas con otra empresa.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'penalties_related' AND dct.title = '⚖️ No B2B e-invoicing fine exists — because no B2B mandate exists';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'es', '📋 Las cifras de sanción de i.SAF no están resueltas -- no se indican aquí', NULL, NULL, 'Dos fuentes sectoriales dan bandas en euros distintas para las presentaciones de i.SAF/SAF-T tardías o no realizadas, y ninguna se confirmó de forma independiente frente al texto vigente del Código de Infracciones Administrativas en esta ronda de investigación (los intentos de acceso directo a e-seimas.lrs.lt e infolex.lt fallaron). En lugar de presentar cualquiera de las dos cifras como consolidada, esta página confirma únicamente que se aplica una sanción general por infrapago de IVA del 20-100% del impuesto no pagado en virtud de la Ley del IVA y la Ley de Administración Tributaria, y que existen en principio sanciones administrativas por la no presentación de documentos tributarios en virtud de un artículo modificado del Código de Infracciones Administrativas.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'penalties_related' AND dct.title = '📋 i.SAF penalty figures are unresolved -- not stated here';

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Confirme que su facturación B2G ya funciona a través de SABIS', 'Si abastece a organismos públicos lituanos, verifique que sus facturas son facturas electrónicas estructuradas EN 16931 presentadas a través de SABIS -- la plataforma que sustituyó al antiguo sistema E. sąskaita en 2024.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Configure la presentación mensual de i.SAF si está registrado a efectos del IVA en Lituania', 'Confirme que su software contable puede generar un libro mayor de IVA de ventas/compras FR0600 conforme, con vencimiento el día 20 del mes siguiente -- no existe exención por tamaño, y se requiere una presentación en blanco incluso en un mes sin facturas.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'No confunda i.SAF con un mandato de facturación electrónica', 'i.SAF cambia qué datos contables reporta y cuándo -- no le exige cambiar la forma de emitir o intercambiar facturas con otras empresas, ya que hoy no existe ningún mandato de facturación electrónica B2B en Lituania.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Trate la cifra "2028" como un asunto a vigilar, no como un plazo', 'No construya planes de cumplimiento en torno a un mandato B2B lituano confirmado para el 1 de enero de 2028 -- no está confirmado. Vigile a la VMI y al Ministerio de Hacienda por si aparece una ley realmente promulgada antes de tratar cualquier fecha como real.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Prepárese de todos modos para el suelo de la UE confirmado para 2030', 'Ocurra lo que ocurra a nivel nacional, la facturación electrónica estructurada y el reporte digital pasan a ser obligatorios para el comercio B2B transfronterizo intracomunitario desde el 1 de julio de 2030 en virtud de ViDA -- esa fecha es derecho de la UE consolidado.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'es', 'SABIS -- plataforma nacional de facturación electrónica B2G' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'es', 'VMI (Inspección Estatal de Impuestos) -- explicación de i.SAF' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'es', 'EU Digital Building Blocks -- Ficha País de facturación electrónica de Lituania' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 2;

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2g-2017', 'es',
  'Facturación electrónica B2G obligatoria en toda la contratación pública',
  'Desde el 1 de julio de 2017, todos los proveedores de las entidades adjudicadoras lituanas deben presentar facturas electrónicas estructuradas para los contratos de contratación pública -- tanto por encima como por debajo de los umbrales de contratación de la UE, un alcance más amplio que el mínimo de la UE. Base legal: la Ley de Contratación Pública (Lietuvos Respublikos viešųjų pirkimų įstatymas), que transpone la Directiva UE 2014/55/UE. Formato: EN 16931, a través de Peppol BIS Billing 3.0 o CII.',
  '["Contexto histórico -- no se requiere ninguna acción para los proveedores existentes de organismos públicos lituanos", "Confirme que las facturas a las entidades adjudicadoras lituanas son facturas electrónicas estructuradas EN 16931, no en PDF ni en papel"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-isaf-2016', 'es',
  'Comienza el reporte de IVA a nivel de factura del libro mayor i.SAF',
  'Desde alrededor de octubre de 2016 (fecha corroborada por fuentes sectoriales, no fechada de forma independiente por la propia página de la VMI), toda entidad registrada a efectos del IVA en Lituania -- nacional o extranjera con un número de IVA de LT, sin umbral de tamaño -- debe presentar un reporte mensual de i.SAF: un libro mayor línea a línea de las facturas de IVA de ventas y compras, con vencimiento el día 20 del mes siguiente, con presentación en blanco obligatoria incluso cuando no se hayan emitido facturas. Se trata de una obligación de reporte periódica y a posteriori ante la Inspección Estatal de Impuestos (VMI) -- comparable en concepto al SII español o al SAF-T búlgaro -- no un sistema de clearance en tiempo real ni un mandato de facturación electrónica. La propia ficha país de la Comisión Europea lo confirma directamente: "Actualmente, no existe ningún sistema de reporte en tiempo real en Lituania".', '["Confirme que su sistema contable produce una exportación mensual de i.SAF conforme si está registrado a efectos del IVA en Lituania", "No confunda esto con un requisito de facturación electrónica -- regula lo que reporta sobre las facturas, no cómo las emite o intercambia"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-sabis-2024', 'es',
  'SABIS sustituye a la antigua plataforma "E. sąskaita" como único canal B2G',
  'A mediados o finales de 2024 (las fuentes discrepan sobre el día exacto del cambio -- reportado indistintamente como el 1 de julio, "septiembre", o "1 de septiembre tras una transición de dos meses"), SABIS (Sąskaitų administravimo bendroji informacinė sistema) se convirtió en la única plataforma nacional de facturación electrónica B2G de Lituania, sustituyendo al antiguo sistema "E. sąskaita"/eSaskaita lanzado en 2015. Los proveedores pueden introducir las facturas manualmente a través del portal web o transmitir facturas electrónicas estructuradas EN 16931 a través de Peppol.', '["Si aún hace referencia al antiguo sistema E. sąskaita/eSaskaita en la documentación para proveedores, actualícela para indicar SABIS"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-sabis-oral-contracts-2025', 'es',
  'El alcance de SABIS se extiende a las facturas de contratos de contratación pública celebrados oralmente',
  'Desde el 1 de enero de 2025 (de fuente sectorial; no se pudo recuperar en esta ronda de investigación ninguna página oficial independiente de la VMI/Oficina de Contratación Pública que confirme esta fecha), las facturas derivadas de contratos de contratación pública celebrados verbalmente -- anteriormente solo obligadas a pasar por SABIS por encima de un umbral de EUR 1.000 (sin IVA) -- también deben presentarse a través de la plataforma con independencia de su valor.', '[]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2b-voluntary', 'es',
  'La facturación electrónica B2B sigue siendo voluntaria -- sin mandato de CTC ni de clearance',
  'Lituania no tiene ningún mandato de facturación electrónica entre empresas, ningún sistema de clearance de facturas ni ningún requisito de reporte de transacciones en tiempo real -- confirmado directamente por la propia ficha país de la Comisión Europea ("No existe ningún mandato entre empresas (B2B)" / "Actualmente, no existe ningún sistema de reporte en tiempo real en Lituania"). La facturación electrónica B2B estructurada es opcional, por acuerdo mutuo entre las partes comerciales. La obligación de i.SAF existente (arriba) es un requisito de reporte de IVA separado y a posteriori, no un mandato de facturación.', '["No se requiere ninguna acción de facturación electrónica B2B nacional por el momento", "No confunda la obligación de reporte i.SAF con un mandato de facturación electrónica -- son legal y operativamente distintas"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2b-2028-target', 'es',
  'Un objetivo general de mandato B2B para "el 1 de enero de 2028" se menciona en la propia ficha de la CE -- pero esto NO es una ley lituana confirmada',
  'La Ficha País de facturación electrónica de Lituania de 2025 de la Comisión Europea menciona "el 1 de enero de 2028" como objetivo para la facturación electrónica obligatoria -- pero la misma página afirma por separado que "No existe ningún mandato entre empresas (B2B)", y no se encontró en ningún sitio ninguna ley lituana promulgada, orden de la VMI o acto del Seimas que corrobore un mandato real para 2028. La vecina Letonia tiene un mandato B2B real, legislado por separado, que fue pospuesto a exactamente el 1 de enero de 2028 (KPMG, junio de 2025) -- lo que plantea la posibilidad genuina de que algunas o todas las afirmaciones sobre "Lituania 2028" que circulan en la cobertura sectorial se remonten a esta ambigüedad o a una confusión con la fecha confirmada de Letonia, más que a un compromiso lituano independiente. Trate esta fecha como, como mucho, orientativa, no confirmada -- se recoge aquí únicamente porque aparece en una fuente oficial de la UE, con esta advertencia adjunta.', '["No trate el 1 de enero de 2028 como un plazo de cumplimiento confirmado para Lituania -- vigile la aparición de una ley realmente promulgada antes de planificar en torno a ella", "Esté atento a un anuncio del Ministerio de Hacienda o del Seimas lituanos que resuelva esta ambigüedad en un sentido u otro"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-vida-2030', 'es',
  'La facturación electrónica B2B transfronteriza y el reporte digital de ViDA pasan a ser obligatorios (derecho de la UE confirmado)',
  'Desde el 1 de julio de 2030, en virtud de la Directiva (UE) 2025/516 del Consejo, la facturación electrónica estructurada y el reporte digital pasan a ser obligatorios para todas las entregas B2B intracomunitarias -- un suelo firme de derecho de la UE que se aplica a Lituania con independencia de que el objetivo nacional no confirmado para 2028 mencionado arriba llegue alguna vez a materializarse en una ley real.', '["Prepárese para la facturación electrónica estructurada obligatoria en todo el comercio B2B intracomunitario desde mediados de 2030, con independencia de que llegue antes un mandato nacional"]'
);

INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES (
  '2024-09-01-lithuania-sabis-platform', 'es',
  'Lituania consolida su facturación electrónica B2G en SABIS -- pero el B2B sigue sin mandato',
  'Lituania consolidó su facturación electrónica B2G en una nueva plataforma única, SABIS, en sustitución del antiguo sistema "E. sąskaita". Lituania sigue sin tener ningún mandato de facturación electrónica B2B -- a pesar de una cifra de "1 de enero de 2028" que circula en parte de la cobertura, que se remonta a una ficha de la Comisión Europea internamente contradictoria y que podría confundirse con el propio mandato de 2028 de la vecina Letonia, legislado por separado.',
  '<h3>🇱🇹 Lituania consolida su facturación electrónica B2G en SABIS -- pero el B2B sigue sin mandato</h3>
<p>En 2024, Lituania retiró su antiguo sistema de facturación electrónica B2G "E. sąskaita" en favor de SABIS (Sąskaitų administravimo bendroji informacinė sistema), el único canal para facturas electrónicas estructuradas dirigidas a las entidades adjudicadoras públicas lituanas -- que admite la introducción manual en el portal o la transmisión mediante Peppol BIS Billing 3.0/CII. La facturación electrónica en la contratación pública es obligatoria en Lituania desde el 1 de julio de 2017 y, por separado, las empresas registradas a efectos del IVA presentan desde alrededor de octubre de 2016 un libro mayor mensual de IVA a nivel de factura (i.SAF) ante la autoridad tributaria.</p>
<p>Lo que Lituania no tiene es un mandato de facturación electrónica entre empresas. La propia ficha país de la Comisión Europea lo dice directamente -- "no existe ningún mandato entre empresas (B2B)" -- mientras que, de forma confusa, la misma página menciona por separado "el 1 de enero de 2028" como fecha objetivo para la facturación electrónica obligatoria. Ninguna ley lituana promulgada corrobora esa fecha, y la vecina Letonia tiene un mandato B2B real propio que fue pospuesto a exactamente el 1 de enero de 2028 -- lo que plantea la posibilidad real de que parte de la cobertura sobre "Lituania 2028" se esté haciendo eco de la fecha confirmada de Letonia en lugar de informar de un compromiso lituano independiente. Hasta que aparezca una ley real, el único plazo transfronterizo consolidado es el suelo de ViDA de la UE del 1 de julio de 2030.</p>'
);


-- ==================== de ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'de',
  'Kein bestätigtes B2B-Mandat — B2G seit 2017 in Kraft, i.SAF-Meldung des Mehrwertsteuer-Hauptbuchs seit 2016, ein umstrittenes „2028“-B2B-Ziel',
  'Diese Analyseseite spiegelt Litauens E-Invoicing-Regime wider, wie es über das eInvoicing-Länderfactsheet der Europäischen Kommission für Litauen (in dieser Rechercherunde zweimal unabhängig neu abgerufen) sowie die eigene i.SAF-Seite der VMI (der Staatlichen Steuerinspektion) und Branchenquellen (Sovos, VATupdate) für die Daten des Plattformwechsels bestätigt wurde, mit Stand 10. August 2026, und dient allgemeinen Informationszwecken, nicht als Rechts- oder Steuerberatung. Ein vielfach kursierendes „2028“-Datum für die B2B-E-Rechnungsstellung wird auf dieser Seite durchgehend als unbestätigt gekennzeichnet — siehe die eigene Anmerkung weiter unten — statt als feststehende Tatsache dargestellt. Bestätigen Sie aktuelle Anforderungen direkt bei der VMI (vmi.lt) oder bei einem litauischen Steuerberater, bevor Sie sich bei Compliance-Entscheidungen auf diese Seite verlassen.',
  'Litauen setzte die B2G-E-Invoicing-Richtlinie der EU am 1. Juli 2017 um und wendet sie umfassender an als das EU-Minimum (die gesamte öffentliche Auftragsvergabe, nicht nur Verträge oberhalb des Schwellenwerts). Seit etwa Oktober 2016 reichen mehrwertsteuerlich registrierte Unternehmen separat eine monatliche Meldung des Mehrwertsteuer-Hauptbuchs (i.SAF) ein — eine Meldepflicht, kein E-Invoicing-Mandat. 2024 wurde die B2G-Plattform in SABIS zusammengeführt. Die einzige offene Frage ist, ob 2028 tatsächlich ein allgemeines B2B-E-Invoicing-Mandat kommt — das eigene Factsheet der Europäischen Kommission nennt dieses Datum, während es auf derselben Seite auch erklärt, dass derzeit kein B2B-Mandat besteht.',
  'Litauen unterstützt EN-16931-konforme strukturierte E-Rechnungen für B2G über SABIS, per Peppol BIS Billing 3.0 oder CII. Für die separate i.SAF-Meldepflicht akzeptiert die VMI XML-Einreichungen (Format FR0600) über ihr eigenes Portal — dies ist eine *Daten*meldung zur Rechnung, kein Rechnungsaustauschformat, und hat keinen Einfluss darauf, wie eine Rechnung tatsächlich an einen Geschäftskunden ausgestellt oder versendet wird.',
  'Der Anwendungsbereich der B2G-E-Rechnungsstellung erfasst alle Lieferanten der öffentlichen Auftragsvergabe, ohne Mindestvertragswert — ein tatsächlich breiterer Anwendungsbereich als bei den meisten vergleichbaren EU-Ländern, die das Mandat auf Verträge oberhalb des Schwellenwerts beschränken. Der Anwendungsbereich der i.SAF-Meldung erfasst jede mehrwertsteuerlich registrierte Einheit in Litauen, im In- oder Ausland, ohne jeden Größenschwellenwert. Die B2B-E-Rechnungsstellung selbst hat heute keinen definierten Anwendungsbereich, da kein Mandat besteht — siehe die eigene Anmerkung zum umstrittenen 2028-Ziel weiter unten dazu, was sich daran ändern könnte.',
  'Die meisten Unternehmen, die mit litauischen öffentlichen Stellen Handel treiben, erfüllen die B2G-Pflicht von 2017 über SABIS wahrscheinlich bereits. Die aktuelle Compliance-Aufgabe für jedes mehrwertsteuerlich registrierte litauische Unternehmen ist die monatliche i.SAF-Meldung, nicht die E-Rechnungsstellung selbst.',
  'In dieser Rechercherunde wurden keine spezifischen, unabhängig bestätigten Bußgeldbeträge für die Nichteinhaltung von i.SAF/SAF-T ermittelt — zwei Branchenquellen nennen unterschiedliche Euro-Spannen, und diese Seite gibt keine davon als feststehende Tatsache wieder, bis der aktuelle Text des Gesetzbuchs über Verwaltungsverstöße direkt eingesehen werden kann. Bestätigt ist: Litauen hat allgemeine Sanktionen für Mehrwertsteuer-Unterzahlung (20-100 % der nicht gezahlten Mehrwertsteuer nach dem Mehrwertsteuergesetz und dem Steuerverwaltungsgesetz), die auf zugrunde liegende Steuerfehler anwendbar wären, die durch eine i.SAF-Abweichung aufgedeckt werden, unabhängig von einer meldungsspezifischen Geldbuße.',
  'Litauen hat ein bestehendes B2G-E-Invoicing-Mandat (seit 1. Juli 2017 in Kraft, EN 16931 über SABIS, das die gesamte öffentliche Auftragsvergabe unabhängig vom Wert erfasst) und eine monatliche Meldepflicht für das Mehrwertsteuer-Hauptbuch auf Rechnungsebene (i.SAF, seit etwa Oktober 2016, ohne Größenschwellenwert) — bestätigt aber direkt im eigenen EU-Kommissions-Factsheet, dass „kein Mandat zwischen Unternehmen (B2B) besteht“ und „kein Echtzeit-Meldesystem“ existiert. Dasselbe Factsheet nennt separat ein Ziel „1. Januar 2028“ für die verpflichtende E-Rechnungsstellung, das diese Seite als unbestätigt behandelt und nicht als reale Frist — kein erlassenes litauisches Gesetz bestätigt dies, und es könnte mit dem eigenen, real bestehenden, separat gesetzlich verankerten 2028-Mandat des Nachbarlands Lettland verwechselt werden. Die bestätigte EU-weite Untergrenze bleibt der 1. Juli 2030 (ViDA).',
  '🇱🇹'
FROM countries WHERE code = 'LT';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '1. Juli 2017', 'B2G-E-Rechnungsstellung für die gesamte öffentliche Auftragsvergabe verpflichtend' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '~Okt. 2016', 'Monatliche i.SAF-Meldung des Mehrwertsteuer-Hauptbuchs beginnt (kein Größenschwellenwert)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', 'Kein Mandat', 'B2B-E-Rechnungsstellung bleibt freiwillig (durch das eigene Factsheet der EK bestätigt)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '2028?', 'Umstrittenes B2B-Ziel des EK-Factsheets — unbestätigt, möglicherweise mit Lettland verwechselt' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '2024', 'SABIS ersetzt die veraltete B2G-Plattform „E. sąskaita“' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'B2G-Format & -Plattform (SABIS)', '[["Format", "EN-16931-konforme strukturierte E-Rechnung"], ["Plattform", "SABIS (Sąskaitų administravimo bendroji informacinė sistema), das 2024 das alte „E. sąskaita“-System ablöste"], ["Übermittlung", "Manuelle Eingabe im Portal, oder Peppol BIS Billing 3.0 / CII"], ["Anwendungsbereich", "Alle Verträge der öffentlichen Auftragsvergabe, oberhalb und unterhalb der EU-Schwellenwerte"]]', 'Litauens B2G-Anwendungsbereich ist breiter als bei den meisten vergleichbaren EU-Ländern -- er gilt für jeden Vertrag der öffentlichen Auftragsvergabe, nicht nur für solche oberhalb der EU-Vergabeschwellenwerte.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'file_format' AND dct.title = 'B2G format & platform (SABIS)';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'i.SAF-Meldeformat (getrennt von der Rechnungsstellung)', '[["Formular", "FR0600 -- strukturiertes Mehrwertsteuer-Rechnungshauptbuch"], ["Inhalt", "Verkaufsregister (alle ausgestellten Rechnungen) und Einkaufsregister (von litauischen Mehrwertsteuerzahlern erhaltene Rechnungen sowie Reverse-Charge-Umsätze)"], ["Häufigkeit", "Monatlich, fällig zum 20. des Folgemonats"], ["Nullmeldung", "Erforderlich, auch wenn keine Rechnungen ausgestellt wurden"]]', 'i.SAF ist eine periodische Meldung über Ihre Rechnungen, die im Nachhinein an die VMI übermittelt wird -- es ändert nicht das Format, das Sie zur tatsächlichen Ausstellung einer Rechnung an einen Kunden verwenden müssen, und ist kein Echtzeit- oder Clearance-System.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'file_format' AND dct.title = 'i.SAF reporting format (separate from invoicing)';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'Was heute abgedeckt ist', '[["B2G", "Alle Lieferanten der öffentlichen Auftragsvergabe, kein Mindestvertragswert -- verpflichtend seit 1. Juli 2017"], ["i.SAF (Mehrwertsteuermeldung)", "Jede mehrwertsteuerlich registrierte Einheit, im In- oder Ausland, kein Größenschwellenwert -- seit ~Okt. 2016"], ["Die B2B-Rechnungsstellung selbst", "Kein Mandat jeglicher Art -- vollständig freiwillig, nach gegenseitiger Vereinbarung"], ["B2C", "Von keiner E-Invoicing- oder Meldevorschrift erfasst"]]', NULL, NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'scope_transmission' AND dct.title = 'What''s covered today';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', 'Das umstrittene „2028“-B2B-Ziel, erklärt', '[["Wo es auftaucht", "Im eigenen 2025 Lithuania eInvoicing Country Sheet der Europäischen Kommission"], ["Der Widerspruch", "Dieselbe Factsheet-Seite erklärt auch unumwunden: „Es besteht kein Mandat zwischen Unternehmen (B2B)“"], ["Was es bestätigt", "Es wurde nirgends ein erlassenes litauisches Gesetz, eine VMI-Anordnung oder ein Seimas-Akt gefunden, der ein 2028-Mandat bestätigt"], ["Eine plausible Erklärung", "Das Nachbarland Lettland hat ein reales, separat erlassenes B2B-Mandat, das bestätigt auf genau den 1. Januar 2028 verschoben wurde (KPMG, Juni 2025) -- mehrere Branchenquellen, die „Litauen 2028“ wiederholen, geben möglicherweise dies, die mehrdeutige Formulierung des Factsheets, oder beides wieder"]]', 'Diese Karte existiert eigens dafür, dass ein Leser, der die Zahl „2028“ anderswo antrifft, versteht, warum diese Seite sie nicht als bestätigt behandelt.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'scope_transmission' AND dct.title = 'The disputed "2028" B2B target, explained';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', '⚖️ Es gibt kein Bußgeld für B2B-E-Invoicing — weil es kein B2B-Mandat gibt', NULL, NULL, 'Auf der Rechnungsstellungsseite gibt es nichts zu sanktionieren: Litauen hat nie eine B2B-E-Invoicing- oder Clearance-Anforderung gesetzlich verankert, sodass kein Bußgeldkatalog daran anknüpft, wie Sie Rechnungen mit einem anderen Unternehmen ausstellen oder austauschen.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'penalties_related' AND dct.title = '⚖️ No B2B e-invoicing fine exists — because no B2B mandate exists';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'de', '📋 i.SAF-Bußgeldbeträge sind ungeklärt -- hier nicht angegeben', NULL, NULL, 'Zwei Branchenquellen nennen unterschiedliche Euro-Spannen für verspätete oder unterlassene i.SAF/SAF-T-Meldungen, und keine wurde in dieser Rechercherunde unabhängig gegen den aktuellen Text des Gesetzbuchs über Verwaltungsverstöße bestätigt (direkte Abrufe von e-seimas.lrs.lt und infolex.lt schlugen fehl). Anstatt eine der beiden Zahlen als feststehend darzustellen, bestätigt diese Seite lediglich, dass nach dem Mehrwertsteuergesetz und dem Steuerverwaltungsgesetz eine allgemeine Sanktion für Mehrwertsteuer-Unterzahlung von 20-100 % der nicht gezahlten Steuer gilt und dass verwaltungsrechtliche Sanktionen für die Nichteinreichung von Steuerdokumenten grundsätzlich nach einem geänderten Artikel des Gesetzbuchs über Verwaltungsverstöße bestehen.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'penalties_related' AND dct.title = '📋 i.SAF penalty figures are unresolved -- not stated here';

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Bestätigen Sie, dass Ihre B2G-Rechnungsstellung bereits über SABIS läuft', 'Wenn Sie litauische öffentliche Stellen beliefern, prüfen Sie, ob Ihre Rechnungen als strukturierte EN-16931-E-Rechnungen über SABIS eingereicht werden -- die Plattform, die 2024 das alte E.-sąskaita-System ablöste.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Richten Sie die monatliche i.SAF-Meldung ein, wenn Sie in Litauen mehrwertsteuerlich registriert sind', 'Stellen Sie sicher, dass Ihre Buchhaltungssoftware ein konformes FR0600-Verkaufs-/Einkaufs-Mehrwertsteuer-Hauptbuch erzeugen kann, fällig zum 20. des Folgemonats -- es gibt keine Größenbefreiung, und eine Nullmeldung ist auch in einem Monat ohne Rechnungen erforderlich.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Verwechseln Sie i.SAF nicht mit einem E-Invoicing-Mandat', 'i.SAF ändert, welche Buchhaltungsdaten Sie wann melden -- es verlangt nicht, dass Sie ändern, wie Sie Rechnungen mit anderen Unternehmen ausstellen oder austauschen, da es ein solches B2B-E-Invoicing-Mandat in Litauen heute nicht gibt.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Behandeln Sie die Zahl „2028“ als Beobachtungspunkt, nicht als Frist', 'Bauen Sie keine Compliance-Pläne rund um ein bestätigtes litauisches B2B-Mandat zum 1. Januar 2028 auf -- es ist nicht bestätigt. Beobachten Sie VMI und das Finanzministerium auf ein tatsächlich erlassenes Gesetz, bevor Sie ein Datum als real behandeln.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Bereiten Sie sich unabhängig davon auf die bestätigte EU-Untergrenze 2030 vor', 'Unabhängig von der innerstaatlichen Entwicklung werden strukturierte E-Rechnungsstellung und digitale Meldung für den grenzüberschreitenden innergemeinschaftlichen B2B-Handel ab dem 1. Juli 2030 nach ViDA verpflichtend -- dieses Datum ist geltendes EU-Recht.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'de', 'SABIS -- nationale B2G-E-Invoicing-Plattform' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'de', 'VMI (Staatliche Steuerinspektion) -- i.SAF-Erklärung' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'de', 'EU Digital Building Blocks -- Länderdatenblatt E-Invoicing Litauen' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 2;

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2g-2017', 'de',
  'B2G-E-Rechnungsstellung für die gesamte öffentliche Auftragsvergabe verpflichtend',
  'Seit dem 1. Juli 2017 müssen alle Lieferanten litauischer Vergabestellen strukturierte E-Rechnungen für Verträge der öffentlichen Auftragsvergabe einreichen -- sowohl oberhalb als auch unterhalb der EU-Vergabeschwellenwerte, ein breiterer Anwendungsbereich als das EU-Minimum. Rechtsgrundlage: das Vergabegesetz (Lietuvos Respublikos viešųjų pirkimų įstatymas), das die EU-Richtlinie 2014/55/EU umsetzt. Format: EN 16931, über Peppol BIS Billing 3.0 oder CII.',
  '["Historischer Kontext -- für bestehende Lieferanten litauischer öffentlicher Stellen ist keine Maßnahme erforderlich", "Bestätigen Sie, dass Rechnungen an litauische Vergabestellen als strukturierte EN-16931-E-Rechnungen eingereicht werden, nicht als PDF oder Papier"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-isaf-2016', 'de',
  'i.SAF-Meldung des Mehrwertsteuer-Hauptbuchs auf Rechnungsebene beginnt',
  'Seit etwa Oktober 2016 (Datum durch Branchenquellen bestätigt, nicht durch die eigene Seite der VMI unabhängig datiert) muss jede mehrwertsteuerlich registrierte Einheit in Litauen -- im In- oder Ausland mit einer litauischen Mehrwertsteuernummer, ohne Größenschwellenwert -- eine monatliche i.SAF-Meldung einreichen: ein Zeile-für-Zeile-Hauptbuch der Verkaufs- und Einkaufs-Mehrwertsteuerrechnungen, fällig zum 20. des Folgemonats, mit einer erforderlichen Nullmeldung auch dann, wenn keine Rechnungen ausgestellt wurden. Dies ist eine periodische, nachträgliche Meldepflicht gegenüber der Staatlichen Steuerinspektion (VMI) -- konzeptionell vergleichbar mit dem spanischen SII oder dem bulgarischen SAF-T -- kein Echtzeit-Clearance-System und kein E-Invoicing-Mandat. Das eigene Länder-Factsheet der EU-Kommission bestätigt direkt: „Derzeit gibt es in Litauen kein Echtzeit-Meldesystem.“', '["Bestätigen Sie, dass Ihr Buchhaltungssystem einen konformen monatlichen i.SAF-Export erzeugt, wenn Sie in Litauen mehrwertsteuerlich registriert sind", "Verwechseln Sie dies nicht mit einer E-Invoicing-Pflicht -- es regelt, was Sie über Rechnungen melden, nicht wie Sie sie ausstellen oder austauschen"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-sabis-2024', 'de',
  'SABIS ersetzt die veraltete Plattform „E. sąskaita“ als alleinigen B2G-Kanal',
  'Mitte bis Ende 2024 (die Quellen sind sich über den genauen Umstellungstag uneinig -- unterschiedlich berichtet als 1. Juli, „September“ oder „1. September nach einer zweimonatigen Übergangszeit“) wurde SABIS (Sąskaitų administravimo bendroji informacinė sistema) Litauens alleinige nationale B2G-E-Invoicing-Plattform und ersetzte das ältere, 2015 eingeführte „E. sąskaita“/eSaskaita-System. Lieferanten können Rechnungen manuell über das Webportal eingeben oder strukturierte EN-16931-E-Rechnungen über Peppol übermitteln.', '["Falls Sie in der Lieferantendokumentation noch auf das alte System E. sąskaita/eSaskaita verweisen, aktualisieren Sie dies auf SABIS"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-sabis-oral-contracts-2025', 'de',
  'SABIS-Anwendungsbereich erstreckt sich auf Rechnungen aus mündlich geschlossenen Vergabeverträgen',
  'Ab dem 1. Januar 2025 (Branchenquelle; in dieser Rechercherunde konnte keine offizielle, unabhängige Seite der VMI/des Amts für öffentliche Auftragsvergabe abgerufen werden, die dieses Datum bestätigt) müssen auch Rechnungen aus mündlich geschlossenen öffentlichen Vergabeverträgen -- zuvor nur oberhalb eines Schwellenwerts von EUR 1.000 (ohne Mehrwertsteuer) über SABIS zu leiten -- unabhängig vom Wert über die Plattform eingereicht werden.', '[]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2b-voluntary', 'de',
  'B2B-E-Rechnungsstellung bleibt freiwillig -- kein CTC- oder Clearance-Mandat',
  'Litauen hat kein Mandat für die elektronische Rechnungsstellung zwischen Unternehmen, kein Rechnungs-Clearance-System und keine Echtzeit-Transaktionsmeldepflicht -- direkt bestätigt durch das eigene Länder-Factsheet der Europäischen Kommission („Es besteht kein Mandat zwischen Unternehmen (B2B)“ / „Derzeit gibt es in Litauen kein Echtzeit-Meldesystem“). Strukturierte B2B-E-Rechnungsstellung ist optional, nach gegenseitiger Vereinbarung zwischen den Handelspartnern. Die bestehende i.SAF-Pflicht (oben) ist eine separate, nachträgliche Mehrwertsteuer-Meldepflicht, kein Rechnungsstellungsmandat.', '["Derzeit ist keine inländische B2B-E-Invoicing-Maßnahme erforderlich", "Verwechseln Sie die i.SAF-Meldepflicht nicht mit einem E-Invoicing-Mandat -- sie sind rechtlich und operativ voneinander getrennt"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2b-2028-target', 'de',
  'Ein allgemeines B2B-Mandat zum „1. Januar 2028“ wird im eigenen Factsheet der EK genannt -- aber dies ist KEIN bestätigtes litauisches Gesetz',
  'Das eigene 2025 Lithuania eInvoicing Country Sheet der Europäischen Kommission nennt „1. Januar 2028“ als Ziel für die verpflichtende E-Rechnungsstellung -- aber dieselbe Seite erklärt separat: „Es besteht kein Mandat zwischen Unternehmen (B2B)“, und es wurde nirgends ein erlassenes litauisches Gesetz, eine VMI-Anordnung oder ein Seimas-Akt gefunden, der ein tatsächliches 2028-Mandat bestätigt. Das Nachbarland Lettland hat ein reales, separat erlassenes B2B-Mandat, das selbst auf genau den 1. Januar 2028 verschoben wurde (KPMG, Juni 2025) -- was die reale Möglichkeit aufwirft, dass einige oder alle in der Branchenberichterstattung kursierenden „Litauen 2028“-Behauptungen auf diese Mehrdeutigkeit oder auf eine Verwechslung mit Lettlands bestätigtem Datum zurückgehen, statt auf eine eigenständige litauische Verpflichtung. Behandeln Sie dieses Datum bestenfalls als Richtwert, nicht als bestätigt -- es wird hier nur festgehalten, weil es in einer offiziellen EU-Quelle auftaucht, mit diesem beigefügten Vorbehalt.', '["Behandeln Sie den 1. Januar 2028 nicht als bestätigte Compliance-Frist für Litauen -- beobachten Sie, ob ein tatsächlich erlassenes Gesetz kommt, bevor Sie darum herum planen", "Achten Sie auf eine Ankündigung des litauischen Finanzministeriums oder des Seimas, die diese Mehrdeutigkeit in die eine oder andere Richtung auflösen würde"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-vida-2030', 'de',
  'ViDA-grenzüberschreitende B2B-E-Rechnungsstellung und digitale Meldung werden verpflichtend (bestätigtes EU-Recht)',
  'Ab dem 1. Juli 2030 werden gemäß der Richtlinie (EU) 2025/516 des Rates die strukturierte E-Rechnungsstellung und die digitale Meldung für alle innergemeinschaftlichen B2B-Lieferungen verpflichtend -- eine feste EU-rechtliche Untergrenze, die für Litauen unabhängig davon gilt, ob das oben genannte unbestätigte innerstaatliche 2028-Ziel jemals zu tatsächlicher Gesetzgebung wird.', '["Bereiten Sie sich auf die verpflichtende strukturierte E-Rechnungsstellung für den gesamten innergemeinschaftlichen B2B-Handel ab Mitte 2030 vor, unabhängig davon, ob zuvor ein inländisches Mandat eingeführt wird"]'
);

INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES (
  '2024-09-01-lithuania-sabis-platform', 'de',
  'Litauen führt die B2G-E-Rechnungsstellung in SABIS zusammen -- doch für B2B gibt es weiterhin kein Mandat',
  'Litauen hat seine B2G-E-Rechnungsstellung auf einer einzigen neuen Plattform, SABIS, zusammengeführt und damit das ältere „E. sąskaita“-System ersetzt. Litauen hat weiterhin kein B2B-E-Invoicing-Mandat -- trotz einer in Teilen der Berichterstattung kursierenden Zahl „1. Januar 2028“, die auf ein in sich widersprüchliches Factsheet der Europäischen Kommission zurückgeht und mit dem eigenen, separat erlassenen 2028-Mandat des Nachbarlands Lettland verwechselt werden könnte.',
  '<h3>🇱🇹 Litauen führt die B2G-E-Rechnungsstellung in SABIS zusammen -- doch für B2B gibt es weiterhin kein Mandat</h3>
<p>2024 stellte Litauen sein älteres „E. sąskaita“-B2G-E-Invoicing-System zugunsten von SABIS (Sąskaitų administravimo bendroji informacinė sistema) ein, dem alleinigen Kanal für strukturierte E-Rechnungen an litauische öffentliche Vergabestellen -- der die manuelle Eingabe im Portal oder die Übermittlung per Peppol BIS Billing 3.0/CII unterstützt. Die E-Rechnungsstellung bei der öffentlichen Auftragsvergabe ist in Litauen seit dem 1. Juli 2017 verpflichtend, und separat reichen mehrwertsteuerlich registrierte Unternehmen seit etwa Oktober 2016 monatlich ein Mehrwertsteuer-Hauptbuch auf Rechnungsebene (i.SAF) bei der Steuerbehörde ein.</p>
<p>Was Litauen nicht hat, ist ein Mandat für die elektronische Rechnungsstellung zwischen Unternehmen. Das eigene Länder-Factsheet der Europäischen Kommission sagt dies direkt -- „es besteht kein Mandat zwischen Unternehmen (B2B)“ -- während dieselbe Seite verwirrenderweise separat „1. Januar 2028“ als Zieldatum für die verpflichtende E-Rechnungsstellung nennt. Kein erlassenes litauisches Gesetz bestätigt dieses Datum, und das Nachbarland Lettland hat ein eigenes reales B2B-Mandat, das auf genau den 1. Januar 2028 verschoben wurde -- was die reale Möglichkeit aufwirft, dass ein Teil der Berichterstattung über „Litauen 2028“ Lettlands bestätigtes Datum widerspiegelt, statt über eine eigenständige litauische Verpflichtung zu berichten. Bis ein tatsächliches Gesetz erscheint, bleibt die ViDA-Untergrenze der EU zum 1. Juli 2030 die einzige feststehende grenzüberschreitende Frist.</p>'
);


-- ==================== fr ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'fr',
  'Pas d''obligation B2B confirmée — B2G en vigueur depuis 2017, déclaration du grand livre de TVA i.SAF depuis 2016, un objectif « 2028 » contesté pour le B2B',
  'Cette page d''analyse reflète le régime de facturation électronique de la Lituanie, tel que confirmé via la fiche pays de facturation électronique de la Commission européenne pour la Lituanie (récupérée de façon indépendante à deux reprises lors de cette série de recherches), ainsi que la propre page i.SAF de la VMI (l''Inspection nationale des impôts) et des sources sectorielles (Sovos, VATupdate) pour les dates de transition de plateforme, à la date du 10 août 2026, et est fournie à titre d''information générale, non comme un conseil juridique ou fiscal. Une date « 2028 » de facturation électronique B2B largement diffusée est signalée tout au long de cette page comme non confirmée — voir la note dédiée ci-dessous — plutôt que présentée comme un fait établi. Confirmez les exigences en vigueur directement auprès de la VMI (vmi.lt) ou d''un conseiller fiscal lituanien avant de fonder vos décisions de conformité sur cette page.',
  'La Lituanie a transposé la directive européenne de facturation électronique B2G le 1er juillet 2017, en l''appliquant plus largement que le minimum de l''UE (l''ensemble des marchés publics, et non uniquement les contrats au-dessus du seuil). Depuis environ octobre 2016, les entreprises immatriculées à la TVA déposent séparément une déclaration mensuelle du grand livre de TVA (i.SAF) — une obligation déclarative, non une obligation de facturation. En 2024, la plateforme B2G a été consolidée au sein de SABIS. La seule question ouverte est de savoir si une obligation générale de facturation électronique B2B arrivera réellement en 2028 — la fiche de la Commission européenne elle-même mentionne cette date tout en affirmant, sur la même page, qu''aucune obligation B2B n''existe actuellement.',
  'La Lituanie accepte les factures électroniques structurées conformes à la norme EN 16931 pour le B2G via SABIS, par Peppol BIS Billing 3.0 ou CII. Pour l''obligation distincte de déclaration i.SAF, la VMI accepte des soumissions XML (format FR0600) via son propre portail — il s''agit d''une déclaration de *données* de facture, non d''un format d''échange de factures, sans incidence sur la manière dont une facture est réellement émise ou envoyée à un client professionnel.',
  'Le champ d''application de la facturation électronique B2G couvre tous les fournisseurs de marchés publics, sans valeur minimale de contrat — un champ d''application véritablement plus large que celui de la plupart des pays européens comparables, qui limitent l''obligation aux contrats au-dessus du seuil. Le champ d''application de la déclaration i.SAF couvre toute entité immatriculée à la TVA en Lituanie, nationale ou étrangère, sans aucun seuil de taille. La facturation électronique B2B elle-même n''a aujourd''hui aucun champ d''application défini puisqu''aucune obligation n''existe — voir la note dédiée sur l''objectif contesté de 2028 ci-dessous pour ce qui pourrait changer cela.',
  'La plupart des entreprises commerçant avec des organismes publics lituaniens sont probablement déjà conformes à l''exigence B2G de 2017 via SABIS. La question de conformité actuelle pour toute entreprise immatriculée à la TVA en Lituanie est la déclaration mensuelle i.SAF, non la facturation électronique elle-même.',
  'Aucun montant de sanction spécifique et confirmé de façon indépendante n''a été établi pour le non-respect d''i.SAF/SAF-T lors de cette série de recherches — deux sources sectorielles donnent des fourchettes en euros différentes, et cette page ne reprend aucune d''elles comme un fait établi tant que le texte en vigueur du Code des infractions administratives ne peut être consulté directement. Ce qui est confirmé : la Lituanie applique des sanctions générales pour insuffisance de paiement de la TVA (20-100 % de la TVA impayée en vertu de la loi sur la TVA et de la loi sur l''administration fiscale), qui s''appliqueraient aux erreurs fiscales sous-jacentes révélées par un écart i.SAF, indépendamment de toute amende spécifique liée à la déclaration.',
  'La Lituanie dispose d''une obligation de facturation électronique B2G (en vigueur depuis le 1er juillet 2017, EN 16931 via SABIS, couvrant l''ensemble des marchés publics quelle que soit leur valeur) et d''une obligation mensuelle de déclaration du grand livre de TVA au niveau de la facture (i.SAF, depuis environ octobre 2016, sans seuil de taille) — mais confirme directement, dans sa propre fiche pays de la Commission européenne, qu'' « il n''existe aucune obligation entre entreprises (B2B) » et qu''« il n''existe actuellement aucun système de déclaration en temps réel ». La même fiche mentionne séparément un objectif « 1er janvier 2028 » pour la facturation électronique obligatoire, que cette page traite comme non confirmé plutôt que comme une échéance réelle — aucune loi lituanienne promulguée ne le corrobore, et il pourrait être confondu avec la propre obligation réelle de 2028, légiférée séparément, du pays voisin, la Lettonie. Le plancher confirmé à l''échelle de l''UE reste le 1er juillet 2030 (ViDA).',
  '🇱🇹'
FROM countries WHERE code = 'LT';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '1er juil. 2017', 'Facturation électronique B2G obligatoire pour l''ensemble des marchés publics' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '~oct. 2016', 'Début de la déclaration mensuelle du grand livre de TVA i.SAF (aucun seuil de taille)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', 'Aucune obligation', 'La facturation électronique B2B reste facultative (confirmé par la fiche de la CE elle-même)' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '2028 ?', 'Objectif B2B contesté de la fiche de la CE — non confirmé, possiblement confondu avec la Lettonie' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '2024', 'SABIS remplace l''ancienne plateforme B2G « E. sąskaita »' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'LT' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'Format et plateforme B2G (SABIS)', '[["Format", "Facture électronique structurée conforme à la norme EN 16931"], ["Plateforme", "SABIS (Sąskaitų administravimo bendroji informacinė sistema), ayant remplacé l''ancien système « E. sąskaita » en 2024"], ["Transmission", "Saisie manuelle sur le portail, ou Peppol BIS Billing 3.0 / CII"], ["Champ d''application", "Tous les contrats de marchés publics, au-dessus et en dessous des seuils de l''UE"]]', 'Le champ d''application B2G de la Lituanie est plus large que celui de la plupart des pays de l''UE comparables -- il s''applique à tout contrat de marché public, et non uniquement à ceux dépassant les seuils de passation des marchés publics de l''UE.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'file_format' AND dct.title = 'B2G format & platform (SABIS)';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'Format de déclaration i.SAF (distinct de la facturation)', '[["Formulaire", "FR0600 -- grand livre structuré des factures de TVA"], ["Contenu", "Registre des ventes (toutes les factures émises) et registre des achats (factures reçues de redevables de la TVA lituaniens, plus les opérations d''autoliquidation)"], ["Fréquence", "Mensuelle, à échéance le 20 du mois suivant"], ["Déclaration néant", "Requise même lorsqu''aucune facture n''a été émise"]]', 'i.SAF est une déclaration périodique concernant vos factures, transmise à la VMI a posteriori -- elle ne change pas le format que vous devez utiliser pour émettre réellement une facture à un client, et il ne s''agit ni d''un système en temps réel ni d''un système de clearance.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'file_format' AND dct.title = 'i.SAF reporting format (separate from invoicing)';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'Ce qui est couvert aujourd''hui', '[["B2G", "Tous les fournisseurs de marchés publics, sans valeur minimale de contrat -- obligatoire depuis le 1er juil. 2017"], ["i.SAF (déclaration de TVA)", "Toute entité immatriculée à la TVA, nationale ou étrangère, sans seuil de taille -- depuis ~oct. 2016"], ["La facturation B2B elle-même", "Aucune obligation d''aucune sorte -- entièrement facultative, par accord mutuel"], ["B2C", "Non couvert par une quelconque règle de facturation électronique ou de déclaration"]]', NULL, NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'scope_transmission' AND dct.title = 'What''s covered today';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', 'L''objectif « 2028 » contesté pour le B2B, expliqué', '[["Où il apparaît", "La propre fiche pays 2025 Lithuania eInvoicing Country Sheet de la Commission européenne"], ["La contradiction", "La même page de la fiche affirme aussi sans détour : « Il n''existe aucune obligation entre entreprises (B2B) »"], ["Ce qui le corrobore", "Aucune loi lituanienne promulguée, aucun arrêté de la VMI ni aucun acte du Seimas confirmant une obligation pour 2028 n''a été trouvé nulle part"], ["Une explication plausible", "La Lettonie voisine dispose d''une obligation B2B réelle, légiférée séparément, confirmée comme reportée à exactement le 1er janvier 2028 (KPMG, juin 2025) -- plusieurs sources sectorielles reprenant « Lituanie 2028 » pourraient faire écho à cela, à la formulation ambiguë de la fiche, ou aux deux"]]', 'Cette carte existe spécifiquement pour qu''un lecteur rencontrant le chiffre « 2028 » ailleurs comprenne pourquoi cette page ne le traite pas comme confirmé.', NULL FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'scope_transmission' AND dct.title = 'The disputed "2028" B2B target, explained';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', '⚖️ Aucune sanction de facturation électronique B2B n''existe — car aucune obligation B2B n''existe', NULL, NULL, 'Il n''y a rien à sanctionner sur le plan de la facturation : la Lituanie n''a jamais légiféré d''exigence de facturation électronique B2B ou de clearance, de sorte qu''aucun barème de sanctions ne se rattache à la façon dont vous émettez ou échangez des factures avec une autre entreprise.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'penalties_related' AND dct.title = '⚖️ No B2B e-invoicing fine exists — because no B2B mandate exists';
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT cd.id, 'fr', '📋 Les montants de sanction i.SAF ne sont pas tranchés -- non indiqués ici', NULL, NULL, 'Deux sources sectorielles donnent des fourchettes en euros différentes pour les déclarations i.SAF/SAF-T tardives ou non déposées, et aucune n''a été confirmée de façon indépendante par rapport au texte en vigueur du Code des infractions administratives lors de cette série de recherches (les tentatives d''accès direct à e-seimas.lrs.lt et infolex.lt ont échoué). Plutôt que de présenter l''un ou l''autre chiffre comme établi, cette page confirme uniquement qu''une sanction générale pour insuffisance de paiement de la TVA de 20-100 % de l''impôt impayé s''applique en vertu de la loi sur la TVA et de la loi sur l''administration fiscale, et que des sanctions administratives pour non-dépôt de documents fiscaux existent en principe en vertu d''un article modifié du Code des infractions administratives.' FROM deep_dive_cards cd JOIN countries c ON cd.country_id = c.id JOIN deep_dive_card_translations dct ON dct.card_id = cd.id AND dct.lang = 'en' WHERE c.code = 'LT' AND cd.section = 'penalties_related' AND dct.title = '📋 i.SAF penalty figures are unresolved -- not stated here';

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Confirmez que votre facturation B2G transite déjà par SABIS', 'Si vous fournissez des organismes publics lituaniens, vérifiez que vos factures sont des factures électroniques structurées EN 16931 soumises via SABIS -- la plateforme qui a remplacé l''ancien système E. sąskaita en 2024.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Mettez en place la déclaration mensuelle i.SAF si vous êtes immatriculé à la TVA en Lituanie', 'Assurez-vous que votre logiciel comptable peut produire un grand livre de TVA ventes/achats FR0600 conforme, à échéance le 20 du mois suivant -- il n''existe aucune exonération de taille, et une déclaration néant est requise même pour un mois sans facture.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Ne confondez pas i.SAF avec une obligation de facturation électronique', 'i.SAF modifie les données comptables que vous déclarez et leur fréquence -- cela ne vous impose pas de changer la façon dont vous émettez ou échangez des factures avec d''autres entreprises, puisqu''aucune obligation de facturation électronique B2B de ce type n''existe aujourd''hui en Lituanie.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Considérez le chiffre « 2028 » comme un point de vigilance, pas comme une échéance', 'Ne construisez pas vos plans de conformité autour d''une obligation B2B lituanienne confirmée au 1er janvier 2028 -- elle n''est pas confirmée. Surveillez la VMI et le ministère des Finances pour une loi effectivement promulguée avant de traiter une date quelconque comme réelle.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Préparez-vous malgré tout au plancher de l''UE confirmé pour 2030', 'Quoi qu''il arrive au niveau national, la facturation électronique structurée et la déclaration numérique deviennent obligatoires pour le commerce B2B transfrontalier intracommunautaire à compter du 1er juillet 2030 en vertu de ViDA -- cette date relève du droit de l''UE établi.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'LT' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'fr', 'SABIS -- plateforme nationale de facturation électronique B2G' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'fr', 'VMI (Inspection nationale des impôts) -- explication d''i.SAF' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT pt.id, 'fr', 'EU Digital Building Blocks -- Fiche pays facturation électronique Lituanie' FROM deep_dive_portals pt JOIN countries c ON pt.country_id = c.id WHERE c.code = 'LT' AND pt.sort_order = 2;

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2g-2017', 'fr',
  'Facturation électronique B2G obligatoire pour l''ensemble des marchés publics',
  'Depuis le 1er juillet 2017, tous les fournisseurs des pouvoirs adjudicateurs lituaniens doivent soumettre des factures électroniques structurées pour les contrats de marchés publics -- aussi bien au-dessus qu''en dessous des seuils de passation des marchés publics de l''UE, un champ d''application plus large que le minimum de l''UE. Base légale : la loi sur les marchés publics (Lietuvos Respublikos viešųjų pirkimų įstatymas), transposant la directive UE 2014/55/UE. Format : EN 16931, via Peppol BIS Billing 3.0 ou CII.',
  '["Contexte historique -- aucune action requise pour les fournisseurs existants d''organismes publics lituaniens", "Confirmez que les factures adressées aux pouvoirs adjudicateurs lituaniens sont des factures électroniques structurées EN 16931, et non en PDF ou sur papier"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-isaf-2016', 'fr',
  'Début de la déclaration i.SAF du grand livre de TVA au niveau de la facture',
  'Depuis environ octobre 2016 (date corroborée par des sources sectorielles, non datée de façon indépendante par la propre page de la VMI), toute entité immatriculée à la TVA en Lituanie -- nationale ou étrangère disposant d''un numéro de TVA LT, sans seuil de taille -- doit déposer une déclaration mensuelle i.SAF : un grand livre ligne par ligne des factures de TVA de vente et d''achat, à échéance le 20 du mois suivant, avec une déclaration néant requise même lorsqu''aucune facture n''a été émise. Il s''agit d''une obligation déclarative périodique et a posteriori auprès de l''Inspection nationale des impôts (VMI) -- comparable dans son principe au SII espagnol ou au SAF-T bulgare -- et non d''un système de clearance en temps réel ni d''une obligation de facturation électronique. La fiche pays de la Commission européenne elle-même le confirme directement : « Actuellement, il n''existe aucun système de déclaration en temps réel en Lituanie. »', '["Confirmez que votre système comptable produit un export i.SAF mensuel conforme si vous êtes immatriculé à la TVA en Lituanie", "Ne confondez pas ceci avec une exigence de facturation électronique -- cela régit ce que vous déclarez au sujet des factures, non la façon dont vous les émettez ou les échangez"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-sabis-2024', 'fr',
  'SABIS remplace l''ancienne plateforme « E. sąskaita » en tant que canal B2G unique',
  'Courant mi-2024 à fin 2024 (les sources divergent sur le jour exact du basculement -- rapporté tantôt comme le 1er juillet, « septembre », ou « le 1er septembre après une transition de deux mois »), SABIS (Sąskaitų administravimo bendroji informacinė sistema) est devenue l''unique plateforme nationale de facturation électronique B2G de la Lituanie, remplaçant l''ancien système « E. sąskaita »/eSaskaita lancé en 2015. Les fournisseurs peuvent saisir les factures manuellement via le portail web ou transmettre des factures électroniques structurées EN 16931 via Peppol.', '["Si vous faites encore référence à l''ancien système E. sąskaita/eSaskaita dans la documentation fournisseurs, mettez-la à jour pour indiquer SABIS"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-sabis-oral-contracts-2025', 'fr',
  'Le champ d''application de SABIS s''étend aux factures issues de contrats de marchés publics conclus oralement',
  'À compter du 1er janvier 2025 (d''après une source sectorielle ; aucune page officielle et indépendante de la VMI/de l''Office des marchés publics confirmant cette date n''a pu être récupérée lors de cette série de recherches), les factures issues de contrats de marchés publics conclus verbalement -- auparavant tenues de transiter par SABIS uniquement au-dessus d''un seuil de 1 000 EUR (hors TVA) -- doivent également être soumises via la plateforme quelle que soit leur valeur.', '[]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2b-voluntary', 'fr',
  'La facturation électronique B2B reste facultative -- aucune obligation de CTC ou de clearance',
  'La Lituanie n''a aucune obligation de facturation électronique interentreprises, aucun système de clearance des factures, ni aucune exigence de déclaration des transactions en temps réel -- confirmé directement par la propre fiche pays de la Commission européenne (« Il n''existe aucune obligation entre entreprises (B2B) » / « Actuellement, il n''existe aucun système de déclaration en temps réel en Lituanie »). La facturation électronique B2B structurée est facultative, par accord mutuel entre partenaires commerciaux. L''obligation i.SAF existante (ci-dessus) est une exigence de déclaration de TVA distincte et a posteriori, non une obligation de facturation.', '["Aucune action de facturation électronique B2B nationale n''est requise aujourd''hui", "Ne confondez pas l''obligation déclarative i.SAF avec une obligation de facturation électronique -- elles sont juridiquement et opérationnellement distinctes"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-b2b-2028-target', 'fr',
  'Une obligation générale B2B au « 1er janvier 2028 » est mentionnée dans la propre fiche de la CE -- mais ce n''est PAS une loi lituanienne confirmée',
  'La propre fiche 2025 Lithuania eInvoicing Country Sheet de la Commission européenne mentionne « le 1er janvier 2028 » comme objectif pour la facturation électronique obligatoire -- mais cette même page affirme par ailleurs qu'' « il n''existe aucune obligation entre entreprises (B2B) », et aucune loi lituanienne promulguée, aucun arrêté de la VMI ni aucun acte du Seimas confirmant une obligation réelle pour 2028 n''a été trouvé nulle part. La Lettonie voisine dispose d''une obligation B2B réelle, légiférée séparément, elle-même reportée à exactement le 1er janvier 2028 (KPMG, juin 2025) -- ce qui soulève une possibilité réelle qu''une partie ou la totalité des affirmations « Lituanie 2028 » circulant dans la couverture sectorielle découlent de cette ambiguïté ou d''une confusion avec la date confirmée de la Lettonie, plutôt que d''un engagement lituanien indépendant. Traitez cette date au mieux comme indicative, non confirmée -- elle n''est recensée ici que parce qu''elle figure dans une source officielle de l''UE, avec cette réserve attachée.', '["Ne traitez pas le 1er janvier 2028 comme une échéance de conformité confirmée pour la Lituanie -- surveillez l''apparition d''une loi effectivement promulguée avant de planifier en fonction de cette date", "Surveillez une annonce du ministère lituanien des Finances ou du Seimas qui résoudrait cette ambiguïté dans un sens ou dans l''autre"]'
);
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'lt-vida-2030', 'fr',
  'La facturation électronique B2B transfrontalière et la déclaration numérique ViDA deviennent obligatoires (droit de l''UE confirmé)',
  'À compter du 1er juillet 2030, en vertu de la directive (UE) 2025/516 du Conseil, la facturation électronique structurée et la déclaration numérique deviennent obligatoires pour toutes les livraisons B2B intracommunautaires -- un plancher ferme de droit de l''UE qui s''applique à la Lituanie, que l''objectif national non confirmé de 2028 mentionné ci-dessus se concrétise ou non un jour en une véritable législation.', '["Préparez-vous à la facturation électronique structurée obligatoire pour l''ensemble du commerce B2B intracommunautaire à partir de mi-2030, indépendamment de l''arrivée éventuelle plus tôt d''une obligation nationale"]'
);

INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES (
  '2024-09-01-lithuania-sabis-platform', 'fr',
  'La Lituanie consolide sa facturation électronique B2G sur SABIS -- mais le B2B reste sans obligation',
  'La Lituanie a consolidé sa facturation électronique B2G sur une nouvelle plateforme unique, SABIS, remplaçant l''ancien système « E. sąskaita ». La Lituanie n''a toujours aucune obligation de facturation électronique B2B -- malgré un chiffre « 1er janvier 2028 » circulant dans une partie de la couverture médiatique, qui trouve son origine dans une fiche de la Commission européenne intrinsèquement contradictoire et pourrait être confondu avec l''obligation 2028 propre à la Lettonie voisine, légiférée séparément.',
  '<h3>🇱🇹 La Lituanie consolide sa facturation électronique B2G sur SABIS -- mais le B2B reste sans obligation</h3>
<p>En 2024, la Lituanie a mis fin à son ancien système de facturation électronique B2G « E. sąskaita » au profit de SABIS (Sąskaitų administravimo bendroji informacinė sistema), le canal unique pour les factures électroniques structurées destinées aux pouvoirs adjudicateurs publics lituaniens -- prenant en charge la saisie manuelle sur le portail ou la transmission via Peppol BIS Billing 3.0/CII. La facturation électronique dans les marchés publics est obligatoire en Lituanie depuis le 1er juillet 2017, et, séparément, les entreprises immatriculées à la TVA déposent depuis environ octobre 2016 un grand livre de TVA mensuel au niveau de la facture (i.SAF) auprès de l''administration fiscale.</p>
<p>Ce que la Lituanie n''a pas, c''est une obligation de facturation électronique interentreprises. La propre fiche pays de la Commission européenne le dit directement -- « il n''existe aucune obligation entre entreprises (B2B) » -- alors que, de façon troublante, la même page mentionne séparément « le 1er janvier 2028 » comme date cible pour la facturation électronique obligatoire. Aucune loi lituanienne promulguée ne corrobore cette date, et la Lettonie voisine dispose de sa propre obligation B2B réelle, reportée à exactement le 1er janvier 2028 -- ce qui soulève une possibilité réelle qu''une partie de la couverture sur « Lituanie 2028 » fasse écho à la date confirmée de la Lettonie plutôt qu''elle ne rende compte d''un engagement lituanien indépendant. Tant qu''une loi effective n''apparaît pas, la seule échéance transfrontalière établie demeure le plancher ViDA de l''UE du 1er juillet 2030.</p>'
);
