-- ================================================================
-- Qatar (QA) deep-dive content, EN. ES/DE/FR ride in a separate
-- translation migration, JOIN-lookup pattern. No lifecycle card (no
-- operative invoicing flow exists to diagram -- there is no mandate,
-- no platform, and no format). No deep_dive_penalty_rows -- nothing
-- to penalize, covered instead by a narrative penalties_related
-- card. See 484's header for the full sourcing trail.
-- ================================================================

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-10' FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en',
  'No mandate yet — a draft e-invoicing law was approved by Cabinet on 6 May 2026, still pending Shura Council review and the Amir''s assent',
  'This deep-dive page reflects Qatar''s e-invoicing regime as confirmed via nine independently-checked sources (EY, KPMG, PwC, Thomson Reuters/Pagero, and others), plus a direct fetch of Qatar''s General Tax Authority website, as of 10 August 2026, and is provided for general awareness, not legal or tax advice. Qatar currently has no enacted e-invoicing law of any kind — everything on this page describes a draft in progress, not a live requirement. Confirm current status directly with Qatar''s General Tax Authority (gta.gov.qa) or a qualified Qatari tax adviser before relying on this page for planning purposes.',
  'On 6 May 2026, Qatar''s Council of Ministers approved a draft e-invoicing law and implementing executive regulations — the first real legislative step this tracker has found for Qatar. As of this page''s last update, that draft has not advanced any further: it still requires Shura Council review and the Amir''s assent before it becomes law, and no source, official or industry, has reported either step occurring. There is exactly one dated event to show on this timeline because there is exactly one dated event that has actually happened.',
  'No e-invoicing format, schema, or technical standard has been published for Qatar. Qatar''s General Tax Authority (GTA) operates the Dhareeba portal for general tax administration, but it contains no e-invoicing content as of this page''s last update — there is no dedicated e-invoicing portal to point to, unlike Saudi Arabia''s Fatoora or the UAE''s Peppol-based system. Some industry commentary speculates Qatar might follow a Saudi ZATCA-style or UAE Peppol-style model, but this is speculation about a still-undrafted regulation, not a confirmed technical decision, and is not treated as fact here.',
  'No scope has been defined — Qatar''s draft law does not yet specify whether e-invoicing will apply to B2B, B2G, B2C, or some combination, which taxpayer categories or transaction thresholds would be covered, or whether the model would be a real-time clearance system (like Saudi Arabia''s) or a reporting-only system. Everything about scope remains open until the executive regulations are actually published in final, enacted form.',
  'There is nothing to comply with today, because no mandate exists. The steps below describe how to stay informed while Qatar''s law works its way through the legislative process, not how to become compliant with a requirement that doesn''t yet exist.',
  'No penalty schedule has been proposed or published for e-invoicing non-compliance, for the simple reason that no e-invoicing requirement exists yet to attach a penalty to. Qatar''s existing general tax-administration penalties (unrelated to e-invoicing specifically) would presumably continue to apply to any underlying tax matter, but no e-invoicing-specific fine structure exists in any source checked this round.',
  'Qatar has no e-invoicing mandate of any kind. On 6 May 2026, the Council of Ministers approved a draft law and implementing regulations — a real first step, but not an enactment. The draft still requires Shura Council review and the Amir''s assent, and Official Gazette publication has not occurred. No implementation date, taxpayer threshold, technical format, or penalty structure has been officially released, and Qatar has not yet implemented VAT at all, despite a 2016 GCC commitment to do so — an unusually early sequencing for an e-invoicing law. This tracker will update immediately once the draft law is actually enacted or a real timeline is officially published.',
  '📝'
FROM countries WHERE code = 'QA';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Draft stage', 'E-invoicing law status');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '6 May 2026', 'Cabinet approved the draft law and regulations');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Not enacted', 'Shura Council review and Amiri assent still required');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'None yet', 'Qatar has not yet implemented VAT');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'None published', 'Implementation date, threshold, and technical format');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'No format has been published', NULL, NULL, 'Qatar''s General Tax Authority has not published an e-invoicing schema, XML/UBL standard, or technical specification of any kind. The GTA''s own Dhareeba portal was checked directly and contains no e-invoicing content. Some industry commentary speculates Qatar might eventually adopt a Saudi ZATCA-style clearance model or a UAE-style Peppol network, given regional precedent -- but this is speculation about a still-undrafted regulation, not a confirmed technical choice, and this page does not treat it as fact.');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'What''s covered today', '[["B2B", "Not defined -- no mandate exists"], ["B2G", "Not defined -- no mandate exists"], ["B2C", "Not defined -- no mandate exists"], ["VAT regime", "Not yet implemented, despite a 2016 GCC Unified VAT Agreement commitment"]]', 'Every row in this table says "not defined" or "not yet implemented" for the same reason: Qatar''s e-invoicing law exists only as an unenacted draft.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'What has to happen before this becomes real', '[["Step 1 (done)", "Council of Ministers approves the draft law and executive regulations -- 6 May 2026"], ["Step 2 (pending)", "Shura Council review -- no date reported"], ["Step 3 (pending)", "Submission to the Amir for enactment"], ["Step 4 (pending)", "Publication in the Official Gazette"]]', 'This tracker will add a real "on tracker" milestone the moment any of the pending steps is independently confirmed.', NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚖️ No penalty schedule exists — because no mandate exists', NULL, NULL, 'There is nothing to penalize: Qatar has not enacted an e-invoicing requirement of any kind, so no fine or sanction schedule attaches to how (or whether) you issue invoices electronically.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📋 Unconfirmed industry timelines — deliberately not repeated here', NULL, NULL, 'Some industry write-ups (e.g. Wafeq) name specific dates such as "October 2026 notifications" or "January 2027 enforcement," but present these explicitly as analyst speculation, not figures published by Qatar''s government. Every official-adjacent source checked (EY, KPMG, PwC, Thomson Reuters) states plainly that no implementation timetable has been released. This page does not repeat the speculative dates as fact.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🌍 Context: the rest of the Gulf is moving faster', NULL, NULL, 'Saudi Arabia''s Fatoora system is live and mature; the UAE is phasing in a Peppol-based B2B mandate from July 2026; Oman has a live pilot. Qatar''s draft law, approved 6 May 2026, makes it the third GCC country to take a concrete legislative step -- but the only one still entirely at the draft stage, with Bahrain and Kuwait having taken no formal step at all.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'There is nothing to comply with today', 'No e-invoicing mandate is in force in Qatar. No registration, filing, or format change is required or even possible yet.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Watch for the real signals of enactment', 'The draft law becomes real news at three specific points: a Shura Council vote, an Amiri Decree, or publication in the Official Gazette. Nothing short of one of these three has happened yet.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Expect a phased rollout by taxpayer size, if enacted', 'Every other GCC e-invoicing mandate built so far (Saudi Arabia, UAE, Oman) rolled out in waves by taxpayer size or revenue tier rather than all at once -- a reasonable expectation for Qatar too, though not yet confirmed.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Don''t plan around unofficial dates', 'Some industry commentary circulates specific 2026/2027 dates for Qatar. None of them is sourced to a Qatari government document -- treat them as speculation, not a compliance deadline, until this page says otherwise.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Bookmark this page', 'This tracker will add a real milestone, update the stats, and publish a proper compliance timeline the moment Qatar''s draft law actually clears the Shura Council or is enacted.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://dhareeba.gov.qa', 0 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'General Tax Authority -- Dhareeba portal (general tax administration; no e-invoicing content yet)');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.ey.com/en_gl/technical/tax-alerts/qatar-approves-draft-e-invoicing-law-and-implementing-regulations', 1 FROM countries WHERE code = 'QA';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'EY tax alert -- summary of the draft law (industry source, not government-published)');
