-- ================================================================
-- Bahrain (BH) deep-dive content, EN. ES/DE/FR ride in a separate
-- translation migration, JOIN-lookup pattern. No lifecycle card (no
-- operative invoicing flow exists to diagram). No
-- deep_dive_penalty_rows -- no e-invoicing-specific penalty exists;
-- Bahrain's general (unrelated) VAT penalties are covered narratively
-- and explicitly caveated as not independently re-verified this
-- round. See 485's header for the full sourcing trail.
-- ================================================================

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-10' FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en',
  'No mandate — e-invoicing remains entirely voluntary, with no draft law, proposal, or timeline of any kind',
  'This deep-dive page reflects Bahrain''s e-invoicing regime as confirmed via the National Bureau for Revenue''s (NBR) own VAT General Guide, two independent professional trackers (EY, Aurifer), and Bahrain''s own Tender Board records, as of 10 August 2026, and is provided for general awareness, not legal or tax advice. Bahrain has no e-invoicing mandate, draft law, or officially-published timeline of any kind — everything on this page describes voluntary practice and preparatory government activity, not a live or upcoming requirement. Confirm current status directly with Bahrain''s National Bureau for Revenue (nbr.gov.bh) or a qualified Bahraini tax adviser before relying on this page for planning purposes.',
  'The one dated, primary-source-confirmed event on this timeline is a minor procedural change: on 16 Nov 2023, the NBR removed a requirement that businesses get prior approval before voluntarily issuing electronic invoices. That''s it — there is no earlier or later e-invoicing-specific milestone to show, because nothing else has happened. Two independent professional trackers checked directly in mid-2026 (EY, Aurifer) both still classify Bahrain as having no applicable mandate and being in "preparatory work" only.',
  'No e-invoicing format, schema, or technical standard exists for Bahrain, because e-invoicing is entirely voluntary and unregulated beyond ordinary VAT invoicing rules. There is no NBR e-invoicing platform, and Bahrain is confirmed not to be a Peppol member.',
  'No scope has ever been defined for a Bahraini e-invoicing mandate, because no mandate has ever been proposed. Ordinary VAT invoicing rules apply uniformly across B2B, B2G, and B2C, with no electronic-format requirement of any kind.',
  'There is nothing to comply with today, and nothing on the horizon with a published date. The steps below describe how to stay informed given Bahrain''s neighbours are moving on e-invoicing, not how to become compliant with a requirement that doesn''t exist.',
  'No e-invoicing-specific penalty schedule has ever been proposed or published, since no e-invoicing requirement exists to attach a penalty to. Bahrain does have general VAT-law penalties covering unrelated matters (late filing, registration failures, invoice-procedure violations, tax evasion) — these are noted below for completeness but are not e-invoicing penalties, and the specific figures were not independently re-verified against the primary VAT law text this research round.',
  'Bahrain has no e-invoicing mandate, draft law, or officially-published timeline of any kind. The only confirmed, dated fact is a minor Nov 2023 procedural change: the NBR removed a requirement to seek prior approval before voluntarily issuing electronic invoices — e-invoicing remains entirely voluntary. Two independent professional trackers checked mid-2026 (EY, Aurifer) both classify Bahrain as still in "preparatory work," alongside Kuwait, while Saudi Arabia, the UAE, and Oman all have active or imminent mandates and Qatar has at least approved a draft law. A 2023 government tender for an e-invoicing platform, and an unconfirmed report of a further 2025 tender, hint at preparatory activity behind the scenes, but neither is a law. This tracker will update immediately once any real proposal, draft law, or timeline is officially published.',
  '📝'
FROM countries WHERE code = 'BH';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'No mandate', 'E-invoicing law status');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'Voluntary only', 'Current basis for e-invoicing in Bahrain');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '16 Nov 2023', 'NBR removed prior-approval requirement for voluntary e-invoicing');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'None published', 'Mandate proposal, draft law, or timeline of any kind');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '"Preparatory work"', 'Per EY''s and Aurifer''s own trackers, both mid-2026');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'No format exists — because e-invoicing remains voluntary', NULL, NULL, 'Bahrain has never published an e-invoicing schema, XML/UBL standard, or technical specification. There is no NBR e-invoicing platform, and Bahrain is confirmed not to be a member of the Peppol network. Businesses that voluntarily issue electronic invoices do so on their own systems, under ordinary VAT invoicing rules, not any e-invoicing-specific format.');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'What''s covered today', '[["B2B", "Not defined -- no mandate exists"], ["B2G", "Not defined -- no mandate exists"], ["B2C", "Not defined -- no mandate exists"], ["Voluntary e-invoicing", "Permitted without prior NBR approval, since 16 Nov 2023"]]', NULL, NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 1 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Preparatory signals, not a mandate', '[["2023 platform tender", "Confirmed via Bahrain''s own Tender Board (305/2023/BTB): a 54-month contract to design/operate an e-invoicing platform"], ["2025 tender (reported)", "A further tender for a nationwide B2B system was reported by one industry brief -- could not be independently corroborated this round"], ["Expected model", "Industry commentary speculates a Saudi ZATCA-style approach -- not an official Bahraini government decision"], ["Peppol membership", "Bahrain is not a Peppol member"]]', 'A government tender to build a platform is real preparatory activity, but it is not a law, a mandate, or a dated legal requirement -- included here for completeness, not as evidence a mandate is imminent.', NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚖️ No e-invoicing penalty schedule exists', NULL, NULL, 'There is nothing to penalize on the e-invoicing side: Bahrain has never legislated an e-invoicing mandate, so no fine or sanction schedule attaches to how (or whether) you issue invoices electronically.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📋 Bahrain''s general VAT penalties (unrelated to e-invoicing)', NULL, NULL, 'Bahrain''s ordinary VAT law carries its own general penalties -- late filing/payment (5-25% of tax due), failure to register (fine up to BHD 10,000), invoice-procedure violations (fine up to BHD 5,000), and tax evasion including non-issuance of invoices (imprisonment plus fines). These apply to VAT compliance broadly and are not specific to e-invoicing; the figures come from a secondary compliance source and were not independently re-verified against the primary VAT law text this research round.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🌍 Context: one of two GCC states with no mandate at all', NULL, NULL, 'Saudi Arabia''s Fatoora system is live and mature; the UAE is phasing in a Peppol-based B2B mandate from July 2026; Oman has a live pilot; Qatar approved a draft law on 6 May 2026. Bahrain and Kuwait are now the only two GCC states with no formal step toward e-invoicing at all.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'There is nothing to comply with today', 'No e-invoicing mandate exists in Bahrain, proposed or enacted. No registration, filing, or format change is required.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'E-invoicing is available voluntarily, with no approval needed', 'Since Nov 2023, any VAT-registered business may issue electronic invoices without seeking NBR''s prior approval -- but nothing requires you to, and no format or platform is mandated.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Watch for a real proposal, not just a tender', 'Bahrain has issued government tenders for e-invoicing platform infrastructure, but a tender is not a mandate. Watch specifically for a draft VAT law amendment or NBR mandate announcement.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Expect Bahrain to follow regional precedent eventually', 'With Saudi Arabia, the UAE, Oman, and now Qatar all moving on e-invoicing, Bahrain is likely to eventually follow -- but nothing officially confirms a timeline, and this page will not speculate on one.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Bookmark this page', 'This tracker will add a real milestone and a proper compliance timeline the moment Bahrain publishes an actual e-invoicing proposal or draft law.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.nbr.gov.bh', 0 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'National Bureau for Revenue (NBR) -- general VAT administration; no e-invoicing mandate content');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.fonoa.com/resources/blog/bahrain-eliminates-tax-authority-approval-requirement-for-e-invoice-issuance', 1 FROM countries WHERE code = 'BH';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'Fonoa -- summary of the Nov 2023 prior-approval removal (industry source, not government-published)');
