-- ================================================================
-- Qatar (QA) ES/DE/FR translations, completing 484 (milestones), 486
-- (deep-dive content) and 488 (launch story) against their English
-- content. Separate migration file, so every deep-dive translation
-- row looks up its parent row via a JOIN on stable identifying
-- columns (country code / section / sort_order / stable url), never
-- via (SELECT MAX(id) ...) -- pattern reference: 481 (Lithuania), 442
-- (Kazakhstan). milestone_translations and story_translations have
-- natural PKs (milestone_id / story_id), so those rows are plain
-- INSERT OR IGNORE statements keyed on the hardcoded id strings from
-- 484/488 -- no JOIN needed. INSERT OR IGNORE throughout.
--
-- Qatar has no lifecycle card and no deep_dive_penalty_rows entries
-- (see 486's header -- the penalties_related cards carry the
-- narrative instead), so those tables are not touched here.
--
-- IMPORTANT -- Qatar has NO enacted e-invoicing mandate, only a
-- draft law approved by Cabinet on 6 May 2026. Every field below
-- preserves that "not yet enacted / draft only" framing with the
-- same clarity as the English source -- never softened into
-- something that sounds more confirmed or definite. Kept unchanged
-- across languages: proper nouns and official/institution names
-- (GTA, Dhareeba, EY, KPMG, PwC, GCC, VAT, ZATCA, Fatoora, Peppol),
-- and the Shura Council / Amir, rendered as natural per-language
-- equivalents (Consejo de la Shura / Emir es; Schura-Rat / Emir de;
-- Conseil de la Choura / Émir fr). Dates localized per language
-- convention: "6 May 2026" -> "6 de mayo de 2026" (es) / "6. Mai
-- 2026" (de) / "6 mai 2026" (fr). mandate_summary_icon is always
-- '📝', untranslated in every language.
-- ================================================================


-- ==================== es ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'es',
  'Sin mandato todavía — un anteproyecto de ley de facturación electrónica fue aprobado por el Gabinete el 6 de mayo de 2026, aún pendiente de la revisión del Consejo de la Shura y de la sanción del Emir',
  'Esta página de análisis refleja el régimen de facturación electrónica de Catar tal como se confirma a través de nueve fuentes verificadas de forma independiente (EY, KPMG, PwC, Thomson Reuters/Pagero, entre otras), junto con una consulta directa del sitio web de la Autoridad General Tributaria de Catar, con fecha de 10 de agosto de 2026, y se ofrece a título informativo general, no como asesoría legal o tributaria. Catar no cuenta actualmente con ninguna ley de facturación electrónica promulgada de ningún tipo -- todo lo que aparece en esta página describe un anteproyecto en curso, no un requisito vigente. Confirme la situación actual directamente con la Autoridad General Tributaria de Catar (gta.gov.qa) o con un asesor fiscal catarí cualificado antes de basar en esta página sus decisiones de planificación.',
  'El 6 de mayo de 2026, el Consejo de Ministros de Catar aprobó un anteproyecto de ley de facturación electrónica y su reglamento de ejecución -- el primer paso legislativo real que este rastreador ha encontrado para Catar. Hasta la última actualización de esta página, ese anteproyecto no ha avanzado más: todavía requiere la revisión del Consejo de la Shura y la sanción del Emir antes de convertirse en ley, y ninguna fuente, oficial o del sector, ha informado de que se haya producido ninguno de esos dos pasos. En esta línea temporal figura exactamente un evento con fecha porque exactamente un evento ha ocurrido realmente.',
  'No se ha publicado ningún formato, esquema o estándar técnico de facturación electrónica para Catar. La Autoridad General Tributaria (GTA) de Catar gestiona el portal Dhareeba para la administración tributaria general, pero este no contiene ningún contenido de facturación electrónica a fecha de la última actualización de esta página -- no existe ningún portal dedicado a la facturación electrónica al que remitir, a diferencia del sistema Fatoora de Arabia Saudí o del sistema basado en Peppol de los Emiratos Árabes Unidos. Algunos comentarios del sector especulan con que Catar podría seguir un modelo al estilo ZATCA de Arabia Saudí o al estilo Peppol de los EAU, pero se trata de una especulación sobre un reglamento aún sin redactar, no de una decisión técnica confirmada, y no se trata aquí como un hecho.',
  'No se ha definido ningún alcance -- el anteproyecto de ley de Catar todavía no especifica si la facturación electrónica se aplicará al B2B, al B2G, al B2C o a alguna combinación de ellos, qué categorías de contribuyentes o umbrales de transacción quedarían cubiertos, ni si el modelo sería un sistema de clearance en tiempo real (como el de Arabia Saudí) o un sistema únicamente de reporte. Todo lo relativo al alcance sigue abierto hasta que el reglamento de ejecución se publique realmente en su forma final y promulgada.',
  'Hoy no hay nada que cumplir, porque no existe ningún mandato. Los pasos siguientes describen cómo mantenerse informado mientras la ley de Catar avanza en el proceso legislativo, no cómo cumplir con un requisito que todavía no existe.',
  'No se ha propuesto ni publicado ningún régimen de sanciones por incumplimiento de facturación electrónica, por la sencilla razón de que todavía no existe ningún requisito de facturación electrónica al que asociar una sanción. Es de suponer que las sanciones generales de administración tributaria ya existentes en Catar (no relacionadas específicamente con la facturación electrónica) seguirían aplicándose a cualquier cuestión tributaria subyacente, pero no existe ninguna estructura de multas específica para la facturación electrónica en ninguna de las fuentes consultadas en esta ronda.',
  'Catar no tiene ningún mandato de facturación electrónica de ningún tipo. El 6 de mayo de 2026, el Consejo de Ministros aprobó un anteproyecto de ley y su reglamento de ejecución -- un primer paso real, pero no una promulgación. El anteproyecto todavía requiere la revisión del Consejo de la Shura y la sanción del Emir, y no se ha producido la publicación en el Boletín Oficial. No se ha publicado oficialmente ninguna fecha de implementación, umbral de contribuyentes, formato técnico ni estructura de sanciones, y Catar todavía no ha implementado el IVA en absoluto, pese a un compromiso del CCG de 2016 para hacerlo -- una secuencia inusualmente temprana para una ley de facturación electrónica. Este rastreador se actualizará de inmediato en cuanto el anteproyecto de ley sea realmente promulgado o se publique oficialmente un calendario real.',
  '📝'
FROM countries WHERE code = 'QA';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', 'Fase de anteproyecto', 'Estado de la ley de facturación electrónica' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', '6 de mayo de 2026', 'El Gabinete aprobó el anteproyecto de ley y el reglamento' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', 'No promulgada', 'Aún se requieren la revisión del Consejo de la Shura y la sanción amirí' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', 'Ninguno todavía', 'Catar aún no ha implementado el IVA' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'es', 'Ninguno publicado', 'Fecha de implementación, umbral y formato técnico' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'es', 'No se ha publicado ningún formato', NULL, NULL, 'La Autoridad General Tributaria de Catar no ha publicado ningún esquema de facturación electrónica, estándar XML/UBL ni especificación técnica de ningún tipo. Se comprobó directamente el propio portal Dhareeba de la GTA y no contiene ningún contenido de facturación electrónica. Algunos comentarios del sector especulan con que Catar podría adoptar eventualmente un modelo de clearance al estilo ZATCA de Arabia Saudí o una red al estilo Peppol de los EAU, dado el precedente regional -- pero se trata de una especulación sobre un reglamento aún sin redactar, no de una elección técnica confirmada, y esta página no la trata como un hecho.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'es', 'Qué está cubierto hoy', '[["B2B", "No definido -- no existe ningún mandato"], ["B2G", "No definido -- no existe ningún mandato"], ["B2C", "No definido -- no existe ningún mandato"], ["Régimen de IVA", "Aún no implementado, pese al compromiso adquirido en el Acuerdo Unificado de IVA del CCG de 2016"]]', 'Cada fila de esta tabla dice "no definido" o "aún no implementado" por la misma razón: la ley de facturación electrónica de Catar existe únicamente como un anteproyecto no promulgado.', NULL FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'es', 'Qué tiene que ocurrir antes de que esto se haga realidad', '[["Paso 1 (completado)", "El Consejo de Ministros aprueba el anteproyecto de ley y el reglamento de ejecución -- 6 de mayo de 2026"], ["Paso 2 (pendiente)", "Revisión del Consejo de la Shura -- sin fecha comunicada"], ["Paso 3 (pendiente)", "Remisión al Emir para su promulgación"], ["Paso 4 (pendiente)", "Publicación en el Boletín Oficial"]]', 'Este rastreador añadirá un hito real "en seguimiento" en el momento en que se confirme de forma independiente cualquiera de los pasos pendientes.', NULL FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'es', '⚖️ No existe ningún régimen de sanciones — porque no existe ningún mandato', NULL, NULL, 'No hay nada que sancionar: Catar no ha promulgado ningún requisito de facturación electrónica de ningún tipo, por lo que no existe ningún régimen de multas o sanciones vinculado a cómo (o si) emite sus facturas electrónicamente.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'es', '📋 Calendarios del sector sin confirmar — deliberadamente no repetidos aquí', NULL, NULL, 'Algunos artículos del sector (por ejemplo, Wafeq) mencionan fechas concretas como "notificaciones en octubre de 2026" o "entrada en vigor en enero de 2027", pero las presentan explícitamente como especulación de analistas, no como cifras publicadas por el Gobierno de Catar. Todas las fuentes cercanas a lo oficial consultadas (EY, KPMG, PwC, Thomson Reuters) afirman claramente que no se ha publicado ningún calendario de implementación. Esta página no repite las fechas especulativas como si fueran un hecho.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'es', '🌍 Contexto: el resto del Golfo avanza más rápido', NULL, NULL, 'El sistema Fatoora de Arabia Saudí está operativo y maduro; los EAU están implementando por fases un mandato B2B basado en Peppol desde julio de 2026; Omán cuenta con un proyecto piloto en funcionamiento. El anteproyecto de ley de Catar, aprobado el 6 de mayo de 2026, lo convierte en el tercer país del CCG en dar un paso legislativo concreto -- pero el único que se encuentra todavía enteramente en fase de anteproyecto, mientras que Baréin y Kuwait no han dado ningún paso formal en absoluto.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Hoy no hay nada que cumplir', 'No existe ningún mandato de facturación electrónica vigente en Catar. No se requiere -- ni siquiera es posible todavía -- ningún registro, presentación o cambio de formato.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Esté atento a las señales reales de la promulgación', 'El anteproyecto de ley se convierte en noticia real en tres momentos concretos: una votación del Consejo de la Shura, un Decreto Amirí o la publicación en el Boletín Oficial. Hasta ahora no se ha producido ninguno de estos tres.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Espere un despliegue por fases según el tamaño del contribuyente, si se promulga', 'Todos los demás mandatos de facturación electrónica del CCG construidos hasta ahora (Arabia Saudí, EAU, Omán) se desplegaron por oleadas según el tamaño del contribuyente o el nivel de ingresos, en lugar de hacerlo todo a la vez -- una expectativa razonable también para Catar, aunque todavía no confirmada.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'No planifique en torno a fechas no oficiales', 'Algunos comentarios del sector hacen circular fechas concretas de 2026/2027 para Catar. Ninguna está sustentada en un documento del Gobierno catarí -- trátelas como especulación, no como una fecha límite de cumplimiento, hasta que esta página indique lo contrario.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'es', 'Guarde esta página en favoritos', 'Este rastreador añadirá un hito real, actualizará las estadísticas y publicará un calendario de cumplimiento adecuado en el momento en que el anteproyecto de ley de Catar realmente supere al Consejo de la Shura o sea promulgado.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT p.id, 'es', 'Autoridad General Tributaria -- portal Dhareeba (administración tributaria general; sin contenido de facturación electrónica todavía)' FROM deep_dive_portals p JOIN countries c ON p.country_id = c.id WHERE c.code = 'QA' AND p.url = 'https://dhareeba.gov.qa';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT p.id, 'es', 'Alerta fiscal de EY -- resumen del anteproyecto de ley (fuente del sector, no publicada por el Gobierno)' FROM deep_dive_portals p JOIN countries c ON p.country_id = c.id WHERE c.code = 'QA' AND p.url = 'https://www.ey.com/en_gl/technical/tax-alerts/qatar-approves-draft-e-invoicing-law-and-implementing-regulations';

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'qa-draft-law-2026', 'es',
  'El Consejo de Ministros aprueba un anteproyecto de ley de facturación electrónica -- aún no promulgado',
  'El 6 de mayo de 2026, el Consejo de Ministros (Gabinete) de Catar aprobó un anteproyecto de ley de facturación electrónica y su reglamento de ejecución -- confirmado directamente por EY, KPMG, PwC y Thomson Reuters/Pagero, todos ellos describiendo la misma acción única. Se trata de un paso real, pero no de un mandato: el anteproyecto aún debe pasar por la revisión del Consejo de la Shura y luego ser remitido al Emir para su promulgación, y no se ha producido la publicación en el Boletín Oficial. Ninguna fuente, oficial o del sector, ha confirmado de forma independiente ningún paso posterior desde el 6 de mayo de 2026. No se ha publicado oficialmente ninguna fecha de implementación, umbral de contribuyentes, modelo de facturación (clearance o reporte) ni régimen de sanciones -- algunos comentarios del sector especulan con una entrada en vigor en 2027 o un despliegue al estilo saudí/emiratí, pero nada de ello está sustentado en un documento del Gobierno catarí, por lo que no se recoge como un hecho en esta página. La Autoridad General Tributaria de Catar todavía no cuenta con un portal dedicado a la facturación electrónica, y el propio Catar aún no ha implementado el IVA (pendiente desde el Acuerdo Unificado de IVA del CCG de 2016) -- una secuencia inusualmente temprana para una ley de facturación electrónica.',
  '["No se requiere ni es posible ninguna acción de cumplimiento todavía -- no existe ningún mandato, no existe ningún portal y no se ha publicado ningún formato", "No planifique en torno a ninguna fecha específica de 2026/2027 que circule en los comentarios del sector -- ninguna está sustentada en un documento del Gobierno catarí", "Esté atento a la revisión del Consejo de la Shura, al Decreto Amirí y a la publicación en el Boletín Oficial como las señales reales de que esto ha pasado de anteproyecto a ley promulgada"]'
);

INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES (
  '2026-05-06-qatar-draft-elaw-approved', 'es',
  'Catar da su primer paso legislativo en materia de facturación electrónica -- todavía queda un largo camino hasta un mandato',
  'El Consejo de Ministros de Catar aprobó un anteproyecto de ley de facturación electrónica y su reglamento de ejecución el 6 de mayo de 2026 -- un primer paso real, pero no un mandato. El anteproyecto todavía necesita la revisión del Consejo de la Shura y la sanción del Emir, no se ha publicado ninguna fecha de implementación ni formato, y Catar ni siquiera ha implementado todavía el IVA.',
  '<h3>🇶🇦 Catar da su primer paso legislativo en materia de facturación electrónica -- todavía queda un largo camino hasta un mandato</h3>
<p>El 6 de mayo de 2026, el Consejo de Ministros de Catar aprobó un anteproyecto de ley de facturación electrónica y su reglamento de ejecución -- confirmado por EY, KPMG, PwC y Thomson Reuters/Pagero, todos ellos describiendo la misma acción única. Se trata del primer movimiento legislativo concreto que este rastreador ha encontrado sobre la facturación electrónica catarí, y sitúa a Catar junto a Arabia Saudí, los Emiratos Árabes Unidos y Omán como un Estado del Golfo que avanza activamente hacia un mandato.</p>
<p>Pero "anteproyecto" significa exactamente eso: la ley todavía tiene que superar la revisión del Consejo de la Shura, después ser remitida al Emir para su promulgación y, por último, publicarse en el Boletín Oficial -- y, a fecha de publicación de esta noticia, ninguno de esos pasos se ha confirmado de forma independiente. No se ha publicado oficialmente ninguna fecha de implementación, umbral de contribuyentes, formato técnico ni estructura de sanciones. Algunos comentarios del sector especulan con una entrada en vigor en 2027 o un despliegue al estilo saudí/emiratí, pero nada de ello está sustentado en un documento del Gobierno catarí. Subrayando lo temprano de esta fase: Catar todavía no ha implementado el IVA en absoluto, pese a haberse comprometido a hacerlo en virtud del Acuerdo Unificado de IVA del CCG de 2016 -- una secuencia inusual para un país que ahora está redactando una ley de facturación electrónica.</p>'
);


-- ==================== de ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'de',
  'Noch kein Mandat — ein Entwurf eines E-Invoicing-Gesetzes wurde am 6. Mai 2026 vom Kabinett gebilligt, die Prüfung durch den Schura-Rat und die Zustimmung des Emir stehen noch aus',
  'Diese Analyseseite spiegelt Katars E-Invoicing-Regime wider, wie es über neun unabhängig geprüfte Quellen (EY, KPMG, PwC, Thomson Reuters/Pagero und weitere) sowie einen direkten Abruf der Website von Katars Allgemeiner Steuerbehörde bestätigt wurde, mit Stand 10. August 2026, und dient allgemeinen Informationszwecken, nicht als Rechts- oder Steuerberatung. Katar verfügt derzeit über kein erlassenes E-Invoicing-Gesetz jeglicher Art -- alles auf dieser Seite beschreibt einen laufenden Entwurf, keine geltende Anforderung. Bestätigen Sie den aktuellen Stand direkt bei Katars Allgemeiner Steuerbehörde (gta.gov.qa) oder bei einem qualifizierten katarischen Steuerberater, bevor Sie sich bei Planungszwecken auf diese Seite verlassen.',
  'Am 6. Mai 2026 billigte der Ministerrat Katars den Entwurf eines E-Invoicing-Gesetzes samt Durchführungsverordnung -- der erste reale gesetzgeberische Schritt, den dieser Tracker für Katar gefunden hat. Mit Stand der letzten Aktualisierung dieser Seite ist dieser Entwurf nicht weiter vorangekommen: Er benötigt noch die Prüfung durch den Schura-Rat und die Zustimmung des Emir, bevor er zum Gesetz wird, und keine Quelle, weder offiziell noch aus der Branche, hat berichtet, dass einer dieser beiden Schritte stattgefunden hat. Es gibt in dieser Zeitleiste genau ein datiertes Ereignis, weil genau ein datiertes Ereignis tatsächlich stattgefunden hat.',
  'Für Katar wurde kein E-Invoicing-Format, kein Schema und kein technischer Standard veröffentlicht. Katars Allgemeine Steuerbehörde (GTA) betreibt das Dhareeba-Portal für die allgemeine Steuerverwaltung, das jedoch mit Stand der letzten Aktualisierung dieser Seite keinerlei E-Invoicing-Inhalte enthält -- es gibt kein eigenes E-Invoicing-Portal, auf das verwiesen werden könnte, anders als bei Saudi-Arabiens Fatoora oder dem Peppol-basierten System der VAE. Einige Branchenkommentare spekulieren, Katar könnte sich an einem ZATCA-ähnlichen Modell Saudi-Arabiens oder einem Peppol-ähnlichen Modell der VAE orientieren, doch dies ist Spekulation über eine noch nicht ausgearbeitete Regelung, keine bestätigte technische Entscheidung, und wird hier nicht als Tatsache behandelt.',
  'Es wurde kein Anwendungsbereich festgelegt -- Katars Gesetzentwurf legt noch nicht fest, ob E-Invoicing für B2B, B2G, B2C oder eine Kombination gelten wird, welche Steuerpflichtigenkategorien oder Transaktionsschwellenwerte erfasst würden, oder ob das Modell ein Echtzeit-Clearance-System (wie in Saudi-Arabien) oder ein reines Meldesystem wäre. Alles zum Anwendungsbereich bleibt offen, bis die Durchführungsverordnung tatsächlich in endgültiger, erlassener Form veröffentlicht wird.',
  'Heute gibt es nichts einzuhalten, weil kein Mandat besteht. Die folgenden Schritte beschreiben, wie Sie informiert bleiben, während sich Katars Gesetz durch den Gesetzgebungsprozess bewegt -- nicht, wie man eine Anforderung erfüllt, die es noch nicht gibt.',
  'Es wurde kein Bußgeldkatalog für die Nichteinhaltung von E-Invoicing-Vorschriften vorgeschlagen oder veröffentlicht, aus dem einfachen Grund, dass es noch keine E-Invoicing-Anforderung gibt, an die ein Bußgeld geknüpft werden könnte. Katars bestehende allgemeine Sanktionen der Steuerverwaltung (nicht speziell E-Invoicing-bezogen) würden vermutlich weiterhin für jede zugrunde liegende steuerliche Angelegenheit gelten, doch in keiner in dieser Runde geprüften Quelle existiert ein E-Invoicing-spezifischer Bußgeldkatalog.',
  'Katar hat kein E-Invoicing-Mandat jeglicher Art. Am 6. Mai 2026 billigte der Ministerrat einen Gesetzentwurf samt Durchführungsverordnung -- ein realer erster Schritt, aber kein Erlass. Der Entwurf benötigt noch die Prüfung durch den Schura-Rat und die Zustimmung des Emir, und eine Veröffentlichung im Amtsblatt ist nicht erfolgt. Es wurde offiziell weder ein Umsetzungsdatum noch ein Steuerpflichtigen-Schwellenwert, ein technisches Format noch eine Bußgeldstruktur veröffentlicht, und Katar hat die Mehrwertsteuer trotz einer GCC-Verpflichtung von 2016 bislang überhaupt noch nicht eingeführt -- eine ungewöhnlich frühe Abfolge für ein E-Invoicing-Gesetz. Dieser Tracker wird umgehend aktualisiert, sobald der Gesetzentwurf tatsächlich erlassen wird oder ein realer Zeitplan offiziell veröffentlicht wird.',
  '📝'
FROM countries WHERE code = 'QA';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', 'Entwurfsstadium', 'Status des E-Invoicing-Gesetzes' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', '6. Mai 2026', 'Kabinett billigte den Gesetzentwurf und die Verordnung' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', 'Nicht erlassen', 'Prüfung durch den Schura-Rat und Zustimmung des Emir noch erforderlich' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', 'Noch keine', 'Katar hat die Mehrwertsteuer noch nicht eingeführt' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'de', 'Noch nichts veröffentlicht', 'Umsetzungsdatum, Schwellenwert und technisches Format' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'de', 'Es wurde kein Format veröffentlicht', NULL, NULL, 'Katars Allgemeine Steuerbehörde hat weder ein E-Invoicing-Schema noch einen XML/UBL-Standard noch eine technische Spezifikation jeglicher Art veröffentlicht. Das GTA-eigene Dhareeba-Portal wurde direkt geprüft und enthält keinerlei E-Invoicing-Inhalte. Einige Branchenkommentare spekulieren, Katar könnte angesichts des regionalen Präzedenzfalls letztlich ein Clearance-Modell nach ZATCA-Vorbild Saudi-Arabiens oder ein Peppol-Netzwerk nach Vorbild der VAE übernehmen -- doch dies ist Spekulation über eine noch nicht ausgearbeitete Regelung, keine bestätigte technische Entscheidung, und diese Seite behandelt es nicht als Tatsache.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'de', 'Was heute abgedeckt ist', '[["B2B", "Nicht festgelegt -- es besteht kein Mandat"], ["B2G", "Nicht festgelegt -- es besteht kein Mandat"], ["B2C", "Nicht festgelegt -- es besteht kein Mandat"], ["Mehrwertsteuersystem", "Noch nicht eingeführt, trotz einer im GCC-Mehrwertsteuer-Rahmenabkommen von 2016 eingegangenen Verpflichtung"]]', 'Jede Zeile dieser Tabelle sagt aus demselben Grund „nicht festgelegt" oder „noch nicht eingeführt": Katars E-Invoicing-Gesetz existiert nur als nicht erlassener Entwurf.', NULL FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'de', 'Was geschehen muss, bevor dies Realität wird', '[["Schritt 1 (erledigt)", "Der Ministerrat billigt den Gesetzentwurf und die Durchführungsverordnung -- 6. Mai 2026"], ["Schritt 2 (ausstehend)", "Prüfung durch den Schura-Rat -- kein Termin gemeldet"], ["Schritt 3 (ausstehend)", "Vorlage beim Emir zur Erlassung"], ["Schritt 4 (ausstehend)", "Veröffentlichung im Amtsblatt"]]', 'Dieser Tracker wird in dem Moment, in dem einer der ausstehenden Schritte unabhängig bestätigt wird, einen echten „im Tracker geführten" Meilenstein hinzufügen.', NULL FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'de', '⚖️ Es gibt keinen Bußgeldkatalog — weil es kein Mandat gibt', NULL, NULL, 'Es gibt nichts zu sanktionieren: Katar hat keinerlei E-Invoicing-Anforderung erlassen, sodass kein Bußgeld- oder Sanktionskatalog daran anknüpft, wie (oder ob) Sie Rechnungen elektronisch ausstellen.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'de', '📋 Unbestätigte Branchen-Zeitpläne — hier bewusst nicht wiederholt', NULL, NULL, 'Einige Branchenberichte (z. B. Wafeq) nennen konkrete Termine wie „Meldungen ab Oktober 2026" oder „Durchsetzung ab Januar 2027", stellen dies aber ausdrücklich als Spekulation von Analysten dar, nicht als von der katarischen Regierung veröffentlichte Zahlen. Jede geprüfte, dem Offiziellen nahestehende Quelle (EY, KPMG, PwC, Thomson Reuters) erklärt klar, dass kein Umsetzungsfahrplan veröffentlicht wurde. Diese Seite wiederholt die spekulativen Termine nicht als Tatsache.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'de', '🌍 Einordnung: Der Rest des Golfs kommt schneller voran', NULL, NULL, 'Saudi-Arabiens Fatoora-System ist live und ausgereift; die VAE führen ab Juli 2026 schrittweise ein Peppol-basiertes B2B-Mandat ein; Oman hat ein laufendes Pilotprojekt. Katars am 6. Mai 2026 gebilligter Gesetzentwurf macht das Land zum dritten GCC-Staat mit einem konkreten gesetzgeberischen Schritt -- aber zum einzigen, das sich noch vollständig im Entwurfsstadium befindet, während Bahrain und Kuwait bislang überhaupt keinen formalen Schritt unternommen haben.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Heute gibt es nichts einzuhalten', 'In Katar ist derzeit kein E-Invoicing-Mandat in Kraft. Es ist weder eine Registrierung, eine Meldung noch eine Formatumstellung erforderlich oder überhaupt möglich.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Achten Sie auf die eigentlichen Signale der Erlassung', 'Der Gesetzentwurf wird an drei konkreten Punkten zur echten Nachricht: einer Abstimmung im Schura-Rat, einem Amiri-Dekret oder der Veröffentlichung im Amtsblatt. Bislang ist keiner dieser drei Schritte eingetreten.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Erwarten Sie im Falle einer Erlassung eine stufenweise Einführung nach Steuerpflichtigengröße', 'Jedes andere bisher aufgebaute GCC-E-Invoicing-Mandat (Saudi-Arabien, VAE, Oman) wurde in Wellen nach Steuerpflichtigengröße oder Umsatzstufe eingeführt statt auf einmal -- eine vernünftige Erwartung auch für Katar, wenngleich noch nicht bestätigt.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Planen Sie nicht anhand inoffizieller Termine', 'Einige Branchenkommentare verbreiten konkrete 2026/2027-Termine für Katar. Keiner davon stützt sich auf ein katarisches Regierungsdokument -- behandeln Sie sie als Spekulation, nicht als Compliance-Frist, bis diese Seite etwas anderes angibt.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'de', 'Setzen Sie ein Lesezeichen für diese Seite', 'Dieser Tracker wird einen echten Meilenstein hinzufügen, die Statistiken aktualisieren und einen ordentlichen Compliance-Zeitplan veröffentlichen, sobald Katars Gesetzentwurf tatsächlich den Schura-Rat passiert oder erlassen wird.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT p.id, 'de', 'Allgemeine Steuerbehörde -- Dhareeba-Portal (allgemeine Steuerverwaltung; noch keine E-Invoicing-Inhalte)' FROM deep_dive_portals p JOIN countries c ON p.country_id = c.id WHERE c.code = 'QA' AND p.url = 'https://dhareeba.gov.qa';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT p.id, 'de', 'EY-Steueralarm -- Zusammenfassung des Gesetzentwurfs (Branchenquelle, nicht von der Regierung veröffentlicht)' FROM deep_dive_portals p JOIN countries c ON p.country_id = c.id WHERE c.code = 'QA' AND p.url = 'https://www.ey.com/en_gl/technical/tax-alerts/qatar-approves-draft-e-invoicing-law-and-implementing-regulations';

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'qa-draft-law-2026', 'de',
  'Ministerrat billigt Entwurf eines E-Invoicing-Gesetzes -- noch nicht erlassen',
  'Am 6. Mai 2026 billigte der Ministerrat (das Kabinett) Katars den Entwurf eines E-Invoicing-Gesetzes samt Durchführungsverordnung -- direkt bestätigt durch EY, KPMG, PwC und Thomson Reuters/Pagero, die alle dieselbe einzelne Maßnahme beschreiben. Dies ist ein realer Schritt, aber kein Mandat: Der Entwurf muss noch die Prüfung durch den Schura-Rat durchlaufen und anschließend dem Emir zur Erlassung vorgelegt werden, und eine Veröffentlichung im Amtsblatt ist nicht erfolgt. Keine Quelle, weder offiziell noch aus der Branche, hat seit dem 6. Mai 2026 einen weiteren Schritt unabhängig bestätigt. Es wurde offiziell weder ein Umsetzungsdatum noch ein Steuerpflichtigen-Schwellenwert, ein Rechnungsmodell (Clearance oder Meldung) noch ein Bußgeldkatalog veröffentlicht -- einige Branchenkommentare spekulieren über einen Start 2027 oder ein Vorgehen nach saudischem/emiratischem Vorbild, doch nichts davon stützt sich auf ein katarisches Regierungsdokument, weshalb es auf dieser Seite nicht als Tatsache festgehalten wird. Katars Allgemeine Steuerbehörde verfügt noch über kein eigenes E-Invoicing-Portal, und Katar selbst hat die Mehrwertsteuer noch nicht eingeführt (weiterhin ausstehend unter dem GCC-Mehrwertsteuer-Rahmenabkommen von 2016) -- eine ungewöhnlich frühe Abfolge für ein E-Invoicing-Gesetz.',
  '["Derzeit ist keine Compliance-Maßnahme erforderlich oder überhaupt möglich -- es besteht kein Mandat, es gibt kein Portal, und es wurde kein Format veröffentlicht", "Planen Sie nicht anhand eines bestimmten, in Branchenkommentaren kursierenden Datums aus 2026/2027 -- keines davon stützt sich auf ein katarisches Regierungsdokument", "Achten Sie auf die Prüfung durch den Schura-Rat, ein Amiri-Dekret und die Veröffentlichung im Amtsblatt als die eigentlichen Signale dafür, dass dies vom Entwurf zum erlassenen Gesetz geworden ist"]'
);

INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES (
  '2026-05-06-qatar-draft-elaw-approved', 'de',
  'Katar unternimmt seinen ersten gesetzgeberischen Schritt beim E-Invoicing -- bis zu einem Mandat ist es noch ein weiter Weg',
  'Katars Ministerrat billigte am 6. Mai 2026 den Entwurf eines E-Invoicing-Gesetzes samt Durchführungsverordnung -- ein realer erster Schritt, aber kein Mandat. Der Entwurf benötigt noch die Prüfung durch den Schura-Rat und die Zustimmung des Emir, es wurde weder ein Umsetzungsdatum noch ein Format veröffentlicht, und Katar hat noch nicht einmal die Mehrwertsteuer eingeführt.',
  '<h3>🇶🇦 Katar unternimmt seinen ersten gesetzgeberischen Schritt beim E-Invoicing -- bis zu einem Mandat ist es noch ein weiter Weg</h3>
<p>Am 6. Mai 2026 billigte Katars Ministerrat den Entwurf eines E-Invoicing-Gesetzes samt Durchführungsverordnung -- bestätigt durch EY, KPMG, PwC und Thomson Reuters/Pagero, die alle dieselbe einzelne Maßnahme beschreiben. Es ist die erste konkrete gesetzgeberische Bewegung, die dieser Tracker beim katarischen E-Invoicing gefunden hat, und stellt Katar neben Saudi-Arabien, die VAE und Oman als Golfstaat, der aktiv auf ein Mandat hinarbeitet.</p>
<p>Doch „Entwurf" bedeutet genau das: Das Gesetz muss noch die Prüfung durch den Schura-Rat durchlaufen, anschließend dem Emir zur Erlassung vorgelegt und schließlich im Amtsblatt veröffentlicht werden -- und mit Stand der Veröffentlichung dieser Nachricht wurde keiner dieser Schritte unabhängig bestätigt. Es wurde offiziell weder ein Umsetzungsdatum noch ein Steuerpflichtigen-Schwellenwert, ein technisches Format noch eine Bußgeldstruktur veröffentlicht. Einige Branchenkommentare spekulieren über einen Start 2027 oder ein Vorgehen nach saudischem/emiratischem Vorbild, doch nichts davon stützt sich auf ein katarisches Regierungsdokument. Wie früh sich das alles noch befindet, unterstreicht auch: Katar hat die Mehrwertsteuer trotz einer entsprechenden Verpflichtung im Rahmen des GCC-Mehrwertsteuer-Rahmenabkommens von 2016 bislang überhaupt noch nicht eingeführt -- eine ungewöhnliche Abfolge für ein Land, das nun ein E-Invoicing-Gesetz entwirft.</p>'
);


-- ==================== fr ====================

INSERT OR IGNORE INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'fr',
  'Pas encore de mandat — un projet de loi sur la facturation électronique a été approuvé par le Cabinet le 6 mai 2026, toujours en attente de l''examen du Conseil de la Choura et de l''assentiment de l''Émir',
  'Cette page d''analyse reflète le régime de facturation électronique du Qatar tel que confirmé par neuf sources vérifiées de manière indépendante (EY, KPMG, PwC, Thomson Reuters/Pagero, entre autres), ainsi que par une consultation directe du site de l''Autorité générale des impôts du Qatar, à la date du 10 août 2026, et est fournie à titre d''information générale, non comme un conseil juridique ou fiscal. Le Qatar ne dispose actuellement d''aucune loi sur la facturation électronique promulguée, quelle qu''elle soit -- tout ce qui figure sur cette page décrit un projet en cours, pas une exigence en vigueur. Confirmez la situation actuelle directement auprès de l''Autorité générale des impôts du Qatar (gta.gov.qa) ou d''un conseiller fiscal qatari qualifié avant de vous fonder sur cette page pour vos décisions de planification.',
  'Le 6 mai 2026, le Conseil des ministres du Qatar a approuvé un projet de loi sur la facturation électronique et son règlement d''application -- la première véritable étape législative que ce suivi ait trouvée pour le Qatar. À la date de la dernière mise à jour de cette page, ce projet n''a pas progressé davantage : il nécessite encore l''examen du Conseil de la Choura et l''assentiment de l''Émir avant de devenir loi, et aucune source, officielle ou du secteur, n''a rapporté que l''une ou l''autre de ces étapes ait eu lieu. Cette chronologie ne comporte exactement qu''un seul événement daté, car exactement un seul événement s''est réellement produit.',
  'Aucun format, schéma ou norme technique de facturation électronique n''a été publié pour le Qatar. L''Autorité générale des impôts (GTA) du Qatar exploite le portail Dhareeba pour l''administration fiscale générale, mais celui-ci ne contient aucun contenu relatif à la facturation électronique à la date de la dernière mise à jour de cette page -- il n''existe aucun portail dédié à la facturation électronique vers lequel se tourner, contrairement au système Fatoora de l''Arabie saoudite ou au système fondé sur Peppol des Émirats arabes unis. Certains commentaires du secteur évoquent l''hypothèse que le Qatar pourrait suivre un modèle de type ZATCA saoudien ou de type Peppol émirati, mais il s''agit d''une spéculation portant sur une réglementation encore non rédigée, et non d''un choix technique confirmé ; cette page ne la présente pas comme un fait.',
  'Aucun champ d''application n''a été défini -- le projet de loi qatari ne précise pas encore si la facturation électronique s''appliquera au B2B, au B2G, au B2C ou à une combinaison de ceux-ci, quelles catégories d''assujettis ou quels seuils de transaction seraient couverts, ni si le modèle serait un système de clearance en temps réel (comme en Arabie saoudite) ou un système de simple déclaration. Tout ce qui touche au champ d''application reste ouvert tant que le règlement d''application n''est pas effectivement publié sous sa forme définitive et promulguée.',
  'Il n''y a rien à respecter aujourd''hui, car aucun mandat n''existe. Les étapes ci-dessous décrivent comment rester informé pendant que la loi qatarie suit son parcours législatif, et non comment se conformer à une exigence qui n''existe pas encore.',
  'Aucun barème de sanctions n''a été proposé ni publié en cas de non-conformité en matière de facturation électronique, pour la simple raison qu''aucune obligation de facturation électronique n''existe encore à laquelle rattacher une sanction. Les sanctions générales déjà existantes en matière d''administration fiscale au Qatar (sans lien spécifique avec la facturation électronique) continueraient vraisemblablement de s''appliquer à toute question fiscale sous-jacente, mais aucune structure d''amende propre à la facturation électronique ne figure dans aucune source consultée lors de cette recherche.',
  'Le Qatar n''a aucun mandat de facturation électronique, quel qu''il soit. Le 6 mai 2026, le Conseil des ministres a approuvé un projet de loi et son règlement d''application -- une première étape réelle, mais pas une promulgation. Le projet nécessite encore l''examen du Conseil de la Choura et l''assentiment de l''Émir, et la publication au Journal officiel n''a pas eu lieu. Aucune date de mise en œuvre, seuil d''assujettissement, format technique ni structure de sanctions n''a été officiellement publié, et le Qatar n''a même pas encore mis en œuvre la TVA, malgré un engagement du CCG datant de 2016 -- un enchaînement inhabituellement précoce pour une loi sur la facturation électronique. Ce suivi sera mis à jour immédiatement dès que le projet de loi sera réellement promulgué ou qu''un calendrier réel sera officiellement publié.',
  '📝'
FROM countries WHERE code = 'QA';

INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', 'Stade de projet', 'Statut de la loi sur la facturation électronique' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', '6 mai 2026', 'Le Cabinet a approuvé le projet de loi et le règlement' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', 'Non promulguée', 'L''examen du Conseil de la Choura et l''assentiment amiri restent nécessaires' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', 'Aucune pour l''instant', 'Le Qatar n''a pas encore mis en œuvre la TVA' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) SELECT s.id, 'fr', 'Rien de publié', 'Date de mise en œuvre, seuil et format technique' FROM deep_dive_stats s JOIN countries c ON s.country_id = c.id WHERE c.code = 'QA' AND s.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'fr', 'Aucun format n''a été publié', NULL, NULL, 'L''Autorité générale des impôts du Qatar n''a publié aucun schéma de facturation électronique, aucune norme XML/UBL ni aucune spécification technique d''aucune sorte. Le portail Dhareeba de la GTA lui-même a été consulté directement et ne contient aucun contenu relatif à la facturation électronique. Certains commentaires du secteur évoquent l''hypothèse que le Qatar pourrait éventuellement adopter un modèle de clearance de type ZATCA saoudien ou un réseau de type Peppol émirati, compte tenu du précédent régional -- mais il s''agit d''une spéculation portant sur une réglementation encore non rédigée, et non d''un choix technique confirmé, et cette page ne la présente pas comme un fait.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'file_format' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'fr', 'Ce qui est couvert aujourd''hui', '[["B2B", "Non défini -- aucun mandat n''existe"], ["B2G", "Non défini -- aucun mandat n''existe"], ["B2C", "Non défini -- aucun mandat n''existe"], ["Régime de TVA", "Pas encore mis en œuvre, malgré un engagement pris au titre de l''accord unifié du CCG sur la TVA de 2016"]]', 'Chaque ligne de ce tableau indique « non défini » ou « pas encore mis en œuvre » pour la même raison : la loi qatarie sur la facturation électronique n''existe qu''à l''état de projet non promulgué.', NULL FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'scope_transmission' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'fr', 'Ce qui doit se produire avant que cela devienne réalité', '[["Étape 1 (réalisée)", "Le Conseil des ministres approuve le projet de loi et le règlement d''application -- 6 mai 2026"], ["Étape 2 (en attente)", "Examen par le Conseil de la Choura -- aucune date communiquée"], ["Étape 3 (en attente)", "Soumission à l''Émir pour promulgation"], ["Étape 4 (en attente)", "Publication au Journal officiel"]]', 'Ce suivi ajoutera un véritable jalon « suivi » dès que l''une des étapes en attente sera confirmée de manière indépendante.', NULL FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'scope_transmission' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'fr', '⚖️ Aucun barème de sanctions n''existe — car aucun mandat n''existe', NULL, NULL, 'Il n''y a rien à sanctionner : le Qatar n''a promulgué aucune obligation de facturation électronique d''aucune sorte, si bien qu''aucun barème d''amendes ou de sanctions n''est rattaché à la manière (ou à la question de savoir si) vous émettez vos factures par voie électronique.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'fr', '📋 Calendriers du secteur non confirmés — délibérément non repris ici', NULL, NULL, 'Certains articles du secteur (par exemple Wafeq) mentionnent des dates précises telles que « notifications en octobre 2026 » ou « entrée en vigueur en janvier 2027 », mais les présentent explicitement comme des spéculations d''analystes, et non comme des chiffres publiés par le gouvernement qatari. Chaque source proche de l''officiel consultée (EY, KPMG, PwC, Thomson Reuters) indique clairement qu''aucun calendrier de mise en œuvre n''a été publié. Cette page ne reprend pas ces dates spéculatives comme des faits.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) SELECT dc.id, 'fr', '🌍 Contexte : le reste du Golfe avance plus vite', NULL, NULL, 'Le système Fatoora de l''Arabie saoudite est opérationnel et mature ; les Émirats arabes unis déploient progressivement un mandat B2B fondé sur Peppol à partir de juillet 2026 ; Oman dispose d''un projet pilote actif. Le projet de loi qatari, approuvé le 6 mai 2026, fait du Qatar le troisième pays du CCG à franchir une étape législative concrète -- mais le seul encore entièrement au stade de projet, alors que Bahreïn et le Koweït n''ont pris aucune mesure formelle à ce jour.' FROM deep_dive_cards dc JOIN countries c ON dc.country_id = c.id WHERE c.code = 'QA' AND dc.section = 'penalties_related' AND dc.sort_order = 2;

INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Il n''y a rien à respecter aujourd''hui', 'Aucun mandat de facturation électronique n''est en vigueur au Qatar. Aucune inscription, déclaration ou modification de format n''est requise, ni même possible pour l''instant.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 0;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Surveillez les véritables signaux de promulgation', 'Le projet de loi deviendra une véritable actualité à trois moments précis : un vote du Conseil de la Choura, un décret amiri, ou une publication au Journal officiel. Aucun de ces trois événements ne s''est encore produit.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 1;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Attendez-vous à un déploiement progressif selon la taille des assujettis, en cas de promulgation', 'Chaque autre mandat de facturation électronique déjà mis en place dans le CCG (Arabie saoudite, Émirats arabes unis, Oman) a été déployé par vagues selon la taille des assujettis ou le niveau de chiffre d''affaires, plutôt que d''un seul coup -- une attente raisonnable pour le Qatar également, bien que non encore confirmée.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 2;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Ne planifiez rien autour de dates non officielles', 'Certains commentaires du secteur font circuler des dates précises de 2026/2027 pour le Qatar. Aucune ne repose sur un document du gouvernement qatari -- considérez-les comme des spéculations, pas comme une échéance de conformité, tant que cette page n''indique pas le contraire.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 3;
INSERT OR IGNORE INTO deep_dive_step_translations (step_id, lang, title, description) SELECT sp.id, 'fr', 'Ajoutez cette page à vos favoris', 'Ce suivi ajoutera un véritable jalon, mettra à jour les statistiques et publiera un calendrier de conformité approprié dès que le projet de loi qatari franchira réellement le Conseil de la Choura ou sera promulgué.' FROM deep_dive_steps sp JOIN countries c ON sp.country_id = c.id WHERE c.code = 'QA' AND sp.sort_order = 4;

INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT p.id, 'fr', 'Autorité générale des impôts -- portail Dhareeba (administration fiscale générale ; aucun contenu de facturation électronique pour l''instant)' FROM deep_dive_portals p JOIN countries c ON p.country_id = c.id WHERE c.code = 'QA' AND p.url = 'https://dhareeba.gov.qa';
INSERT OR IGNORE INTO deep_dive_portal_translations (portal_id, lang, label) SELECT p.id, 'fr', 'Alerte fiscale EY -- résumé du projet de loi (source du secteur, non publiée par le gouvernement)' FROM deep_dive_portals p JOIN countries c ON p.country_id = c.id WHERE c.code = 'QA' AND p.url = 'https://www.ey.com/en_gl/technical/tax-alerts/qatar-approves-draft-e-invoicing-law-and-implementing-regulations';

INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES (
  'qa-draft-law-2026', 'fr',
  'Le Conseil des ministres approuve un projet de loi sur la facturation électronique -- pas encore promulgué',
  'Le 6 mai 2026, le Conseil des ministres (le Cabinet) du Qatar a approuvé un projet de loi sur la facturation électronique et son règlement d''application -- confirmé directement par EY, KPMG, PwC et Thomson Reuters/Pagero, qui décrivent tous la même action unique. Il s''agit d''une étape réelle, mais pas d''un mandat : le projet doit encore passer par l''examen du Conseil de la Choura, puis être soumis à l''Émir pour promulgation, et la publication au Journal officiel n''a pas eu lieu. Aucune source, officielle ou du secteur, n''a confirmé de manière indépendante une quelconque étape ultérieure depuis le 6 mai 2026. Aucune date de mise en œuvre, seuil d''assujettissement, modèle de facturation (clearance ou déclaration) ni barème de sanctions n''a été officiellement publié -- certains commentaires du secteur évoquent une entrée en vigueur en 2027 ou un déploiement à la saoudienne/émiratie, mais rien de tout cela ne repose sur un document du gouvernement qatari, et ce n''est donc pas présenté comme un fait sur cette page. L''Autorité générale des impôts du Qatar ne dispose pas encore d''un portail dédié à la facturation électronique, et le Qatar lui-même n''a pas encore mis en œuvre la TVA (toujours en attente au titre de l''accord unifié du CCG sur la TVA de 2016) -- un enchaînement inhabituellement précoce pour une loi sur la facturation électronique.',
  '["Aucune action de conformité n''est requise ni même possible pour l''instant -- aucun mandat n''existe, aucun portail n''existe, et aucun format n''a été publié", "Ne planifiez rien autour d''une date précise de 2026/2027 circulant dans les commentaires du secteur -- aucune ne repose sur un document du gouvernement qatari", "Surveillez l''examen par le Conseil de la Choura, le décret amiri et la publication au Journal officiel, qui sont les véritables signaux du passage du projet à une loi promulguée"]'
);

INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES (
  '2026-05-06-qatar-draft-elaw-approved', 'fr',
  'Le Qatar franchit sa première étape législative en matière de facturation électronique -- un mandat reste encore loin',
  'Le Conseil des ministres du Qatar a approuvé un projet de loi sur la facturation électronique et son règlement d''application le 6 mai 2026 -- une première étape réelle, mais pas un mandat. Le projet nécessite encore l''examen du Conseil de la Choura et l''assentiment de l''Émir, aucune date de mise en œuvre ni format n''a été publié, et le Qatar n''a même pas encore mis en œuvre la TVA.',
  '<h3>🇶🇦 Le Qatar franchit sa première étape législative en matière de facturation électronique -- un mandat reste encore loin</h3>
<p>Le 6 mai 2026, le Conseil des ministres du Qatar a approuvé un projet de loi sur la facturation électronique et son règlement d''application -- confirmé par EY, KPMG, PwC et Thomson Reuters/Pagero, qui décrivent tous la même action unique. Il s''agit du premier mouvement législatif concret que ce suivi ait trouvé concernant la facturation électronique qatarie, plaçant le Qatar aux côtés de l''Arabie saoudite, des Émirats arabes unis et d''Oman parmi les États du Golfe travaillant activement à l''instauration d''un mandat.</p>
<p>Mais « projet » signifie exactement cela : la loi doit encore passer l''examen du Conseil de la Choura, puis être soumise à l''Émir pour promulgation, puis être publiée au Journal officiel -- et, à la date de publication de cet article, aucune de ces étapes n''a été confirmée de manière indépendante. Aucune date de mise en œuvre, seuil d''assujettissement, format technique ni structure de sanctions n''a été officiellement publié. Certains commentaires du secteur évoquent une entrée en vigueur en 2027 ou un déploiement à la saoudienne/émiratie, mais rien de tout cela ne repose sur un document du gouvernement qatari. Ce qui souligne le caractère précoce de tout cela : le Qatar n''a même pas encore mis en œuvre la TVA, malgré l''engagement pris à cet effet au titre de l''accord unifié du CCG sur la TVA de 2016 -- un enchaînement inhabituel pour un pays en train de rédiger une loi sur la facturation électronique.</p>'
);

