-- Uzbekistan deep-dive content (English). A mature, universal B2B
-- e-invoicing regime (ESF / электрон счёт-фактура): voluntary from
-- 1 Jul 2019, mandatory for all business entities since 1 Jan 2020,
-- and since 1 Jan 2026 layered with real-time automated risk scoring
-- that ties the buyer's input VAT credit to the invoice's risk status.
--
-- Deliberate editorial position on the compliance model: this page
-- does NOT call Uzbekistan a clearance regime, despite one circulated
-- industry booklet doing so. The evidence points the other way and is
-- set out in its own card -- the buyer, not the tax authority, is the
-- validation gate, and the 2026 risk system colours invoices rather
-- than blocking them. Where sources genuinely disagree the page says
-- so rather than picking a tidy label.
--
-- Sourcing: lex.uz (Resolutions 522, 489, 168; Decree UP-153; Law
-- ZRU-1108; Decree UP-100) and gov.uz (State Tax Committee) fetched
-- directly; Uzbek specialist legal press (Norma.uz, Buxgalter.uz,
-- Gazeta.uz, Spot.uz, UzDaily) for operational detail and statistics;
-- EY and PwC as labelled secondary. Flagged gaps are stated on the
-- page itself rather than hidden: Appendix 2 to Resolution 489 could
-- not be retrieved in full, Tax Code Article 223's verbatim text was
-- not read directly, the JSON format rests on secondary sources only,
-- and B2C scope is genuinely contested.

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-10' FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en',
  'Centralised continuous transaction control (CTC): universal B2B e-invoicing since 2020, exchanged through the state platform or a registered operator, with the buyer as the validation gate — not a pre-clearance regime',
  'This deep-dive page reflects Uzbek legislation as published on lex.uz and the State Tax Committee''s own portal (gov.uz), supplemented by Uzbek specialist legal and tax press where primary appendices could not be retrieved in full, as of 10 August 2026. It is provided for general awareness, not legal or tax advice. Several items are explicitly flagged on this page as unconfirmed rather than presented as settled — please read those notes. Confirm current requirements directly with Uzbekistan''s Tax Committee, your ESF operator, or an Uzbek tax adviser before relying on this page for compliance decisions.',
  'Uzbekistan''s ESF electronic invoice regime was created by Cabinet of Ministers Resolution No. 522 of 25 June 2019: voluntary from 1 July 2019, mandatory for all business entities from 1 January 2020. Resolution No. 489 of August 2020 set the operating rules still in force. Two changes landed on 1 January 2026 — real-time invoice risk scoring, and the extension of the obligation to the self-employed.',
  'A compliant Uzbek e-invoice is a structured electronic document signed with an ETsP digital signature by the seller and countersigned by the buyer on acceptance. It is exchanged either through the state platform or through any of the registered private EDO operators, with interoperability between operators handled by the state-designated roaming operator, the state enterprise "Yangi Texnologiyalar". Product and service lines carry ITSPU classification codes drawn from the national e-catalogue.',
  'The obligation is universal for business entities and is not tied to the VAT threshold: every economic entity must issue electronic invoices, whether or not it is a VAT payer. Self-employed persons were brought in from 1 January 2026. Paper invoices survive only where a transaction involves state secrets. Sales to individual consumers sit outside the electronic exchange loop in practice and are covered by online cash registers instead.',
  'If you trade B2B in Uzbekistan you are already in scope and have been since 2020 — there is no phase-in left to prepare for. The live work is adapting to the two January 2026 changes: the risk-scoring system, which affects when your buyers can recover input VAT on your invoices, and the pre-filled returns generated from your own invoice feed.',
  'Uzbekistan backs the mandate with a single quantified sanction — 20% of the concealed tax base under Tax Code Article 223 — rather than a published schedule of fixed fines. The 2026 risk-scoring system carries no penalty at all; its consequence is deferral of the buyer''s input VAT credit.',
  'Uzbekistan has required electronic invoices from all business entities since 1 January 2020, under Cabinet of Ministers Resolution No. 522. Invoices are exchanged through the state platform or a registered private operator, digitally signed by the seller and confirmed by the buyer within ten days. From 1 January 2026 every invoice is scored for risk in real time, with input VAT on a flagged invoice creditable only once the tax reaches the budget, and the tax authority now pre-fills VAT returns directly from the invoice feed.',
  '🇺🇿'
FROM countries WHERE code = 'UZ';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1 Jan 2020', 'Electronic invoicing becomes mandatory for all business entities');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '~3.5 million', 'Electronic invoices issued every month (reported October 2025)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '27', 'Registered ESF operators on the Tax Committee''s register (January 2026)');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '209,000', 'VAT payers, cited at the April 2026 presidential tax meeting');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '12%', 'Standard VAT rate, with an optional 6% simplified rate from June 2026');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & transmission', '[["Invoice format", "Structured electronic document, reported as JSON"], ["Signature", "ETsP digital signature — bilateral: the seller signs to issue, the buyer signs to accept"], ["Channels", "The state platform, or any of 27 registered private EDO operators"], ["Interoperability", "Handled by the state-designated roaming operator, the state enterprise \"Yangi Texnologiyalar\" (Resolution 522)"], ["Classification codes", "ITSPU codes from the national e-catalogue, which held over 454,500 codes as of September 2024"], ["European standards", "Not EN 16931; Uzbekistan is not a Peppol authority"]]', 'The JSON format is stated consistently across independent secondary sources but no primary technical specification was located in this research round — treat the format name as well-supported rather than confirmed.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Retention: two different clocks', '[["Operators", "Must retain confirmed electronic documents for at least 5 years, after which archiving passes to the tax authority"], ["Taxpayers", "General accounting and tax document retention was reduced from 5 years to 3 years from 1 January 2024 by Law No. ZRU-891, tracking the Tax Code Article 88 limitation period"], ["Longer periods", "Fixed-asset and depreciation records are held longer"]]', 'These are genuinely separate obligations and are frequently conflated. Your operator holding an invoice for five years does not extend your own three-year retention duty, and your three-year duty does not shorten theirs.', NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Who must issue electronic invoices', '[["All business entities", "Mandatory since 1 January 2020 under Resolution 522 — no revenue threshold on the obligation itself"], ["Self-employed persons", "Brought in from 1 January 2026 by Law No. ZRU-1108, on a par with legal entities and individual entrepreneurs"], ["B2G", "In scope"], ["B2C", "Not an electronic exchange in practice — see the note"], ["Only exemption found", "Transactions involving state secrets, where paper invoices in at least two copies remain permitted"]]', 'B2C scope is genuinely contested. Two international compliance sources list B2C as in scope, but Uzbek practitioner guidance states that for sales to individual consumers the seller prints and hands over the document, with the electronic loop not applying — retail being covered instead by online cash registers and QR-code payment duties. This page does not assert a B2C e-invoicing mandate.', NULL);

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔍 Why this page does not call Uzbekistan a clearance regime', NULL, NULL, 'A widely-circulated industry booklet describes Uzbekistan as a real-time clearance model in which the tax authority validates an invoice before it becomes legally final. The evidence points elsewhere, so this page describes it differently and explains why. The documented workflow runs seller to buyer, not seller to tax authority to buyer: the seller signs and transmits, then the buyer either certifies with their own signature or rejects with stated reasons, within a ten-day window after which the reject option disables. A buyer-acceptance clock is the signature of an exchange model. The 2026 risk system reinforces the point — it colours invoices rather than blocking them, and a flagged invoice is still validly issued, with the consequence falling on the buyer''s input VAT timing rather than the invoice''s validity. Under genuine pre-clearance, a failed invoice would not exist at all. There is a technical registration gate, and since 2026 a risk gate affecting VAT credit, but no fiscal approval gate suspending legal validity pending tax-authority sign-off. One further caveat, stated rather than buried: Appendix 2 to Resolution 489, which carries the operative procedure, could not be retrieved in full from a primary source in this research round, so the workflow description above rests on high-quality Uzbek specialist legal press rather than statutory text.');

INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 1, 'pills' FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'The exchange flow', 'An Uzbek electronic invoice moves through this sequence:', 'The decisive step is the buyer''s, not the tax authority''s — which is why this page describes Uzbekistan as centralised exchange rather than clearance.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Seller generates the invoice and signs it with an ETsP digital signature');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Transmitted through the state platform or a registered operator, with cross-operator routing via the state roaming operator');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'From 2026: scored for risk in real time and flagged, but not blocked');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 3, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Buyer certifies with their own signature, or rejects with stated reasons, within 10 days');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 4, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Digitally marked goods run a much shorter clock: confirm or reject within one calendar day, or the invoice auto-confirms');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚠️ The one quantified sanction: Tax Code Article 223', NULL, NULL, 'Uzbekistan does not publish a schedule of fixed-sum fines for e-invoicing format, transmission or acceptance failures. It has one quantified sanction, and it is a blunt one: 20% of the concealed or understated tax base under Tax Code Article 223, applied where goods or services are sold without an electronic invoice being issued, or where it is issued late. Enforcement began on 1 April 2021, postponed from 1 March, and from that date taxpayers could back-issue invoices for prior periods only by accepting the 20% charge. One nuance worth knowing: Uzbek tax practitioners argue Article 223 is a concealment provision rather than a documentary-formality provision, and so should not bite where an invoice is lawfully issued after month-end within the Resolution 489 deadlines, since no tax distortion arises. The 20% figure is corroborated by two independent Uzbek sources but the verbatim article text could not be read directly in this research round — lex.uz serves the Tax Code as a single very large document that would not render the article body.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🚦 Risk scoring: no fine, but your buyer pays for it in cash flow', NULL, NULL, 'The system that went live on 1 January 2026 under Article 4 of Presidential Decree UP-153 carries no penalty whatsoever, which makes it easy to underestimate. Every invoice is scored in real time against criteria the Tax Committee has deliberately kept secret — reportedly 48 of them, withheld on international experts'' advice to prevent gaming — and flagged red or green, with the status visible to the buyer. Two consequences follow. A taxpayer''s flagged invoices must not exceed 10% of all invoices issued in a reporting period. And input VAT on a flagged invoice becomes creditable only once the tax has actually been paid into the budget by the seller or the buyer, which in practice pushes buyers either to wait for their supplier or to pay the VAT themselves. The commercial effect is that your risk status becomes your customers'' problem, and therefore your problem. Pilot figures cited at launch: 281 enterprises, 5.9 trillion sum of invoices and 706 billion sum of VAT credit at issue over July to September 2025.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '💳 Adjacent 2026 penalties, and what we could not confirm', NULL, NULL, 'Law ZRU-1108 introduced two adjacent fines from 1 January 2026 that are not e-invoicing sanctions but sit close enough to be worth knowing: UZS 5,000,000 for trading without the mandatory electronic payment systems and QR codes, and UZS 20,000,000 for using another taxpayer''s QR codes. Both are sourced to a professional-services alert rather than statute. Four items from this research round are flagged rather than presented as settled fact: the verbatim text of Tax Code Article 223 could not be read; Appendix 2 to Resolution 489, the operative procedural regulation, could not be retrieved in full; the JSON invoice format rests on consistent secondary sourcing with no primary technical specification located; and the two soliq.uz web properties are robots-blocked to automated checking, so their current availability was not independently verified.');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Confirm you are issuing electronic invoices at all', 'The obligation is universal for business entities and has been since 1 January 2020 — there is no threshold to fall under and no phase-in remaining. If any part of your Uzbek trade is still on paper, that is a live exposure under Article 223, not a pending deadline.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Get an ETsP digital signature and choose a channel', 'You need a digital signature certificate from the tax authority''s key centre, and either a state-platform account or an account with one of the 27 registered operators. Because the state roaming operator routes between operators, choosing a private one does not cut you off from any counterparty.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Put the buyer''s acceptance window into your own process', 'The buyer has ten days to certify or reject, and once that lapses the reject option disables and you can no longer cancel. Invoices for digitally marked goods run on a one-day clock with automatic confirmation. Chase acceptance rather than assuming silence is agreement.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Treat your risk status as a commercial issue, not just a tax one', 'Since January 2026 your invoices are scored and flagged, and a flagged invoice defers your customer''s input VAT recovery. Monitor your flagged ratio against the 10% ceiling, and expect buyers to start asking about it. The criteria are secret by design, so supplier and counterparty due diligence is the only real control.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Review the pre-filled VAT return within five working days', 'From January 2026 the tax authority generates your VAT and turnover-tax returns from your own invoice feed, and you have five working days to correct them. Reconcile continuously rather than at filing time — by the time the return appears, the underlying data is already the authority''s version of events.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://gov.uz/en/soliq', 0 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'State Tax Committee — official portal (gov.uz)');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://lex.uz/en/docs/4386771', 1 FROM countries WHERE code = 'UZ';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'lex.uz — Resolution No. 522 of 25 June 2019, the founding instrument');
