-- Azerbaijan deep-dive content (English). A mature, universal B2B
-- e-invoicing regime (elektron qaimə-faktura / e-qaimə) in force
-- since 1 April 2017 and universal since 1 January 2018, with the
-- best primary-source footing of any country added in this recent
-- run: the State Tax Service publishes its own e-invoicing page, user
-- guide, sanctions booklet and annual amendments FAQ, all of which
-- were fetched directly.
--
-- Editorial position on the compliance model: three separate industry
-- sources give three incompatible labels for this system ("post-audit
-- reporting", "post-audit clearance", "clearance model"). Rather than
-- pick one, this page describes the mechanism precisely -- the State
-- Tax Service issues the invoice's series and number and records it
-- in AVIS at issuance, but does not substantively approve it, and the
-- buyer confirms within five days with silent auto-confirmation. That
-- is a registration-at-issuance CTC model. The disagreement is
-- surfaced in its own card rather than hidden.
--
-- Azerbaijan has a genuine, quantified, escalating penalty schedule
-- published by the tax authority itself, so this build uses a real
-- penalty table -- unlike Uzbekistan alongside it, which has only one
-- figure and gets narrative cards.
--
-- Flagged gaps stated on the page: no e-invoice volume statistics
-- appear to be published by Azerbaijan at all (no adoption figure is
-- invented here); no statutory e-invoice retention period could be
-- confirmed; B2G scope is inferred rather than primary-sourced; and
-- the advance-payment invoice's article number is cited differently
-- by two sources.

INSERT INTO deep_dive_pages (country_id, last_updated) SELECT id, '2026-08-10' FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_page_translations (country_id, lang, compliance_model, footer_disclaimer, timeline_intro, file_format_intro, scope_intro, steps_intro, penalties_intro, mandate_summary, mandate_summary_icon) SELECT id, 'en',
  'Centralised CTC, registration-at-issuance: the State Tax Service portal issues the invoice number and records the invoice in AVİS as it is issued, but does not substantively approve it — the buyer confirms within five days, with silent auto-confirmation',
  'This deep-dive page reflects Azerbaijani rules as published by the State Tax Service (taxes.gov.az) — including its e-qaimə page, 2024 user guide, 2025 financial-sanctions booklet and 2026 amendments FAQ — together with Cabinet of Ministers decision texts on nk.gov.az, as of 10 August 2026. The consolidated Tax Code is served as a single very large document that could not be retrieved in full, so nothing here quotes statutory text verbatim; each claim rests instead on an official State Tax Service publication or a Cabinet decision. Provided for general awareness, not legal or tax advice. Confirm current requirements with the State Tax Service or an Azerbaijani tax adviser before relying on this page.',
  'Azerbaijan''s e-qaimə mandate began on 1 April 2017 under Cabinet Decision No. 89, implementing Tax Code Article 71-1, and extended to all remaining taxpayers on 1 January 2018. In 2020 the separate electronic VAT invoice was abolished and merged into the e-qaimə. Cabinet Decision No. 26 of 2021 is the current rulebook. New timing rules took effect on 1 January 2026.',
  'A compliant e-qaimə is an XML document drawn up in Azerbaijani, signed with an enhanced electronic signature, transmitted to the registered recipient through the State Tax Service portal and recorded in AVİS, the Automated Tax Information System. The State Tax Service publishes the file-format specification, sample templates and a goods, works and services classification file. Signing uses ASAN İMZA, e-İmza or SİMA Token, producing .adoc or .edoc containers.',
  'The mandate covers essentially the whole B2B commercial-supply population, with no revenue threshold on the obligation itself since the 2018 phase. B2C is out of scope as a rule — retail runs on new-generation cash registers instead — though a consumer may request an e-invoice in a retail or catering transaction. Persons not registered as taxpayers cannot issue electronic invoices at all, and non-residents do not issue Azerbaijani e-invoices.',
  'If you supply goods, works or services in Azerbaijan as a registered taxpayer, you are already in scope and have been since 2018. The live work is the 1 January 2026 timing change, which is genuinely disruptive for anyone billing continuous services on a quarterly or annual cycle, and which most international compliance summaries have not yet picked up.',
  'Azerbaijan publishes a real, quantified and escalating penalty schedule for e-invoicing failures, and it bites both sides of the transaction: the seller for not issuing, and the buyer for holding goods without the required invoices.',
  'Azerbaijan has required electronic invoices since 1 April 2017, universal for all taxpayers from 1 January 2018, under Tax Code Article 71-1 and Cabinet Decision No. 89. Invoices are XML, drawn up in Azerbaijani, signed with an enhanced electronic signature and registered in the State Tax Service''s AVİS system, which assigns the series and number; the buyer then has five days to confirm, with silence counting as confirmation. From 1 January 2026 international transport and continuous services lost the general five-day invoicing window.',
  '🇦🇿'
FROM countries WHERE code = 'AZ';

INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '1 Apr 2017', 'The e-qaimə mandate begins, under Tax Code Article 71-1');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '9', 'Distinct electronic invoice types defined in the current rules');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '55,600', 'Active VAT payers as at 1 July 2025, up 5.2% over six months');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', 'AZN 4,622m', 'VAT collected in 2025 — about 28% of total tax revenue');
INSERT INTO deep_dive_stats (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_stat_translations (stat_id, lang, stat_value, stat_label) VALUES ((SELECT MAX(id) FROM deep_dive_stats), 'en', '18%', 'Standard VAT rate; registration threshold AZN 200,000');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Format & signature', '[["Invoice format", "XML — the State Tax Service publishes the file-format specification and sample templates"], ["Language", "Azerbaijani, required by Cabinet Decision No. 26"], ["Signature", "Enhanced electronic signature, mandatory in both online and offline modes"], ["Signing mechanisms", "ASAN İMZA (mobile SIM-based), e-İmza certificate, SİMA Token, or the ASAN DOC client"], ["Container formats", ".adoc and .edoc"], ["European standards", "Not EN 16931; Azerbaijan is not a Peppol authority"]]', 'The absence of EN 16931 and Peppol alignment is asserted by one secondary source and corroborated by silence elsewhere; no primary source addresses it either way.', NULL);
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '"Offline mode" does not mean what it sounds like', NULL, NULL, 'Azerbaijan offers two modes, and the naming misleads people into thinking one of them lets you issue invoices outside the state system. It does not. In online mode you authenticate to the İnternet Vergi İdarəsi portal with an enhanced electronic signature and compose and send in real time. In offline mode you download eFP — Elektron Faktura hazırlama Proqramı — compose and package invoices with no internet connection, sign the package, and then upload it to the portal, at which point the State Tax Service assigns the series and number and emails confirmation. eFP is a preparation tool, not an issuance channel. There is no legally valid e-qaimə that never touches the State Tax Service, because the invoice''s identity — its series and number — is state-issued rather than taxpayer-issued.');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 0 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', 'Scope, thresholds and deadlines', '[["B2B", "Mandatory and universal — all taxpayers, from 1 January 2018"], ["B2G", "In scope; public bodies are recipients like any registered taxpayer"], ["B2C", "Out of scope as a rule — retail runs on new-generation cash registers — but a consumer may request an e-invoice in a retail or catering transaction"], ["Goods", "Invoice on the same day as delivery"], ["Services", "Within 5 days — except the two 2026 carve-outs below"], ["International transport (from 2026)", "Before the transport begins"], ["Continuous services (from 2026)", "Monthly, at the start of each calendar month''s service, regardless of the billing cycle"], ["Advance payments", "On the day the advance is received"], ["Buyer confirmation", "5 days to confirm or return for correction; silence auto-confirms"], ["Corrections", "Until the 20th of the month following the reporting month"]]', 'B2G scope is inferred: it is asserted by two secondary sources and nowhere carved out, but no primary source explicitly names it.', NULL);

INSERT INTO deep_dive_lifecycle_cards (country_id, section, sort_order, display_style) SELECT id, 'scope_transmission', 1, 'pills' FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_lifecycle_card_translations (card_id, lang, title, intro_text, outro_text) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 'en', 'Registration at issuance', 'An e-qaimə moves through this sequence in both online and offline modes:', 'The State Tax Service is inside the transaction in real time — but it numbers and records the invoice rather than approving it, and the decisive validation is the buyer''s, or their silence.');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 0, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Seller composes the invoice in Azerbaijani, online in the portal or offline in eFP');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 1, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Signs with an enhanced electronic signature and submits to the State Tax Service portal');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 2, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'The system validates the counterparty''s VÖEN tax ID and auto-calculates VAT');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 3, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'The State Tax Service assigns the series and number and records the invoice in AVİS');
INSERT INTO deep_dive_lifecycle_statuses_v2 (card_id, sort_order, is_special) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_cards), 4, 0);
INSERT INTO deep_dive_lifecycle_status_v2_translations (status_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_lifecycle_statuses_v2), 'en', 'Buyer confirms, returns for correction, or does nothing — in which case it auto-confirms after 5 days');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'scope_transmission', 2 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔍 Three sources, three different labels for the same system', NULL, NULL, 'Anyone researching Azerbaijan will hit a naming problem, so it is worth stating openly. One compliance source calls this a post-audit reporting model and explicitly not pre-clearance. A second calls it "post-audit clearance", which is internally contradictory. A third calls it a clearance model. All three describe the same mechanism. This page does not adopt any of those labels, because clearance overstates what happens and post-audit understates it. What is actually true, from primary sources: the invoice cannot exist outside the state system, its identity is state-issued, it is recorded in AVİS at issuance, and the system validates the counterparty tax ID and computes VAT automatically — but no tax officer or rules engine approves the substance of the invoice as a condition of its validity, and a passive counterparty auto-approves it after five days. That is registration-at-issuance, and describing it in a sentence serves a reader better than forcing it into a one-word category. One further caution: a 2025 industry article claims Azerbaijan mandated e-invoicing in 2010 under Tax Code Article 2. That is wrong — Article 2 concerns the basis of tax legislation, and the operative provision is Article 71-1, inserted for 1 April 2017. It is named here so a future reader does not reintroduce it from a search result.');

INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 0 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '⚠️ Penalties escalate within a calendar year — and catch the buyer too', NULL, NULL, 'The figures in the table above come from the State Tax Service''s own 2025 booklet on financial sanctions. Three features are worth drawing out. First, the escalation is per calendar year and resets: 10% for the first instance, 20% for the second, 40% for the third and beyond. Second, Article 58.8.2 charges the buyer, not the seller, where goods are held without the required invoices — so both sides of a transaction carry exposure, which is unusual and makes counterparty compliance a commercial concern rather than someone else''s problem. Third, the State Tax Service has actively policed the B2B/B2C boundary: in July 2020 it publicly warned that wholesale transactions requiring an e-invoice were being disguised as retail point-of-sale sales by ringing implausibly large amounts through cash registers, and confirmed that Article 58.13 sanctions apply to that behaviour.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 1 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '📋 Two carve-outs, and one penalty that does not exist', NULL, NULL, 'Late submission of an advance-payment electronic invoice specifically does not attract a financial sanction, unlike ordinary electronic invoices — a genuine and slightly odd differentiator, sourced to Azerbaijani professional tax portals rather than statute. Separately, the 2017 State Tax Service presentation routes some e-invoice-related sanctions through Articles 194.2.3 and 194.2.8 at 5-10% for undisclosed funds, in an excise context. And one thing to state plainly rather than imply: no penalty could be sourced for merely late issuance of an ordinary electronic invoice, as distinct from non-issuance. The sanction articles are framed around supplying goods without an e-invoice. This page does not claim a late-filing penalty exists, because it could not be shown to.');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'penalties_related', 2 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json, note, body) VALUES ((SELECT MAX(id) FROM deep_dive_cards), 'en', '🔗 Related, but deliberately not shown as an e-invoicing milestone', NULL, NULL, 'From 23 August 2026, non-resident suppliers of electronic services to Azerbaijani consumers must register for VAT and charge 18% once annual Azerbaijan-source gross sales exceed the manat equivalent of USD 10,000, replacing a voluntary-registration and withholding arrangement. This is a VAT-registration obligation, not an e-invoicing one — non-residents do not issue Azerbaijani electronic invoices at all — so this tracker does not record it as a mandate milestone. It is worth knowing for a second reason: a professional-services alert in April 2025 forecast this change for 1 January 2026 with no threshold, noting the enabling legislation had not been adopted. The law that actually passed moved the date to August 2026 and added the USD 10,000 threshold. A useful reminder of why this site verifies against what was enacted rather than what was expected. Separately, from 1 January 2026 a new Article 155.1-1 applies a 0.5 coefficient to cashless point-of-sale receipts when testing the VAT registration threshold, so card turnover counts at half value — meaning a business can run roughly AZN 400,000 of card sales before crossing the AZN 200,000 line.');

INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Goods supplied without an e-invoice where one was required — 1st instance in a calendar year (Art. 58.13)', '10% of the sale value, plus AZN 100 per undocumented transaction', 'No cap published');
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Same failure — 2nd instance in the same calendar year (Art. 58.13)', '20% of the sale value, plus AZN 100 per undocumented transaction', 'No cap published');
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Same failure — 3rd and subsequent instances (Art. 58.13)', '40% of the sale value, plus AZN 100 per undocumented transaction', 'No cap published');
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Buyer holds goods without the required e-invoices or purchase documents (Art. 58.8.2)', '10% / 20% / 40% of the value of the goods, escalating on repeat within a calendar year', 'No cap published');
INSERT INTO deep_dive_penalty_rows (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_penalty_row_translations (row_id, lang, failure_description, fine_amount, annual_cap) VALUES ((SELECT MAX(id) FROM deep_dive_penalty_rows), 'en', 'Excisable goods moved between the taxpayer''s own facilities without an internal-movement e-invoice (Art. 58.13-1)', '10% / 20% / 40% of goods value, plus AZN 100 per undocumented transaction', 'No cap published');

INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 0 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Re-cut your invoicing cycle for continuous services', 'This is the most urgent item on the page. Since 1 January 2026, regularly and continuously supplied services — security, cleaning, utilities, subscriptions, and most SaaS — must be invoiced monthly, at the start of each month''s service, even where your contract bills quarterly or annually. If your ERP is still following a blanket five-day service rule, it is following a rule that no longer applies.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 1 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Move transport invoicing ahead of the transport', 'International transport services must now be invoiced by the time the transport begins, not within five days of it. For freight and logistics operators this reverses the usual order of operations and needs a process change, not just a date field.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 2 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Get an enhanced electronic signature and a portal account', 'You need ASAN İMZA, an e-İmza certificate or a SİMA Token, plus access to the İnternet Vergi İdarəsi portal. If you plan to prepare invoices in bulk offline, install eFP as well — but remember it prepares rather than issues.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 3 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Watch your inbound invoices, not just your outbound ones', 'Article 58.8.2 penalises the buyer for holding goods without the required invoices, at the same escalating 10/20/40% rates. Chase suppliers who have not issued, and use the five-day confirmation window actively — silence counts as confirmation, so an unreviewed invoice becomes an accepted one.');
INSERT INTO deep_dive_steps (country_id, sort_order) SELECT id, 4 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_step_translations (step_id, lang, title, description) VALUES ((SELECT MAX(id) FROM deep_dive_steps), 'en', 'Re-check your VAT registration position for 2026', 'New Article 155.1-1 counts cashless point-of-sale receipts at half value when testing the AZN 200,000 registration threshold, so a retail or services business can now run roughly AZN 400,000 of card turnover before mandatory registration. If you were close to the line, you may no longer be.');

INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.taxes.gov.az/en/page/elektron-qaime-faktura', 0 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'State Tax Service — the official e-qaimə page');
INSERT INTO deep_dive_portals (country_id, url, sort_order) SELECT id, 'https://www.e-taxes.gov.az', 1 FROM countries WHERE code = 'AZ';
INSERT INTO deep_dive_portal_translations (portal_id, lang, label) VALUES ((SELECT MAX(id) FROM deep_dive_portals), 'en', 'İnternet Vergi İdarəsi (e-Tax Account) — where invoices are actually issued (login required)');
