-- ================================================================
-- Every word the compliance guides say, in four languages.
-- ================================================================
--
-- Sixty-odd strings x 4 languages, plus the Resources menu entry that opens the
-- feature. Generated by migrations/gen_guides_strings.py, where the
-- English is written once and the four languages sit beside it -- a
-- layout chosen so that a dropped {0} placeholder or a missing language
-- is visible while editing rather than after deploying.
--
-- ---- WHY THESE ARE IN THE 'tracker' NAMESPACE -----------------------
--
-- Because that is the namespace generate_files.py rebuilds into
-- i18n/<lang>.json, and i18n/<lang>.json is the file both guides routes
-- read through authStrings(). A new namespace would have needed a new
-- file, a new fetch and a new failure mode, to hold sixty-two strings
-- that belong to the same site chrome as everything else in there.
--
-- ---- AND WHY EVERY ONE OF THEM ALSO HAS AN ENGLISH FALLBACK IN CODE --
--
-- authStrings() answers {} for a missing or malformed language file, and
-- both routes are written to keep working when it does. That is correct
-- runtime behaviour and it is ALSO how a translation gap ships unnoticed:
-- every page renders, in English, in all four languages, and nothing
-- looks broken. tests/guides-routes.mjs closes that by asserting the keys
-- exist in the checked-in files, and the standing invariant at the foot
-- of this file closes it in the database.

-- ---- the strings ----------------------------------------------------
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.back', 'en', '← Back to global tracker');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.back', 'de', '← Zurück zum globalen Tracker');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.back', 'fr', '← Retour au tracker mondial');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.back', 'es', '← Volver al rastreador global');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.cap', 'en', 'Annual cap');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.cap', 'de', 'Jahresobergrenze');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.cap', 'fr', 'Plafond annuel');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.cap', 'es', 'Límite anual');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.country', 'en', 'Jurisdiction');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.country', 'de', 'Rechtsraum');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.country', 'fr', 'Juridiction');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.country', 'es', 'Jurisdicción');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.failure', 'en', 'Failure');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.failure', 'de', 'Verstoß');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.failure', 'fr', 'Manquement');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.failure', 'es', 'Incumplimiento');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.fine', 'en', 'Fine');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.fine', 'de', 'Bußgeld');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.fine', 'fr', 'Amende');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.fine', 'es', 'Multa');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.model', 'en', 'Model');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.model', 'de', 'Modell');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.model', 'fr', 'Modèle');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.model', 'es', 'Modelo');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.next', 'en', 'Next dated obligation');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.next', 'de', 'Nächste datierte Pflicht');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.next', 'fr', 'Prochaine obligation datée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.next', 'es', 'Próxima obligación con fecha');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.what', 'en', 'What changes');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.what', 'de', 'Was sich ändert');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.what', 'fr', 'Ce qui change');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.col.what', 'es', 'Qué cambia');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.change', 'en', '← Change countries');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.change', 'de', '← Länder ändern');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.change', 'fr', '← Changer de pays');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.change', 'es', '← Cambiar países');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.convention', 'en', 'In the five headline tiles on each page, a status describes the obligation to ISSUE an e-invoice. Where a business must only be able to RECEIVE one, that is said in the line under the tile. NOT CONFIRMED means we could not source the fact, which is not the same as no requirement.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.convention', 'de', 'In den fünf Kennzahlen-Kacheln jeder Seite beschreibt ein Status die Pflicht, eine E-Rechnung AUSZUSTELLEN. Besteht lediglich eine Pflicht, eine solche EMPFANGEN zu können, steht das in der Zeile unter der Kachel. NICHT BESTÄTIGT heißt, dass wir die Angabe nicht belegen konnten — das ist nicht dasselbe wie keine Pflicht.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.convention', 'fr', 'Dans les cinq tuiles d''en-tête de chaque page, un statut décrit l''obligation d''ÉMETTRE une facture électronique. Lorsqu''une entreprise doit seulement pouvoir en RECEVOIR une, cela figure dans la ligne sous la tuile. NON CONFIRMÉ signifie que nous n''avons pas pu sourcer le fait, ce qui n''est pas la même chose qu''une absence d''obligation.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.convention', 'es', 'En las cinco casillas de cabecera de cada página, un estado describe la obligación de EMITIR una factura electrónica. Cuando la empresa solo debe poder RECIBIRLA, se indica en la línea bajo la casilla. NO CONFIRMADO significa que no pudimos documentar el dato, que no es lo mismo que no haber obligación.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.count', 'en', '{0} jurisdictions');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.count', 'de', '{0} Rechtsräume');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.count', 'fr', '{0} juridictions');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.count', 'es', '{0} jurisdicciones');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBack', 'en', '← Choose countries');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBack', 'de', '← Länder auswählen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBack', 'fr', '← Choisir des pays');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBack', 'es', '← Elegir países');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBody', 'en', 'No countries were named in that link, so there is nothing to build. Choose the markets you want and we will make the guide.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBody', 'de', 'In diesem Link waren keine Länder genannt, also gibt es nichts zu erstellen. Wählen Sie die gewünschten Märkte aus, und wir erstellen den Leitfaden.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBody', 'fr', 'Aucun pays n''était nommé dans ce lien, il n''y a donc rien à produire. Choisissez les marchés voulus et nous créerons le guide.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyBody', 'es', 'Ese enlace no nombraba ningún país, así que no hay nada que crear. Elija los mercados que quiera y haremos la guía.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyTitle', 'en', 'Nothing selected');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyTitle', 'de', 'Nichts ausgewählt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyTitle', 'fr', 'Aucune sélection');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.emptyTitle', 'es', 'Nada seleccionado');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.eyebrow', 'en', 'The E-Invoicing Compliance Corner');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.eyebrow', 'de', 'The E-Invoicing Compliance Corner');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.eyebrow', 'fr', 'The E-Invoicing Compliance Corner');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.eyebrow', 'es', 'The E-Invoicing Compliance Corner');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.full', 'en', 'Full detail: {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.full', 'de', 'Alle Einzelheiten: {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.full', 'fr', 'Détail complet : {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.full', 'es', 'Detalle completo: {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.generated', 'en', 'Generated {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.generated', 'de', 'Erstellt {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.generated', 'fr', 'Généré le {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.generated', 'es', 'Generado el {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.lede', 'en', '{0} jurisdictions, drawn from this site''s tracked mandate data on {1}. Each country follows on its own page. Dates are the published obligations as we hold them; the full detail for every country is on its deep dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.lede', 'de', '{0} Rechtsräume, entnommen den auf dieser Website verfolgten Mandatsdaten vom {1}. Jedes Land folgt auf einer eigenen Seite. Die Daten sind die veröffentlichten Pflichten in unserem Stand; alle Einzelheiten stehen im jeweiligen Deep Dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.lede', 'fr', '{0} juridictions, issues des données de mandats suivies par ce site au {1}. Chaque pays occupe sa propre page. Les dates correspondent aux obligations publiées telles que nous les détenons ; le détail complet figure dans le deep dive de chaque pays.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.lede', 'es', '{0} jurisdicciones, extraídas de los datos de mandatos que sigue este sitio a {1}. Cada país ocupa su propia página. Las fechas son las obligaciones publicadas según nuestros registros; el detalle completo está en el análisis a fondo de cada país.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.print', 'en', 'Print / save as PDF');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.print', 'de', 'Drucken / als PDF speichern');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.print', 'fr', 'Imprimer / enregistrer en PDF');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.print', 'es', 'Imprimir / guardar en PDF');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.title', 'en', 'Compliance guide');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.title', 'de', 'Compliance-Leitfaden');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.title', 'fr', 'Guide de conformité');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.doc.title', 'es', 'Guía de cumplimiento');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.more', 'en', '{0} further detail rows are on the full deep dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.more', 'de', '{0} weitere Detailzeilen stehen im vollständigen Deep Dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.more', 'fr', '{0} lignes de détail supplémentaires figurent dans le deep dive complet.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.more', 'es', '{0} filas de detalle adicionales están en el análisis a fondo completo.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.moreOne', 'en', '1 further detail row is on the full deep dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.moreOne', 'de', '1 weitere Detailzeile steht im vollständigen Deep Dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.moreOne', 'fr', '1 ligne de détail supplémentaire figure dans le deep dive complet.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.facts.moreOne', 'es', '1 fila de detalle adicional está en el análisis a fondo completo.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateBody', 'en', 'Subscribing is free. Pick the markets you care about and we will build a one-page briefing for each — the mandate as it stands, the dated timeline, the penalties, the key facts and what to do next — ready to print or save as a PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateBody', 'de', 'Das Abonnement ist kostenlos. Wählen Sie die Märkte aus, die für Sie zählen, und wir erstellen für jeden ein einseitiges Briefing — die Pflicht in ihrem aktuellen Stand, die datierte Zeitleiste, die Sanktionen, die wichtigsten Fakten und die nächsten Schritte — fertig zum Drucken oder als PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateBody', 'fr', 'L''abonnement est gratuit. Choisissez les marchés qui vous intéressent et nous produirons pour chacun une note d''une page — l''obligation en l''état, le calendrier daté, les sanctions, les faits essentiels et les prochaines étapes — prête à imprimer ou à enregistrer en PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateBody', 'es', 'Suscribirse es gratis. Elija los mercados que le interesan y crearemos un informe de una página para cada uno — el mandato tal como está, el calendario con fechas, las sanciones, los datos clave y los próximos pasos — listo para imprimir o guardar en PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateEyebrow', 'en', 'Subscriber tool');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateEyebrow', 'de', 'Abonnenten-Tool');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateEyebrow', 'fr', 'Outil pour abonnés');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateEyebrow', 'es', 'Herramienta para suscriptores');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSignedUp', 'en', 'Already subscribed?');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSignedUp', 'de', 'Bereits abonniert?');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSignedUp', 'fr', 'Déjà abonné ?');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSignedUp', 'es', '¿Ya está suscrito?');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSubscribe', 'en', 'Subscribe free');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSubscribe', 'de', 'Kostenlos abonnieren');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSubscribe', 'fr', 'S''abonner gratuitement');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateSubscribe', 'es', 'Suscribirse gratis');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateTitle', 'en', 'Compliance guides');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateTitle', 'de', 'Compliance-Leitfäden');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateTitle', 'fr', 'Guides de conformité');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.gateTitle', 'es', 'Guías de cumplimiento');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.active', 'en', 'ACTIVE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.active', 'de', 'AKTIV');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.active', 'fr', 'EN VIGUEUR');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.active', 'es', 'VIGENTE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.none', 'en', 'NO REQUIREMENT');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.none', 'de', 'KEINE PFLICHT');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.none', 'fr', 'AUCUNE OBLIGATION');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.none', 'es', 'SIN OBLIGACIÓN');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.varies', 'en', 'VARIES');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.varies', 'de', 'UNTERSCHIEDLICH');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.varies', 'fr', 'VARIABLE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.arch.varies', 'es', 'VARIABLE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.archiving', 'en', 'Archiving');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.archiving', 'de', 'Archivierung');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.archiving', 'fr', 'Archivage');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.archiving', 'es', 'Archivado');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2b', 'en', 'B2B e-invoicing');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2b', 'de', 'B2B-E-Rechnung');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2b', 'fr', 'Facturation B2B');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2b', 'es', 'Factura-e B2B');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2c', 'en', 'B2C e-invoicing');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2c', 'de', 'B2C-E-Rechnung');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2c', 'fr', 'Facturation B2C');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2c', 'es', 'Factura-e B2C');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2g', 'en', 'B2G e-invoicing');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2g', 'de', 'B2G-E-Rechnung');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2g', 'fr', 'Facturation B2G');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.b2g', 'es', 'Factura-e B2G');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.signature', 'en', 'Digital signature');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.signature', 'de', 'Digitale Signatur');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.signature', 'fr', 'Signature numérique');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.lbl.signature', 'es', 'Firma digital');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.none', 'en', 'NO MANDATE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.none', 'de', 'KEINE PFLICHT');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.none', 'fr', 'AUCUNE OBLIGATION');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.none', 'es', 'SIN MANDATO');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.planned', 'en', 'PLANNED');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.planned', 'de', 'GEPLANT');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.planned', 'fr', 'PRÉVU');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.planned', 'es', 'PREVISTO');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.conditional', 'en', 'CONDITIONAL');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.conditional', 'de', 'BEDINGT');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.conditional', 'fr', 'CONDITIONNELLE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.conditional', 'es', 'CONDICIONAL');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.not', 'en', 'NOT REQUIRED');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.not', 'de', 'NICHT ERFORDERLICH');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.not', 'fr', 'NON REQUISE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.not', 'es', 'NO OBLIGATORIA');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.required', 'en', 'REQUIRED');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.required', 'de', 'ERFORDERLICH');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.required', 'fr', 'REQUISE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.sig.required', 'es', 'OBLIGATORIA');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.unknown', 'en', 'NOT CONFIRMED');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.unknown', 'de', 'NICHT BESTÄTIGT');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.unknown', 'fr', 'NON CONFIRMÉ');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.unknown', 'es', 'NO CONFIRMADO');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.verified', 'en', 'Facts verified {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.verified', 'de', 'Fakten geprüft {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.verified', 'fr', 'Faits vérifiés le {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.verified', 'es', 'Datos verificados {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.voluntary', 'en', 'VOLUNTARY');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.voluntary', 'de', 'FREIWILLIG');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.voluntary', 'fr', 'VOLONTAIRE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.voluntary', 'es', 'VOLUNTARIO');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.yrs', 'en', 'yrs');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.yrs', 'de', 'J.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.yrs', 'fr', 'ans');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.hl.yrs', 'es', 'años');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.lbl.updated', 'en', 'Updated');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.lbl.updated', 'de', 'Aktualisiert');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.lbl.updated', 'fr', 'Mis à jour');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.lbl.updated', 'es', 'Actualizado');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pen.capsAll', 'en', 'Annual cap: {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pen.capsAll', 'de', 'Jahresobergrenze: {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pen.capsAll', 'fr', 'Plafond annuel : {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pen.capsAll', 'es', 'Límite anual: {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.all', 'en', 'Select all');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.all', 'de', 'Alle auswählen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.all', 'fr', 'Tout sélectionner');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.all', 'es', 'Seleccionar todo');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.build', 'en', 'Build my guide');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.build', 'de', 'Leitfaden erstellen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.build', 'fr', 'Créer mon guide');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.build', 'es', 'Crear mi guía');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.clear', 'en', 'Clear');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.clear', 'de', 'Leeren');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.clear', 'fr', 'Effacer');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.clear', 'es', 'Borrar');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countMany', 'en', '{0} countries selected');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countMany', 'de', '{0} Länder ausgewählt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countMany', 'fr', '{0} pays sélectionnés');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countMany', 'es', '{0} países seleccionados');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countNone', 'en', 'No countries selected');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countNone', 'de', 'Keine Länder ausgewählt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countNone', 'fr', 'Aucun pays sélectionné');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countNone', 'es', 'Ningún país seleccionado');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countOne', 'en', '1 country selected');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countOne', 'de', '1 Land ausgewählt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countOne', 'fr', '1 pays sélectionné');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.countOne', 'es', '1 país seleccionado');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.eyebrow', 'en', 'Subscriber tool');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.eyebrow', 'de', 'Abonnenten-Tool');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.eyebrow', 'fr', 'Outil pour abonnés');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.eyebrow', 'es', 'Herramienta para suscriptores');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.lede', 'en', 'Pick the markets you care about and we will build a one-page briefing for each: the mandate as it stands, the dated timeline, the penalties, the key facts and what to do next. It opens ready to print or save as a PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.lede', 'de', 'Wählen Sie die Märkte aus, die für Sie zählen, und wir erstellen für jeden ein einseitiges Briefing: die Pflicht in ihrem aktuellen Stand, die datierte Zeitleiste, die Sanktionen, die wichtigsten Fakten und die nächsten Schritte. Es öffnet sich fertig zum Drucken oder als PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.lede', 'fr', 'Choisissez les marchés qui vous intéressent et nous produirons pour chacun une note d''une page : l''obligation en l''état, le calendrier daté, les sanctions, les faits essentiels et les prochaines étapes. Elle s''ouvre prête à imprimer ou à enregistrer en PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.lede', 'es', 'Elija los mercados que le interesan y crearemos un informe de una página para cada uno: el mandato tal como está, el calendario con fechas, las sanciones, los datos clave y los próximos pasos. Se abre listo para imprimir o guardar en PDF.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.savedNote', 'en', 'The countries you follow are ticked already and marked with a star. Add or remove any you like.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.savedNote', 'de', 'Die von Ihnen verfolgten Länder sind bereits angehakt und mit einem Stern versehen. Sie können beliebig ergänzen oder entfernen.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.savedNote', 'fr', 'Les pays que vous suivez sont déjà cochés et marqués d''une étoile. Ajoutez-en ou retirez-en à votre convenance.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.savedNote', 'es', 'Los países que sigue ya están marcados y señalados con una estrella. Añada o quite los que quiera.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.title', 'en', 'Compliance guides');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.title', 'de', 'Compliance-Leitfäden');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.title', 'fr', 'Guides de conformité');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pick.title', 'es', 'Guías de cumplimiento');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.complex', 'en', 'Complex');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.complex', 'de', 'Komplex');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.complex', 'fr', 'Complexe');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.complex', 'es', 'Complejo');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.eu', 'en', 'EU');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.eu', 'de', 'EU');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.eu', 'fr', 'UE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.eu', 'es', 'UE');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.inforce', 'en', 'In force');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.inforce', 'de', 'In Kraft');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.inforce', 'fr', 'En vigueur');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.inforce', 'es', 'En vigor');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.nodate', 'en', 'No dated step');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.nodate', 'de', 'Kein datierter Schritt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.nodate', 'fr', 'Aucune étape datée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.pill.nodate', 'es', 'Sin paso con fecha');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.facts', 'en', 'Key facts');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.facts', 'de', 'Wichtigste Fakten');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.facts', 'fr', 'Faits essentiels');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.facts', 'es', 'Datos clave');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.news', 'en', 'From the newsletter');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.news', 'de', 'Aus dem Newsletter');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.news', 'fr', 'Extrait de la newsletter');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.news', 'es', 'Del boletín');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.penalties', 'en', 'Penalties');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.penalties', 'de', 'Sanktionen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.penalties', 'fr', 'Sanctions');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.penalties', 'es', 'Sanciones');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.sources', 'en', 'Where this is tracked');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.sources', 'de', 'Wo wir das verfolgen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.sources', 'fr', 'Où nous suivons cela');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.sources', 'es', 'Dónde lo seguimos');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.steps', 'en', 'What to do');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.steps', 'de', 'Was zu tun ist');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.steps', 'fr', 'Que faire');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.steps', 'es', 'Qué hacer');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.timeline', 'en', 'Compliance timeline');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.timeline', 'de', 'Compliance-Zeitleiste');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.timeline', 'fr', 'Calendrier de conformité');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.sec.timeline', 'es', 'Calendario de cumplimiento');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.tl.hidden', 'en', '{0} earlier milestones are on the full deep dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.tl.hidden', 'de', '{0} frühere Meilensteine stehen im vollständigen Deep Dive.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.tl.hidden', 'fr', '{0} jalons antérieurs figurent dans le deep dive complet.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'guides.tl.hidden', 'es', '{0} hitos anteriores están en el análisis a fondo completo.');

-- ---- and the way in ------------------------------------------------
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.guides', 'en', 'Compliance guides');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.guides', 'de', 'Compliance-Leitfäden');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.guides', 'fr', 'Guides de conformité');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.guides', 'es', 'Guías de cumplimiento');

-- ---- what this migration claims it did ------------------------------
-- ASSERT: SELECT count(*) FROM translations WHERE namespace = 'tracker' AND key LIKE 'guides.%' = 268
-- ASSERT: SELECT count(*) FROM translations WHERE namespace = 'tracker' AND key = 'menu.guides' = 4
--
-- FOUR LANGUAGES OR NONE, per key. The count above would also be
-- satisfied by that many English strings and nothing else, which is exactly the
-- gap that ships unnoticed: every page renders, in English, in four
-- languages, and nobody sees a fault. This one cannot be satisfied that
-- way.
-- ASSERT ALWAYS: SELECT count(*) FROM (SELECT key FROM translations WHERE namespace = 'tracker' AND key LIKE 'guides.%' GROUP BY key HAVING count(DISTINCT lang) != 4) = 0

