-- ================================================================
-- The headline notes go back to house length, before they are
-- translated three more times.
-- ================================================================
--
-- Dan, 23 August 2026: "try to be concise with translations, and
-- ensure we still meet our 1-page per country rule."
--
-- Measuring first turned up something to fix before translating.
-- Across the 350 notes the median is 78 characters and the 90th
-- percentile is 118. Thirty run past the p90 -- and TWENTY-SIX OF
-- THOSE TWENTY-SEVEN were written today, in 620, 621 and 622. The
-- research sweep produced better sourcing and worse prose.
--
-- That matters more once the notes exist in four languages. German
-- runs 20-30% longer than English, so a 190-character note becomes
-- about 240 -- and the one-page-per-country rule is enforced in the
-- READER'S BROWSER, by GUIDE_FIT_SCRIPT shrinking the page until it
-- fits. Long notes do not overflow. They quietly make every other
-- line on that country's page smaller.
--
-- All 30 are rewritten to 125 characters or fewer. Nothing a reader
-- acts on is dropped: every date, instrument number and live caveat
-- survives, including the two "this may prove to be conditional"
-- flags on Korea and Vietnam.
--
-- Generated by gen_tighten_notes.py -- edit that, not this.
-- ================================================================

UPDATE country_headline_fact_translations SET b2g_note = 'Suppliers invoice via CanadaBuys (SAP Ariba), most electronically, but none must: CRA accepts paper, no penalty.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Canada');
UPDATE country_headline_fact_translations SET b2b_note = 'Decree 386/2020 bound the first 134 firms from 15 Nov 2020; universal 15 Dec 2022. Apr 2023 is a buyer deduction rule.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Egypt');
UPDATE country_headline_fact_translations SET b2g_note = 'No separate B2G rule; each supplier''s own wave applies, first Nov 2020. Government pays only on e-invoice from Dec 2022.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Egypt');
UPDATE country_headline_fact_translations SET signature_note = 'E-invoices carry the issuer''s e-seal; ETA''s e-receipt FAQ says a receipt needs none, so it depends on the document.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Egypt');
UPDATE country_headline_fact_translations SET b2c_note = 'PER-03/PJ/2022 arts.25-27: a retail PKP issues a simplified invoice, which may be a till slip, so no electronic form.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Indonesia');
UPDATE country_headline_fact_translations SET archiving_note = 'Four years from the latest of tax-period end, filing or assessment; since 2023 the JoFotara record replaces paper.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Jordan');
UPDATE country_headline_fact_translations SET b2c_note = 'All establishments, companies and individuals bar narrow turnover exemptions; no official B2C start date is published.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Jordan');
UPDATE country_headline_fact_translations SET b2g_note = 'Regulation 2/2025 makes departments buy from JoFotara-compliant suppliers from 1 Apr 2025; the duty dates from 13/2023.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Jordan');
UPDATE country_headline_fact_translations SET signature_note = 'ISTD''s integration guide specifies UBL 2.1 with client-ID authentication and no signing step; a spec that omits it.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Jordan');
UPDATE country_headline_fact_translations SET archiving_note = 'Accounting Law s.28: invoices are ''other source documents'', kept at least five years. Registers and payroll are ten.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Latvia');
UPDATE country_headline_fact_translations SET b2g_note = 'Accounting Law s.11(14) obliges the SUPPLIER to draw up a structured e-invoice; in force for budget bodies 1 Jan 2025.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Latvia');
UPDATE country_headline_fact_translations SET archiving_note = 'VAT Act (Cap.406) art.48: at least six years from the end of the year, extendable for specified records.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Malta');
UPDATE country_headline_fact_translations SET b2g_note = 'The Ministry for Finance states suppliers need not invoice public bodies electronically; government must only accept.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Malta');
UPDATE country_headline_fact_translations SET archiving_note = 'art.15(2): ten years from year-end for private entities; public-sector e-invoices are kept permanently in the SEF.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Serbia');
UPDATE country_headline_fact_translations SET b2g_note = 'Law on E-Invoicing art.24(5): private to public from 1 May 2022; public to private from 1 Jul 2022.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Serbia');
UPDATE country_headline_fact_translations SET signature_note = 'No signature or seal in the law; art.15(6) assigns authenticity and integrity to the format and to storage.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Serbia');
UPDATE country_headline_fact_translations SET archiving_note = 'Five years, still secondary: NTS says invoices sent to it need no separate keeping, but Korean hosts refused us.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'South Korea');
UPDATE country_headline_fact_translations SET b2b_note = 'NTS: all corporations, plus sole traders above KRW 80m prior-year supply, joining each 1 July. The 2011 start is unread.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'South Korea');
UPDATE country_headline_fact_translations SET b2c_note = 'No tax invoice to consumers; cash receipts or card slips instead. Whether a mandatory cash receipt counts is unsettled.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'South Korea');
UPDATE country_headline_fact_translations SET b2g_note = 'No separate B2G regime: the duty follows the supplier''s own status under VAT Act art.32, whoever the buyer is.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'South Korea');
UPDATE country_headline_fact_translations SET signature_note = 'NTS requires a joint certificate to issue; the Decree''s ARS and agent channels may not, so possibly conditional.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'South Korea');
UPDATE country_headline_fact_translations SET b2g_note = 'Authorities must accept compliant e-invoices since Apr 2019 (SI 2019/624; Procurement Act 2023 s67); no issuing duty.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United Kingdom');
UPDATE country_headline_fact_translations SET archiving_note = 'The regulation puts 10 yrs on the platform operator and is silent on the taxpayer; our 5 yrs cited an unattributable host.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Uzbekistan');
UPDATE country_headline_fact_translations SET b2c_note = 'Para 18 covers sales to individuals; the seller signs its own e-invoice. Cash sales with a fiscal receipt are carved out.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Uzbekistan');
UPDATE country_headline_fact_translations SET b2g_note = 'Cabinet Resolution 522 of 25 Jun 2019: voluntary from 1 Jul 2019, compulsory for all business entities 1 Jan 2020.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Uzbekistan');
UPDATE country_headline_fact_translations SET signature_note = 'Paras 14, 16 and 18 make the signature constitutive: the seller signs, the buyer signs to accept or rejects with reasons.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Uzbekistan');
UPDATE country_headline_fact_translations SET archiving_note = 'Ten years under Accounting Law art.41, still secondary: the tax department blocks us and the Gazette withholds the text.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Vietnam');
UPDATE country_headline_fact_translations SET b2c_note = 'In scope since Jul 2022; Decree 70/2025 widened the cash-register variant from 1 Jun 2025 to households over VND 1bn.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Vietnam');
UPDATE country_headline_fact_translations SET b2g_note = 'No separate B2G track. Decree 123/2020 in force 1 Jul 2022 per the Gazette, which serves only a PDF it will not release.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Vietnam');
UPDATE country_headline_fact_translations SET signature_note = 'Seller signature required, but Decree 123 art.10 lists invoices needing none, cash-register among them; may be conditional.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Vietnam');

-- ---- what this migration claims it did ------------------------------

-- ASSERT: SELECT count(*) FROM country_headline_fact_translations WHERE lang = 'en' AND (length(b2g_note) > 125 OR length(b2b_note) > 125 OR length(b2c_note) > 125 OR length(archiving_note) > 125 OR length(signature_note) > 125) = 0

-- A NOTE IS A LINE UNDER A TILE, not a paragraph. The cap is the
-- corpus's own 90th percentile, rounded up, and it is a standing rule
-- rather than a one-off tidy: the next long note pushes a country's
-- whole page smaller in the reader's browser, silently.
-- ASSERT ALWAYS: SELECT count(*) FROM country_headline_fact_translations WHERE length(b2g_note) > 150 OR length(b2b_note) > 150 OR length(b2c_note) > 150 OR length(archiving_note) > 150 OR length(signature_note) > 150 = 0

