-- ================================================================
-- e-Reporting, seventy countries.
-- ================================================================
--
-- Generated by gen_ereporting.py from ereporting_research.json,
-- ereporting_decisions.py and ereporting_systems.py. Edit those.
--
--   ACTIVE        39
--   NO MANDATE    23
--   ON REQUEST    5
--   PLANNED       2
--   NOT CONFIRMED 1
--
-- Cadence among the active: monthly 20, varies 6, near_real_time 5, real_time 3, annual 2, daily 2, quarterly 1.
--
-- ---- WHAT THIS SET SAYS THAT THE MANDATE BOX DOES NOT ---------------
--
-- Only four of the active countries use SAF-T. The rest run on about
-- thirty different regimes, and that is the whole argument for the box:
-- a reader who has satisfied the e-invoicing mandate in Greece, Hungary
-- or Spain still has myDATA, Online Szamla or the SII to build, and
-- nothing on the page told them so before now.
--
-- The clearance countries are the ones to read carefully. Italy, Mexico
-- and Poland all clear invoices AND report separately; Chile, Kenya and
-- Malaysia clear invoices and do not. That distinction is invisible from
-- the mandate box alone, and getting it wrong is the difference between
-- a project that ships and one that discovers a second system in UAT.
--
-- ---- 17 NOTES WERE REWRITTEN, AND WHY THAT IS NOT TIDYING ---------
--
-- The research wrote each note before the decisions were applied. Where
-- a decision changed what the box says, the note that came with it
-- became wrong -- Pakistan's said "transmitted to FBR in real time"
-- against a box now reading MONTHLY, and Indonesia's said "no separate
-- e-reporting" against a box now reading ACTIVE. Every rewrite is in
-- gen_ereporting.py's NOTES dict where it can be read next to the row it
-- replaces. The other 70 keep the researcher's own words, which are
-- better than anything written from a summary because the researcher had
-- the source open.
--
-- Longest note is 115 characters (Estonia); the cap is 125, set by
-- 623 from the corpus's own 90th percentile.
-- ================================================================


-- ---- the facts -----------------------------------------------------

UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'Libro IVA Digital',
  ereporting_date = '2019-10-01',
  ereporting_source = 'https://servicios.infoleg.gob.ar/infolegInternet/anexos/410000-414999/413495/norma.htm'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Argentina');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.vatupdate.com/2025/11/16/331691/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Australia');
UPDATE country_headline_facts SET
  ereporting_status = 'on_request',
  ereporting_frequency = 'on_request',
  ereporting_system = 'SAF-T AT',
  ereporting_date = NULL,
  ereporting_source = 'https://www.bmf.gv.at/themen/steuern/fristen-verfahren/bundesabgabenordnung/standard-audit-file-tax.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Austria');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = '2019-02-14',
  ereporting_source = 'https://e-kassa.gov.az/az/faydali/en-cox-verilen-suallar'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Azerbaijan');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.vatupdate.com/2026/08/10/bahrain-e-invoicing-e-reporting-country-booklet/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Bahrain');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'annual',
  ereporting_system = 'Client listing',
  ereporting_date = NULL,
  ereporting_source = 'https://news.belgium.be/fr/instauration-de-lobligation-de-rapportage-electronique-des-donnees-de-facturation'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Belgium');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'SPED',
  ereporting_date = '2009-01-01',
  ereporting_source = 'https://www.gov.br/sped/pt-br/assuntos/escrituracoes-digitais/efd-contribuicoes'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Brazil');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'SAF-T',
  ereporting_date = '2026-01-01',
  ereporting_source = 'https://www.pwc.bg/bg/publications/tax-and-legal-alerts-2025/SAF-T-legislation.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Bulgaria');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = '2025-05-31',
  ereporting_source = 'https://www.revenuquebec.ca/en/businesses/sector-specific-measures/mandatory-billing/mandatory-billing-sending-information/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Canada');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.vatupdate.com/2026/06/30/chiles-e-invoicing-framework-understanding-rcv-dtes-and-invoice-acceptance-rules/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Chile');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.vatupdate.com/2025/12/10/briefing-document-podcast-e-invoicing-and-e-reporting-in-china/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'China');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'annual',
  ereporting_system = 'Info. exogena',
  ereporting_date = NULL,
  ereporting_source = 'https://normograma.dian.gov.co/dian/compilacion/docs/resolucion_dian_0162_2023.htm'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Colombia');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'D-270',
  ereporting_date = '2026-01-01',
  ereporting_source = 'https://www.hacienda.go.cr/docs/CP14-2026.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Costa Rica');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'real_time',
  ereporting_system = 'Fiskalizacija 2.0',
  ereporting_date = '2026-01-01',
  ereporting_source = 'https://porezna-uprava.gov.hr/hr/izdavanje-i-primanje-eracuna-i-fiskalizacija-eracuna/8047'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Croatia');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108880/eInvoicing+in+Cyprus'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Cyprus');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'Kontrolni hlaseni',
  ereporting_date = '2016-01-01',
  ereporting_source = 'https://financnisprava.gov.cz/en/taxes/vat-control-statement'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Czech Republic');
UPDATE country_headline_facts SET
  ereporting_status = 'on_request',
  ereporting_frequency = 'on_request',
  ereporting_system = 'SAF-T',
  ereporting_date = NULL,
  ereporting_source = 'https://erhvervsstyrelsen.dk/bogfoering'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Denmark');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = '606/607/608/609',
  ereporting_date = NULL,
  ereporting_source = 'https://dgii.gov.do/legislacion/normasGenerales/Documents/NG%20sobre%20Comprobantes%20Fiscales/Norma07-18.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Dominican Republic');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'ATS',
  ereporting_date = '2012-01-14',
  ereporting_source = 'https://www.sri.gob.ec/o/sri-portlet-biblioteca-alfresco-internet/descargar/72d717c2-88ed-47b7-baba-50b87b7198b7/Ficha%20Tecnica%20Transaccional%20Simplificado%20ATS.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Ecuador');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = '2022-10-01',
  ereporting_source = 'https://www.eta.gov.eg/en/node/373'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Egypt');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'KMD INF',
  ereporting_date = NULL,
  ereporting_source = 'https://www.emta.ee/en/business-client/taxes-and-payment/value-added-tax/filing-vat-returns-and-reports'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Estonia');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.vero.fi/en/businesses-and-corporations/taxes-and-charges/vat/when-to-file-and-pay/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Finland');
UPDATE country_headline_facts SET
  ereporting_status = 'planned',
  ereporting_frequency = 'varies',
  ereporting_system = 'e-reporting',
  ereporting_date = '2026-09-01',
  ereporting_source = 'https://www.impots.gouv.fr/international-professionnel/le-reporting-pour-les-entreprises-etrangeres-sans-etablissement-stable'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'France');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.bundesfinanzministerium.de/Content/DE/FAQ/e-rechnung.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Germany');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'real_time',
  ereporting_system = 'myDATA',
  ereporting_date = '2021-07-01',
  ereporting_source = 'https://www.aade.gr/sites/default/files/2025-08/a_1112_2025.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Greece');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'real_time',
  ereporting_system = 'Online Szamla',
  ereporting_date = '2021-01-04',
  ereporting_source = 'https://nav.gov.hu/pfile/file?path=%2Fen%2Ftaxation%2FBooklets%2F14---useful-information-for-start-ups-starters-in-the-vat-regime'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Hungary');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.skatturinn.is/atvinnurekstur/virdisaukaskattur/uppgjor-og-skil/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Iceland');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'GSTR-1',
  ereporting_date = NULL,
  ereporting_source = 'https://tutorial.gst.gov.in/userguide/returns/GSTR_1.htm'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'India');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'SPT Masa PPN',
  ereporting_date = '2025-01-01',
  ereporting_source = 'https://ortax.org/ini-bentuk-spt-masa-ppn-di-aplikasi-coretax'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Indonesia');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = '2028-11-01',
  ereporting_source = 'https://www.revenue.ie/en/vat/documents/implementation-einvoicing.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Ireland');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'PCN874',
  ereporting_date = '2025-09-01',
  ereporting_source = 'https://www.amir-cpa.net/post/%D7%93%D7%99%D7%95%D7%95%D7%97-%D7%9E%D7%A4%D7%95%D7%A8%D7%98-%D7%9C%D7%9E%D7%A2-%D7%9E-%D7%9C%D7%A2%D7%A6%D7%9E%D7%90%D7%99-%D7%9E-2026-%D7%97%D7%95%D7%91%D7%95%D7%AA-%D7%95%D7%94%D7%A7%D7%9C%D7%95%D7%AA'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Israel');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'varies',
  ereporting_system = 'SdI cross-border',
  ereporting_date = '2019-07-01',
  ereporting_source = 'https://www.fiscoetasse.com/normativa-prassi/12802-trasmissione-telematica-corrispettivi-volume-d-affari-superiore-a-400-000-euro.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Italy');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.fiscal-requirements.com/countries/56-japan'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Japan');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.vatupdate.com/2026/03/20/briefing-document-podcast-e-invoicing-e-reporting-in-jordan/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Jordan');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'quarterly',
  ereporting_system = 'VAT registers',
  ereporting_date = '2018-01-01',
  ereporting_source = 'https://pro1c.kz/articles/nalog-na-dobavlennuyu-stoimost-nds/postrochnoe-zapolnenie-deklaratsii-po-nds-za-1-kvartal-2017-goda/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Kazakhstan');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'VAT3 schedules',
  ereporting_date = '2024-03-01',
  ereporting_source = 'https://www.kra.go.ke/images/publications/FAQS-FOR-THE-VAT-AUTOPOPULATED-RETURN-090724.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Kenya');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'near_real_time',
  ereporting_system = 'e-rekins to VID',
  ereporting_date = '2026-01-01',
  ereporting_source = 'https://likumi.lv/ta/id/365040-kartiba-kada-organize-un-isteno-strukturetu-elektronisko-rekinu-apriti-un-kada-strukturetu-elektronisko-rekinu-datus-iesniedz-valsts-ienemumu-dienestam'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Latvia');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'i.SAF',
  ereporting_date = NULL,
  ereporting_source = 'https://www.vmi.lt/evmi/pvm-s%C4%85skait%C5%B3-fakt%C5%ABr%C5%B3-registr%C5%B3-duomen%C5%B3-teikimas-ir-tikslinimas'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Lithuania');
UPDATE country_headline_facts SET
  ereporting_status = 'on_request',
  ereporting_frequency = 'on_request',
  ereporting_system = 'FAIA',
  ereporting_date = NULL,
  ereporting_source = 'https://pfi.public.lu/fr/professionnel/tva/faia.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Luxembourg');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.vatupdate.com/2025/10/19/briefing-document-comprehensive-overview-of-e-invoicing-compliance-in-malaysia/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Malaysia');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108894/eInvoicing+in+Malta'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Malta');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'Cont. Electronica',
  ereporting_date = '2015-01-01',
  ereporting_source = 'https://www.taxcom.mx/blog/cumplimiento-fiscal/contabilidad-electronica-sat-guia-2026/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Mexico');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467108895/eInvoicing+in+The+Netherlands'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Netherlands');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.ird.govt.nz/managing-my-tax/record-keeping/einvoicing'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'New Zealand');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = '2025-11-01',
  ereporting_source = 'https://www.vatupdate.com/2026/06/16/nigeria-to-make-second-wave-of-e-invoicing-mandatory-from-july-2026/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Nigeria');
UPDATE country_headline_facts SET
  ereporting_status = 'on_request',
  ereporting_frequency = 'on_request',
  ereporting_system = 'SAF-T',
  ereporting_date = NULL,
  ereporting_source = 'https://www.skatteetaten.no/en/business-and-organisation/start-and-run/best-practices-accounting-and-cash-register-systems/saf-t-financial/questions-and-answers---saf-t-financial/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Norway');
UPDATE country_headline_facts SET
  ereporting_status = 'unknown',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.e-invoice.app/blog/oman-decision-189-2026-e-invoicing-dates'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Oman');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'STR-7 Annex A/C',
  ereporting_date = NULL,
  ereporting_source = 'https://download1.fbr.gov.pk/Docs/201936173129323STFE-Return-16-17.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Pakistan');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'SIRE',
  ereporting_date = '2023-07-01',
  ereporting_source = 'https://cpe.sunat.gob.pe/node/139'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Peru');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'varies',
  ereporting_system = 'eSales + SLSP',
  ereporting_date = NULL,
  ereporting_source = 'https://knowledgebase.ptabcp.com/pos-crm-and-esales-compliance/'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Philippines');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'JPK_V7M',
  ereporting_date = '2020-10-01',
  ereporting_source = 'https://www.podatki.gov.pl/podatki-firmowe/jednolity-plik-kontrolny/jpk_vat-z-deklaracja'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Poland');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'SAF-T (PT)',
  ereporting_date = NULL,
  ereporting_source = 'https://info.portaldasfinancas.gov.pt/pt/apoio_contribuinte/questoes_frequentes/pages/faqs-00978.aspx'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Portugal');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.fiscal-requirements.com/news/5769-qatar-vat-status'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Qatar');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'D406 SAF-T',
  ereporting_date = '2022-01-01',
  ereporting_source = 'https://static.anaf.ro/static/10/Anaf/legislatie/OPANAF_1783_2021.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Romania');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'near_real_time',
  ereporting_system = 'FATOORA',
  ereporting_date = '2023-01-01',
  ereporting_source = 'https://zatca.gov.sa/en/E-Invoicing/Introduction/Guidelines/Documents/E-Invoicing_Detailed__Guideline.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Saudi Arabia');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'varies',
  ereporting_system = 'SEF VAT records',
  ereporting_date = '2023-01-01',
  ereporting_source = 'https://www.paragraf.rs/propisi/zakon-o-elektronskom-fakturisanju.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Serbia');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'varies',
  ereporting_system = 'InvoiceNow',
  ereporting_date = '2025-11-01',
  ereporting_source = 'https://www.iras.gov.sg/media/docs/default-source/uploadedfiles/gst/frequently-asked-questions-for-gst-invoicenow-requirement.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Singapore');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'varies',
  ereporting_system = 'Kontrolny vykaz',
  ereporting_date = '2014-01-01',
  ereporting_source = 'https://www.financnasprava.sk/_img/pfsedit/Dokumenty_PFS/Profesionalna_zona/Dane/Metodicke_pokyny/Nepriame_dane/2014/2014_03_07_mp_kv_dph.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Slovakia');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = '2016-01-02',
  ereporting_source = 'https://www.fu.gov.si/fileadmin/Internet/Nadzor/Podrocja/Davcne_blagajne_in_VKR/Opis/Davcne_blagajne_-_splosno_nadzor_in_prekrski.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Slovenia');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'near_real_time',
  ereporting_system = 'e-Tax Invoice',
  ereporting_date = '2011-01-01',
  ereporting_source = 'https://www.britacom.org/images/tlzt_02_04Slides%20of%20Korea.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'South Korea');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'near_real_time',
  ereporting_system = 'SII',
  ereporting_date = '2017-07-01',
  ereporting_source = 'https://sede.agenciatributaria.gob.es/Sede/iva/suministro-inmediato-informacion/informacion-general.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Spain');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.skatteverket.se/foretag/internationellt/transaktionsbaseradrapporteringochefakturering.4.386bd4b919276cc86c42b3f.html'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Sweden');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'near_real_time',
  ereporting_system = 'eGUI upload',
  ereporting_date = '2025-01-01',
  ereporting_source = 'https://www.dot.gov.tw/singlehtml/ch26?cntId=92588e5cc8a344c4ac560de582214ea0'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Taiwan');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'daily',
  ereporting_system = 'e-Arsiv raporu',
  ereporting_date = '2020-01-01',
  ereporting_source = 'https://cdn.gib.gov.tr/api/gibportal-file/file/getFile?objectKey=MEVZUAT_TEBLIGLER%2FUNIVERSAL%2F2026%2FMEVZUAT_TEBLIGLER_2026_VukTeb509_Guncel.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Turkey');
UPDATE country_headline_facts SET
  ereporting_status = 'planned',
  ereporting_frequency = NULL,
  ereporting_system = 'FTA reporting',
  ereporting_date = '2027-01-01',
  ereporting_source = 'https://mof.gov.ae/wp-content/uploads/2025/09/Ministerial-Decision-no.-243-of-2025-on-the-Electronic-Invoicing-System.pdf'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'United Arab Emirates');
UPDATE country_headline_facts SET
  ereporting_status = 'no_mandate',
  ereporting_frequency = NULL,
  ereporting_system = NULL,
  ereporting_date = NULL,
  ereporting_source = 'https://www.gov.uk/government/consultations/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector/outcome/promoting-electronic-invoicing-across-uk-businesses-and-the-public-sector-consultation-response'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'United Kingdom');
UPDATE country_headline_facts SET
  ereporting_status = 'on_request',
  ereporting_frequency = 'on_request',
  ereporting_system = 'Rev. Proc. 98-25',
  ereporting_date = NULL,
  ereporting_source = 'https://www.irs.gov/businesses/automated-records'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'United States');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'daily',
  ereporting_system = 'Reporte diario',
  ereporting_date = '2012-05-08',
  ereporting_source = 'https://www.impo.com.uy/bases/resoluciones-dgi-interes-general/798-2012/1'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Uruguay');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'monthly',
  ereporting_system = 'VAT annexes 4/5',
  ereporting_date = '2019-01-21',
  ereporting_source = 'https://buxgalter.uz/nds3/kak_zapolnit_otchetnost_po_nds_pri_obshcheustanovlennom_poryadke_ego_rascheta'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Uzbekistan');
UPDATE country_headline_facts SET
  ereporting_status = 'active',
  ereporting_frequency = 'varies',
  ereporting_system = 'Form 01/TH-HDDT',
  ereporting_date = '2022-07-01',
  ereporting_source = 'https://vanbanphapluat.co/decree-123-2020-nd-cp-prescribing-invoices-and-records'
 WHERE country_id = (SELECT id FROM countries WHERE name_en = 'Vietnam');

-- ---- the notes, English; the other three follow in 629 -------------

UPDATE country_headline_fact_translations SET ereporting_note = 'Libro de IVA Digital: monthly ledger filed by day 15; from Dec 2025 VAT-exempt subjects only'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Argentina');
UPDATE country_headline_fact_translations SET ereporting_note = 'No transaction reporting to the ATO; Peppol e-invoicing voluntary in B2B; BAS is a summary return'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Australia');
UPDATE country_headline_fact_translations SET ereporting_note = 'No periodic filing; SAF-T AT is produced only on request in an audit, under BAO sections 131(3), 132(3)'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Austria');
UPDATE country_headline_fact_translations SET ereporting_note = 'No ledger or invoice reporting; e-kassa sends retail receipts to the STS and e-qaime is clearance'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Azerbaijan');
UPDATE country_headline_fact_translations SET ereporting_note = 'No transaction reporting to the NBR; VAT returns only; e-invoicing framework still unpublished'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Bahrain');
UPDATE country_headline_fact_translations SET ereporting_note = 'Annual client listing of VAT-registered customers via Intervat by 31 March; e-reporting proposed for 2028'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Belgium');
UPDATE country_headline_fact_translations SET ereporting_note = 'SPED: EFD ICMS/IPI and EFD-Contribuicoes filed monthly, separate from NF-e clearance'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Brazil');
UPDATE country_headline_fact_translations SET ereporting_note = 'SAF-T to the NRA: monthly by the 14th, fixed assets by 30 June; phased by size 2026 to 2030'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Bulgaria');
UPDATE country_headline_fact_translations SET ereporting_note = 'No federal duty. Quebec''s WEB-SRM covers restaurants, bars, catering, accommodation and taxis only'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Canada');
UPDATE country_headline_fact_translations SET ereporting_note = 'DTE/boleta clearance only; RCV ledger is compiled by the SII from DTEs, no separate filing duty found'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Chile');
UPDATE country_headline_fact_translations SET ereporting_note = 'Fully digitalised e-fapiao is cleared at issuance; no separate periodic or ledger reporting duty found'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'China');
UPDATE country_headline_fact_translations SET ereporting_note = 'Annual informacion exogena to DIAN: third-party sales, purchase and VAT listings; no real-time system'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Colombia');
UPDATE country_headline_fact_translations SET ereporting_note = 'D-270 monthly listing of clients, suppliers and specific expenses not covered by an electronic voucher'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Costa Rica');
UPDATE country_headline_fact_translations SET ereporting_note = 'Invoice data fiscalised to Porezna uprava as a step separate from the e-invoice; B2C in real time'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Croatia');
UPDATE country_headline_fact_translations SET ereporting_note = 'No transaction reporting, SAF-T or real-time system; periodic VAT return and VIES only'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Cyprus');
UPDATE country_headline_fact_translations SET ereporting_note = 'kontrolni hlaseni: invoice-level VAT listing, monthly by the 25th; quarterly for some individuals'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Czech Republic');
UPDATE country_headline_fact_translations SET ereporting_note = 'No periodic transmission; digital bookkeeping with SAF-T export produced for authorities on request'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Denmark');
UPDATE country_headline_fact_translations SET ereporting_note = 'Formats 606/607/608/609: monthly purchase, sales and cancelled-voucher listings to DGII by the 15th'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Dominican Republic');
UPDATE country_headline_fact_translations SET ereporting_note = 'ATS: monthly XML of purchases, sales, exports and withholdings filed with SRI by RUC ninth digit'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Ecuador');
UPDATE country_headline_fact_translations SET ereporting_note = 'No ledger reporting. The e-Receipt system carries B2C till data; the e-invoice itself is clearance'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Egypt');
UPDATE country_headline_fact_translations SET ereporting_note = 'KMD INF annex to the monthly VAT return lists sales and purchase invoices from EUR 1,000 per partner; due the 20th.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Estonia');
UPDATE country_headline_fact_translations SET ereporting_note = 'No transaction-level reporting; VAT return and EU recapitulative statement only; no SAF-T.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Finland');
UPDATE country_headline_fact_translations SET ereporting_note = 'E-reporting of B2C, non-established B2B and payment data: 1 Sep 2026 large/ETI, 1 Sep 2027 others.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'France');
UPDATE country_headline_fact_translations SET ereporting_note = 'No duty in force; the BMF plans a Meldesystem beside B2B e-invoicing but has named no date'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Germany');
UPDATE country_headline_fact_translations SET ereporting_note = 'myDATA: invoice summaries and classifications transmitted to AADE in real time; mandatory since 2021.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Greece');
UPDATE country_headline_fact_translations SET ereporting_note = 'Online Szamla: invoice data to NAV immediately from invoicing software, 4 days for handwritten invoices.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hungary');
UPDATE country_headline_fact_translations SET ereporting_note = 'No transaction data transmission; VAT return every two months; cash-register records kept, not filed.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Iceland');
UPDATE country_headline_fact_translations SET ereporting_note = 'GSTR-1: invoice-level outward supplies to GSTN monthly by the 11th; quarterly by the 13th under QRMP.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'India');
UPDATE country_headline_fact_translations SET ereporting_note = 'SPT Masa PPN annexes list every tax invoice issued and received, monthly; auto-posted from e-Faktur since 2025'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Indonesia');
UPDATE country_headline_fact_translations SET ereporting_note = 'Nothing in force. Revenue''s roadmap gives Nov 2028 and Nov 2029, with no enacted instrument and no day'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Ireland');
UPDATE country_headline_fact_translations SET ereporting_note = 'PCN874 detailed VAT report: invoice-level sales and purchases, monthly, by the 23rd'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Israel');
UPDATE country_headline_fact_translations SET ereporting_note = 'Cross-border invoice data goes to SdI since Jul 2022; corrispettivi telematici is the daily till limb'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Italy');
UPDATE country_headline_fact_translations SET ereporting_note = 'No SAF-T and no transaction-level reporting to the NTA; Qualified Invoice System governs content, not transmission'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Japan');
UPDATE country_headline_fact_translations SET ereporting_note = 'JoFotara clears invoices before issuance; no separate periodic reporting duty to the ISTD identified'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Jordan');
UPDATE country_headline_fact_translations SET ereporting_note = 'Invoice registers file with the quarterly VAT return, but ESF electronic invoices are excluded, so paper only'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Kazakhstan');
UPDATE country_headline_fact_translations SET ereporting_note = 'The iTax VAT3 return carries invoice-level sales and purchase schedules, pre-filled from eTIMS since Mar 2024'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Kenya');
UPDATE country_headline_fact_translations SET ereporting_note = 'E-invoice data filed to VID within 5 working days; B2G since 2026, B2B from 2028'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Latvia');
UPDATE country_headline_fact_translations SET ereporting_note = 'i.SAF monthly VAT invoice registers, filed by the 20th of the following month'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Lithuania');
UPDATE country_headline_fact_translations SET ereporting_note = 'No periodic transaction reporting; FAIA audit file only on AED request'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Luxembourg');
UPDATE country_headline_fact_translations SET ereporting_note = 'MyInvois is clearance; the consolidated B2C e-invoice is filed in that platform, not a separate report.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Malaysia');
UPDATE country_headline_fact_translations SET ereporting_note = 'No transaction reporting to the tax authority; e-invoicing and real-time reporting under study, no dates set'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Malta');
UPDATE country_headline_fact_translations SET ereporting_note = 'Monthly balanza de comprobación XML to SAT under CFF art. 28 fr. IV; DIOT filed monthly'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Mexico');
UPDATE country_headline_fact_translations SET ereporting_note = 'No periodic transaction reporting; XAF audit file is a de-facto software format, not a legal filing'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Netherlands');
UPDATE country_headline_fact_translations SET ereporting_note = 'No data reporting to Inland Revenue; Peppol e-invoicing is a B2B exchange and IR receives nothing'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'New Zealand');
UPDATE country_headline_fact_translations SET ereporting_note = 'No ledger or invoice-data reporting; the B2C receipt feed and MBS clearance both sit in the mandate box'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Nigeria');
UPDATE country_headline_fact_translations SET ereporting_note = 'SAF-T Financial is produced on request in an audit only; no scheduled transmission of ledger data'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Norway');
UPDATE country_headline_fact_translations SET ereporting_note = 'Position unsettled: sources conflict on dates and on whether the OTA data flow is a separate report.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Oman');
UPDATE country_headline_fact_translations SET ereporting_note = 'STR-7 Annexure A and C list every purchase and sale invoice; Annexure C is due on the 10th, the return on the 18th'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Pakistan');
UPDATE country_headline_fact_translations SET ereporting_note = 'SIRE: electronic sales (RVIE) and purchase (RCE) registers filed monthly to SUNAT'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Peru');
UPDATE country_headline_fact_translations SET ereporting_note = 'eSales files machine-level monthly sales; the quarterly Summary Lists of Sales and Purchases are invoice-level'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Philippines');
UPDATE country_headline_fact_translations SET ereporting_note = 'JPK_V7M merges the VAT return and the sales/purchase ledger, filed monthly by the 25th; KSeF is separate'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Poland');
UPDATE country_headline_fact_translations SET ereporting_note = 'SAF-T (PT) de faturação: invoice data communicated to the AT by the 5th of the following month'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Portugal');
UPDATE country_headline_fact_translations SET ereporting_note = 'No VAT and no transaction reporting duty; e-invoicing law approved by Cabinet May 2026, not yet gazetted'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Qatar');
UPDATE country_headline_fact_translations SET ereporting_note = 'D406 SAF-T filed monthly or quarterly by the last day of the following period; small taxpayers since 2025'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Romania');
UPDATE country_headline_fact_translations SET ereporting_note = 'Simplified B2C invoices reported to ZATCA within 24 hours; standard invoices are cleared, not reported'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Saudi Arabia');
UPDATE country_headline_fact_translations SET ereporting_note = 'VAT calculation recorded in the SEF by the 12th of the following month; e-fiskalizacija covers retail'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Serbia');
UPDATE country_headline_fact_translations SET ereporting_note = 'GST InvoiceNow: invoice data sent to IRAS via Peppol; phased from Nov 2025, all GST registrants by 2031'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Singapore');
UPDATE country_headline_fact_translations SET ereporting_note = 'Kontrolny vykaz lists every transaction and files with each VAT return; eKasa is the separate till feed'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Slovakia');
UPDATE country_headline_fact_translations SET ereporting_note = 'No SAF-T and no ledger filing; davcne blagajne fiscalise cash invoices with FURS in real time'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Slovenia');
UPDATE country_headline_fact_translations SET ereporting_note = 'e-Tax invoices transmitted to the NTS by the day after issuance; no separate periodic audit file'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'South Korea');
UPDATE country_headline_fact_translations SET ereporting_note = 'SII: invoice records supplied to AEAT within 4 working days; large taxpayers, VAT groups, REDEME.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Spain');
UPDATE country_headline_fact_translations SET ereporting_note = 'No transaction reporting duty; Skatteverket cites EU cross-border digital reporting from 2030.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Sweden');
UPDATE country_headline_fact_translations SET ereporting_note = 'eGUI data uploaded to the MOF platform within 2 days (non-business buyer) or 7 days; VAT Act art. 32-1.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Taiwan');
UPDATE country_headline_fact_translations SET ereporting_note = 'e-Arsiv invoice data reported to GIB by 23:59 next day; monthly e-Defter berat; e-Fatura excluded.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Turkey');
UPDATE country_headline_fact_translations SET ereporting_note = 'MD 243/2025 art. 6(6): invoices must be reported to the FTA; phase 1 go-live 1 Jan 2027.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United Arab Emirates');
UPDATE country_headline_fact_translations SET ereporting_note = 'No reporting duty; e-invoicing mandated from 2029, real-time reporting explicitly deferred.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United Kingdom');
UPDATE country_headline_fact_translations SET ereporting_note = 'No reporting duty. Machine-sensible records under Rev. Proc. 98-25 are produced to the IRS on request'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'United States');
UPDATE country_headline_fact_translations SET ereporting_note = 'CFE issuers send DGI a consolidated daily report within 18 hours of the next business day.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Uruguay');
UPDATE country_headline_fact_translations SET ereporting_note = 'VAT return annexes 4 and 5 register every purchase and sale invoice, monthly by the 20th; pre-filled from ESF data'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Uzbekistan');
UPDATE country_headline_fact_translations SET ereporting_note = 'Uncoded e-invoices: data sent to the GDT - summary 01/TH-HDDT with the VAT return, or same day by sector.'
 WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Vietnam');

-- ---- what this migration claims it did ------------------------------

-- ASSERT: SELECT count(*) FROM country_headline_facts WHERE ereporting_status = 'active' = 39
-- ASSERT: SELECT count(*) FROM country_headline_facts WHERE ereporting_status = 'no_mandate' = 23
-- ASSERT: SELECT count(*) FROM country_headline_facts WHERE ereporting_status = 'on_request' = 5
-- ASSERT: SELECT count(*) FROM country_headline_facts WHERE ereporting_status = 'planned' = 2

-- 'unknown' IS A REAL ANSWER HERE, NOT AN UNFILLED ROW -- and this file
-- originally tried to prove every row was decided by counting the ones
-- that are NOT unknown. That assertion failed on its first run, at 69
-- against 70, and it was right to: 626 leaves every row at the DEFAULT
-- of 'unknown', so the status column cannot tell a decided unknown from
-- an untouched row. Oman is deliberately NOT CONFIRMED -- the OTA's own
-- FAQs give a four-phase timetable from Aug 2026 while the only
-- published account of Decision 189/2026 gives two dates in 2027, and
-- the decision's text has not been released.
-- ASSERT: SELECT count(*) FROM country_headline_facts WHERE ereporting_status = 'unknown' = 1

-- THE NOTE IS WHAT PROVES ALL SEVENTY WERE LOOKED AT, because 626 sets
-- no note and this migration sets one for every country including Oman.
-- A blank note on a card reading NO MANDATE is the difference between
-- "we checked and there is none" and "we did not look".
-- ASSERT: SELECT count(*) FROM country_headline_fact_translations WHERE lang = 'en' AND ifnull(ereporting_note,'') != '' = 70

-- ---- and what must stay true afterwards -----------------------------

-- NO NOTE OUTRUNS THE CARD. Same 125-character house length as the other
-- five, for the same reason: the guide's one-page rule is enforced in
-- the reader's browser by shrinking, so a long note never overflows --
-- it quietly makes every other line on that country's page smaller.
-- ASSERT ALWAYS: SELECT count(*) FROM country_headline_fact_translations WHERE length(ereporting_note) > 150 = 0

-- A COUNTRY WITH NOTHING TO REPORT SHOWS NO CADENCE. Otherwise the card
-- prints "MONTHLY" above a status saying there is no duty.
-- ASSERT ALWAYS: SELECT count(*) FROM country_headline_facts WHERE ereporting_status IN ('no_mandate','voluntary','unknown') AND ereporting_frequency IS NOT NULL = 0

-- AND A LIVE DUTY IS SOURCED. The whole set was researched in one pass;
-- an unsourced row added later is the one that would slip through.
-- ASSERT ALWAYS: SELECT count(*) FROM country_headline_facts WHERE ereporting_status IN ('active','on_request','planned') AND ifnull(ereporting_source,'') = '' = 0

