-- ================================================================
-- The specification register: twenty jurisdictions.
-- ================================================================
--
-- Generated by gen_spec_register.py -- edit that, not this.
--
-- Researched 24 August 2026 against primary sources. A field is NULL
-- where it could not be confirmed from one; nothing here is inferred
-- from a vendor summary.
--
-- WHAT THE RESEARCH CHANGED. The feasibility study called Germany,
-- France, Denmark, the Netherlands, Turkey and the Peppol countries
-- 'tier 1 -- clone and run'. Two of those are wrong and this file is
-- the correction: France's Factur-X package asks for an email address,
-- and Turkey's GIB blocks automated access altogether so nothing about
-- it could be verified.
--
-- ONLY TWO OF TWENTY publish machine-readable artefacts under a NAMED
-- licence -- Germany (Apache-2.0) and the Netherlands (MIT). Croatia is
-- third and still does not qualify: an explicit permission to reuse,
-- with no licence name on it. The rest publish openly on terms that are
-- unstated, unknown, or -- for every Peppol jurisdiction -- explicitly
-- restrictive: the artefacts download without a login and then forbid
-- redistribution without OpenPeppol's consent. 'Open' and 'licensed'
-- are different questions and this table answers them separately.
--
-- FOUR ROWS CARRY NOTHING MACHINE-READABLE AT ALL, and they are the
-- most useful rows here. Romania's RO_CIUS exists only as prose in an ordinance.
-- Ireland's does not exist yet. Turkey's and Portugal's publishers
-- refuse us. Saying so precisely, with the reason, is what a register
-- can do that a validator cannot.
-- ================================================================


-- ---- the register ---------------------------------------------------
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'PINT A-NZ', '1.1.2', 'ubl', 'yes',
         'OpenPeppol AISBL / ATO', NULL, 'restrictive', 'open',
         '2025-11-21', NULL, 'https://docs.peppol.eu/poac/aunz/pint-aunz/release-notes/', NULL, '2026-08-24'
    FROM countries WHERE code = 'AU';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'Peppol BIS Billing 3.0', '3.0.21', 'ubl', 'yes',
         'OpenPeppol AISBL', NULL, 'restrictive', 'open',
         '2026-05-20', '2026-08-17', 'https://docs.peppol.eu/poacc/billing/3.0/release-notes/', NULL, '2026-08-24'
    FROM countries WHERE code = 'BE';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'XRechnung', '3.0.2', 'multiple', 'yes',
         'KoSIT (Koordinierungsstelle für IT-Standards)', 'Apache-2.0', 'named', 'open',
         '2024-06-20', NULL, 'https://xeinkauf.de/xrechnung/versionen-und-bundles/', NULL, '2026-08-24'
    FROM countries WHERE code = 'DE';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'OIOUBL 2.1', '1.17.1', 'ubl', 'yes',
         'Erhvervsstyrelsen', NULL, 'unknown', 'open',
         '2026-02-19', '2026-05-15', 'https://nemhandel.dk/oioubl-21-schematron-version-1171', 'https://oioubl.nemhandel.dk/validation', '2026-08-24'
    FROM countries WHERE code = 'DK';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'partial', 'Facturae / Veri*Factu', 'Facturae 3.2.2', 'multiple', 'no',
         'AEAT / Ministerio de Economía', NULL, 'unstated', 'open',
         NULL, NULL, NULL, NULL, '2026-08-24'
    FROM countries WHERE code = 'ES';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'partial', 'Finvoice', '3.0', 'national_xml', 'yes',
         'Finanssiala ry (a private banking association)', NULL, 'unstated', 'open',
         '2025-09-16', NULL, 'https://www.finanssiala.fi/en/topics/finvoice-standard/', NULL, '2026-08-24'
    FROM countries WHERE code = 'FI';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'partial', 'Spécifications externes B2B / Factur-X', '3.2', 'multiple', 'yes',
         'DGFiP / AIFE, with Factur-X by FNFE-MPE', NULL, 'unstated', 'registration',
         '2026-04-30', NULL, 'https://www.impots.gouv.fr/specifications-externes-b2b', NULL, '2026-08-24'
    FROM countries WHERE code = 'FR';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'eRačun (Fiskalizacija 2.0)', '1.3', 'multiple', 'yes',
         'Porezna uprava', NULL, 'permissive_unnamed', 'open',
         '2025-06-20', NULL, 'https://porezna.gov.hr/fiskalizacija/bezgotovinski-racuni/bezgotovinski-racuni-novosti', NULL, '2026-08-24'
    FROM countries WHERE code = 'HR';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'not_yet', NULL, NULL, 'unknown', 'yes',
         'Revenue Commissioners', NULL, 'unknown', 'none',
         NULL, NULL, NULL, NULL, '2026-08-24'
    FROM countries WHERE code = 'IE';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'partial', 'FatturaPA', '1.9.1', 'national_xml', 'no',
         'Agenzia delle Entrate', NULL, 'unstated', 'open',
         NULL, '2026-05-15', NULL, NULL, '2026-08-24'
    FROM countries WHERE code = 'IT';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'JP PINT', '1.1.2', 'ubl', 'yes',
         'OpenPeppol AISBL / Digital Agency', NULL, 'restrictive', 'open',
         '2025-11-17', NULL, 'https://docs.peppol.eu/poac/jp/pint-jp/release-notes/', NULL, '2026-08-24'
    FROM countries WHERE code = 'JP';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'SI-UBL 2.0 (NLCIUS)', '2.0.3.13', 'ubl', 'yes',
         'Nederlandse Peppolautoriteit / Logius', 'MIT', 'named', 'open',
         '2025-11-27', '2026-02-23', 'https://www.peppolautoriteit.nl/actueel/nieuws', NULL, '2026-08-24'
    FROM countries WHERE code = 'NL';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'EHF Billing 3.0', '3.0.3', 'ubl', 'yes',
         'DFØ (Direktoratet for forvaltning og økonomistyring)', NULL, 'unknown', 'open',
         '2026-08-13', NULL, 'https://anskaffelser.dev/postaward/g3/spec/current/billing-3.0/norway/', 'https://anskaffelser.dev/service/validator/', '2026-08-24'
    FROM countries WHERE code = 'NO';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'PINT A-NZ', '1.1.2', 'ubl', 'yes',
         'OpenPeppol AISBL / MBIE', NULL, 'restrictive', 'open',
         '2025-11-21', NULL, 'https://docs.peppol.eu/poac/aunz/pint-aunz/release-notes/', NULL, '2026-08-24'
    FROM countries WHERE code = 'NZ';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'partial', 'KSeF FA(3)', 'v1-0', 'national_xml', 'no',
         'Ministerstwo Finansów', NULL, 'unstated', 'open',
         NULL, NULL, NULL, NULL, '2026-08-24'
    FROM countries WHERE code = 'PL';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'unreachable', 'CIUS-PT', '1.5.2', 'ubl', 'yes',
         'eSPap', NULL, 'unknown', 'blocked',
         '2021-07-22', NULL, NULL, NULL, '2026-08-24'
    FROM countries WHERE code = 'PT';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'unpublished', 'RO_CIUS', '1.0.1', 'ubl', 'yes',
         'Ministerul Finanțelor / ANAF', NULL, 'unstated', 'open',
         '2021-11-05', NULL, NULL, NULL, '2026-08-24'
    FROM countries WHERE code = 'RO';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'Peppol BIS Billing 3.0', '3.0.21', 'ubl', 'yes',
         'OpenPeppol AISBL', NULL, 'restrictive', 'open',
         '2026-05-20', '2026-08-17', 'https://docs.peppol.eu/poacc/billing/3.0/release-notes/', NULL, '2026-08-24'
    FROM countries WHERE code = 'SE';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'published', 'PINT SG', '1.4.0', 'ubl', 'yes',
         'OpenPeppol AISBL / IMDA', NULL, 'restrictive', 'open',
         '2025-11-28', NULL, 'https://docs.peppol.eu/poac/sg/pint-sg/specialized-release-notes/', NULL, '2026-08-24'
    FROM countries WHERE code = 'SG';
INSERT OR REPLACE INTO country_spec (country_id, capture_status, format_name,
    format_version, syntax, is_en16931, governance, licence, licence_status,
    access, version_released, mandatory_from, changelog_url, validator_url,
    last_verified)
  SELECT id, 'unreachable', 'UBL-TR', NULL, 'national_xml', 'no',
         'Gelir İdaresi Başkanlığı (GİB)', NULL, 'unknown', 'blocked',
         NULL, NULL, NULL, NULL, '2026-08-24'
    FROM countries WHERE code = 'TR';

-- ---- the artefacts --------------------------------------------------
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://docs.peppol.eu/poac/aunz/pint-aunz/resources.zip', 'OpenPeppol AISBL', 0
    FROM countries WHERE code = 'AU';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://docs.peppol.eu/poac/aunz/pint-aunz/bis/', 'OpenPeppol AISBL', 1
    FROM countries WHERE code = 'AU';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'schematron', 'https://github.com/OpenPEPPOL/peppol-bis-invoice-3', 'OpenPeppol AISBL', 0
    FROM countries WHERE code = 'BE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://docs.peppol.eu/poacc/billing/3.0/bis/', 'OpenPeppol AISBL', 1
    FROM countries WHERE code = 'BE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'schematron', 'https://github.com/itplr-kosit/xrechnung-schematron', 'KoSIT', 0
    FROM countries WHERE code = 'DE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'sdk', 'https://github.com/itplr-kosit/validator', 'KoSIT', 1
    FROM countries WHERE code = 'DE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'testsuite', 'https://github.com/itplr-kosit/xrechnung-testsuite', 'KoSIT', 2
    FROM countries WHERE code = 'DE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://xeinkauf.de/xrechnung/', 'KoSIT / xeinkauf.de', 3
    FROM countries WHERE code = 'DE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'schematron', 'https://nemhandel.dk/oioubl-21-schematron-version-1171', 'Erhvervsstyrelsen', 0
    FROM countries WHERE code = 'DK';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://www.facturae.gob.es/formato/Paginas/version-3-2.aspx', 'Ministerio de Economía', 0
    FROM countries WHERE code = 'ES';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://www.finanssiala.fi/en/topics/finvoice-standard/', 'Finanssiala ry', 0
    FROM countries WHERE code = 'FI';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://file.finanssiala.fi/finvoice/Finvoice_3_0_implementation_guidelines.pdf', 'Finanssiala ry', 1
    FROM countries WHERE code = 'FI';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://www.impots.gouv.fr/specifications-externes-b2b', 'DGFiP / AIFE', 0
    FROM countries WHERE code = 'FR';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'schematron', 'https://fnfe-mpe.org/factur-x/factur-x_en/', 'FNFE-MPE', 1
    FROM countries WHERE code = 'FR';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://porezna.gov.hr/fiskalizacija/api/dokumenti/175', 'Porezna uprava', 0
    FROM countries WHERE code = 'HR';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://porezna.gov.hr/fiskalizacija/api/dokumenti/187', 'Porezna uprava', 1
    FROM countries WHERE code = 'HR';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://fiskalizacija2.hr/wp-content/uploads/2025/07/Tehnicka_specifikacija_Fiskalizacija_eRacuna_i_eIzvjestavanje.pdf', 'Porezna uprava', 2
    FROM countries WHERE code = 'HR';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://www.fatturapa.gov.it/it/norme-e-regole/documentazione-fattura-elettronica/formato-fatturapa/', 'Agenzia delle Entrate', 0
    FROM countries WHERE code = 'IT';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://docs.peppol.eu/poac/jp/pint-jp/resources.zip', 'OpenPeppol AISBL', 0
    FROM countries WHERE code = 'JP';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://docs.peppol.eu/poac/jp/pint-jp/bis/', 'OpenPeppol AISBL', 1
    FROM countries WHERE code = 'JP';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'schematron', 'https://github.com/peppolautoriteit-nl/validation', 'Nederlandse Peppolautoriteit', 0
    FROM countries WHERE code = 'NL';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'repo', 'https://github.com/peppolautoriteit-nl/publications', 'Nederlandse Peppolautoriteit', 1
    FROM countries WHERE code = 'NL';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'schematron', 'https://github.com/anskaffelser/ehf-postaward-g3', 'DFØ', 0
    FROM countries WHERE code = 'NO';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'sdk', 'https://github.com/anskaffelser/vefa-validator', 'DFØ', 1
    FROM countries WHERE code = 'NO';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://anskaffelser.dev/postaward/g3/spec/current/billing-3.0/norway/', 'DFØ', 2
    FROM countries WHERE code = 'NO';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://docs.peppol.eu/poac/aunz/pint-aunz/resources.zip', 'OpenPeppol AISBL', 0
    FROM countries WHERE code = 'NZ';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://docs.peppol.eu/poac/aunz/pint-aunz/bis/', 'OpenPeppol AISBL', 1
    FROM countries WHERE code = 'NZ';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://ksef.podatki.gov.pl/media/ukrllh1e/schemat_fa_vat-3-_v1-0.xsd', 'Ministerstwo Finansów', 0
    FROM countries WHERE code = 'PL';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://mfinante.gov.ro/documents/35673/1120722/ordin1366_MO10658112021.pdf', 'Ministerul Finanțelor', 0
    FROM countries WHERE code = 'RO';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'schematron', 'https://github.com/OpenPEPPOL/peppol-bis-invoice-3', 'OpenPeppol AISBL', 0
    FROM countries WHERE code = 'SE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://docs.peppol.eu/poacc/billing/3.0/bis/', 'OpenPeppol AISBL', 1
    FROM countries WHERE code = 'SE';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'xsd', 'https://docs.peppol.eu/poac/sg/pint-sg/resources.zip', 'OpenPeppol AISBL', 0
    FROM countries WHERE code = 'SG';
INSERT INTO country_spec_artefacts (country_id, kind, url, publisher, sort_order)
  SELECT id, 'spec_pdf', 'https://docs.peppol.eu/poac/sg/pint-sg/bis/', 'OpenPeppol AISBL', 1
    FROM countries WHERE code = 'SG';

-- ---- what the artefacts do not tell you -----------------------------
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'The ATO''s scope rules — which entities are covered, and the 30% and automation targets — are procurement policy stated in guidance pages, not encoded in the artefacts.'
    FROM countries WHERE code = 'AU';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Die Geltungsregeln der ATO – welche Stellen erfasst sind, die 30-%- und Automatisierungsziele – sind Beschaffungspolitik in Leitfäden, nicht in den Artefakten kodiert.'
    FROM countries WHERE code = 'AU';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Les règles de périmètre de l''ATO — entités concernées, cibles de 30 % et d''automatisation — relèvent de la politique d''achat publiée en guides, non des artefacts.'
    FROM countries WHERE code = 'AU';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Las reglas de alcance de la ATO —qué entidades y los objetivos del 30% y de automatización— son política de compras publicada en guías, no van en los artefactos.'
    FROM countries WHERE code = 'AU';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'The royal decree lets two parties agree an alternative EN 16931 format between them. The audit criteria for that opt-out are legal text, not part of any artefact.'
    FROM countries WHERE code = 'BE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Der Königliche Erlass erlaubt zwei Parteien, ein alternatives EN-16931-Format zu vereinbaren. Die Prüfkriterien dafür sind Rechtstext, kein Artefakt.'
    FROM countries WHERE code = 'BE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'L''arrêté royal permet à deux parties de convenir d''un autre format EN 16931. Les critères de contrôle de cette option sont un texte juridique, pas un artefact.'
    FROM countries WHERE code = 'BE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'El real decreto permite a dos partes pactar otro formato EN 16931. Los criterios de control de esa excepción son texto jurídico, no forman parte de artefacto alguno.'
    FROM countries WHERE code = 'BE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'The federal receipt platforms (ZRE and OZG-RE) apply their own routing and registration checks when an invoice arrives. Only the schema and the Schematron are published.'
    FROM countries WHERE code = 'DE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Die Empfangsplattformen des Bundes (ZRE, OZG-RE) prüfen beim Eingang zusätzlich Routing und Registrierung. Veröffentlicht sind nur Schema und Schematron.'
    FROM countries WHERE code = 'DE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Les plateformes fédérales de réception (ZRE, OZG-RE) appliquent leurs propres contrôles de routage et d''enregistrement. Seuls le schéma et le Schematron sont publiés.'
    FROM countries WHERE code = 'DE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Las plataformas federales de recepción (ZRE, OZG-RE) aplican sus propios controles de enrutamiento y registro. Solo se publican el esquema y el Schematron.'
    FROM countries WHERE code = 'DE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'Denmark consulted in March 2026 on retiring OIOUBL for Peppol BIS 4 by around 2029; the successor rules are not published. The licence terms are not stated either.'
    FROM countries WHERE code = 'DK';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Dänemark hat im März 2026 zur Ablösung von OIOUBL durch Peppol BIS 4 bis etwa 2029 konsultiert; die Nachfolgeregeln fehlen. Auch Lizenzbedingungen fehlen.'
    FROM countries WHERE code = 'DK';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Le Danemark a consulté en mars 2026 sur l''abandon d''OIOUBL au profit de Peppol BIS 4 vers 2029 ; les règles successeurs ne sont pas publiées, ni les licences.'
    FROM countries WHERE code = 'DK';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Dinamarca consultó en marzo de 2026 sobre sustituir OIOUBL por Peppol BIS 4 hacia 2029; las reglas sucesoras no están publicadas, ni los términos de licencia.'
    FROM countries WHERE code = 'DK';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'There is no single Spanish specification: Facturae for B2G, Veri*Factu from 2027, the general B2B format still unfinalised, and TicketBAI regionally in the Basque Country.'
    FROM countries WHERE code = 'ES';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Es gibt keine einheitliche spanische Spezifikation: Facturae für B2G, Veri*Factu ab 2027, das allgemeine B2B-Format offen und regional TicketBAI im Baskenland.'
    FROM countries WHERE code = 'ES';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Il n''existe pas de spécification espagnole unique : Facturae pour le B2G, Veri*Factu dès 2027, le format B2B général non finalisé, et TicketBAI au Pays basque.'
    FROM countries WHERE code = 'ES';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'No hay una especificación española única: Facturae para B2G, Veri*Factu desde 2027, el formato B2B general sin cerrar y TicketBAI a nivel regional en el País Vasco.'
    FROM countries WHERE code = 'ES';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'Finvoice is governed by a private banking association rather than a public authority, so its roadmap and version decisions go through no public standards process.'
    FROM countries WHERE code = 'FI';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Finvoice wird von einem privaten Bankenverband und nicht von einer Behörde verantwortet; Roadmap und Versionsentscheidungen durchlaufen kein öffentliches Normverfahren.'
    FROM countries WHERE code = 'FI';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Finvoice est gouverné par une association bancaire privée et non par une autorité publique : sa feuille de route et ses versions ne suivent aucun processus normatif public.'
    FROM countries WHERE code = 'FI';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Finvoice lo gobierna una asociación bancaria privada, no una autoridad pública, así que su hoja de ruta y sus versiones no pasan por ningún proceso normativo público.'
    FROM countries WHERE code = 'FI';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'The Factur-X package asks for an email address, and the accreditation test suite every certified platform must pass is not published. Platforms may add checks of their own.'
    FROM countries WHERE code = 'FR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Das Factur-X-Paket verlangt eine E-Mail-Adresse, und die Akkreditierungstests jeder zertifizierten Plattform sind unveröffentlicht. Plattformen prüfen zusätzlich.'
    FROM countries WHERE code = 'FR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Le package Factur-X demande une adresse e-mail, et la suite de tests d''accréditation que chaque plateforme agréée doit passer n''est pas publiée. Chacune peut ajouter des contrôles.'
    FROM countries WHERE code = 'FR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'El paquete Factur-X pide un correo electrónico, y la batería de pruebas de acreditación de cada plataforma homologada no se publica. Cada una puede añadir controles.'
    FROM countries WHERE code = 'FR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'Access-point conformance testing and FiskAplikacija onboarding must both be passed before an invoice is accepted, and neither process is described in the schema files.'
    FROM countries WHERE code = 'HR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Vor der Annahme müssen Access-Point-Konformitätstests und das FiskAplikacija-Onboarding bestanden werden; beides ist in den Schemadateien nicht beschrieben.'
    FROM countries WHERE code = 'HR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Les tests de conformité du point d''accès et l''enrôlement FiskAplikacija doivent être franchis avant acceptation ; ni l''un ni l''autre ne figure dans les schémas.'
    FROM countries WHERE code = 'HR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Antes de aceptar una factura hay que superar las pruebas de conformidad del punto de acceso y el alta en FiskAplikacija; ninguna consta en los esquemas.'
    FROM countries WHERE code = 'HR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'Revenue says the technical specification will be published well ahead of the 2028 phase. It does not exist yet, so there is nothing to build against or to validate.'
    FROM countries WHERE code = 'IE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Revenue kündigt an, die technische Spezifikation lange vor der Stufe 2028 zu veröffentlichen. Sie existiert noch nicht – es gibt nichts zu implementieren oder zu prüfen.'
    FROM countries WHERE code = 'IE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Revenue annonce la publication de la spécification technique bien avant l''échéance de 2028. Elle n''existe pas encore : il n''y a rien à implémenter ni à valider.'
    FROM countries WHERE code = 'IE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Revenue afirma que publicará la especificación técnica bastante antes de la fase de 2028. Todavía no existe, así que no hay nada que implementar ni validar.'
    FROM countries WHERE code = 'IE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'SdI checks VAT-registry validity and routing codes that no schema describes, no Schematron is published, and the test channel needs an Italian digital identity.'
    FROM countries WHERE code = 'IT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Das SdI prüft Registergültigkeit und Empfängercodes, die kein Schema beschreibt; ein Schematron fehlt, und der Testkanal verlangt eine italienische digitale Identität.'
    FROM countries WHERE code = 'IT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Le SdI contrôle la validité du registre TVA et les codes de routage qu''aucun schéma ne décrit ; aucun Schematron n''est publié et le canal de test exige une identité numérique italienne.'
    FROM countries WHERE code = 'IT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'El SdI comprueba la validez del registro de IVA y los códigos de destino que ningún esquema describe; no se publica Schematron y el canal de pruebas exige identidad digital italiana.'
    FROM countries WHERE code = 'IT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'Japan mandates no format at all — JP PINT is voluntary and the Qualified Invoice System governs content, not syntax. Peppol accreditation is governance, not schema.'
    FROM countries WHERE code = 'JP';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Japan schreibt kein Format vor: JP PINT ist freiwillig, das Qualified Invoice System regelt Inhalte, nicht Syntax. Peppol-Akkreditierung ist Governance, kein Schema.'
    FROM countries WHERE code = 'JP';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Le Japon n''impose aucun format : JP PINT est volontaire et le Qualified Invoice System régit le contenu, pas la syntaxe. L''accréditation Peppol relève de la gouvernance.'
    FROM countries WHERE code = 'JP';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Japón no impone formato alguno: JP PINT es voluntario y el Qualified Invoice System regula el contenido, no la sintaxis. La acreditación Peppol es gobernanza, no esquema.'
    FROM countries WHERE code = 'JP';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'There is no domestic B2B mandate, so nothing is enforced beyond the B2G Peppol route, where a government access point may still apply acceptance checks of its own.'
    FROM countries WHERE code = 'NL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Es gibt keine nationale B2B-Pflicht; durchgesetzt wird nur der B2G-Peppol-Weg, wo ein staatlicher Access Point eigene Annahmeprüfungen anwenden kann.'
    FROM countries WHERE code = 'NL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Il n''existe aucune obligation B2B nationale : seule la voie B2G Peppol est appliquée, où un point d''accès public peut ajouter ses propres contrôles d''acceptation.'
    FROM countries WHERE code = 'NL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'No existe mandato B2B nacional: solo se aplica la vía B2G Peppol, donde un punto de acceso público puede añadir sus propios controles de aceptación.'
    FROM countries WHERE code = 'NL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'The format itself is fully public. The 2027 B2B mandate''s detailed rules are delegated to a regulation (forskrift) that has not yet been issued.'
    FROM countries WHERE code = 'NO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Das Format selbst ist vollständig öffentlich. Die Detailregeln der B2B-Pflicht 2027 sind einer Verordnung (forskrift) überlassen, die noch nicht vorliegt.'
    FROM countries WHERE code = 'NO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Le format lui-même est entièrement public. Les règles détaillées de l''obligation B2B de 2027 sont renvoyées à un règlement (forskrift) non encore publié.'
    FROM countries WHERE code = 'NO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'El formato en sí es totalmente público. Las reglas detalladas del mandato B2B de 2027 se remiten a un reglamento (forskrift) que aún no se ha publicado.'
    FROM countries WHERE code = 'NO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'MBIE''s rules for mandated agencies, including paying 95% of e-invoices within five business days, are payment policy rather than anything the schema can express.'
    FROM countries WHERE code = 'NZ';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Die MBIE-Regeln für verpflichtete Stellen, etwa 95 % der E-Rechnungen binnen fünf Werktagen zu zahlen, sind Zahlungspolitik und im Schema nicht abbildbar.'
    FROM countries WHERE code = 'NZ';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Les règles du MBIE pour les agences concernées, dont le paiement de 95 % des e-factures sous cinq jours ouvrés, relèvent du paiement, non de ce que le schéma exprime.'
    FROM countries WHERE code = 'NZ';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'Las reglas del MBIE para los organismos obligados, como pagar el 95% de las e-facturas en cinco días hábiles, son política de pago, no algo que el esquema exprese.'
    FROM countries WHERE code = 'NZ';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'The XSD is structural only. KSeF applies a layer of semantic rejections — identifier cross-checks, duplicates, field dependencies — that no official artefact documents.'
    FROM countries WHERE code = 'PL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Das XSD ist rein strukturell. KSeF wendet semantische Ablehnungen an – Kennungsabgleich, Duplikate, Feldabhängigkeiten –, die kein offizielles Artefakt dokumentiert.'
    FROM countries WHERE code = 'PL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Le XSD n''est que structurel. KSeF applique des rejets sémantiques — contrôles d''identifiants, doublons, dépendances de champs — qu''aucun artefact officiel ne documente.'
    FROM countries WHERE code = 'PL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'El XSD es solo estructural. KSeF aplica rechazos semánticos —cruces de identificadores, duplicados, dependencias entre campos— que ningún artefacto oficial documenta.'
    FROM countries WHERE code = 'PL';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'eSPap could not be reached, and the newest CIUS-PT version we can see indexed dates from 2021 — which is itself a question about how current the specification is.'
    FROM countries WHERE code = 'PT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'eSPap war nicht erreichbar, und die neueste indexierte CIUS-PT-Fassung stammt von 2021 – was schon für sich die Frage nach der Aktualität der Spezifikation aufwirft.'
    FROM countries WHERE code = 'PT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'eSPap est resté inaccessible, et la version CIUS-PT la plus récente que nous voyons indexée date de 2021 — ce qui pose en soi la question de l''actualité de la spécification.'
    FROM countries WHERE code = 'PT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'No pudimos acceder a eSPap, y la versión de CIUS-PT más reciente que vemos indexada es de 2021, lo que ya plantea la duda de si la especificación está al día.'
    FROM countries WHERE code = 'PT';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'RO_CIUS exists only as prose in a ministerial ordinance. No ANAF-published XSD or Schematron could be found; what the SPV validates lives inside government software.'
    FROM countries WHERE code = 'RO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'RO_CIUS existiert nur als Fließtext in einer Ministerialverordnung. Kein XSD oder Schematron der ANAF auffindbar; die Prüfungen des SPV stecken in Behördensoftware.'
    FROM countries WHERE code = 'RO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'RO_CIUS n''existe qu''en texte dans un arrêté ministériel. Aucun XSD ni Schematron publié par l''ANAF n''a été trouvé ; ce que valide le SPV réside dans un logiciel public.'
    FROM countries WHERE code = 'RO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'RO_CIUS solo existe como texto en una orden ministerial. No se halló XSD ni Schematron publicado por la ANAF; lo que valida el SPV vive dentro del software estatal.'
    FROM countries WHERE code = 'RO';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'There is no Swedish artefact of its own: rules such as SE-R-011 sit inside the core Peppol rule set. Agency onboarding requirements are published separately, if at all.'
    FROM countries WHERE code = 'SE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Es gibt kein eigenes schwedisches Artefakt: Regeln wie SE-R-011 stehen im Peppol-Kernregelwerk. Onboarding-Anforderungen der Behörden erscheinen gesondert, wenn überhaupt.'
    FROM countries WHERE code = 'SE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'Il n''existe pas d''artefact suédois propre : des règles comme SE-R-011 figurent dans le socle Peppol. Les exigences d''enrôlement des agences sont publiées à part, voire pas.'
    FROM countries WHERE code = 'SE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'No hay artefacto sueco propio: reglas como SE-R-011 están en el núcleo Peppol. Los requisitos de alta de cada organismo se publican aparte, si es que se publican.'
    FROM countries WHERE code = 'SE';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'The current PINT SG release is still marked draft, and IRAS''s turnover-band phase-in running to 2031 is tax policy layered on the network, not part of the artefacts.'
    FROM countries WHERE code = 'SG';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Die aktuelle PINT-SG-Fassung gilt noch als Entwurf; die Umsatzstaffelung der IRAS bis 2031 ist Steuerpolitik über dem Netz, nicht Teil der Artefakte.'
    FROM countries WHERE code = 'SG';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'La version PINT SG actuelle est encore marquée « draft », et l''entrée en vigueur par tranches de l''IRAS jusqu''en 2031 est fiscale, hors artefacts.'
    FROM countries WHERE code = 'SG';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'La versión actual de PINT SG sigue marcada como borrador, y la entrada por tramos de facturación de IRAS hasta 2031 es política fiscal, no parte de los artefactos.'
    FROM countries WHERE code = 'SG';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'en', 'GİB blocks automated access to its own technical portal, so we could not read the UBL-TR package or its terms. This records that we could not verify, not that it is absent.'
    FROM countries WHERE code = 'TR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'de', 'Die GİB sperrt automatisierten Zugriff auf ihr Technikportal; das UBL-TR-Paket und seine Bedingungen blieben ungeprüft. Festgehalten ist: nicht verifizierbar, nicht: fehlend.'
    FROM countries WHERE code = 'TR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'fr', 'La GİB bloque l''accès automatisé à son portail technique : nous n''avons pu lire ni le package UBL-TR ni ses conditions. Ceci consigne une non-vérification, pas une absence.'
    FROM countries WHERE code = 'TR';
INSERT OR REPLACE INTO country_spec_translations (country_id, lang, gap_note)
  SELECT id, 'es', 'La GİB bloquea el acceso automatizado a su portal técnico, así que no pudimos leer el paquete UBL-TR ni sus condiciones. Esto registra que no se pudo verificar, no que falte.'
    FROM countries WHERE code = 'TR';

-- ---- what this migration claims it did ------------------------------

-- ASSERT: SELECT count(*) FROM country_spec = 20
-- ASSERT: SELECT count(*) FROM country_spec_artefacts = 33
-- ASSERT: SELECT count(*) FROM country_spec_translations = 80

-- The two findings, asserted so that a later edit cannot quietly
-- soften them. 11 of 20 publish machine-readable artefacts they
-- consider current; only 2 do so under a licence with a name.
-- ASSERT: SELECT count(*) FROM country_spec WHERE capture_status = 'published' = 11
-- ASSERT: SELECT count(*) FROM country_spec WHERE licence_status = 'named' = 2

-- ---- and what must stay true afterwards -----------------------------

-- EVERY REGISTERED COUNTRY IS A REAL, TRACKED JURISDICTION. A row
-- against a country the site does not otherwise cover would render a
-- page with no guide to link to.
-- ASSERT ALWAYS: SELECT count(*) FROM country_spec s JOIN countries c ON c.id = s.country_id WHERE c.slug IS NULL = 0

-- NO ARTEFACT IS ORPHANED. The artefact table has no foreign-key
-- enforcement in D1, so the invariant does the work.
-- ASSERT ALWAYS: SELECT count(*) FROM country_spec_artefacts a WHERE a.country_id NOT IN (SELECT country_id FROM country_spec) = 0

-- AND EVERY ARTEFACT URL IS ONE, so that a card cannot render a link
-- that goes nowhere.
-- ASSERT ALWAYS: SELECT count(*) FROM country_spec_artefacts WHERE url NOT LIKE 'https://%' = 0

