-- ================================================================
-- The words the specification register says.
-- ================================================================
--
-- Generated by gen_spec_strings.py -- edit that, not this.
--
-- THE VOCABULARY IS THE PRODUCT. capture_status, licence_status and
-- access each hold a controlled set of words, and each word is a claim.
-- 'Open to download, redistribution refused' is not a softened way of
-- saying 'no terms stated' -- it is what every Peppol jurisdiction
-- actually offers, and a reader deciding whether they may ship a rule
-- set inside their own product needs the difference. 'We could not read
-- it' is a claim about US, not about the publisher.
--
-- Those distinctions exist in four languages or they exist in English
-- only, which on this site means they do not exist. The generator
-- refuses to emit unless every word permitted by 636's CHECK
-- constraints has a label in all four -- read out of the CHECK itself,
-- not from a list retyped here that could fall behind it.
--
-- The register's own caveat ('spec.caveat') is the most important
-- string in this file. The feasibility study's finding was that a
-- conformance checker can never honestly promise acceptance; this page
-- must not imply it either, in any language.
-- ================================================================

-- ---- page strings ---------------------------------------------------
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.blocked', 'en', 'Publisher blocks automated access');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.blocked', 'de', 'Herausgeber sperrt automatisierten Zugriff');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.blocked', 'fr', 'L''éditeur bloque l''accès automatisé');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.blocked', 'es', 'El editor bloquea el acceso automatizado');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.credentials', 'en', 'National digital identity');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.credentials', 'de', 'Nationale digitale Identität');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.credentials', 'fr', 'Identité numérique nationale');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.credentials', 'es', 'Identidad digital nacional');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.none', 'en', 'Nothing published yet');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.none', 'de', 'Noch nichts veröffentlicht');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.none', 'fr', 'Rien de publié');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.none', 'es', 'Nada publicado aún');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.open', 'en', 'Download, no account');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.open', 'de', 'Download ohne Konto');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.open', 'fr', 'Téléchargement sans compte');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.open', 'es', 'Descarga sin cuenta');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.registration', 'en', 'Email or free account');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.registration', 'de', 'E-Mail oder kostenloses Konto');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.registration', 'fr', 'E-mail ou compte gratuit');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.access.registration', 'es', 'Correo o cuenta gratuita');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.codelist', 'en', 'Code lists');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.codelist', 'de', 'Codelisten');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.codelist', 'fr', 'Listes de codes');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.codelist', 'es', 'Listas de códigos');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.repo', 'en', 'Repository');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.repo', 'de', 'Repository');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.repo', 'fr', 'Dépôt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.repo', 'es', 'Repositorio');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.schematron', 'en', 'Business rules (Schematron)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.schematron', 'de', 'Geschäftsregeln (Schematron)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.schematron', 'fr', 'Règles de gestion (Schematron)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.schematron', 'es', 'Reglas de negocio (Schematron)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.sdk', 'en', 'Validator or SDK');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.sdk', 'de', 'Prüfwerkzeug oder SDK');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.sdk', 'fr', 'Validateur ou SDK');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.sdk', 'es', 'Validador o SDK');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.spec_pdf', 'en', 'Specification document');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.spec_pdf', 'de', 'Spezifikationsdokument');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.spec_pdf', 'fr', 'Document de spécification');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.spec_pdf', 'es', 'Documento de especificación');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.testsuite', 'en', 'Test invoices');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.testsuite', 'de', 'Testrechnungen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.testsuite', 'fr', 'Factures de test');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.testsuite', 'es', 'Facturas de prueba');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xsd', 'en', 'Schema (XSD)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xsd', 'de', 'Schema (XSD)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xsd', 'fr', 'Schéma (XSD)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xsd', 'es', 'Esquema (XSD)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xslt', 'en', 'Rules (XSLT)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xslt', 'de', 'Regeln (XSLT)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xslt', 'fr', 'Règles (XSLT)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefact.xslt', 'es', 'Reglas (XSLT)');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefactsHeading', 'en', 'Authoritative files');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefactsHeading', 'de', 'Maßgebliche Dateien');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefactsHeading', 'fr', 'Fichiers de référence');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.artefactsHeading', 'es', 'Archivos de referencia');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.asOf', 'en', 'Verified {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.asOf', 'de', 'Geprüft am {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.asOf', 'fr', 'Vérifié le {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.asOf', 'es', 'Verificado el {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.back', 'en', '← Back to global tracker');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.back', 'de', '← Zurück zum globalen Tracker');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.back', 'fr', '← Retour au tracker mondial');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.back', 'es', '← Volver al rastreador global');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.not_yet', 'en', 'Not issued yet');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.not_yet', 'de', 'Noch nicht erschienen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.not_yet', 'fr', 'Pas encore publiée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.not_yet', 'es', 'Aún no publicada');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.partial', 'en', 'Partly published');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.partial', 'de', 'Teilweise veröffentlicht');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.partial', 'fr', 'Partiellement publiée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.partial', 'es', 'Publicada en parte');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.published', 'en', 'Published');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.published', 'de', 'Veröffentlicht');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.published', 'fr', 'Publiée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.published', 'es', 'Publicada');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unpublished', 'en', 'Not published');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unpublished', 'de', 'Nicht veröffentlicht');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unpublished', 'fr', 'Non publiée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unpublished', 'es', 'No publicada');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unreachable', 'en', 'We could not read it');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unreachable', 'de', 'Für uns nicht lesbar');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unreachable', 'fr', 'Nous n''avons pas pu la lire');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.capture.unreachable', 'es', 'No pudimos leerla');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.caveat', 'en', 'This register says where a specification is and what it covers. It is not a validator, and conforming to a published artefact is not the same as being accepted — every platform applies checks that no artefact describes.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.caveat', 'de', 'Dieses Register sagt, wo eine Spezifikation liegt und was sie abdeckt. Es ist kein Prüfdienst: Die Konformität mit einem Artefakt bedeutet nicht Annahme – jede Plattform prüft mehr, als Artefakte beschreiben.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.caveat', 'fr', 'Ce registre indique où se trouve une spécification et ce qu''elle couvre. Ce n''est pas un validateur : être conforme à un artefact publié n''est pas être accepté — chaque plateforme applique des contrôles qu''aucun artefact ne décrit.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.caveat', 'es', 'Este registro indica dónde está una especificación y qué abarca. No es un validador: cumplir un artefacto publicado no equivale a ser aceptado, porque toda plataforma aplica controles que ningún artefacto describe.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.eyebrow', 'en', 'The specification register');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.eyebrow', 'de', 'Das Spezifikationsregister');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.eyebrow', 'fr', 'Le registre des spécifications');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.eyebrow', 'es', 'El registro de especificaciones');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gapHeading', 'en', 'What the artefacts do not tell you');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gapHeading', 'de', 'Was die Artefakte nicht sagen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gapHeading', 'fr', 'Ce que les artefacts ne disent pas');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gapHeading', 'es', 'Lo que los artefactos no dicen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateBody', 'en', 'Subscribing is free. The register names the mandated format, its current version, the authoritative file and its licence for twenty jurisdictions — and, for each, what the published artefacts leave out.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateBody', 'de', 'Das Abonnement ist kostenlos. Das Register nennt für zwanzig Jurisdiktionen das vorgeschriebene Format, die aktuelle Version, die maßgebliche Datei und deren Lizenz – und was die Artefakte auslassen.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateBody', 'fr', 'L''abonnement est gratuit. Le registre indique, pour vingt juridictions, le format imposé, sa version actuelle, le fichier de référence et sa licence — et ce que les artefacts publiés omettent.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateBody', 'es', 'Suscribirse es gratis. El registro indica, para veinte jurisdicciones, el formato exigido, su versión actual, el archivo de referencia y su licencia, y qué omiten los artefactos publicados.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateEyebrow', 'en', 'Subscriber reference');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateEyebrow', 'de', 'Referenz für Abonnenten');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateEyebrow', 'fr', 'Référence abonnés');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateEyebrow', 'es', 'Referencia para suscriptores');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateTitle', 'en', 'The specification register');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateTitle', 'de', 'Das Spezifikationsregister');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateTitle', 'fr', 'Le registre des spécifications');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.gateTitle', 'es', 'El registro de especificaciones');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.guideLink', 'en', 'What is mandated, and from when →');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.guideLink', 'de', 'Was gilt – und ab wann →');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.guideLink', 'fr', 'Ce qui est obligatoire, et à partir de quand →');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.guideLink', 'es', 'Qué es obligatorio y desde cuándo →');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.intro', 'en', 'The format, the version, the authoritative file, the licence, and the date a version becomes obligatory — with, for every country, what the published artefacts do not tell you.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.intro', 'de', 'Format, Version, maßgebliche Datei, Lizenz und der Stichtag, ab dem eine Version gilt – und für jedes Land das, was die veröffentlichten Artefakte nicht sagen.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.intro', 'fr', 'Le format, la version, le fichier de référence, la licence et la date à laquelle une version devient obligatoire — et, pour chaque pays, ce que les artefacts publiés ne disent pas.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.intro', 'es', 'El formato, la versión, el archivo de referencia, la licencia y la fecha en que una versión pasa a ser obligatoria, y para cada país lo que los artefactos publicados no cuentan.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.access', 'en', 'Access');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.access', 'de', 'Zugang');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.access', 'fr', 'Accès');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.access', 'es', 'Acceso');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.changelog', 'en', 'Version history');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.changelog', 'de', 'Versionsverlauf');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.changelog', 'fr', 'Historique des versions');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.changelog', 'es', 'Historial de versiones');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.format', 'en', 'Format');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.format', 'de', 'Format');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.format', 'fr', 'Format');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.format', 'es', 'Formato');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.licence', 'en', 'Licence');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.licence', 'de', 'Lizenz');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.licence', 'fr', 'Licence');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.licence', 'es', 'Licencia');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.mandatory', 'en', 'Obligatory from');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.mandatory', 'de', 'Verbindlich ab');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.mandatory', 'fr', 'Obligatoire au');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.mandatory', 'es', 'Obligatoria desde');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.published_by', 'en', 'Published by');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.published_by', 'de', 'Herausgeber');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.published_by', 'fr', 'Publié par');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.published_by', 'es', 'Publicado por');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.released', 'en', 'Released');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.released', 'de', 'Veröffentlicht');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.released', 'fr', 'Publiée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.released', 'es', 'Publicada');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.standard', 'en', 'EN 16931');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.standard', 'de', 'EN 16931');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.standard', 'fr', 'EN 16931');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.standard', 'es', 'EN 16931');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.syntax', 'en', 'Syntax');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.syntax', 'de', 'Syntax');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.syntax', 'fr', 'Syntaxe');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.syntax', 'es', 'Sintaxis');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.validator', 'en', 'Public validator');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.validator', 'de', 'Öffentlicher Prüfdienst');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.validator', 'fr', 'Validateur public');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.validator', 'es', 'Validador público');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.version', 'en', 'Version');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.version', 'de', 'Version');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.version', 'fr', 'Version');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.lbl.version', 'es', 'Versión');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.named', 'en', 'Named licence');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.named', 'de', 'Benannte Lizenz');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.named', 'fr', 'Licence nommée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.named', 'es', 'Licencia con nombre');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.permissive_unnamed', 'en', 'Reuse permitted, no named licence');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.permissive_unnamed', 'de', 'Nutzung erlaubt, ohne benannte Lizenz');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.permissive_unnamed', 'fr', 'Réutilisation permise, sans licence nommée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.permissive_unnamed', 'es', 'Reutilización permitida, sin licencia con nombre');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.restrictive', 'en', 'Open to download, redistribution refused');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.restrictive', 'de', 'Frei ladbar, Weitergabe untersagt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.restrictive', 'fr', 'Téléchargeable, redistribution refusée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.restrictive', 'es', 'Descargable, redistribución denegada');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unknown', 'en', 'Terms not established');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unknown', 'de', 'Bedingungen ungeklärt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unknown', 'fr', 'Conditions non établies');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unknown', 'es', 'Condiciones no determinadas');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unstated', 'en', 'No terms stated');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unstated', 'de', 'Keine Bedingungen genannt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unstated', 'fr', 'Aucune condition indiquée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.licenceStatus.unstated', 'es', 'Sin condiciones indicadas');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.no', 'en', 'No');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.no', 'de', 'Nein');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.no', 'fr', 'Non');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.no', 'es', 'No');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.noArtefacts', 'en', 'Nothing to download');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.noArtefacts', 'de', 'Kein Download vorhanden');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.noArtefacts', 'fr', 'Rien à télécharger');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.noArtefacts', 'es', 'Nada que descargar');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.jurisdictions', 'en', 'Jurisdictions');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.jurisdictions', 'de', 'Jurisdiktionen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.jurisdictions', 'fr', 'Juridictions');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.jurisdictions', 'es', 'Jurisdicciones');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.named', 'en', 'Under a named licence');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.named', 'de', 'Mit benannter Lizenz');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.named', 'fr', 'Sous licence nommée');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.named', 'es', 'Con licencia con nombre');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.nothing', 'en', 'Nothing machine-readable');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.nothing', 'de', 'Nichts Maschinenlesbares');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.nothing', 'fr', 'Rien d''exploitable');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.nothing', 'es', 'Nada legible por máquina');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.validators', 'en', 'Public validator');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.validators', 'de', 'Öffentlicher Prüfdienst');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.validators', 'fr', 'Validateur public');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.strip.validators', 'es', 'Validador público');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.cii', 'en', 'UN/CEFACT CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.cii', 'de', 'UN/CEFACT CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.cii', 'fr', 'UN/CEFACT CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.cii', 'es', 'UN/CEFACT CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.hybrid', 'en', 'Hybrid PDF + CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.hybrid', 'de', 'Hybrid PDF + CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.hybrid', 'fr', 'Hybride PDF + CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.hybrid', 'es', 'Híbrido PDF + CII');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.json', 'en', 'JSON');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.json', 'de', 'JSON');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.json', 'fr', 'JSON');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.json', 'es', 'JSON');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.multiple', 'en', 'More than one accepted');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.multiple', 'de', 'Mehrere zulässig');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.multiple', 'fr', 'Plusieurs formats admis');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.multiple', 'es', 'Se admite más de uno');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.national_xml', 'en', 'National XML');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.national_xml', 'de', 'Nationales XML');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.national_xml', 'fr', 'XML national');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.national_xml', 'es', 'XML nacional');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.ubl', 'en', 'UBL 2.1');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.ubl', 'de', 'UBL 2.1');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.ubl', 'fr', 'UBL 2.1');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.ubl', 'es', 'UBL 2.1');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.unknown', 'en', 'Not established');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.unknown', 'de', 'Ungeklärt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.unknown', 'fr', 'Non établie');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.syntaxName.unknown', 'es', 'Sin determinar');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.title', 'en', 'What each country actually mandates, and where the file is');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.title', 'de', 'Was jedes Land tatsächlich vorschreibt – und wo die Datei liegt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.title', 'fr', 'Ce que chaque pays impose réellement, et où se trouve le fichier');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.title', 'es', 'Qué exige realmente cada país y dónde está el archivo');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.unknown', 'en', 'Not established');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.unknown', 'de', 'Ungeklärt');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.unknown', 'fr', 'Non établi');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.unknown', 'es', 'Sin determinar');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.yes', 'en', 'Yes');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.yes', 'de', 'Ja');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.yes', 'fr', 'Oui');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'spec.yes', 'es', 'Sí');

-- ---- the menu entry -------------------------------------------------
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.specs', 'en', 'Specification register');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.specs', 'de', 'Spezifikationsregister');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.specs', 'fr', 'Registre des spécifications');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.specs', 'es', 'Registro de especificaciones');

-- ---- what this migration claims it did ------------------------------

-- ASSERT: SELECT count(*) FROM translations WHERE namespace = 'tracker' AND (key LIKE 'spec.%' OR key = 'menu.specs') = 248

-- ---- and what must stay true afterwards -----------------------------

-- FOUR LANGUAGES OR NONE, per key.
-- ASSERT ALWAYS: SELECT count(*) FROM (SELECT key FROM translations WHERE namespace = 'tracker' AND key LIKE 'spec.%' GROUP BY key HAVING count(DISTINCT lang) != 4) = 0

-- THE CAVEAT SURVIVES TRANSLATION. A register that quietly loses the
-- sentence saying it is not a validator, in one language, is the
-- confident wrong answer this whole feature was scoped to avoid.
-- ASSERT ALWAYS: SELECT count(*) FROM translations WHERE namespace = 'tracker' AND key = 'spec.caveat' = 4

-- AND THE DATE PLACEHOLDER SURVIVES IT TOO, so the page cannot claim
-- verification without saying when.
-- ASSERT ALWAYS: SELECT count(*) FROM translations WHERE namespace = 'tracker' AND key = 'spec.asOf' AND value NOT LIKE '%{0}%' = 0

