-- ================================================================
-- The menu says which items need an account.
-- ================================================================
--
-- Generated by gen_menu_subscriber_marker.py -- edit that, not this.
--
-- Dan, 24 August 2026: "it would be good to highlight this in the menu
-- itself" -- and, in the same breath, that it "should not prevent them
-- from clicking the link, as they will be presented with a subscribe
-- page thereafter". So this is a qualifier on the label, not a state on
-- the link: nothing is disabled, nothing is hidden, and the route still
-- answers the wall it always did.
--
-- IT RESTORES A MARKER THAT WAS DELIBERATELY REMOVED. A padlock came
-- off the planner's menu item on 21 August because it claimed
-- exclusivity for a page then served to everyone. Three routes now
-- genuinely gate -- the planner, the compliance guides and the
-- specification register -- so the claim is true, and the markup
-- comment that explained the padlock's absence has been rewritten
-- rather than left to certify the opposite of what the code does.
-- ================================================================

-- ---- the string ----------------------------------------------------
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.subscriberOnly', 'en', 'Subscribers');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.subscriberOnly', 'de', 'Abonnenten');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.subscriberOnly', 'fr', 'Abonnés');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('tracker', 'menu.subscriberOnly', 'es', 'Suscriptores');

-- ---- what this migration claims it did ------------------------------

-- ASSERT: SELECT count(*) FROM translations WHERE namespace = 'tracker' AND key = 'menu.subscriberOnly' = 4

-- ---- and what must stay true afterwards -----------------------------

-- FOUR LANGUAGES OR NONE. An English marker on a German menu would be
-- the one word on the row that is not translated, which reads as a
-- system message rather than as part of the label.
-- ASSERT ALWAYS: SELECT count(*) FROM (SELECT key FROM translations WHERE namespace = 'tracker' AND key = 'menu.subscriberOnly' GROUP BY key HAVING count(DISTINCT lang) != 4) = 0

-- AND IT STAYS SHORT. The marker shares a row with an icon and a label
-- inside a narrow dropdown; a phrase here wraps every gated item onto
-- two lines. tests/spec-register.mjs checks the markup; this checks the
-- string a future edit might lengthen without looking at the menu.
-- ASSERT ALWAYS: SELECT count(*) FROM translations WHERE namespace = 'tracker' AND key = 'menu.subscriberOnly' AND length(value) > 16 = 0

