-- ================================================================
-- Remove the stat tiles the headline tiles now state.
-- ================================================================
--
-- Generated by gen_dedupe_stat_tiles.py -- edit that, not this.
--
-- The headline strip (mandate / e-reporting / archiving / signature)
-- reached the country deep dives on 25 August. Where a free-form stat
-- tile restated one of those facts, or restated the compliance-model line
-- in the page head, the page said the same thing twice about 40mm apart.
-- Germany showed archiving twice and "No CTC" beside a model line already
-- reading "Fully decentralised -- no clearance".
--
-- 43 tiles go. 311 stay, because they are the reason the deep dive exists:
-- formats, penalties, thresholds, and dated milestones with citations.
--
-- DELETES THE TRANSLATIONS FIRST, then the stat. The rows are matched on
-- country plus ENGLISH label, so all four languages of a removed tile go
-- with it -- a tile that vanished in English and survived in German would
-- be worse than the duplication this fixes.
-- ================================================================

-- ---- the removals -------------------------------------------------

-- archiving: Argentina -- 10 years / Mandatory invoice retention period
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Argentina' AND t.stat_label = 'Mandatory invoice retention period');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Argentina' AND t.stat_id IS NULL);

-- mandate-status: Austria -- Voluntary / B2B e-invoicing (today)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Austria' AND t.stat_label = 'B2B e-invoicing (today)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Austria' AND t.stat_id IS NULL);

-- mandate-status: Bahrain -- No mandate / E-invoicing law status
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Bahrain' AND t.stat_label = 'E-invoicing law status');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Bahrain' AND t.stat_id IS NULL);

-- archiving: Brazil -- 5 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Brazil' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Brazil' AND t.stat_id IS NULL);

-- mandate-status: Bulgaria -- No mandate / B2B e-invoicing remains entirely voluntary
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Bulgaria' AND t.stat_label = 'B2B e-invoicing remains entirely voluntary');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Bulgaria' AND t.stat_id IS NULL);

-- archiving: Canada -- 6 yrs / Record retention
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Canada' AND t.stat_label = 'Record retention');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Canada' AND t.stat_id IS NULL);

-- archiving: Chile -- 6 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Chile' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Chile' AND t.stat_id IS NULL);

-- archiving: Colombia -- 5 years / Mandatory invoice retention period
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Colombia' AND t.stat_label = 'Mandatory invoice retention period');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Colombia' AND t.stat_id IS NULL);

-- mandate-status: Cyprus -- Voluntary / B2G/B2B issuance (no mandate)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Cyprus' AND t.stat_label = 'B2G/B2B issuance (no mandate)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Cyprus' AND t.stat_id IS NULL);

-- mandate-status: Cyprus -- None / Confirmed domestic B2B timetable
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Cyprus' AND t.stat_label = 'Confirmed domestic B2B timetable');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Cyprus' AND t.stat_id IS NULL);

-- mandate-status: Czech Republic -- Voluntary / B2G/B2B issuance (no mandate)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Czech Republic' AND t.stat_label = 'B2G/B2B issuance (no mandate)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Czech Republic' AND t.stat_id IS NULL);

-- archiving: Denmark -- 5 yrs / Standard archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Denmark' AND t.stat_label = 'Standard archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Denmark' AND t.stat_id IS NULL);

-- clearance-model: Egypt -- Clearance / Centralized ETA model
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Egypt' AND t.stat_label = 'Centralized ETA model');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Egypt' AND t.stat_id IS NULL);

-- clearance-model: Estonia -- No CTC / No clearance authority — invoices move directly, peer to peer
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Estonia' AND t.stat_label = 'No clearance authority — invoices move directly, peer to peer');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Estonia' AND t.stat_id IS NULL);

-- clearance-model: France -- Y-model / Compliance model
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'France' AND t.stat_label = 'Compliance model');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'France' AND t.stat_id IS NULL);

-- archiving: France -- 10 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'France' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'France' AND t.stat_id IS NULL);

-- clearance-model: Germany -- No CTC / No central platform (B2B)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Germany' AND t.stat_label = 'No central platform (B2B)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Germany' AND t.stat_id IS NULL);

-- archiving: Germany -- 8 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Germany' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Germany' AND t.stat_id IS NULL);

-- mandate-status: Iceland -- None / B2B mandate proposed, drafted, or dated as of mid-2026
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Iceland' AND t.stat_label = 'B2B mandate proposed, drafted, or dated as of mid-2026');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Iceland' AND t.stat_id IS NULL);

-- clearance-model: Israel -- Clearance / Centralized SHAAM model
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Israel' AND t.stat_label = 'Centralized SHAAM model');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Israel' AND t.stat_id IS NULL);

-- archiving: Italy -- 10 yrs / Conservazione retention
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Italy' AND t.stat_label = 'Conservazione retention');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Italy' AND t.stat_id IS NULL);

-- archiving: Japan -- 7 years / Invoice retention requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Japan' AND t.stat_label = 'Invoice retention requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Japan' AND t.stat_id IS NULL);

-- clearance-model: Jordan -- Clearance / Centralized JoFotara model
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Jordan' AND t.stat_label = 'Centralized JoFotara model');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Jordan' AND t.stat_id IS NULL);

-- mandate-status: Lithuania -- No mandate / B2B e-invoicing remains voluntary (confirmed by the EC's own factsheet)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Lithuania' AND t.stat_label = 'B2B e-invoicing remains voluntary (confirmed by the EC''s own factsheet)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Lithuania' AND t.stat_id IS NULL);

-- archiving: Luxembourg -- 10 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Luxembourg' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Luxembourg' AND t.stat_id IS NULL);

-- archiving: Malaysia -- 7 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Malaysia' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Malaysia' AND t.stat_id IS NULL);

-- mandate-status: Malta -- No mandate / No B2B e-invoicing mandate, no target date, no draft law
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Malta' AND t.stat_label = 'No B2B e-invoicing mandate, no target date, no draft law');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Malta' AND t.stat_id IS NULL);

-- archiving: Mexico -- 5 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Mexico' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Mexico' AND t.stat_id IS NULL);

-- mandate-status: Netherlands -- Voluntary / B2B e-invoicing (today)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Netherlands' AND t.stat_label = 'B2B e-invoicing (today)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Netherlands' AND t.stat_id IS NULL);

-- archiving: New Zealand -- 7 yrs / Record retention
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'New Zealand' AND t.stat_label = 'Record retention');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'New Zealand' AND t.stat_id IS NULL);

-- archiving: Peru -- 5 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Peru' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Peru' AND t.stat_id IS NULL);

-- clearance-model: Philippines -- Post-issuance / Reporting model, not real-time clearance
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Philippines' AND t.stat_label = 'Reporting model, not real-time clearance');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Philippines' AND t.stat_id IS NULL);

-- archiving: Poland -- 10 yrs / KSeF central retention
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Poland' AND t.stat_label = 'KSeF central retention');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Poland' AND t.stat_id IS NULL);

-- archiving: Portugal -- 10 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Portugal' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Portugal' AND t.stat_id IS NULL);

-- clearance-model: Romania -- CTC / Compliance model
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Romania' AND t.stat_label = 'Compliance model');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Romania' AND t.stat_id IS NULL);

-- archiving: Slovakia -- 10 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Slovakia' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Slovakia' AND t.stat_id IS NULL);

-- clearance-model: South Korea -- Post-issuance / Real-time reporting, not clearance
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'South Korea' AND t.stat_label = 'Real-time reporting, not clearance');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'South Korea' AND t.stat_id IS NULL);

-- archiving: Sweden -- 7 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Sweden' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Sweden' AND t.stat_id IS NULL);

-- clearance-model: Turkey -- 2 systems / e-Fatura (clearance) or e-Arşiv (reporting)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Turkey' AND t.stat_label = 'e-Fatura (clearance) or e-Arşiv (reporting)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Turkey' AND t.stat_id IS NULL);

-- clearance-model: United Kingdom -- No CTC / No real-time reporting at launch
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'United Kingdom' AND t.stat_label = 'No real-time reporting at launch');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'United Kingdom' AND t.stat_id IS NULL);

-- mandate-status: United States -- No mandate / Federal B2B requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'United States' AND t.stat_label = 'Federal B2B requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'United States' AND t.stat_id IS NULL);

-- clearance-model: Vietnam -- 2 models / Real-time clearance or same-day reporting
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Vietnam' AND t.stat_label = 'Real-time clearance or same-day reporting');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Vietnam' AND t.stat_id IS NULL);

-- archiving: Vietnam -- 10 years / Invoice retention period
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Vietnam' AND t.stat_label = 'Invoice retention period');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Vietnam' AND t.stat_id IS NULL);

-- ---- what this migration claims it did ------------------------------

-- 43 tiles named above, from 354, leaving 311.
-- ASSERT: SELECT count(*) FROM deep_dive_stats = 311

-- AND EVERY LANGUAGE WENT WITH THEM. A translation row whose stat no
-- longer exists is a tile that vanished in English and survives in
-- German -- worse than the duplication this migration removes.
-- ASSERT: SELECT count(*) FROM deep_dive_stat_translations t LEFT JOIN deep_dive_stats ds ON ds.id = t.stat_id WHERE ds.id IS NULL = 0

-- ---- and what must stay true afterwards -----------------------------

-- NO COUNTRY IS LEFT WITH AN EMPTY STRIP. An earlier draft of the rules
-- flagged 86 tiles and would have left Latvia with none, because all five
-- of its tiles are dated milestones that read like mandate statuses. The
-- floor is asserted rather than trusted.
--
-- THE FLOOR IS TWO, NOT THE THREE THIS MIGRATION LEFT. Written as 3 and
-- true when 643 ran; migration 644 -- Dan's hand-reviewed list -- takes
-- Cyprus's B2G receive tile and leaves it with two. The runner caught it
-- immediately and said so precisely: "an ASSERT ALWAYS held when its own
-- migration ran, and does not hold at the end of the chain."
--
-- Loosened deliberately rather than deleted. An ASSERT ALWAYS is a claim
-- about how the world must stay, not a record of how it was; when the
-- world legitimately changes the claim is restated with the reason, and
-- the floor still stops a future sweep emptying a strip.
--
-- WRAPPED IN A SUBQUERY: the runner splits on the LAST comparison
-- operator in the line, so a bare `... HAVING count(*) < 2 ... = 0` would
-- be read as a query ending `< 3` compared against 0.
-- ASSERT ALWAYS: SELECT (SELECT count(*) FROM (SELECT country_id FROM deep_dive_stats GROUP BY country_id HAVING count(*) < 2)) = 0

-- AND NOTHING IS ORPHANED LATER EITHER.
-- ASSERT ALWAYS: SELECT count(*) FROM deep_dive_stat_translations t LEFT JOIN deep_dive_stats ds ON ds.id = t.stat_id WHERE ds.id IS NULL = 0

