-- ================================================================
-- The tile removals Dan reviewed by hand.
-- ================================================================
--
-- Generated by gen_dan_tile_removals.py -- edit that, not this.
--
-- 643 swept 43 tiles by rule and deliberately kept anything carrying a
-- year, because a year is usually a milestone. These 24 are the cases
-- where a dated tile still says only what a headline tile now says --
-- "2014 / B2G mandate in force" beside a B2G tile reading ACTIVE, with
-- the date already in the timeline below. No rule separates those from a
-- real milestone; a person reading the page does.
--
-- Belgium's "7 yrs / Archive requirement" is here too. 643 held it back
-- because it CONTRADICTED the headline tile (7 vs 10) and deleting one
-- side would have settled that silently. Dan has settled it: 10 stands.
-- ================================================================

-- ---- the removals -------------------------------------------------

-- Austria: 2014 / B2G mandate in force
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Austria' AND t.stat_label = 'B2G mandate in force');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Austria' AND t.stat_id IS NULL);

-- Belgium: 7 yrs / Archive requirement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Belgium' AND t.stat_label = 'Archive requirement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Belgium' AND t.stat_id IS NULL);

-- Belgium: 2028 / E-reporting go-live
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Belgium' AND t.stat_label = 'E-reporting go-live');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Belgium' AND t.stat_id IS NULL);

-- Croatia: 20th / Monthly e-report deadline
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Croatia' AND t.stat_label = 'Monthly e-report deadline');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Croatia' AND t.stat_id IS NULL);

-- Cyprus: 2019/2020 / B2G receive mandate in force
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Cyprus' AND t.stat_label = 'B2G receive mandate in force');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Cyprus' AND t.stat_id IS NULL);

-- Czech Republic: 2016 / B2G receive mandate in force
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Czech Republic' AND t.stat_label = 'B2G receive mandate in force');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Czech Republic' AND t.stat_id IS NULL);

-- Estonia: 1 Jul 2019 / B2G e-invoicing mandatory for the public sector
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Estonia' AND t.stat_label = 'B2G e-invoicing mandatory for the public sector');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Estonia' AND t.stat_id IS NULL);

-- Finland: No B2B / mandate — none confirmed
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Finland' AND t.stat_label = 'mandate — none confirmed');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Finland' AND t.stat_id IS NULL);

-- Greece: Sep 2025 / B2G fully mandatory
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Greece' AND t.stat_label = 'B2G fully mandatory');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Greece' AND t.stat_id IS NULL);

-- Greece: 2 Mar 2026 / B2B Phase 1 (in force)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Greece' AND t.stat_label = 'B2B Phase 1 (in force)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Greece' AND t.stat_id IS NULL);

-- Hungary: 1 Jul 2018 / RTIR real-time invoice-data reporting launches
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Hungary' AND t.stat_label = 'RTIR real-time invoice-data reporting launches');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Hungary' AND t.stat_id IS NULL);

-- Hungary: 1 Jul 2025 / First real e-invoicing mandate begins (energy/water B2B)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Hungary' AND t.stat_label = 'First real e-invoicing mandate begins (energy/water B2B)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Hungary' AND t.stat_id IS NULL);

-- Ireland: 2018 / OGP named Irish Peppol Authority
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Ireland' AND t.stat_label = 'OGP named Irish Peppol Authority');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Ireland' AND t.stat_id IS NULL);

-- Latvia: 1 Jan 2025 / B2G e-invoicing: all companies must issue structured e-invoices to government
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Latvia' AND t.stat_label = 'B2G e-invoicing: all companies must issue structured e-invoices to government');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Latvia' AND t.stat_id IS NULL);

-- Latvia: 1 Jan 2026 / Mandatory e-invoice data reporting to VID begins (B2G/G2G/G2B)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Latvia' AND t.stat_label = 'Mandatory e-invoice data reporting to VID begins (B2G/G2G/G2B)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Latvia' AND t.stat_id IS NULL);

-- Lithuania: 1 Jul 2017 / B2G e-invoicing mandatory for all public procurement
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Lithuania' AND t.stat_label = 'B2G e-invoicing mandatory for all public procurement');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Lithuania' AND t.stat_id IS NULL);

-- Luxembourg: 2023 / B2G fully in force
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Luxembourg' AND t.stat_label = 'B2G fully in force');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Luxembourg' AND t.stat_id IS NULL);

-- Netherlands: 2017/2019 / B2G mandate in force
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Netherlands' AND t.stat_label = 'B2G mandate in force');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Netherlands' AND t.stat_id IS NULL);

-- Norway: Jun 2026 / Law formally enacted
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Norway' AND t.stat_label = 'Law formally enacted');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Norway' AND t.stat_id IS NULL);

-- Portugal: No B2B / mandate — yet
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Portugal' AND t.stat_label = 'mandate — yet');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Portugal' AND t.stat_id IS NULL);

-- Serbia: 1 Jan 2023 / B2B e-invoicing (issuance and receipt) becomes mandatory nationwide
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Serbia' AND t.stat_label = 'B2B e-invoicing (issuance and receipt) becomes mandatory nationwide');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Serbia' AND t.stat_id IS NULL);

-- Slovenia: 1 Jan 2015 / Public sector required to receive e-invoices (ZOPSPU/ZOPSPU-A)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Slovenia' AND t.stat_label = 'Public sector required to receive e-invoices (ZOPSPU/ZOPSPU-A)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Slovenia' AND t.stat_id IS NULL);

-- Spain: 2015 / B2G (FACe) mandatory since
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Spain' AND t.stat_label = 'B2G (FACe) mandatory since');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Spain' AND t.stat_id IS NULL);

-- Sweden: No B2B / Domestic mandate — none yet
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Sweden' AND t.stat_label = 'Domestic mandate — none yet');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Sweden' AND t.stat_id IS NULL);

-- ---- what this migration claims it did ------------------------------

-- 24 tiles named above, from 311, leaving 287.
-- ASSERT: SELECT count(*) FROM deep_dive_stats = 287

-- Every language went with them; no orphaned translation rows.
-- ASSERT: SELECT count(*) FROM deep_dive_stat_translations t LEFT JOIN deep_dive_stats ds ON ds.id = t.stat_id WHERE ds.id IS NULL = 0

-- ---- and what must stay true afterwards -----------------------------

-- THE FLOOR DROPS FROM THREE TO TWO, and that is a real consequence of
-- this list rather than a loosened check. 643 asserted every country kept
-- at least three tiles; Cyprus loses its B2G receive tile here and is
-- left with two ("2x / Issuance mandates proposed, then dropped" and
-- "2030 / EU cross-border floor"). Two is the new floor and is asserted
-- so the next sweep cannot quietly empty a strip.
--
-- Wrapped in a subquery: the runner splits on the LAST comparison
-- operator, so a bare `... HAVING count(*) < 2 ... = 0` would be read as
-- a query ending `< 2` compared against 0.
-- ASSERT ALWAYS: SELECT (SELECT count(*) FROM (SELECT country_id FROM deep_dive_stats GROUP BY country_id HAVING count(*) < 2)) = 0

-- ASSERT ALWAYS: SELECT count(*) FROM deep_dive_stat_translations t LEFT JOIN deep_dive_stats ds ON ds.id = t.stat_id WHERE ds.id IS NULL = 0

