-- ================================================================
-- Dan's Asia-Pacific tile removals -- the last regional pass.
-- ================================================================
--
-- Generated by gen_apac_tile_removals.py -- edit that, not this.
--
-- Fifteen tiles. Most are dated milestones restating a headline tile;
-- Australia's and Japan's are the status word itself sitting under a
-- mandate tile printing the same word, which 643's rule missed because
-- "No B2B" is a value carrying half of its own label. Singapore's Peppol
-- history and the Philippines' TRAIN Law citation duplicate nothing and
-- are here on judgement, like Qatar's VAT tile in 646.
--
-- With this pass: 90 tiles removed of the original 354, 264 left.
-- ================================================================

-- ---- the removals -------------------------------------------------

-- Australia: No B2B / Mandate — voluntary only
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Australia' AND t.stat_label = 'Mandate — voluntary only');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Australia' AND t.stat_id IS NULL);

-- Australia: 2022 / B2G receiving mandate since
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Australia' AND t.stat_label = 'B2G receiving mandate since');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Australia' AND t.stat_id IS NULL);

-- Azerbaijan: 1 Apr 2017 / The e-qaimə mandate begins, under Tax Code Article 71-1
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Azerbaijan' AND t.stat_label = 'The e-qaimə mandate begins, under Tax Code Article 71-1');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Azerbaijan' AND t.stat_id IS NULL);

-- China: Dec 2024 / Nationwide since
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'China' AND t.stat_label = 'Nationwide since');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'China' AND t.stat_id IS NULL);

-- India: 2020 / Mandatory since October
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'India' AND t.stat_label = 'Mandatory since October');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'India' AND t.stat_id IS NULL);

-- Indonesia: 1 Jul 2016 / e-Faktur becomes mandatory nationwide
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Indonesia' AND t.stat_label = 'e-Faktur becomes mandatory nationwide');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Indonesia' AND t.stat_id IS NULL);

-- Indonesia: 1 Jan 2025 / Coretax platform launches
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Indonesia' AND t.stat_label = 'Coretax platform launches');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Indonesia' AND t.stat_id IS NULL);

-- Japan: Voluntary / JP PINT/Peppol e-invoicing adoption
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Japan' AND t.stat_label = 'JP PINT/Peppol e-invoicing adoption');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Japan' AND t.stat_id IS NULL);

-- Kazakhstan: 2014 / IS ESF launches as a voluntary pilot -- 12 years of history by the 2026 expansion
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Kazakhstan' AND t.stat_label = 'IS ESF launches as a voluntary pilot -- 12 years of history by the 2026 expansion');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Kazakhstan' AND t.stat_id IS NULL);

-- Kazakhstan: 1 Jan 2019 / E-invoicing becomes mandatory for all VAT-registered taxpayers
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Kazakhstan' AND t.stat_label = 'E-invoicing becomes mandatory for all VAT-registered taxpayers');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Kazakhstan' AND t.stat_id IS NULL);

-- Pakistan: 31 Dec 2025 / Formal deadline for all registered persons to integrate
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Pakistan' AND t.stat_label = 'Formal deadline for all registered persons to integrate');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Pakistan' AND t.stat_id IS NULL);

-- Philippines: 2018 / TRAIN Law establishes the legal basis (RA 10963)
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Philippines' AND t.stat_label = 'TRAIN Law establishes the legal basis (RA 10963)');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Philippines' AND t.stat_id IS NULL);

-- Singapore: 2018 / First Peppol Authority outside Europe
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Singapore' AND t.stat_label = 'First Peppol Authority outside Europe');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Singapore' AND t.stat_id IS NULL);

-- Taiwan: 1 May 2017 / Cross-border VAT/eGUI regime for foreign digital providers begins
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Taiwan' AND t.stat_label = 'Cross-border VAT/eGUI regime for foreign digital providers begins');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Taiwan' AND t.stat_id IS NULL);

-- Uzbekistan: 1 Jan 2020 / Electronic invoicing becomes mandatory for all business entities
DELETE FROM deep_dive_stat_translations WHERE stat_id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    JOIN deep_dive_stat_translations t ON t.stat_id = ds.id AND t.lang = 'en'
   WHERE c.name_en = 'Uzbekistan' AND t.stat_label = 'Electronic invoicing becomes mandatory for all business entities');
DELETE FROM deep_dive_stats WHERE id IN (
  SELECT ds.id FROM deep_dive_stats ds
    JOIN countries c ON c.id = ds.country_id
    LEFT JOIN deep_dive_stat_translations t ON t.stat_id = ds.id
   WHERE c.name_en = 'Uzbekistan' AND t.stat_id IS NULL);

-- ---- what this migration claims it did ------------------------------

-- 15 tiles named above, from 279, leaving 264.
-- ASSERT: SELECT count(*) FROM deep_dive_stats = 264

-- Every language went with them; no orphaned translation rows.
-- ASSERT: SELECT count(*) FROM deep_dive_stat_translations t LEFT JOIN deep_dive_stats ds ON ds.id = t.stat_id WHERE ds.id IS NULL = 0

-- CYPRUS IS STILL THE ONLY COUNTRY AT TWO. Australia, Indonesia,
-- Kazakhstan and Japan each lose enough to reach three, and three of
-- those lose two tiles apiece -- so the floor is checked here rather
-- than assumed to have survived a fourth pass.
-- ASSERT: SELECT (SELECT count(*) FROM (SELECT country_id FROM deep_dive_stats GROUP BY country_id HAVING count(*) < 3)) = 1

