-- ================================================================
-- The PDF names every benefit, not just the priced ones.
-- ================================================================
--
-- Dan, 26 August 2026: "I would like to support the business case by
-- acknowledging all benefits, including intangible benefits ... I'd like
-- for the reader of the PDF to understand the whole project benefits,
-- not just the commercial savings which are listed next to the pie
-- chart. Importantly, I'd like this information to appear only on page
-- one, and not spill into a second page. So page real-estate is
-- important."
--
-- Generated by gen_pdf_benefits_strings.py -- edit the generator.
--
-- ---- WHAT THIS PAID FOR IN SPACE, AND A DEFECT IT UNCOVERED ---------
--
-- Page one had no room. Measured across all four languages at A4 width,
-- the free space below the existing content ran from 159px in English
-- down to 42px in German at the eleven-jurisdiction default -- and went
-- NEGATIVE well inside normal use. Real page counts of the document as
-- it shipped on 25 August:
--
--     lang   n=20   n=30   n=45   n=70
--     en        2      2      3      3
--     de        2      3      3      3
--     fr        2      3      3      3
--     es        3      3      3      3
--
-- Spanish was printing three pages at twenty jurisdictions. Dan's rule
-- from 15 August is "It should be no longer than 2 pages", so that was a
-- standing defect that predates this change and that nobody had
-- measured. The wave-table cap in roi-render.mjs fixes it.
--
-- ---- ONE FACT, TWO SURFACES -----------------------------------------
--
-- These are shorter restatements of section 4's "named, not priced"
-- rows, because that copy is written for a full-width scrolling column
-- and does not fit a 166px card. The NUMBERS are the same numbers, and
-- tests/roi-pdf-benefits.mjs asserts the two surfaces still agree on
-- them -- two copies of a figure is how this project's Ardent
-- discrepancy happened.
-- ================================================================


INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.h.benefits', 'en', 'Benefits this model does not price');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.h.benefits', 'de', 'Nutzen, den dieses Modell nicht beziffert');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.h.benefits', 'fr', 'Bénéfices que ce modèle ne chiffre pas');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.h.benefits', 'es', 'Beneficios que este modelo no cuantifica');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.lede', 'en', 'The case above prices only what a number can defend. These are real too &mdash; Grade A evidence is cited, and the rest are named rather than guessed.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.lede', 'de', 'Die Rechnung oben beziffert nur, was sich mit einer Zahl belegen lässt. Auch das Folgende ist real &mdash; Belege der Stufe A sind angegeben, alles Übrige wird benannt statt geschätzt.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.lede', 'fr', 'Le calcul ci-dessus ne chiffre que ce qu&rsquo;un nombre peut défendre. Ces bénéfices sont réels aussi &mdash; les preuves de grade A sont citées, le reste est nommé plutôt qu&rsquo;estimé.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.lede', 'es', 'El cálculo anterior solo cuantifica lo que una cifra puede defender. Estos también son reales &mdash; se cita la evidencia de grado A y el resto se nombra en lugar de estimarse.');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycle', 'en', 'Faster cycle time, fewer supplier queries');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycle', 'de', 'Kürzere Durchlaufzeit, weniger Lieferantenanfragen');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycle', 'fr', 'Délais raccourcis, moins de relances fournisseurs');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycle', 'es', 'Ciclo más corto, menos consultas de proveedores');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleD', 'en', '2.9 vs 13.5 days; queries 12.8% vs 24.0% of AP time.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleD', 'de', '2,9 statt 13,5 Tage; Anfragen 12,8 % statt 24,0 % der Kreditorenzeit.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleD', 'fr', '2,9 contre 13,5 jours ; relances 12,8 % contre 24,0 % du temps fournisseurs.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleD', 'es', '2,9 frente a 13,5 días; consultas 12,8 % frente a 24,0 % del tiempo de cuentas a pagar.');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleSrc', 'en', 'Ardent Partners 2025 &mdash; A');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleSrc', 'de', 'Ardent Partners 2025 &mdash; A');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleSrc', 'fr', 'Ardent Partners 2025 &mdash; A');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.cycleSrc', 'es', 'Ardent Partners 2025 &mdash; A');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paper', 'en', 'Paper, print, postage, storage');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paper', 'de', 'Papier, Druck, Porto, Archivierung');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paper', 'fr', 'Papier, impression, affranchissement, archivage');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paper', 'es', 'Papel, impresión, franqueo, archivo');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperD', 'en', 'AUD 30.87 vs 9.18 an invoice.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperD', 'de', '30,87 AUD statt 9,18 AUD je Rechnung.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperD', 'fr', '30,87 AUD contre 9,18 AUD par facture.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperD', 'es', '30,87 AUD frente a 9,18 AUD por factura.');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperSrc', 'en', 'ATO / Deloitte &mdash; A');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperSrc', 'de', 'ATO / Deloitte &mdash; A');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperSrc', 'fr', 'ATO / Deloitte &mdash; A');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.paperSrc', 'es', 'ATO / Deloitte &mdash; A');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penalty', 'en', 'Penalty &amp; remediation exposure avoided');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penalty', 'de', 'Vermiedene Bußgeld- und Nachbesserungsrisiken');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penalty', 'fr', 'Risque de sanctions et de reprise évité');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penalty', 'es', 'Exposición a sanciones y subsanación evitada');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penaltyD', 'en', '{0} of your jurisdictions publish a schedule. Size it per country.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penaltyD', 'de', '{0} Ihrer Länder veröffentlichen einen Bußgeldkatalog. Je Land zu beziffern.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penaltyD', 'fr', '{0} de vos juridictions publient un barème. À chiffrer pays par pays.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.penaltyD', 'es', '{0} de sus jurisdicciones publican un baremo. Cuantifíquelo por país.');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraud', 'en', 'Fraud detection, working-capital visibility');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraud', 'de', 'Betrugserkennung, Transparenz im Working Capital');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraud', 'fr', 'Détection de fraude, visibilité sur le BFR');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraud', 'es', 'Detección de fraude, visibilidad del circulante');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraudD', 'en', 'No published benchmark.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraudD', 'de', 'Kein veröffentlichter Benchmark.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraudD', 'fr', 'Aucun référentiel publié.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.fraudD', 'es', 'Sin referencia publicada.');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.vat', 'en', '<strong>VAT leakage / gap recovery</strong> is often quoted, is not defensible, and is excluded from this model entirely.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.vat', 'de', '<strong>Mehrwertsteuerausfälle / Rückgewinnung der Steuerlücke</strong> werden oft genannt, sind nicht belegbar und bleiben in diesem Modell vollständig unberücksichtigt.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.vat', 'fr', '<strong>Les pertes de TVA / la récupération de l&rsquo;écart de TVA</strong> sont souvent citées, ne sont pas défendables et sont entièrement exclues de ce modèle.');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.ben.vat', 'es', '<strong>Las fugas de IVA / recuperación de la brecha</strong> se citan a menudo, no son defendibles y quedan totalmente excluidas de este modelo.');

INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.planFrom', 'en', '{0} onward');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.planFrom', 'de', 'ab {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.planFrom', 'fr', 'à partir du {0}');
INSERT OR REPLACE INTO translations (namespace, key, lang, value)
  VALUES ('roi', 'pdf.planFrom', 'es', 'desde {0}');

-- ---- what this migration claims it did ------------------------------

-- ASSERT: SELECT (SELECT count(*) FROM translations WHERE namespace = 'roi' AND key LIKE 'pdf.ben.%' OR namespace = 'roi' AND key IN ('pdf.h.benefits','pdf.planFrom')) = 56

-- ---- and what must stay true afterwards -----------------------------

-- FOUR LANGUAGES OR NONE.
--
-- getRoiStrings COALESCEs per key, so a missing German value renders an
-- English card in the middle of a German document and nothing anywhere
-- says so. It is also a LAYOUT risk here and not only a reading one:
-- German runs longer than English, and the fit of this block was
-- measured with the German strings in place. A key that falls back to
-- English is measured against the wrong length.
-- ASSERT ALWAYS: SELECT (SELECT count(*) FROM translations t WHERE t.namespace = 'roi' AND (t.key LIKE 'pdf.ben.%' OR t.key IN ('pdf.h.benefits','pdf.planFrom')) AND (SELECT count(*) FROM translations x WHERE x.namespace = 'roi' AND x.key = t.key) <> 4) = 0

-- NO CARD CARRIES A SOURCE IT HAS NOT EARNED.
--
-- Dan asked for Grade A citations only. Two of the four rows are Grade A
-- on this site's grading and carry a source; penalty exposure and fraud
-- are Grade D and carry none. If a *Src key ever appears for either, the
-- document is claiming evidence that does not exist.
-- ASSERT ALWAYS: SELECT (SELECT count(*) FROM translations WHERE namespace = 'roi' AND key IN ('pdf.ben.penaltySrc','pdf.ben.fraudSrc','pdf.ben.vatSrc')) = 0

