-- Liechtenstein: milestones + English translations. Generated by
-- new_country_scaffold.py; INSERT OR IGNORE throughout (idempotent).

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope, obligation_status) SELECT 'li-eea-einvoicing-incorporated', id, '2016-01-01', 1, 'https://www.efta.int/eea-lex/32014l0055', 0, '[]', NULL, 'none', 'unreviewed' FROM countries WHERE code = 'LI';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('li-eea-einvoicing-incorporated', 'en', 'EEA Joint Committee Decision 166/2015 brings the EU e-invoicing directive into the EEA Agreement', 'Decision 166/2015 of 11 June 2015 incorporated Directive 2014/55/EU into Annex XVI of the EEA Agreement, entering into force on 1 January 2016. Liechtenstein notified fulfilment of its constitutional requirements on 19 November 2015. This is the route by which a non-EU state acquired a European e-invoicing obligation.', '["Read as background to the 2018 obligation, not as a duty in itself"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope, obligation_status) SELECT 'li-b2g-receive', id, '2018-11-27', 0, 'https://www.efta.int/eea-lex/32014l0055', 1, '[{"label": "Public Procurement Department", "url": "https://www.llv.li/en/national-administration/public-procurement-department"}]', NULL, 'none', 'live' FROM countries WHERE code = 'LI';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('li-b2g-receive', 'en', 'Contracting authorities must accept and process EN 16931 electronic invoices', 'The EEA compliance date for Directive 2014/55/EU. Liechtenstein''s contracting authorities must receive and process electronic invoices conforming to the European standard for procurement above EU thresholds. The duty is on the authority to receive, not on the supplier to send: issuing electronically remains the supplier''s choice.', '["You may invoice the administration electronically; you are not obliged to", "There is no national platform -- above-threshold invoices are sent to the contracting authority by email"]');

INSERT OR IGNORE INTO milestones (id, country_id, date, anchor, source_url, on_tracker, portals, confidence, mandate_scope, obligation_status) SELECT 'li-emwst-portalpflicht', id, '2025-01-01', 0, 'https://www.llv.li/serviceportal2/amtsstellen/steuerverwaltung/newsletter/stv_newsletter_uebersicht.pdf', 1, '[{"label": "eMWST -- VAT filing portal", "url": "https://www.llv.li/en/national-administration/fiscal-authority/value-added-tax/e-mwst"}]', NULL, 'none', 'live' FROM countries WHERE code = 'LI';
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('li-emwst-portalpflicht', 'en', 'VAT returns must be filed through the eMWST portal', 'The Steuerverwaltung''s eMWST portal became the mandatory channel for VAT returns. This is a filing-channel obligation and not a digital reporting requirement: periodic return data is submitted, and no invoice-level or transaction-level detail reaches the authority.', '["Register for eMWST if you file Liechtenstein VAT", "Do not read this as e-reporting -- no invoice data is transmitted"]');

-- ---- what this migration claims it did (see apply_migrations.py) ----
-- The on_tracker count is the one to watch: it decides what appears on
-- the arrivals board, and getting it wrong is invisible in SQL and
-- obvious on the live site.
--
-- ASSERT: SELECT count(*) FROM milestones WHERE country_id = (SELECT id FROM countries WHERE code = 'LI') = 3
-- ASSERT: SELECT count(*) FROM milestones WHERE on_tracker = 1 AND country_id = (SELECT id FROM countries WHERE code = 'LI') = 2
-- ASSERT: SELECT count(*) FROM milestone_translations WHERE lang = 'en' AND milestone_id IN ('li-eea-einvoicing-incorporated','li-b2g-receive','li-emwst-portalpflicht') = 3
-- ASSERT: SELECT count(*) FROM milestones WHERE obligation_status = 'live' AND id IN ('li-eea-einvoicing-incorporated','li-b2g-receive','li-emwst-portalpflicht') = 2

-- WHY li-b2g-receive CARRIES mandate_scope = 'none' AND NOT 'b2g_only'.
--
-- Corrected 27 August 2026, after tests/map-tiles-agree.mjs refused the
-- country: "the map says B2G only -- government mandate real, no B2B
-- mandate, but the tiles say B2G VOLUNTARY / B2B NO_MANDATE". It was
-- right, and the milestone was the side that was wrong.
--
-- 'b2g_only' means a mandate restricted to invoicing the government --
-- a duty on the SUPPLIER to issue. Liechtenstein has no such duty. What
-- it has is a duty on the contracting AUTHORITY to receive and process,
-- which is the third value's territory exactly: real and binding, but
-- not itself an e-invoicing-mandate-scope fact.
--
-- Cyprus is the precedent and it runs the same way. Its 2020 milestone,
-- "Sub-central public bodies must also receive e-invoices", is on the
-- board with mandate_scope = 'none' -- and Cyprus's B2G tile reads
-- VOLUNTARY, as Liechtenstein's does. The two off-board Cypriot and
-- Czech receive milestones do carry 'b2g_only', which is survivable
-- because The Map only reads on-board rows; putting one on the board is
-- what surfaces the disagreement.
--
-- The lesson generalises past this country: mandate_scope answers "what
-- kind of obligation is this, and on whom", not "what is this milestone
-- about". A receive duty is about B2G and is not a B2G mandate.
