-- Ghana: country row + name translations. Generated by
-- new_country_scaffold.py; INSERT OR IGNORE throughout (idempotent).

-- roi_complexity and eu_member are written explicitly, never left to
-- the column defaults. 'none' would price the country at zero
-- integrations in the ROI planner and exempt it from the weekly
-- complexity review, which only scans countries rated 'simple'.
INSERT OR IGNORE INTO countries (code, name_en, region, slug, in_picker, roi_complexity, eu_member) VALUES ('GH', 'Ghana', 'Middle East / Africa', 'ghana', 1, 'complex', 0);

INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'en', 'Ghana' FROM countries WHERE code = 'GH';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'es', 'Ghana' FROM countries WHERE code = 'GH';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'de', 'Ghana' FROM countries WHERE code = 'GH';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'fr', 'Ghana' FROM countries WHERE code = 'GH';

-- ---- what this migration claims it did (see apply_migrations.py) ----
-- INSERT OR IGNORE cannot fail; it can only decline. Assert the row
-- and all four display names are actually there, so a code that
-- collides with an existing country is caught in replay rather than
-- discovered as a missing menu entry.
--
-- ASSERT: SELECT count(*) FROM countries WHERE code = 'GH' = 1
-- ASSERT: SELECT in_picker FROM countries WHERE code = 'GH' = 1
-- ASSERT: SELECT roi_complexity FROM countries WHERE code = 'GH' = 'complex'
-- ASSERT: SELECT eu_member FROM countries WHERE code = 'GH' = 0
-- ASSERT: SELECT count(*) FROM country_translations WHERE country_id = (SELECT id FROM countries WHERE code = 'GH') = 4
