-- Switzerland: country row + name translations. Generated by
-- new_country_scaffold.py; INSERT OR IGNORE throughout (idempotent).

-- roi_complexity and eu_member are written explicitly, never left to
-- the column defaults. 'none' would price the country at zero
-- integrations in the ROI planner and exempt it from the weekly
-- complexity review, which only scans countries rated 'simple'.
INSERT OR IGNORE INTO countries (code, name_en, region, slug, in_picker, roi_complexity, eu_member) VALUES ('CH', 'Switzerland', 'Europe', 'switzerland', 1, 'simple', 0);

INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'en', 'Switzerland' FROM countries WHERE code = 'CH';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'es', 'Suiza' FROM countries WHERE code = 'CH';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'de', 'Schweiz' FROM countries WHERE code = 'CH';
INSERT OR IGNORE INTO country_translations (country_id, lang, display_name) SELECT id, 'fr', 'Suisse' FROM countries WHERE code = 'CH';

-- ---- what this migration claims it did (see apply_migrations.py) ----
-- INSERT OR IGNORE cannot fail; it can only decline. Assert the row
-- and all four display names are actually there, so a code that
-- collides with an existing country is caught in replay rather than
-- discovered as a missing menu entry.
--
-- ASSERT: SELECT count(*) FROM countries WHERE code = 'CH' = 1
-- ASSERT: SELECT in_picker FROM countries WHERE code = 'CH' = 1
-- ASSERT: SELECT roi_complexity FROM countries WHERE code = 'CH' = 'simple'
-- ASSERT: SELECT eu_member FROM countries WHERE code = 'CH' = 0
-- ASSERT: SELECT count(*) FROM country_translations WHERE country_id = (SELECT id FROM countries WHERE code = 'CH') = 4
