-- Bundle 2, sample set: compliance_model for eight countries and portal
-- labels for four. GENERATED by gen_sample_model_and_labels.py -- edit
-- the generator, which refuses to emit anything breaching
-- DEEP-DIVE-FRAMEWORK.md.
--
-- Pure content UPDATE. No schema change, no static file, no worker
-- redeploy -- the same shape as migration 355, which was the first
-- attempt to correct this drift.
--
-- Every SET is guarded on (country, lang) ONLY, with no value guard, so
-- it cannot silently match zero rows. That is migration 500's rule and
-- it is why 470, 480 and 490 each ran clean and did nothing.

-- Hong Kong
UPDATE deep_dive_page_translations SET compliance_model = 'No mandate — no VAT or GST, so no tax invoice exists in law' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hong Kong');
UPDATE deep_dive_page_translations SET compliance_model = 'Sin obligación — sin IVA, y por tanto sin factura fiscal' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hong Kong');
UPDATE deep_dive_page_translations SET compliance_model = 'Keine Pflicht — keine Mehrwertsteuer, also keine Steuerrechnung' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hong Kong');
UPDATE deep_dive_page_translations SET compliance_model = 'Aucune obligation — pas de TVA, donc pas de facture fiscale' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hong Kong');

-- Switzerland
UPDATE deep_dive_page_translations SET compliance_model = 'Contractual B2G duty — non-paper, not structured' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Switzerland');
UPDATE deep_dive_page_translations SET compliance_model = 'Deber B2G contractual — sin papel, no estructurado' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Switzerland');
UPDATE deep_dive_page_translations SET compliance_model = 'Vertragliche B2G-Pflicht — papierlos, nicht strukturiert' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Switzerland');
UPDATE deep_dive_page_translations SET compliance_model = 'Obligation B2G contractuelle — sans papier, non structurée' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Switzerland');

-- Bahrain
UPDATE deep_dive_page_translations SET compliance_model = 'No mandate — voluntary, with no draft law or timeline' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Bahrain');
UPDATE deep_dive_page_translations SET compliance_model = 'Sin obligación — voluntario, sin proyecto de ley ni plazo' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Bahrain');
UPDATE deep_dive_page_translations SET compliance_model = 'Keine Pflicht — freiwillig, ohne Gesetzentwurf oder Termin' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Bahrain');
UPDATE deep_dive_page_translations SET compliance_model = 'Aucune obligation — volontaire, sans projet de loi ni date' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Bahrain');

-- Hungary
UPDATE deep_dive_page_translations SET compliance_model = 'Real-time reporting (RTIR) — no B2B exchange mandate' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hungary');
UPDATE deep_dive_page_translations SET compliance_model = 'Reporte en tiempo real (RTIR) — sin intercambio B2B obligatorio' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hungary');
UPDATE deep_dive_page_translations SET compliance_model = 'Echtzeitmeldung (RTIR) — keine B2B-Austauschpflicht' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hungary');
UPDATE deep_dive_page_translations SET compliance_model = 'Déclaration en temps réel (RTIR) — pas d''échange B2B imposé' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Hungary');

-- Taiwan
UPDATE deep_dive_page_translations SET compliance_model = 'Post-issuance transmission (eGUI) — mandatory since 2021' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Taiwan');
UPDATE deep_dive_page_translations SET compliance_model = 'Transmisión posterior a la emisión (eGUI) — obligatoria desde 2021' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Taiwan');
UPDATE deep_dive_page_translations SET compliance_model = 'Übermittlung nach Ausstellung (eGUI) — Pflicht seit 2021' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Taiwan');
UPDATE deep_dive_page_translations SET compliance_model = 'Transmission après émission (eGUI) — obligatoire depuis 2021' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Taiwan');

-- Kenya
UPDATE deep_dive_page_translations SET compliance_model = 'Centralised CTC (eTIMS) — enforced via expense deductibility' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Kenya');
UPDATE deep_dive_page_translations SET compliance_model = 'CTC centralizado (eTIMS) — exigido vía deducibilidad del gasto' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Kenya');
UPDATE deep_dive_page_translations SET compliance_model = 'Zentrales CTC (eTIMS) — durchgesetzt über die Abzugsfähigkeit' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Kenya');
UPDATE deep_dive_page_translations SET compliance_model = 'CTC centralisé (eTIMS) — imposé par la déductibilité des charges' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Kenya');

-- Portugal
UPDATE deep_dive_page_translations SET compliance_model = 'Certified-software regime — B2G structured mandate only' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Portugal');
UPDATE deep_dive_page_translations SET compliance_model = 'Régimen de software certificado — solo obligación B2G estructurada' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Portugal');
UPDATE deep_dive_page_translations SET compliance_model = 'Zertifizierte-Software-Regime — nur strukturierte B2G-Pflicht' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Portugal');
UPDATE deep_dive_page_translations SET compliance_model = 'Régime de logiciel certifié — obligation structurée B2G seule' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Portugal');

-- Costa Rica
UPDATE deep_dive_page_translations SET compliance_model = 'Real-time clearance (DGT) — migrating to TRIBU-CR' WHERE lang = 'en' AND country_id = (SELECT id FROM countries WHERE name_en = 'Costa Rica');
UPDATE deep_dive_page_translations SET compliance_model = 'Clearance en tiempo real (DGT) — en migración a TRIBU-CR' WHERE lang = 'es' AND country_id = (SELECT id FROM countries WHERE name_en = 'Costa Rica');
UPDATE deep_dive_page_translations SET compliance_model = 'Echtzeit-Freigabe (DGT) — Migration zu TRIBU-CR' WHERE lang = 'de' AND country_id = (SELECT id FROM countries WHERE name_en = 'Costa Rica');
UPDATE deep_dive_page_translations SET compliance_model = 'Dédouanement en temps réel (DGT) — migration vers TRIBU-CR' WHERE lang = 'fr' AND country_id = (SELECT id FROM countries WHERE name_en = 'Costa Rica');

-- ---- portal labels, matched on url so a reorder cannot mislabel ----
UPDATE deep_dive_portal_translations SET label = 'IRD — electronic filing of profits tax returns' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_epf.htm');
UPDATE deep_dive_portal_translations SET label = 'Hacienda — declaración electrónica de sociedades' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_epf.htm');
UPDATE deep_dive_portal_translations SET label = 'Steuerbehörde — elektronische Gewinnsteuererklärung' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_epf.htm');
UPDATE deep_dive_portal_translations SET label = 'Fisc — télédéclaration de l''impôt sur les bénéfices' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_epf.htm');
UPDATE deep_dive_portal_translations SET label = 'IRD — iXBRL filing and taxonomy' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_ixbrl.htm');
UPDATE deep_dive_portal_translations SET label = 'Hacienda — presentación en iXBRL y taxonomía' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_ixbrl.htm');
UPDATE deep_dive_portal_translations SET label = 'Steuerbehörde — iXBRL-Einreichung und Taxonomie' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_ixbrl.htm');
UPDATE deep_dive_portal_translations SET label = 'Fisc — dépôt en iXBRL et taxonomie' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_ixbrl.htm');
UPDATE deep_dive_portal_translations SET label = 'GovHK — e-Procurement Programme' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.gov.hk/en/theme/eprocurement/eppp/overview.htm');
UPDATE deep_dive_portal_translations SET label = 'GovHK — Programa de Contratación Electrónica' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.gov.hk/en/theme/eprocurement/eppp/overview.htm');
UPDATE deep_dive_portal_translations SET label = 'GovHK — e-Procurement-Programm' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.gov.hk/en/theme/eprocurement/eppp/overview.htm');
UPDATE deep_dive_portal_translations SET label = 'GovHK — programme e-Procurement' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.gov.hk/en/theme/eprocurement/eppp/overview.htm');
UPDATE deep_dive_portal_translations SET label = 'IRD — business record keeping' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_rke.htm');
UPDATE deep_dive_portal_translations SET label = 'Hacienda — llevanza de libros de empresa' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_rke.htm');
UPDATE deep_dive_portal_translations SET label = 'Steuerbehörde — Aufbewahrung von Unterlagen' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_rke.htm');
UPDATE deep_dive_portal_translations SET label = 'Fisc — tenue des livres d''entreprise' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Hong Kong' AND x.url = 'https://www.ird.gov.hk/eng/tax/bus_rke.htm');
UPDATE deep_dive_portal_translations SET label = 'EFV — sending an e-invoice to the Confederation' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/e-rechnungen-zustellen');
UPDATE deep_dive_portal_translations SET label = 'EFV — enviar una factura a la Confederación' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/e-rechnungen-zustellen');
UPDATE deep_dive_portal_translations SET label = 'EFV — E-Rechnung dem Bund zustellen' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/e-rechnungen-zustellen');
UPDATE deep_dive_portal_translations SET label = 'AFF — adresser une facture à la Confédération' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/e-rechnungen-zustellen');
UPDATE deep_dive_portal_translations SET label = 'EFV — federal units that receive e-invoices' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/liste-verwaltungseinheiten');
UPDATE deep_dive_portal_translations SET label = 'EFV — unidades federales que reciben facturas' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/liste-verwaltungseinheiten');
UPDATE deep_dive_portal_translations SET label = 'EFV — Verwaltungseinheiten mit E-Rechnungsempfang' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/liste-verwaltungseinheiten');
UPDATE deep_dive_portal_translations SET label = 'AFF — unités fédérales destinataires' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.efv.admin.ch/de/liste-verwaltungseinheiten');
UPDATE deep_dive_portal_translations SET label = 'BKB — procurement terms (clause 9.4)' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.bkb.admin.ch/de/agb-des-bundes');
UPDATE deep_dive_portal_translations SET label = 'BKB — condiciones de contratación (cláusula 9.4)' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.bkb.admin.ch/de/agb-des-bundes');
UPDATE deep_dive_portal_translations SET label = 'BKB — AGB des Bundes (Ziffer 9.4)' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.bkb.admin.ch/de/agb-des-bundes');
UPDATE deep_dive_portal_translations SET label = 'CA — conditions générales (clause 9.4)' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.bkb.admin.ch/de/agb-des-bundes');
UPDATE deep_dive_portal_translations SET label = 'ESTV — filing VAT online' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.estv.admin.ch/de/mwst-online-abrechnen');
UPDATE deep_dive_portal_translations SET label = 'AFC — declarar el IVA en línea' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.estv.admin.ch/de/mwst-online-abrechnen');
UPDATE deep_dive_portal_translations SET label = 'ESTV — MWST online abrechnen' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.estv.admin.ch/de/mwst-online-abrechnen');
UPDATE deep_dive_portal_translations SET label = 'AFC — déclarer la TVA en ligne' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Switzerland' AND x.url = 'https://www.estv.admin.ch/de/mwst-online-abrechnen');

-- ---- and two countries matched on sort_order ----
UPDATE deep_dive_portal_translations SET label = 'NBR — National Bureau for Revenue' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'NBR — Oficina Nacional de Ingresos' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'NBR — National Bureau for Revenue' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'NBR — Bureau national des recettes' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'Fonoa — prior-approval removal (industry)' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 1);
UPDATE deep_dive_portal_translations SET label = 'Fonoa — fin de la aprobación previa (sector)' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 1);
UPDATE deep_dive_portal_translations SET label = 'Fonoa — Ende der Vorabgenehmigung (Branche)' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 1);
UPDATE deep_dive_portal_translations SET label = 'Fonoa — fin de l''approbation préalable (secteur)' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Bahrain' AND x.sort_order = 1);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — Comprobantes Electrónicos API' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — API de Comprobantes Electrónicos' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — API Comprobantes Electrónicos' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — API Comprobantes Electrónicos' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 0);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — TRIBU-CR notices' WHERE lang = 'en' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 1);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — avisos TRIBU-CR' WHERE lang = 'es' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 1);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — TRIBU-CR-Mitteilungen' WHERE lang = 'de' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 1);
UPDATE deep_dive_portal_translations SET label = 'Hacienda — avis TRIBU-CR' WHERE lang = 'fr' AND portal_id = (SELECT x.id FROM deep_dive_portals x JOIN countries co ON co.id = x.country_id WHERE co.name_en = 'Costa Rica' AND x.sort_order = 1);

-- ---- what this migration claims it did ----
-- An UPDATE matching zero rows is not an error, so assert the VALUES,
-- not the row counts. Length is the whole point of the change.
-- ASSERT: SELECT count(*) FROM deep_dive_page_translations t JOIN countries c ON c.id = t.country_id WHERE c.name_en IN ('Hong Kong', 'Switzerland', 'Bahrain', 'Hungary', 'Taiwan', 'Kenya', 'Portugal', 'Costa Rica') AND t.lang = 'en' AND length(t.compliance_model) > 64 = 0
-- ASSERT: SELECT count(*) FROM deep_dive_page_translations t JOIN countries c ON c.id = t.country_id WHERE c.name_en IN ('Hong Kong', 'Switzerland', 'Bahrain', 'Hungary', 'Taiwan', 'Kenya', 'Portugal', 'Costa Rica') AND length(t.compliance_model) > 96 = 0
-- ASSERT: SELECT length(compliance_model) FROM deep_dive_page_translations t JOIN countries c ON c.id = t.country_id WHERE c.name_en = 'Hong Kong' AND t.lang = 'en' <= 64
-- ASSERT: SELECT length(compliance_model) FROM deep_dive_page_translations t JOIN countries c ON c.id = t.country_id WHERE c.name_en = 'Costa Rica' AND t.lang = 'en' <= 64
-- ASSERT: SELECT count(*) FROM deep_dive_portal_translations l JOIN deep_dive_portals x ON x.id = l.portal_id JOIN countries c ON c.id = x.country_id WHERE c.name_en IN ('Bahrain', 'Costa Rica', 'Hong Kong', 'Switzerland') AND l.lang = 'en' AND length(l.label) > 48 = 0
-- The guide's Model column clips the FIRST SENTENCE at 64. These eight
-- are single noun phrases, so the whole string must survive the clip:
-- ASSERT: SELECT count(*) FROM deep_dive_page_translations t JOIN countries c ON c.id = t.country_id WHERE c.name_en IN ('Hong Kong', 'Switzerland', 'Bahrain', 'Hungary', 'Taiwan', 'Kenya', 'Portugal', 'Costa Rica') AND t.lang = 'en' AND instr(t.compliance_model, '. ') > 0 = 0
