-- Thailand: milestone translations, es / de / fr. The English rows
-- shipped in 704.
--
-- One translation decision worth recording. "Voluntary" must not soften
-- into "not yet mandatory" -- noch nicht verpflichtend, aún no
-- obligatorio, pas encore obligatoire. That phrasing quietly implies a
-- mandate is scheduled, which is precisely the error three vendor pages
-- have made about this country. Every language below says the thing is
-- optional, not that it is pending.

-- ---- 1. Ministerial Regulation No. 384 ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-ministerial-reg-384', 'es', 'El Reglamento Ministerial n.º 384 autoriza los documentos fiscales electrónicos', 'Dictado el 8 de julio de 2022 al amparo del Código Fiscal, publicado en el Boletín Oficial el 20 de julio y en vigor treinta días después. Permite preparar, enviar y conservar documentos fiscales por vía electrónica. Conviene leer con cuidado lo que hace: autoriza, no obliga, y todos los instrumentos tailandeses posteriores han mantenido esa forma.', '["Trátelo como el permiso, no como un plazo"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-ministerial-reg-384', 'de', 'Die Ministerialverordnung Nr. 384 lässt elektronische Steuerdokumente zu', 'Erlassen am 8. Juli 2022 auf Grundlage der Abgabenordnung, am 20. Juli im Staatsanzeiger veröffentlicht und dreissig Tage später in Kraft. Sie erlaubt die elektronische Erstellung, Übermittlung und Aufbewahrung von Steuerdokumenten. Man lese genau, was sie tut: sie erlaubt, sie zwingt nicht — und jedes spätere thailändische Instrument hat diese Form beibehalten.', '["Als Erlaubnis lesen, nicht als Frist"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-ministerial-reg-384', 'fr', 'Le règlement ministériel n° 384 autorise les documents fiscaux électroniques', 'Pris le 8 juillet 2022 sur le fondement du Code des impôts, publié au Journal officiel le 20 juillet et entré en vigueur trente jours plus tard. Il permet d''établir, de transmettre et de conserver les documents fiscaux par voie électronique. Il faut lire précisément ce qu''il fait : il autorise, il n''oblige pas, et tous les instruments thaïlandais ultérieurs ont gardé cette forme.', '["À lire comme une autorisation, non comme une échéance"]');

-- ---- 2. the by-email / time stamp route ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-etax-by-timestamp', 'es', 'Entra en vigor la vía de factura electrónica con sello de tiempo para empresas menores', 'Anunciada por el Departamento de Hacienda el 12 de mayo de 2023 y vigente desde esta fecha. Un sujeto pasivo de IVA con ingresos anuales de hasta 30 millones de baht puede enviar por correo al comprador una factura en PDF/A-3, con copia a ETDA, que aplica un sello de tiempo de confianza y devuelve el archivo sellado a ambas partes. Los instrumentos la llaman vía de sello de tiempo; las páginas de usuario, factura por correo. Son lo mismo.', '["Compruebe el techo de 30 millones de baht antes de elegir esta vía", "No puede usar esta vía y el sistema XML completo a la vez"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-etax-by-timestamp', 'de', 'Der Zeitstempel-Weg der elektronischen Rechnung tritt für kleinere Unternehmen in Kraft', 'Von der Steuerbehörde am 12. Mai 2023 bekannt gegeben und ab diesem Datum wirksam. Ein MWST-Registrierter mit Jahresumsatz bis 30 Millionen Baht darf dem Käufer eine PDF/A-3-Rechnung per E-Mail senden, in Kopie an ETDA, die einen vertrauenswürdigen Zeitstempel setzt und die gestempelte Datei an beide zurückgibt. Die Instrumente nennen das den Zeitstempel-Weg, die Nutzerseiten die Rechnung per E-Mail. Es ist dasselbe.', '["Prüfen Sie die Grenze von 30 Millionen Baht, bevor Sie diesen Weg wählen", "Dieser Weg und das volle XML-System schliessen einander aus"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-etax-by-timestamp', 'fr', 'La voie de la facture électronique par horodatage entre en vigueur pour les petites entreprises', 'Annoncée par l''administration fiscale le 12 mai 2023 et applicable depuis cette date. Un assujetti à la TVA réalisant jusqu''à 30 millions de bahts de recettes annuelles peut adresser à l''acheteur une facture en PDF/A-3 par courriel, en copie à l''ETDA, qui appose un horodatage de confiance et renvoie le fichier horodaté aux deux parties. Les instruments parlent d''horodatage, les pages destinées aux usagers de facture par courriel. C''est la même chose.', '["Vérifiez le plafond de 30 millions de bahts avant de choisir cette voie", "Cette voie et le système XML complet s''excluent mutuellement"]');

-- ---- 3. the 200 per cent deduction ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-deduction-decree-766', 'es', 'Una deducción del 200 % por invertir en factura electrónica y retención electrónica', 'El Decreto Real n.º 766 concedió una doble deducción —el 100 % ordinario más otro 100— por la inversión en sistemas de factura electrónica, recibo electrónico y retención electrónica, incluidos equipos, programas y honorarios de proveedores. El anuncio de desarrollo del Director General lleva fecha de 28 de junio de 2023 y se aplicó con efectos retroactivos desde el 1 de enero de 2023. Tailandia impulsa la adopción con incentivos y no con obligaciones, y este es el ejemplo más claro.', '["Si invirtió entre 2023 y 2025, consulte el plazo de reclamación con su asesor"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-deduction-decree-766', 'de', 'Ein Abzug von 200 Prozent für Investitionen in E-Rechnung und E-Quellensteuer', 'Das Königliche Dekret Nr. 766 gewährte einen doppelten Abzug — die gewöhnlichen 100 Prozent und weitere 100 — für Investitionen in E-Rechnungs-, E-Quittungs- und E-Quellensteuersysteme, einschliesslich Hardware, Software und Dienstleisterhonoraren. Die Durchführungsbekanntmachung des Generaldirektors datiert vom 28. Juni 2023 und galt rückwirkend ab dem 1. Januar 2023. Thailand fördert die Einführung mit Anreizen statt mit Pflichten, und dies ist das deutlichste Beispiel.', '["Bei Investitionen zwischen 2023 und 2025 die Antragsfrist mit dem Berater klären"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-deduction-decree-766', 'fr', 'Une déduction de 200 % pour l''investissement en facture et retenue électroniques', 'Le décret royal n° 766 a accordé une double déduction — les 100 % ordinaires et 100 de plus — pour l''investissement dans les systèmes de facture électronique, de reçu électronique et de retenue à la source électronique, y compris matériel, logiciels et honoraires de prestataires. L''annonce d''application du Directeur général date du 28 juin 2023 et s''est appliquée rétroactivement au 1er janvier 2023. La Thaïlande encourage l''adoption par l''incitation et non par l''obligation ; c''est l''exemple le plus net.', '["Si vous avez investi entre 2023 et 2025, vérifiez le délai de réclamation avec votre conseil"]');

-- ---- 4. the board row ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-deduction-lapsed', 'es', 'Vence la deducción del 200 % y su reemplazo aún no es ley', 'El Decreto Real n.º 766 llegaba hasta el 31 de diciembre de 2025 y no se renovó antes de vencer. El 16 de junio de 2026 el Consejo de Ministros aprobó una prórroga de dos años con el mismo 200 % para 2026 y 2027, que además cubre los honorarios de evaluación de sistemas de ETDA, junto a una rebaja de la retención electrónica a un 1 % único. El Departamento de Hacienda lo anunció en la nota 14/2569. A 27 de agosto de 2026 no consta decreto real alguno en el índice del propio Departamento, de modo que el gasto de 2026 se apoya en una medida aprobada pero no promulgada.', '["No dé por segura la deducción de 2026 hasta que se publique el decreto real", "Vigile el índice de decretos, no la nota de prensa", "Documente igualmente facturas y honorarios de evaluación"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-deduction-lapsed', 'de', 'Der Abzug von 200 Prozent läuft aus, und sein Ersatz ist noch kein Recht', 'Das Königliche Dekret Nr. 766 lief bis zum 31. Dezember 2025 und wurde vor Ablauf nicht verlängert. Am 16. Juni 2026 billigte das Kabinett eine zweijährige Verlängerung mit denselben 200 Prozent für 2026 und 2027, die neu auch ETDA-Systemprüfungshonorare erfasst, samt einer Senkung der E-Quellensteuer auf einheitlich 1 Prozent. Die Steuerbehörde gab dies in der Mitteilung 14/2569 bekannt. Am 27. August 2026 findet sich im Dekretverzeichnis der Behörde kein umsetzendes Dekret, sodass Ausgaben des Jahres 2026 auf einer gebilligten, aber nicht verkündeten Massnahme beruhen.', '["Den Abzug für 2026 erst als sicher buchen, wenn das Dekret veröffentlicht ist", "Das Dekretverzeichnis beobachten, nicht die Pressemitteilung", "Rechnungen und Prüfungshonorare in jedem Fall dokumentieren"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-deduction-lapsed', 'fr', 'La déduction de 200 % expire et son remplacement n''est pas encore la loi', 'Le décret royal n° 766 courait jusqu''au 31 décembre 2025 et n''a pas été renouvelé avant son expiration. Le 16 juin 2026, le Conseil des ministres a approuvé une prorogation de deux ans au même taux de 200 % pour 2026 et 2027, couvrant désormais les honoraires d''évaluation des systèmes par l''ETDA, ainsi qu''une baisse de la retenue électronique à 1 % uniforme. L''administration fiscale l''a annoncé dans le communiqué 14/2569. Au 27 août 2026, aucun décret royal d''application ne figure à l''index de l''administration : les dépenses de 2026 reposent donc sur une mesure approuvée mais non promulguée.', '["Ne comptez pas la déduction 2026 comme acquise avant la publication du décret", "Surveillez l''index des décrets, non le communiqué", "Documentez de toute façon factures et honoraires d''évaluation"]');

-- ---- 5. enforcement ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-fake-invoice-operation', 'es', 'Se anuncia una segunda gran operación contra facturas falsas', 'La nota 20/2569 informa de una operación contra facturas fiscales fraudulentas con un perjuicio estimado en unos 360 millones de baht, tras otra actuación similar a principios de año. Se recoge aquí porque responde a la pregunta que de verdad se hace quien mira un país sin obligación: ¿dónde pone el esfuerzo la administración tributaria? En Tailandia, en la lucha contra el fraude y en los incentivos, no en obligar.', '["Espere escrutinio sobre la autenticidad de la factura, no sobre su formato"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-fake-invoice-operation', 'de', 'Eine zweite grosse Aktion gegen Scheinrechnungen wird bekannt gegeben', 'Die Mitteilung 20/2569 berichtet von einem Vorgehen gegen gefälschte Steuerrechnungen mit einem Schaden von rund 360 Millionen Baht, nach einer ähnlichen Aktion Anfang des Jahres. Sie steht hier, weil sie die Frage beantwortet, die man sich bei einem Land ohne Pflicht wirklich stellt: worauf verwendet die Steuerverwaltung ihre Kraft? In Thailand auf Betrugsbekämpfung und Anreize, nicht auf Verpflichtung.', '["Rechnen Sie mit Prüfungen der Echtheit, nicht des Formats"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('th-fake-invoice-operation', 'fr', 'Une deuxième grande opération contre les fausses factures est annoncée', 'Le communiqué 20/2569 fait état d''une opération contre des factures fiscales frauduleuses, pour un préjudice estimé à quelque 360 millions de bahts, après une action comparable en début d''année. Il figure ici parce qu''il répond à la question que l''on se pose vraiment devant un pays sans obligation : où l''administration fiscale met-elle son énergie ? En Thaïlande, dans la lutte contre la fraude et dans l''incitation, non dans la contrainte.', '["Attendez-vous à un contrôle de l''authenticité de la facture, non de son format"]');

-- ---- what this migration claims it did ----
-- ASSERT: SELECT count(*) FROM milestone_translations WHERE milestone_id IN ('th-ministerial-reg-384','th-etax-by-timestamp','th-deduction-decree-766','th-deduction-lapsed','th-fake-invoice-operation') = 20
-- ASSERT: SELECT count(*) FROM milestone_translations WHERE lang = 'de' AND milestone_id IN ('th-ministerial-reg-384','th-etax-by-timestamp','th-deduction-decree-766','th-deduction-lapsed','th-fake-invoice-operation') = 5
-- ASSERT ALWAYS: SELECT count(*) FROM milestones m WHERE (SELECT count(*) FROM milestone_translations t WHERE t.milestone_id = m.id) < 4 = 0
