-- Section-02 spine, 1 countries. GENERATED by tools/respine.mjs.
-- Re-run the tool rather than editing this file.
--
-- No prose is rewritten. Every row below is the row that was already
-- there, in all four languages, moved to the spine card its own key
-- routes it to. The tool refuses any country where a spine slot would
-- end up empty, so nothing here is a card invented to fill a hole.

-- ---- Singapore: 11 rows -> 3/3/3/2 plus one card kept whole ----
DELETE FROM deep_dive_card_translations WHERE card_id IN (SELECT d.id FROM deep_dive_cards d JOIN countries c ON c.id = d.country_id WHERE c.name_en = 'Singapore' AND d.section = 'file_format');
DELETE FROM deep_dive_cards WHERE section = 'file_format' AND country_id = (SELECT id FROM countries WHERE name_en = 'Singapore');
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 0 FROM countries WHERE name_en = 'Singapore';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'en', 'Format & standard', '[["Current standard","SG Peppol BIS Billing 3.0"],["Base","European Peppol BIS 3.0, extended for Singapore-specific requirements"],["Digital signature","Not required from the taxpayer"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 0;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'es', 'Formato y estándar', '[["Estándar actual","SG Peppol BIS Billing 3.0"],["Base","Peppol BIS 3.0 europeo, extendido para requisitos específicos de Singapur"],["Firma digital","No se requiere del contribuyente"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 0;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'de', 'Format und Standard', '[["Aktueller Standard","SG Peppol BIS Billing 3.0"],["Basis","Europäisches Peppol BIS 3.0, erweitert um Singapur-spezifische Anforderungen"],["Digitale Signatur","Vom Steuerpflichtigen nicht erforderlich"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 0;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'fr', 'Format et norme', '[["Norme actuelle","SG Peppol BIS Billing 3.0"],["Base","Peppol BIS 3.0 européen, étendu pour les exigences spécifiques à Singapour"],["Signature numérique","Non requise du contribuable"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 0;
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 1 FROM countries WHERE name_en = 'Singapore';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'en', 'Identifiers & registration', '[["Peppol ID base","Unique Entity Number (UEN)"],["Also underlies","PayNow Corporate (Singapore''s e-payment scheme)"],["Multi-entity businesses","Each GST-registered entity needs its own Peppol ID"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 1;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'es', 'Identificadores y registro', '[["Base del ID Peppol","Número de Entidad Único (UEN)"],["También sustenta","PayNow Corporate (el esquema de pago electrónico de Singapur)"],["Empresas multi-entidad","Cada entidad registrada en el GST necesita su propio ID Peppol"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 1;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'de', 'Kennungen und Registrierung', '[["Basis der Peppol-ID","Unique Entity Number (UEN)"],["Liegt auch zugrunde","PayNow Corporate (Singapurs E-Zahlungssystem)"],["Unternehmen mit mehreren Einheiten","Jede GST-registrierte Einheit benötigt ihre eigene Peppol-ID"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 1;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'fr', 'Identifiants et enregistrement', '[["Base de l''identifiant Peppol","Unique Entity Number (UEN)"],["Sous-tend également","PayNow Corporate (le système de paiement électronique de Singapour)"],["Entreprises multi-entités","Chaque entité enregistrée à la GST a besoin de son propre identifiant Peppol"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 1;
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 2 FROM countries WHERE name_en = 'Singapore';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'en', 'Mandatory content', '[["Party identifiers","Supplier/customer UEN and GST registration numbers (GSTN)"],["Tax codes","Mapped to IRAS-approved GST category codes (Annex E, e-Tax Guide)"],["Aggregated entries","Special \"POS\" or \"PCP\" indicators for point-of-sale/petty-cash purchases"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 2;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'es', 'Contenido obligatorio', '[["Identificadores de parte","UEN del proveedor/cliente y números de registro GST (GSTN)"],["Códigos fiscales","Asignados a los códigos de categoría GST aprobados por la IRAS (Anexo E, Guía e-Tax)"],["Entradas agregadas","Indicadores especiales \"POS\" o \"PCP\" para compras en punto de venta/caja chica"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 2;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'de', 'Pflichtangaben', '[["Parteikennungen","Lieferanten-/Kunden-UEN und GST-Registrierungsnummern (GSTN)"],["Steuercodes","Zugeordnet zu den von der IRAS genehmigten GST-Kategoriecodes (Anhang E, e-Tax Guide)"],["Aggregierte Einträge","Spezielle „POS“- oder „PCP“-Kennzeichen für Point-of-Sale-/Portokassekäufe"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 2;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'fr', 'Mentions obligatoires', '[["Identifiants des parties","UEN du fournisseur/client et numéros d''enregistrement GST (GSTN)"],["Codes fiscaux","Associés aux codes de catégorie GST approuvés par l''IRAS (annexe E, e-Tax Guide)"],["Entrées agrégées","Indicateurs spéciaux « POS » ou « PCP » pour les achats en point de vente/petite caisse"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 2;
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 3 FROM countries WHERE name_en = 'Singapore';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'en', 'Archiving', '[["Period and form","Five years for GST records including e-invoices, and they must be kept in machine-readable form — a scan of a printout does not satisfy it."],["Signature","Not required for the archived copy. Integrity rests on ordinary bookkeeping controls rather than on a certificate."]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 3;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'es', 'Conservación', '[["Plazo y forma","Cinco años para los registros de GST, incluidas las facturas electrónicas, y deben conservarse en forma legible por máquina: un escaneo de una impresión no basta."],["Firma","No exigida para la copia archivada. La integridad descansa en los controles contables ordinarios, no en un certificado."]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 3;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'de', 'Aufbewahrung', '[["Frist und Form","Fünf Jahre für GST-Unterlagen einschliesslich E-Rechnungen, und sie müssen maschinenlesbar aufbewahrt werden — ein Scan eines Ausdrucks genügt nicht."],["Signatur","Für die archivierte Kopie nicht erforderlich. Die Integrität stützt sich auf gewöhnliche Buchführungskontrollen, nicht auf ein Zertifikat."]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 3;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'fr', 'Conservation', '[["Durée et forme","Cinq ans pour les documents de GST, factures électroniques comprises, et ils doivent être conservés sous forme lisible par machine : un scan d''une impression ne suffit pas."],["Signature","Non exigée pour la copie archivée. L''intégrité repose sur les contrôles comptables ordinaires, non sur un certificat."]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 3;
INSERT INTO deep_dive_cards (country_id, section, sort_order) SELECT id, 'file_format', 4 FROM countries WHERE name_en = 'Singapore';
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'en', 'Evolving format: PINT SG', '[["Fields not in older templates","Supply type codes, line-level GST amounts, UEN-linked Peppol IDs"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 4;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'es', 'Formato en evolución: PINT SG', '[["Campos ausentes en plantillas antiguas","Códigos de tipo de suministro, importes de GST a nivel de línea, ID Peppol vinculados al UEN"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 4;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'de', 'Sich entwickelndes Format: PINT SG', '[["Felder, die in älteren Vorlagen fehlen","Liefertyp-Codes, GST-Beträge auf Zeilenebene, UEN-verknüpfte Peppol-IDs"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 4;
INSERT INTO deep_dive_card_translations (card_id, lang, title, rows_json)
SELECT d.id, 'fr', 'Format en évolution : PINT SG', '[["Champs absents des anciens modèles","Codes de type de fourniture, montants GST au niveau ligne, identifiants Peppol liés à l''UEN"]]' FROM deep_dive_cards d WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND d.sort_order = 4;

-- ---- what this migration claims it did ----
-- ASSERT: SELECT count(*) FROM deep_dive_cards WHERE section = 'file_format' AND country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') = 5
-- Not one row may have been lost in the move. Compare the total against
-- what went in, per country, since a silent drop is the only way this
-- tool can do real damage.
-- ASSERT: SELECT sum(json_array_length(t.rows_json)) FROM deep_dive_card_translations t JOIN deep_dive_cards d ON d.id = t.card_id WHERE d.country_id = (SELECT id FROM countries WHERE name_en = 'Singapore') AND d.section = 'file_format' AND t.lang = 'en' = 12
