-- Angola's milestones in Spanish, German and French.
--
-- From the scaffolder's drafts/ stub, which ships pre-filled with the
-- English so that an untranslated file is obviously untranslated rather
-- than plausibly complete. Every system, desc and actions value below is
-- rewritten; none is the English text with a different lang column, which
-- is the failure 695 recorded in story_translations and the reason the
-- stub lives outside the numbered sequence where the runner cannot reach
-- it.
--
-- Two things kept identical on purpose across the four languages, because
-- they are names rather than words: 'Regime Jurídico das Facturas' and
-- 'Portal do Contribuinte'. A reader looking for either on a government
-- site needs the string the site uses.

-- ---- es ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-dp7125-vigor', 'es', 'Entra en vigor el Regime Jurídico das Facturas', 'El Decreto Presidencial 71/25, de 20 de marzo de 2025, entró en vigor seis meses después de su publicación y sustituyó al régimen de facturación de 2018. El artículo 16 impone la factura electrónica a los contribuyentes de los regímenes general y simplificado del IVA; el artículo 17(2) exige un software validado o facilitado por la AGT que transmita en tiempo real y no permita borrar un documento ya emitido.', '["Lea los artículos 16, 17 y 25 y no el resumen de un proveedor", "Tenga presente que la obligación sigue al régimen de IVA, no a la facturación"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-b2b-phase1', 'es', 'Grandes contribuyentes y proveedores del Estado', 'La emisión electrónica y la comunicación en tiempo real pasan a ser obligatorias para los grandes contribuyentes, los proveedores del Estado y quienes emitan facturas de 25 millones de kwanzas o más. Una ventana transitoria desde el 1 de octubre de 2025 permitió el papel sin sanción mientras la AGT certificaba el software. En abril de 2026 la AGT declaraba 28.949 contribuyentes en el sistema y entre 250.000 y 500.000 facturas diarias.', '["Confirme que su software de facturación figura en la lista certificada de la AGT", "Registre cada establecimiento en el Portal do Contribuinte antes de pedir series", "Solicite una serie por establecimiento: las series no se comparten"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-statutory-12m', 'es', 'Vence el período transitorio de doce meses del artículo 37', 'El artículo 37 limita la obligación a los grandes contribuyentes y a los proveedores del Estado durante doce meses desde el Decreto Ejecutivo 683/25, que surtió efecto alrededor del 21 de septiembre de 2025. Según el reloj del propio decreto, desde esta fecha quedan alcanzados todos los demás contribuyentes. La práctica angoleña ha alineado en cambio cada fase al 1 de enero, y por eso esta entrada se mantiene fuera del tablero: ninguna autoridad la ha confirmado como fecha operativa.', '["Vigile una instrucción de la AGT que fije la fecha operativa de la segunda fase"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-b2b-phase2', 'es', 'El resto de los contribuyentes con IVA', 'La obligación se extiende a todos los demás contribuyentes de los regímenes general y simplificado del IVA. La fecha la sostienen de forma coherente las fuentes del mercado angoleño y los proveedores de software certificado, y sigue el patrón de la primera fase, cuya fecha legal de 20 de septiembre de 2025 también empezó a aplicarse el 1 de enero. No es la fecha escrita en el decreto, y por eso lleva la marca de prevista.', '["Los contribuyentes menores no deberían esperar a que se despeje el mercado de software certificado", "Compruebe si una instrucción de la AGT ha movido esta fecha antes de planificar sobre ella"]');

-- ---- de ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-dp7125-vigor', 'de', 'Das Regime Jurídico das Facturas tritt in Kraft', 'Das Präsidialdekret 71/25 vom 20. März 2025 trat sechs Monate nach seiner Veröffentlichung in Kraft und löste das Rechnungsregime von 2018 ab. Artikel 16 verpflichtet Steuerpflichtige des allgemeinen und des vereinfachten Umsatzsteuerregimes zur elektronischen Rechnung; Artikel 17(2) verlangt eine von der AGT validierte oder bereitgestellte Software, die in Echtzeit übermittelt und ein ausgestelltes Dokument nicht löschen kann.', '["Lesen Sie die Artikel 16, 17 und 25, nicht die Zusammenfassung eines Anbieters", "Beachten Sie: die Pflicht folgt dem Umsatzsteuerregime, nicht dem Umsatz"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-b2b-phase1', 'de', 'Grossunternehmen und Lieferanten des Staates', 'Elektronische Ausstellung und Übermittlung in Echtzeit werden für Grossunternehmen, Lieferanten des Staates und alle, die Rechnungen ab 25 Millionen Kwanza ausstellen, verpflichtend. Ein Übergangsfenster ab dem 1. Oktober 2025 erlaubte Papier ohne Sanktion, während die AGT Software zertifizierte. Im April 2026 meldete die AGT 28.949 Steuerpflichtige im System und täglich 250.000 bis 500.000 Rechnungen.', '["Prüfen Sie, ob Ihre Fakturierungssoftware auf der zertifizierten Liste der AGT steht", "Melden Sie jede Betriebsstätte im Portal do Contribuinte an, bevor Sie Serien beantragen", "Beantragen Sie je Betriebsstätte eine eigene Serie — Serien lassen sich nicht teilen"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-statutory-12m', 'de', 'Die zwölfmonatige Übergangsfrist aus Artikel 37 endet', 'Artikel 37 beschränkt die Pflicht zwölf Monate lang auf Grossunternehmen und Lieferanten des Staates, gerechnet ab dem Durchführungsdekret 683/25, das um den 21. September 2025 wirksam wurde. Nach der Uhr des Dekrets sind ab diesem Datum alle übrigen Steuerpflichtigen erfasst. Die angolanische Praxis hat jede Stufe stattdessen auf den 1. Januar gelegt, weshalb dieser Eintrag ausserhalb des Boards bleibt: keine Behörde hat ihn als massgebliches Datum bestätigt.', '["Achten Sie auf eine Anweisung der AGT, die das massgebliche Datum der zweiten Stufe nennt"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-b2b-phase2', 'de', 'Alle übrigen umsatzsteuerpflichtigen Unternehmen', 'Die Pflicht erstreckt sich auf alle übrigen Steuerpflichtigen des allgemeinen und des vereinfachten Umsatzsteuerregimes. Das Datum wird von Quellen im angolanischen Markt und von Anbietern zertifizierter Software übereinstimmend genannt und folgt dem Muster der ersten Stufe, deren gesetzliches Datum vom 20. September 2025 ebenfalls erst zum 1. Januar galt. Es ist nicht das im Dekret stehende Datum, daher das Kennzeichen "erwartet".', '["Kleinere Steuerpflichtige sollten nicht warten, bis sich der Markt für zertifizierte Software geklärt hat", "Prüfen Sie vor der Planung, ob eine AGT-Anweisung dieses Datum verschoben hat"]');

-- ---- fr ----
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-dp7125-vigor', 'fr', 'Entrée en vigueur du Regime Jurídico das Facturas', 'Le décret présidentiel 71/25 du 20 mars 2025 est entré en vigueur six mois après sa publication, remplaçant le régime de facturation de 2018. L''article 16 impose la facture électronique aux assujettis des régimes général et simplifié de TVA ; l''article 17(2) exige un logiciel validé ou fourni par l''AGT, qui transmet en temps réel et ne peut supprimer un document déjà émis.', '["Lisez les articles 16, 17 et 25 plutôt que le résumé d''un éditeur", "Retenez que l''obligation suit le régime de TVA et non le chiffre d''affaires"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-b2b-phase1', 'fr', 'Grandes entreprises et fournisseurs de l''État', 'L''émission électronique et la transmission en temps réel deviennent obligatoires pour les grandes entreprises, les fournisseurs de l''État et quiconque émet des factures d''au moins 25 millions de kwanzas. Une fenêtre transitoire ouverte le 1er octobre 2025 autorisait le papier sans sanction pendant que l''AGT agréait les logiciels. En avril 2026, l''AGT annonçait 28 949 contribuables raccordés et de 250 000 à 500 000 factures par jour.', '["Vérifiez que votre logiciel de facturation figure sur la liste agréée par l''AGT", "Déclarez chaque établissement au Portal do Contribuinte avant de demander des séries", "Demandez une série par établissement : les séries ne se partagent pas"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-statutory-12m', 'fr', 'Expiration de la période transitoire de douze mois de l''article 37', 'L''article 37 réserve l''obligation aux grandes entreprises et aux fournisseurs de l''État pendant douze mois à compter du décret exécutif 683/25, entré en vigueur autour du 21 septembre 2025. Selon l''horloge du décret lui-même, tous les autres assujettis sont visés à partir de cette date. La pratique angolaise a plutôt aligné chaque phase sur le 1er janvier, et cette entrée reste hors du tableau : aucune autorité ne l''a confirmée comme date opérante.', '["Guettez une instruction de l''AGT fixant la date opérante de la deuxième phase"]');
INSERT OR IGNORE INTO milestone_translations (milestone_id, lang, system, desc, actions) VALUES ('ao-b2b-phase2', 'fr', 'Tous les autres assujettis à la TVA', 'L''obligation s''étend à tous les autres assujettis des régimes général et simplifié de TVA. La date est rapportée de façon concordante par les sources du marché angolais et par les éditeurs de logiciels agréés, et elle suit le schéma de la première phase, dont la date légale du 20 septembre 2025 n''a elle aussi pris effet qu''au 1er janvier. Ce n''est pas la date inscrite au décret, d''où la mention « attendue ».', '["Les petits assujettis ne devraient pas attendre que le marché des logiciels agréés se dégage", "Vérifiez qu''une instruction de l''AGT n''a pas déplacé cette date avant de planifier dessus"]');

-- ---- what this migration claims it did ----
-- ASSERT: SELECT count(*) FROM milestone_translations WHERE milestone_id IN ('ao-dp7125-vigor','ao-b2b-phase1','ao-statutory-12m','ao-b2b-phase2') = 16
--
-- NONE OF THE TWELVE IS THE ENGLISH ROW WITH A DIFFERENT LANG COLUMN.
-- Compared column against column rather than read, which is how 695
-- caught the same defect in Hong Kong's stories: a page can look
-- translated because its heading is.
-- ASSERT: SELECT count(*) FROM milestone_translations t JOIN milestone_translations e ON e.milestone_id = t.milestone_id AND e.lang = 'en' WHERE t.lang <> 'en' AND t.milestone_id LIKE 'ao-%' AND (t.desc = e.desc OR t.system = e.system) = 0
--
-- STANDING: every milestone carries all four languages.
--
-- Written relatively, and the invariant that failed the replay while this
-- file did not exist. It is restated here rather than left to 708 because
-- this is the file that satisfies it for Angola.
-- ASSERT ALWAYS: SELECT count(*) FROM milestones m WHERE (SELECT count(*) FROM milestone_translations t WHERE t.milestone_id = m.id) < 4 = 0
