# Generates 200_peru_story_translations.sql — ES/DE/FR translations for
# the three Peru stories (migration 199). INSERT OR IGNORE, matching the
# established pattern (see 197), safe against existing English rows.
import json

translations = {
  "2026-04-30-peru-day-one-e-invoicing": {
    "es": {
      "title": "La SUNAT elimina el período de adaptación: los nuevos contribuyentes deben facturar electrónicamente desde el primer día",
      "summary": "La Resolución de Superintendencia N.° 000075-2026/SUNAT, vigente desde el 1 de junio de 2026, elimina el período de adaptación que Perú concedía a las empresas recién registradas: quien se inscriba en el RUC bajo el Régimen MYPE Tributario, el Régimen Especial (RER) o el Régimen General debe emitir comprobantes de pago electrónicos desde la fecha misma de su inscripción.",
      "html": """<h3>🇵🇪 La SUNAT elimina el período de adaptación: los nuevos contribuyentes deben facturar electrónicamente desde el primer día</h3>
<p>La autoridad tributaria del Perú, la SUNAT, ha publicado la Resolución de Superintendencia N.° 000075-2026/SUNAT (30 de abril de 2026, vigente desde el 1 de junio de 2026), cerrando uno de los últimos márgenes flexibles de lo que ya es uno de los sistemas de compensación más completos de América Latina. La emisión electrónica de comprobantes de pago (CPE) a través del Sistema de Emisión Electrónica (SEE) es obligatoria para prácticamente todos los contribuyentes peruanos desde 2022 — pero las empresas recién registradas disfrutaban hasta ahora de un período de adaptación, con plazo hasta el tercer mes posterior a su inscripción para poner en marcha su emisión electrónica. Esa ventana ha desaparecido.</p>
<p>Bajo el marco modificado, cualquier empresa o emprendedor que se inscriba en el RUC (el registro de contribuyentes peruano) bajo el Régimen MYPE Tributario, el Régimen Especial del Impuesto a la Renta (RER) o el Régimen General debe emitir comprobantes electrónicos desde la fecha misma de la inscripción — desde el primer día, sin período de transición. Los contribuyentes que salgan del régimen simplificado Nuevo RUS hacia uno de esos regímenes deben comenzar a emitir electrónicamente desde el primer día del mes siguiente a su salida. Y, como disposición de cierre, los contribuyentes cuya designación como emisores electrónicos había sido efectuada pero aún no había surtido efecto al 31 de mayo de 2026 pasaron automáticamente a ser emisores electrónicos el 1 de junio de 2026.</p>
<p>La misma resolución también ajusta las reglas de plazos en torno al Sistema Integrado de Registros Electrónicos (SIRE), la plataforma de la SUNAT para los registros electrónicos de ventas y compras, alineando el momento en que los contribuyentes recién obligados deben comenzar a llevar sus registros allí con sus obligaciones de emisión electrónica.</p>
<p><strong>Qué significa esto para su equipo:</strong> si está constituyendo una entidad peruana o dando de alta un nuevo RUC por cualquier motivo, la capacidad de emisión electrónica es ahora un requisito previo al lanzamiento, no una tarea del segundo mes. En la práctica, esto significa tener su canal de emisión — SEE-SOL, su propio sistema (SEE-Del contribuyente), el Facturador gratuito de la SUNAT (SFS) o un proveedor PSE/OSE autorizado — seleccionado y operativo antes de la primera venta, ya que ya no existe ninguna vía legal para emitir comprobantes físicos mientras se completa la puesta en marcha.</p>""",
    },
    "de": {
      "title": "SUNAT schafft die Übergangsfrist ab: Neue Steuerpflichtige müssen ab dem ersten Tag elektronisch fakturieren",
      "summary": "Die Superintendency-Resolution Nr. 000075-2026/SUNAT, in Kraft seit dem 1. Juni 2026, beseitigt die Anpassungsfrist, die Peru neu registrierten Unternehmen bisher gewährte: Wer sich unter dem MYPE-Tributario-Regime, dem Sonderregime (RER) oder dem allgemeinen Regime im RUC registriert, muss elektronische Comprobantes de Pago ab dem Tag der Registrierung ausstellen.",
      "html": """<h3>🇵🇪 SUNAT schafft die Übergangsfrist ab: Neue Steuerpflichtige müssen ab dem ersten Tag elektronisch fakturieren</h3>
<p>Perus Steuerbehörde SUNAT hat die Superintendency-Resolution Nr. 000075-2026/SUNAT veröffentlicht (30. April 2026, in Kraft seit dem 1. Juni 2026) und damit eine der letzten weichen Kanten in einem der umfassendsten Clearance-Systeme Lateinamerikas geschlossen. Die elektronische Ausstellung von Comprobantes de Pago (CPE) über das Sistema de Emisión Electrónica (SEE) ist seit 2022 für praktisch alle peruanischen Steuerpflichtigen verpflichtend — neu registrierte Unternehmen genossen bislang jedoch eine Anpassungsfrist von bis zum dritten Monat nach der Registrierung, um ihre elektronische Ausstellung einzurichten. Dieses Zeitfenster ist nun geschlossen.</p>
<p>Nach dem geänderten Rahmen muss jedes Unternehmen und jeder Unternehmer, der sich im RUC (dem peruanischen Steuerpflichtigenregister) unter dem MYPE-Tributario-Regime, dem Sonderregime der Einkommensteuer (RER) oder dem allgemeinen Regime registriert, elektronische Comprobantes ab dem Tag der Registrierung selbst ausstellen — vom ersten Tag an, ohne Übergangsfrist. Steuerpflichtige, die das vereinfachte Nuevo-RUS-Regime in Richtung eines dieser Regime verlassen, müssen ab dem ersten Tag des auf den Austritt folgenden Monats elektronisch ausstellen. Und als Auffangbestimmung wurden Steuerpflichtige, deren Benennung als elektronische Aussteller zwar erfolgt, aber bis zum 31. Mai 2026 noch nicht wirksam geworden war, am 1. Juni 2026 automatisch zu elektronischen Ausstellern.</p>
<p>Dieselbe Resolution verschärft auch die Fristenregeln rund um das Sistema Integrado de Registros Electrónicos (SIRE), SUNATs Plattform für elektronische Verkaufs- und Einkaufsregister, und richtet den Zeitpunkt, ab dem neu verpflichtete Steuerpflichtige ihre Register dort führen müssen, an ihren elektronischen Ausstellungspflichten aus.</p>
<p><strong>Was das für Ihr Team bedeutet:</strong> Wenn Sie eine peruanische Gesellschaft gründen oder aus irgendeinem Grund einen neuen RUC anlegen, ist die Fähigkeit zur elektronischen Ausstellung nun eine Voraussetzung vor dem Start, keine Aufgabe für den zweiten Monat. Praktisch heißt das: Ihr Ausstellungskanal — SEE-SOL, Ihr eigenes System (SEE-Del contribuyente), SUNATs kostenloser Facturador (SFS) oder ein autorisierter PSE/OSE-Anbieter — muss vor dem ersten Verkauf ausgewählt und funktionsfähig sein, denn es gibt keinen rechtmäßigen Weg mehr, während der Einrichtung physische Comprobantes auszustellen.</p>""",
    },
    "fr": {
      "title": "La SUNAT supprime la période d'adaptation : les nouveaux contribuables doivent facturer électroniquement dès le premier jour",
      "summary": "La résolution de Superintendance n° 000075-2026/SUNAT, en vigueur depuis le 1er juin 2026, supprime la période d'adaptation que le Pérou accordait aux entreprises nouvellement enregistrées : toute inscription au RUC sous le régime MYPE Tributario, le régime spécial (RER) ou le régime général impose d'émettre des comprobantes de pago électroniques dès la date d'enregistrement.",
      "html": """<h3>🇵🇪 La SUNAT supprime la période d'adaptation : les nouveaux contribuables doivent facturer électroniquement dès le premier jour</h3>
<p>L'autorité fiscale du Pérou, la SUNAT, a publié la résolution de Superintendance n° 000075-2026/SUNAT (30 avril 2026, en vigueur depuis le 1er juin 2026), refermant l'une des dernières marges de souplesse de ce qui est déjà l'un des systèmes de validation préalable les plus complets d'Amérique latine. L'émission électronique des comprobantes de pago (CPE) via le Sistema de Emisión Electrónica (SEE) est obligatoire pour la quasi-totalité des contribuables péruviens depuis 2022 — mais les entreprises nouvellement enregistrées bénéficiaient jusqu'ici d'une période d'adaptation, avec un délai courant jusqu'au troisième mois suivant leur inscription pour mettre en place leur émission électronique. Cette fenêtre a disparu.</p>
<p>Dans le cadre modifié, toute entreprise ou tout entrepreneur s'inscrivant au RUC (le registre péruvien des contribuables) sous le régime MYPE Tributario, le régime spécial de l'impôt sur le revenu (RER) ou le régime général doit émettre des comprobantes électroniques dès la date même de l'inscription — dès le premier jour, sans période de transition. Les contribuables quittant le régime simplifié Nuevo RUS vers l'un de ces régimes doivent commencer à émettre électroniquement dès le premier jour du mois suivant leur sortie. Et, disposition de rattrapage, les contribuables dont la désignation comme émetteurs électroniques avait été prononcée mais n'avait pas encore pris effet au 31 mai 2026 sont automatiquement devenus émetteurs électroniques le 1er juin 2026.</p>
<p>La même résolution ajuste également les règles de délais autour du Sistema Integrado de Registros Electrónicos (SIRE), la plateforme de la SUNAT pour les registres électroniques des ventes et des achats, en alignant le moment où les contribuables nouvellement assujettis doivent commencer à y tenir leurs registres sur leurs obligations d'émission électronique.</p>
<p><strong>Ce que cela signifie pour votre équipe :</strong> si vous constituez une entité péruvienne ou créez un nouveau RUC pour quelque raison que ce soit, la capacité d'émission électronique est désormais un prérequis au lancement, pas une tâche du deuxième mois. Concrètement, cela signifie que votre canal d'émission — SEE-SOL, votre propre système (SEE-Del contribuyente), le Facturador gratuit de la SUNAT (SFS) ou un prestataire PSE/OSE agréé — doit être choisi et opérationnel avant la première vente, car il n'existe plus aucune voie légale pour émettre des comprobantes physiques pendant la mise en place.</p>""",
    },
  },
  "2026-07-22-peru-see-overhaul-resolution-048": {
    "es": {
      "title": "La Resolución 000048-2026/SUNAT reforma el SEE: se eliminan las notas de crédito consolidadas desde el 1 de agosto",
      "summary": "La Resolución 000048-2026/SUNAT de la SUNAT, con sus disposiciones principales vigentes desde el 1 de agosto de 2026, incorpora nuevos tipos de documentos al sistema de emisión electrónica, designa nuevos emisores electrónicos, restringe aún más los comprobantes físicos — y, lo más relevante para los equipos financieros, exige que cada nota de crédito electrónica modifique exactamente un comprobante, eliminando las notas de crédito consolidadas.",
      "html": """<h3>🇵🇪 La Resolución 000048-2026/SUNAT reforma el SEE: se eliminan las notas de crédito consolidadas desde el 1 de agosto</h3>
<p>La SUNAT ha publicado la Resolución de Superintendencia N.° 000048-2026/SUNAT, una modificación sustancial del Sistema de Emisión Electrónica (SEE) del Perú — el marco que sustenta el régimen de facturación electrónica de modelo de compensación del país. Las disposiciones principales de la resolución entran en vigor el 1 de agosto de 2026, con una segunda ola de disposiciones inicialmente programada para el 1 de noviembre de 2026 (desde entonces postergada — véase la historia complementaria sobre la Resolución 000143-2026/SUNAT).</p>
<p>El cambio con mayor impacto operativo inmediato para los equipos financieros afecta a las notas de crédito electrónicas: desde la entrada en vigor de la resolución, una nota de crédito solo puede modificar un único comprobante de pago. Se elimina la práctica anterior de emitir una nota de crédito consolidada que ajustaba múltiples facturas, boletas u otros documentos electrónicos en una sola operación. Las notas de débito quedan sujetas a reglas de validación paralelas endurecidas. Para las empresas con altos volúmenes de devoluciones o acuerdos periódicos de descuentos — comercio minorista, distribución, bienes de consumo — se trata de un cambio de proceso genuino, no de un tecnicismo: los descuentos y ajustes por volumen que antes cabían en un solo documento ahora requieren una nota de crédito por cada comprobante subyacente.</p>
<p>Más allá de las notas de crédito, la resolución incorpora nuevos tipos de documentos al SEE como documentos electrónicos (incluidos los documentos autorizados por servicios aeroportuarios y los documentos de atribución), designa nuevas clases de emisores electrónicos, restringe aún más las circunstancias en las que pueden usarse comprobantes físicos y simplifica partes del Reglamento de Comprobantes de Pago — continuando el patrón sostenido de la SUNAT de absorber progresivamente en el sistema electrónico cada clase de documento en papel que aún subsiste.</p>
<p><strong>Qué significa esto para su equipo:</strong> audite su lógica de notas de crédito antes de emitir ajustes por operaciones de agosto en adelante. Si su ERP o sistema de facturación genera notas de crédito consolidadas contra múltiples facturas — algo común en flujos de descuentos, devoluciones y liquidaciones — debe reconfigurarse para emitir una nota por cada comprobante referenciado, y sus procesos de conciliación deben prever el mayor volumen documental resultante.</p>""",
    },
    "de": {
      "title": "Resolution 000048-2026/SUNAT reformiert das SEE: Konsolidierte Gutschriften ab dem 1. August abgeschafft",
      "summary": "SUNATs Resolution 000048-2026/SUNAT, deren Hauptbestimmungen ab dem 1. August 2026 gelten, bringt neue Dokumenttypen in das elektronische Ausstellungssystem, benennt neue elektronische Aussteller, schränkt physische Comprobantes weiter ein — und verlangt, für Finanzteams am bedeutsamsten, dass jede elektronische Gutschrift genau einen Comprobante ändert, womit konsolidierte Gutschriften enden.",
      "html": """<h3>🇵🇪 Resolution 000048-2026/SUNAT reformiert das SEE: Konsolidierte Gutschriften ab dem 1. August abgeschafft</h3>
<p>SUNAT hat die Superintendency-Resolution Nr. 000048-2026/SUNAT veröffentlicht, eine umfassende Änderung von Perus Sistema de Emisión Electrónica (SEE) — dem Rahmen hinter dem Clearance-Modell des Landes für die elektronische Rechnungsstellung. Die Hauptbestimmungen der Resolution treten am 1. August 2026 in Kraft, eine zweite Welle von Bestimmungen war ursprünglich für den 1. November 2026 vorgesehen (inzwischen verschoben — siehe den Begleitartikel zur Resolution 000143-2026/SUNAT).</p>
<p>Die Änderung mit den unmittelbarsten operativen Folgen für Finanzteams betrifft elektronische Gutschriften: Ab Inkrafttreten der Resolution darf eine Gutschrift nur noch einen einzigen Comprobante de Pago ändern. Die bisherige Praxis, eine konsolidierte Gutschrift auszustellen, die mehrere Rechnungen, Boletas oder andere elektronische Dokumente in einem Vorgang anpasst, wird abgeschafft. Für Lastschriften gelten parallel verschärfte Validierungsregeln. Für Unternehmen mit hohen Retourenvolumina oder periodischen Rabattvereinbarungen — Einzelhandel, Distribution, Konsumgüter — ist das eine echte Prozessänderung, keine Formalität: Rabatte und Mengenanpassungen, die bisher in ein Dokument passten, erfordern nun eine Gutschrift pro zugrunde liegendem Comprobante.</p>
<p>Über die Gutschriften hinaus nimmt die Resolution neue Dokumenttypen als elektronische Dokumente in das SEE auf (darunter Documentos Autorizados für Flughafendienstleistungen und Documentos de Atribución), benennt neue Klassen elektronischer Aussteller, schränkt die Fälle, in denen physische Comprobantes verwendet werden dürfen, weiter ein und vereinfacht Teile des Reglamento de Comprobantes de Pago — womit SUNAT ihr langjähriges Muster fortsetzt, jede verbleibende papierbasierte Dokumentklasse schrittweise in das elektronische System zu überführen.</p>
<p><strong>Was das für Ihr Team bedeutet:</strong> Prüfen Sie Ihre Gutschriftslogik, bevor Sie Anpassungen für Vorgänge ab August ausstellen. Wenn Ihr ERP- oder Abrechnungssystem konsolidierte Gutschriften über mehrere Rechnungen erzeugt — üblich in Rabatt-, Retouren- und Abrechnungsprozessen — muss es so umkonfiguriert werden, dass es eine Gutschrift pro referenziertem Comprobante ausstellt, und Ihre Abstimmungsprozesse müssen das daraus folgende höhere Dokumentvolumen einplanen.</p>""",
    },
    "fr": {
      "title": "La résolution 000048-2026/SUNAT refond le SEE : les notes de crédit consolidées supprimées à compter du 1er août",
      "summary": "La résolution 000048-2026/SUNAT de la SUNAT, dont les dispositions principales entrent en vigueur le 1er août 2026, intègre de nouveaux types de documents au système d'émission électronique, désigne de nouveaux émetteurs électroniques, restreint davantage les comprobantes physiques — et, point le plus important pour les équipes financières, impose que chaque note de crédit électronique ne modifie qu'un seul comprobante, mettant fin aux notes de crédit consolidées.",
      "html": """<h3>🇵🇪 La résolution 000048-2026/SUNAT refond le SEE : les notes de crédit consolidées supprimées à compter du 1er août</h3>
<p>La SUNAT a publié la résolution de Superintendance n° 000048-2026/SUNAT, une modification substantielle du Sistema de Emisión Electrónica (SEE) du Pérou — le cadre qui sous-tend le régime de facturation électronique à validation préalable du pays. Les dispositions principales de la résolution entrent en vigueur le 1er août 2026, une seconde vague de dispositions étant initialement prévue pour le 1er novembre 2026 (depuis reportée — voir l'article complémentaire sur la résolution 000143-2026/SUNAT).</p>
<p>Le changement à l'impact opérationnel le plus immédiat pour les équipes financières concerne les notes de crédit électroniques : dès l'entrée en vigueur de la résolution, une note de crédit ne peut modifier qu'un seul comprobante de pago. La pratique antérieure consistant à émettre une note de crédit consolidée ajustant plusieurs factures, boletas ou autres documents électroniques en une seule opération est supprimée. Les notes de débit sont soumises à des règles de validation parallèles durcies. Pour les entreprises à forts volumes de retours ou à accords périodiques de remises — commerce de détail, distribution, biens de consommation — il s'agit d'un vrai changement de processus, pas d'une technicité : les remises et ajustements de volume qui tenaient auparavant dans un seul document exigent désormais une note de crédit par comprobante sous-jacent.</p>
<p>Au-delà des notes de crédit, la résolution intègre de nouveaux types de documents au SEE en tant que documents électroniques (dont les documentos autorizados pour les services aéroportuaires et les documentos de atribución), désigne de nouvelles catégories d'émetteurs électroniques, restreint davantage les cas où des comprobantes physiques peuvent être utilisés et simplifie des pans du Reglamento de Comprobantes de Pago — poursuivant la démarche constante de la SUNAT d'absorber progressivement dans le système électronique chaque catégorie de document papier restante.</p>
<p><strong>Ce que cela signifie pour votre équipe :</strong> auditez votre logique de notes de crédit avant d'émettre des ajustements pour les opérations d'août et au-delà. Si votre ERP ou votre système de facturation génère des notes de crédit consolidées portant sur plusieurs factures — courant dans les flux de remises, de retours et de règlements — il doit être reconfiguré pour émettre une note par comprobante référencé, et vos processus de rapprochement doivent anticiper le volume documentaire accru qui en résulte.</p>""",
    },
  },
  "2026-07-31-peru-resolution-143-postponements": {
    "es": {
      "title": "La SUNAT posterga la siguiente ola de obligaciones del SEE: la designación de nuevos emisores electrónicos pasa a abril de 2027",
      "summary": "La Resolución 000143-2026/SUNAT, publicada en El Peruano el 31 de julio de 2026, suaviza el calendario de implementación de la reforma del SEE de julio: la designación de nuevos emisores electrónicos pasa del 1 de noviembre de 2026 al 1 de abril de 2027, se aplican reglas transitorias a las notas sobre documentos emitidos fuera del SEE, y se amplían los plazos de presentación de los formularios 836, 847 y 837.",
      "html": """<h3>🇵🇪 La SUNAT posterga la siguiente ola de obligaciones del SEE: la designación de nuevos emisores electrónicos pasa a abril de 2027</h3>
<p>Apenas unas semanas después de publicar su gran reforma del Sistema de Emisión Electrónica (Resolución 000048-2026/SUNAT — véase la historia complementaria), la SUNAT ha flexibilizado parcialmente el calendario de implementación. La Resolución de Superintendencia N.° 000143-2026/SUNAT, publicada en el diario oficial El Peruano el 31 de julio de 2026, modifica los artículos 5, 7 y 14 de la resolución original y traslada varios de los hitos de su segunda ola de finales de 2026 a 2027.</p>
<p>El cambio principal: la designación de nuevos emisores electrónicos del SEE — que abarca a los sujetos obligados a emitir electrónicamente los documentos autorizados por servicios aeroportuarios, los documentos de atribución y las demás clases de documentos que se incorporan al sistema —, prevista inicialmente para el 1 de noviembre de 2026, comenzará a operar desde el 1 de abril de 2027. Junto a ello, la SUNAT establece una transición para las notas de crédito y débito electrónicas emitidas respecto de determinados documentos autorizados que a su vez fueron emitidos fuera del SEE (bajo procedimientos de contingencia o como documentos físicos preexistentes): para tales documentos autorizados emitidos hasta el 31 de diciembre de 2026, las notas correspondientes podrán seguir las reglas vigentes para cada sistema del SEE, protegiendo la regularización de operaciones realizadas bajo el régimen anterior.</p>
<p>El calendario de presentación de los formularios de autorización se amplía en consecuencia: los formularios N.° 836 y 847 (vinculados con la autorización para la emisión de boletos de viaje por medios electrónicos en el transporte ferroviario y con la comunicación de emisión de boletos de viaje) podrán presentarse hasta el 31 de diciembre de 2026, y el formulario N.° 837 (autorización para comprobantes SEAE por medios electrónicos) hasta el 31 de marzo de 2027.</p>
<p><strong>Qué significa esto para su equipo:</strong> la prórroga da tiempo de integración, pero léala en sentido estricto. Las disposiciones de la Resolución 000048-2026/SUNAT que entraron en vigor el 1 de agosto de 2026 — incluida la regla de una nota de crédito por comprobante — no se postergan; el alivio apunta a la ola de noviembre de nuevas designaciones de emisores y a la transición para documentos fuera del SEE. Si sus operaciones peruanas tocan las clases de documentos afectadas, lo sensato es tratar abril de 2027 como fecha límite firme y usar los meses adicionales para desarrollo y pruebas de validación, no para aplazar el trabajo — el patrón de la SUNAT con estas prórrogas, como antes con el SIRE, es concederlas cuando la presión operativa llega a su punto máximo, no suavizar los requisitos técnicos subyacentes.</p>""",
    },
    "de": {
      "title": "SUNAT verschiebt die nächste Welle der SEE-Pflichten: Neue Ausstellerbenennungen rücken auf April 2027",
      "summary": "Die Resolution 000143-2026/SUNAT, veröffentlicht in El Peruano am 31. Juli 2026, entschärft den Umsetzungskalender der SEE-Reform vom Juli: Die Benennung neuer elektronischer Aussteller rückt vom 1. November 2026 auf den 1. April 2027, für Gut- und Lastschriften über außerhalb des SEE ausgestellte Dokumente gelten Übergangsregeln, und die Einreichungsfristen der Formulare 836, 847 und 837 werden verlängert.",
      "html": """<h3>🇵🇪 SUNAT verschiebt die nächste Welle der SEE-Pflichten: Neue Ausstellerbenennungen rücken auf April 2027</h3>
<p>Nur wenige Wochen nach der Veröffentlichung ihrer großen Reform des Sistema de Emisión Electrónica (Resolution 000048-2026/SUNAT — siehe Begleitartikel) hat SUNAT den Umsetzungskalender teilweise entschärft. Die Superintendency-Resolution Nr. 000143-2026/SUNAT, veröffentlicht im Amtsblatt El Peruano am 31. Juli 2026, ändert die Artikel 5, 7 und 14 der ursprünglichen Resolution und verschiebt mehrere Meilensteine ihrer zweiten Welle von Ende 2026 auf 2027.</p>
<p>Die wichtigste Änderung: Die Benennung neuer elektronischer Aussteller im SEE — sie umfasst die Steuerpflichtigen, die Documentos Autorizados für Flughafendienstleistungen, Documentos de Atribución und die weiteren in das System aufgenommenen Dokumentklassen elektronisch ausstellen müssen —, ursprünglich für den 1. November 2026 vorgesehen, greift nun ab dem 1. April 2027. Daneben schafft SUNAT eine Übergangsregelung für elektronische Gut- und Lastschriften zu bestimmten Documentos Autorizados, die ihrerseits außerhalb des SEE ausgestellt wurden (in Notfallverfahren oder als vorbestehende physische Dokumente): Für solche bis zum 31. Dezember 2026 autorisierten Dokumente dürfen die zugehörigen Gut- und Lastschriften weiterhin den derzeit für den jeweiligen SEE-Kanal geltenden Regeln folgen, was die Regularisierung von Vorgängen unter dem alten Regime schützt.</p>
<p>Der Einreichungskalender für die Autorisierungsformulare wird entsprechend verlängert: Die Formulare Nr. 836 und 847 (verbunden mit der Autorisierung zur elektronischen Ausstellung von Fahrscheinen im Schienenverkehr und der Mitteilung der Fahrscheinausstellung) können nun bis zum 31. Dezember 2026 eingereicht werden, das Formular Nr. 837 (Autorisierung für elektronisch ausgestellte SEAE-Comprobantes) bis zum 31. März 2027.</p>
<p><strong>Was das für Ihr Team bedeutet:</strong> Die Verlängerung verschafft Integrationszeit, sollte aber eng gelesen werden. Die am 1. August 2026 in Kraft getretenen Bestimmungen der Resolution 000048-2026/SUNAT — einschließlich der Regel einer Gutschrift pro Comprobante — sind nicht verschoben; die Entlastung zielt auf die November-Welle neuer Ausstellerbenennungen und die Übergangsregeln für Dokumente außerhalb des SEE. Wenn Ihre peruanischen Aktivitäten die betroffenen Dokumentklassen berühren, ist es ratsam, April 2027 als festen Termin zu behandeln und die zusätzlichen Monate für Entwicklung und Validierungstests zu nutzen, nicht zum Aufschieben — SUNATs Muster bei solchen Verlängerungen, wie zuvor beim SIRE, ist es, sie zu gewähren, wenn der operative Druck am größten ist, nicht die zugrunde liegenden technischen Anforderungen aufzuweichen.</p>""",
    },
    "fr": {
      "title": "La SUNAT reporte la prochaine vague d'obligations du SEE : la désignation des nouveaux émetteurs électroniques passe à avril 2027",
      "summary": "La résolution 000143-2026/SUNAT, publiée dans El Peruano le 31 juillet 2026, assouplit le calendrier de mise en œuvre de la refonte du SEE de juillet : la désignation des nouveaux émetteurs électroniques passe du 1er novembre 2026 au 1er avril 2027, des règles transitoires s'appliquent aux notes portant sur des documents émis hors du SEE, et les fenêtres de dépôt des formulaires 836, 847 et 837 sont prolongées.",
      "html": """<h3>🇵🇪 La SUNAT reporte la prochaine vague d'obligations du SEE : la désignation des nouveaux émetteurs électroniques passe à avril 2027</h3>
<p>Quelques semaines à peine après la publication de sa grande refonte du Sistema de Emisión Electrónica (résolution 000048-2026/SUNAT — voir l'article complémentaire), la SUNAT a partiellement assoupli le calendrier de mise en œuvre. La résolution de Superintendance n° 000143-2026/SUNAT, publiée au journal officiel El Peruano le 31 juillet 2026, modifie les articles 5, 7 et 14 de la résolution d'origine et reporte plusieurs jalons de sa seconde vague de fin 2026 à 2027.</p>
<p>Le changement principal : la désignation des nouveaux émetteurs électroniques du SEE — couvrant les contribuables tenus d'émettre électroniquement les documentos autorizados pour les services aéroportuaires, les documentos de atribución et les autres catégories de documents intégrées au système —, initialement prévue pour le 1er novembre 2026, ne s'appliquera qu'à partir du 1er avril 2027. Parallèlement, la SUNAT établit une transition pour les notes de crédit et de débit électroniques émises au titre de certains documentos autorizados eux-mêmes émis hors du SEE (dans le cadre de procédures de contingence ou en tant que documents physiques préexistants) : pour ces documents autorisés jusqu'au 31 décembre 2026, les notes correspondantes pourront continuer de suivre les règles actuellement en vigueur pour chaque canal du SEE, protégeant la régularisation des opérations menées sous l'ancien régime.</p>
<p>Le calendrier de dépôt des formulaires d'autorisation est prolongé en conséquence : les formulaires n° 836 et 847 (liés à l'autorisation d'émettre des billets de voyage par voie électronique dans le transport ferroviaire et à la communication de l'émission de billets de voyage) peuvent désormais être déposés jusqu'au 31 décembre 2026, et le formulaire n° 837 (autorisation pour les comprobantes SEAE émis par voie électronique) jusqu'au 31 mars 2027.</p>
<p><strong>Ce que cela signifie pour votre équipe :</strong> ce report offre du temps d'intégration, mais lisez-le de manière stricte. Les dispositions de la résolution 000048-2026/SUNAT entrées en vigueur le 1er août 2026 — dont la règle d'une note de crédit par comprobante — ne sont pas reportées ; l'allègement vise la vague de novembre des nouvelles désignations d'émetteurs et la transition pour les documents hors SEE. Si vos opérations péruviennes touchent les catégories de documents concernées, la démarche raisonnable est de traiter avril 2027 comme une échéance ferme et d'utiliser les mois supplémentaires pour le développement et les tests de validation, pas pour différer le travail — la pratique de la SUNAT avec ces prolongations, comme auparavant avec le SIRE, consiste à les accorder quand la pression opérationnelle atteint son maximum, pas à assouplir les exigences techniques sous-jacentes.</p>""",
    },
  },
}

def sql_escape(s):
    return s.replace("'", "''")

lines = [
    "-- ES/DE/FR translations for the three Peru newsletter stories (199).",
    "-- INSERT OR IGNORE, safe against existing English rows.",
    "",
]
for story_id, langs in translations.items():
    for lang, t in langs.items():
        lines.append(
            f"INSERT OR IGNORE INTO story_translations (story_id, lang, title, summary, html) VALUES "
            f"('{sql_escape(story_id)}', '{lang}', '{sql_escape(t['title'])}', "
            f"'{sql_escape(t['summary'])}', '{sql_escape(t['html'])}');"
        )
    lines.append("")

with open("200_peru_story_translations.sql", "w", encoding="utf-8") as out:
    out.write("\n".join(lines))
print(f"Written {sum(len(v) for v in translations.values())} translation rows to 200_peru_story_translations.sql")
