#!/bin/bash
# Run from members-worker/. Applies the remaining _meta.* backfill rows
# in small batches via --command, sidestepping the file-upload issue.
set -e

echo "Batch 1/6..."
npx wrangler d1 execute eicc-content --remote --command "INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.reviewed', 'de', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.reviewed', 'de', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.reviewed', 'de', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.reviewed', 'de', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.reviewed', 'de', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.reviewed', 'de', 'true');"

echo "Batch 2/6..."
npx wrangler d1 execute eicc-content --remote --command "INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.reviewed', 'de', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.language', 'de', 'de'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.label', 'de', 'Deutsch'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewed', 'de', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewedNote', 'de', 'Mit KI-Unterstützung erstellte Übersetzung, freigegeben zur Veröffentlichung (Navigationsinhalte, keine Compliance-Daten).'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.reviewed', 'en', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.reviewed', 'en', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.reviewed', 'en', 'true');"

echo "Batch 3/6..."
npx wrangler d1 execute eicc-content --remote --command "INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.reviewed', 'en', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.reviewed', 'en', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.reviewed', 'en', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.reviewed', 'en', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.language', 'en', 'en'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.label', 'en', 'English'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewed', 'en', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewedNote', 'en', 'Source language — always considered authoritative.');"

echo "Batch 4/6..."
npx wrangler d1 execute eicc-content --remote --command "INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.reviewed', 'es', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.reviewed', 'es', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.reviewed', 'es', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.reviewed', 'es', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.reviewed', 'es', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.reviewed', 'es', 'true');"

echo "Batch 5/6..."
npx wrangler d1 execute eicc-content --remote --command "INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.reviewed', 'es', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.language', 'es', 'es'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.label', 'es', 'Español'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewed', 'es', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewedNote', 'es', 'Traducción generada con asistencia de IA, aprobada para publicación (contenido de navegación, no datos de cumplimiento).'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-certified-providers', '_meta.reviewed', 'fr', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-impact-of-mandate', '_meta.reviewed', 'fr', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-mandate-types', '_meta.reviewed', 'fr', 'true');"

echo "Batch 6/6..."
npx wrangler d1 execute eicc-content --remote --command "INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-preparing-for-mandate', '_meta.reviewed', 'fr', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('edu-types-of-provider', '_meta.reviewed', 'fr', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('feedback', '_meta.reviewed', 'fr', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('subscribe', '_meta.reviewed', 'fr', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.language', 'fr', 'fr'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.label', 'fr', 'Français'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewed', 'fr', 'true'); INSERT OR IGNORE INTO translations (namespace, key, lang, value) VALUES ('tracker', '_meta.reviewedNote', 'fr', 'Traduction générée avec assistance de l''IA, approuvée pour publication (contenu de navigation, pas de données de conformité).');"

echo "Done. Verifying final count..."
npx wrangler d1 execute eicc-content --remote --command "SELECT COUNT(*) FROM translations;"
